[
  {
    "id": 661,
    "level": "beginner",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "What is Accessibility?",
    "question": "What does 'a11y' stand for in web development?",
    "code_snippet": null,
    "options": ["A JavaScript library", "Accessibility (the '11' represents the 11 letters between 'a' and 'y')", "A CSS layout method", "A type of web server"],
    "correct_answer": "Accessibility (the '11' represents the 11 letters between 'a' and 'y')",
    "explanation": "Just like i18n stands for internationalization, a11y is a numeronym for accessibility. It refers to designing and developing websites so that people with disabilities (visual, auditory, motor, or cognitive) can perceive, understand, navigate, and interact with the web."
  },
  {
    "id": 662,
    "level": "beginner",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Semantic HTML",
    "question": "Why is using semantic HTML (like `<nav>`, `<main>`, `<article>`) the most critical step in web accessibility?",
    "code_snippet": null,
    "options": ["It makes the CSS load faster", "It provides built-in meaning and structure that screen readers and assistive technologies can understand natively, without needing extra ARIA attributes", "It prevents JavaScript errors", "It automatically fixes color contrast"],
    "correct_answer": "It provides built-in meaning and structure that screen readers and assistive technologies can understand natively, without needing extra ARIA attributes",
    "explanation": "A `<button>` already tells the screen reader 'I am clickable'. A `<div onclick='...'>` requires you to manually add ARIA roles, keyboard handlers, and focus styles to achieve the exact same thing. Always use the right HTML element first."
  },
  {
    "id": 663,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Landmark Regions",
    "question": "What are 'Landmark Regions' in HTML, and how do they help screen reader users?",
    "code_snippet": null,
    "options": ["They are CSS classes that change the background color", "They are semantic elements (like `<header>`, `<nav>`, `<main>`, `<footer>`) that allow screen reader users to quickly jump between major sections of the page", "They are hidden elements used for SEO", "They are special tags that only work in Safari"],
    "correct_answer": "They are semantic elements (like `<header>`, `<nav>`, `<main>`, `<footer>`) that allow screen reader users to quickly jump between major sections of the page",
    "explanation": "Just like sighted users scan a page visually, screen reader users use landmarks to navigate. They can press a shortcut key to jump directly to the `<main>` content, bypassing the header and navigation entirely."
  },
  {
    "id": 664,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "First Rule of ARIA",
    "question": "What is the 'First Rule of ARIA' (Accessible Rich Internet Applications)?",
    "code_snippet": null,
    "options": ["Always add ARIA roles to every div", "If you can use a native HTML element with the semantics and behavior you require, do that instead of using ARIA", "ARIA attributes must be written in uppercase", "ARIA is only for images"],
    "correct_answer": "If you can use a native HTML element with the semantics and behavior you require, do that instead of using ARIA",
    "explanation": "Native HTML elements come with built-in keyboard interactions and screen reader announcements. 'No ARIA is better than bad ARIA.' Only use ARIA when native HTML falls short (like for complex custom widgets)."
  },
  {
    "id": 665,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "topic": "aria-hidden",
    "question": "Fill in the blank to correctly hide a decorative icon (like a FontAwesome star) from screen readers so it doesn't announce 'image' or 'icon' unnecessarily.",
    "code_snippet": "<span class='icon-star' _______='true'></span>",
    "options": ["aria-hidden", "aria-visible", "screen-reader", "display"],
    "correct_answer": "aria-hidden",
    "explanation": "`aria-hidden='true'` completely removes the element and its children from the accessibility tree. Screen readers will act as if the element does not exist in the DOM."
  },
  {
    "id": 666,
    "level": "beginner",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Alt Text",
    "question": "What is the purpose of the `alt` attribute on an `<img>` tag?",
    "code_snippet": null,
    "options": ["To provide a tooltip when the user hovers over the image", "To provide a text alternative for screen readers, and to display text if the image fails to load", "To set the title of the image in the database", "To change the file format of the image"],
    "correct_answer": "To provide a text alternative for screen readers, and to display text if the image fails to load",
    "explanation": "Every informative image MUST have an `alt` attribute. If the image conveys meaning (like a chart or a photo of a product), the `alt` text must describe that meaning concisely."
  },
  {
    "id": 667,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "question": "How do you correctly mark an image as purely decorative so screen readers skip it entirely?",
    "code_snippet": "<img src='decorative-line.png' _______>",
    "options": ["alt='decorative'", "alt=''", "alt='none'", "skip='true'"],
    "correct_answer": "alt=''",
    "explanation": "An empty `alt` attribute (`alt=''`) tells the screen reader to ignore the image completely. Writing `alt='decorative'` is incorrect because the screen reader will literally announce the word 'decorative' to the user."
  },
  {
    "id": 668,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Color Contrast",
    "question": "According to WCAG 2.1 AA standards, what is the minimum contrast ratio required for normal body text against its background?",
    "code_snippet": null,
    "options": ["2:1", "3:1", "4.5:1", "7:1"],
    "correct_answer": "4.5:1",
    "explanation": "Normal text requires a 4.5:1 contrast ratio. Large text (typically 18pt or 14pt bold) only requires 3:1. AAA compliance (the highest standard) requires 7:1 for normal text."
  },
  {
    "id": 669,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Color Alone",
    "question": "Why is it an accessibility violation to use color alone to convey information (e.g., 'Click the red button to delete')?",
    "code_snippet": null,
    "options": ["Red is an ugly color", "Users with color vision deficiencies (color blindness) may not be able to distinguish the red button from the background or other buttons", "It makes the CSS file larger", "It slows down the browser"],
    "correct_answer": "Users with color vision deficiencies (color blindness) may not be able to distinguish the red button from the background or other buttons",
    "explanation": "Always pair color with another visual indicator. Instead of just a red button, use a red button WITH an icon (like a trash can) and clear text ('Delete')."
  },
  {
    "id": 670,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Focus Indicators",
    "question": "Why is it a severe accessibility violation to use `outline: none;` on focused elements without providing a custom alternative?",
    "code_snippet": null,
    "options": ["It makes the page load slower", "It completely removes the visual focus ring, making it impossible for keyboard-only users to see where they are on the page", "It breaks the CSS cascade", "It disables the element"],
    "correct_answer": "It completely removes the visual focus ring, making it impossible for keyboard-only users to see where they are on the page",
    "explanation": "Keyboard users rely entirely on the focus indicator to navigate. If you remove the default outline for aesthetic reasons, you MUST replace it with a highly visible custom focus style (like a thick box-shadow or border)."
  },
  {
    "id": 671,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "topic": "Focus Visible",
    "question": "Fill in the blank with the modern pseudo-class that shows a focus ring ONLY when the user is navigating via keyboard, hiding it when they click with a mouse.",
    "code_snippet": ".button:_______ {\n  outline: 3px solid blue;\n}",
    "options": ["focus", "focus-visible", "active", "keyboard"],
    "correct_answer": "focus-visible",
    "explanation": "`:focus-visible` uses browser heuristics to determine if the user needs a focus ring. Mouse users won't see an ugly blue outline when clicking a button, but keyboard users will see it when tabbing."
  },
  {
    "id": 672,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "tabindex values",
    "question": "What is the difference between `tabindex='0'` and `tabindex='-1'`?",
    "code_snippet": null,
    "options": ["There is no difference", "`tabindex='0'` adds the element to the natural tab order; `tabindex='-1'` removes it from the tab order but allows it to be focused programmatically via JavaScript", "`tabindex='-1'` adds it to the tab order; `tabindex='0'` removes it", "`tabindex='0'` makes it unclickable"],
    "correct_answer": "`tabindex='0'` adds the element to the natural tab order; `tabindex='-1'` removes it from the tab order but allows it to be focused programmatically via JavaScript",
    "explanation": "Use `tabindex='0'` to make a custom widget (like a `<div role='button'>`) focusable. Use `tabindex='-1'` on things like dropdown menu items so they can be focused by arrow keys via JS, but skipped by the standard Tab key."
  },
  {
    "id": 673,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Skip Navigation",
    "question": "What is a 'Skip Navigation' link?",
    "code_snippet": null,
    "options": ["A link that bypasses the server", "A hidden link at the very top of the page that allows keyboard users to jump directly to the `<main>` content, bypassing repetitive navigation menus", "A link that disables CSS", "A link that opens a new tab"],
    "correct_answer": "A hidden link at the very top of the page that allows keyboard users to jump directly to the `<main>` content, bypassing repetitive navigation menus",
    "explanation": "Tabbing through a 15-item navigation menu on every single page is exhausting for keyboard users. A 'Skip to Main Content' link (usually hidden until focused) solves this instantly."
  },
  {
    "id": 674,
    "level": "beginner",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "topic": "Form Labels",
    "question": "Fill in the blank to correctly associate a text label with an input field so screen readers announce the label when the input is focused.",
    "code_snippet": "<_______ for='email'>Email Address</label>\n<input type='email' id='email'>",
    "options": ["text", "label", "name", "caption"],
    "correct_answer": "label",
    "explanation": "The `<label>` element, linked via the `for` attribute matching the input's `id`, is the only correct way to name a form field. Clicking the label also focuses the input, which is a great UX bonus."
  },
  {
    "id": 675,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "aria-describedby",
    "question": "How do you associate a helper text or error message with a form input so a screen reader reads it?",
    "code_snippet": null,
    "options": ["Use `aria-label`", "Use `aria-describedby` pointing to the ID of the helper text element", "Use `alt` text", "Use `title` attribute"],
    "correct_answer": "Use `aria-describedby` pointing to the ID of the helper text element",
    "explanation": "`aria-label` replaces the name of the element. `aria-describedby` appends additional descriptive text (like 'Password must be 8 characters') to the element's announcement."
  },
  {
    "id": 676,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Heading Hierarchy",
    "question": "Why is it an accessibility violation to skip heading levels (e.g., going from `<h2>` directly to `<h4>`)?",
    "code_snippet": null,
    "options": ["It makes the text too small", "It breaks the logical document outline, confusing screen reader users who rely on headings to navigate the page structure", "It causes a CSS syntax error", "It slows down the browser"],
    "correct_answer": "It breaks the logical document outline, confusing screen reader users who rely on headings to navigate the page structure",
    "explanation": "Headings create a table of contents for the page. Skipping levels is like skipping chapters in a book. If you need a smaller heading visually, use CSS to change the font-size, not the HTML tag."
  },
  {
    "id": 677,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The role attribute",
    "question": "What does the `role` attribute do in HTML?",
    "code_snippet": null,
    "options": ["It changes the visual styling of the element", "It explicitly tells assistive technologies what the purpose of an element is (e.g., `role='alert'`, `role='navigation'`)", "It assigns CSS variables", "It links to a JavaScript file"],
    "correct_answer": "It explicitly tells assistive technologies what the purpose of an element is (e.g., `role='alert'`, `role='navigation'`)",
    "explanation": "ARIA roles override the implicit semantics of an element. However, remember the first rule: if a native `<nav>` or `<button>` exists, use that instead of `<div role='navigation'>`."
  },
  {
    "id": 678,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Keyboard Interaction",
    "question": "By standard web convention, which keys should activate a `<button>` element?",
    "code_snippet": null,
    "options": ["Only the Spacebar", "Only the Enter key", "Both the Enter key and the Spacebar", "The Tab key"],
    "correct_answer": "Both the Enter key and the Spacebar",
    "explanation": "Native `<button>` elements fire their click event on both Enter and Space. (Note: Native `<a>` links only fire on Enter. This is why using the correct HTML element is crucial for expected keyboard behavior!)."
  },
  {
    "id": 679,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "aria-live Regions",
    "question": "What is the purpose of an `aria-live='polite'` region?",
    "code_snippet": null,
    "options": ["To hide content from screen readers", "To create a region where dynamic content updates (like a success message or a loading spinner) are automatically announced by the screen reader without the user having to focus it", "To play audio", "To translate text"],
    "correct_answer": "To create a region where dynamic content updates (like a success message or a loading spinner) are automatically announced by the screen reader without the user having to focus it",
    "explanation": "If JavaScript updates a `<div>` to say 'Form submitted successfully', a screen reader won't know it changed unless that `<div>` has `aria-live='polite'`. The screen reader will gently announce the new text when it's done with its current task."
  },
  {
    "id": 680,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Screen Reader Basics",
    "question": "How does a screen reader primarily interpret a webpage?",
    "code_snippet": null,
    "options": ["It takes a screenshot and reads the pixels", "It reads the DOM tree linearly from top to bottom, announcing the semantic roles, names, and states of the elements it encounters", "It only reads the text inside `<p>` tags", "It reads the CSS file first"],
    "correct_answer": "It reads the DOM tree linearly from top to bottom, announcing the semantic roles, names, and states of the elements it encounters",
    "explanation": "Screen readers rely entirely on the Accessibility Tree (which is generated from the DOM). If your HTML is semantic and your ARIA is correct, the screen reader will provide a perfect audio representation of your UI."
  }
]
[
  {
    "id": 681,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Focus Trapping",
    "question": "What is 'Focus Trapping' in the context of a modal or dialog box?",
    "code_snippet": null,
    "options": ["Preventing the user from closing the modal", "Restricting the keyboard Tab focus strictly to the elements inside the open modal, preventing the user from tabbing into the background page content", "Hiding the modal on mobile devices", "Disabling the Escape key"],
    "correct_answer": "Restricting the keyboard Tab focus strictly to the elements inside the open modal, preventing the user from tabbing into the background page content",
    "explanation": "If a modal is open but the user can Tab into the background page, the screen reader and keyboard focus become completely disconnected from the visual UI. Focus trapping ensures the user's context remains locked to the modal until it is closed."
  },
  {
    "id": 682,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Native <dialog> Element",
    "question": "Why is the native HTML `<dialog>` element heavily preferred over building custom modals with `<div>` and JavaScript?",
    "code_snippet": null,
    "options": ["It loads faster", "It automatically handles focus trapping, blocks background scrolling, closes on the Escape key, and creates a native backdrop, providing perfect accessibility out-of-the-box", "It allows CSS animations", "It prevents XSS attacks"],
    "correct_answer": "It automatically handles focus trapping, blocks background scrolling, closes on the Escape key, and creates a native backdrop, providing perfect accessibility out-of-the-box",
    "explanation": "Building an accessible modal from scratch is notoriously difficult. The `<dialog>` element (opened via `.showModal()`) gives you all the complex keyboard and screen reader behaviors for free."
  },
  {
    "id": 683,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "topic": "aria-modal",
    "question": "If you must build a custom modal without the native `<dialog>` tag, which ARIA attribute tells screen readers that the rest of the page is inert and should be ignored?",
    "code_snippet": "<div class='custom-modal' _______='true' role='dialog'>\n  ...\n</div>",
    "options": ["aria-hidden", "aria-modal", "aria-inert", "aria-block"],
    "correct_answer": "aria-modal",
    "explanation": "`aria-modal='true'` tells assistive technologies that content outside this dialog is temporarily hidden. (Note: You still have to manually implement focus trapping and background inertness via JS/CSS)."
  },
  {
    "id": 684,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Accessible Tables (<caption>)",
    "question": "What is the purpose of the `<caption>` tag inside an HTML `<table>`?",
    "code_snippet": null,
    "options": ["To style the table headers", "To provide a visible title or description of the table's data, which screen readers announce when the user enters the table", "To add a footer to the table", "To merge cells together"],
    "correct_answer": "To provide a visible title or description of the table's data, which screen readers announce when the user enters the table",
    "explanation": "Just like an image needs `alt` text, a complex data table needs a `<caption>` so a screen reader user knows what the table is about before they start navigating its rows and columns."
  },
  {
    "id": 685,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to explicitly tell a screen reader that a `<th>` element represents the header for a specific COLUMN.",
    "code_snippet": "<th _______='col'>Name</th>",
    "options": ["type", "scope", "role", "header"],
    "correct_answer": "scope",
    "explanation": "The `scope='col'` (or `scope='row'`) attribute programmatically links the header cell to its corresponding data cells. This allows screen readers to announce 'Name: Alice' instead of just reading 'Alice' out of context."
  },
  {
    "id": 686,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Accessible SVGs",
    "question": "How do you provide an accessible name to an inline `<svg>` icon so a screen reader knows what it represents?",
    "code_snippet": null,
    "options": ["Use the `alt` attribute on the `<svg>` tag", "Add a `<title>` element as the first child inside the `<svg>`, and reference it using `aria-labelledby`", "Use the `name` attribute", "SVGs are automatically read by screen readers"],
    "correct_answer": "Add a `<title>` element as the first child inside the `<svg>`, and reference it using `aria-labelledby`",
    "explanation": "Unlike `<img>`, SVGs do not support the `alt` attribute. You must use `<title id='icon-search'>Search</title>` inside the SVG, and apply `aria-labelledby='icon-search'` to the `<svg>` tag itself."
  },
  {
    "id": 687,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly assign the 'image' role to an inline SVG, ensuring screen readers treat it as a single graphic rather than a group of shapes.",
    "code_snippet": "<svg _______='img' aria-labelledby='title'>\n  <title id='title'>Logo</title>\n</svg>",
    "options": ["role", "type", "display", "mode"],
    "correct_answer": "role",
    "explanation": "By default, screen readers might try to read every individual `<path>` or `<circle>` inside an SVG. Adding `role='img'` collapses it into a single, clean image announcement."
  },
  {
    "id": 688,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Cognitive Accessibility",
    "question": "What does 'Cognitive Accessibility' focus on?",
    "code_snippet": null,
    "options": ["Making the website load faster for the brain", "Ensuring the interface is easy to understand, navigate, and use for people with learning disabilities, ADHD, dementia, or language barriers", "Translating the text into multiple languages", "Increasing the font size to 100px"],
    "correct_answer": "Ensuring the interface is easy to understand, navigate, and use for people with learning disabilities, ADHD, dementia, or language barriers",
    "explanation": "Cognitive a11y involves using clear language, consistent navigation, predictable layouts, and avoiding distracting animations or auto-playing media that could overwhelm or confuse the user."
  },
  {
    "id": 689,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "aria-invalid",
    "question": "When a user submits a form with an invalid email address, which ARIA attribute should be dynamically added to the input to alert screen readers?",
    "code_snippet": null,
    "options": ["aria-error='true'", "aria-invalid='true'", "aria-wrong='true'", "aria-fail='true'"],
    "correct_answer": "aria-invalid='true'",
    "explanation": "`aria-invalid='true'` tells the screen reader that the current value of the field does not match the expected format. It is usually paired with `aria-describedby` to point to the specific error message."
  },
  {
    "id": 690,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "aria-current",
    "question": "How do you indicate to a screen reader which link in a navigation menu represents the page the user is currently on?",
    "code_snippet": null,
    "options": ["Add a `.active` CSS class", "Use `aria-current='page'` on the active `<a>` tag", "Change the link color to red", "Use `aria-selected='true'`"],
    "correct_answer": "Use `aria-current='page'` on the active `<a>` tag",
    "explanation": "`aria-current='page'` (or 'step', 'location', etc.) is the semantic way to indicate the current item in a set. Screen readers will announce something like 'Home, current page'."
  },
  {
    "id": 691,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "aria-expanded",
    "question": "What is the purpose of the `aria-expanded` attribute on an accordion or dropdown toggle?",
    "code_snippet": null,
    "options": ["It animates the dropdown", "It tells screen readers whether the controlled content panel is currently visible (true) or hidden (false)", "It prevents the user from clicking it twice", "It changes the CSS display property"],
    "correct_answer": "It tells screen readers whether the controlled content panel is currently visible (true) or hidden (false)",
    "explanation": "Without `aria-expanded`, a screen reader user has no idea if clicking the 'Menu' button actually opened the menu. Toggling this attribute between 'true' and 'false' provides crucial state feedback."
  },
  {
    "id": 692,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The .sr-only Pattern",
    "question": "What is the `.sr-only` (or `.visually-hidden`) CSS class used for?",
    "code_snippet": null,
    "options": ["Hiding elements from screen readers", "Hiding elements visually using CSS (via clipping/positioning) while keeping them fully accessible and readable by screen readers", "Making text transparent", "Disabling the element"],
    "correct_answer": "Hiding elements visually using CSS (via clipping/positioning) while keeping them fully accessible and readable by screen readers",
    "explanation": "Sometimes you need to add extra context for screen readers that sighted users don't need to see (like 'Read more about our company' instead of just 'Read more'). The `.sr-only` class hides it visually without using `display: none` (which hides it from screen readers too)."
  },
  {
    "id": 693,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank with the standard CSS technique to create a `.sr-only` class that hides text visually but keeps it in the accessibility tree.",
    "code_snippet": ".sr-only {\n  position: absolute;\n  width: 1px; height: 1px;\n  padding: 0; margin: -1px;\n  overflow: hidden;\n  _______: rect(0, 0, 0, 0);\n  white-space: nowrap;\n  border: 0;\n}",
    "options": ["display", "visibility", "clip", "opacity"],
    "correct_answer": "clip",
    "explanation": "The `clip: rect(0 0 0 0)` (or the modern `clip-path: inset(50%)`) collapses the element to a 1x1 pixel box off-screen. It is invisible to the eye, but still exists in the DOM for screen readers."
  },
  {
    "id": 694,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly attach a closed-caption (`.vtt`) file to an HTML5 `<video>` element.",
    "code_snippet": "<video src='movie.mp4'>\n  <_______ kind='captions' src='captions.en.vtt' srclang='en'>\n</video>",
    "options": ["caption", "subtitle", "track", "src"],
    "correct_answer": "track",
    "explanation": "The `<track>` element is used to specify timed text tracks (like captions or subtitles) for media elements. It allows users to toggle captions on and off natively in the browser's video controls."
  },
  {
    "id": 695,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Captions vs Transcripts",
    "question": "What is the difference between Captions and a Transcript for an audio/video file?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "Captions are synchronized with the media timeline and include speaker IDs/sound effects; a Transcript is a static, text-only document of the audio provided alongside the media", "Transcripts are for video, Captions are for audio", "Captions are only in English"],
    "correct_answer": "Captions are synchronized with the media timeline and include speaker IDs/sound effects; a Transcript is a static, text-only document of the audio provided alongside the media",
    "explanation": "Captions (via `<track>`) are for Deaf/HoH users watching the video. Transcripts are beneficial for Deaf/HoH users, but also for blind users, non-native speakers, and SEO."
  },
  {
    "id": 696,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Automated Testing Limits",
    "question": "Tools like Lighthouse or Axe can automatically detect many accessibility violations. Approximately what percentage of total a11y issues can automated tools catch?",
    "code_snippet": null,
    "options": ["100%", "About 50-70%", "Only about 30-40%", "0%"],
    "correct_answer": "Only about 30-40%",
    "explanation": "Automated tools are great at catching missing `alt` attributes, low contrast, or missing form labels. But they CANNOT tell if an `alt` tag is actually descriptive, if the tab order makes logical sense, or if a modal traps focus correctly. Manual testing is mandatory."
  },
  {
    "id": 697,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Manual Testing (Keyboard Only)",
    "question": "What is the most critical manual accessibility test every developer must perform before shipping a feature?",
    "code_snippet": null,
    "options": ["Viewing the site on a mobile phone", "Unplugging their mouse and navigating the entire feature using ONLY the Tab, Shift+Tab, Enter, Space, and Escape keys", "Running a Lighthouse audit", "Checking the site in Incognito mode"],
    "correct_answer": "Unplugging their mouse and navigating the entire feature using ONLY the Tab, Shift+Tab, Enter, Space, and Escape keys",
    "explanation": "If you can't operate your dropdown, modal, or custom button using only a keyboard, it is completely inaccessible to motor-impaired users and screen reader users. This 5-minute test catches massive bugs."
  },
  {
    "id": 698,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Target Size (WCAG 2.5.8)",
    "question": "According to the latest WCAG 2.2 guidelines, what is the minimum recommended 'Target Size' for clickable elements (like buttons or links) to ensure they are easy to tap for users with motor tremors?",
    "code_snippet": null,
    "options": ["10x10 CSS pixels", "24x24 CSS pixels", "100x100 CSS pixels", "There is no size requirement"],
    "correct_answer": "24x24 CSS pixels",
    "explanation": "WCAG 2.2 introduced a strict rule that interactive targets must be at least 24x24 CSS pixels. (The older AAA standard recommended 44x44, but 24x24 is the new baseline minimum for AA compliance)."
  },
  {
    "id": 699,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Contrast for UI Components",
    "question": "While text requires a 4.5:1 contrast ratio, what is the minimum contrast ratio required for non-text UI components (like the border of an input field or a solid icon) against its adjacent colors?",
    "code_snippet": null,
    "options": ["1.5:1", "3:1", "4.5:1", "7:1"],
    "correct_answer": "3:1",
    "explanation": "WCAG requires a 3:1 contrast ratio for UI components and graphical objects. This ensures that a user with low vision can clearly see the boundaries of a button or input field, even if they can't read the text inside it."
  },
  {
    "id": 700,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The Philosophy of A11y",
    "question": "What is the ultimate philosophy of Web Accessibility?",
    "code_snippet": null,
    "options": ["It is a legal checkbox to avoid lawsuits", "Accessibility is not a feature for a minority; it is the foundation of good UX. Features like keyboard navigation, high contrast, clear focus states, and semantic HTML ultimately make the web faster, more robust, and easier to use for EVERYONE", "It only applies to government websites", "It requires disabling JavaScript"],
    "correct_answer": "Accessibility is not a feature for a minority; it is the foundation of good UX. Features like keyboard navigation, high contrast, clear focus states, and semantic HTML ultimately make the web faster, more robust, and easier to use for EVERYONE",
    "explanation": "The 'Curb Cut Effect' proves this: ramps were built for wheelchairs, but they are used by people with strollers, bikes, and delivery carts. Accessibility features (like captions, dark mode, and voice control) end up being loved by all users."
  }
]
[
  {
    "id": 701,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The 'inert' Attribute",
    "question": "What does the modern HTML `inert` attribute do when applied to a container?",
    "code_snippet": null,
    "options": ["It hides the element visually", "It completely disables the element and all its children from receiving focus, click events, or being read by screen readers, acting as a native 'freeze' switch", "It makes the element read-only", "It prevents the element from being printed"],
    "correct_answer": "It completely disables the element and all its children from receiving focus, click events, or being read by screen readers, acting as a native 'freeze' switch",
    "explanation": "The `inert` attribute is a game-changer for modals and sidebars. Instead of manually writing JavaScript to hide background elements from screen readers and block clicks, you simply add the `inert` attribute to the background container."
  },
  {
    "id": 702,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Shadow DOM Focus (delegatesFocus)",
    "question": "When creating a Web Component with Shadow DOM, how do you ensure that clicking the component or tabbing to it focuses its first internal input field?",
    "code_snippet": null,
    "options": ["You cannot focus inside Shadow DOM", "By attaching the shadow root with `{ delegatesFocus: true }`, which forwards focus from the host element to the first focusable internal element", "By using `tabindex='0'` on the host", "By using CSS `:focus`"],
    "correct_answer": "By attaching the shadow root with `{ delegatesFocus: true }`, which forwards focus from the host element to the first focusable internal element",
    "explanation": "`delegatesFocus: true` is essential for building accessible custom elements like `<my-search-bar>`. It ensures that keyboard and mouse users interact with the component naturally, without needing to know about the Shadow DOM boundary."
  },
  {
    "id": 703,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Accessible Carousels (ARIA)",
    "question": "What is the correct ARIA pattern for a standard image carousel/slider?",
    "code_snippet": null,
    "options": ["Use `role='carousel'` on the container", "Use `role='region'` with `aria-roledescription='carousel'`, and `role='group'` with `aria-roledescription='slide'` for each panel", "Use `role='slider'` on the images", "Carousels cannot be made accessible"],
    "correct_answer": "Use `role='region'` with `aria-roledescription='carousel'`, and `role='group'` with `aria-roledescription='slide'` for each panel",
    "explanation": "Screen readers don't have a native 'carousel' announcement. By using `aria-roledescription`, you tell the screen reader to say 'Carousel, region' and 'Slide 2 of 5', providing crucial context to non-visual users."
  },
  {
    "id": 704,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Accessible Carousels (Keyboard)",
    "question": "According to W3C ARIA Authoring Practices, how should a user navigate between slides in a carousel using a keyboard?",
    "code_snippet": null,
    "options": ["Using the Tab key to move to the next slide", "Using the Left/Right Arrow keys to move between slides, while Tab moves to the next interactive control (like 'Next' buttons or links inside the slide)", "Using the Spacebar", "Using the Enter key"],
    "correct_answer": "Using the Left/Right Arrow keys to move between slides, while Tab moves to the next interactive control (like 'Next' buttons or links inside the slide)",
    "explanation": "If a carousel has 10 slides and you use the Tab key to navigate them, the user has to press Tab 10 times just to get past the widget. Arrow keys allow rapid navigation within the widget, keeping the Tab order clean."
  },
  {
    "id": 705,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Accessible Tooltips",
    "question": "What are the two mandatory requirements for making a custom CSS/JS tooltip accessible?",
    "code_snippet": null,
    "options": ["It must be colored blue and have a border", "It must be triggered by BOTH hover (mouse) AND focus (keyboard), and the tooltip content must be linked via `aria-describedby`", "It must use `position: absolute`", "It must have a `title` attribute"],
    "correct_answer": "It must be triggered by BOTH hover (mouse) AND focus (keyboard), and the tooltip content must be linked via `aria-describedby`",
    "explanation": "If a tooltip only appears on `:hover`, keyboard users will never see it. Furthermore, the tooltip text must be programmatically associated with the trigger element so screen readers announce it."
  },
  {
    "id": 706,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Drag and Drop Accessibility",
    "question": "If your application relies heavily on Drag-and-Drop (like a Kanban board), what is the mandatory accessibility requirement?",
    "code_snippet": null,
    "options": ["You must increase the size of the draggable items", "You must provide a complete keyboard alternative (e.g., using 'Move' buttons or Arrow keys) to achieve the exact same result without a mouse", "You must disable drag-and-drop on mobile", "You must use HTML5 native drag events"],
    "correct_answer": "You must provide a complete keyboard alternative (e.g., using 'Move' buttons or Arrow keys) to achieve the exact same result without a mouse",
    "explanation": "Native HTML5 drag-and-drop is notoriously inaccessible to keyboard and touch users. You must always provide a parallel, non-mouse workflow (like a 'Move to...' dropdown) for motor-impaired users."
  },
  {
    "id": 707,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Target Size Spacing (WCAG 2.5.8)",
    "question": "According to WCAG 2.2, if a clickable target is smaller than 24x24 CSS pixels, what is the requirement to ensure it doesn't cause accidental clicks?",
    "code_snippet": null,
    "options": ["It must be hidden on mobile", "It must have sufficient empty space around it so that it does not overlap with any other conflicting target's 24x24 bounding box", "It must have a thicker border", "It must be animated"],
    "correct_answer": "It must have sufficient empty space around it so that it does not overlap with any other conflicting target's 24x24 bounding box",
    "explanation": "If you have tiny social media icons in a footer, they can be smaller than 24x24px AS LONG AS they are spaced far enough apart that a user's finger (or a 24x24 hit box) won't accidentally trigger the wrong icon."
  },
  {
    "id": 708,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Data Visualization (Charts)",
    "question": "How do you make a complex, interactive D3.js or Chart.js data visualization accessible?",
    "code_snippet": null,
    "options": ["You cannot make charts accessible", "Provide a visually hidden, standard HTML `<table>` containing the exact same raw data used to generate the chart", "Use `alt` text on the `<canvas>` tag", "Add `aria-label='chart'`"],
    "correct_answer": "Provide a visually hidden, standard HTML `<table>` containing the exact same raw data used to generate the chart",
    "explanation": "Screen readers cannot interpret a `<canvas>` or SVG chart natively. Providing the underlying data in a semantic, `.sr-only` HTML table ensures blind users have access to the exact same information."
  },
  {
    "id": 709,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Cognitive A11y (Autocomplete)",
    "question": "How does the HTML `autocomplete` attribute (e.g., `autocomplete='email'`) aid cognitive accessibility?",
    "code_snippet": null,
    "options": ["It translates the text", "It allows the browser to auto-fill known user data (like names/addresses), reducing memory burden and typing effort for users with cognitive or motor disabilities", "It checks for spelling errors", "It prevents the user from typing"],
    "correct_answer": "It allows the browser to auto-fill known user data (like names/addresses), reducing memory burden and typing effort for users with cognitive or motor disabilities",
    "explanation": "WCAG 1.3.5 (Identify Input Purpose) requires `autocomplete` on relevant fields. It helps users with memory impairments, dyslexia, or motor tremors complete forms quickly and error-free."
  },
  {
    "id": 710,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Focus Not Obscured (WCAG 2.5.14)",
    "question": "What does the new WCAG 2.5.14 'Focus Not Obscured' criterion require?",
    "code_snippet": null,
    "options": ["Focus rings must be blue", "When an element receives focus, it must not be completely hidden behind sticky headers, footers, or floating sidebars", "Focus must be trapped in modals", "Focus must animate smoothly"],
    "correct_answer": "When an element receives focus, it must not be completely hidden behind sticky headers, footers, or floating sidebars",
    "explanation": "If a user tabs to a link at the top of the page, but a `position: sticky` header covers it, the user has no idea what they are focused on. You must use `scroll-padding-top` or JS to ensure focused elements scroll into clear view."
  },
  {
    "id": 711,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Seizure Safety (WCAG 2.3.1)",
    "question": "To comply with WCAG 2.3.1 (Three Flashes or Below Threshold), what must you avoid in CSS animations?",
    "code_snippet": null,
    "options": ["Using the color red", "Any content that flashes or alternates in brightness/color more than 3 times in any one-second period", "Using `opacity` transitions", "Using `transform: scale()`"],
    "correct_answer": "Any content that flashes or alternates in brightness/color more than 3 times in any one-second period",
    "explanation": "Rapid flashing can trigger photosensitive epileptic seizures. If your design requires a flashing alert, it must be small, low-contrast, or easily pausable."
  },
  {
    "id": 712,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Accessible Name Computation",
    "question": "If an element has a visible `<label>`, an `aria-label`, and a `title` attribute, which one does the screen reader use as the 'Accessible Name'?",
    "code_snippet": null,
    "options": ["The `title` attribute", "The `aria-label` attribute", "The visible `<label>` (via `aria-labelledby` or native association)", "It reads all three"],
    "correct_answer": "The visible `<label>` (via `aria-labelledby` or native association)",
    "explanation": "The Accessible Name Computation algorithm dictates a strict priority. Native HTML labels (or `aria-labelledby`) take precedence over `aria-label`, which takes precedence over `title`. Always prioritize visible, native labels."
  },
  {
    "id": 713,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The 'title' Attribute",
    "question": "Why is the HTML `title` attribute (which creates native browser tooltips) generally discouraged for critical accessibility information?",
    "code_snippet": null,
    "options": ["It makes the page load slower", "It is inaccessible to keyboard-only users (requires hover), and screen reader support for it is highly inconsistent and often disabled by default", "It is deprecated in HTML5", "It causes CSS conflicts"],
    "correct_answer": "It is inaccessible to keyboard-only users (requires hover), and screen reader support for it is highly inconsistent and often disabled by default",
    "explanation": "Never put critical information in a `title` attribute. If a user needs to know what an icon does, use `aria-label` or a visually hidden `<span>` instead."
  },
  {
    "id": 714,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "role='alert' vs aria-live",
    "question": "What is the difference between `role='alert'` and `aria-live='polite'`?",
    "code_snippet": null,
    "options": ["There is no difference", "`role='alert'` is equivalent to `aria-live='assertive'` and interrupts the screen reader immediately; `aria-live='polite'` waits until the screen reader is idle before announcing", "`role='alert'` is for errors, `aria-live` is for success", "`aria-live` is deprecated"],
    "correct_answer": "`role='alert'` is equivalent to `aria-live='assertive'` and interrupts the screen reader immediately; `aria-live='polite'` waits until the screen reader is idle before announcing",
    "explanation": "Use `role='alert'` sparingly for critical errors or system failures. Use `aria-live='polite'` for non-urgent updates like 'Item added to cart' or search results loading."
  },
  {
    "id": 715,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Descriptive Link Text",
    "question": "Why is using 'Click Here' or 'Read More' as link text considered a severe accessibility failure?",
    "code_snippet": null,
    "options": ["It is too short", "Screen reader users often navigate by pulling up a list of all links on the page; a list of 20 'Click Here' links provides zero context about the destination", "It is bad for SEO", "It violates color contrast rules"],
    "correct_answer": "Screen reader users often navigate by pulling up a list of all links on the page; a list of 20 'Click Here' links provides zero context about the destination",
    "explanation": "Always use descriptive link text like 'Read more about our accessibility policy'. If you must use 'Read More' visually, use the `.sr-only` pattern to append the context for screen readers."
  },
  {
    "id": 716,
    "level": "beginner",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The 'lang' Attribute",
    "question": "Why is the `<html lang='en'>` attribute mandatory for accessibility?",
    "code_snippet": null,
    "options": ["It is required for CSS to load", "It tells the screen reader which language pronunciation rules and braille character sets to use", "It translates the page automatically", "It improves SEO"],
    "correct_answer": "It tells the screen reader which language pronunciation rules and braille character sets to use",
    "explanation": "Without the `lang` attribute, a screen reader might try to read English text using a French pronunciation engine, resulting in completely garbled, unintelligible audio."
  },
  {
    "id": 717,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Page Title",
    "question": "What is the first piece of information a screen reader announces when a user lands on a new webpage?",
    "code_snippet": null,
    "options": ["The main heading (`<h1>`)", "The `<title>` tag content in the `<head>` of the document", "The URL of the page", "The meta description"],
    "correct_answer": "The `<title>` tag content in the `<head>` of the document",
    "explanation": "The page title is the equivalent of a book's cover title. It must be unique, descriptive, and clearly state the current page's purpose (e.g., 'Checkout - Cart Review | MyStore')."
  },
  {
    "id": 718,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Testing Methodology",
    "question": "What is the industry-standard 'Three-Pronged' approach to accessibility testing?",
    "code_snippet": null,
    "options": ["Chrome, Firefox, Safari", "Automated tools (Axe/Lighthouse), Manual Keyboard Testing, and Testing with actual Assistive Technology (Screen Readers)", "HTML, CSS, JS", "Design, Development, QA"],
    "correct_answer": "Automated tools (Axe/Lighthouse), Manual Keyboard Testing, and Testing with actual Assistive Technology (Screen Readers)",
    "explanation": "Automated tools catch ~40% of errors. Manual keyboard testing catches interaction and focus bugs. Screen reader testing (using NVDA, VoiceOver, or JAWS) is the only way to verify the actual auditory experience."
  },
  {
    "id": 719,
    "level": "intermediate",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "Screen Reader Tools",
    "question": "Which of the following is a free, open-source screen reader for Windows that developers should use for testing?",
    "code_snippet": null,
    "options": ["JAWS", "NVDA (NonVisual Desktop Access)", "VoiceOver", "TalkBack"],
    "correct_answer": "NVDA (NonVisual Desktop Access)",
    "explanation": "JAWS is expensive. VoiceOver is Mac/iOS only. TalkBack is Android only. NVDA is free, open-source, and the standard for testing the Windows web experience."
  },
  {
    "id": 720,
    "level": "advanced",
    "module_id": "css_mod_10_accessibility",
    "module_name": "Accessibility (a11y) & Best Practices",
    "type": "conceptual",
    "topic": "The Complete CSS Journey",
    "question": "You have now completed the entire CSS curriculum (from basic selectors to advanced accessibility). What is the ultimate mark of a Senior Frontend Developer?",
    "code_snippet": null,
    "options": ["Memorizing every CSS property", "The ability to build interfaces that are not only visually stunning, highly performant, and scalable, but fundamentally inclusive and accessible to every single human being on the planet", "Writing code without any comments", "Using only the newest, experimental CSS features"],
    "correct_answer": "The ability to build interfaces that are not only visually stunning, highly performant, and scalable, but fundamentally inclusive and accessible to every single human being on the planet",
    "explanation": "CSS is not just about making things look pretty. It is about communication, resilience, and empathy. By mastering the cascade, layout, architecture, and accessibility, you have the power to build a web that truly works for everyone. Congratulations on completing the curriculum!"
  }
]
