[
  {
    "id": 401,
    "level": "beginner",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Basics",
    "question": "What is the core philosophy of 'Responsive Web Design' (RWD)?",
    "code_snippet": null,
    "options": ["Building separate websites for mobile and desktop", "Creating a single website that fluidly adapts its layout, images, and typography to fit any screen size or device", "Only supporting screens larger than 1024px", "Using JavaScript to detect the device and reload the page"],
    "correct_answer": "Creating a single website that fluidly adapts its layout, images, and typography to fit any screen size or device",
    "explanation": "Coined by Ethan Marcotte in 2010, RWD relies on fluid grids, flexible images, and media queries to ensure one codebase serves phones, tablets, laptops, and ultra-wide monitors perfectly."
  },
  {
    "id": 402,
    "level": "beginner",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Viewport Meta Tag",
    "question": "Fill in the blank to correctly add the essential viewport meta tag to the `<head>` of an HTML document for mobile responsiveness.",
    "code_snippet": "<head>\n  <meta name='_______' content='width=device-width, initial-scale=1.0'>\n</head>",
    "options": ["screen", "viewport", "display", "mobile"],
    "correct_answer": "viewport",
    "explanation": "The `<meta name='viewport'>` tag tells the mobile browser not to simulate a 980px desktop screen and zoom out. It forces the browser to match the CSS viewport width to the actual physical device width."
  },
  {
    "id": 403,
    "level": "beginner",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Viewport Meta Tag",
    "question": "What happens if you FORGET to include the viewport meta tag on a modern smartphone?",
    "code_snippet": null,
    "options": ["The page will not load", "The browser will render the page as if it were on a ~980px wide desktop screen, making all your text and UI elements appear tiny and requiring the user to pinch-to-zoom", "The page will automatically switch to dark mode", "The CSS Grid will break"],
    "correct_answer": "The browser will render the page as if it were on a ~980px wide desktop screen, making all your text and UI elements appear tiny and requiring the user to pinch-to-zoom",
    "explanation": "To maintain compatibility with older, non-responsive websites, mobile browsers default to a 'virtual viewport' of ~980px. The meta tag is the explicit instruction to stop doing this."
  },
  {
    "id": 404,
    "level": "beginner",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Media Query Syntax",
    "question": "Fill in the blank to correctly write a media query that applies styles ONLY when the screen is 768px wide or smaller.",
    "code_snippet": "@_______ (max-width: 768px) {\n  .sidebar { display: none; }\n}",
    "options": ["screen", "media", "query", "device"],
    "correct_answer": "media",
    "explanation": "The `@media` at-rule is the foundation of responsive CSS. It allows you to conditionally apply a block of CSS only if the device matches the specified criteria (like width, height, or orientation)."
  },
  {
    "id": 405,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Mobile-First vs Desktop-First",
    "question": "What does a 'Mobile-First' approach to CSS mean?",
    "code_snippet": null,
    "options": ["Writing CSS exclusively for mobile phones", "Writing the base CSS for the smallest screens first, and using `min-width` media queries to progressively enhance the layout for larger screens", "Using `max-width` media queries to hide elements on desktop", "Building the mobile app before the website"],
    "correct_answer": "Writing the base CSS for the smallest screens first, and using `min-width` media queries to progressively enhance the layout for larger screens",
    "explanation": "Mobile-first forces you to prioritize core content and performance. Your base CSS is lightweight, and you only add complex layouts (like multi-column grids) when the screen is large enough to handle them."
  },
  {
    "id": 406,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Mobile-First Syntax",
    "question": "Fill in the blank to correctly write a Mobile-First media query that applies styles when the screen is AT LEAST 1024px wide.",
    "code_snippet": "@media (_______: 1024px) {\n  .container { max-width: 960px; margin: 0 auto; }\n}",
    "options": ["max-width", "min-width", "exact-width", "device-width"],
    "correct_answer": "min-width",
    "explanation": "In a mobile-first workflow, your base styles apply to 0px and up. You use `min-width` to say, 'Once the screen reaches 1024px, apply these desktop enhancements'."
  },
  {
    "id": 407,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Breakpoints",
    "question": "What is a 'breakpoint' in responsive design?",
    "code_snippet": null,
    "options": ["A syntax error in CSS", "A specific screen width where the layout changes significantly, triggering a media query", "The point where the browser crashes", "The maximum width of an image"],
    "correct_answer": "A specific screen width where the layout changes significantly, triggering a media query",
    "explanation": "Common breakpoints target phones (e.g., 480px), tablets (e.g., 768px), and desktops (e.g., 1024px+). However, modern best practice suggests adding breakpoints exactly where your specific content starts to look broken, rather than targeting specific devices."
  },
  {
    "id": 408,
    "level": "beginner",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to ensure an `<img>` never exceeds the width of its parent container, preventing horizontal scrollbars on mobile.",
    "code_snippet": "img {\n  _______: 100%;\n  height: auto;\n}",
    "options": ["max-width", "width", "min-width", "flex-basis"],
    "correct_answer": "max-width",
    "explanation": "Setting `max-width: 100%` allows the image to be its natural size on large screens, but forces it to shrink proportionally to fit inside smaller containers. `height: auto` maintains the aspect ratio."
  },
  {
    "id": 409,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Images",
    "question": "If you need a responsive image to completely fill a 400x400 square container without distorting its aspect ratio (cropping the edges if necessary), which property should you use?",
    "code_snippet": null,
    "options": ["max-width: 100%", "object-fit: cover", "background-size: contain", "resize: both"],
    "correct_answer": "object-fit: cover",
    "explanation": "`object-fit: cover` tells the image to maintain its aspect ratio while filling the entire content box. Any parts of the image that spill outside the box are cropped. (Use `contain` if you want to see the whole image without cropping)."
  },
  {
    "id": 410,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "srcset and picture",
    "question": "Why is the HTML `<picture>` element (or the `srcset` attribute) crucial for modern responsive performance?",
    "code_snippet": null,
    "options": ["It makes images load faster on desktop", "It allows the browser to download a completely different, smaller image file for mobile devices, saving massive amounts of bandwidth and memory", "It automatically converts images to SVG", "It adds a drop shadow to images"],
    "correct_answer": "It allows the browser to download a completely different, smaller image file for mobile devices, saving massive amounts of bandwidth and memory",
    "explanation": "Using CSS to shrink a 4000px wide desktop image down to a 400px mobile screen wastes massive bandwidth. The `<picture>` element lets you serve a 400px file to mobile and a 2000px file to desktop."
  },
  {
    "id": 411,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Fluid Typography",
    "question": "What is 'Fluid Typography' in CSS?",
    "code_snippet": null,
    "options": ["Using only em units", "Scaling font sizes smoothly and proportionally based on the viewport width, without needing media query breakpoints", "Using only the `px` unit", "Changing fonts based on the user's language"],
    "correct_answer": "Scaling font sizes smoothly and proportionally based on the viewport width, without needing media query breakpoints",
    "explanation": "Instead of text jumping from 16px to 20px at a specific breakpoint, fluid typography scales continuously as the user resizes the browser window, providing a much smoother reading experience."
  },
  {
    "id": 412,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Fluid Typography (clamp)",
    "question": "Fill in the blank to create a fluid heading that is AT LEAST 24px, scales with the viewport width, but NEVER exceeds 48px.",
    "code_snippet": "h1 {\n  font-size: _______(24px, 5vw, 48px);\n}",
    "options": ["min", "max", "clamp", "calc"],
    "correct_answer": "clamp",
    "explanation": "`clamp(minimum, preferred, maximum)` is the ultimate responsive function. It sets a hard floor (24px), a fluid middle (5vw), and a hard ceiling (48px). It completely replaces the need for media queries for typography."
  },
  {
    "id": 413,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to apply a dark background and light text if the user's operating system is set to Dark Mode.",
    "code_snippet": "@media (prefers-_______: dark) {\n  body { background: #121212; color: #fff; }\n}",
    "options": ["theme", "color-scheme", "mode", "dark-mode"],
    "correct_answer": "color-scheme",
    "explanation": "The `prefers-color-scheme` media feature detects the user's OS-level preference. It allows your website to seamlessly respect the user's desire for a dark or light interface."
  },
  {
    "id": 414,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Accessibility (prefers-reduced-motion)",
    "question": "What is the purpose of the `@media (prefers-reduced-motion: reduce)` query?",
    "code_snippet": null,
    "options": ["To speed up animations for faster computers", "To detect users who experience motion sickness or vestibular disorders, allowing you to disable or simplify CSS animations and transitions", "To reduce the file size of CSS", "To pause video elements"],
    "correct_answer": "To detect users who experience motion sickness or vestibular disorders, allowing you to disable or simplify CSS animations and transitions",
    "explanation": "This is a critical accessibility feature. If a user has toggled 'Reduce Motion' in their OS settings, this media query allows you to set `animation: none` or `transition: none` to prevent causing them physical discomfort."
  },
  {
    "id": 415,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Interaction Media Features",
    "question": "Why is it important to use `@media (hover: hover)` before applying complex `:hover` states (like massive dropdown menus)?",
    "code_snippet": null,
    "options": ["It makes the hover state animate smoother", "It ensures the hover state only applies to devices with a real mouse pointer, preventing 'sticky' hover bugs on touch-screen devices", "It increases the click area", "It is required by HTML5"],
    "correct_answer": "It ensures the hover state only applies to devices with a real mouse pointer, preventing 'sticky' hover bugs on touch-screen devices",
    "explanation": "On touch screens, there is no 'hover'. Tapping an element with a `:hover` state often triggers the hover state and 'sticks' it, requiring the user to tap elsewhere to dismiss it. `@media (hover: hover)` restricts hover effects to actual mice/trackpads."
  },
  {
    "id": 416,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to apply a specific cursor and style ONLY if the user has a precise pointing device (like a mouse), rather than a thick finger on a touch screen.",
    "code_snippet": "@media (_______: fine) {\n  .tiny-button { width: 24px; height: 24px; }\n}",
    "options": ["pointer", "cursor", "device", "touch"],
    "correct_answer": "pointer",
    "explanation": "The `pointer` media feature checks the precision of the primary input mechanism. `fine` means a mouse/trackpad (allowing tiny click targets). `coarse` means a touch screen (requiring larger, finger-friendly tap targets like 44x44px)."
  },
  {
    "id": 417,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Container Queries",
    "question": "What is the fundamental difference between a Media Query and a Container Query?",
    "code_snippet": null,
    "options": ["There is no difference", "Media queries respond to the viewport (browser window) size; Container queries respond to the size of a specific parent component/container", "Container queries are for Flexbox, Media queries are for Grid", "Media queries are deprecated"],
    "correct_answer": "Media queries respond to the viewport (browser window) size; Container queries respond to the size of a specific parent component/container",
    "explanation": "Media queries ask, 'How wide is the browser window?' Container queries ask, 'How wide is the card I am placed inside?' This allows components to be truly modular and responsive, regardless of where they are placed on the page."
  },
  {
    "id": 418,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly define a parent element as a queryable container for its children.",
    "code_snippet": ".card-wrapper {\n  _______: inline-size;\n}",
    "options": ["container-type", "query-type", "media-type", "responsive"],
    "correct_answer": "container-type",
    "explanation": "To use container queries, you MUST first establish a containment context. `container-type: inline-size` tells the browser to track the horizontal width of this specific element so children can query it."
  },
  {
    "id": 419,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to write a Container Query that changes the card's layout to a row if its parent container is wider than 400px.",
    "code_snippet": "@_______ (min-width: 400px) {\n  .card { flex-direction: row; }\n}",
    "options": ["media", "container", "query", "component"],
    "correct_answer": "container",
    "explanation": "The `@container` at-rule works exactly like `@media`, but it evaluates the width of the nearest ancestor that has `container-type` defined, rather than the browser viewport."
  },
  {
    "id": 420,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Media Query Source Order",
    "question": "If you have two media queries with the EXACT same specificity and conditions (e.g., two `@media (min-width: 768px)` blocks targeting the same element), which one wins?",
    "code_snippet": null,
    "options": ["The first one in the CSS file", "The last one in the CSS file (Source Order)", "The one with the highest pixel value", "They merge together"],
    "correct_answer": "The last one in the CSS file (Source Order)",
    "explanation": "Just like standard CSS, if specificity and conditions are perfectly tied, the rule that appears later in the stylesheet overrides the earlier one. This is why organizing your mobile-first media queries from smallest `min-width` to largest is crucial."
  }
]
[
  {
    "id": 421,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Media Query Logic (AND)",
    "question": "How do you write a media query that applies styles ONLY if the screen is at least 768px wide AND the device is in landscape orientation?",
    "code_snippet": null,
    "options": ["@media (min-width: 768px) + (orientation: landscape)", "@media (min-width: 768px) and (orientation: landscape)", "@media (min-width: 768px) & (orientation: landscape)", "@media (min-width: 768px, landscape)"],
    "correct_answer": "@media (min-width: 768px) and (orientation: landscape)",
    "explanation": "The `and` keyword is used to combine multiple media features into a single query. ALL conditions must be true for the CSS block to apply."
  },
  {
    "id": 422,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Media Query Logic (OR)",
    "question": "How do you write a media query that applies styles if the screen is EITHER in portrait mode OR has a max-width of 600px?",
    "code_snippet": null,
    "options": ["@media (orientation: portrait) or (max-width: 600px)", "@media (orientation: portrait) | (max-width: 600px)", "@media (orientation: portrait), (max-width: 600px)", "@media (orientation: portrait) + (max-width: 600px)"],
    "correct_answer": "@media (orientation: portrait), (max-width: 600px)",
    "explanation": "In CSS Media Queries, a comma (`,`) acts as the logical OR operator. If either the portrait condition OR the max-width condition is met, the styles will apply."
  },
  {
    "id": 423,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Media Query Logic (NOT)",
    "question": "What does the `not` keyword do in a media query like `@media not print { ... }`?",
    "code_snippet": null,
    "options": ["It applies the styles only when printing", "It negates the media query, applying the styles to everything EXCEPT the print media type", "It throws a syntax error", "It reverses the colors for printing"],
    "correct_answer": "It negates the media query, applying the styles to everything EXCEPT the print media type",
    "explanation": "The `not` keyword is used to negate a media type or feature. `@media not print` means 'apply these styles on screens, but hide them when the user prints the page'."
  },
  {
    "id": 424,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Media Queries Level 4 (Range Syntax)",
    "question": "Fill in the blank to correctly use the modern CSS Media Queries Level 4 'Range Syntax' to target screens 768px and wider.",
    "code_snippet": "@media (_______ >= 768px) {\n  .sidebar { display: block; }\n}",
    "options": ["min-width", "width", "screen-width", "device-width"],
    "correct_answer": "width",
    "explanation": "Level 4 allows mathematical range syntax. Instead of the clunky `min-width: 768px`, you can simply write `(width >= 768px)`. It is much more readable and intuitive."
  },
  {
    "id": 425,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Media Queries Level 4 (Chained Ranges)",
    "question": "What does the following modern media query do? `@media (400px <= width <= 800px)`",
    "code_snippet": null,
    "options": ["It targets screens exactly 600px wide", "It targets screens that are between 400px and 800px wide, inclusive", "It throws a syntax error because you can't chain ranges", "It targets screens smaller than 400px or larger than 800px"],
    "correct_answer": "It targets screens that are between 400px and 800px wide, inclusive",
    "explanation": "Level 4 allows you to chain inequalities. This completely replaces the old, messy `@media (min-width: 400px) and (max-width: 800px)` syntax."
  },
  {
    "id": 426,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Safe Area Insets (Notches)",
    "question": "Which CSS function is used to access the safe area insets (like the iPhone notch or home indicator) to prevent content from being obscured?",
    "code_snippet": null,
    "options": ["var()", "calc()", "env()", "attr()"],
    "correct_answer": "env()",
    "explanation": "The `env()` function accesses environment variables set by the user agent. `padding-bottom: env(safe-area-inset-bottom)` ensures your fixed bottom navigation bar doesn't get hidden behind the iPhone's home swipe indicator."
  },
  {
    "id": 427,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Safe Area Meta Tag",
    "question": "Fill in the blank in the viewport meta tag to enable the use of `env(safe-area-inset-*)` values in your CSS.",
    "code_snippet": "<meta name='viewport' content='width=device-width, initial-scale=1.0, _______=cover'>",
    "options": ["viewport-fit", "safe-area", "notch-mode", "display-mode"],
    "correct_answer": "viewport-fit",
    "explanation": "By default, the browser draws the viewport inside the safe area. Setting `viewport-fit=cover` tells the browser to extend the viewport into the notches and rounded corners, which then allows you to use `env()` to manually pad your content away from the danger zones."
  },
  {
    "id": 428,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Spacing Systems",
    "question": "How can you create a fully fluid spacing system (margins/padding) that scales with the screen without writing dozens of media queries?",
    "code_snippet": null,
    "options": ["Use only `px` units", "Define CSS custom properties (variables) using `clamp()` for your spacing scale (e.g., `--space-md: clamp(1rem, 2vw, 2rem)`)", "Use JavaScript to calculate margins", "Use `width: 100%` on all margins"],
    "correct_answer": "Define CSS custom properties (variables) using `clamp()` for your spacing scale (e.g., `--space-md: clamp(1rem, 2vw, 2rem)`)",
    "explanation": "By combining CSS variables with `clamp()`, you create a 'fluid' design token system. Your padding and margins will smoothly scale from mobile to desktop automatically, eliminating breakpoint jumps."
  },
  {
    "id": 429,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Container Query Units",
    "question": "Fill in the blank to set an element's width to 50% of its nearest Container Query ancestor's width (not the viewport).",
    "code_snippet": ".child {\n  width: 50_______;\n}",
    "options": ["vw", "cqw", "pw", "cw"],
    "correct_answer": "cqw",
    "explanation": "Container Query Units (`cqw`, `cqh`, `cqi`, `cqb`) are relative to the dimensions of the queried container, not the viewport. `50cqw` means 50% of the container's inline-size."
  },
  {
    "id": 430,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Named Container Queries",
    "question": "Why is it highly recommended to NAME your container queries (e.g., `container-name: card`) instead of relying on the default nearest ancestor?",
    "code_snippet": null,
    "options": ["It makes the CSS load faster", "It prevents the child component from accidentally querying the wrong ancestor container if it gets nested deeper in the DOM later", "It is required by the CSS specification", "It allows the container to be queried by JavaScript"],
    "correct_answer": "It prevents the child component from accidentally querying the wrong ancestor container if it gets nested deeper in the DOM later",
    "explanation": "If you use `@container (min-width: 400px)`, it queries the *nearest* ancestor. If a developer later wraps your component in another container, it will break. Naming it (`@container card (min-width: 400px)`) ensures it always targets the exact right parent."
  },
  {
    "id": 431,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Container Style Queries",
    "question": "What is the cutting-edge 'Container Style Query' feature in CSS?",
    "code_snippet": null,
    "options": ["Querying the container's background color", "Allowing a child component to change its styles based on the CSS Custom Properties (variables) applied to its parent container, rather than just its size", "Querying the container's HTML tag name", "It is a JavaScript API"],
    "correct_answer": "Allowing a child component to change its styles based on the CSS Custom Properties (variables) applied to its parent container, rather than just its size",
    "explanation": "Using `@container style(--theme: dark)`, a child component can adapt its internal styles based on the theme or state variables of its parent, enabling truly context-aware, modular components!"
  },
  {
    "id": 432,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Tables",
    "question": "What is the most common, accessible CSS technique for handling wide data tables on small mobile screens?",
    "code_snippet": null,
    "options": ["Hiding the table completely", "Wrapping the table in a container with `overflow-x: auto` to allow horizontal scrolling", "Using `display: none` on every other column", "Converting the table to a Flexbox row"],
    "correct_answer": "Wrapping the table in a container with `overflow-x: auto` to allow horizontal scrolling",
    "explanation": "Tables represent structured data. Hiding columns or breaking them apart ruins the data relationship. Wrapping them in a scrollable container preserves the data integrity while allowing mobile users to swipe horizontally."
  },
  {
    "id": 433,
    "level": "beginner",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Print Media Queries",
    "question": "Fill in the blank to correctly hide the main navigation bar when the user prints the webpage.",
    "code_snippet": "@media _______ {\n  nav { display: none; }\n}",
    "options": ["screen", "print", "paper", "output"],
    "correct_answer": "print",
    "explanation": "The `print` media type targets the document when it is being printed or viewed in print preview. It's best practice to hide interactive elements (nav, buttons, video) and optimize typography for ink."
  },
  {
    "id": 434,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "High DPI / Retina Displays",
    "question": "Fill in the blank to serve a high-resolution background image ONLY to devices with a pixel ratio of 2 or higher (Retina displays).",
    "code_snippet": "@media (min-_______: 2dppx) {\n  .logo { background-image: url('logo@2x.png'); }\n}",
    "options": ["pixel-ratio", "resolution", "dpi", "density"],
    "correct_answer": "resolution",
    "explanation": "The modern standard for targeting high-DPI screens is `min-resolution: 2dppx` (dots per pixel). (The legacy vendor-prefixed version was `-webkit-min-device-pixel-ratio: 2`)."
  },
  {
    "id": 435,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Color Gamut (P3)",
    "question": "What does the `@media (color-gamut: p3)` query allow you to do?",
    "code_snippet": null,
    "options": ["Change the page to black and white", "Apply ultra-vibrant, wide-gamut colors (like `color(display-p3 1 0 0)`) ONLY to devices with screens that physically support the Display P3 color space", "Reduce the color palette for accessibility", "Convert all images to PNG"],
    "correct_answer": "Apply ultra-vibrant, wide-gamut colors (like `color(display-p3 1 0 0)`) ONLY to devices with screens that physically support the Display P3 color space",
    "explanation": "Standard sRGB monitors cannot display certain ultra-vivid colors. `color-gamut: p3` ensures you only use these next-gen colors on modern Apple/Android flagship screens that can actually render them, falling back to sRGB for older monitors."
  },
  {
    "id": 436,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Forced Colors Mode",
    "question": "What is the purpose of `@media (forced-colors: active)`?",
    "code_snippet": null,
    "options": ["To force the browser to use dark mode", "To detect when the OS has forced a high-contrast color palette (like Windows High Contrast), allowing you to remove custom backgrounds/borders so the system colors can take over", "To force the user to accept cookies", "To lock the color palette to grayscale"],
    "correct_answer": "To detect when the OS has forced a high-contrast color palette (like Windows High Contrast), allowing you to remove custom backgrounds/borders so the system colors can take over",
    "explanation": "Users with visual impairments often use OS-level forced colors. If you don't use this media query to strip out your custom CSS backgrounds and borders, your site might become completely unreadable in their high-contrast mode."
  },
  {
    "id": 437,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Inverted Colors",
    "question": "What does `@media (inverted-colors: inverted)` detect?",
    "code_snippet": null,
    "options": ["When the user is using Dark Mode", "When the user or OS has inverted all colors on the screen (often for light sensitivity), allowing you to pre-invert images so they appear normal", "When the screen is upside down", "When the monitor is in portrait mode"],
    "correct_answer": "When the user or OS has inverted all colors on the screen (often for light sensitivity), allowing you to pre-invert images so they appear normal",
    "explanation": "If the OS inverts colors, a normal photo becomes a creepy negative. By detecting `inverted-colors`, you can apply `filter: invert(1)` to images, which cancels out the OS inversion, showing the photo correctly!"
  },
  {
    "id": 438,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Debugging",
    "question": "What is the most efficient way to test responsive breakpoints and touch interactions during development without needing a physical phone?",
    "code_snippet": null,
    "options": ["Guessing the screen sizes", "Using the 'Device Mode' / 'Responsive Design Mode' in browser DevTools (Chrome/Safari) to simulate viewports, touch events, and throttled network speeds", "Writing JavaScript to resize the window", "Asking a friend to test it on their phone"],
    "correct_answer": "Using the 'Device Mode' / 'Responsive Design Mode' in browser DevTools (Chrome/Safari) to simulate viewports, touch events, and throttled network speeds",
    "explanation": "Browser DevTools allow you to drag the viewport to any size, simulate specific device dimensions (like iPhone 14 or Galaxy S20), emulate touch-screen hover states, and throttle the CPU/Network to test real-world performance."
  },
  {
    "id": 439,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Dynamic Viewport Units (dvh)",
    "question": "Why is `100dvh` (Dynamic Viewport Height) considered the ultimate fix for the '100vh mobile bug'?",
    "code_snippet": null,
    "options": ["It loads the page faster", "It dynamically recalculates the viewport height in real-time as the mobile browser's address bar and toolbars hide or show, preventing content from being cut off or causing scrollbars", "It forces the browser into fullscreen mode", "It disables the scrollbar"],
    "correct_answer": "It dynamically recalculates the viewport height in real-time as the mobile browser's address bar and toolbars hide or show, preventing content from being cut off or causing scrollbars",
    "explanation": "Standard `100vh` breaks on mobile because it includes the space hidden by the URL bar. `100dvh` updates continuously as the user scrolls and the UI expands/collapses, ensuring your layout is always perfectly sized."
  },
  {
    "id": 440,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The Future: Intrinsic Web Design",
    "question": "What is 'Intrinsic Web Design' and how does it relate to the future of responsive CSS?",
    "code_snippet": null,
    "options": ["Using only images for layouts", "Moving away from hardcoded breakpoints entirely, relying instead on intrinsic sizing (`minmax`, `auto-fit`, `clamp`) and Container Queries so the layout naturally adapts based on the available space and content", "Designing websites exclusively for VR headsets", "Using JavaScript to calculate layouts"],
    "correct_answer": "Moving away from hardcoded breakpoints entirely, relying instead on intrinsic sizing (`minmax`, `auto-fit`, `clamp`) and Container Queries so the layout naturally adapts based on the available space and content",
    "explanation": "The future of responsive design isn't about targeting specific devices (iPhone, iPad, Desktop). It's about creating fluid, intrinsic layouts that look perfect at ANY arbitrary width, from a smartwatch to an ultrawide monitor, without a single `@media` query."
  }
]
[
  {
    "id": 441,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Fluid Typography Math",
    "question": "Before the `clamp()` function existed, how did developers write fluid typography using `calc()` and viewport units?",
    "code_snippet": null,
    "options": ["font-size: calc(16px + 1vw);", "font-size: 16px + 1vw;", "font-size: calc(16px * 1vw);", "font-size: fluid(16px, 1vw);"],
    "correct_answer": "font-size: calc(16px + 1vw);",
    "explanation": "By adding a fixed pixel base (16px) to a fluid viewport unit (1vw), the text scales smoothly as the screen grows. However, this lacks a minimum and maximum cap, which is why `clamp()` is preferred today."
  },
  {
    "id": 442,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Fluid Typography Extremes",
    "question": "Why is using ONLY `vw` for font sizes (e.g., `font-size: 5vw;`) considered a bad practice?",
    "code_snippet": null,
    "options": ["It makes the text load slower", "On very small screens, the text becomes microscopically small and unreadable; on ultrawide monitors, it becomes massively huge and overwhelming", "It breaks the CSS cascade", "It only works in Chrome"],
    "correct_answer": "On very small screens, the text becomes microscopically small and unreadable; on ultrawide monitors, it becomes massively huge and overwhelming",
    "explanation": "Viewport units have no floor or ceiling. `clamp(16px, 5vw, 32px)` is the correct approach because it guarantees the text will never drop below 16px or exceed 32px, ensuring readability at all extremes."
  },
  {
    "id": 443,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Responsive Video Embeds",
    "question": "Fill in the blank to correctly make an `<iframe>` video embed perfectly responsive, maintaining a 16:9 aspect ratio without JavaScript.",
    "code_snippet": "iframe {\n  width: 100%;\n  _______: 16 / 9;\n}",
    "options": ["ratio", "aspect-ratio", "size-ratio", "video-ratio"],
    "correct_answer": "aspect-ratio",
    "explanation": "The modern `aspect-ratio` property is a game-changer for responsive media. It automatically calculates the height based on the width, eliminating the need for the old, messy 'padding-top percentage' hack."
  },
  {
    "id": 444,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Legacy Responsive Video Hack",
    "question": "Before `aspect-ratio` was supported, what was the standard CSS hack to create a responsive 16:9 video container?",
    "code_snippet": null,
    "options": ["Using `transform: scale()`", "Wrapping the video in a `div` with `height: 0`, `padding-top: 56.25%`, and `position: relative`, while the video was `position: absolute`", "Using `width: 16%` and `height: 9%`", "Using JavaScript to calculate the height on window resize"],
    "correct_answer": "Wrapping the video in a `div` with `height: 0`, `padding-top: 56.25%`, and `position: relative`, while the video was `position: absolute`",
    "explanation": "Because vertical percentage padding is calculated based on the parent's *width*, setting `padding-top: 56.25%` (which is 9/16) forced the container to maintain a 16:9 box regardless of screen size."
  },
  {
    "id": 445,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Touch Target Accessibility",
    "question": "According to WCAG and Apple/Google design guidelines, what is the minimum recommended touch target size for interactive elements (buttons, links) on mobile devices?",
    "code_snippet": null,
    "options": ["16x16 pixels", "24x24 pixels", "44x44 pixels (or 48x48 on Android)", "100x100 pixels"],
    "correct_answer": "44x44 pixels (or 48x48 on Android)",
    "explanation": "Human fingers are much less precise than mouse pointers. If a button is smaller than 44x44px, users will frequently experience 'fat finger' mis-taps, leading to extreme frustration."
  },
  {
    "id": 446,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to ensure a paragraph of text never exceeds 65 characters per line, which is the optimal length for readability on ultrawide monitors.",
    "code_snippet": "p {\n  max-width: 65_______;\n}",
    "options": ["px", "em", "ch", "vw"],
    "correct_answer": "ch",
    "explanation": "The `ch` unit is relative to the width of the '0' character in the current font. Setting `max-width: 65ch` guarantees the text block will always be exactly 65 characters wide, ensuring perfect readability regardless of screen size."
  },
  {
    "id": 447,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Browser Zoom & Units",
    "question": "What happens to `rem` and `em` units when a user zooms in on a webpage using their browser's native zoom feature (Ctrl/Cmd +)?",
    "code_snippet": null,
    "options": ["They stay the exact same pixel size", "They scale up proportionally, respecting the user's desire for larger text", "They shrink to compensate", "They throw a CSS error"],
    "correct_answer": "They scale up proportionally, respecting the user's desire for larger text",
    "explanation": "This is why `rem` and `em` are vastly superior to `px` for accessibility. If a visually impaired user zooms their browser to 150%, `rem`-based layouts will gracefully expand, whereas `px`-based layouts might break or remain too small."
  },
  {
    "id": 448,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "iOS Text Size Adjust",
    "question": "What does the `-webkit-text-size-adjust: 100%` property do on mobile Safari?",
    "code_snippet": null,
    "options": ["It makes all text bold", "It prevents iOS from automatically inflating font sizes when the user rotates the device from portrait to landscape", "It translates the text to English", "It disables the zoom feature entirely"],
    "correct_answer": "It prevents iOS from automatically inflating font sizes when the user rotates the device from portrait to landscape",
    "explanation": "Historically, iOS Safari would aggressively increase font sizes in landscape mode to make text readable. This often broke responsive layouts. Setting it to `100%` (or `none`) tells the browser to let your CSS handle the sizing."
  },
  {
    "id": 449,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The 100vh iOS Bug",
    "question": "Why does `height: 100vh` notoriously fail on mobile Safari (iOS), and what is the modern CSS fix?",
    "code_snippet": null,
    "options": ["It crashes the browser; use JavaScript instead", "Mobile Safari calculates `100vh` including the space hidden behind the URL bar, causing a scrollbar to appear; the fix is to use `100dvh` (Dynamic Viewport Height)", "It only works in landscape mode; use `100vw` instead", "It is blocked by Apple for security reasons"],
    "correct_answer": "Mobile Safari calculates `100vh` including the space hidden behind the URL bar, causing a scrollbar to appear; the fix is to use `100dvh` (Dynamic Viewport Height)",
    "explanation": "Because the URL bar hides/shows dynamically, a static `100vh` calculation results in content being pushed off-screen. `100dvh` updates in real-time as the browser UI expands and collapses."
  },
  {
    "id": 450,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Small vs Large Viewport",
    "question": "What is the difference between `100svh` (Small Viewport Height) and `100lvh` (Large Viewport Height)?",
    "code_snippet": null,
    "options": ["There is no difference", "`svh` assumes the browser UI is fully expanded (guaranteeing no scrollbars); `lvh` assumes the browser UI is completely hidden (maximum possible screen real estate)", "`svh` is for mobile, `lvh` is for desktop", "`lvh` is deprecated"],
    "correct_answer": "`svh` assumes the browser UI is fully expanded (guaranteeing no scrollbars); `lvh` assumes the browser UI is completely hidden (maximum possible screen real estate)",
    "explanation": "Use `svh` when you absolutely cannot have a scrollbar (like a modal). Use `lvh` when you want the element to be as massive as possible, even if it means the user has to scroll past the browser's URL bar to see the bottom."
  },
  {
    "id": 451,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Grid Last Row",
    "question": "When using CSS Grid `auto-fit` for a responsive card layout, what happens to the cards in the very last row if there are only 1 or 2 cards left?",
    "code_snippet": null,
    "options": ["They disappear", "They stretch to fill the entire row, becoming massively wider than the cards above them", "They wrap to the next page", "They throw an error"],
    "correct_answer": "They stretch to fill the entire row, becoming massively wider than the cards above them",
    "explanation": "Because `1fr` distributes *all* free space equally, 2 cards in the last row will each take up 50% of the screen. To fix this, developers often use `align-content: start` or switch to Flexbox for the specific card container."
  },
  {
    "id": 452,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The Zoom Trap",
    "question": "Why is adding `user-scalable=no` to the viewport meta tag considered a severe accessibility violation?",
    "code_snippet": null,
    "options": ["It makes the page load slower", "It prevents visually impaired users from pinching-to-zoom to read the text, effectively locking them out of the content", "It disables JavaScript", "It breaks CSS Grid"],
    "correct_answer": "It prevents visually impaired users from pinching-to-zoom to read the text, effectively locking them out of the content",
    "explanation": "Never use `user-scalable=no` or `maximum-scale=1`. Users with low vision rely entirely on browser zoom to navigate the web. Modern browsers actually ignore this tag now to protect users."
  },
  {
    "id": 453,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Line Height",
    "question": "Why is it recommended to use a unitless number for `line-height` (e.g., `line-height: 1.5`) instead of pixels or rems in responsive design?",
    "code_snippet": null,
    "options": ["It loads faster", "It acts as a multiplier of the element's current `font-size`, ensuring the spacing scales perfectly if the user zooms or if the font size changes via media queries", "It is required by HTML5", "It prevents text from wrapping"],
    "correct_answer": "It acts as a multiplier of the element's current `font-size`, ensuring the spacing scales perfectly if the user zooms or if the font size changes via media queries",
    "explanation": "If you set `line-height: 24px` and the font-size scales up to 20px via a media query, the text will overlap. `line-height: 1.5` guarantees the spacing will always be exactly 1.5x whatever the current font size is."
  },
  {
    "id": 454,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Scrollbar Jank",
    "question": "Why does a webpage sometimes 'jump' horizontally by about 15px when navigating between pages on desktop?",
    "code_snippet": null,
    "options": ["Because of a CSS syntax error", "Because one page has enough content to trigger a vertical scrollbar (reducing the viewport width), and the next page doesn't, causing the layout to reflow", "Because the browser is reloading the fonts", "Because of the `viewport` meta tag"],
    "correct_answer": "Because one page has enough content to trigger a vertical scrollbar (reducing the viewport width), and the next page doesn't, causing the layout to reflow",
    "explanation": "This is a classic responsive annoyance. The fix is to force the scrollbar to always be visible using `html { overflow-y: scroll; }`, ensuring the viewport width remains constant across all pages."
  },
  {
    "id": 455,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Container Queries Use Case",
    "question": "How do Container Queries solve the 'Sidebar Problem' in responsive design?",
    "code_snippet": null,
    "options": ["They hide the sidebar on mobile", "They allow a component (like a user profile card) to switch from a horizontal layout to a vertical layout based on the width of the sidebar it is placed inside, rather than the browser window", "They make the sidebar scrollable", "They convert the sidebar to a Flexbox"],
    "correct_answer": "They allow a component (like a user profile card) to switch from a horizontal layout to a vertical layout based on the width of the sidebar it is placed inside, rather than the browser window",
    "explanation": "If you put a card in a 300px sidebar, and then move that same card to a 1200px main content area, Media Queries won't know the difference. Container Queries allow the card to say, 'If I have less than 400px of space, stack vertically'."
  },
  {
    "id": 456,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive vs Adaptive",
    "question": "What is the fundamental difference between 'Responsive Design' and 'Adaptive Design'?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "Responsive design uses fluid grids that continuously adapt to any screen size; Adaptive design uses static, fixed layouts snapped to specific, predefined device widths (like 320px, 768px, 1024px)", "Adaptive design is for mobile, Responsive is for desktop", "Responsive design requires JavaScript"],
    "correct_answer": "Responsive design uses fluid grids that continuously adapt to any screen size; Adaptive design uses static, fixed layouts snapped to specific, predefined device widths (like 320px, 768px, 1024px)",
    "explanation": "Responsive (popularized by Ethan Marcotte) is fluid and future-proof. Adaptive (often associated with older server-side device detection or rigid CSS pixel breakpoints) creates distinct layouts for specific devices, which breaks on new, unanticipated screen sizes."
  },
  {
    "id": 457,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Focus Visible on Touch",
    "question": "Why is the `:focus-visible` pseudo-class incredibly important for responsive design across devices?",
    "code_snippet": null,
    "options": ["It makes the page load faster", "It ensures keyboard users see a clear focus outline when tabbing, but hides that ugly outline when touch-screen users simply tap a button with their finger", "It prevents the keyboard from popping up on mobile", "It changes the cursor to a pointer"],
    "correct_answer": "It ensures keyboard users see a clear focus outline when tabbing, but hides that ugly outline when touch-screen users simply tap a button with their finger",
    "explanation": "Touch devices don't have a 'hover' or 'focus' state in the traditional sense. `:focus-visible` uses browser heuristics to only show the accessibility focus ring when it's actually needed (keyboard navigation), keeping the mobile UI clean."
  },
  {
    "id": 458,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Data Saver Mode",
    "question": "What does the `@media (save-data: on)` query detect?",
    "code_snippet": null,
    "options": ["When the user's battery is low", "When the user has enabled 'Data Saver' mode in their browser/OS, allowing you to hide heavy background images or auto-playing videos to save their cellular bandwidth", "When the user is on Wi-Fi", "When the server is saving data to the database"],
    "correct_answer": "When the user has enabled 'Data Saver' mode in their browser/OS, allowing you to hide heavy background images or auto-playing videos to save their cellular bandwidth",
    "explanation": "This is a fantastic performance and empathy feature. If a user is on a metered connection and has Data Saver on, you can use this query to serve a lightweight, text-only version of your site."
  },
  {
    "id": 459,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Scripting Media Feature",
    "question": "What does `@media (scripting: none)` allow you to do?",
    "code_snippet": null,
    "options": ["Disable JavaScript", "Apply specific CSS styles ONLY if the user has JavaScript disabled in their browser, acting as a modern replacement for the `<noscript>` HTML tag", "Detect if the user is using a screen reader", "Prevent CSS animations"],
    "correct_answer": "Apply specific CSS styles ONLY if the user has JavaScript disabled in their browser, acting as a modern replacement for the `<noscript>` HTML tag",
    "explanation": "This is an incredibly powerful, yet rarely used, media feature. It allows you to show a 'Please enable JavaScript' banner, or provide CSS-only fallback navigation menus, purely through CSS without needing `<noscript>` tags in the HTML."
  },
  {
    "id": 460,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The Ultimate Responsive Philosophy",
    "question": "What is the ultimate goal of modern Responsive Web Design?",
    "code_snippet": null,
    "options": ["To make the website look exactly the same on a smartwatch and a 4K TV", "To ensure the content is accessible, readable, and functional regardless of the device, screen size, input method, or user preferences", "To force all users to download the mobile app", "To eliminate the need for CSS Grid and Flexbox"],
    "correct_answer": "To ensure the content is accessible, readable, and functional regardless of the device, screen size, input method, or user preferences",
    "explanation": "Responsive design isn't about pixel-perfect replication across devices. It's about resilience. A truly responsive site adapts gracefully to a folded Galaxy Z Fold, a 32-inch ultrawide monitor, a user with a tremor using a keyboard, or someone browsing in bright sunlight."
  }
]
[
  {
    "id": 461,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The 100vw Scrollbar Bug",
    "question": "Why does applying `width: 100vw` to an element often cause an unwanted horizontal scrollbar on the page?",
    "code_snippet": null,
    "options": ["Because 100vw is an invalid unit", "Because `100vw` includes the width of the vertical scrollbar itself, so when the scrollbar appears, the element becomes wider than the viewport", "Because it triggers a media query", "Because it conflicts with CSS Grid"],
    "correct_answer": "Because `100vw` includes the width of the vertical scrollbar itself, so when the scrollbar appears, the element becomes wider than the viewport",
    "explanation": "The viewport width (`100vw`) is calculated including the scrollbar. If your content is tall enough to trigger a vertical scrollbar, `100vw` + the scrollbar width exceeds the available space, creating a horizontal scrollbar. The fix is usually to use `width: 100%` on the body, or `overflow-x: hidden`."
  },
  {
    "id": 462,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Sticky Hover Bug",
    "question": "What is the 'sticky hover' bug on touch-screen devices?",
    "code_snippet": null,
    "options": ["When a dropdown menu won't close", "When tapping an element with a `:hover` state triggers the hover effect, and it remains 'stuck' in that state until the user taps somewhere else", "When the screen gets stuck in landscape mode", "When the browser's back button stops working"],
    "correct_answer": "When tapping an element with a `:hover` state triggers the hover effect, and it remains 'stuck' in that state until the user taps somewhere else",
    "explanation": "Touch screens don't have a persistent 'hover' state. When you tap a link with a `:hover` background color change, the browser applies the hover state and leaves it there. Using `@media (hover: hover)` prevents this by only applying the hover styles to devices with a real mouse."
  },
  {
    "id": 463,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Print CSS (@page)",
    "question": "Fill in the blank to correctly set the physical margins of the printed page to 1 inch on all sides.",
    "code_snippet": "@_______ {\n  margin: 1in;\n}",
    "options": ["media print", "page", "print-layout", "document"],
    "correct_answer": "page",
    "explanation": "The `@page` at-rule is used specifically in print stylesheets to configure the dimensions, orientation, and margins of the physical paper page itself, separate from the HTML body margins."
  },
  {
    "id": 464,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "Print CSS (Page Breaks)",
    "question": "Fill in the blank to prevent a specific element (like a data table or an image) from being split across two separate printed pages.",
    "code_snippet": ".important-chart {\n  _______: avoid;\n}",
    "options": ["page-break", "break-inside", "split-page", "overflow"],
    "correct_answer": "break-inside",
    "explanation": "The `break-inside: avoid` property (or the legacy `page-break-inside: avoid`) tells the browser's print engine, 'Do not cut this element in half. If it doesn't fit on the current page, move the whole thing to the next page.'"
  },
  {
    "id": 465,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Fluid Box Shadows",
    "question": "How can you make a `box-shadow` scale proportionally as the screen size changes, without using media queries?",
    "code_snippet": null,
    "options": ["You cannot, shadows are fixed", "By using the `clamp()` function or viewport units inside the shadow's blur-radius and spread-radius values", "By using `box-shadow: auto`", "By applying `transform: scale()` to the shadow"],
    "correct_answer": "By using the `clamp()` function or viewport units inside the shadow's blur-radius and spread-radius values",
    "explanation": "You can write `box-shadow: 0 10px clamp(10px, 2vw, 30px) rgba(0,0,0,0.1)`. This ensures the shadow's softness scales fluidly with the viewport, keeping the design cohesive from mobile to desktop."
  },
  {
    "id": 466,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Tables (Card Layout)",
    "question": "What is a common CSS technique to transform a standard HTML data table into a stack of 'cards' on mobile screens?",
    "code_snippet": null,
    "options": ["Using `display: none` on the table", "Setting `tr` and `td` to `display: block`, and using the `::before` pseudo-element with the `attr()` function to inject column headers as labels", "Using `float: left` on the table", "Converting the table to an image"],
    "correct_answer": "Setting `tr` and `td` to `display: block`, and using the `::before` pseudo-element with the `attr()` function to inject column headers as labels",
    "explanation": "By hiding the `<th>` and making `<td>` block-level, each row becomes a vertical card. You can then use `td::before { content: attr(data-label); }` to pull the column name from a custom HTML data attribute, providing context for each piece of data."
  },
  {
    "id": 467,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "code-fill-in-blank",
    "topic": "The attr() function",
    "question": "Fill in the blank to correctly pull the value of an HTML `data-category` attribute and display it as CSS content.",
    "code_snippet": ".element::before {\n  content: _______(data-category);\n}",
    "options": ["var", "calc", "attr", "data"],
    "correct_answer": "attr",
    "explanation": "The `attr()` function in CSS allows you to read an HTML attribute and use it in your styles. While currently most reliably used with the `content` property, it's a powerful bridge between HTML data and CSS presentation."
  },
  {
    "id": 468,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Images (sizes attribute)",
    "question": "When using `srcset` on an `<img>` tag, what is the purpose of the `sizes` attribute?",
    "code_snippet": null,
    "options": ["It sets the CSS width of the image", "It tells the browser how wide the image will be displayed in the layout at different breakpoints, so the browser can pick the correct file resolution from `srcset`", "It compresses the image", "It sets the aspect ratio"],
    "correct_answer": "It tells the browser how wide the image will be displayed in the layout at different breakpoints, so the browser can pick the correct file resolution from `srcset`",
    "explanation": "Without `sizes`, the browser assumes the image will be 100vw wide. If your CSS actually displays the image at 50vw on desktop, `sizes='(max-width: 800px) 100vw, 50vw'` tells the browser to download a smaller, more efficient file for the desktop view."
  },
  {
    "id": 469,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Dynamic Viewport Units",
    "question": "What is the exact difference between `100svh`, `100lvh`, and `100dvh`?",
    "code_snippet": null,
    "options": ["They are just different syntaxes for the same thing", "`svh` assumes the browser UI is fully expanded (smallest viewport); `lvh` assumes the UI is completely hidden (largest viewport); `dvh` dynamically updates in real-time as the UI expands/collapses", "`svh` is for mobile, `lvh` is for desktop, `dvh` is for tablets", "`dvh` is deprecated"],
    "correct_answer": "`svh` assumes the browser UI is fully expanded (smallest viewport); `lvh` assumes the UI is completely hidden (largest viewport); `dvh` dynamically updates in real-time as the UI expands/collapses",
    "explanation": "These three units solve the mobile browser toolbar bug. Use `svh` to guarantee no scrollbars, `lvh` for maximum immersive height, and `dvh` for the best of both worlds that updates live as the user scrolls."
  },
  {
    "id": 470,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Orientation Media Feature",
    "question": "Which media feature evaluates to `portrait` when the viewport height is greater than or equal to the width?",
    "code_snippet": null,
    "options": ["aspect-ratio", "orientation", "layout", "direction"],
    "correct_answer": "orientation",
    "explanation": "`@media (orientation: portrait)` targets devices held vertically (or windows resized to be taller than they are wide). It's useful for switching from a multi-column layout to a single-column stack."
  },
  {
    "id": 471,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Container Query Fallbacks",
    "question": "How do you provide a fallback for browsers that do not yet support Container Queries?",
    "code_snippet": null,
    "options": ["You must use JavaScript", "Write the base mobile styles outside the `@container` block; unsupported browsers will simply ignore the `@container` block and render the base styles", "Use `@supports not (container-type: inline-size)`", "Container queries don't need fallbacks"],
    "correct_answer": "Write the base mobile styles outside the `@container` block; unsupported browsers will simply ignore the `@container` block and render the base styles",
    "explanation": "Because CSS naturally ignores rules it doesn't understand, progressive enhancement works perfectly. Define your default (mobile) layout first, then use `@container` to enhance it for larger components in modern browsers."
  },
  {
    "id": 472,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Fluid Borders",
    "question": "How can you create a border that gets visually thicker as the screen size increases, without using media queries?",
    "code_snippet": null,
    "options": ["Use `border-width: auto`", "Use viewport units or `clamp()` in the `border-width` property (e.g., `border-width: clamp(1px, 0.5vw, 5px)`)", "Use `border: thick`", "It is impossible"],
    "correct_answer": "Use viewport units or `clamp()` in the `border-width` property (e.g., `border-width: clamp(1px, 0.5vw, 5px)`)",
    "explanation": "Just like typography and spacing, borders can be fluid. Using `clamp()` ensures the border is at least 1px on mobile (for performance and crispness) but scales up to 5px on ultrawide monitors to maintain visual proportion."
  },
  {
    "id": 473,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Accessibility (Zooming & Grid)",
    "question": "What happens to a well-built CSS Grid layout when a visually impaired user zooms the browser to 200%?",
    "code_snippet": null,
    "options": ["The layout completely breaks and overlaps", "The grid tracks and items scale up proportionally, and the layout gracefully reflows to maintain readability without horizontal scrolling", "The grid converts to Flexbox", "The text stays the same size but the images grow"],
    "correct_answer": "The grid tracks and items scale up proportionally, and the layout gracefully reflows to maintain readability without horizontal scrolling",
    "explanation": "Because CSS Grid uses relative units and flexible tracks (`fr`), browser zoom acts just like resizing the window. The layout reflows gracefully, which is why Grid + `rem`/`em` is the gold standard for accessibility."
  },
  {
    "id": 474,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Animations",
    "question": "Why should you avoid animating `width`, `height`, `top`, or `left` in responsive CSS animations?",
    "code_snippet": null,
    "options": ["They are deprecated", "They trigger expensive layout recalculations (Reflows) on every frame, causing severe jank and battery drain; you should animate `transform` and `opacity` instead", "They don't work on mobile", "They cause the screen to flash"],
    "correct_answer": "They trigger expensive layout recalculations (Reflows) on every frame, causing severe jank and battery drain; you should animate `transform` and `opacity` instead",
    "explanation": "Animating geometric properties forces the browser to recalculate the layout of the entire page 60 times a second. `transform: translateX()` and `opacity` are handled by the GPU compositor thread, resulting in buttery smooth 60fps animations."
  },
  {
    "id": 475,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The 'ch' Unit for Readability",
    "question": "Why is the `ch` unit considered the ultimate tool for responsive typography readability?",
    "code_snippet": null,
    "options": ["It scales with the viewport width", "It is based on the width of the '0' character, allowing you to set a maximum line length (e.g., `max-width: 65ch`) that guarantees optimal reading comfort regardless of screen size or font", "It changes the font family", "It prevents text from wrapping"],
    "correct_answer": "It is based on the width of the '0' character, allowing you to set a maximum line length (e.g., `max-width: 65ch`) that guarantees optimal reading comfort regardless of screen size or font",
    "explanation": "Typographic studies show that 45-75 characters per line is optimal for reading. Using `max-width: 65ch` ensures your text block never exceeds that perfect length, even on a 5K ultrawide monitor."
  },
  {
    "id": 476,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "iOS Safe Area Deep Dive",
    "question": "If you want to apply padding to the bottom of a fixed footer to account for the iPhone home indicator, but ONLY if the device actually has a safe area inset, how do you write it?",
    "code_snippet": null,
    "options": ["padding-bottom: env(safe-area-inset-bottom);", "padding-bottom: max(16px, env(safe-area-inset-bottom));", "padding-bottom: 16px + env(safe-area-inset-bottom);", "padding-bottom: safe-area(bottom);"],
    "correct_answer": "padding-bottom: max(16px, env(safe-area-inset-bottom));",
    "explanation": "The `max()` function is perfect here. It ensures the footer has AT LEAST 16px of padding (for standard devices), but if the `env()` value is larger (like 34px on an iPhone with a home indicator), it uses that larger value instead."
  },
  {
    "id": 477,
    "level": "intermediate",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Responsive Debugging",
    "question": "What is the most efficient way to test responsive breakpoints and touch interactions during development without needing a physical phone?",
    "code_snippet": null,
    "options": ["Guessing the screen sizes", "Using the 'Device Mode' / 'Responsive Design Mode' in browser DevTools to simulate viewports, touch events, and throttled network speeds", "Writing JavaScript to resize the window", "Asking a friend to test it on their phone"],
    "correct_answer": "Using the 'Device Mode' / 'Responsive Design Mode' in browser DevTools to simulate viewports, touch events, and throttled network speeds",
    "explanation": "Browser DevTools allow you to drag the viewport to any size, simulate specific device dimensions (like iPhone 14 or Galaxy S20), emulate touch-screen hover states, and throttle the CPU/Network to test real-world performance."
  },
  {
    "id": 478,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Scripting Media Feature",
    "question": "What does `@media (scripting: none)` allow you to do?",
    "code_snippet": null,
    "options": ["Disable JavaScript", "Apply specific CSS styles ONLY if the user has JavaScript disabled in their browser, acting as a modern replacement for the `<noscript>` HTML tag", "Detect if the user is using a screen reader", "Prevent CSS animations"],
    "correct_answer": "Apply specific CSS styles ONLY if the user has JavaScript disabled in their browser, acting as a modern replacement for the `<noscript>` HTML tag",
    "explanation": "This is an incredibly powerful, yet rarely used, media feature. It allows you to show a 'Please enable JavaScript' banner, or provide CSS-only fallback navigation menus, purely through CSS without needing `<noscript>` tags in the HTML."
  },
  {
    "id": 479,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "Intrinsic Web Design",
    "question": "What is 'Intrinsic Web Design' and how does it relate to the future of responsive CSS?",
    "code_snippet": null,
    "options": ["Using only images for layouts", "Moving away from hardcoded breakpoints entirely, relying instead on intrinsic sizing (`minmax`, `auto-fit`, `clamp`) and Container Queries so the layout naturally adapts based on the available space and content", "Designing websites exclusively for VR headsets", "Using JavaScript to calculate layouts"],
    "correct_answer": "Moving away from hardcoded breakpoints entirely, relying instead on intrinsic sizing (`minmax`, `auto-fit`, `clamp`) and Container Queries so the layout naturally adapts based on the available space and content",
    "explanation": "The future of responsive design isn't about targeting specific devices (iPhone, iPad, Desktop). It's about creating fluid, intrinsic layouts that look perfect at ANY arbitrary width, from a smartwatch to an ultrawide monitor, without a single `@media` query."
  },
  {
    "id": 480,
    "level": "advanced",
    "module_id": "css_mod_06_responsive",
    "module_name": "Responsive Design & Media Queries",
    "type": "conceptual",
    "topic": "The Ultimate Responsive Philosophy",
    "question": "What is the ultimate goal of modern Responsive Web Design?",
    "code_snippet": null,
    "options": ["To make the website look exactly the same on a smartwatch and a 4K TV", "To ensure the content is accessible, readable, and functional regardless of the device, screen size, input method, or user preferences", "To force all users to download the mobile app", "To eliminate the need for CSS Grid and Flexbox"],
    "correct_answer": "To ensure the content is accessible, readable, and functional regardless of the device, screen size, input method, or user preferences",
    "explanation": "Responsive design isn't about pixel-perfect replication across devices. It's about resilience. A truly responsive site adapts gracefully to a folded Galaxy Z Fold, a 32-inch ultrawide monitor, a user with a tremor using a keyboard, or someone browsing in bright sunlight."
  }
]
