[
  {
    "id": 1,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "CSS Basics",
    "question": "What does CSS stand for?",
    "code_snippet": null,
    "options": ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style Sheets", "Colorful Style Sheets"],
    "correct_answer": "Cascading Style Sheets",
    "explanation": "CSS stands for Cascading Style Sheets. The 'cascading' part refers to how styles are applied based on specificity, inheritance, and source order."
  },
  {
    "id": 2,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "CSS Basics",
    "question": "What is the 'separation of concerns' principle in web development?",
    "code_snippet": null,
    "options": ["Keeping HTML for structure, CSS for presentation, and JS for behavior", "Keeping all code in a single file for easy loading", "Separating frontend code from backend databases", "Using different browsers for different tasks"],
    "correct_answer": "Keeping HTML for structure, CSS for presentation, and JS for behavior",
    "explanation": "Separation of concerns makes code much easier to maintain. If you want to change the color of a button, you only edit the CSS, without touching the HTML structure or JavaScript logic."
  },
  {
    "id": 3,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Including CSS",
    "question": "Which HTML tag is used to write Internal CSS directly inside an HTML document?",
    "code_snippet": "<head>\n  <_______>\n    body { background: white; }\n  </_______>\n</head>",
    "options": ["script", "style", "css", "link"],
    "correct_answer": "style",
    "explanation": "The `<style>` tag is used to embed internal CSS directly within the `<head>` of an HTML document."
  },
  {
    "id": 4,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Including CSS",
    "question": "Which HTML tag and attribute combination is used to link an External CSS file?",
    "code_snippet": "<head>\n  <_______ rel='stylesheet' href='styles.css'>\n</head>",
    "options": ["<script>", "<link>", "<style>", "<meta>"],
    "correct_answer": "<link>",
    "explanation": "The `<link>` tag with `rel='stylesheet'` is the standard way to connect an external `.css` file to your HTML document."
  },
  {
    "id": 5,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Including CSS",
    "question": "Which HTML attribute is used to apply Inline CSS directly to a specific element?",
    "code_snippet": "<button _______='background-color: blue; color: white;'>Click Me</button>",
    "options": ["css", "class", "style", "font"],
    "correct_answer": "style",
    "explanation": "The `style` attribute allows you to write CSS rules directly on an HTML element. It is generally discouraged for large projects because it mixes structure with presentation."
  },
  {
    "id": 6,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Basic Selectors",
    "question": "How do you select ALL `<p>` elements on a page using an element selector?",
    "code_snippet": "_______ {\n  color: blue;\n}",
    "options": ["#p", ".p", "p", "*p"],
    "correct_answer": "p",
    "explanation": "Element (or type) selectors use the raw HTML tag name without any symbols. `p` selects every paragraph on the page."
  },
  {
    "id": 7,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Basic Selectors",
    "question": "Which symbol is used to select elements by their class name?",
    "code_snippet": "_______highlight {\n  background-color: yellow;\n}",
    "options": ["#", ".", "*", "&"],
    "correct_answer": ".",
    "explanation": "The period/dot (`.`) is the class selector. `.highlight` will select any element that has `class='highlight'` in the HTML."
  },
  {
    "id": 8,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Basic Selectors",
    "question": "Which symbol is used to select an element by its unique ID?",
    "code_snippet": "_______main-header {\n  font-size: 24px;\n}",
    "options": [".", "#", "@", "!"],
    "correct_answer": "#",
    "explanation": "The hash/pound symbol (`#`) is the ID selector. `#main-header` selects the single element with `id='main-header'`."
  },
  {
    "id": 9,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Basic Selectors",
    "question": "What does the universal selector (`*`) do in CSS?",
    "code_snippet": null,
    "options": ["Selects only the `<body>` element", "Selects all elements on the page", "Selects all elements with a specific class", "Selects the parent of the current element"],
    "correct_answer": "Selects all elements on the page",
    "explanation": "The `*` selector matches every single element in the DOM. It is most commonly used for global resets, like `* { box-sizing: border-box; margin: 0; }`."
  },
  {
    "id": 10,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Combinators",
    "question": "What is the difference between a descendant selector (`div p`) and a child selector (`div > p`)?",
    "code_snippet": null,
    "options": ["There is no difference", "Descendant selects ALL `<p>` inside the `<div>` at any depth; Child selects ONLY `<p>` that are direct children of the `<div>`", "Child selects ALL `<p>` inside the `<div>`; Descendant selects ONLY direct children", "Descendant is for classes, Child is for IDs"],
    "correct_answer": "Descendant selects ALL `<p>` inside the `<div>` at any depth; Child selects ONLY `<p>` that are direct children of the `<div>`",
    "explanation": "The space (` `) is the descendant combinator (looks anywhere down the tree). The `>` is the child combinator (looks only one level deep)."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Combinators",
    "question": "Fill in the blank to select only the DIRECT `<li>` children of a `<ul>`.",
    "code_snippet": "ul _______ li {\n  list-style-type: square;\n}",
    "options": [">", "+", "~", " "],
    "correct_answer": ">",
    "explanation": "The `>` symbol is the child combinator. It ensures you only style `<li>` tags that are immediately inside the `<ul>`, ignoring `<li>` tags nested inside sub-lists."
  },
  {
    "id": 12,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Combinators",
    "question": "Which combinator selects an element that is IMMEDIATELY preceded by another specific element (Adjacent Sibling)?",
    "code_snippet": "h1 _______ p {\n  margin-top: 0;\n}",
    "options": [">", "+", "~", ","],
    "correct_answer": "+",
    "explanation": "The `+` symbol is the adjacent sibling combinator. `h1 + p` selects a `<p>` that comes immediately after an `<h1>`, sharing the same parent."
  },
  {
    "id": 13,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Combinators",
    "question": "Which combinator selects ALL subsequent sibling elements that share the same parent (General Sibling)?",
    "code_snippet": "h1 _______ p {\n  color: gray;\n}",
    "options": [">", "+", "~", "*"],
    "correct_answer": "~",
    "explanation": "The `~` symbol is the general sibling combinator. `h1 ~ p` selects ANY `<p>` that comes after an `<h1>` in the same parent container, even if they aren't immediately next to each other."
  },
  {
    "id": 14,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Attribute Selectors",
    "question": "How do you select all `<input>` elements that have the exact attribute `type='text'`?",
    "code_snippet": "input_______ {\n  border: 1px solid black;\n}",
    "options": ["[type='text']", "(type='text')", ".type='text'", "#type='text'"],
    "correct_answer": "[type='text']",
    "explanation": "Attribute selectors use square brackets `[]`. `[type='text']` targets elements where the `type` attribute is exactly equal to 'text'."
  },
  {
    "id": 15,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Attribute Selectors",
    "question": "What does the attribute selector `[href^='https']` match?",
    "code_snippet": null,
    "options": ["Links that end with 'https'", "Links that contain 'https' anywhere in the URL", "Links whose `href` attribute starts with 'https'", "Links that have 'https' as a separate word"],
    "correct_answer": "Links whose `href` attribute starts with 'https'",
    "explanation": "The `^=` operator means 'starts with'. (`$=` means 'ends with', and `*=` means 'contains anywhere')."
  },
  {
    "id": 16,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes",
    "question": "Which pseudo-class is used to style a link when the user's mouse pointer is hovering over it?",
    "code_snippet": "a:_______ {\n  color: red;\n}",
    "options": ["active", "hover", "focus", "over"],
    "correct_answer": "hover",
    "explanation": "The `:hover` pseudo-class applies styles when the user interacts with the element using a pointing device (like a mouse). Remember the LVHA order: Link, Visited, Hover, Active."
  },
  {
    "id": 17,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-elements",
    "question": "What is the correct modern CSS syntax to insert generated content BEFORE an element's actual content?",
    "code_snippet": ".icon_______ {\n  content: '★';\n  color: gold;\n}",
    "options": [":before", "::before", ":pre", "::pre"],
    "correct_answer": "::before",
    "explanation": "CSS3 introduced the double colon `::` syntax to distinguish pseudo-elements (which create virtual elements) from pseudo-classes (which select states). `::before` and `::after` require the `content` property to work."
  },
  {
    "id": 18,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-classes vs Pseudo-elements",
    "question": "What is the fundamental difference between a pseudo-class and a pseudo-element?",
    "code_snippet": null,
    "options": ["There is no difference", "A pseudo-class selects a specific STATE of an element (like :hover); a pseudo-element selects a specific PART of an element or inserts synthetic content (like ::first-line)", "Pseudo-elements are deprecated", "Pseudo-classes are for HTML, pseudo-elements are for SVG"],
    "correct_answer": "A pseudo-class selects a specific STATE of an element (like :hover); a pseudo-element selects a specific PART of an element or inserts synthetic content (like ::first-line)",
    "explanation": "Pseudo-classes (`:`) filter existing elements based on state or position. Pseudo-elements (`::`) act as if they inserted a brand new HTML element into the DOM."
  },
  {
    "id": 19,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Specificity",
    "question": "Which of the following selectors has the HIGHEST specificity?",
    "code_snippet": null,
    "options": [".header .nav a", "#main-content", "div > p.intro", "body header h1"],
    "correct_answer": "#main-content",
    "explanation": "Specificity is calculated as (Inline, IDs, Classes/Attributes/Pseudo-classes, Elements/Pseudo-elements). An ID selector (`#`) has a specificity of 1,0,0. The others are 0,2,1 / 0,1,2 / 0,0,3 respectively. IDs always win over classes and elements."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "!important",
    "question": "Why is the `!important` declaration generally considered a bad practice in modern CSS?",
    "code_snippet": null,
    "options": ["It causes the browser to crash", "It makes the CSS file size significantly larger", "It overrides the natural cascade, making styles extremely difficult to debug, override, and maintain", "It only works in Internet Explorer"],
    "correct_answer": "It overrides the natural cascade, making styles extremely difficult to debug, override, and maintain",
    "explanation": "Using `!important` is like using a sledgehammer. If you need to override it later, you have to use another `!important`, leading to a messy 'specificity war'. It's better to fix the selector specificity instead."
  }
]
[
  {
    "id": 21,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:nth-child)",
    "question": "Fill in the blank to select every EVEN row in a table (e.g., 2nd, 4th, 6th) to create a zebra-stripe effect.",
    "code_snippet": "tr:_______ {\n  background-color: #f2f2f2;\n}",
    "options": ["nth-child(even)", "nth-child(odd)", "nth-child(2)", "nth-of-type(even)"],
    "correct_answer": "nth-child(even)",
    "explanation": "The `:nth-child(even)` (or `:nth-child(2n)`) pseudo-class selects elements whose index among siblings is an even number. It's the standard way to create zebra-striped tables or lists."
  },
  {
    "id": 22,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-classes (:first-of-type)",
    "question": "What is the difference between `:first-child` and `:first-of-type`?",
    "code_snippet": null,
    "options": ["There is no difference", "`:first-child` selects the first element only if it matches the element type; `:first-of-type` selects the first element of that specific type, regardless of what comes before it", "`:first-of-type` is deprecated", "`:first-child` is for IDs, `:first-of-type` is for classes"],
    "correct_answer": "`:first-child` selects the first element only if it matches the element type; `:first-of-type` selects the first element of that specific type, regardless of what comes before it",
    "explanation": "If you have `<h1>Title</h1><p>First</p><p>Second</p>`, `p:first-child` matches NOTHING (because the first child is an h1). But `p:first-of-type` matches the 'First' paragraph, because it's the first `<p>` in the parent."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:not)",
    "question": "Fill in the blank to select all `<button>` elements EXCEPT those with the class `.disabled`.",
    "code_snippet": "button:_______(.disabled) {\n  cursor: pointer;\n}",
    "options": ["not", "except", "exclude", "minus"],
    "correct_answer": "not",
    "explanation": "The `:not()` pseudo-class is the negation pseudo-class. It matches elements that do NOT match the selector list inside the parentheses."
  },
  {
    "id": 24,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-classes (:focus-visible)",
    "question": "Why is `:focus-visible` generally preferred over `:focus` for styling keyboard navigation outlines?",
    "code_snippet": null,
    "options": ["It runs faster", "`:focus-visible` only applies the outline when the user navigates via keyboard (Tab), hiding it when they click with a mouse", "`:focus` is deprecated", "There is no difference"],
    "correct_answer": "`:focus-visible` only applies the outline when the user navigates via keyboard (Tab), hiding it when they click with a mouse",
    "explanation": "Using `:focus` often results in ugly blue outlines appearing when a user simply clicks a button with their mouse. `:focus-visible` uses browser heuristics to only show the focus ring when it's actually needed for accessibility (keyboard users)."
  },
  {
    "id": 25,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Modern Selectors (:is)",
    "question": "How does the `:is()` pseudo-class calculate its specificity?",
    "code_snippet": null,
    "options": ["It always has a specificity of 0", "It takes the specificity of the MOST specific selector in its comma-separated list", "It adds the specificity of all selectors in the list together", "It always has a specificity of 1,0,0"],
    "correct_answer": "It takes the specificity of the MOST specific selector in its comma-separated list",
    "explanation": "If you write `:is(#id, .class)`, the specificity of the entire `:is()` block becomes 1,0,0 (the ID's specificity), because it takes the highest specificity argument to ensure the styles apply correctly."
  },
  {
    "id": 26,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Modern Selectors (:where)",
    "question": "What is unique about the specificity of the `:where()` pseudo-class?",
    "code_snippet": null,
    "options": ["It takes the specificity of the most specific argument", "It always has a specificity of 0,0,0, making it incredibly useful for CSS resets and defaults that are easy to override", "It doubles the specificity of its arguments", "It inherits the specificity of the parent element"],
    "correct_answer": "It always has a specificity of 0,0,0, making it incredibly useful for CSS resets and defaults that are easy to override",
    "explanation": "Unlike `:is()`, `:where()` always contributes 0 to the specificity calculation. This makes it perfect for writing base styles (like `:where(h1, h2, h3) { margin: 0; }`) that any developer can easily override later without fighting specificity wars."
  },
  {
    "id": 27,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-elements (::selection)",
    "question": "Fill in the blank to style the background color of text when the user highlights it with their mouse.",
    "code_snippet": "::_______ {\n  background-color: yellow;\n  color: black;\n}",
    "options": ["highlight", "select", "selection", "marked"],
    "correct_answer": "selection",
    "explanation": "The `::selection` pseudo-element allows you to customize the browser's default text highlighting color to match your brand or design system."
  },
  {
    "id": 28,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-elements (::placeholder)",
    "question": "Which pseudo-element is used to style the hint text inside an empty `<input>` field?",
    "code_snippet": "input::_______ {\n  color: gray;\n  font-style: italic;\n}",
    "options": ["hint", "placeholder", "default-text", "ghost"],
    "correct_answer": "placeholder",
    "explanation": "The `::placeholder` pseudo-element targets the text defined in the `placeholder='...'` attribute of form inputs, allowing you to change its color, opacity, or font."
  },
  {
    "id": 29,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Specificity Calculation",
    "question": "What is the exact specificity score (Inline, IDs, Classes, Elements) for the selector: `#header .nav a`?",
    "code_snippet": null,
    "options": ["1, 1, 1", "0, 1, 1, 1", "1, 0, 1, 1", "0, 2, 1, 0"],
    "correct_answer": "0, 1, 1, 1",
    "explanation": "Break it down: `#header` is 1 ID (0,1,0,0). `.nav` is 1 class (0,0,1,0). `a` is 1 element (0,0,0,1). Add them together: 0, 1, 1, 1."
  },
  {
    "id": 30,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Specificity Calculation",
    "question": "Which rule will win and be applied to the `<p>` element?",
    "code_snippet": "/* Rule A */\n#content p { color: red; }\n\n/* Rule B */\n.text { color: blue; }\n\n/* HTML */\n<div id='content'><p class='text'>Hello</p></div>",
    "options": ["Rule A (Red)", "Rule B (Blue)", "Neither, it defaults to black", "It throws a CSS error"],
    "correct_answer": "Rule A (Red)",
    "explanation": "Rule A has a specificity of 1,0,1 (one ID, one element). Rule B has a specificity of 0,1,0 (one class). Because IDs are worth more than any number of classes, Rule A wins."
  },
  {
    "id": 31,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Inheritance",
    "question": "Which of the following CSS properties is INHERITED by default from parent to child elements?",
    "code_snippet": null,
    "options": ["border", "margin", "color", "padding"],
    "correct_answer": "color",
    "explanation": "Typography and color properties (like `color`, `font-family`, `line-height`) are inherited by default. Box model properties (margin, padding, border) are NOT inherited, because you usually don't want a child element to have the exact same margins as its parent."
  },
  {
    "id": 32,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "The Cascade",
    "question": "If two CSS rules have the EXACT SAME specificity, which one does the browser apply?",
    "code_snippet": null,
    "options": ["The first one in the CSS file", "The last one in the CSS file (source order)", "It randomly picks one", "It merges both properties together"],
    "correct_answer": "The last one in the CSS file (source order)",
    "explanation": "This is the final tie-breaker in the Cascade. If specificity and inheritance are identical, the rule that appears LATER in the stylesheet (or in a stylesheet loaded later in the HTML) wins."
  },
  {
    "id": 33,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:empty)",
    "question": "Fill in the blank to hide any `<div>` that has absolutely no children or text inside it.",
    "code_snippet": "div:_______ {\n  display: none;\n}",
    "options": ["blank", "void", "empty", "null"],
    "correct_answer": "empty",
    "explanation": "The `:empty` pseudo-class selects elements that have no children (including text nodes). Note: Even a single space or line break in the HTML will prevent `:empty` from matching."
  },
  {
    "id": 34,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:checked)",
    "question": "Which pseudo-class allows you to style a checkbox or radio button ONLY when it is selected by the user?",
    "code_snippet": "input[type='checkbox']:_______ {\n  accent-color: green;\n}",
    "options": ["selected", "active", "checked", "on"],
    "correct_answer": "checked",
    "explanation": "The `:checked` pseudo-class matches radio (`<input type='radio'>`) and checkbox (`<input type='checkbox'>`) elements when they are in the 'on' state."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Modern Selectors (:has)",
    "question": "What is the `:has()` pseudo-class often referred to as by CSS developers?",
    "code_snippet": null,
    "options": ["The 'Undo' selector", "The 'Parent' selector", "The 'Universal' selector", "The 'Shadow' selector"],
    "correct_answer": "The 'Parent' selector",
    "explanation": "For decades, CSS could only select children based on parents. `:has()` finally allows you to select a parent element based on its children! E.g., `figure:has(figcaption)` selects a `<figure>` only if it contains a `<figcaption>`."
  },
  {
    "id": 36,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:root)",
    "question": "Fill in the blank to select the highest-level parent element in the document (usually the `<html>` tag), which is the standard place to declare global CSS variables.",
    "code_snippet": ":_______ {\n  --main-color: #333;\n}",
    "options": ["html", "body", "root", "global"],
    "correct_answer": "root",
    "explanation": "The `:root` pseudo-class matches the document's root element. It is functionally similar to `html`, but has a higher specificity (0,1,0 vs 0,0,1), making it the perfect place to define CSS Custom Properties (variables)."
  },
  {
    "id": 37,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Specificity Calculation",
    "question": "What is the exact specificity score for the selector: `.btn.primary.large`?",
    "code_snippet": null,
    "options": ["0, 3, 0", "0, 1, 0", "0, 0, 3", "1, 0, 0"],
    "correct_answer": "0, 3, 0",
    "explanation": "Chaining multiple classes together on a single element adds their specificity up. `.btn` (0,1,0) + `.primary` (0,1,0) + `.large` (0,1,0) equals a total specificity of 0,3,0."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-elements (::marker)",
    "question": "Which pseudo-element allows you to style the bullet point of a list item or the number in an ordered list?",
    "code_snippet": "li::_______ {\n  color: red;\n  font-size: 1.5em;\n}",
    "options": ["bullet", "list-item", "marker", "icon"],
    "correct_answer": "marker",
    "explanation": "The `::marker` pseudo-element selects the generated bullet or number of a list item. Note: It only supports a limited set of CSS properties, primarily `color`, `font-size`, and `content`."
  },
  {
    "id": 39,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Pseudo-classes (:nth-child math)",
    "question": "Which elements will the selector `:nth-child(3n+1)` match in a list of 10 items?",
    "code_snippet": null,
    "options": ["3, 6, 9", "1, 4, 7, 10", "2, 5, 8", "1, 3, 5, 7, 9"],
    "correct_answer": "1, 4, 7, 10",
    "explanation": "The formula is `an+b`. Here, `a=3` and `b=1`. Plug in `n=0` -> 1. `n=1` -> 4. `n=2` -> 7. `n=3` -> 10. It selects every 3rd item, starting from the 1st."
  },
  {
    "id": 40,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:target)",
    "question": "Fill in the blank to style an element ONLY when its ID matches the current URL's hash fragment (e.g., `website.com/page#section2`).",
    "code_snippet": "div:_______ {\n  background-color: yellow;\n  scroll-margin-top: 2rem;\n}",
    "options": ["active", "hash", "target", "focus"],
    "correct_answer": "target",
    "explanation": "The `:target` pseudo-class applies styles to the unique element with an ID matching the URL's fragment (the part after the `#`). It's perfect for highlighting the section the user just jumped to."
  }
]
[
  {
    "id": 41,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Grouping Selectors",
    "question": "How do you apply the exact same styles to both `<h1>` and `<h2>` elements using a single CSS rule?",
    "code_snippet": "_______ {\n  font-family: 'Helvetica', sans-serif;\n}",
    "options": ["h1 + h2", "h1, h2", "h1 h2", "h1 & h2"],
    "correct_answer": "h1, h2",
    "explanation": "The comma (`,`) is the grouping combinator. It allows you to apply the same declaration block to multiple, completely separate selectors, keeping your CSS clean and DRY."
  },
  {
    "id": 42,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Chaining Selectors",
    "question": "What does the selector `p.intro` (with NO space between them) select?",
    "code_snippet": null,
    "options": ["All `<p>` elements inside an element with class 'intro'", "All `<p>` elements that ALSO have the class 'intro'", "All elements with class 'intro' inside a `<p>`", "It is a syntax error"],
    "correct_answer": "All `<p>` elements that ALSO have the class 'intro'",
    "explanation": "Chaining selectors (no space) means the element must match ALL parts of the selector. `<p class='intro'>` will match, but `<div class='intro'>` or `<p class='outro'>` will not."
  },
  {
    "id": 43,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Specificity Calculation",
    "question": "What is the exact specificity score (Inline, IDs, Classes, Elements) for the chained selector: `div#main.active`?",
    "code_snippet": null,
    "options": ["0, 1, 1, 1", "0, 1, 2, 0", "0, 2, 1, 0", "1, 1, 1, 0"],
    "correct_answer": "0, 1, 1, 1",
    "explanation": "Break it down: `div` is 1 element (0,0,0,1). `#main` is 1 ID (0,1,0,0). `.active` is 1 class (0,0,1,0). Add them together: 0, 1, 1, 1."
  },
  {
    "id": 44,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Form Pseudo-classes",
    "question": "Which pseudo-class selects form elements that have the `disabled` attribute, preventing user interaction?",
    "code_snippet": "input:_______ {\n  background-color: #eee;\n  cursor: not-allowed;\n}",
    "options": ["inactive", "disabled", "locked", "read-only"],
    "correct_answer": "disabled",
    "explanation": "The `:disabled` pseudo-class matches any element that has the `disabled` attribute, such as `<input>`, `<button>`, or `<select>`. Its counterpart is `:enabled`."
  },
  {
    "id": 45,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Form Validation Pseudo-classes",
    "question": "Which pseudo-class matches an `<input>` element whose current value fails validation (e.g., an invalid email format)?",
    "code_snippet": "input:_______ {\n  border: 2px solid red;\n}",
    "options": ["error", "invalid", "incorrect", "bad-input"],
    "correct_answer": "invalid",
    "explanation": "The `:invalid` pseudo-class is incredibly useful for real-time form validation. It automatically applies styles when the user's input doesn't match the `type` or `pattern` attribute."
  },
  {
    "id": 46,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Form Pseudo-classes",
    "question": "Which pseudo-class targets form inputs that have the `required` attribute?",
    "code_snippet": "input:_______ {\n  background-image: url('asterisk.png');\n}",
    "options": ["mandatory", "required", "needed", "must-fill"],
    "correct_answer": "required",
    "explanation": "The `:required` pseudo-class selects inputs with the `required` attribute. Its counterpart is `:optional`, which selects inputs that do NOT have the `required` attribute."
  },
  {
    "id": 47,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Language Pseudo-class",
    "question": "How do you select all `<p>` elements that are explicitly marked as French (e.g., `lang='fr'`)?",
    "code_snippet": "p:_______(fr) {\n  font-family: 'Garamond', serif;\n}",
    "options": ["language", "lang", "locale", "text"],
    "correct_answer": "lang",
    "explanation": "The `:lang()` pseudo-class matches elements based on their language. It is slightly smarter than the attribute selector `[lang|=fr]` because it also inherits language from parent elements."
  },
  {
    "id": 48,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-elements",
    "question": "Which pseudo-element allows you to style ONLY the very first character of a block-level element (often used for 'drop caps' in magazines)?",
    "code_snippet": "p::_______ {\n  font-size: 3em;\n  font-weight: bold;\n  float: left;\n}",
    "options": ["first-char", "first-letter", "initial", "start"],
    "correct_answer": "first-letter",
    "explanation": "The `::first-letter` pseudo-element targets the first typographic letter of a block. Note: It only works on block-level containers, not inline elements like `<span>`."
  },
  {
    "id": 49,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-elements (::backdrop)",
    "question": "What does the `::backdrop` pseudo-element target?",
    "code_snippet": null,
    "options": ["The background color of the body", "The area behind a fullscreen element or an HTML `<dialog>` element", "The shadow behind a box", "The background of a pseudo-element"],
    "correct_answer": "The area behind a fullscreen element or an HTML `<dialog>` element",
    "explanation": "When you use the `<dialog>` element or the Fullscreen API, the browser creates a `::backdrop` directly behind it. You can use this pseudo-element to style the darkened overlay (e.g., `dialog::backdrop { background: rgba(0,0,0,0.5); }`)."
  },
  {
    "id": 50,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Specificity Edge Cases",
    "question": "Which has higher specificity: an inline style (`style='color: red;'`) or an ID selector (`#header`)?",
    "code_snippet": null,
    "options": ["ID selector", "Inline style", "They are equal", "Depends on the browser"],
    "correct_answer": "Inline style",
    "explanation": "Inline styles have a specificity of 1,0,0,0. An ID selector has a specificity of 0,1,0,0. No matter how many IDs you chain together in a stylesheet, an inline style will always win (unless `!important` is used)."
  },
  {
    "id": 51,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "!important",
    "question": "Can a standard CSS rule with `!important` override an inline style?",
    "code_snippet": null,
    "options": ["No, inline styles always win", "Yes, `!important` overrides everything except other `!important` rules and inline styles with `!important`", "Only if it has an ID selector", "Only in Internet Explorer"],
    "correct_answer": "Yes, `!important` overrides everything except other `!important` rules and inline styles with `!important`",
    "explanation": "The `!important` declaration sits at the very top of the cascade hierarchy. It will beat inline styles, IDs, and classes. The only thing that beats an `!important` rule is another `!important` rule with a higher specificity or later source order."
  },
  {
    "id": 52,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Modern CSS (@layer)",
    "question": "How does the `@layer` at-rule affect the CSS Cascade?",
    "code_snippet": null,
    "options": ["It disables specificity entirely", "It allows you to control the order of the cascade; a rule in a later layer will override a rule in an earlier layer, even if the earlier layer has a higher specificity selector", "It automatically adds `!important` to all rules", "It scopes CSS to a specific HTML component"],
    "correct_answer": "It allows you to control the order of the cascade; a rule in a later layer will override a rule in an earlier layer, even if the earlier layer has a higher specificity selector",
    "explanation": "CSS Layers introduce a new step in the Cascade. Origin > Specificity > Source Order is the old way. Now, Layer Order trumps Specificity. This is a game-changer for building design systems and overriding third-party libraries."
  },
  {
    "id": 53,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Selectors Level 4 (:not)",
    "question": "In CSS Selectors Level 4, how do you select all elements EXCEPT those with class `.active` OR `.disabled`?",
    "code_snippet": "button:_______(.active, .disabled) {\n  opacity: 1;\n}",
    "options": ["not", "except", "exclude", "minus"],
    "correct_answer": "not",
    "explanation": "Older CSS only allowed a single simple selector inside `:not()`. Modern CSS (Selectors Level 4) allows a comma-separated list of selectors, making it incredibly powerful for exclusion logic."
  },
  {
    "id": 54,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-classes (:nth-last-child)",
    "question": "What does the `:nth-last-child(2)` pseudo-class select?",
    "code_snippet": null,
    "options": ["The second child from the beginning", "The second child from the end (the second-to-last element)", "The last two children", "Every second child starting from the end"],
    "correct_answer": "The second child from the end (the second-to-last element)",
    "explanation": "The `:nth-last-child()` pseudo-class works exactly like `:nth-child()`, but it counts backwards from the last element in the parent container."
  },
  {
    "id": 55,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-classes (:nth-of-type)",
    "question": "Why would you use `p:nth-of-type(2)` instead of `p:nth-child(2)`?",
    "code_snippet": null,
    "options": ["There is no difference", "`:nth-of-type(2)` selects the second `<p>` element regardless of what other elements are mixed in between; `:nth-child(2)` only selects it if the second child overall is a `<p>`", "`:nth-of-type` is faster", "`:nth-child` is deprecated"],
    "correct_answer": "`:nth-of-type(2)` selects the second `<p>` element regardless of what other elements are mixed in between; `:nth-child(2)` only selects it if the second child overall is a `<p>`",
    "explanation": "If you have `<h1>Title</h1><p>First</p><p>Second</p>`, `p:nth-child(2)` matches NOTHING (because the 2nd child is a `<p>`, but wait, the 1st child is h1, 2nd is p... let's be precise). `p:nth-child(2)` matches the first `<p>` because it is the 2nd child of the parent. `p:nth-of-type(2)` matches the SECOND `<p>` ('Second'), ignoring the `<h1>` entirely."
  },
  {
    "id": 56,
    "level": "beginner",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "code-fill-in-blank",
    "topic": "Pseudo-classes (:only-child)",
    "question": "Which pseudo-class selects an element that is the ONLY child of its parent (no siblings)?",
    "code_snippet": "li:_______ {\n  list-style-type: none;\n}",
    "options": ["single", "only-child", "unique", "first-and-last"],
    "correct_answer": "only-child",
    "explanation": "The `:only-child` pseudo-class matches an element if its parent has no other element children. It is functionally equivalent to `:first-child:last-child` or `:only-of-type` (if there's only one element of that type)."
  },
  {
    "id": 57,
    "level": "advanced",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Pseudo-classes (:scope)",
    "question": "What does the `:scope` pseudo-class refer to when used in JavaScript's `querySelectorAll()`?",
    "code_snippet": null,
    "options": ["The entire HTML document", "The element upon which `querySelectorAll()` was called (the reference element)", "The `<body>` element", "The currently focused element"],
    "correct_answer": "The element upon which `querySelectorAll()` was called (the reference element)",
    "explanation": "If you do `document.querySelector('.container').querySelectorAll(':scope > .item')`, `:scope` acts as the `.container` element. It allows you to write scoped CSS selectors in JS."
  },
  {
    "id": 58,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "output-prediction",
    "topic": "Specificity Calculation",
    "question": "Which of the following selectors has the highest specificity?",
    "code_snippet": null,
    "options": ["a, b, c", "div p span", ".nav .link", "#main"],
    "correct_answer": "#main",
    "explanation": "Let's calculate: `a, b, c` is 0,0,0,1. `div p span` is 0,0,0,3. `.nav .link` is 0,0,2,0. `#main` is 0,1,0,0. Because IDs are worth more than any combination of classes or elements, `#main` wins."
  },
  {
    "id": 59,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "Specificity Edge Cases",
    "question": "What is the specificity of the universal selector (`*`)?",
    "code_snippet": null,
    "options": ["0, 0, 0, 1", "0, 0, 1, 0", "0, 0, 0, 0", "It depends on what it is selecting"],
    "correct_answer": "0, 0, 0, 0",
    "explanation": "The universal selector (`*`), combinators (`+`, `>`, `~`, ` `), and the negation pseudo-class `:not()` (by itself) contribute ZERO to the specificity calculation. They are completely ignored when determining the winner."
  },
  {
    "id": 60,
    "level": "intermediate",
    "module_id": "css_mod_01_selectors",
    "module_name": "Introduction & Selectors",
    "type": "conceptual",
    "topic": "The Cascade",
    "question": "What are the three main pillars that determine which CSS rule is ultimately applied to an element (The Cascade)?",
    "code_snippet": null,
    "options": ["HTML, CSS, JavaScript", "Inline, Internal, External", "Specificity, Inheritance, and Source Order", "Selectors, Properties, and Values"],
    "correct_answer": "Specificity, Inheritance, and Source Order",
    "explanation": "The Cascade is the algorithm that resolves conflicts. 1. Origin & Importance (User agent, user, author, !important). 2. Specificity. 3. Source Order. Inheritance also plays a massive role in whether a property trickles down from a parent."
  }
]
