[
  {
    "id": 201,
    "level": "beginner",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Flexbox Basics",
    "question": "What is the primary defining characteristic of CSS Flexbox?",
    "code_snippet": null,
    "options": ["It is a two-dimensional layout system (rows AND columns simultaneously)", "It is a one-dimensional layout system, dealing with layout in one direction at a time (either as a row or as a column)", "It is used exclusively for 3D animations", "It replaces the CSS Box Model entirely"],
    "correct_answer": "It is a one-dimensional layout system, dealing with layout in one direction at a time (either as a row or as a column)",
    "explanation": "Flexbox is designed for one-dimensional layouts (either a horizontal row OR a vertical column). If you need strict two-dimensional control (rows AND columns together), CSS Grid is the better tool."
  },
  {
    "id": 202,
    "level": "beginner",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "topic": "Flex Container",
    "question": "Fill in the blank to turn a standard `<div>` into a Flex container, enabling Flexbox layout for its direct children.",
    "code_snippet": ".container {\n  display: _______;\n}",
    "options": ["block", "flex", "grid", "inline"],
    "correct_answer": "flex",
    "explanation": "Setting `display: flex` on a parent element turns it into a Flex Container. Its direct children automatically become Flex Items and will now follow Flexbox layout rules."
  },
  {
    "id": 203,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Axes",
    "question": "In Flexbox, what are the 'Main Axis' and 'Cross Axis'?",
    "code_snippet": null,
    "options": ["They are always horizontal and vertical, respectively", "The Main Axis is the primary direction of the flex items (defined by flex-direction); the Cross Axis is perpendicular to it", "The Main Axis is for alignment; the Cross Axis is for spacing", "They are determined by the browser's text direction only"],
    "correct_answer": "The Main Axis is the primary direction of the flex items (defined by flex-direction); the Cross Axis is perpendicular to it",
    "explanation": "If `flex-direction` is `row`, the Main Axis is horizontal and the Cross Axis is vertical. If you change `flex-direction` to `column`, the Main Axis becomes vertical, and the Cross Axis becomes horizontal!"
  },
  {
    "id": 204,
    "level": "beginner",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-direction",
    "question": "What is the default value of the `flex-direction` property?",
    "code_snippet": null,
    "options": ["column", "row", "row-reverse", "column-reverse"],
    "correct_answer": "row",
    "explanation": "By default, Flexbox lays out items horizontally in a row, from left to right (in LTR languages). This establishes the horizontal Main Axis."
  },
  {
    "id": 205,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "output-prediction",
    "topic": "flex-direction",
    "question": "If you apply `flex-direction: column` to a Flex container, what happens to the Main Axis?",
    "code_snippet": null,
    "options": ["It remains horizontal", "It becomes vertical (top to bottom)", "It reverses to right-to-left", "The axes are deleted"],
    "correct_answer": "It becomes vertical (top to bottom)",
    "explanation": "Changing the direction to `column` rotates the layout. The Main Axis is now vertical (top to bottom), meaning properties like `justify-content` will now align items vertically instead of horizontally."
  },
  {
    "id": 206,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "topic": "flex-wrap",
    "question": "By default, Flex items try to fit onto one line. Fill in the blank to allow them to wrap onto multiple lines if they run out of space.",
    "code_snippet": ".container {\n  display: flex;\n  flex-_______: wrap;\n}",
    "options": ["direction", "flow", "wrap", "grid"],
    "correct_answer": "wrap",
    "explanation": "The default is `nowrap`, which forces items to shrink to fit the container. Setting `flex-wrap: wrap` allows items to drop to the next line, creating a multi-line flex container."
  },
  {
    "id": 207,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-flow",
    "question": "What is the `flex-flow` property?",
    "code_snippet": null,
    "options": ["A property to animate flex items", "A shorthand property combining `flex-direction` and `flex-wrap`", "A property to control the flow of text inside a flex item", "A deprecated property from CSS2"],
    "correct_answer": "A shorthand property combining `flex-direction` and `flex-wrap`",
    "explanation": "Instead of writing `flex-direction: column; flex-wrap: wrap;`, you can simply write `flex-flow: column wrap;`. It saves time and keeps your CSS clean."
  },
  {
    "id": 208,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "justify-content",
    "question": "Which axis does the `justify-content` property align items along?",
    "code_snippet": null,
    "options": ["The Cross Axis", "The Main Axis", "Both axes simultaneously", "The Z-axis (depth)"],
    "correct_answer": "The Main Axis",
    "explanation": "`justify-content` controls alignment along the Main Axis. If your direction is `row`, it aligns horizontally. If your direction is `column`, it aligns vertically."
  },
  {
    "id": 209,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "justify-content values",
    "question": "What is the difference between `space-between` and `space-evenly`?",
    "code_snippet": null,
    "options": ["There is no difference", "`space-between` puts the first and last items flush against the edges; `space-evenly` distributes space so the gaps between items and the edges are all exactly equal", "`space-evenly` is for vertical, `space-between` is for horizontal", "`space-between` requires at least 3 items"],
    "correct_answer": "`space-between` puts the first and last items flush against the edges; `space-evenly` distributes space so the gaps between items and the edges are all exactly equal",
    "explanation": "With `space-between`, the edge items touch the container walls. With `space-evenly`, the empty space on the far left is exactly the same size as the empty space between the items."
  },
  {
    "id": 210,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to align all flex items to the exact center of the container along the Cross Axis.",
    "code_snippet": ".container {\n  display: flex;\n  _______-items: center;\n}",
    "options": ["justify", "align", "cross", "main"],
    "correct_answer": "align",
    "explanation": "`align-items` controls alignment on the Cross Axis. If your Main Axis is horizontal (row), `align-items: center` will vertically center the items inside the container."
  },
  {
    "id": 211,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "align-items default",
    "question": "What is the default value of `align-items`, and what does it do?",
    "code_snippet": null,
    "options": ["center; it centers items vertically", "stretch; it forces items to fill the entire height (or width) of the container", "flex-start; it aligns items to the top", "baseline; it aligns items by their text baseline"],
    "correct_answer": "stretch; it forces items to fill the entire height (or width) of the container",
    "explanation": "By default, `align-items: stretch` makes flex items stretch to fill the cross-size of the container. If your container is 200px tall, the items will stretch to be 200px tall unless they have explicit heights or content that prevents it."
  },
  {
    "id": 212,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to override the container's `align-items` setting for ONE specific flex item, pushing it to the bottom of the container.",
    "code_snippet": ".special-item {\n  _______-self: flex-end;\n}",
    "options": ["justify", "align", "item", "cross"],
    "correct_answer": "align",
    "explanation": "`align-self` allows you to treat a single flex item differently from the rest. If the container has `align-items: center`, but one item has `align-self: flex-end`, that specific item will drop to the bottom edge."
  },
  {
    "id": 213,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "align-content",
    "question": "What is the strict requirement for `align-content` to have any visible effect?",
    "code_snippet": null,
    "options": ["The container must have a defined width", "The flex container MUST be multi-line (e.g., `flex-wrap: wrap`), creating multiple rows or columns to align", "The items must have `align-self` applied", "It only works on `flex-direction: column`"],
    "correct_answer": "The flex container MUST be multi-line (e.g., `flex-wrap: wrap`), creating multiple rows or columns to align",
    "explanation": "`align-content` aligns the *lines* (the rows themselves) within the container. If you only have one single line of items, `align-content` does nothing. It only works when there are multiple lines to distribute space between."
  },
  {
    "id": 214,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-grow",
    "question": "What does the `flex-grow` property control?",
    "code_snippet": null,
    "options": ["The maximum width an item can reach", "How much of the remaining free space in the container the item should take up relative to other items", "The initial size of the item before space is distributed", "The font-size of the text inside the item"],
    "correct_answer": "How much of the remaining free space in the container the item should take up relative to other items",
    "explanation": "If you have two items, one with `flex-grow: 1` and another with `flex-grow: 2`, the second item will consume twice as much of the leftover empty space as the first item."
  },
  {
    "id": 215,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-shrink",
    "question": "What does the `flex-shrink` property control?",
    "code_snippet": null,
    "options": ["How much an item should shrink relative to others if there is NOT enough space in the container", "The minimum width of the item", "The padding inside the item", "The speed of the flex animation"],
    "correct_answer": "How much an item should shrink relative to others if there is NOT enough space in the container",
    "explanation": "If the container is too small to fit all items at their natural size, `flex-shrink` dictates who gives up space first. An item with `flex-shrink: 0` will refuse to shrink, forcing the other items to compress."
  },
  {
    "id": 216,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-basis",
    "question": "What does the `flex-basis` property define?",
    "code_snippet": null,
    "options": ["The final rendered size of the element", "The initial main-size of a flex item before `flex-grow` and `flex-shrink` distribute the remaining space", "The cross-axis size of the element", "The margin around the element"],
    "correct_answer": "The initial main-size of a flex item before `flex-grow` and `flex-shrink` distribute the remaining space",
    "explanation": "`flex-basis` is essentially the 'starting width' (in a row) or 'starting height' (in a column). After the browser calculates this starting size, it then applies `grow` or `shrink` based on the leftover container space."
  },
  {
    "id": 217,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "The flex shorthand",
    "question": "When you write `flex: 1;` on a flex item, what three underlying properties does it actually set?",
    "code_snippet": null,
    "options": ["flex-grow: 1, flex-shrink: 1, flex-basis: 0%", "flex-grow: 1, flex-shrink: 0, flex-basis: auto", "flex-grow: 1, flex-shrink: 1, flex-basis: auto", "flex-grow: 0, flex-shrink: 1, flex-basis: 100%"],
    "correct_answer": "flex-grow: 1, flex-shrink: 1, flex-basis: 0%",
    "explanation": "The `flex` shorthand is highly recommended over setting the individual properties. `flex: 1` is the most common way to say 'take up all available equal space'. It sets the basis to 0%, meaning it ignores the content's natural width and purely divides the container's space equally."
  },
  {
    "id": 218,
    "level": "beginner",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to apply a consistent 20px gap between all flex items, without needing to use margins.",
    "code_snippet": ".container {\n  display: flex;\n  _______: 20px;\n}",
    "options": ["spacing", "gap", "margin", "gutter"],
    "correct_answer": "gap",
    "explanation": "The `gap` property (which also works in CSS Grid) is the modern, clean way to add spacing between flex items. It only applies space *between* the items, not on the outer edges of the container."
  },
  {
    "id": 219,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to visually move a flex item to the very beginning of the container, WITHOUT changing the HTML source order.",
    "code_snippet": ".first-item {\n  _______: -1;\n}",
    "options": ["position", "z-index", "order", "priority"],
    "correct_answer": "order",
    "explanation": "The `order` property controls the visual painting order of flex items. The default is 0. Negative numbers push items to the front, positive numbers push them to the back. This is great for mobile-first responsive design!"
  },
  {
    "id": 220,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "The Centering Trick",
    "question": "What is the classic, modern CSS 'holy grail' trick to perfectly center a single child element both horizontally and vertically inside its parent?",
    "code_snippet": null,
    "options": ["margin: auto; text-align: center;", "display: flex; justify-content: center; align-items: center;", "position: absolute; top: 50%; left: 50%;", "float: center; align: middle;"],
    "correct_answer": "display: flex; justify-content: center; align-items: center;",
    "explanation": "For decades, centering in CSS was a massive joke. Flexbox solved it with three simple lines of code. `justify-content` centers on the Main Axis, and `align-items` centers on the Cross Axis."
  }
]
[
  {
    "id": 221,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex shorthand math",
    "question": "What is the exact difference between `flex: 1` and `flex: 1 1 auto`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`flex: 1` sets the basis to 0% (ignoring content size); `flex: 1 1 auto` sets the basis to `auto` (using the content's natural size as the starting point before growing/shrinking)", "`flex: 1` is for width, `auto` is for height", "`flex: 1` is deprecated"],
    "correct_answer": "`flex: 1` sets the basis to 0% (ignoring content size); `flex: 1 1 auto` sets the basis to `auto` (using the content's natural size as the starting point before growing/shrinking)",
    "explanation": "`flex: 1` is shorthand for `1 1 0%`. It tells the browser to ignore the content's natural width and just divide the container's space equally. `flex: 1 1 auto` respects the content's natural width first, then distributes the remaining space."
  },
  {
    "id": 222,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-basis vs width",
    "question": "Why is it recommended to use `flex-basis` instead of `width` on flex items?",
    "code_snippet": null,
    "options": ["`width` is deprecated in Flexbox", "`flex-basis` respects the flex container's main-axis direction (e.g., acting as height in a column), whereas `width` always forces a horizontal measurement", "`flex-basis` is faster", "There is no difference"],
    "correct_answer": "`flex-basis` respects the flex container's main-axis direction (e.g., acting as height in a column), whereas `width` always forces a horizontal measurement",
    "explanation": "If you change `flex-direction` to `column`, `flex-basis` automatically applies to the vertical height. `width` will stubbornly try to set the horizontal width, breaking your column layout."
  },
  {
    "id": 223,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "min-width: 0 trap",
    "question": "By default, flex items have `min-width: auto`, which prevents them from shrinking smaller than their content. How do you fix a flex item that is overflowing its container and causing a horizontal scrollbar?",
    "code_snippet": null,
    "options": ["Add `max-width: 100%`", "Add `min-width: 0` to the flex item", "Add `overflow: visible`", "Add `flex-shrink: 0`"],
    "correct_answer": "Add `min-width: 0` to the flex item",
    "explanation": "This is the most famous Flexbox trap! Because `min-width: auto` prevents items from shrinking below their content size, long text or images can break the layout. Applying `min-width: 0` (or `overflow: hidden`) overrides this and allows the item to shrink properly."
  },
  {
    "id": 224,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Auto margins",
    "question": "What happens if you apply `margin-left: auto` to a flex item?",
    "code_snippet": null,
    "options": ["It throws an error", "It pushes the item and all subsequent items to the far right, consuming all available free space on its left", "It centers the item", "It removes the item from the DOM"],
    "correct_answer": "It pushes the item and all subsequent items to the far right, consuming all available free space on its left",
    "explanation": "In Flexbox, auto margins are incredibly powerful. They absorb ALL available free space in the specified direction. This is the standard way to push a 'Logout' button to the far right of a navigation bar."
  },
  {
    "id": 225,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Auto margins vs justify-content",
    "question": "Why might you use `margin-left: auto` on the last item in a nav bar instead of `justify-content: space-between` on the container?",
    "code_snippet": null,
    "options": ["`margin-left: auto` is faster", "If you have 3 items and want the first two grouped on the left, and the third pushed to the far right, `justify-content: space-between` would space all 3 evenly; `margin-left: auto` on the 3rd item achieves the exact grouping you want", "`justify-content` is deprecated", "There is no difference"],
    "correct_answer": "If you have 3 items and want the first two grouped on the left, and the third pushed to the far right, `justify-content: space-between` would space all 3 evenly; `margin-left: auto` on the 3rd item achieves the exact grouping you want",
    "explanation": "`justify-content` applies to the entire container. Auto margins apply to specific items, giving you granular control over exactly where the 'break' in the layout occurs."
  },
  {
    "id": 226,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Nested flexbox",
    "question": "Can a flex item also act as a flex container for its own children?",
    "code_snippet": null,
    "options": ["No, an element can only be one or the other", "Yes, by applying `display: flex` to the flex item, creating a nested flex layout", "Only if it has `position: absolute`", "Only if it is a `<div>`"],
    "correct_answer": "Yes, by applying `display: flex` to the flex item, creating a nested flex layout",
    "explanation": "Flexbox can be nested infinitely. An element can be a flex item (respecting its parent's layout) and simultaneously be a flex container (controlling its own children's layout)."
  },
  {
    "id": 227,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "align-content vs align-items",
    "question": "What is the exact difference between `align-items` and `align-content`?",
    "code_snippet": null,
    "options": ["They are the same", "`align-items` aligns individual items within their single line; `align-content` aligns the multiple lines (rows) themselves within the container", "`align-content` is for the main axis", "`align-items` only works on images"],
    "correct_answer": "`align-items` aligns individual items within their single line; `align-content` aligns the multiple lines (rows) themselves within the container",
    "explanation": "If you have a single row of items, `align-content` does absolutely nothing. It only takes effect when `flex-wrap: wrap` creates multiple rows, allowing you to pack those rows to the top, bottom, or center of the container."
  },
  {
    "id": 228,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "output-prediction",
    "topic": "justify-content values",
    "question": "Which `justify-content` value distributes the items so that the spacing between any two adjacent items is the same, but the space before the first and after the last item is exactly HALF that size?",
    "code_snippet": null,
    "options": ["space-between", "space-around", "space-evenly", "center"],
    "correct_answer": "space-around",
    "explanation": "`space-around` puts equal space on both sides of each item. This means the space between two items is double the space at the edges. (`space-evenly` makes the edge spaces exactly equal to the item spaces)."
  },
  {
    "id": 229,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "flex-direction",
    "question": "If you apply `flex-direction: row-reverse`, what happens to the visual order of the items compared to the HTML source order?",
    "code_snippet": null,
    "options": ["They remain the same", "The visual order is reversed (right-to-left), but the HTML source order and keyboard tab-navigation order remain unchanged", "The HTML source order is permanently changed", "The items are stacked vertically"],
    "correct_answer": "The visual order is reversed (right-to-left), but the HTML source order and keyboard tab-navigation order remain unchanged",
    "explanation": "Flexbox changes the visual rendering, not the DOM. This is great for RTL languages, but be careful: screen readers and keyboard users will still experience the items in the original HTML order."
  },
  {
    "id": 230,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "order property",
    "question": "What is a major accessibility concern when using the `order` property to visually rearrange flex items?",
    "code_snippet": null,
    "options": ["It makes the page load slower", "Screen readers and keyboard navigation (Tab key) will still follow the original HTML source order, creating a disconnect between what the user sees and what they interact with", "It breaks the CSS cascade", "It removes focus states"],
    "correct_answer": "Screen readers and keyboard navigation (Tab key) will still follow the original HTML source order, creating a disconnect between what the user sees and what they interact with",
    "explanation": "If you visually move the 'Submit' button to the top of a form using `order: -1`, a keyboard user tabbing through the page will still hit the bottom of the form first. Visual order should generally match DOM order for accessibility."
  },
  {
    "id": 231,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "topic": "flex-wrap",
    "question": "Fill in the blank to allow flex items to wrap to the next line, and align those multiple lines to the bottom of the container.",
    "code_snippet": ".container {\n  display: flex;\n  flex-wrap: wrap;\n  _______: flex-end;\n}",
    "options": ["align-items", "align-content", "justify-content", "vertical-align"],
    "correct_answer": "align-content",
    "explanation": "Because the items are wrapping into multiple lines, we use `align-content` to control the vertical alignment of those rows as a group within the container."
  },
  {
    "id": 232,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Intrinsic sizing",
    "question": "What does the `min-content` keyword do when used as a `flex-basis` or `width`?",
    "code_snippet": null,
    "options": ["Sets the size to 0", "Shrinks the item to the size of its largest unbreakable content (like the longest word or image)", "Expands the item to fill the container", "Hides the content"],
    "correct_answer": "Shrinks the item to the size of its largest unbreakable content (like the longest word or image)",
    "explanation": "Intrinsic sizing keywords tell the browser to look at the actual content to determine the size. `min-content` is the absolute minimum the item can be without breaking words or cropping images."
  },
  {
    "id": 233,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "topic": "flex-shrink",
    "question": "Fill in the blank to prevent a specific flex item (like a logo) from EVER shrinking, even if the container is too small and other items are compressing.",
    "code_snippet": ".logo {\n  _______: 0;\n}",
    "options": ["flex-grow", "flex-shrink", "flex-basis", "min-width"],
    "correct_answer": "flex-shrink",
    "explanation": "By default, `flex-shrink` is 1. Setting it to 0 tells the browser, 'This item is sacred. Do not compress it, no matter what.' The other items will be forced to shrink to accommodate it."
  },
  {
    "id": 234,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "topic": "gap",
    "question": "Fill in the blank to apply a 10px gap between flex rows, and a 20px gap between flex columns.",
    "code_snippet": ".container {\n  display: flex;\n  flex-wrap: wrap;\n  _______: 10px 20px;\n}",
    "options": ["margin", "padding", "gap", "spacing"],
    "correct_answer": "gap",
    "explanation": "The `gap` property accepts two values: the first is the row-gap (vertical spacing between wrapped lines), and the second is the column-gap (horizontal spacing between items)."
  },
  {
    "id": 235,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Writing modes",
    "question": "How does Flexbox handle Right-to-Left (RTL) languages like Arabic or Hebrew?",
    "code_snippet": null,
    "options": ["Flexbox breaks in RTL languages", "`flex-direction: row` automatically flows from right-to-left based on the document's `dir` attribute, making RTL layouts incredibly easy", "You must manually reverse all margins", "Flexbox only works in English"],
    "correct_answer": "`flex-direction: row` automatically flows from right-to-left based on the document's `dir` attribute, making RTL layouts incredibly easy",
    "explanation": "Flexbox is inherently direction-aware. If the HTML has `<html dir='rtl'>`, a standard `flex-direction: row` will automatically start placing items from the right edge."
  },
  {
    "id": 236,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "code-fill-in-blank",
    "topic": "Auto margins",
    "question": "Fill in the blank to perfectly center a single, fixed-width flex item horizontally within its container using auto margins.",
    "code_snippet": ".modal {\n  width: 300px;\n  margin: 0 _______;\n}",
    "options": ["center", "auto", "50%", "flex"],
    "correct_answer": "auto",
    "explanation": "Just like in standard block layout, `margin: 0 auto` works beautifully in Flexbox to center an item horizontally, provided it has a defined width that is smaller than the container."
  },
  {
    "id": 237,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Real-world patterns",
    "question": "In the classic 'Holy Grail Layout' (Header, Footer, Sidebar, Main), how do you ensure the Footer stays at the bottom of the viewport even if the Main content is very short?",
    "code_snippet": null,
    "options": ["Use `position: fixed` on the footer", "Make the body a flex column (`min-height: 100vh`), and apply `margin-top: auto` to the footer", "Use `float: bottom`", "Set the footer's height to 100%"],
    "correct_answer": "Make the body a flex column (`min-height: 100vh`), and apply `margin-top: auto` to the footer",
    "explanation": "By making the body a column flex container that is at least 100vh tall, the `margin-top: auto` on the footer absorbs all the empty vertical space, pushing the footer exactly to the bottom of the screen."
  },
  {
    "id": 238,
    "level": "advanced",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "output-prediction",
    "topic": "Real-world patterns",
    "question": "What is the standard Flexbox pattern to create a 'Sticky Footer'?",
    "code_snippet": null,
    "options": ["`body { display: flex; flex-direction: column; min-height: 100vh; } main { flex: 1; }`", "`footer { position: sticky; bottom: 0; }`", "`body { display: grid; }`", "`footer { margin-top: 100%; }`"],
    "correct_answer": "`body { display: flex; flex-direction: column; min-height: 100vh; } main { flex: 1; }`",
    "explanation": "By making the body a column flex container that is at least 100vh tall, and giving the `<main>` content area `flex: 1`, the main area will expand to fill all available space, naturally pushing the footer to the very bottom of the screen."
  },
  {
    "id": 239,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Flexbox vs Grid",
    "question": "When should you choose CSS Grid over Flexbox?",
    "code_snippet": null,
    "options": ["Never, Flexbox is superior", "When you need strict two-dimensional control over both rows and columns simultaneously, or when you want to define the overall page layout structure first", "Only for animations", "When you have less than 3 items"],
    "correct_answer": "When you need strict two-dimensional control over both rows and columns simultaneously, or when you want to define the overall page layout structure first",
    "explanation": "The golden rule: Flexbox is for the components (navbars, card contents, centering). Grid is for the overall page layout (defining the main columns and rows of the website)."
  },
  {
    "id": 240,
    "level": "intermediate",
    "module_id": "css_mod_04_flexbox",
    "module_name": "Flexbox",
    "type": "conceptual",
    "topic": "Performance",
    "question": "Is Flexbox bad for browser performance compared to older layout methods like floats?",
    "code_snippet": null,
    "options": ["Yes, it causes massive layout thrashing", "No, modern browsers have highly optimized Flexbox layout engines; it is generally faster and more efficient than float-based layouts and clearfix hacks", "Yes, it disables GPU acceleration", "Only in Internet Explorer"],
    "correct_answer": "No, modern browsers have highly optimized Flexbox layout engines; it is generally faster and more efficient than float-based layouts and clearfix hacks",
    "explanation": "Flexbox was designed from the ground up for modern web layouts. Browsers have spent over a decade optimizing its rendering pipeline. It is significantly faster and cleaner than legacy float hacks."
  }
]
