[
  {
    "id": 61,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Color Values (Named)",
    "question": "Which of the following is a valid CSS named color?",
    "code_snippet": null,
    "options": ["lightblue", "bright-red", "dark-grey", "neon-green"],
    "correct_answer": "lightblue",
    "explanation": "CSS has a predefined list of 140+ named colors (like 'red', 'tomato', 'lightblue'). Multi-word names are written as a single word without hyphens."
  },
  {
    "id": 62,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Color Values (Hex)",
    "question": "Fill in the blank to correctly define a hex color for pure red.",
    "code_snippet": ".error { color: _______; }",
    "options": ["#FF0000", "#RRGGBB", "#RED", "hex(255, 0, 0)"],
    "correct_answer": "#FF0000",
    "explanation": "Hex colors use a base-16 system. The first two digits are Red (FF = 255), the next two are Green (00 = 0), and the last two are Blue (00 = 0)."
  },
  {
    "id": 63,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Color Values (RGBA)",
    "question": "What does the 'A' stand for in the `rgba()` color function?",
    "code_snippet": null,
    "options": ["Alpha", "Amber", "Accent", "Automatic"],
    "correct_answer": "Alpha",
    "explanation": "The Alpha channel controls the opacity/transparency of the color. It takes a value between 0 (completely transparent) and 1 (completely opaque)."
  },
  {
    "id": 64,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Color Values (HSL)",
    "question": "What do the three letters in the `hsl()` color function stand for?",
    "code_snippet": null,
    "options": ["Hex, Saturation, Lightness", "Hue, Saturation, Lightness", "Hue, Style, Luminance", "Highlight, Saturation, Level"],
    "correct_answer": "Hue, Saturation, Lightness",
    "explanation": "Hue is the color degree on the color wheel (0-360). Saturation is the intensity (0% is gray, 100% is full color). Lightness is how bright it is (0% is black, 100% is white)."
  },
  {
    "id": 65,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Color Values (HSL)",
    "question": "Why do many developers prefer `hsl()` over `hex` or `rgb()` when creating color palettes?",
    "code_snippet": null,
    "options": ["It loads faster", "It is much easier to create lighter or darker variations of a base color by simply adjusting the Lightness value", "It supports more colors than RGB", "It is the only format supported by CSS Variables"],
    "correct_answer": "It is much easier to create lighter or darker variations of a base color by simply adjusting the Lightness value",
    "explanation": "With HSL, if you have a base brand color, you can instantly create a hover state by just changing the Lightness from 50% to 40%, without needing a color picker tool to figure out the new Hex code."
  },
  {
    "id": 66,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Color Values (Hex Shorthand)",
    "question": "What will be the exact output of the following CSS shorthand hex code?",
    "code_snippet": ".box { background-color: #F0F; }",
    "options": ["It throws an error", "It is equivalent to #FF00FF (Magenta)", "It is equivalent to #F0F0F0 (Light Gray)", "It sets the background to transparent"],
    "correct_answer": "It is equivalent to #FF00FF (Magenta)",
    "explanation": "A 3-digit hex code is a shorthand where each digit is doubled. `#F0F` becomes `#FF00FF`. Red is maxed, Green is zero, Blue is maxed, resulting in Magenta."
  },
  {
    "id": 67,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Absolute Units",
    "question": "What is the defining characteristic of 'Absolute Units' in CSS (like px, cm, in)?",
    "code_snippet": null,
    "options": ["They scale automatically based on the screen size", "They represent a fixed measurement that does not change relative to parent elements or viewport", "They are only used for print media", "They are relative to the root font size"],
    "correct_answer": "They represent a fixed measurement that does not change relative to parent elements or viewport",
    "explanation": "Absolute units are fixed. A 100px box will always be 100px, regardless of whether it's inside a tiny sidebar or a massive full-width container."
  },
  {
    "id": 68,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Absolute Units (px)",
    "question": "Which absolute unit is the most commonly used for screen-based web design?",
    "code_snippet": null,
    "options": ["cm", "pt", "px", "in"],
    "correct_answer": "px",
    "explanation": "Pixels (`px`) are the standard unit for screens. While technically a 'reference pixel' rather than a physical hardware pixel, it provides a consistent, predictable measurement for digital layouts."
  },
  {
    "id": 69,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Absolute Units (pt)",
    "question": "In CSS, the `pt` (point) unit is primarily intended for which medium?",
    "code_snippet": null,
    "options": ["Mobile screens", "High-resolution retina displays", "Print media (like physical paper)", "Virtual reality headsets"],
    "correct_answer": "Print media (like physical paper)",
    "explanation": "Points are a typographic unit traditionally used in print (1pt = 1/72 of an inch). In CSS, they are mostly used in `@media print` stylesheets to ensure physical documents print at the correct size."
  },
  {
    "id": 70,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Absolute Units (cm/in)",
    "question": "Why is it generally a bad idea to use `cm` or `in` for styling standard web pages?",
    "code_snippet": null,
    "options": ["They are deprecated in CSS3", "Screens have varying pixel densities (PPI/DPI), so a CSS inch won't accurately map to a physical ruler inch on the user's monitor", "They cause the browser to crash", "They only work in Internet Explorer"],
    "correct_answer": "Screens have varying pixel densities (PPI/DPI), so a CSS inch won't accurately map to a physical ruler inch on the user's monitor",
    "explanation": "Because a 24-inch monitor and a 13-inch laptop might have the exact same resolution (1920x1080), a CSS `in` will look drastically different in physical size on both screens. Stick to `px` or relative units for screens."
  },
  {
    "id": 71,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (%)",
    "question": "When you set an element's `width: 50%`, what is that percentage relative to?",
    "code_snippet": null,
    "options": ["The width of the browser window", "The width of its parent element", "The width of the screen", "The element's own original width"],
    "correct_answer": "The width of its parent element",
    "explanation": "Percentage units are relative to the parent element's dimensions. If the parent is 800px wide, `width: 50%` makes the child 400px wide."
  },
  {
    "id": 72,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (em)",
    "question": "In CSS, the `em` unit for font-size is relative to what?",
    "code_snippet": null,
    "options": ["The root `<html>` element's font-size", "The parent element's font-size", "The browser's default font-size (16px)", "The viewport width"],
    "correct_answer": "The parent element's font-size",
    "explanation": "The `em` unit is relative to the font-size of its direct parent. If the parent is 20px, `1.5em` on the child equals 30px."
  },
  {
    "id": 73,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (rem)",
    "question": "What does the 'r' in `rem` stand for, and what is it relative to?",
    "code_snippet": null,
    "options": ["'relative', relative to the parent", "'root', relative to the `<html>` element's font-size", "'ratio', relative to the viewport", "'responsive', relative to the screen width"],
    "correct_answer": "'root', relative to the `<html>` element's font-size",
    "explanation": "The `rem` (root em) unit is ALWAYS relative to the font-size of the root `<html>` element, no matter how deeply nested the target element is."
  },
  {
    "id": 74,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (em vs rem)",
    "question": "Why is `rem` generally preferred over `em` for setting global typography and spacing in modern CSS?",
    "code_snippet": null,
    "options": ["`rem` is shorter to type", "`em` compounds exponentially in nested elements, making it hard to predict; `rem` provides a consistent, predictable scale based only on the root", "`em` is deprecated", "`rem` automatically adjusts to the user's screen size"],
    "correct_answer": "`em` compounds exponentially in nested elements, making it hard to predict; `rem` provides a consistent, predictable scale based only on the root",
    "explanation": "If you nest three `div`s with `1.2em` padding, the padding gets exponentially larger with each level. `rem` prevents this 'compounding' effect, keeping your spacing math simple."
  },
  {
    "id": 75,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (Viewport)",
    "question": "What does `100vw` represent in CSS?",
    "code_snippet": null,
    "options": ["100% of the viewport's height", "100% of the viewport's width", "100 pixels", "100% of the parent element's width"],
    "correct_answer": "100% of the viewport's width",
    "explanation": "`vw` stands for Viewport Width. `1vw` is equal to 1% of the browser window's width. Therefore, `100vw` is the full width of the screen."
  },
  {
    "id": 76,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (Viewport)",
    "question": "What is the classic '100vh bug' on mobile browsers?",
    "code_snippet": null,
    "options": ["The page crashes when using 100vh", "The mobile browser's address bar and toolbar are included in the 100vh calculation, causing the bottom of the page to be pushed off-screen", "100vh doesn't work on iOS", "It makes the text unreadable"],
    "correct_answer": "The mobile browser's address bar and toolbar are included in the 100vh calculation, causing the bottom of the page to be pushed off-screen",
    "explanation": "Mobile browsers calculate `100vh` including the space taken up by the URL bar. When the user scrolls and the URL bar hides, the page suddenly jumps. (Modern CSS introduced `dvh`, `svh`, and `lvh` to fix this!)."
  },
  {
    "id": 77,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (vmin/vmax)",
    "question": "What does the `vmin` unit represent?",
    "code_snippet": null,
    "options": ["The smaller of the viewport's width or height", "The larger of the viewport's width or height", "The minimum font size allowed by the browser", "1% of the viewport's width"],
    "correct_answer": "The smaller of the viewport's width or height",
    "explanation": "`vmin` takes the smaller dimension of the viewport. If the screen is 1000px wide and 800px tall, `10vmin` is 80px (10% of 800). It's great for ensuring text fits on both portrait and landscape screens."
  },
  {
    "id": 78,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Relative Units (em calculation)",
    "question": "If the `<body>` has a `font-size: 20px`, and a `<div>` inside it has `font-size: 2em`, and a `<p>` inside the `<div>` has `font-size: 1.5em`, what is the final font-size of the `<p>` in pixels?",
    "code_snippet": null,
    "options": ["30px", "40px", "60px", "24px"],
    "correct_answer": "60px",
    "explanation": "The `<div>` is 2 * 20px (body) = 40px. The `<p>` is 1.5 * 40px (its parent, the div) = 60px. This is the 'compounding' effect of `em`."
  },
  {
    "id": 79,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Relative Units (rem calculation)",
    "question": "If the `<html>` has `font-size: 16px`, and a deeply nested `<p>` has `font-size: 2.5rem`, what is the final font-size of the `<p>` in pixels?",
    "code_snippet": null,
    "options": ["25px", "40px", "32px", "16px"],
    "correct_answer": "40px",
    "explanation": "`rem` always calculates against the root `<html>` font-size, ignoring any intermediate parent font-sizes. 2.5 * 16px = 40px."
  },
  {
    "id": 80,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Relative Units (Modern Viewport)",
    "question": "Which modern CSS viewport unit was introduced to fix the '100vh' mobile bug by representing the viewport height EXCLUDING the browser's dynamic toolbars?",
    "code_snippet": null,
    "options": ["svh", "dvh", "lvh", "pvh"],
    "correct_answer": "svh",
    "explanation": "`svh` (Small Viewport Height) assumes the browser UI is fully expanded (taking up maximum space), ensuring your content is never cut off by the address bar. (`dvh` is dynamic, `lvh` is large)."
  }
]
[
  {
    "id": 81,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "The Box Model",
    "question": "What are the four areas of the CSS Box Model, listed from the inside out?",
    "code_snippet": null,
    "options": ["Margin, Border, Padding, Content", "Content, Padding, Border, Margin", "Content, Border, Padding, Margin", "Padding, Content, Border, Margin"],
    "correct_answer": "Content, Padding, Border, Margin",
    "explanation": "Every element in CSS is a rectangular box. From the center outward, it consists of the actual Content, surrounded by Padding, then the Border, and finally the Margin separating it from other elements."
  },
  {
    "id": 82,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "The Box Model (Padding)",
    "question": "Fill in the blank to apply exactly 20 pixels of space INSIDE the element, between its content and its border.",
    "code_snippet": ".box {\n  _______: 20px;\n}",
    "options": ["margin", "padding", "spacing", "border-width"],
    "correct_answer": "padding",
    "explanation": "Padding is the transparent space inside the element, directly surrounding the content. It pushes the border outward."
  },
  {
    "id": 83,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Margin vs Padding",
    "question": "What is the primary visual difference between `margin` and `padding`?",
    "code_snippet": null,
    "options": ["Margin is inside the border; padding is outside", "Margin creates space OUTSIDE the border (between elements); padding creates space INSIDE the border (between content and border)", "They are exactly the same", "Margin accepts colors; padding does not"],
    "correct_answer": "Margin creates space OUTSIDE the border (between elements); padding creates space INSIDE the border (between content and border)",
    "explanation": "If you want a button to have more breathing room inside itself, use padding. If you want to push two buttons away from each other, use margin."
  },
  {
    "id": 84,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "box-sizing",
    "question": "What is the default value of the `box-sizing` property in all browsers?",
    "code_snippet": null,
    "options": ["border-box", "content-box", "padding-box", "margin-box"],
    "correct_answer": "content-box",
    "explanation": "By default, CSS uses `content-box`. This means if you set `width: 100px`, the *content* is 100px, but any padding or border you add will make the total rendered element LARGER than 100px."
  },
  {
    "id": 85,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "box-sizing",
    "question": "When you apply `box-sizing: border-box`, what does the `width` property include?",
    "code_snippet": null,
    "options": ["Only the content", "Content + Padding", "Content + Padding + Border", "Content + Padding + Border + Margin"],
    "correct_answer": "Content + Padding + Border",
    "explanation": "`border-box` forces the browser to include the padding and border inside the specified width. If you set `width: 200px`, the element will be exactly 200px wide on the screen, no matter how much padding or border you add."
  },
  {
    "id": 86,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "box-sizing",
    "question": "Fill in the blank with the universal CSS reset that almost every modern website uses to make the box model intuitive.",
    "code_snippet": "*, *::before, *::after {\n  _______: border-box;\n}",
    "options": ["box-model", "box-sizing", "sizing", "layout"],
    "correct_answer": "box-sizing",
    "explanation": "Applying `box-sizing: border-box` to the universal selector (`*`) and its pseudo-elements is the industry standard. It makes sizing elements infinitely easier because what you type is what you get."
  },
  {
    "id": 87,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Margin Collapse",
    "question": "What is 'Margin Collapse' in CSS?",
    "code_snippet": null,
    "options": ["When margins are set to 0", "When two vertical margins touch, they combine into a single margin equal to the larger of the two, rather than adding together", "When margins overflow the parent container", "When horizontal margins collapse to 0"],
    "correct_answer": "When two vertical margins touch, they combine into a single margin equal to the larger of the two, rather than adding together",
    "explanation": "If Block A has `margin-bottom: 30px` and Block B has `margin-top: 20px`, the space between them is NOT 50px. It collapses to just 30px (the larger value)."
  },
  {
    "id": 88,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Margin Collapse",
    "question": "Given the following CSS, what will be the exact vertical space between the two `<div>` elements?",
    "code_snippet": ".box1 { margin-bottom: 40px; }\n.box2 { margin-top: 20px; }",
    "options": ["60px", "40px", "20px", "0px"],
    "correct_answer": "40px",
    "explanation": "Because of margin collapse, the 40px and 20px margins don't add up. The browser takes the maximum of the two (40px) and uses that as the final space between the elements."
  },
  {
    "id": 89,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Margin Collapse Prevention",
    "question": "Which of the following will PREVENT vertical margin collapse between a parent and its first child element?",
    "code_snippet": null,
    "options": ["Adding a transparent border or padding to the top of the parent", "Setting the parent to `display: inline`", "Adding a `margin-top` to the parent", "Using `width: 100%` on the parent"],
    "correct_answer": "Adding a transparent border or padding to the top of the parent",
    "explanation": "Margin collapse happens when there is nothing separating the margins. Adding a border, padding, or making the parent a Flex/Grid container establishes a barrier that keeps the parent's and child's margins separate."
  },
  {
    "id": 90,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Display: block",
    "question": "Which `display` value makes an element take up the full available width of its parent and always start on a new line?",
    "code_snippet": null,
    "options": ["inline", "inline-block", "block", "flex"],
    "correct_answer": "block",
    "explanation": "Block-level elements (like `<div>`, `<p>`, `<h1>`) stretch horizontally to fill their container and force a line break before and after them."
  },
  {
    "id": 91,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Display: inline",
    "question": "Which `display` value makes an element flow horizontally with text, but ignores `width`, `height`, and vertical padding/margins?",
    "code_snippet": null,
    "options": ["block", "inline", "inline-block", "grid"],
    "correct_answer": "inline",
    "explanation": "Inline elements (like `<span>`, `<a>`, `<strong>`) only take up as much width as their content. You cannot set a specific `width` or `height` on them."
  },
  {
    "id": 92,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Display: inline-block",
    "question": "What is the main advantage of `display: inline-block`?",
    "code_snippet": null,
    "options": ["It removes the element from the DOM", "It flows inline with text like an `inline` element, but respects `width`, `height`, and vertical padding/margin like a `block` element", "It makes the element fixed to the screen", "It hides the element on mobile devices"],
    "correct_answer": "It flows inline with text like an `inline` element, but respects `width`, `height`, and vertical padding/margin like a `block` element",
    "explanation": "`inline-block` is the hybrid of block and inline. It's perfect for things like navigation links or buttons that need to sit side-by-side but require specific padding and sizing."
  },
  {
    "id": 93,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Display: none vs visibility",
    "question": "What is the difference between `display: none` and `visibility: hidden`?",
    "code_snippet": null,
    "options": ["There is no difference", "`display: none` removes the element from the layout entirely; `visibility: hidden` hides it visually but it still takes up physical space", "`visibility: hidden` removes it from the layout; `display: none` keeps its space", "`display: none` only works on images"],
    "correct_answer": "`display: none` removes the element from the layout entirely; `visibility: hidden` hides it visually but it still takes up physical space",
    "explanation": "If you use `display: none`, surrounding elements will shift to fill the gap. If you use `visibility: hidden`, the element becomes invisible, but leaves an empty 'hole' in the layout where it used to be."
  },
  {
    "id": 94,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Display: none",
    "question": "Fill in the blank to completely hide an element from the page and remove it from the document flow.",
    "code_snippet": ".secret-message {\n  _______: none;\n}",
    "options": ["visibility", "display", "opacity", "hidden"],
    "correct_answer": "display",
    "explanation": "The `display: none` property is the standard way to toggle elements on and off via JavaScript or CSS media queries."
  },
  {
    "id": 95,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Width & Height (max-width)",
    "question": "Why is `max-width: 100%` commonly applied to images in responsive CSS?",
    "code_snippet": null,
    "options": ["It makes the image exactly 100% of the screen width", "It ensures the image never grows larger than its parent container, preventing horizontal scrollbars on smaller screens", "It forces the image to be square", "It increases the image resolution"],
    "correct_answer": "It ensures the image never grows larger than its parent container, preventing horizontal scrollbars on smaller screens",
    "explanation": "If an image is naturally 1200px wide, but its container is only 800px wide, `max-width: 100%` shrinks the image down to 800px. If the container is 1500px, the image stays at its natural 1200px."
  },
  {
    "id": 96,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Width & Height (min-height)",
    "question": "Fill in the blank to ensure a container is AT LEAST the height of the viewport, but can grow taller if the content requires it.",
    "code_snippet": ".page-wrapper {\n  _______: 100vh;\n}",
    "options": ["height", "max-height", "min-height", "vh-height"],
    "correct_answer": "min-height",
    "explanation": "Using `height: 100vh` would force the container to be exactly the screen height, potentially cutting off content or creating scrollbars. `min-height: 100vh` guarantees it fills the screen but allows it to expand gracefully."
  },
  {
    "id": 97,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Overflow",
    "question": "What does `overflow: hidden` do when content exceeds the element's defined height or width?",
    "code_snippet": null,
    "options": ["It expands the element to fit the content", "It adds a scrollbar", "It clips the overflowing content, making it completely invisible and inaccessible", "It wraps the text to the next line"],
    "correct_answer": "It clips the overflowing content, making it completely invisible and inaccessible",
    "explanation": "`overflow: hidden` acts like a pair of scissors. Anything that spills outside the boundaries of the box is simply chopped off and hidden from the user."
  },
  {
    "id": 98,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Overflow",
    "question": "What is the difference between `overflow: auto` and `overflow: scroll`?",
    "code_snippet": null,
    "options": ["There is no difference", "`scroll` always shows the scrollbar (even if not needed); `auto` only shows the scrollbar if the content actually overflows", "`auto` is for horizontal, `scroll` is for vertical", "`scroll` hides the content"],
    "correct_answer": "`scroll` always shows the scrollbar (even if not needed); `auto` only shows the scrollbar if the content actually overflows",
    "explanation": "`overflow: auto` is generally preferred because it keeps the UI clean. The scrollbar only appears when the user actually needs it to see hidden content."
  },
  {
    "id": 99,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Box Model Math (content-box)",
    "question": "Assuming the default `box-sizing: content-box`, what will be the TOTAL rendered width of this element on the screen?",
    "code_snippet": ".box {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid black;\n}",
    "options": ["200px", "225px", "240px", "250px"],
    "correct_answer": "250px",
    "explanation": "With `content-box`, padding and border are added ON TOP of the width. Total = 200 (content) + 40 (left/right padding) + 10 (left/right border) = 250px."
  },
  {
    "id": 100,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Box Model Math (border-box)",
    "question": "Assuming `box-sizing: border-box` is applied, what will be the TOTAL rendered width of this element, and what is the width of the actual content area?",
    "code_snippet": ".box {\n  box-sizing: border-box;\n  width: 200px;\n  padding: 20px;\n  border: 5px solid black;\n}",
    "options": ["Total: 250px, Content: 200px", "Total: 200px, Content: 150px", "Total: 200px, Content: 200px", "Total: 150px, Content: 150px"],
    "correct_answer": "Total: 200px, Content: 150px",
    "explanation": "With `border-box`, the total width is locked to the `width` property (200px). The browser subtracts the padding (40px) and border (10px) from the inside, leaving exactly 150px for the actual content."
  }
]
[
  {
    "id": 101,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "calc()",
    "question": "What does the `calc()` function allow you to do in CSS?",
    "code_snippet": null,
    "options": ["Calculate the specificity of a selector", "Perform mathematical calculations to determine CSS property values, mixing different units", "Calculate the total number of elements in the DOM", "Compile CSS into JavaScript"],
    "correct_answer": "Perform mathematical calculations to determine CSS property values, mixing different units",
    "explanation": "`calc()` is incredibly powerful because it lets you mix units. You can subtract fixed pixels from fluid percentages, or multiply viewport widths by a number."
  },
  {
    "id": 102,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "calc()",
    "question": "Fill in the blank to correctly set an element's width to 100% of its parent minus 40 pixels.",
    "code_snippet": ".box {\n  width: _______;\n}",
    "options": ["calc(100% - 40px)", "100% - 40px", "math(100% - 40px)", "calc(100% minus 40px)"],
    "correct_answer": "calc(100% - 40px)",
    "explanation": "The `calc()` function requires the `calc()` wrapper. Note: You MUST include spaces around the `-` and `+` operators, or the browser will throw a syntax error!"
  },
  {
    "id": 103,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "calc() Math",
    "question": "Assuming the parent container is exactly 400px wide, what will be the exact rendered width of the `.box` element?",
    "code_snippet": ".box {\n  width: calc(50% + 20px);\n}",
    "options": ["200px", "220px", "240px", "It throws a syntax error"],
    "correct_answer": "220px",
    "explanation": "First, the browser calculates 50% of the 400px parent, which is 200px. Then, it adds the 20px. The final rendered width is 220px."
  },
  {
    "id": 104,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Margin Shorthand",
    "question": "When using the 4-value margin shorthand (e.g., `margin: 10px 20px 30px 40px;`), what is the order of the sides?",
    "code_snippet": null,
    "options": ["Top, Right, Bottom, Left (Clockwise)", "Top, Bottom, Left, Right", "Left, Right, Top, Bottom", "Top, Left, Bottom, Right"],
    "correct_answer": "Top, Right, Bottom, Left (Clockwise)",
    "explanation": "CSS shorthand for box model properties always follows a clockwise direction starting from the top: Top, Right, Bottom, Left. (Think: TRBL, or 'Trouble')."
  },
  {
    "id": 105,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Margin Shorthand",
    "question": "Fill in the blank to apply 10px of margin to the top and bottom, and 20px to the left and right.",
    "code_snippet": ".box {\n  margin: _______;\n}",
    "options": ["10px 20px", "20px 10px", "10px, 20px", "10px + 20px"],
    "correct_answer": "10px 20px",
    "explanation": "When you provide 2 values to a box-model shorthand, the first value applies to Top/Bottom, and the second value applies to Left/Right."
  },
  {
    "id": 106,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Auto Margins",
    "question": "What is the standard CSS trick to horizontally center a block-level element with a defined width inside its parent?",
    "code_snippet": null,
    "options": ["margin: 0 auto;", "align: center;", "text-align: center;", "position: center;"],
    "correct_answer": "margin: 0 auto;",
    "explanation": "Setting left and right margins to `auto` tells the browser to calculate the remaining horizontal space and divide it equally on both sides, perfectly centering the block."
  },
  {
    "id": 107,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Negative Margins",
    "question": "What happens when you apply a negative margin (e.g., `margin-left: -20px;`) to an element?",
    "code_snippet": null,
    "options": ["It throws a syntax error", "It pulls the element 20px to the left, potentially overlapping adjacent elements", "It shrinks the element's width by 20px", "It hides the element"],
    "correct_answer": "It pulls the element 20px to the left, potentially overlapping adjacent elements",
    "explanation": "Negative margins are perfectly valid in CSS. They pull the element in the specified direction, effectively 'eating' into the space of its neighbors or its parent."
  },
  {
    "id": 108,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "min() and max()",
    "question": "What does the `min()` CSS function do?",
    "code_snippet": null,
    "options": ["Returns the largest value from a comma-separated list", "Returns the smallest value from a comma-separated list, often used for responsive sizing", "Calculates the minimum specificity", "Sets the minimum viewport width"],
    "correct_answer": "Returns the smallest value from a comma-separated list, often used for responsive sizing",
    "explanation": "If you write `width: min(500px, 100%)`, the browser will use 500px on large screens, but on screens smaller than 500px, it will use 100% (because 100% becomes the smaller value)."
  },
  {
    "id": 109,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "clamp()",
    "question": "Fill in the blank to set a fluid font size that is AT LEAST 16px, preferably 5vw, but NO MORE than 24px.",
    "code_snippet": "h1 {\n  font-size: _______(16px, 5vw, 24px);\n}",
    "options": ["min", "max", "clamp", "range"],
    "correct_answer": "clamp",
    "explanation": "`clamp(minimum, preferred, maximum)` is the ultimate responsive CSS function. It sets a hard floor, a fluid middle, and a hard ceiling."
  },
  {
    "id": 110,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Modern Color Syntax",
    "question": "In modern CSS (Colors Level 4), how can you write the `rgb()` function using the new space-separated syntax?",
    "code_snippet": null,
    "options": ["rgb(255, 0, 0)", "rgb 255 0 0", "rgb(255 0 0)", "rgb[255, 0, 0]"],
    "correct_answer": "rgb(255 0 0)",
    "explanation": "The modern syntax drops the commas in favor of spaces. It also uses a forward slash `/` for the alpha channel: `rgb(255 0 0 / 50%)`."
  },
  {
    "id": 111,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "color-mix()",
    "question": "What does the modern `color-mix()` function do?",
    "code_snippet": null,
    "options": ["Mixes two fonts together", "Blends two colors together in a specified color space and proportion", "Mixes CSS variables", "Converts hex to rgb"],
    "correct_answer": "Blends two colors together in a specified color space and proportion",
    "explanation": "`color-mix(in srgb, red 50%, blue 50%)` allows you to create dynamic hover states or themes by blending existing colors directly in CSS without needing a preprocessor."
  },
  {
    "id": 112,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "OKLCH",
    "question": "Which modern color space is considered 'perceptually uniform', meaning a 10% change in lightness looks like a consistent 10% change to the human eye?",
    "code_snippet": null,
    "options": ["sRGB", "Hex", "OKLCH", "CMYK"],
    "correct_answer": "OKLCH",
    "explanation": "Unlike RGB or HSL, where changing the lightness can accidentally shift the hue, OKLCH (and OKLab) are designed to match human vision perfectly, making it incredible for generating accessible color palettes."
  },
  {
    "id": 113,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "ch unit",
    "question": "What does the `ch` unit represent in CSS?",
    "code_snippet": null,
    "options": ["The height of the parent element", "The width of the '0' (zero) character in the element's current font", "The width of the viewport", "1% of the parent's width"],
    "correct_answer": "The width of the '0' (zero) character in the element's current font",
    "explanation": "`ch` is incredibly useful for typography. Setting `max-width: 60ch` ensures a paragraph of text never exceeds 60 characters per line, which is the optimal length for readability."
  },
  {
    "id": 114,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Percentage Margin Gotcha",
    "question": "If you set `margin-top: 5%` on a block element, what is that 5% calculated relative to?",
    "code_snippet": null,
    "options": ["The parent element's height", "The parent element's width", "The viewport height", "The element's own font-size"],
    "correct_answer": "The parent element's width",
    "explanation": "This is a classic CSS gotcha! Percentage margins and paddings (top, bottom, left, right) are ALWAYS calculated relative to the inline-size (width) of the containing block, even for vertical margins."
  },
  {
    "id": 115,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "dvh",
    "question": "What is the purpose of the `dvh` (Dynamic Viewport Height) unit?",
    "code_snippet": null,
    "options": ["It is exactly the same as `vh`", "It dynamically adjusts based on the current state of the browser's UI (like the address bar hiding or showing), fixing the classic 100vh mobile bug", "It stands for 'double viewport height'", "It is used for 3D transforms"],
    "correct_answer": "It dynamically adjusts based on the current state of the browser's UI (like the address bar hiding or showing), fixing the classic 100vh mobile bug",
    "explanation": "`dvh` updates in real-time as the mobile browser's toolbars expand or collapse, ensuring your 100% height layouts never result in awkward scrollbars or cut-off content."
  },
  {
    "id": 116,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "CSS Variables & Units",
    "question": "Why is it a common practice to define CSS variables WITH units (e.g., `--spacing: 16px;`) rather than just numbers?",
    "code_snippet": null,
    "options": ["CSS variables cannot hold numbers without units", "It allows you to reuse the variable directly in properties or `calc()`, keeping your design tokens centralized and intuitive", "It makes the CSS file smaller", "It is required by the CSS specification"],
    "correct_answer": "It allows you to reuse the variable directly in properties or `calc()`, keeping your design tokens centralized and intuitive",
    "explanation": "If you define `--size: 16`, you have to write `font-size: calc(var(--size) * 1px)`. If you define `--size: 16px`, you can just write `font-size: var(--size)`. Including the unit is much cleaner."
  },
  {
    "id": 117,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Border Shorthand",
    "question": "Fill in the blank to correctly set a 2px solid red border using the shorthand property.",
    "code_snippet": ".box {\n  _______: 2px solid red;\n}",
    "options": ["border-style", "border-width", "border", "outline"],
    "correct_answer": "border",
    "explanation": "The `border` shorthand allows you to set the width, style, and color all in one line. The order of the three values doesn't strictly matter, but width-style-color is the standard convention."
  },
  {
    "id": 118,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "box-sizing Inheritance",
    "question": "Does the `box-sizing` property inherit from parent to child elements by default?",
    "code_snippet": null,
    "options": ["Yes, it is inherited like the `color` property", "No, it must be explicitly set on every element (usually via the universal selector `*`)", "Yes, but only for block elements", "No, it is strictly controlled by the browser's user-agent stylesheet"],
    "correct_answer": "No, it must be explicitly set on every element (usually via the universal selector `*`)",
    "explanation": "Unlike typography or color, box model properties do not inherit. This is why the global reset `*, *::before, *::after { box-sizing: border-box; }` is absolutely mandatory in modern CSS."
  },
  {
    "id": 119,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "lh and rlh units",
    "question": "What do the `lh` and `rlh` units stand for?",
    "code_snippet": null,
    "options": ["Line Height and Root Line Height", "Left Horizontal and Right Horizontal", "Large Header and Root Header", "Local Host and Remote Host"],
    "correct_answer": "Line Height and Root Line Height",
    "explanation": "`1lh` is equal to the `line-height` of the element. `1rlh` is equal to the `line-height` of the root `<html>` element. They are perfect for setting consistent vertical rhythm and spacing in typography."
  },
  {
    "id": 120,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "calc() Edge Cases",
    "question": "If you use `width: calc(100vw - 100%)`, what will the browser calculate?",
    "code_snippet": null,
    "options": ["The width of the viewport minus the width of the parent element", "It throws an error because you cannot mix viewport and percentage units", "The width of the viewport minus the element's own width", "0px"],
    "correct_answer": "The width of the viewport minus the width of the parent element",
    "explanation": "`100vw` is the full screen width. `100%` is the parent container's width. Subtracting them gives you the exact amount of horizontal space left over (useful for breaking out of a centered container to create full-bleed backgrounds)."
  }
]
[
  {
    "id": 121,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Logical Properties",
    "question": "What is the purpose of CSS Logical Properties (like `margin-inline` and `padding-block`)?",
    "code_snippet": null,
    "options": ["To make CSS load faster", "To define spacing based on the flow of text (inline/block axes) rather than physical directions (top/bottom/left/right), making RTL translations easy", "To create 3D margins", "To lock the margins so they cannot be changed by JavaScript"],
    "correct_answer": "To define spacing based on the flow of text (inline/block axes) rather than physical directions (top/bottom/left/right), making RTL translations easy",
    "explanation": "In a Left-to-Right language, `margin-inline-start` is the left margin. In a Right-to-Left language (like Arabic), it automatically becomes the right margin. This makes building multi-language websites incredibly efficient."
  },
  {
    "id": 122,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Logical Properties",
    "question": "Fill in the blank to apply 20px of padding to the top and bottom of an element, regardless of text direction.",
    "code_snippet": ".card {\n  _______: 20px;\n}",
    "options": ["padding-inline", "padding-block", "padding-vertical", "padding-y"],
    "correct_answer": "padding-block",
    "explanation": "The 'block' axis corresponds to the top and bottom in standard horizontal writing modes. `padding-block` is the logical equivalent of `padding-top` and `padding-bottom`."
  },
  {
    "id": 123,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Outline vs Border",
    "question": "What is the primary difference between `border` and `outline` in the CSS Box Model?",
    "code_snippet": null,
    "options": ["There is no difference", "`border` takes up space in the layout and affects the element's size; `outline` is drawn outside the border edge and does NOT affect the layout or element size", "`outline` is deprecated", "`border` is only for images, `outline` is for text"],
    "correct_answer": "`border` takes up space in the layout and affects the element's size; `outline` is drawn outside the border edge and does NOT affect the layout or element size",
    "explanation": "Because `outline` doesn't affect layout, it is the perfect property for focus states (the blue ring around a button when you Tab to it). It won't cause the page to 'jump' or reflow when the focus ring appears."
  },
  {
    "id": 124,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Outline Offset",
    "question": "Fill in the blank to create a gap between the element's border and its focus outline.",
    "code_snippet": "button:focus {\n  outline: 2px solid blue;\n  _______: 4px;\n}",
    "options": ["outline-gap", "outline-spacing", "outline-offset", "outline-margin"],
    "correct_answer": "outline-offset",
    "explanation": "`outline-offset` pushes the outline outward (with a positive value) or inward (with a negative value) relative to the border edge. It's a fantastic modern trick for creating beautiful, accessible focus rings."
  },
  {
    "id": 125,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Box Shadow",
    "question": "Fill in the blank to correctly apply a drop shadow with a 5px horizontal offset, 10px vertical offset, 15px blur, and a black color with 20% opacity.",
    "code_snippet": ".card {\n  _______: 5px 10px 15px rgba(0, 0, 0, 0.2);\n}",
    "options": ["drop-shadow", "box-shadow", "shadow", "elevation"],
    "correct_answer": "box-shadow",
    "explanation": "The `box-shadow` syntax is: `offset-x offset-y blur-radius color`. It is drawn outside the border and takes up no physical space in the layout."
  },
  {
    "id": 126,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Box Shadow (Inset)",
    "question": "How do you make a `box-shadow` appear INSIDE the element's borders, rather than outside?",
    "code_snippet": null,
    "options": ["Use negative offset values", "Add the `inset` keyword to the box-shadow declaration", "Use `inner-shadow` instead", "Set the blur radius to 0"],
    "correct_answer": "Add the `inset` keyword to the box-shadow declaration",
    "explanation": "Adding `inset` (e.g., `box-shadow: inset 0 5px 10px black;`) forces the shadow to be drawn inside the padding area, pointing inward. It's great for creating 'pressed' button states."
  },
  {
    "id": 127,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Text Shadow",
    "question": "Fill in the blank to apply a shadow directly to the text characters inside an element.",
    "code_snippet": "h1 {\n  _______: 2px 2px 4px rgba(0,0,0,0.5);\n}",
    "options": ["font-shadow", "text-shadow", "type-shadow", "char-shadow"],
    "correct_answer": "text-shadow",
    "explanation": "`text-shadow` applies only to the glyphs (the actual letters). Unlike `box-shadow`, it doesn't have an `inset` option, and it doesn't create a rectangular bounding box."
  },
  {
    "id": 128,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Background Size",
    "question": "What is the difference between `background-size: cover` and `background-size: contain`?",
    "code_snippet": null,
    "options": ["They are the same", "`cover` scales the image to fill the entire box (cropping if necessary); `contain` scales the image to fit entirely inside the box (leaving empty space if necessary)", "`contain` crops the image; `cover` leaves empty space", "`cover` is for videos, `contain` is for images"],
    "correct_answer": "`cover` scales the image to fill the entire box (cropping if necessary); `contain` scales the image to fit entirely inside the box (leaving empty space if necessary)",
    "explanation": "Use `cover` for hero banners where you want no empty space. Use `contain` for logos or product images where you need to see the entire image without any cropping."
  },
  {
    "id": 129,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Background Position",
    "question": "Fill in the blank to position a background image exactly in the center of its container.",
    "code_snippet": ".hero {\n  background-image: url('bg.jpg');\n  background-position: _______;\n}",
    "options": ["middle", "center", "50%", "auto"],
    "correct_answer": "center",
    "explanation": "`background-position: center` (or `center center`) aligns the image's center point with the container's center point. You can also use keywords like `top left` or percentages like `50% 50%`."
  },
  {
    "id": 130,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Opacity vs RGBA",
    "question": "What is the crucial difference between applying `opacity: 0.5` to an element versus using `background-color: rgba(0,0,0,0.5)`?",
    "code_snippet": null,
    "options": ["There is no difference", "`opacity` makes the element AND all of its children 50% transparent; `rgba` only makes the background color transparent, leaving the text and children fully opaque", "`rgba` is deprecated", "`opacity` only works on images"],
    "correct_answer": "`opacity` makes the element AND all of its children 50% transparent; `rgba` only makes the background color transparent, leaving the text and children fully opaque",
    "explanation": "If you want a semi-transparent black overlay but want the white text on top of it to remain fully readable, you MUST use `rgba()` for the background. If you use `opacity`, the text will become ghostly and hard to read."
  },
  {
    "id": 131,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Aspect Ratio",
    "question": "Fill in the blank to force a `<div>` to always maintain a 16:9 widescreen proportion, regardless of its width.",
    "code_snippet": ".video-wrapper {\n  width: 100%;\n  _______: 16 / 9;\n}",
    "options": ["ratio", "proportion", "aspect-ratio", "size-ratio"],
    "correct_answer": "aspect-ratio",
    "explanation": "The `aspect-ratio` property is a modern game-changer. It tells the browser to automatically calculate the height based on the width (or vice versa) to maintain the specified ratio, eliminating the need for the old 'padding-top percentage' hack."
  },
  {
    "id": 132,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Object Fit",
    "question": "What does the `object-fit` property do on an `<img>` or `<video>` tag?",
    "code_snippet": null,
    "options": ["It changes the file format of the media", "It controls how the content (the image/video) scales and fits inside its designated content box", "It adds a border around the image", "It compresses the image for faster loading"],
    "correct_answer": "It controls how the content (the image/video) scales and fits inside its designated content box",
    "explanation": "While `background-size` works on CSS backgrounds, `object-fit` works on 'replaced elements' like `<img>`, `<video>`, and `<canvas>`. It allows you to use `cover` or `contain` directly on HTML media tags."
  },
  {
    "id": 133,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "code-fill-in-blank",
    "topic": "Object Fit",
    "question": "Fill in the blank to make an image fill its square container completely, cropping the edges if the image's natural aspect ratio doesn't match.",
    "code_snippet": "img {\n  width: 200px;\n  height: 200px;\n  object-fit: _______;\n}",
    "options": ["contain", "cover", "fill", "stretch"],
    "correct_answer": "cover",
    "explanation": "`object-fit: cover` ensures the entire 200x200 box is filled with the image, maintaining the image's aspect ratio but cropping the overflow. (`fill` would stretch and distort the image to fit)."
  },
  {
    "id": 134,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "CSS Variables in calc()",
    "question": "How do you correctly multiply a CSS variable by a number inside a `calc()` function?",
    "code_snippet": null,
    "options": ["width: var(--base) * 2;", "width: calc(var(--base) * 2);", "width: calc(--base * 2);", "width: multiply(var(--base), 2);"],
    "correct_answer": "width: calc(var(--base) * 2);",
    "explanation": "Math operations involving CSS variables MUST be wrapped in `calc()`. If `--base` is `10px`, `calc(var(--base) * 2)` correctly evaluates to `20px`."
  },
  {
    "id": 135,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Inline Box Model",
    "question": "If you apply `width: 200px; height: 100px;` to an element with `display: inline;`, what happens?",
    "code_snippet": null,
    "options": ["The element becomes 200x100px", "The width and height declarations are completely ignored by the browser", "The browser throws a syntax error", "The element becomes a block element"],
    "correct_answer": "The width and height declarations are completely ignored by the browser",
    "explanation": "Inline elements (like `<span>`) do not respect explicit width or height properties. Their dimensions are dictated entirely by their text content and font-size. You must use `inline-block` or `block` to set dimensions."
  },
  {
    "id": 136,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Margin Auto in Flexbox",
    "question": "How does `margin: auto` behave differently inside a Flexbox or Grid container compared to standard block layout?",
    "code_snippet": null,
    "options": ["It doesn't work in Flexbox", "It absorbs ALL available extra space in that direction, pushing the element to the opposite side (often used to push a nav link to the far right)", "It centers the element vertically", "It removes the element from the DOM"],
    "correct_answer": "It absorbs ALL available extra space in that direction, pushing the element to the opposite side (often used to push a nav link to the far right)",
    "explanation": "In Flexbox, if there is 500px of free space, `margin-left: auto` on a child will consume all 500px, effectively pushing the child to the far right edge. It's a powerful alternative to `justify-content: space-between`."
  },
  {
    "id": 137,
    "level": "beginner",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "Negative Padding",
    "question": "What happens if you try to apply a negative value to padding (e.g., `padding: -20px;`)?",
    "code_snippet": null,
    "options": ["It pulls the content inward", "The declaration is invalid and ignored by the browser", "It throws a fatal error", "It shrinks the element's width"],
    "correct_answer": "The declaration is invalid and ignored by the browser",
    "explanation": "Unlike margins, which can be negative, padding CANNOT be negative. The CSS specification explicitly forbids it. If you write it, the browser will simply ignore the rule."
  },
  {
    "id": 138,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Percentage Border Radius",
    "question": "If you apply `border-radius: 50%;` to a perfectly square `<div>` (e.g., 100px by 100px), what shape does it become?",
    "code_snippet": null,
    "options": ["A square with slightly rounded corners", "A perfect circle", "An oval", "It throws an error"],
    "correct_answer": "A perfect circle",
    "explanation": "When using percentages for `border-radius`, the value is relative to the element's own dimensions. 50% of the width and 50% of the height on a square creates a perfect circle. (If the box was rectangular, it would create an oval/ellipse)."
  },
  {
    "id": 139,
    "level": "advanced",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "output-prediction",
    "topic": "Box Sizing with Percentages",
    "question": "Assuming `box-sizing: border-box`, if a parent is 400px wide, and a child has `width: 50%; padding: 20px; border: 5px solid black;`, what is the width of the child's CONTENT area?",
    "code_snippet": null,
    "options": ["200px", "150px", "100px", "250px"],
    "correct_answer": "150px",
    "explanation": "With `border-box`, the total width is 50% of 400px = 200px. The browser subtracts the padding (40px total) and border (10px total) from that 200px. 200 - 50 = 150px left for the actual content."
  },
  {
    "id": 140,
    "level": "intermediate",
    "module_id": "css_mod_02_box_model_units",
    "module_name": "Colors, Units & The Box Model",
    "type": "conceptual",
    "topic": "The Box Model Philosophy",
    "question": "Why is mastering the CSS Box Model considered the single most important foundational skill in CSS?",
    "code_snippet": null,
    "options": ["It allows you to use JavaScript faster", "Because every single element on a webpage is a rectangular box; understanding how content, padding, borders, and margins interact dictates how all layouts, alignments, and spacing ultimately work", "It is required to pass the CSS certification exam", "It prevents XSS attacks"],
    "correct_answer": "Because every single element on a webpage is a rectangular box; understanding how content, padding, borders, and margins interact dictates how all layouts, alignments, and spacing ultimately work",
    "explanation": "Whether you are using Flexbox, Grid, or absolute positioning, you are always manipulating the Box Model. If you don't understand how `box-sizing` or margin collapse works, advanced layouts will always feel like a guessing game."
  }
]
