[
  {
    "id": 141,
    "level": "beginner",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Static Positioning",
    "question": "What is the default value of the `position` property for all HTML elements?",
    "code_snippet": null,
    "options": ["relative", "absolute", "static", "fixed"],
    "correct_answer": "static",
    "explanation": "Every element is `position: static` by default. This means it follows the normal document flow, stacking block elements vertically and inline elements horizontally."
  },
  {
    "id": 142,
    "level": "beginner",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Static Positioning",
    "question": "If an element has `position: static`, what happens if you apply `top: 50px; left: 50px;` to it?",
    "code_snippet": null,
    "options": ["It moves 50px down and 50px right", "It moves 50px up and 50px left", "Nothing. The top/left/right/bottom properties are completely ignored on static elements", "It throws a CSS syntax error"],
    "correct_answer": "Nothing. The top/left/right/bottom properties are completely ignored on static elements",
    "explanation": "Offset properties (`top`, `right`, `bottom`, `left`) ONLY work on elements that have a `position` value other than `static` (i.e., relative, absolute, fixed, or sticky)."
  },
  {
    "id": 143,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "Static Positioning",
    "question": "Fill in the blank to explicitly reset an element back to the default document flow, overriding any inherited or previously applied positioning.",
    "code_snippet": ".reset-element {\n  position: _______;\n}",
    "options": ["default", "normal", "static", "initial"],
    "correct_answer": "static",
    "explanation": "While `initial` also works, `static` is the explicit keyword for the default positioning state in CSS. It ensures the element ignores any offset properties and participates in normal layout."
  },
  {
    "id": 144,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Relative Positioning",
    "question": "How does `position: relative` affect an element's space in the normal document flow?",
    "code_snippet": null,
    "options": ["It removes the element from the flow entirely", "It offsets the element visually, but it STILL takes up its original space in the normal flow", "It shrinks the element's width to 0", "It pushes all surrounding elements out of the way"],
    "correct_answer": "It offsets the element visually, but it STILL takes up its original space in the normal flow",
    "explanation": "Relative positioning is like taking a snapshot of the element's original spot, and then moving the visual rendering. The 'ghost' of the original space remains, preventing other elements from shifting."
  },
  {
    "id": 145,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "Relative Positioning",
    "question": "If you apply `position: relative; top: 20px; left: 30px;` to a `<div>`, where will it visually appear?",
    "code_snippet": null,
    "options": ["20px up and 30px left from its original spot", "20px down and 30px right from its original spot", "20px down and 30px left from its original spot", "It will not move because relative requires absolute values"],
    "correct_answer": "20px down and 30px right from its original spot",
    "explanation": "Positive `top` values push the element DOWN from its original position. Positive `left` values push the element RIGHT. It acts as if you are pulling the top-left corner downwards and rightwards."
  },
  {
    "id": 146,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Absolute Positioning",
    "question": "What is the defining characteristic of `position: absolute`?",
    "code_snippet": null,
    "options": ["It is positioned relative to the browser window", "It is removed from the normal document flow and positioned relative to its nearest positioned ancestor", "It stays in the normal flow but can be offset", "It locks the element to the center of the screen"],
    "correct_answer": "It is removed from the normal document flow and positioned relative to its nearest positioned ancestor",
    "explanation": "Absolute positioning completely removes the element from the layout. Other elements will act as if it doesn't exist, and the element will position itself based on its 'containing block'."
  },
  {
    "id": 147,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Containing Blocks",
    "question": "What is a 'Containing Block' in the context of CSS positioning?",
    "code_snippet": null,
    "options": ["A `<div>` with a specific ID", "The reference box that an absolutely or fixed positioned element uses to calculate its `top`, `right`, `bottom`, and `left` offsets", "The parent element in the HTML tree", "The `<body>` tag"],
    "correct_answer": "The reference box that an absolutely or fixed positioned element uses to calculate its `top`, `right`, `bottom`, and `left` offsets",
    "explanation": "For `position: absolute`, the containing block is the padding edge of the nearest ancestor that has a `position` value other than `static`. For `fixed`, it's the viewport."
  },
  {
    "id": 148,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to position an element 10px from the top and 10px from the right of its containing block.",
    "code_snippet": ".badge {\n  position: _______;\n  top: 10px;\n  right: 10px;\n}",
    "options": ["relative", "absolute", "fixed", "sticky"],
    "correct_answer": "absolute",
    "explanation": "To pin an element to a specific corner or edge of a parent container, you use `position: absolute` on the child, combined with offset properties."
  },
  {
    "id": 149,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "Absolute Positioning (No Positioned Ancestor)",
    "question": "What happens if you apply `position: absolute; top: 0; left: 0;` to an element, but NONE of its parent elements have a `position` value other than `static`?",
    "code_snippet": null,
    "options": ["It throws an error", "It stays in its normal document flow position", "It positions itself relative to the initial containing block (the `<html>` element / viewport)", "It positions itself relative to the `<body>` element"],
    "correct_answer": "It positions itself relative to the initial containing block (the `<html>` element / viewport)",
    "explanation": "If an absolute element has no positioned ancestors, it 'escapes' all the way up the DOM tree and uses the root `<html>` element as its containing block."
  },
  {
    "id": 150,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Creating Containing Blocks",
    "question": "What is the standard, most common way to create a 'containing block' for an absolutely positioned child element?",
    "code_snippet": null,
    "options": ["Add `display: block` to the parent", "Add `position: relative` to the parent", "Add `overflow: hidden` to the parent", "Add `width: 100%` to the parent"],
    "correct_answer": "Add `position: relative` to the parent",
    "explanation": "By adding `position: relative` to a parent, you don't change its visual layout (since you aren't applying offsets), but you successfully establish it as the new containing block for any `position: absolute` children inside it."
  },
  {
    "id": 151,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly set up a parent container so that its child `.icon` can be pinned to its bottom-right corner.",
    "code_snippet": ".card {\n  position: _______;\n}\n.icon {\n  position: absolute;\n  bottom: 10px;\n  right: 10px;\n}",
    "options": ["absolute", "fixed", "relative", "static"],
    "correct_answer": "relative",
    "explanation": "The `.card` needs to be the containing block. `position: relative` achieves this without altering the card's own placement in the normal document flow."
  },
  {
    "id": 152,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Fixed Positioning",
    "question": "What is the primary behavior of `position: fixed`?",
    "code_snippet": null,
    "options": ["It is removed from the flow and positioned relative to the viewport, staying in the exact same place even when the user scrolls", "It is removed from the flow and positioned relative to the nearest positioned ancestor", "It stays in the normal flow but becomes sticky when scrolled", "It locks the element's dimensions so they cannot be changed"],
    "correct_answer": "It is removed from the flow and positioned relative to the viewport, staying in the exact same place even when the user scrolls",
    "explanation": "Fixed elements are anchored to the browser window itself. They are commonly used for 'Back to Top' buttons, persistent navigation bars, or modal overlays."
  },
  {
    "id": 153,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Fixed Positioning Containing Block",
    "question": "What is the containing block for an element with `position: fixed`?",
    "code_snippet": null,
    "options": ["The nearest parent with `position: relative`", "The `<body>` element", "The viewport (the browser window)", "The `<html>` element only"],
    "correct_answer": "The viewport (the browser window)",
    "explanation": "Unlike `absolute`, `fixed` ignores all `position: relative` ancestors. Its containing block is always the viewport. (Note: There is a modern exception if an ancestor has a `transform`, `perspective`, or `filter` property, which creates a new containing block for fixed elements!)."
  },
  {
    "id": 154,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "Fixed Positioning Scroll",
    "question": "If you apply `position: fixed; bottom: 20px; right: 20px;` to a chat widget, what happens when the user scrolls down a long webpage?",
    "code_snippet": null,
    "options": ["The widget scrolls off the top of the screen", "The widget stays exactly 20px from the bottom and right edges of the visible screen", "The widget moves down the page with the rest of the content", "The widget disappears"],
    "correct_answer": "The widget stays exactly 20px from the bottom and right edges of the visible screen",
    "explanation": "Because it is fixed to the viewport, the widget ignores the document's scroll position and remains pinned to the user's visible screen area."
  },
  {
    "id": 155,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Absolute vs Fixed",
    "question": "What is the main difference between `position: absolute` and `position: fixed`?",
    "code_snippet": null,
    "options": ["`absolute` is for text, `fixed` is for images", "`absolute` is positioned relative to a positioned ancestor (or the `<html>`); `fixed` is ALWAYS positioned relative to the viewport", "`fixed` takes up space in the layout; `absolute` does not", "There is no difference"],
    "correct_answer": "`absolute` is positioned relative to a positioned ancestor (or the `<html>`); `fixed` is ALWAYS positioned relative to the viewport",
    "explanation": "If you put an `absolute` element inside a `relative` parent, it stays inside that parent. If you put a `fixed` element inside that same parent, it ignores the parent and pins itself to the browser window."
  },
  {
    "id": 156,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Sticky Positioning",
    "question": "How does `position: sticky` behave?",
    "code_snippet": null,
    "options": ["It is always fixed to the top of the screen", "It acts like `position: relative` until the user scrolls past a specified threshold, at which point it 'sticks' and acts like `position: fixed`", "It sticks to the nearest parent element's borders", "It prevents the user from scrolling the page"],
    "correct_answer": "It acts like `position: relative` until the user scrolls past a specified threshold, at which point it 'sticks' and acts like `position: fixed`",
    "explanation": "Sticky is a hybrid. It lives in the normal flow, but when the scroll position hits the offset you defined (like `top: 0`), it locks in place until its parent container scrolls out of view."
  },
  {
    "id": 157,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to make a navigation bar stick to the top of the screen once the user scrolls past it.",
    "code_snippet": ".navbar {\n  position: _______;\n  top: 0;\n}",
    "options": ["fixed", "absolute", "sticky", "relative"],
    "correct_answer": "sticky",
    "explanation": "The `top: 0` acts as the threshold. The navbar will scroll normally with the page, but the moment it reaches the top of the viewport (0px from the top), it will 'stick' there."
  },
  {
    "id": 158,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Sticky Positioning Requirements",
    "question": "What is a mandatory requirement for `position: sticky` to work?",
    "code_snippet": null,
    "options": ["The element must have a `z-index`", "You MUST specify at least one offset threshold (like `top`, `bottom`, `left`, or `right`)", "The parent element must have `overflow: hidden`", "The element must be a block-level element"],
    "correct_answer": "You MUST specify at least one offset threshold (like `top`, `bottom`, `left`, or `right`)",
    "explanation": "If you just write `position: sticky;` without a `top: 0` (or similar), the browser doesn't know WHEN to trigger the sticky behavior, and it will act exactly like `position: relative`."
  },
  {
    "id": 159,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Sticky Positioning Trap",
    "question": "Why might `position: sticky` fail to work even if you applied it correctly with a `top` threshold?",
    "code_snippet": null,
    "options": ["The browser doesn't support it", "A parent element has `overflow: hidden`, `overflow: scroll`, or `overflow: auto` applied to it, which breaks the sticky behavior", "The element is too wide", "The element has a background color"],
    "correct_answer": "A parent element has `overflow: hidden`, `overflow: scroll`, or `overflow: auto` applied to it, which breaks the sticky behavior",
    "explanation": "Sticky elements are confined to their scrolling container. If any ancestor has an `overflow` value that creates a new scroll context, the sticky element will stop sticking the moment it hits the boundary of that ancestor."
  },
  {
    "id": 160,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "Sticky Positioning Boundary",
    "question": "If a `position: sticky; top: 0;` element is inside a parent `<div>` that is 500px tall, what happens when the user scrolls the parent `<div>` completely off the screen?",
    "code_snippet": null,
    "options": ["It stays fixed to the top of the viewport forever", "It scrolls away with its parent, because sticky elements cannot escape their containing block", "It jumps to the bottom of the page", "It throws an error"],
    "correct_answer": "It scrolls away with its parent, because sticky elements cannot escape their containing block",
    "explanation": "A sticky element is only 'sticky' within the bounds of its direct parent container. Once the parent scrolls out of the viewport, the sticky element is forced to scroll away with it."
  }
]
[
  {
    "id": 161,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "z-index Basics",
    "question": "What is the primary requirement for the `z-index` property to work on an element?",
    "code_snippet": null,
    "options": ["The element must be a block-level element", "The element must have a `position` value other than `static` (or be a flex/grid item)", "The element must have a `display: none` property", "The element must be inside a `<div>`"],
    "correct_answer": "The element must have a `position` value other than `static` (or be a flex/grid item)",
    "explanation": "By default, `z-index` only works on positioned elements (`relative`, `absolute`, `fixed`, `sticky`). (Note: Flex and Grid items are a modern exception and accept `z-index` even if their position is `static`)."
  },
  {
    "id": 162,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "z-index Values",
    "question": "Can the `z-index` property accept negative values?",
    "code_snippet": null,
    "options": ["No, it only accepts positive integers", "Yes, a negative z-index will place the element BEHIND the background of its parent container", "Yes, but it makes the element invisible", "No, it will throw a CSS syntax error"],
    "correct_answer": "Yes, a negative z-index will place the element BEHIND the background of its parent container",
    "explanation": "Negative z-index values push the element further back in the stacking order. If you set `z-index: -1` on a child, it will render behind its parent's background color or image."
  },
  {
    "id": 163,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Stacking Contexts",
    "question": "What is a 'Stacking Context' in CSS?",
    "code_snippet": null,
    "options": ["The order in which HTML tags are written in the file", "A conceptual 3D layer that groups elements together; z-index values are only compared within the same stacking context", "The list of all CSS files loaded on the page", "The browser's memory allocation for DOM elements"],
    "correct_answer": "A conceptual 3D layer that groups elements together; z-index values are only compared within the same stacking context",
    "explanation": "Think of stacking contexts like layers in Photoshop. An element with `z-index: 100` inside a low-level stacking context will still be hidden behind an element with `z-index: 1` in a higher-level stacking context."
  },
  {
    "id": 164,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "Stacking Context Trap",
    "question": "Given the following CSS, which element will appear on TOP?",
    "code_snippet": ".parent-a { position: relative; z-index: 10; }\n.child-a { position: absolute; z-index: 999; }\n\n.parent-b { position: relative; z-index: 20; }\n.child-b { position: absolute; z-index: 1; }",
    "options": ["child-a (because 999 is greater than 1)", "child-b (because parent-b's z-index of 20 beats parent-a's 10)", "They will overlap perfectly", "The browser will throw an error"],
    "correct_answer": "child-b (because parent-b's z-index of 20 beats parent-a's 10)",
    "explanation": "This is the classic z-index trap! `child-a` and `child-b` are in DIFFERENT stacking contexts. The browser compares the parents first. Since `parent-b` (20) is higher than `parent-a` (10), everything inside `parent-b` wins, regardless of the children's z-index."
  },
  {
    "id": 165,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Creating Stacking Contexts",
    "question": "Besides using `position` and `z-index`, which of the following CSS properties will ALSO force an element to create a new stacking context?",
    "code_snippet": null,
    "options": ["margin: auto", "opacity: 0.99 (or any value less than 1)", "color: transparent", "font-size: 0"],
    "correct_answer": "opacity: 0.99 (or any value less than 1)",
    "explanation": "Many modern CSS properties inadvertently create stacking contexts. Setting `opacity` to anything less than 1, or applying a `transform`, `filter`, or `perspective`, will trap the element's z-index inside a new local context."
  },
  {
    "id": 166,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "z-index: auto vs 0",
    "question": "What is the difference between `z-index: auto` and `z-index: 0` on a positioned element?",
    "code_snippet": null,
    "options": ["There is no difference", "`auto` does NOT create a new stacking context, while `0` DOES create a new stacking context", "`0` makes the element invisible", "`auto` is for flexbox, `0` is for grid"],
    "correct_answer": "`auto` does NOT create a new stacking context, while `0` DOES create a new stacking context",
    "explanation": "Visually, they often look the same. But `z-index: 0` establishes a new stacking context (trapping children's z-index values), whereas `auto` does not. This is a crucial distinction in complex UI architectures."
  },
  {
    "id": 167,
    "level": "beginner",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Floats Basics",
    "question": "What does the `float` property do to an element?",
    "code_snippet": null,
    "options": ["It makes the element transparent", "It removes the element from the normal document flow and shifts it to the left or right, allowing inline content to wrap around it", "It locks the element to the center of the screen", "It converts the element into a flex container"],
    "correct_answer": "It removes the element from the normal document flow and shifts it to the left or right, allowing inline content to wrap around it",
    "explanation": "Originally designed for magazine-style layouts (wrapping text around images), `float` takes the element out of the normal vertical flow and pushes it to the specified side."
  },
  {
    "id": 168,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Float Collapse Problem",
    "question": "What happens to a parent `<div>` if ALL of its children are floated?",
    "code_snippet": null,
    "options": ["The parent automatically floats as well", "The parent collapses to 0 height, because floated children do not take up space in the parent's normal flow", "The parent expands to fill the screen", "The browser throws an error"],
    "correct_answer": "The parent collapses to 0 height, because floated children do not take up space in the parent's normal flow",
    "explanation": "Because floated elements are removed from the normal flow, the parent acts as if they don't exist. If there is no other content, the parent's height collapses to 0, breaking the layout."
  },
  {
    "id": 169,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "Clearing Floats",
    "question": "Fill in the blank to force an element to drop BELOW any preceding floated elements, fixing the layout collapse.",
    "code_snippet": ".footer {\n  _______: both;\n}",
    "options": ["float", "position", "clear", "stop"],
    "correct_answer": "clear",
    "explanation": "The `clear` property tells an element to move down past any floated elements. `clear: both` ensures it clears both left and right floats."
  },
  {
    "id": 170,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "The Clearfix Hack",
    "question": "What is the modern 'Clearfix Hack' used for?",
    "code_snippet": null,
    "options": ["To clear the browser cache", "To force a parent container to wrap around its floated children without adding extra HTML markup", "To remove all CSS styles from an element", "To center a floated element"],
    "correct_answer": "To force a parent container to wrap around its floated children without adding extra HTML markup",
    "explanation": "Before Flexbox, developers used the clearfix hack (applying a `::after` pseudo-element with `clear: both` to the parent) to make the parent recognize the height of its floated children."
  },
  {
    "id": 171,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "The Clearfix Hack",
    "question": "Fill in the blank to complete the standard CSS clearfix hack on a parent container.",
    "code_snippet": ".clearfix::_______ {\n  content: '';\n  display: block;\n  clear: both;\n}",
    "options": ["before", "after", "float", "clear"],
    "correct_answer": "after",
    "explanation": "The `::after` pseudo-element injects an invisible block-level element at the very end of the container. Applying `clear: both` to this ghost element forces the container to stretch and encompass the floated children."
  },
  {
    "id": 172,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Block Formatting Context (BFC)",
    "question": "How does applying `overflow: hidden` (or `auto`) to a parent fix the float collapse problem?",
    "code_snippet": null,
    "options": ["It hides the floated elements", "It forces the parent to establish a new Block Formatting Context (BFC), which internally contains the floats and calculates their height", "It converts the floats to absolute elements", "It throws an error"],
    "correct_answer": "It forces the parent to establish a new Block Formatting Context (BFC), which internally contains the floats and calculates their height",
    "explanation": "A BFC is an isolated rendering environment. One of the rules of a BFC is that it must encompass the height of its internal floated children. (Note: `display: flow-root` is the modern, semantic way to create a BFC without risking content clipping!)."
  },
  {
    "id": 173,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Floats are Legacy",
    "question": "Why are CSS floats considered 'legacy' for building page layouts?",
    "code_snippet": null,
    "options": ["They are deprecated and throw errors in modern browsers", "They were originally designed for text-wrapping, not layout; using them for columns requires messy hacks and clearfixes, which Flexbox and Grid solve natively", "They only work in Internet Explorer", "They make the website load slower"],
    "correct_answer": "They were originally designed for text-wrapping, not layout; using them for columns requires messy hacks and clearfixes, which Flexbox and Grid solve natively",
    "explanation": "Using floats to build a 3-column layout is a 15-year-old hack. Modern CSS provides Flexbox (for 1D layouts) and Grid (for 2D layouts) which are vastly superior, cleaner, and more responsive."
  },
  {
    "id": 174,
    "level": "beginner",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Modern Float Use Case",
    "question": "What is the ONE highly valid, modern use case for the `float` property?",
    "code_snippet": null,
    "options": ["Building a navigation bar", "Creating a responsive grid system", "Wrapping text around an image (like a magazine layout)", "Centering a div vertically"],
    "correct_answer": "Wrapping text around an image (like a magazine layout)",
    "explanation": "Flexbox and Grid still cannot easily replicate the 'magazine style' text-wrap around an irregular shape. For floating an image to the left with text wrapping around its right side, `float: left` is still the perfect tool."
  },
  {
    "id": 175,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "Multiple Floats",
    "question": "If you apply `float: left` to three consecutive `<div>` elements, each with a width of 30%, what will happen?",
    "code_snippet": null,
    "options": ["They will stack vertically", "They will line up horizontally next to each other on the same row", "They will overlap each other", "The third one will drop to the next line"],
    "correct_answer": "They will line up horizontally next to each other on the same row",
    "explanation": "Because 30% + 30% + 30% = 90% (which is less than 100%), all three floated elements will fit side-by-side on the same horizontal line, assuming there is no margin/padding pushing them over 100%."
  },
  {
    "id": 176,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "z-index and Flex/Grid",
    "question": "Do Flexbox and Grid items require `position: relative` to use the `z-index` property?",
    "code_snippet": null,
    "options": ["Yes, they must be positioned", "No, Flex and Grid items automatically accept `z-index` and create stacking contexts even if their position is `static`", "No, but they require `display: block`", "Yes, but only if they are nested"],
    "correct_answer": "No, Flex and Grid items automatically accept `z-index` and create stacking contexts even if their position is `static`",
    "explanation": "This is a modern CSS superpower. You no longer need to add `position: relative` just to change the z-index of a Flex or Grid child. The layout engine handles it natively."
  },
  {
    "id": 177,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to establish a Block Formatting Context (BFC) on a parent, ensuring it contains its floated children without using `overflow: hidden`.",
    "code_snippet": ".container {\n  display: _______;\n}",
    "options": ["block", "flow-root", "inline", "flex"],
    "correct_answer": "flow-root",
    "explanation": "`display: flow-root` was introduced specifically to create a BFC. It tells the browser to contain internal floats and prevent margin collapse, without any of the side effects of `overflow: hidden`."
  },
  {
    "id": 178,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Stacking Order",
    "question": "In the default CSS painting order (without z-index), which element is painted LAST (and therefore appears on top)?",
    "code_snippet": null,
    "options": ["Background and borders of the root element", "Block-level elements in normal flow", "Floated elements", "Inline-level elements in normal flow (like text and links)"],
    "correct_answer": "Inline-level elements in normal flow (like text and links)",
    "explanation": "The default stacking order from back to front is: 1. Background/borders of root. 2. Negative z-index positioned elements. 3. Block-level non-positioned. 4. Floats. 5. Block-level non-positioned (inline). 6. Inline text/links. (Positioned elements with z-index: 0/auto come after this)."
  },
  {
    "id": 179,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Transforms and Stacking",
    "question": "If you apply `transform: translateX(10px)` to an element, what side effect does it have on its stacking context?",
    "code_snippet": null,
    "options": ["It removes the element from the DOM", "It forces the element to create a new stacking context, acting similarly to `z-index: 0`", "It disables the `z-index` property on that element", "It pushes the element behind the background"],
    "correct_answer": "It forces the element to create a new stacking context, acting similarly to `z-index: 0`",
    "explanation": "Applying almost any `transform` (even a tiny one) creates a new stacking context. This means the element will paint on top of non-positioned elements and floats, which is why transformed elements sometimes unexpectedly cover up other UI components."
  },
  {
    "id": 180,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Positioning Summary",
    "question": "Which positioning value should you use to create a 'Back to Top' button that stays visible in the bottom-right corner of the screen no matter how far down the user scrolls?",
    "code_snippet": null,
    "options": ["position: relative", "position: absolute", "position: fixed", "position: sticky"],
    "correct_answer": "position: fixed",
    "explanation": "`fixed` anchors the element to the viewport. `sticky` would require the user to scroll past it first before it sticks. `absolute` would scroll away with the rest of the page content."
  }
]
[
  {
    "id": 181,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "isolation: isolate",
    "question": "What does the `isolation: isolate` property do?",
    "code_snippet": null,
    "options": ["It prevents the element from being clicked", "It forces the element to create a new stacking context, without requiring `position` or `z-index`", "It hides the element from screen readers", "It removes the element from the DOM"],
    "correct_answer": "It forces the element to create a new stacking context, without requiring `position` or `z-index`",
    "explanation": "`isolation: isolate` is the cleanest, most semantic way to create a stacking context. It's perfect for encapsulating complex UI components (like a dropdown menu) so their internal z-index values don't accidentally leak out and overlap unrelated parts of your page."
  },
  {
    "id": 182,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Stacking Context Boundaries",
    "question": "Is it possible for a child element to 'break out' or escape its parent's stacking context to appear on top of elements outside that context?",
    "code_snippet": null,
    "options": ["Yes, by using a high enough z-index like 99999", "Yes, by using `position: fixed`", "No, once a stacking context is formed, its children are permanently trapped inside it and can only be ordered relative to each other", "Yes, by using `!important`"],
    "correct_answer": "No, once a stacking context is formed, its children are permanently trapped inside it and can only be ordered relative to each other",
    "explanation": "This is the golden rule of z-index. If Parent A (z-index: 1) contains Child A (z-index: 9999), Child A will STILL be hidden behind Parent B (z-index: 2). You must fix the parent's z-index, not the child's."
  },
  {
    "id": 183,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "Absolute Stretching",
    "question": "Fill in the blank to make an absolutely positioned element stretch to fill the exact width and height of its containing block.",
    "code_snippet": ".overlay {\n  position: absolute;\n  top: 0;\n  bottom: 0;\n  left: 0;\n  _______: 0;\n}",
    "options": ["width", "right", "end", "span"],
    "correct_answer": "right",
    "explanation": "By setting all four offset properties (top, bottom, left, right) to 0, the browser stretches the absolute element to perfectly match the dimensions of its containing block. This is the standard way to create full-coverage overlays."
  },
  {
    "id": 184,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "Absolute Centering",
    "question": "Assuming the element has a defined width and height, fill in the blank to perfectly center an absolutely positioned element both vertically and horizontally.",
    "code_snippet": ".modal {\n  position: absolute;\n  top: 0; bottom: 0; left: 0; right: 0;\n  _______: auto;\n}",
    "options": ["z-index", "margin", "padding", "align"],
    "correct_answer": "margin",
    "explanation": "When an absolute element has `top/bottom/left/right: 0`, it fills the parent. By applying `margin: auto`, the browser distributes the remaining space equally on all four sides, perfectly centering the element (provided it has explicit dimensions)."
  },
  {
    "id": 185,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "The Transform Trap",
    "question": "What happens to a `position: fixed` element if one of its ancestor elements has `transform: translateX(0)` applied to it?",
    "code_snippet": null,
    "options": ["Nothing, fixed always stays on the viewport", "The fixed element stops being fixed to the viewport and instead becomes positioned relative to the transformed ancestor", "The fixed element disappears", "The browser throws a syntax error"],
    "correct_answer": "The fixed element stops being fixed to the viewport and instead becomes positioned relative to the transformed ancestor",
    "explanation": "This is a notorious CSS trap! Applying a `transform` (even a zero-value one), `filter`, or `perspective` to an element creates a new containing block. Any `position: fixed` descendants will anchor to THAT element instead of the browser window."
  },
  {
    "id": 186,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "The Transform Trap",
    "question": "Given the following CSS, where will the `.badge` element be positioned when the user scrolls the page?",
    "code_snippet": ".card { transform: scale(1.01); }\n.badge { position: fixed; top: 10px; right: 10px; }",
    "options": ["Pinned to the top-right of the browser viewport", "Pinned to the top-right of the `.card` element, scrolling away with it", "Pinned to the center of the screen", "It will not render"],
    "correct_answer": "Pinned to the top-right of the `.card` element, scrolling away with it",
    "explanation": "Because `.card` has a `transform`, it becomes the containing block for the `fixed` `.badge`. The badge is no longer fixed to the screen; it is fixed to the card and will scroll off-screen when the card does."
  },
  {
    "id": 187,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "clip-path vs Layout",
    "question": "If you apply `clip-path: circle(50%)` to a 200px square `<div>`, what happens to its space in the document layout?",
    "code_snippet": null,
    "options": ["The layout space shrinks to a circle, pushing surrounding elements inward", "The layout space remains a 200px square; only the visual rendering is clipped into a circle", "The element is removed from the DOM", "The element's width becomes 0"],
    "correct_answer": "The layout space remains a 200px square; only the visual rendering is clipped into a circle",
    "explanation": "`clip-path` is purely a visual effect. It acts like a mask over the element. The browser still reserves the original 200x200px rectangular box in the layout, preventing surrounding elements from shifting."
  },
  {
    "id": 188,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "shape-outside",
    "question": "Fill in the blank to allow text to wrap smoothly around a circular, floated image, rather than wrapping around its rectangular bounding box.",
    "code_snippet": "img.avatar {\n  float: left;\n  border-radius: 50%;\n  _______: circle(50%);\n}",
    "options": ["clip-path", "shape-outside", "wrap-mode", "float-shape"],
    "correct_answer": "shape-outside",
    "explanation": "By default, text wraps around the rectangular bounding box of a float. `shape-outside` allows you to define a geometric shape (like a circle) that the inline text will actually flow around, creating beautiful magazine-style layouts."
  },
  {
    "id": 189,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Floats & Margins",
    "question": "Do floated elements participate in vertical margin collapsing with adjacent block-level elements?",
    "code_snippet": null,
    "options": ["Yes, they collapse just like normal blocks", "No, floated elements are completely isolated from the margin collapsing of normal flow blocks", "Yes, but only if they are floated left", "No, because floats do not have margins"],
    "correct_answer": "No, floated elements are completely isolated from the margin collapsing of normal flow blocks",
    "explanation": "Because floats are removed from the normal document flow, their margins do not collapse with the margins of adjacent non-floated blocks. The spacing between them is simply the sum of their respective margins."
  },
  {
    "id": 190,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to make an element stick to the BOTTOM of its scrolling container when the user scrolls past it.",
    "code_snippet": ".footer-note {\n  position: _______;\n  bottom: 0;\n}",
    "options": ["fixed", "absolute", "sticky", "relative"],
    "correct_answer": "sticky",
    "explanation": "Just like `top: 0` makes an element stick to the top, `bottom: 0` on a sticky element means it will scroll normally until it hits the bottom edge of its parent container, at which point it locks in place."
  },
  {
    "id": 191,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "z-index Limits",
    "question": "What happens if you set an absurdly high z-index, like `z-index: 99999999999999999999;`?",
    "code_snippet": null,
    "options": ["The browser crashes", "It throws a syntax error", "The browser clamps the value to the maximum 32-bit signed integer (2147483647)", "It wraps around to a negative number"],
    "correct_answer": "The browser clamps the value to the maximum 32-bit signed integer (2147483647)",
    "explanation": "CSS z-index values are 32-bit integers. If you exceed the maximum limit, the browser simply caps it at 2,147,483,647. (Though in practice, if you need a number that high, you have a stacking context architecture problem!)."
  },
  {
    "id": 192,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "will-change",
    "question": "What side effect does applying `will-change: transform` have on an element's stacking context?",
    "code_snippet": null,
    "options": ["It destroys the stacking context", "It forces the element to create a new stacking context, similar to applying a transform", "It merges the element's stacking context with its parent", "It sets the z-index to auto"],
    "correct_answer": "It forces the element to create a new stacking context, similar to applying a transform",
    "explanation": "`will-change` tells the browser to optimize for an upcoming change. To do this efficiently, the browser creates a new stacking context and containing block. Be careful not to overuse `will-change`, as it consumes significant memory."
  },
  {
    "id": 193,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Fixed & Overflow",
    "question": "If an ancestor element has `overflow: hidden` applied to it, what happens to a descendant with `position: fixed`?",
    "code_snippet": null,
    "options": ["The fixed element gets clipped and stops being fixed to the viewport", "The fixed element ignores the overflow and stays pinned to the viewport", "The fixed element is deleted from the DOM", "The overflow property is overridden"],
    "correct_answer": "The fixed element ignores the overflow and stays pinned to the viewport",
    "explanation": "Unlike `position: sticky` (which is trapped by overflow boundaries), `position: fixed` is anchored to the viewport. It will happily render on top of the `overflow: hidden` boundary, completely ignoring it."
  },
  {
    "id": 194,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Sticky & Overflow",
    "question": "Conversely, what happens to a `position: sticky` element if an ancestor has `overflow: hidden`?",
    "code_snippet": null,
    "options": ["It stays sticky forever", "It gets clipped at the boundary of the overflow container and appears to 'stop sticking' prematurely", "It turns into `position: fixed`", "It throws an error"],
    "correct_answer": "It gets clipped at the boundary of the overflow container and appears to 'stop sticking' prematurely",
    "explanation": "Sticky elements are strictly confined to their scrolling container. If that container has `overflow: hidden`, the sticky element will be chopped off the moment it hits the edge of that container, breaking the sticky illusion."
  },
  {
    "id": 195,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Absolute & Inline",
    "question": "What happens if you apply `position: absolute` to an inline element like a `<span>`?",
    "code_snippet": null,
    "options": ["It throws an error", "It remains inline but can now accept top/left offsets", "It is transformed into a block-level box, allowing it to accept width, height, and vertical margins", "It becomes a flex container"],
    "correct_answer": "It is transformed into a block-level box, allowing it to accept width, height, and vertical margins",
    "explanation": "When an element is absolutely positioned, its `display` property is computationally forced to behave like a block-level element (specifically, `block` or `flex`/`grid` depending on the original display). It no longer flows inline with text."
  },
  {
    "id": 196,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Float & Inline",
    "question": "What happens to the `display` type of an inline element (like `<img>` or `<span>`) when you apply `float: left` to it?",
    "code_snippet": null,
    "options": ["It stays inline", "It becomes block-level", "It becomes inline-block", "It becomes hidden"],
    "correct_answer": "It becomes block-level",
    "explanation": "Just like absolute positioning, floating an element forces it to compute as a block-level box. This is why you can set a specific `width` and `height` on a floated `<img>`, even though it is technically an inline replaced element by default."
  },
  {
    "id": 197,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "code-fill-in-blank",
    "topic": "Clearing Floats",
    "question": "Fill in the blank to force an element to drop below any preceding elements that were floated to the left.",
    "code_snippet": ".sidebar-follower {\n  clear: _______;\n}",
    "options": ["left", "float", "align", "drop"],
    "correct_answer": "left",
    "explanation": "`clear: left` ensures the element is pushed down past any `float: left` elements. It will ignore `float: right` elements. (`clear: both` clears both left and right)."
  },
  {
    "id": 198,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "contain: paint",
    "question": "What does the modern `contain: paint` property do regarding stacking contexts and layout?",
    "code_snippet": null,
    "options": ["It makes the element transparent", "It guarantees that the element's descendants will never paint outside its borders, establishing a new stacking context and containing block", "It removes the element from the DOM", "It locks the element's position to static"],
    "correct_answer": "It guarantees that the element's descendants will never paint outside its borders, establishing a new stacking context and containing block",
    "explanation": "`contain: paint` is a powerful performance and layout tool. It tells the browser, 'Nothing inside this box will ever visually spill out.' This allows the browser to heavily optimize rendering, and it acts as a containing block for absolute/fixed descendants."
  },
  {
    "id": 199,
    "level": "intermediate",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "output-prediction",
    "topic": "z-index on non-positioned",
    "question": "What will be the exact output of the following CSS if applied to standard, non-positioned block elements?",
    "code_snippet": ".box1 { z-index: 999; background: red; }\n.box2 { z-index: 1; background: blue; }",
    "options": [".box1 will overlap .box2", ".box2 will overlap .box1", "z-index is ignored; they will paint in standard DOM source order", "The browser throws an error"],
    "correct_answer": "z-index is ignored; they will paint in standard DOM source order",
    "explanation": "Unless the elements are Flex/Grid items, `z-index` ONLY works on positioned elements. If they are just standard `static` blocks, the `z-index` declarations are completely ignored, and `.box2` will paint on top of `.box1` simply because it comes later in the HTML."
  },
  {
    "id": 200,
    "level": "advanced",
    "module_id": "css_mod_03_positioning",
    "module_name": "Positioning & Floats",
    "type": "conceptual",
    "topic": "Module Wrap-up",
    "question": "When debugging a complex CSS layout where elements are overlapping incorrectly, what are the TWO most important concepts you must check?",
    "code_snippet": null,
    "options": ["Font sizes and line heights", "The Containing Block (for positioning) and the Stacking Context (for z-index layering)", "The margin collapse and the float clear", "The color contrast and the opacity"],
    "correct_answer": "The Containing Block (for positioning) and the Stacking Context (for z-index layering)",
    "explanation": "If an element is in the wrong place, its Containing Block is usually not what you think it is (often due to a rogue `transform`). If it's hidden behind something else, its Stacking Context is trapping it. Mastering these two concepts solves 95% of advanced CSS bugs."
  }
]
