[
  {
    "id": 541,
    "level": "beginner",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Font Families",
    "question": "What is the purpose of providing a 'font stack' (multiple font names) in the `font-family` property?",
    "code_snippet": null,
    "options": ["To make the text load faster", "To provide fallback fonts in case the user's device doesn't have the preferred font installed", "To apply multiple fonts to the same word simultaneously", "To increase the font size"],
    "correct_answer": "To provide fallback fonts in case the user's device doesn't have the preferred font installed",
    "explanation": "The browser reads the font stack from left to right. If 'Helvetica Neue' isn't available, it tries 'Arial'. If that's missing, it falls back to the generic 'sans-serif' family guaranteed by the OS."
  },
  {
    "id": 542,
    "level": "beginner",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Font Families",
    "question": "Fill in the blank to correctly set the font family with proper fallbacks.",
    "code_snippet": "body {\n  _______-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;\n}",
    "options": ["font", "text", "type", "font-style"],
    "correct_answer": "font",
    "explanation": "The `font-family` property accepts a comma-separated list. Font names with spaces must be wrapped in quotes. The final value should always be a generic family keyword (serif, sans-serif, monospace, cursive, or fantasy)."
  },
  {
    "id": 543,
    "level": "beginner",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Generic Font Families",
    "question": "Which of the following is NOT a valid CSS generic font family keyword?",
    "code_snippet": null,
    "options": ["serif", "sans-serif", "monospace", "handwriting"],
    "correct_answer": "handwriting",
    "explanation": "The five valid generic families are: `serif`, `sans-serif`, `monospace`, `cursive`, and `fantasy`. 'Handwriting' is not a valid keyword, though `cursive` is often used for handwriting-style fonts."
  },
  {
    "id": 544,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "@font-face",
    "question": "What is the purpose of the `@font-face` at-rule in CSS?",
    "code_snippet": null,
    "options": ["To change the font size", "To define a custom font and specify the URL where the browser can download the font file", "To apply a font to the entire page", "To convert text to uppercase"],
    "correct_answer": "To define a custom font and specify the URL where the browser can download the font file",
    "explanation": "`@font-face` allows you to use any custom typeface on the web, even if the user doesn't have it installed on their device. The browser downloads the font file from your server and renders the text with it."
  },
  {
    "id": 545,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "@font-face Syntax",
    "question": "Fill in the blank to correctly define a custom font using `@font-face`.",
    "code_snippet": "@font-face {\n  font-family: 'MyCustomFont';\n  _______: url('myfont.woff2') format('woff2');\n}",
    "options": ["font-url", "font-file", "src", "href"],
    "correct_answer": "src",
    "explanation": "The `src` descriptor tells the browser where to find the font file. The `format()` hint helps the browser quickly identify the file type without downloading it first, improving performance."
  },
  {
    "id": 546,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Font Formats",
    "question": "Which modern font format is considered the gold standard for web fonts due to its superior compression and fast loading?",
    "code_snippet": null,
    "options": ["TTF (TrueType)", "OTF (OpenType)", "WOFF2 (Web Open Font Format 2)", "EOT (Embedded OpenType)"],
    "correct_answer": "WOFF2 (Web Open Font Format 2)",
    "explanation": "WOFF2 uses Brotli compression, resulting in files that are 30-50% smaller than WOFF and 60-70% smaller than TTF. It is supported by all modern browsers and should be your primary format."
  },
  {
    "id": 547,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Font Loading (FOIT)",
    "question": "What is FOIT (Flash of Invisible Text) in web font loading?",
    "code_snippet": null,
    "options": ["When the text flashes in a different color", "When the browser hides the text completely while waiting for the custom font to download, leaving a blank space", "When the font file fails to load", "When the text becomes too small to read"],
    "correct_answer": "When the browser hides the text completely while waiting for the custom font to download, leaving a blank space",
    "explanation": "FOIT is the default behavior in most browsers. The text is invisible for up to 3 seconds while the font downloads. On slow connections, this creates a frustrating blank page experience."
  },
  {
    "id": 548,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Font Loading (FOUT)",
    "question": "What is FOUT (Flash of Unstyled Text) and why is it generally preferred over FOIT?",
    "code_snippet": null,
    "options": ["When the text flashes in a different color", "When the browser immediately shows the text in a fallback system font, then swaps to the custom font once it finishes downloading", "When the font file is corrupted", "When the text overflows its container"],
    "correct_answer": "When the browser immediately shows the text in a fallback system font, then swaps to the custom font once it finishes downloading",
    "explanation": "FOUT ensures the user can start reading content immediately, even if the font isn't perfect yet. A brief font swap is far less disruptive than staring at a blank screen for 3 seconds."
  },
  {
    "id": 549,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Font Display",
    "question": "Fill in the blank to tell the browser to show fallback text immediately and swap to the custom font as soon as it loads (eliminating FOIT).",
    "code_snippet": "@font-face {\n  font-family: 'MyFont';\n  src: url('myfont.woff2') format('woff2');\n  font-_______: swap;\n}",
    "options": ["loading", "display", "render", "swap"],
    "correct_answer": "display",
    "explanation": "`font-display: swap` is the modern best practice. It gives the custom font an extremely short block period (~0ms) and an infinite swap period, ensuring text is always visible."
  },
  {
    "id": 550,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Font Display Values",
    "question": "What does `font-display: optional` do?",
    "code_snippet": null,
    "options": ["It makes the font optional for the user to download", "It gives the font an extremely short block period (~100ms); if the font isn't loaded by then, the browser uses the fallback font permanently and cancels the download", "It makes the font load only on hover", "It disables the font entirely"],
    "correct_answer": "It gives the font an extremely short block period (~100ms); if the font isn't loaded by then, the browser uses the fallback font permanently and cancels the download",
    "explanation": "`optional` is the most performance-conscious option. It says, 'If the font loads instantly, great. If not, don't bother—the user will never see the swap.' This prevents late-arriving font swaps that disrupt reading."
  },
  {
    "id": 551,
    "level": "beginner",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Font Weight",
    "question": "Fill in the blank to make text bold using the numeric font-weight value.",
    "code_snippet": "h1 {\n  font-_______: 700;\n}",
    "options": ["style", "weight", "bold", "thickness"],
    "correct_answer": "weight",
    "explanation": "Font weights range from 100 (Thin) to 900 (Black). `400` is normal, `700` is bold. Using numeric values gives you precise control over the exact weight of the typeface."
  },
  {
    "id": 552,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Font Style",
    "question": "What is the difference between `font-style: italic` and `font-style: oblique`?",
    "code_snippet": null,
    "options": ["There is no difference", "`italic` uses a specifically designed italic version of the font (with unique letterforms); `oblique` simply slants the regular font mechanically", "`oblique` is for headings, `italic` is for body text", "`italic` is deprecated"],
    "correct_answer": "`italic` uses a specifically designed italic version of the font (with unique letterforms); `oblique` simply slants the regular font mechanically",
    "explanation": "True italics are hand-crafted by the type designer with completely different letter shapes (e.g., a cursive 'a' instead of a slanted 'a'). Oblique is just the regular font tilted at an angle."
  },
  {
    "id": 553,
    "level": "beginner",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Line Height",
    "question": "Fill in the blank to set the line height to 1.6 times the font size (the recommended value for body text readability).",
    "code_snippet": "p {\n  _______-height: 1.6;\n}",
    "options": ["text", "line", "spacing", "leading"],
    "correct_answer": "line",
    "explanation": "Using a unitless number (like `1.6`) is the best practice because it acts as a multiplier. If the font-size changes via a media query, the line-height automatically scales proportionally."
  },
  {
    "id": 554,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Letter Spacing",
    "question": "What does the `letter-spacing` property control?",
    "code_snippet": null,
    "options": ["The space between words", "The space between individual characters (tracking)", "The space between lines of text", "The space between paragraphs"],
    "correct_answer": "The space between individual characters (tracking)",
    "explanation": "In typography, this is called 'tracking'. A small positive `letter-spacing` (like `0.05em`) on uppercase text dramatically improves readability and gives headings a premium, editorial feel."
  },
  {
    "id": 555,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Word Spacing",
    "question": "What does the `word-spacing` property control?",
    "code_snippet": null,
    "options": ["The space between individual letters", "The space between words (the gap created by the spacebar)", "The space between lines", "The space between paragraphs"],
    "correct_answer": "The space between words (the gap created by the spacebar)",
    "explanation": "`word-spacing` adjusts the width of the space character. It's useful for fine-tuning justified text or creating dramatic typographic effects in headlines."
  },
  {
    "id": 556,
    "level": "beginner",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Text Alignment",
    "question": "Fill in the blank to align text to both the left and right edges of the container, creating clean margins on both sides.",
    "code_snippet": ".article {\n  text-_______: justify;\n}",
    "options": ["align", "justify", "position", "flow"],
    "correct_answer": "align",
    "explanation": "`text-align: justify` stretches the spaces between words so every line (except the last) touches both edges. Note: On narrow screens, justified text can create ugly 'rivers' of white space."
  },
  {
    "id": 557,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Text Decoration",
    "question": "How do you create a custom underline with a specific color and thickness using modern CSS?",
    "code_snippet": null,
    "options": ["Use `border-bottom`", "Use `text-decoration: underline` combined with `text-decoration-color` and `text-decoration-thickness`", "Use `box-shadow`", "Use `outline`"],
    "correct_answer": "Use `text-decoration: underline` combined with `text-decoration-color` and `text-decoration-thickness`",
    "explanation": "Modern CSS has expanded `text-decoration` into a full shorthand. You can now write `text-decoration: underline wavy red 3px;` to create beautiful, custom underlines without hacks."
  },
  {
    "id": 558,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Text Transform",
    "question": "Fill in the blank to force all text inside an element to display in UPPERCASE, regardless of how it was typed in the HTML.",
    "code_snippet": ".nav-link {\n  text-_______: uppercase;\n}",
    "options": ["style", "transform", "decoration", "format"],
    "correct_answer": "transform",
    "explanation": "`text-transform` visually changes the case of the text without altering the underlying HTML. Values include `uppercase`, `lowercase`, `capitalize` (first letter of each word), and `none`."
  },
  {
    "id": 559,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Text Overflow",
    "question": "What three CSS properties must be combined to create a single-line text truncation with an ellipsis ('...')?",
    "code_snippet": null,
    "options": ["`text-overflow: ellipsis` alone is sufficient", "`white-space: nowrap`, `overflow: hidden`, and `text-overflow: ellipsis`", "`display: none`, `visibility: hidden`, and `text-overflow: ellipsis`", "`max-width: 100%`, `overflow: scroll`, and `text-overflow: clip`"],
    "correct_answer": "`white-space: nowrap`, `overflow: hidden`, and `text-overflow: ellipsis`",
    "explanation": "All three are required. `nowrap` prevents the text from wrapping to a second line. `overflow: hidden` clips the overflowing text. `text-overflow: ellipsis` adds the '...' at the cut-off point."
  },
  {
    "id": 560,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Font Shorthand",
    "question": "Fill in the blank to correctly use the `font` shorthand property to set the style, weight, size, line-height, and family in one line.",
    "code_snippet": "p {\n  _______: italic 700 16px/1.5 'Georgia', serif;\n}",
    "options": ["text", "font", "type", "typography"],
    "correct_answer": "font",
    "explanation": "The `font` shorthand follows a strict order: `font-style font-variant font-weight font-size/line-height font-family`. The size and family are mandatory; the rest are optional."
  }
]
[
  {
    "id": 561,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Variable Fonts",
    "question": "What is a 'Variable Font' in modern CSS?",
    "code_snippet": null,
    "options": ["A font that changes based on the user's language", "A single font file that contains a continuous range of styles (weight, width, slant) that can be dynamically adjusted via CSS", "A font that automatically translates to other languages", "A font that only works in dark mode"],
    "correct_answer": "A single font file that contains a continuous range of styles (weight, width, slant) that can be dynamically adjusted via CSS",
    "explanation": "Instead of downloading separate files for Regular, Bold, and Italic, a single Variable Font file contains all of them. You can set `font-weight: 625` (any number between 1 and 999) and the browser will render the exact intermediate weight."
  },
  {
    "id": 562,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "font-variation-settings",
    "question": "Fill in the blank to correctly use the low-level API to set a variable font's weight axis ('wght') to 750.",
    "code_snippet": "h1 {\n  _______-settings: 'wght' 750;\n}",
    "options": ["font-variation", "font-axis", "font-custom", "font-variable"],
    "correct_answer": "font-variation",
    "explanation": "`font-variation-settings` allows you to access the specific 4-letter 'axes' of a variable font (like 'wght' for weight, 'wdth' for width, or 'slnt' for slant). It is the most powerful way to control variable fonts."
  },
  {
    "id": 563,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Variable Fonts Performance",
    "question": "What is the primary performance benefit of using Variable Fonts over static font files?",
    "code_snippet": null,
    "options": ["They load slower but look better", "A single variable font file is often smaller than the combined size of multiple static font files (Regular, Bold, Italic), saving massive amounts of bandwidth", "They disable the browser's rendering engine", "They compress the HTML file"],
    "correct_answer": "A single variable font file is often smaller than the combined size of multiple static font files (Regular, Bold, Italic), saving massive amounts of bandwidth",
    "explanation": "If you need 5 different weights of a font, downloading one 80kb variable font is vastly superior to downloading five 60kb static files. It also enables smooth font-weight animations!"
  },
  {
    "id": 564,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "font-optical-sizing",
    "question": "What does `font-optical-sizing: auto` do in a variable font?",
    "code_snippet": null,
    "options": ["It automatically changes the font family", "It tells the browser to automatically adjust the font's optical size axis (if available) to maintain readability at different sizes (e.g., thicker strokes at small sizes)", "It calculates the file size", "It aligns the text automatically"],
    "correct_answer": "It tells the browser to automatically adjust the font's optical size axis (if available) to maintain readability at different sizes (e.g., thicker strokes at small sizes)",
    "explanation": "Historically, type designers had to cut separate 'Display' and 'Text' versions of a font. Variable fonts can include an 'opsz' axis. `font-optical-sizing: auto` lets the browser automatically pick the best optical size based on the CSS `font-size`."
  },
  {
    "id": 565,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Drop Caps (initial-letter)",
    "question": "Fill in the blank to create a magazine-style drop cap where the first letter spans 3 lines in height and sinks down by 2 lines.",
    "code_snippet": "p::first-letter {\n  _______: 3 2;\n}",
    "options": ["drop-cap", "initial-letter", "first-letter-size", "letter-span"],
    "correct_answer": "initial-letter",
    "explanation": "The `initial-letter` property is the modern, native way to create drop caps. The first value is the size (number of lines it occupies), and the second optional value is the sink (how many lines it drops down)."
  },
  {
    "id": 566,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Legacy Drop Caps",
    "question": "Before `initial-letter` existed, how did developers create drop caps?",
    "code_snippet": null,
    "options": ["Using `font-size: 500%` on the first `<span>`", "Using the `::first-letter` pseudo-element combined with `float: left`, massive `font-size`, and negative margins", "Using JavaScript to measure the text", "Using `text-transform: uppercase`"],
    "correct_answer": "Using the `::first-letter` pseudo-element combined with `float: left`, massive `font-size`, and negative margins",
    "explanation": "The `::first-letter` pseudo-element allows you to target the first character of a block. By floating it and scaling it up, developers could fake a drop cap, though it was notoriously difficult to align perfectly across browsers."
  },
  {
    "id": 567,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "font-size-adjust",
    "question": "What problem does the `font-size-adjust` property solve?",
    "code_snippet": null,
    "options": ["It prevents the font from loading", "It ensures that if a fallback font is used, its x-height matches the preferred font, preventing drastic shifts in apparent text size and layout reflow", "It adjusts the font weight automatically", "It translates the text"],
    "correct_answer": "It ensures that if a fallback font is used, its x-height matches the preferred font, preventing drastic shifts in apparent text size and layout reflow",
    "explanation": "Different fonts have different x-heights (the height of a lowercase 'x'). If your preferred font has a tall x-height and your fallback has a short one, the fallback will look tiny. `font-size-adjust` scales the fallback font so its x-height matches the primary font."
  },
  {
    "id": 568,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "font-size-adjust Syntax",
    "question": "Fill in the blank to set the font-size-adjust value to 0.5 (the approximate x-height ratio of many standard sans-serif fonts).",
    "code_snippet": "body {\n  font-family: 'CustomFont', Arial, sans-serif;\n  font-size-_______: 0.5;\n}",
    "options": ["ratio", "adjust", "scale", "height"],
    "correct_answer": "adjust",
    "explanation": "The value is the aspect ratio (x-height divided by font-size) of your primary font. If 'CustomFont' has an aspect ratio of 0.5, the browser will adjust Arial's size so its x-height perfectly matches what CustomFont's x-height would have been."
  },
  {
    "id": 569,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "text-wrap: balance",
    "question": "What does the revolutionary `text-wrap: balance` property do?",
    "code_snippet": null,
    "options": ["It centers the text", "It automatically adjusts the line breaks so that all lines of text in a paragraph or heading are roughly the same length, eliminating short orphaned lines", "It justifies the text", "It wraps text around images"],
    "correct_answer": "It automatically adjusts the line breaks so that all lines of text in a paragraph or heading are roughly the same length, eliminating short orphaned lines",
    "explanation": "This is a massive quality-of-life feature for headings. Instead of a heading breaking awkwardly like 'The Future of Web Design / Now', it will balance it to 'The Future of / Web Design Now' so the lines are visually equal."
  },
  {
    "id": 570,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "text-wrap: pretty",
    "question": "What is the purpose of `text-wrap: pretty`?",
    "code_snippet": null,
    "options": ["It makes the font bold", "It prevents 'orphans' (a single word left alone on the final line of a paragraph) by recalculating line breaks if needed", "It adds a drop shadow to the text", "It converts text to an image"],
    "correct_answer": "It prevents 'orphans' (a single word left alone on the final line of a paragraph) by recalculating line breaks if needed",
    "explanation": "While `balance` is great for short headings, `pretty` is designed for long body text. It tells the browser, 'If the last line only has one word, try to pull a word down from the previous line to make it look better.'"
  },
  {
    "id": 571,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Hanging Punctuation",
    "question": "What does `hanging-punctuation: first` do?",
    "code_snippet": null,
    "options": ["It makes the first letter larger", "It pushes opening quotation marks or apostrophes outside the left margin of the text block, so the actual letters align perfectly vertically", "It adds a hanging indent", "It removes the first punctuation mark"],
    "correct_answer": "It pushes opening quotation marks or apostrophes outside the left margin of the text block, so the actual letters align perfectly vertically",
    "explanation": "In professional book typesetting, quotes 'hang' in the margin so the text block looks like a perfect rectangle. `hanging-punctuation` brings this centuries-old print design standard to the web."
  },
  {
    "id": 572,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "OpenType (Numeric Styles)",
    "question": "What is the difference between `font-variant-numeric: lining-nums` and `oldstyle-nums`?",
    "code_snippet": null,
    "options": ["There is no difference", "`lining-nums` are all caps-height and align on the baseline (good for all-caps); `oldstyle-nums` have ascenders and descenders like lowercase letters (good for blending into body text)", "`oldstyle-nums` are deprecated", "`lining-nums` are only for math equations"],
    "correct_answer": "`lining-nums` are all caps-height and align on the baseline (good for all-caps); `oldstyle-nums` have ascenders and descenders like lowercase letters (good for blending into body text)",
    "explanation": "Oldstyle numerals (like 3, 4, 5, 7, 9 dropping below the baseline) are beautiful in paragraphs of text because they mimic the rhythm of lowercase letters. Lining numerals are uniform and better for data tables or uppercase headings."
  },
  {
    "id": 573,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "OpenType (Ligatures)",
    "question": "What does `font-variant-ligatures: common-ligatures` do?",
    "code_snippet": null,
    "options": ["It translates the text", "It replaces specific character combinations (like 'f' and 'i') with a single, beautifully designed glyph (like 'ﬁ') to prevent overlapping strokes", "It adds a line under the text", "It makes the text bold"],
    "correct_answer": "It replaces specific character combinations (like 'f' and 'i') with a single, beautifully designed glyph (like 'ﬁ') to prevent overlapping strokes",
    "explanation": "Ligatures are a hallmark of high-quality typography. Enabling them ensures that letters like 'f' and 't' don't visually crash into each other, creating a much more polished reading experience."
  },
  {
    "id": 574,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "OpenType (Small Caps)",
    "question": "Fill in the blank to display text in true, professionally drawn small capital letters (if the font supports it).",
    "code_snippet": ".acronym {\n  font-variant-_______: small-caps;\n}",
    "options": ["caps", "letters", "style", "text"],
    "correct_answer": "caps",
    "explanation": "Unlike `text-transform: uppercase` (which just scales up regular letters), `font-variant-caps: small-caps` uses the font's actual, specially designed small capital glyphs, which have correct proportions and stroke weights."
  },
  {
    "id": 575,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Text Underline Offset",
    "question": "Fill in the blank to move a text underline 4px further away from the text baseline.",
    "code_snippet": "a {\n  text-_______-offset: 4px;\n}",
    "options": ["decoration", "underline", "line", "border"],
    "correct_answer": "underline",
    "explanation": "`text-underline-offset` gives you precise control over the vertical position of the underline, allowing you to prevent it from colliding with descenders (like the tail of a 'y' or 'g')."
  },
  {
    "id": 576,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Text Decoration Skip Ink",
    "question": "What does `text-decoration-skip-ink: auto` do?",
    "code_snippet": null,
    "options": ["It removes the underline completely", "It automatically breaks the underline when it intersects with a descender (like 'p', 'q', 'y'), improving readability", "It changes the underline color", "It makes the underline dashed"],
    "correct_answer": "It automatically breaks the underline when it intersects with a descender (like 'p', 'q', 'y'), improving readability",
    "explanation": "By default, underlines cut straight through descenders, making letters hard to read. `skip-ink: auto` creates tiny gaps in the underline where the letter strokes pass through, a hallmark of premium web typography."
  },
  {
    "id": 577,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Hyphenation",
    "question": "Fill in the blank to enable automatic hyphenation of long words at the end of a line (requires the `lang` attribute in HTML).",
    "code_snippet": "p {\n  _______: auto;\n}",
    "options": ["hyphens", "break-word", "dash", "split"],
    "correct_answer": "hyphens",
    "explanation": "`hyphens: auto` tells the browser to insert hyphens (-) where words break across lines. It relies on the HTML `lang='en'` attribute to use the correct dictionary rules for hyphenation."
  },
  {
    "id": 578,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Word Break vs Overflow Wrap",
    "question": "What is the difference between `word-break: break-all` and `overflow-wrap: break-word`?",
    "code_snippet": null,
    "options": ["They are the same", "`break-all` aggressively breaks words anywhere to prevent overflow (even in normal text); `break-word` only breaks a word if it is too long to fit on the line by itself", "`break-word` is deprecated", "`break-all` is for Flexbox"],
    "correct_answer": "`break-all` aggressively breaks words anywhere to prevent overflow (even in normal text); `break-word` only breaks a word if it is too long to fit on the line by itself",
    "explanation": "`overflow-wrap: break-word` is the safe, standard way to prevent long URLs or strings from breaking your layout. `word-break: break-all` is usually reserved for CJK (Chinese/Japanese/Korean) text or specific data tables."
  },
  {
    "id": 579,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Writing Mode",
    "question": "What does `writing-mode: vertical-rl` do to a block of text?",
    "code_snippet": null,
    "options": ["It aligns the text to the right", "It changes the text flow to vertical, with lines progressing from right to left (standard for traditional Japanese/Chinese)", "It rotates the text 90 degrees", "It reverses the spelling of the words"],
    "correct_answer": "It changes the text flow to vertical, with lines progressing from right to left (standard for traditional Japanese/Chinese)",
    "explanation": "`writing-mode` completely changes the block flow direction. `vertical-rl` means vertical lines, starting on the right and moving left. `vertical-lr` moves left to right."
  },
  {
    "id": 580,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Text Orientation",
    "question": "When using `writing-mode: vertical-rl`, what does `text-orientation: upright` do to Latin (English) characters?",
    "code_snippet": null,
    "options": ["It hides them", "It rotates each individual Latin character 90 degrees so they stand upright vertically, rather than lying on their side", "It translates them to Japanese", "It makes them bold"],
    "correct_answer": "It rotates each individual Latin character 90 degrees so they stand upright vertically, rather than lying on their side",
    "explanation": "By default (`mixed`), Latin letters rotate sideways in vertical text. `text-orientation: upright` forces them to remain readable vertically, which is useful for mixing English terms into Asian vertical layouts."
  }
]
[
  {
    "id": 581,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Gradient Text (background-clip)",
    "question": "How do you make text display a background image or a CSS gradient?",
    "code_snippet": null,
    "options": ["Use `text-fill-color: gradient`", "Apply the gradient to `background-image`, set `color: transparent`, and use `background-clip: text`", "Use `text-shadow` with a gradient", "It is impossible in pure CSS"],
    "correct_answer": "Apply the gradient to `background-image`, set `color: transparent`, and use `background-clip: text`",
    "explanation": "By clipping the background to the exact shape of the text glyphs and making the text color transparent, the background gradient shines through the letters, creating a stunning gradient text effect."
  },
  {
    "id": 582,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Gradient Text Syntax",
    "question": "Fill in the blank to correctly clip a background gradient to the text.",
    "code_snippet": ".gradient-heading {\n  background: linear-gradient(to right, red, blue);\n  -webkit-background-clip: _______;\n  color: transparent;\n}",
    "options": ["text", "font", "glyphs", "letters"],
    "correct_answer": "text",
    "explanation": "The `background-clip: text` property (often requiring the `-webkit-` prefix for full browser support) restricts the background painting area to the foreground text. Remember to set `color: transparent` or the text color will paint over the gradient!"
  },
  {
    "id": 583,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Text Stroke",
    "question": "What does the `-webkit-text-stroke` property do?",
    "code_snippet": null,
    "options": ["Adds a shadow behind the text", "Draws an outline (stroke) around the outer edge of the text glyphs", "Underlines the text", "Increases the letter spacing"],
    "correct_answer": "Draws an outline (stroke) around the outer edge of the text glyphs",
    "explanation": "Text stroke is perfect for creating 'knockout' text effects, retro styles, or ensuring text remains readable when placed over a complex, busy background image."
  },
  {
    "id": 584,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "Text Stroke Syntax",
    "question": "Fill in the blank to correctly apply a 2px black outline to a heading.",
    "code_snippet": "h1 {\n  -webkit-_______: 2px black;\n  color: white;\n}",
    "options": ["text-outline", "text-stroke", "text-border", "text-edge"],
    "correct_answer": "text-stroke",
    "explanation": "`-webkit-text-stroke` is a shorthand for `-webkit-text-stroke-width` and `-webkit-text-stroke-color`. Note that the stroke is drawn centered on the edge of the glyph, meaning half of the stroke width eats into the inside of the letter."
  },
  {
    "id": 585,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Text Shadow Syntax",
    "question": "What is the correct syntax order for the `text-shadow` property?",
    "code_snippet": null,
    "options": ["color, blur, x-offset, y-offset", "x-offset, y-offset, blur-radius, color", "blur-radius, x-offset, y-offset, color", "x-offset, y-offset, color, blur-radius"],
    "correct_answer": "x-offset, y-offset, blur-radius, color",
    "explanation": "Just like `box-shadow`, `text-shadow` follows the order: horizontal offset, vertical offset, blur radius (optional), and color (optional). E.g., `text-shadow: 2px 2px 4px rgba(0,0,0,0.5);`."
  },
  {
    "id": 586,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Multiple Text Shadows",
    "question": "How do you apply multiple text shadows to a single element to create a 3D extrusion effect?",
    "code_snippet": null,
    "options": ["You can only apply one shadow", "By chaining multiple `text-shadow` values separated by commas", "By using the `+` operator between shadows", "By applying `text-shadow` to the parent and the child"],
    "correct_answer": "By chaining multiple `text-shadow` values separated by commas",
    "explanation": "You can stack dozens of shadows! E.g., `text-shadow: 1px 1px 0 #ccc, 2px 2px 0 #bbb, 3px 3px 0 #aaa;`. This creates a beautiful, retro 3D block-text effect purely in CSS."
  },
  {
    "id": 587,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "text-shadow vs filter: drop-shadow",
    "question": "What is the difference between `text-shadow` and `filter: drop-shadow()` when applied to text?",
    "code_snippet": null,
    "options": ["There is no difference", "`text-shadow` applies strictly to the text glyphs; `filter: drop-shadow()` applies to the alpha channel of the entire rendered element, including its background and borders", "`drop-shadow` is for 3D text", "`text-shadow` is deprecated"],
    "correct_answer": "`text-shadow` applies strictly to the text glyphs; `filter: drop-shadow()` applies to the alpha channel of the entire rendered rendered element, including its background and borders",
    "explanation": "If you have a text element with a background color and rounded corners, `text-shadow` only shadows the letters. `filter: drop-shadow()` will shadow the entire rectangular (or rounded) box."
  },
  {
    "id": 588,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Accessibility (Contrast Ratios)",
    "question": "According to WCAG AA standards, what is the minimum contrast ratio required for normal body text against its background?",
    "code_snippet": null,
    "options": ["1.5:1", "3:1", "4.5:1", "7:1"],
    "correct_answer": "4.5:1",
    "explanation": "Normal text requires a 4.5:1 contrast ratio. Large text (typically 18pt or 14pt bold) only requires 3:1. AAA compliance requires 7:1 for normal text. This ensures visually impaired users can read your content."
  },
  {
    "id": 589,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Accessibility (Browser Zoom)",
    "question": "Why is it considered an accessibility best practice to use `rem` or `em` for font sizes instead of `px`?",
    "code_snippet": null,
    "options": ["They load faster", "They respect the user's browser-level zoom and default font-size settings, whereas `px` locks the text to a fixed physical pixel size", "They are required by HTML5", "They prevent text from wrapping"],
    "correct_answer": "They respect the user's browser-level zoom and default font-size settings, whereas `px` locks the text to a fixed physical pixel size",
    "explanation": "If a visually impaired user sets their browser's default font size to 20px, `rem`-based layouts will scale up proportionally. `px`-based layouts will ignore the user's preference, potentially making the site unreadable."
  },
  {
    "id": 590,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "CSS Font Loading API",
    "question": "What is the purpose of the CSS Font Loading API (e.g., `document.fonts.ready`)?",
    "code_snippet": null,
    "options": ["To download fonts faster", "It allows JavaScript to detect exactly when custom web fonts have finished downloading and are ready to be rendered, preventing layout shifts", "It converts fonts to SVG", "It disables the fonts"],
    "correct_answer": "It allows JavaScript to detect exactly when custom web fonts have finished downloading and are ready to be rendered, preventing layout shifts",
    "explanation": "By using `document.fonts.ready.then(() => { ... })`, you can delay complex JavaScript layout calculations or animations until the exact moment your custom typography is fully loaded and painted."
  },
  {
    "id": 591,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "font-synthesis",
    "question": "What does `font-synthesis: none` do?",
    "code_snippet": null,
    "options": ["It disables all fonts", "It prevents the browser from artificially faking a bold or italic style if the exact weight/style isn't available in the loaded font file", "It removes the font from the DOM", "It makes the text transparent"],
    "correct_answer": "It prevents the browser from artificially faking a bold or italic style if the exact weight/style isn't available in the loaded font file",
    "explanation": "If you request `font-weight: 700` but only loaded the 400 file, the browser will mathematically 'smear' the text to fake boldness. This looks terrible. `font-synthesis: none` forces the browser to just use the 400 weight instead of ruining the typeface's design."
  },
  {
    "id": 592,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "font-synthesis Syntax",
    "question": "Fill in the blank to disable the browser's ability to synthesize fake bold and italic styles.",
    "code_snippet": "body {\n  font-_______: none;\n}",
    "options": ["synthesis", "fake", "style", "weight"],
    "correct_answer": "synthesis",
    "explanation": "`font-synthesis: none` is a crucial quality-control property for brand-heavy websites where you want absolute control over the typography and refuse to let the browser distort your chosen typeface."
  },
  {
    "id": 593,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "text-rendering (optimizeLegibility)",
    "question": "What does `text-rendering: optimizeLegibility` do?",
    "code_snippet": null,
    "options": ["It increases the font size", "It tells the browser to prioritize typographic quality (enabling kerning, ligatures, and optical sizing) over rendering speed", "It translates the text", "It adds a drop shadow"],
    "correct_answer": "It tells the browser to prioritize typographic quality (enabling kerning, ligatures, and optical sizing) over rendering speed",
    "explanation": "This property hints to the browser engine to turn on advanced OpenType features that make text look beautiful, particularly at large font sizes or in headings."
  },
  {
    "id": 594,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "text-rendering (Performance Trap)",
    "question": "Why is it considered a performance anti-pattern to apply `text-rendering: optimizeLegibility` to the entire `body` or large blocks of text?",
    "code_snippet": null,
    "options": ["It makes the text unreadable", "The complex calculations for kerning and ligatures can significantly slow down text layout and painting, causing severe jank on long pages", "It increases the file size of the font", "It disables hardware acceleration"],
    "correct_answer": "The complex calculations for kerning and ligatures can significantly slow down text layout and painting, causing severe jank on long pages",
    "explanation": "Always restrict `optimizeLegibility` to specific elements like `h1`, `h2`, or `.hero-text`. Applying it to a 5,000-word article will cause the browser to work unnecessarily hard, draining battery and freezing the UI."
  },
  {
    "id": 595,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "font-feature-settings",
    "question": "What is the difference between `font-variant-ligatures` and `font-feature-settings`?",
    "code_snippet": null,
    "options": ["They are the same", "`font-variant` is the high-level, semantic CSS API; `font-feature-settings` is the low-level API that directly passes OpenType feature tags (like 'liga', 'dlig', 'smcp') to the font engine", "`font-feature-settings` is deprecated", "`font-variant` is for Flexbox"],
    "correct_answer": "`font-variant` is the high-level, semantic CSS API; `font-feature-settings` is the low-level API that directly passes OpenType feature tags (like 'liga', 'dlig', 'smcp') to the font engine",
    "explanation": "You should almost always use `font-variant` for standard features. `font-feature-settings` is a fallback for accessing obscure, custom OpenType tags that don't have a dedicated `font-variant` property yet."
  },
  {
    "id": 596,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "code-fill-in-blank",
    "topic": "font-feature-settings Syntax",
    "question": "Fill in the blank to correctly use the low-level API to enable discretionary ligatures ('dlig') and small caps ('smcp').",
    "code_snippet": ".fancy-text {\n  font-_______: \"dlig\" 1, \"smcp\" 1;\n}",
    "options": ["variant", "feature-settings", "opentype", "ligatures"],
    "correct_answer": "feature-settings",
    "explanation": "The syntax requires the 4-letter OpenType tag in quotes, followed by a `1` (to enable) or `0` (to disable). E.g., `font-feature-settings: \"dlig\" 1;`."
  },
  {
    "id": 597,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Print Typography",
    "question": "When writing CSS for `@media print`, what is a common best practice for font families?",
    "code_snippet": null,
    "options": ["Use a monospace font", "Use a high-quality serif font (like Georgia or Times) for body text, as serifs guide the eye along printed lines", "Use the exact same web fonts as the screen", "Use a cursive font"],
    "correct_answer": "Use a high-quality serif font (like Georgia or Times) for body text, as serifs guide the eye along printed lines",
    "explanation": "Printed ink spreads slightly on paper. Serif fonts have 'feet' that help anchor the letters and guide the reader's eye horizontally across the page, making long printed documents much easier to read."
  },
  {
    "id": 598,
    "level": "intermediate",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Print Typography (Colors)",
    "question": "How should you handle text colors in a `@media print` stylesheet to save ink and ensure readability?",
    "code_snippet": null,
    "options": ["Keep all screen colors", "Force all text to pure black (`#000`) and backgrounds to white (`#fff`)", "Use grayscale for everything", "Hide all text"],
    "correct_answer": "Force all text to pure black (`#000`) and backgrounds to white (`#fff`)",
    "explanation": "Users printing a webpage usually want the information, not the brand colors. Forcing `color: black` and `background: white` saves massive amounts of printer ink and guarantees perfect contrast."
  },
  {
    "id": 599,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Variable Fonts & Animation",
    "question": "What unique animation capability do Variable Fonts provide that static fonts cannot?",
    "code_snippet": null,
    "options": ["They can change color", "They can smoothly interpolate between different font weights or widths (e.g., animating from `font-weight: 100` to `900`) without needing multiple font files", "They can translate languages", "They can change the font family entirely"],
    "correct_answer": "They can smoothly interpolate between different font weights or widths (e.g., animating from `font-weight: 100` to `900`) without needing multiple font files",
    "explanation": "Because a variable font contains the entire axis spectrum, you can use CSS `transition` or `@keyframes` to smoothly morph a font from Thin to Black, creating stunning, eye-catching typographic animations."
  },
  {
    "id": 600,
    "level": "advanced",
    "module_id": "css_mod_08_typography",
    "module_name": "Typography, Fonts & Text Effects",
    "type": "conceptual",
    "topic": "Philosophy of Web Typography",
    "question": "What is the ultimate goal of mastering CSS Typography, Fonts, and Text Effects?",
    "code_snippet": null,
    "options": ["To use as many custom fonts as possible", "To create a harmonious, accessible, and performant reading experience that guides the user's eye, establishes hierarchy, and communicates the brand's tone without them even realizing it", "To make the text as large as possible", "To replace images with text"],
    "correct_answer": "To create a harmonious, accessible, and performant reading experience that guides the user's eye, establishes hierarchy, and communicates the brand's tone without them even realizing it",
    "explanation": "Great typography is invisible. If the user is struggling to read, noticing awkward line breaks, or waiting for fonts to load, the typography has failed. Mastering these CSS properties ensures your content is consumed effortlessly."
  }
]
