[
  {
    "id": 631,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Sync vs Async",
    "question": "What is the main difference between Synchronous and Asynchronous code in JavaScript?",
    "code_snippet": null,
    "options": ["Synchronous code is faster", "Synchronous code executes line-by-line and blocks execution; Asynchronous code allows the program to continue while waiting for an operation to finish", "Asynchronous code runs on a separate thread", "There is no difference"],
    "correct_answer": "Synchronous code executes line-by-line and blocks execution; Asynchronous code allows the program to continue while waiting for an operation to finish",
    "explanation": "JavaScript is single-threaded. Synchronous code blocks the thread until it finishes. Asynchronous code (like fetching data) offloads the work, allowing the rest of your UI to remain responsive."
  },
  {
    "id": 632,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "The Call Stack",
    "question": "What is the 'Call Stack' in JavaScript?",
    "code_snippet": null,
    "options": ["A database of all variables", "A data structure that records where in the program we currently are; when a function is called, it's pushed to the stack, and when it returns, it's popped off", "A queue that holds asynchronous callbacks", "A list of all imported modules"],
    "correct_answer": "A data structure that records where in the program we currently are; when a function is called, it's pushed to the stack, and when it returns, it's popped off",
    "explanation": "The Call Stack is the core of JS execution. It operates on a Last-In-First-Out (LIFO) principle. If the stack gets too deep (like an infinite recursive function), you get a 'Maximum call stack size exceeded' error."
  },
  {
    "id": 633,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "The Call Stack",
    "question": "What will be the exact output of the following synchronous code?",
    "code_snippet": "function first() { console.log('1'); }\nfunction second() { first(); console.log('2'); }\nfunction third() { second(); console.log('3'); }\nthird();",
    "options": ["3, 2, 1", "1, 2, 3", "1, 3, 2", "2, 1, 3"],
    "correct_answer": "1, 2, 3",
    "explanation": "Because it's synchronous, `third()` calls `second()`, which calls `first()`. `first()` logs '1' and finishes. `second()` then logs '2' and finishes. Finally, `third()` logs '3'."
  },
  {
    "id": 634,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Web APIs",
    "question": "Since JavaScript is single-threaded, what handles asynchronous operations like `setTimeout` or `fetch` in the browser?",
    "code_snippet": null,
    "options": ["The Call Stack", "The JavaScript Engine (V8)", "The Web APIs (provided by the browser environment)", "The HTML Parser"],
    "correct_answer": "The Web APIs (provided by the browser environment)",
    "explanation": "The JS engine itself only executes code. Features like timers, DOM events, and HTTP requests are handled by the browser's underlying C++ Web APIs, which run on separate threads and notify JS when they are done."
  },
  {
    "id": 635,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Callback Queue",
    "question": "What is the 'Callback Queue' (or Task Queue)?",
    "code_snippet": null,
    "options": ["Where synchronous functions wait to be executed", "A queue that holds callback functions waiting to be pushed to the Call Stack once it is empty", "A list of all variables in the global scope", "The queue where CSS animations are stored"],
    "correct_answer": "A queue that holds callback functions waiting to be pushed to the Call Stack once it is empty",
    "explanation": "When a Web API (like a timer) finishes its job, it pushes the associated callback function into the Callback Queue. It waits there until the Event Loop moves it to the Call Stack."
  },
  {
    "id": 636,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "The Event Loop",
    "question": "What is the primary job of the 'Event Loop'?",
    "code_snippet": null,
    "options": ["To execute code faster", "To continuously check if the Call Stack is empty; if it is, it pushes the first callback from the Queue onto the Stack", "To loop through arrays", "To prevent memory leaks"],
    "correct_answer": "To continuously check if the Call Stack is empty; if it is, it pushes the first callback from the Queue onto the Stack",
    "explanation": "The Event Loop is the orchestrator. Its entire job is to look at the Call Stack and the Callback Queue. If the Stack is empty, it takes the first thing from the Queue and pushes it onto the Stack."
  },
  {
    "id": 637,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Event Loop Basics",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log('A');\nsetTimeout(() => console.log('B'), 0);\nconsole.log('C');",
    "options": ["A, B, C", "A, C, B", "B, A, C", "C, A, B"],
    "correct_answer": "A, C, B",
    "explanation": "'A' and 'C' are synchronous and run immediately on the Call Stack. The `setTimeout` callback is sent to the Web API, then to the Queue. Even with a 0ms delay, it must wait for the Stack to be completely empty before the Event Loop pushes it. So 'B' logs last."
  },
  {
    "id": 638,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Callbacks",
    "question": "In the context of asynchronous JavaScript, what is a 'Callback'?",
    "code_snippet": null,
    "options": ["A function that calls itself", "A function passed as an argument to another function, intended to be executed later when an async operation completes", "A return value from a Promise", "A syntax error"],
    "correct_answer": "A function passed as an argument to another function, intended to be executed later when an async operation completes",
    "explanation": "Before Promises, callbacks were the only way to handle async code. You pass a function to `setTimeout` or `fetch`, and the browser executes it later when the timer finishes or the data arrives."
  },
  {
    "id": 639,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "setTimeout",
    "question": "Fill in the blank to correctly schedule a function to run after 2000 milliseconds (2 seconds).",
    "code_snippet": "_______(() => {\n  console.log('Done!');\n}, 2000);",
    "options": ["setInterval", "setTimeout", "setTimer", "wait"],
    "correct_answer": "setTimeout",
    "explanation": "`setTimeout(callback, delayInMs)` executes a function once after a specified timer expires. `setInterval` would run it repeatedly every 2 seconds."
  },
  {
    "id": 640,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Callback Hell",
    "question": "What is 'Callback Hell' (also known as the Pyramid of Doom)?",
    "code_snippet": null,
    "options": ["When a callback function throws an error", "When you have multiple nested asynchronous callbacks, making the code deeply indented, hard to read, and difficult to debug", "When the Event Loop crashes", "When a callback is executed too many times"],
    "correct_answer": "When you have multiple nested asynchronous callbacks, making the code deeply indented, hard to read, and difficult to debug",
    "explanation": "If you need to do 3 async tasks in sequence (e.g., fetch user, then fetch posts, then fetch comments), nesting callbacks results in code that looks like a sideways pyramid. Promises and async/await were invented to solve this."
  },
  {
    "id": 641,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promises",
    "question": "What is a 'Promise' in JavaScript?",
    "code_snippet": null,
    "options": ["A guarantee that the code will run without errors", "An object representing the eventual completion (or failure) of an asynchronous operation", "A synchronous function that returns immediately", "A method to pause the execution of code"],
    "correct_answer": "An object representing the eventual completion (or failure) of an asynchronous operation",
    "explanation": "A Promise is a placeholder for a value that doesn't exist yet. It allows you to attach `.then()` and `.catch()` handlers to deal with the result when it eventually arrives, avoiding nested callbacks."
  },
  {
    "id": 642,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise States",
    "question": "What are the three possible states of a Promise?",
    "code_snippet": null,
    "options": ["start, middle, end", "pending, fulfilled, rejected", "open, closed, error", "loading, success, failure"],
    "correct_answer": "pending, fulfilled, rejected",
    "explanation": "A Promise starts as 'pending'. Once the async operation finishes, it either succeeds and becomes 'fulfilled' (resolved), or it fails and becomes 'rejected'. Once fulfilled or rejected, it is 'settled' and cannot change states again."
  },
  {
    "id": 643,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Promise Constructor",
    "question": "Fill in the blank to correctly create a new Promise that resolves with the number 42.",
    "code_snippet": "const myPromise = new Promise((resolve, reject) => {\n  _______(42);\n});",
    "options": ["fulfill", "resolve", "return", "success"],
    "correct_answer": "resolve",
    "explanation": "The Promise constructor takes an executor function with two parameters: `resolve` and `reject`. Calling `resolve(value)` changes the state to fulfilled and passes the value to the `.then()` handler."
  },
  {
    "id": 644,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Promise .then()",
    "question": "Fill in the blank to correctly handle the resolved value of a Promise.",
    "code_snippet": "fetchData()._______(data => {\n  console.log(data);\n});",
    "options": [".catch()", ".then()", ".finally()", ".resolve()"],
    "correct_answer": ".then()",
    "explanation": "The `.then()` method is called when a Promise is successfully fulfilled. It receives the resolved value as its argument."
  },
  {
    "id": 645,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Microtask Queue",
    "question": "What is the 'Microtask Queue' (or Job Queue)?",
    "code_snippet": null,
    "options": ["Where `setTimeout` callbacks wait", "A higher-priority queue for Promise callbacks (`.then`, `.catch`, `.finally`) and `queueMicrotask()`", "Where DOM events are stored", "A deprecated feature from ES5"],
    "correct_answer": "A higher-priority queue for Promise callbacks (`.then`, `.catch`, `.finally`) and `queueMicrotask()`",
    "explanation": "The Event Loop processes the Microtask Queue BEFORE the Macrotask Queue (Callback Queue). This means Promise callbacks will always run before `setTimeout` callbacks, even if the timeout is 0ms."
  },
  {
    "id": 646,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Microtask vs Macrotask",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');",
    "options": ["1, 2, 3, 4", "1, 4, 3, 2", "1, 4, 2, 3", "1, 3, 4, 2"],
    "correct_answer": "1, 4, 3, 2",
    "explanation": "1. '1' and '4' are synchronous (Call Stack). 2. '3' is a Promise callback (Microtask Queue), which runs next. 3. '2' is a setTimeout callback (Macrotask Queue), which runs last."
  },
  {
    "id": 647,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Promise .catch()",
    "question": "Fill in the blank to correctly handle an error if the Promise is rejected.",
    "code_snippet": "fetchData()\n  .then(data => console.log(data))\n  ._______(error => console.error('Failed!', error));",
    "options": ["error", "catch", "reject", "fail"],
    "correct_answer": "catch",
    "explanation": "The `.catch()` method is used to handle rejected Promises. It is essentially an alias for `.then(null, rejectionHandler)`."
  },
  {
    "id": 648,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise .catch()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const p = new Promise((resolve, reject) => {\n  reject('Error!');\n});\np.then(val => console.log('Success:', val))\n  .catch(err => console.log('Caught:', err));",
    "options": ["Success: Error!", "Caught: Error!", "undefined", "Unhandled Promise Rejection"],
    "correct_answer": "Caught: Error!",
    "explanation": "Because the Promise executor calls `reject('Error!')`, the Promise state becomes rejected. The `.then()` block is skipped, and the `.catch()` block catches the error and logs it."
  },
  {
    "id": 649,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise.resolve()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "Promise.resolve('Hello')\n  .then(val => val + ' World')\n  .then(val => console.log(val));",
    "options": ["Hello", "Hello World", "undefined", "Error"],
    "correct_answer": "Hello World",
    "explanation": "`Promise.resolve('Hello')` creates an immediately fulfilled Promise. The first `.then()` receives 'Hello', appends ' World', and returns it. The second `.then()` receives that new string and logs it. This is called Promise Chaining."
  },
  {
    "id": 650,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "clearTimeout",
    "question": "Fill in the blank to cancel a scheduled timeout before it executes.",
    "code_snippet": "const timerId = setTimeout(() => console.log('Hi'), 5000);\n_______(timerId);",
    "options": ["stopTimeout", "cancelTimeout", "clearTimeout", "endTimer"],
    "correct_answer": "clearTimeout",
    "explanation": "`setTimeout` returns a unique numeric ID. You can pass this ID to `clearTimeout(id)` to cancel the timer before it fires."
  }
]
[
  {
    "id": 651,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "async/await Basics",
    "question": "What does adding the `async` keyword before a function declaration do?",
    "code_snippet": null,
    "options": ["It makes the function run faster", "It guarantees the function will return a Promise, even if you return a plain value", "It allows the function to run on a separate thread", "It prevents the function from throwing errors"],
    "correct_answer": "It guarantees the function will return a Promise, even if you return a plain value",
    "explanation": "An `async` function always returns a Promise. If you return a normal value (like `return 42;`), JavaScript automatically wraps it in a resolved Promise: `Promise.resolve(42)`."
  },
  {
    "id": 652,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "async/await Basics",
    "question": "Fill in the blank to correctly declare an asynchronous arrow function.",
    "code_snippet": "const fetchData = _______ () => {\n  // async code here\n};",
    "options": ["async", "await", "promise", "defer"],
    "correct_answer": "async",
    "explanation": "The `async` keyword is placed before the parameter list to define an asynchronous function, whether it's a standard function or an arrow function."
  },
  {
    "id": 653,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "async/await Basics",
    "question": "What does the `await` keyword do when placed before a Promise?",
    "code_snippet": null,
    "options": ["It stops the entire JavaScript program", "It pauses the execution of the async function until the Promise settles, then returns the resolved value", "It converts the Promise into a synchronous value permanently", "It rejects the Promise"],
    "correct_answer": "It pauses the execution of the async function until the Promise settles, then returns the resolved value",
    "explanation": "`await` only pauses the *async function* it is inside of, not the whole program. The rest of the script continues to run, making it non-blocking. Once the Promise resolves, the function resumes."
  },
  {
    "id": 654,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "async/await Basics",
    "question": "Fill in the blank to correctly wait for the Promise to resolve and assign its value to `data`.",
    "code_snippet": "async function loadData() {\n  const data = _______ fetchUserData();\n  console.log(data);\n}",
    "options": ["async", "await", "resolve", "yield"],
    "correct_answer": "await",
    "explanation": "The `await` keyword is used inside an `async` function to wait for a Promise to resolve and extract its fulfilled value."
  },
  {
    "id": 655,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "async/await Basics",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "async function getValue() {\n  return 42;\n}\ngetValue().then(val => console.log(val));",
    "options": ["42", "Promise { 42 }", "undefined", "Error"],
    "correct_answer": "42",
    "explanation": "Because the function is `async`, the `return 42` is automatically wrapped in `Promise.resolve(42)`. The `.then()` correctly extracts the value 42 and logs it."
  },
  {
    "id": 656,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "async/await Basics",
    "question": "Where is the `await` keyword allowed to be used in standard JavaScript?",
    "code_snippet": null,
    "options": ["Anywhere in any function", "Only inside the body of an `async` function (or at the top level of ES Modules)", "Only inside `.then()` blocks", "Only inside `setTimeout`"],
    "correct_answer": "Only inside the body of an `async` function (or at the top level of ES Modules)",
    "explanation": "If you try to use `await` inside a normal, non-async function, JavaScript will throw a SyntaxError. (Note: Top-level await is allowed in ES Modules, but not in standard scripts)."
  },
  {
    "id": 657,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "async/await Basics",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "async function test() {\n  console.log('A');\n  await Promise.resolve();\n  console.log('B');\n}\ntest();\nconsole.log('C');",
    "options": ["A, B, C", "A, C, B", "C, A, B", "B, A, C"],
    "correct_answer": "A, C, B",
    "explanation": "'A' logs synchronously. The `await` pauses the async function and yields control back to the main thread. 'C' logs synchronously. Once the Call Stack is empty, the microtask resumes the async function, and 'B' logs."
  },
  {
    "id": 658,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Error Handling",
    "question": "Which block is used to catch errors from rejected Promises when using `async/await`?",
    "code_snippet": "async function fetchData() {\n  _______ {\n    const data = await getAPI();\n  } catch (error) {\n    console.error(error);\n  }\n}",
    "options": ["try", "attempt", "check", "promise"],
    "correct_answer": "try",
    "explanation": "When using `async/await`, the standard `try...catch` block is the correct and cleanest way to handle Promise rejections, replacing the need for `.catch()`."
  },
  {
    "id": 659,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Error Handling",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "async function fail() {\n  try {\n    await Promise.reject('Oops!');\n  } catch (e) {\n    console.log('Caught:', e);\n  }\n}\nfail();",
    "options": ["Oops!", "Caught: Oops!", "Unhandled Promise Rejection", "undefined"],
    "correct_answer": "Caught: Oops!",
    "explanation": "The `await` throws the rejected value as an error. The `catch` block immediately catches it, preventing an Unhandled Promise Rejection, and logs 'Caught: Oops!'."
  },
  {
    "id": 660,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Error Handling",
    "question": "If an `async` function throws a standard error (e.g., `throw new Error('Fail')`), what happens to the Promise returned by that function?",
    "code_snippet": null,
    "options": ["The Promise resolves with the error", "The Promise is rejected with that error", "The program crashes immediately", "The error is ignored"],
    "correct_answer": "The Promise is rejected with that error",
    "explanation": "Any error thrown inside an `async` function (whether via `throw` or a rejected `await`) automatically causes the Promise returned by that function to be rejected."
  },
  {
    "id": 661,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise Combinators",
    "question": "What does `Promise.all()` do?",
    "code_snippet": null,
    "options": ["Runs promises sequentially", "Takes an array of Promises and returns a single Promise that resolves when ALL of them have fulfilled, or rejects if ANY of them reject", "Returns the fastest promise", "Cancels all pending promises"],
    "correct_answer": "Takes an array of Promises and returns a single Promise that resolves when ALL of them have fulfilled, or rejects if ANY of them reject",
    "explanation": "`Promise.all()` is perfect for running multiple independent async operations in parallel and waiting for all of them to finish before proceeding."
  },
  {
    "id": 662,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise Combinators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const p1 = Promise.resolve(1);\nconst p2 = Promise.resolve(2);\nconst p3 = Promise.resolve(3);\nPromise.all([p1, p2, p3]).then(results => console.log(results));",
    "options": ["1, 2, 3", "[1, 2, 3]", "6", "undefined"],
    "correct_answer": "[1, 2, 3]",
    "explanation": "`Promise.all()` resolves with an array of the fulfilled values, maintaining the exact same order as the input array."
  },
  {
    "id": 663,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise Combinators",
    "question": "If you pass 5 promises to `Promise.all()` and the 2nd one rejects, what happens?",
    "code_snippet": null,
    "options": ["It waits for the other 4 to finish, then rejects", "It rejects immediately with the error from the 2nd promise, ignoring the results of the others", "It resolves with the 4 successful ones and ignores the failed one", "It throws a SyntaxError"],
    "correct_answer": "It rejects immediately with the error from the 2nd promise, ignoring the results of the others",
    "explanation": "`Promise.all()` fails fast. The moment a single promise rejects, the entire `Promise.all()` rejects immediately. It does not wait for the others to settle."
  },
  {
    "id": 664,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise Combinators",
    "question": "What does `Promise.race()` do?",
    "code_snippet": null,
    "options": ["Waits for all promises to finish", "Returns a Promise that settles (fulfills OR rejects) as soon as the FIRST promise in the array settles", "Only returns fulfilled promises", "Cancels slow promises"],
    "correct_answer": "Returns a Promise that settles (fulfills OR rejects) as soon as the FIRST promise in the array settles",
    "explanation": "`Promise.race()` is often used for timeouts. You race your actual fetch against a `setTimeout` promise. Whichever finishes first dictates the outcome."
  },
  {
    "id": 665,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise Combinators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const fast = new Promise(res => setTimeout(() => res('Fast'), 100));\nconst slow = new Promise(res => setTimeout(() => res('Slow'), 500));\nPromise.race([fast, slow]).then(val => console.log(val));",
    "options": ["Fast", "Slow", "Fast Slow", "undefined"],
    "correct_answer": "Fast",
    "explanation": "`Promise.race()` resolves with the value of the very first promise to settle. Since `fast` resolves in 100ms and `slow` in 500ms, 'Fast' wins the race."
  },
  {
    "id": 666,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise Combinators",
    "question": "What is the main advantage of `Promise.allSettled()` over `Promise.all()`?",
    "code_snippet": null,
    "options": ["It runs faster", "It waits for ALL promises to finish (either fulfilled or rejected) and returns an array of their outcomes, without failing early", "It only returns the successful ones", "It cancels rejected promises"],
    "correct_answer": "It waits for ALL promises to finish (either fulfilled or rejected) and returns an array of their outcomes, without failing early",
    "explanation": "If you want to fire 5 API calls and show the results of the 3 that succeeded, while showing error messages for the 2 that failed, `Promise.allSettled()` is the perfect tool."
  },
  {
    "id": 667,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise Combinators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const p1 = Promise.resolve('Success');\nconst p2 = Promise.reject('Error');\nPromise.allSettled([p1, p2]).then(results => console.log(results[1].status));",
    "options": ["fulfilled", "rejected", "Error", "undefined"],
    "correct_answer": "rejected",
    "explanation": "`Promise.allSettled()` returns an array of objects describing each outcome. The second object corresponds to `p2`, which has the structure `{ status: 'rejected', reason: 'Error' }`. We log the status."
  },
  {
    "id": 668,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise Combinators",
    "question": "What does `Promise.any()` do (introduced in ES2021)?",
    "code_snippet": null,
    "options": ["Returns the first promise that fulfills; if ALL reject, it rejects with an AggregateError", "Returns the first promise that settles (fulfill or reject)", "Waits for all to fulfill", "Returns a random promise from the array"],
    "correct_answer": "Returns the first promise that fulfills; if ALL reject, it rejects with an AggregateError",
    "explanation": "`Promise.any()` ignores rejections and waits for the first success. If every single promise in the array fails, it rejects with an `AggregateError` containing all the rejection reasons."
  },
  {
    "id": 669,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "The Fetch API",
    "question": "Fill in the blank to correctly initiate a GET request to an API endpoint.",
    "code_snippet": "_______('https://api.example.com/data')\n  .then(response => response.json())\n  .then(data => console.log(data));",
    "options": ["get()", "request()", "fetch()", "http()"],
    "correct_answer": "fetch()",
    "explanation": "`fetch()` is the modern, built-in browser API for making network requests. It returns a Promise that resolves to the Response object."
  },
  {
    "id": 670,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "The Fetch API",
    "question": "What is a major 'gotcha' with the `fetch()` API regarding HTTP errors (like 404 Not Found or 500 Internal Server Error)?",
    "code_snippet": null,
    "options": ["fetch() automatically retries on 500 errors", "fetch() does NOT reject the Promise on HTTP error statuses; it only rejects on network failures. You must manually check response.ok", "fetch() throws a SyntaxError on 404", "fetch() automatically redirects to the homepage on 404"],
    "correct_answer": "fetch() does NOT reject the Promise on HTTP error statuses; it only rejects on network failures. You must manually check response.ok",
    "explanation": "This is a classic trap! If a server returns a 404, `fetch()` still resolves successfully. You must check `if (!response.ok) { throw new Error(...) }` to trigger your `.catch()` or `catch` block."
  },
  {
    "id": 671,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "The Fetch API",
    "question": "Fill in the blank to correctly extract the JSON body from a fetch Response object.",
    "code_snippet": "fetch('/api/user')\n  .then(response => response._______())\n  .then(user => console.log(user.name));",
    "options": ["parse()", "json()", "data()", "body()"],
    "correct_answer": "json()",
    "explanation": "The Response object's `.json()` method reads the stream to completion and parses the body text as JSON, returning a new Promise that resolves with the result."
  },
  {
    "id": 672,
    "level": "intermediate",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "The Fetch API",
    "question": "How do you send a POST request with a JSON body using `fetch()`?",
    "code_snippet": null,
    "options": ["fetch(url, { method: 'POST', body: JSON.stringify(data) })", "fetch.post(url, data)", "fetch(url, data)", "fetch(url, { type: 'POST', data: data })"],
    "correct_answer": "fetch(url, { method: 'POST', body: JSON.stringify(data) })",
    "explanation": "You must pass an options object as the second argument. You specify the `method: 'POST'` and provide the stringified JSON in the `body` property. (You should also set the `Content-Type` header to `application/json`)."
  },
  {
    "id": 673,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3')).then(() => console.log('4'));\nconsole.log('5');",
    "options": ["1, 5, 3, 4, 2", "1, 5, 2, 3, 4", "1, 2, 3, 4, 5", "1, 5, 2, 4, 3"],
    "correct_answer": "1, 5, 3, 4, 2",
    "explanation": "1 & 5 are sync. 3 & 4 are microtasks (Promise chain). 2 is a macrotask (setTimeout). Microtasks always drain completely before the Event Loop picks up the next macrotask."
  },
  {
    "id": 674,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "async function async1() {\n  console.log('A');\n  await async2();\n  console.log('B');\n}\nasync function async2() { console.log('C'); }\nconsole.log('D');\nasync1();\nconsole.log('E');",
    "options": ["D, A, C, E, B", "D, A, C, B, E", "A, C, D, E, B", "D, E, A, C, B"],
    "correct_answer": "D, A, C, E, B",
    "explanation": "D is sync. async1() starts, logs A, calls async2() which logs C. The `await` pauses async1, yielding control. E logs sync. Finally, the microtask queue resumes async1, logging B."
  },
  {
    "id": 675,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "Why is using `await` inside a standard `for` loop generally considered a performance anti-pattern if the operations are independent?",
    "code_snippet": "for (const url of urls) {\n  await fetch(url);\n}",
    "options": ["It causes a SyntaxError", "It forces the requests to run sequentially (one after the other), rather than in parallel", "It crashes the browser", "It uses too much memory"],
    "correct_answer": "It forces the requests to run sequentially (one after the other), rather than in parallel",
    "explanation": "If you have 10 URLs, `await` in a loop will fetch #1, wait for it, then fetch #2, wait for it, etc. To run them in parallel, you should map them to promises and use `await Promise.all(urls.map(url => fetch(url)))`."
  },
  {
    "id": 676,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Async Patterns",
    "question": "Fill in the blank to correctly run an array of fetch requests in parallel and wait for all of them.",
    "code_snippet": "const urls = ['/api/1', '/api/2', '/api/3'];\nasync function getAllData() {\n  const promises = urls.map(url => fetch(url));\n  const responses = await Promise._______(promises);\n}",
    "options": ["race()", "all()", "any()", "resolve()"],
    "correct_answer": "all()",
    "explanation": "By mapping the URLs to an array of Promises first, and then awaiting `Promise.all()`, all network requests are fired simultaneously, drastically improving performance."
  },
  {
    "id": 677,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "What is an 'IIFE' (Immediately Invoked Function Expression) and how is it used with `async/await`?",
    "code_snippet": null,
    "options": ["It's a loop that runs once", "It allows you to use the `await` keyword at the top level of a standard script by wrapping the code in an async function that calls itself immediately", "It prevents memory leaks", "It is a deprecated feature"],
    "correct_answer": "It allows you to use the `await` keyword at the top level of a standard script by wrapping the code in an async function that calls itself immediately",
    "explanation": "Before Top-Level Await was introduced in ES Modules, developers used `(async () => { await doSomething(); })();` to use `await` in the global scope of a standard `.js` file."
  },
  {
    "id": 678,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "setTimeout(() => console.log('1'), 0);\nsetImmediate(() => console.log('2')); // Note: Node.js environment\nprocess.nextTick(() => console.log('3')); // Note: Node.js environment\nPromise.resolve().then(() => console.log('4'));",
    "options": ["1, 2, 3, 4", "4, 3, 1, 2", "3, 4, 1, 2", "4, 1, 2, 3"],
    "correct_answer": "3, 4, 1, 2",
    "explanation": "In Node.js: `process.nextTick` (Tick Queue) has the highest priority. Then Promises (Microtask Queue). Then `setTimeout` (Timer Queue). Finally `setImmediate` (Check Queue)."
  },
  {
    "id": 679,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "What is a 'Race Condition' in asynchronous programming?",
    "code_snippet": null,
    "options": ["When two promises resolve at the exact same millisecond", "When the output or state of a program depends on the unpredictable timing of asynchronous operations, leading to bugs", "When the Event Loop crashes", "When a fetch request is too slow"],
    "correct_answer": "When the output or state of a program depends on the unpredictable timing of asynchronous operations, leading to bugs",
    "explanation": "If you fire two async requests to update the same UI element, and the slower one finishes after the faster one, it might overwrite the correct data with stale data. This is a classic race condition."
  },
  {
    "id": 680,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "How can you prevent a Race Condition when making multiple API calls that update the same state?",
    "code_snippet": null,
    "options": ["Use `setTimeout` to delay them", "Use an AbortController to cancel outdated requests, or ensure you await them sequentially / use Promise.all", "Use `var` instead of `let`", "You cannot prevent it"],
    "correct_answer": "Use an AbortController to cancel outdated requests, or ensure you await them sequentially / use Promise.all",
    "explanation": "The modern way to handle race conditions in fetch requests is the `AbortController`, which allows you to send a signal to cancel a pending network request if a newer one supersedes it."
  },
  {
    "id": 681,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log('Start');\nasync function foo() {\n  console.log('Inside Foo');\n  await bar();\n  console.log('End Foo');\n}\nasync function bar() {\n  console.log('Inside Bar');\n}\nfoo();\nconsole.log('End');",
    "options": ["Start, Inside Foo, Inside Bar, End Foo, End", "Start, Inside Foo, Inside Bar, End, End Foo", "Start, End, Inside Foo, Inside Bar, End Foo", "Start, Inside Foo, End, Inside Bar, End Foo"],
    "correct_answer": "Start, Inside Foo, Inside Bar, End, End Foo",
    "explanation": "Start (sync). foo() starts, logs Inside Foo, calls bar() which logs Inside Bar. bar() returns a resolved promise. The `await` pauses foo, yielding control. End (sync). Microtask resumes foo, logs End Foo."
  },
  {
    "id": 682,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "What is 'Promise Chaining' and why is it useful?",
    "code_snippet": null,
    "options": ["Running promises in parallel", "Passing the result of one .then() to the next .then(), allowing sequential async operations without deep nesting", "Cancelling promises", "Converting promises to callbacks"],
    "correct_answer": "Passing the result of one .then() to the next .then(), allowing sequential async operations without deep nesting",
    "explanation": "If a `.then()` returns a new Promise, the next `.then()` in the chain waits for that new Promise to resolve. This keeps async code flat and readable."
  },
  {
    "id": 683,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let a = 0;\nsetTimeout(() => { a += 1; console.log(a); }, 0);\nPromise.resolve().then(() => { a += 10; console.log(a); });\na += 100;\nconsole.log(a);",
    "options": ["100, 101, 1", "100, 110, 111", "1, 101, 100", "100, 1, 110"],
    "correct_answer": "100, 110, 111",
    "explanation": "Sync: a becomes 100, logs 100. Microtask: a becomes 110, logs 110. Macrotask: a becomes 111, logs 111."
  },
  {
    "id": 684,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "What does the `.finally()` method on a Promise do?",
    "code_snippet": null,
    "options": ["It runs only if the promise is rejected", "It runs only if the promise is fulfilled", "It executes a callback when the promise is settled (either fulfilled or rejected), without receiving any value", "It cancels the promise"],
    "correct_answer": "It executes a callback when the promise is settled (either fulfilled or rejected), without receiving any value",
    "explanation": "`.finally()` is perfect for cleanup tasks, like hiding a loading spinner or closing a database connection, regardless of whether the operation succeeded or failed."
  },
  {
    "id": 685,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "async function f() {\n  try {\n    await Promise.reject('error!');\n  } finally {\n    console.log('finally');\n  }\n}\nf().catch(e => console.log('caught'));",
    "options": ["caught", "finally", "finally, caught", "caught, finally"],
    "correct_answer": "finally, caught",
    "explanation": "The `await` throws the rejection. The `finally` block runs first (logging 'finally'). Because the error wasn't caught inside `f()`, it bubbles out to the `.catch()` attached to `f()`, logging 'caught'."
  },
  {
    "id": 686,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "What is an 'Async Generator' in JavaScript?",
    "code_snippet": null,
    "options": ["A function that generates random numbers asynchronously", "A function declared with `async function*` that can use `await` and `yield` to produce a stream of promises", "A generator that runs on a web worker", "A deprecated feature"],
    "correct_answer": "A function declared with `async function*` that can use `await` and `yield` to produce a stream of promises",
    "explanation": "Async generators combine the power of generators (pause/resume) with async/await. They are used to create asynchronous iterables, which can be consumed with `for await...of` loops."
  },
  {
    "id": 687,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Async Patterns",
    "question": "Fill in the blank to correctly loop through an asynchronous iterable.",
    "code_snippet": "_______ (const data of asyncIterable) {\n  console.log(data);\n}",
    "options": ["for", "for await", "while await", "async for"],
    "correct_answer": "for await",
    "explanation": "The `for await...of` loop is specifically designed to consume async iterables (like those produced by async generators or readable streams), waiting for each promise to resolve before moving to the next iteration."
  },
  {
    "id": 688,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "What is a 'Thunk' in the context of older asynchronous JavaScript patterns?",
    "code_snippet": null,
    "options": ["A type of error", "A function that wraps another function and its parameters, used to delay execution or manage callbacks (often used with libraries like co or redux-thunk)", "A built-in Promise method", "A way to cancel a fetch request"],
    "correct_answer": "A function that wraps another function and its parameters, used to delay execution or manage callbacks (often used with libraries like co or redux-thunk)",
    "explanation": "Before Promises were standard, libraries used thunks to pass around 'a computation to be done later'. In modern Redux, `redux-thunk` allows you to write action creators that return a function instead of an action."
  },
  {
    "id": 689,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Advanced Event Loop",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(1);\nqueueMicrotask(() => console.log(2));\nconsole.log(3);\nPromise.resolve().then(() => console.log(4));\nconsole.log(5);",
    "options": ["1, 3, 5, 2, 4", "1, 3, 5, 4, 2", "1, 2, 3, 4, 5", "1, 3, 5, 2, 4 (or 1, 3, 5, 4, 2 depending on engine, but both are microtasks)"],
    "correct_answer": "1, 3, 5, 2, 4",
    "explanation": "1, 3, 5 are sync. `queueMicrotask` and `Promise.then` both push to the Microtask Queue. They execute in the exact order they were added to the queue. 2 was added first, so it logs before 4."
  },
  {
    "id": 690,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Async Patterns",
    "question": "Why is it important to always handle Promise rejections (either via `.catch()` or `try/catch`)?",
    "code_snippet": null,
    "options": ["Because it makes the code run faster", "Because unhandled promise rejections can cause Node.js processes to crash, and in browsers, they will eventually throw a global error and break your app", "Because it saves memory", "Because it is required by HTML5"],
    "correct_answer": "Because unhandled promise rejections can cause Node.js processes to crash, and in browsers, they will eventually throw a global error and break your app",
    "explanation": "In Node.js, an unhandled rejection triggers an 'unhandledRejection' event, which by default terminates the process. In browsers, it results in an Unhandled Promise Rejection warning/error in the console, masking the real bug."
  }
]
[
  {
    "id": 691,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "AbortController",
    "question": "What is the purpose of the `AbortController` API in modern JavaScript?",
    "code_snippet": null,
    "options": ["To pause a Promise and resume it later", "To cancel one or more asynchronous operations, such as a fetch request", "To stop the Event Loop", "To clear all setTimeout timers at once"],
    "correct_answer": "To cancel one or more asynchronous operations, such as a fetch request",
    "explanation": "`AbortController` allows you to send a 'signal' to abort an operation. It is most commonly used to cancel pending `fetch()` requests if a user navigates away or clicks a 'Cancel' button."
  },
  {
    "id": 692,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "AbortController",
    "question": "Fill in the blank to correctly pass an abort signal to a fetch request.",
    "code_snippet": "const controller = new AbortController();\nfetch(url, { signal: controller._______ });",
    "options": ["token", "signal", "id", "abort"],
    "correct_answer": "signal",
    "explanation": "You pass the `signal` property from the `AbortController` instance into the fetch options. When `controller.abort()` is called, the fetch request is immediately canceled."
  },
  {
    "id": 693,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "AbortController",
    "question": "What type of error is thrown in the `.catch()` block when a fetch request is aborted via `AbortController`?",
    "code_snippet": "const controller = new AbortController();\nfetch('https://api.example.com', { signal: controller.signal })\n  .catch(err => console.log(err.name));\ncontroller.abort();",
    "options": ["TypeError", "Error", "DOMException", "AbortError"],
    "correct_answer": "DOMException",
    "explanation": "When aborted, fetch rejects with a `DOMException` where the `name` property is specifically 'AbortError'. This allows you to distinguish a user cancellation from a real network failure."
  },
  {
    "id": 694,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "requestAnimationFrame",
    "question": "Why is `requestAnimationFrame()` preferred over `setTimeout()` for creating smooth visual animations in the browser?",
    "code_snippet": null,
    "options": ["It runs on a separate thread", "It synchronizes with the browser's monitor refresh rate (usually 60fps), pausing when the tab is in the background to save CPU", "It is a synchronous function", "It bypasses the Event Loop"],
    "correct_answer": "It synchronizes with the browser's monitor refresh rate (usually 60fps), pausing when the tab is in the background to save CPU",
    "explanation": "`setTimeout` doesn't know about the screen's refresh rate, which can cause 'jank' or dropped frames. `requestAnimationFrame` tells the browser to execute the callback right before the next repaint."
  },
  {
    "id": 695,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "setTimeout 'this' trap",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = {\n  name: 'Alice',\n  greet: function() {\n    setTimeout(function() {\n      console.log(this.name);\n    }, 100);\n  }\n};\nobj.greet();",
    "options": ["Alice", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "The callback inside `setTimeout` is a standard function. When it executes, it is called by the global timer, not by `obj`. Therefore, `this` defaults to the global `window` object, where `this.name` is undefined."
  },
  {
    "id": 696,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "setTimeout 'this' fix",
    "question": "How do you fix the previous code so it correctly logs 'Alice'?",
    "code_snippet": "setTimeout(_______() => {\n  console.log(this.name);\n}, 100);",
    "options": ["function", "async", "arrow", "No change needed, just use an arrow function"],
    "correct_answer": "No change needed, just use an arrow function",
    "explanation": "By replacing the standard `function()` with an arrow function `() =>`, the callback inherits the `this` context from the surrounding `greet` method (which is bound to `obj`)."
  },
  {
    "id": 697,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise Chaining",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "Promise.resolve('start')\n  .then(val => {\n    console.log(val);\n  })\n  .then(val => {\n    console.log(val);\n  });",
    "options": ["start, start", "start, undefined", "undefined, undefined", "Error"],
    "correct_answer": "start, undefined",
    "explanation": "The first `.then()` logs 'start' but doesn't explicitly return anything, so it implicitly returns `undefined`. The second `.then()` receives that `undefined` as its argument and logs it."
  },
  {
    "id": 698,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise Chaining Errors",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "Promise.resolve('A')\n  .then(val => {\n    console.log(val);\n    throw new Error('Oops');\n  })\n  .catch(err => console.log('Caught'));\n",
    "options": ["A", "A, Caught", "Caught", "Unhandled Rejection"],
    "correct_answer": "A, Caught",
    "explanation": "The first `.then()` logs 'A' and then throws an error. Throwing an error inside a `.then()` automatically rejects the returned Promise, which is then caught by the subsequent `.catch()` block."
  },
  {
    "id": 699,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Microtask Starvation",
    "question": "What is 'Microtask Starvation'?",
    "code_snippet": null,
    "options": ["When the microtask queue is empty", "When an infinite loop of microtasks (like recursive Promises) completely blocks the Event Loop from ever processing macrotasks or rendering the UI", "When a fetch request takes too long", "When the browser runs out of memory"],
    "correct_answer": "When an infinite loop of microtasks (like recursive Promises) completely blocks the Event Loop from ever processing macrotasks or rendering the UI",
    "explanation": "Because the Event Loop processes ALL microtasks before moving to the next macrotask, if you keep adding new microtasks (e.g., a Promise that resolves and immediately queues another Promise in a `while(true)` loop), the browser will freeze completely."
  },
  {
    "id": 700,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Microtask Starvation",
    "question": "What will happen when this code is executed?",
    "code_snippet": "function starve() {\n  Promise.resolve().then(starve);\n}\nstarve();\nsetTimeout(() => console.log('Timer!'), 0);",
    "options": ["It logs 'Timer!' immediately", "It logs 'Timer!' after 1 second", "The browser tab will freeze and 'Timer!' will never be logged", "It throws a SyntaxError"],
    "correct_answer": "The browser tab will freeze and 'Timer!' will never be logged",
    "explanation": "The `starve` function continuously queues a new microtask. The Event Loop will never finish draining the microtask queue, so it will never move on to execute the `setTimeout` macrotask. The UI will freeze."
  },
  {
    "id": 701,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Promise.resolve() timing",
    "question": "What is the difference between `Promise.resolve(val)` and `new Promise(resolve => resolve(val))`?",
    "code_snippet": null,
    "options": ["There is no difference", "`Promise.resolve()` is synchronous if passed a non-Promise value, but `new Promise()` always executes its callback synchronously and queues the resolution as a microtask", "`new Promise()` is faster", "`Promise.resolve()` is deprecated"],
    "correct_answer": "`Promise.resolve()` is synchronous if passed a non-Promise value, but `new Promise()` always executes its callback synchronously and queues the resolution as a microtask",
    "explanation": "Actually, both result in a microtask for the `.then()` handler, but `Promise.resolve(val)` is a highly optimized, built-in shortcut that avoids the overhead of executing a callback function."
  },
  {
    "id": 702,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "Global Error Handling",
    "question": "Fill in the blank to listen for ANY unhandled Promise rejections globally in the browser.",
    "code_snippet": "window.addEventListener('_______', (event) => {\n  console.error('Unhandled:', event.reason);\n});",
    "options": ["error", "promiseError", "unhandledrejection", "catch"],
    "correct_answer": "unhandledrejection",
    "explanation": "The `unhandledrejection` event is fired whenever a Promise is rejected and no `.catch()` handler is attached. It's a great safety net for logging errors to a monitoring service like Sentry."
  },
  {
    "id": 703,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise.any",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const p1 = Promise.reject('Error 1');\nconst p2 = Promise.reject('Error 2');\nPromise.any([p1, p2]).catch(err => console.log(err.name));",
    "options": ["Error", "TypeError", "AggregateError", "DOMException"],
    "correct_answer": "AggregateError",
    "explanation": "If ALL promises passed to `Promise.any()` reject, it doesn't just return the first error. It collects all of them into a special `AggregateError` object, which contains an `errors` array with all the rejection reasons."
  },
  {
    "id": 704,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "await in loops",
    "question": "If you have an array of 5 URLs and you use `await fetch(url)` inside a standard `for...of` loop, how long will it take to finish (assuming each takes 1 second)?",
    "code_snippet": null,
    "options": ["1 second (they run in parallel)", "5 seconds (they run sequentially, one after the other)", "0 seconds", "It throws an error"],
    "correct_answer": "5 seconds (they run sequentially, one after the other)",
    "explanation": "`await` inside a loop pauses the loop until the current Promise resolves before moving to the next iteration. To run them in parallel (taking only 1 second), you must map them to Promises first and use `await Promise.all()`."
  },
  {
    "id": 705,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Top-Level Await",
    "question": "In what environment is 'Top-Level Await' (using `await` outside of an `async` function) natively supported?",
    "code_snippet": null,
    "options": ["In any standard <script> tag in HTML", "Only inside ES Modules (files imported with type=\"module\" or .mjs)", "Only inside Node.js", "It is not supported anywhere yet"],
    "correct_answer": "Only inside ES Modules (files imported with type=\"module\" or .mjs)",
    "explanation": "Top-level await allows you to use `await` at the root of a file, but only if the file is treated as an ES Module. This is incredibly useful for initializing database connections or fetching config data before the rest of the app loads."
  },
  {
    "id": 706,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "setTimeout minimum delay",
    "question": "What is the minimum delay time for nested `setTimeout` calls (5 levels deep or more) in modern browsers?",
    "code_snippet": null,
    "options": ["0ms", "1ms", "4ms", "16ms"],
    "correct_answer": "4ms",
    "explanation": "To prevent CPU battery drain from infinite recursive timers, the HTML5 specification mandates that any nested `setTimeout` or `setInterval` deeper than 5 levels will be clamped to a minimum delay of 4 milliseconds."
  },
  {
    "id": 707,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "Promise.allSettled structure",
    "question": "What is the exact structure of the objects returned by `Promise.allSettled()`?",
    "code_snippet": null,
    "options": ["[{ status: 'fulfilled', value: data }, { status: 'rejected', reason: error }]", "[{ success: true, data: data }, { success: false, error: error }]", "[data, error]", "{ fulfilled: [], rejected: [] }"],
    "correct_answer": "[{ status: 'fulfilled', value: data }, { status: 'rejected', reason: error }]",
    "explanation": "`Promise.allSettled()` returns an array of objects. Each object has a `status` property ('fulfilled' or 'rejected'). If fulfilled, it has a `value` property. If rejected, it has a `reason` property."
  },
  {
    "id": 708,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "code-fill-in-blank",
    "topic": "AbortController",
    "question": "Fill in the blank to correctly trigger the cancellation of a fetch request.",
    "code_snippet": "const controller = new AbortController();\n// ... fetch started with controller.signal ...\n\n// User clicks cancel button:\ncontroller._______();",
    "options": ["cancel()", "stop()", "abort()", "terminate()"],
    "correct_answer": "abort()",
    "explanation": "Calling `.abort()` on the `AbortController` instance dispatches the abort signal to any listeners (like the fetch request), causing them to cancel immediately."
  },
  {
    "id": 709,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "output-prediction",
    "topic": "async function return",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "async function getData() {\n  // No return statement\n}\ngetData().then(val => console.log(val));",
    "options": ["null", "undefined", "Error", "Promise { undefined }"],
    "correct_answer": "undefined",
    "explanation": "If an `async` function reaches the end of its block without a `return` statement, it implicitly returns `undefined`. The Promise resolves with `undefined`, which is then logged."
  },
  {
    "id": 710,
    "level": "advanced",
    "module_id": "mod_11_async",
    "module_name": "Asynchronous JavaScript",
    "type": "conceptual",
    "topic": "Macro vs Microtask",
    "question": "If you need a piece of code to run as soon as possible, but AFTER the current synchronous code and DOM rendering is complete, which should you use?",
    "code_snippet": null,
    "options": ["setTimeout(fn, 0)", "queueMicrotask(fn)", "requestAnimationFrame(fn)", "Promise.resolve().then(fn)"],
    "correct_answer": "setTimeout(fn, 0)",
    "explanation": "Microtasks (Promises) run BEFORE the browser renders the next frame. If you want to defer execution until AFTER the current call stack AND the browser's rendering cycle, `setTimeout(fn, 0)` (a macrotask) is the correct choice."
  }
]
