[
  {
    "id": 961,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Package Managers",
    "question": "What does 'npm' stand for in the JavaScript ecosystem?",
    "code_snippet": null,
    "options": ["Node Project Manager", "Node Package Manager", "New Programming Method", "Native Protocol Module"],
    "correct_answer": "Node Package Manager",
    "explanation": "npm is the default package manager for Node.js. It allows developers to download, share, and manage external libraries (packages) and dependencies for their projects."
  },
  {
    "id": 962,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "package.json",
    "question": "What is the purpose of the `package.json` file in a Node.js/JavaScript project?",
    "code_snippet": null,
    "options": ["It stores the database credentials", "It acts as the manifest file, containing project metadata, scripts, and a list of required dependencies", "It contains the compiled machine code", "It is used to configure the web server"],
    "correct_answer": "It acts as the manifest file, containing project metadata, scripts, and a list of required dependencies",
    "explanation": "Every modern JS project has a `package.json`. It tells npm what the project is, what scripts can be run (like `npm start` or `npm test`), and exactly which external libraries the project needs to function."
  },
  {
    "id": 963,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Dependencies",
    "question": "What is the difference between `dependencies` and `devDependencies` in `package.json`?",
    "code_snippet": null,
    "options": ["There is no difference", "`dependencies` are required for the app to run in production; `devDependencies` are only needed during development (like testing or linting tools)", "`devDependencies` are for frontend, `dependencies` are for backend", "`dependencies` are downloaded first"],
    "correct_answer": "`dependencies` are required for the app to run in production; `devDependencies` are only needed during development (like testing or linting tools)",
    "explanation": "Libraries like React or Express go in `dependencies`. Tools like Jest, ESLint, or Webpack go in `devDependencies`. When deploying to a production server, you can skip installing devDependencies to save time and space."
  },
  {
    "id": 964,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "code-fill-in-blank",
    "topic": "npm commands",
    "question": "If you clone a project from GitHub that already has a `package.json` file, which command do you run to download all the required libraries?",
    "code_snippet": "git clone https://github.com/user/project.git\ncd project\n_______",
    "options": ["npm start", "npm init", "npm install", "npm run"],
    "correct_answer": "npm install",
    "explanation": "Running `npm install` (or `npm i`) reads the `package.json` file and downloads every package listed in the dependencies into a local `node_modules` folder."
  },
  {
    "id": 965,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "package-lock.json",
    "question": "What is the purpose of the `package-lock.json` file?",
    "code_snippet": null,
    "options": ["To encrypt the dependencies", "To lock the exact, specific versions of every installed package and sub-dependency, ensuring deterministic builds across different machines", "To prevent users from uninstalling packages", "To store the source code of the packages"],
    "correct_answer": "To lock the exact, specific versions of every installed package and sub-dependency, ensuring deterministic builds across different machines",
    "explanation": "While `package.json` might say `\"react\": \"^18.0.0\"` (allowing minor updates), `package-lock.json` locks it to exactly `18.2.0`. This ensures that every developer and the production server install the exact same code, preventing 'it works on my machine' bugs."
  },
  {
    "id": 966,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "npx",
    "question": "What does the `npx` command do?",
    "code_snippet": null,
    "options": ["It deletes a package", "It executes a package binary directly from the npm registry without requiring you to install it globally on your machine", "It creates a new Node.js project", "It compiles TypeScript to JavaScript"],
    "correct_answer": "It executes a package binary directly from the npm registry without requiring you to install it globally on your machine",
    "explanation": "`npx` (Node Package Execute) is incredibly useful for one-off commands. For example, `npx create-react-app my-app` downloads the scaffolding tool, runs it, and discards it, keeping your global environment clean."
  },
  {
    "id": 967,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "ESLint",
    "question": "What is the primary purpose of ESLint?",
    "code_snippet": null,
    "options": ["To format code to look pretty", "To statically analyze code to find buggy patterns, syntax errors, and deviations from style guides", "To minify JavaScript for production", "To run unit tests"],
    "correct_answer": "To statically analyze code to find buggy patterns, syntax errors, and deviations from style guides",
    "explanation": "ESLint is a 'linter'. It reads your code without executing it and warns you about things like unused variables, missing equality checks (`==` instead of `===`), or unreachable code."
  },
  {
    "id": 968,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Prettier",
    "code_snippet": null,
    "question": "What is the primary purpose of Prettier?",
    "options": ["To find logical bugs in the code", "To automatically format code (indentation, semicolons, quotes) to enforce a consistent visual style across a team", "To translate JavaScript to Python", "To manage database connections"],
    "correct_answer": "To automatically format code (indentation, semicolons, quotes) to enforce a consistent visual style across a team",
    "explanation": "Prettier is a 'code formatter'. You write messy code, hit save, and Prettier automatically rewrites it to look beautiful and consistent. It eliminates team arguments over tabs vs. spaces."
  },
  {
    "id": 969,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "ESLint vs Prettier",
    "question": "How do ESLint and Prettier complement each other in a modern project?",
    "code_snippet": null,
    "options": ["They do the exact same thing, so you only need one", "ESLint focuses on code quality and potential bugs; Prettier focuses purely on visual formatting. They are often configured to work together", "ESLint is for frontend, Prettier is for backend", "Prettier fixes the bugs that ESLint finds"],
    "correct_answer": "ESLint focuses on code quality and potential bugs; Prettier focuses purely on visual formatting. They are often configured to work together",
    "explanation": "The industry standard is to use Prettier to handle all visual styling (turning off ESLint's formatting rules) and let ESLint focus strictly on catching logical errors and enforcing best practices."
  },
  {
    "id": 970,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Testing Pyramid",
    "question": "What is the 'Testing Pyramid' concept in software engineering?",
    "code_snippet": null,
    "options": ["A UI design pattern", "A strategy suggesting you should have many fast Unit Tests at the bottom, fewer Integration Tests in the middle, and very few slow End-to-End tests at the top", "A way to organize database tables", "A method for sorting arrays"],
    "correct_answer": "A strategy suggesting you should have many fast Unit Tests at the bottom, fewer Integration Tests in the middle, and very few slow End-to-End tests at the top",
    "explanation": "Unit tests are fast and cheap to write. E2E tests (like clicking through a real browser) are slow and brittle. The pyramid ensures you get maximum confidence with minimum maintenance overhead."
  },
  {
    "id": 971,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Unit Testing",
    "question": "What is a 'Unit Test'?",
    "code_snippet": null,
    "options": ["Testing the entire application from start to finish", "Testing a single, isolated piece of code (like one function or one component) to verify it works as expected", "Testing the database connection", "Testing the CSS styles"],
    "correct_answer": "Testing a single, isolated piece of code (like one function or one component) to verify it works as expected",
    "explanation": "Unit tests are the foundation of the testing pyramid. You test a function like `add(2, 2)` and assert that it returns `4`, completely ignoring the rest of the application."
  },
  {
    "id": 972,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Integration Testing",
    "question": "What is an 'Integration Test'?",
    "code_snippet": null,
    "options": ["Testing a single function in isolation", "Testing how multiple units, modules, or services work together (e.g., testing that a function correctly writes to a database)", "Testing the application on a mobile device", "Testing the network speed"],
    "correct_answer": "Testing how multiple units, modules, or services work together (e.g., testing that a function correctly writes to a database)",
    "explanation": "While unit tests mock out dependencies, integration tests let the real dependencies interact. It verifies that the 'glue' between your components works correctly."
  },
  {
    "id": 973,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "E2E Testing",
    "question": "What is 'End-to-End' (E2E) Testing?",
    "code_snippet": null,
    "options": ["Testing only the frontend UI", "Testing the complete flow of an application in a real browser environment, simulating real user actions from start to finish", "Testing the server hardware", "Testing the code for syntax errors"],
    "correct_answer": "Testing the complete flow of an application in a real browser environment, simulating real user actions from start to finish",
    "explanation": "Tools like Cypress or Playwright open a real browser, click buttons, fill out forms, and verify the final result. It's the ultimate safety net, but also the slowest type of test."
  },
  {
    "id": 974,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "TDD",
    "question": "What does TDD stand for, and what is its core cycle?",
    "code_snippet": null,
    "options": ["Test-Driven Development; Red (write failing test) -> Green (write code to pass) -> Refactor", "Total Design Deployment; Plan -> Build -> Ship", "Technical Debugging Directive; Find -> Fix -> Verify", "Test-Data Distribution; Collect -> Analyze -> Report"],
    "correct_answer": "Test-Driven Development; Red (write failing test) -> Green (write code to pass) -> Refactor",
    "explanation": "In TDD, you write the test BEFORE you write the actual code. This forces you to think about the API and requirements first, and guarantees you have 100% test coverage for that feature."
  },
  {
    "id": 975,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Mocking",
    "question": "What is 'Mocking' in the context of unit testing?",
    "code_snippet": null,
    "options": ["Making fun of bad code", "Replacing real, complex dependencies (like API calls or database queries) with fake, controlled implementations to isolate the code being tested", "Running tests without a network connection", "Writing tests that always pass"],
    "correct_answer": "Replacing real, complex dependencies (like API calls or database queries) with fake, controlled implementations to isolate the code being tested",
    "explanation": "If you are testing a function that fetches user data, you 'mock' the fetch call to return fake data instantly. This ensures your test doesn't fail just because the external API is down."
  },
  {
    "id": 976,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "code-fill-in-blank",
    "topic": "Jest Basics",
    "question": "In the Jest testing framework, which function is used to group related test cases together?",
    "code_snippet": "_______('Math functions', () => {\n  // tests go here\n});",
    "options": ["group()", "suite()", "describe()", "test()"],
    "correct_answer": "describe()",
    "explanation": "`describe()` creates a block that groups together several related tests. When the tests run, Jest will print the name of the describe block to help organize the output."
  },
  {
    "id": 977,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "code-fill-in-blank",
    "topic": "Jest Basics",
    "question": "In Jest, which function is used to define an individual test case?",
    "code_snippet": "_______('adds 1 + 2 to equal 3', () => {\n  expect(1 + 2).toBe(3);\n});",
    "options": ["describe()", "test() or it()", "case()", "check()"],
    "correct_answer": "test() or it()",
    "explanation": "Both `test()` and `it()` do the exact same thing in Jest. They define a single test. `it('should do something')` is popular because it reads like plain English in the test output."
  },
  {
    "id": 978,
    "level": "beginner",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "code-fill-in-blank",
    "topic": "Jest Basics",
    "question": "In Jest, which function is used to assert that a value matches an expected result?",
    "code_snippet": "_______(sum(1, 2)).toBe(3);",
    "options": ["assert()", "check()", "expect()", "verify()"],
    "correct_answer": "expect()",
    "explanation": "`expect()` takes the actual value, and is chained with a 'matcher' like `.toBe()`, `.toEqual()`, or `.toBeTruthy()` to verify the result."
  },
  {
    "id": 979,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Jest Setup",
    "question": "What is the purpose of the `beforeEach()` function in Jest?",
    "code_snippet": null,
    "options": ["It runs once before all tests in the file", "It runs a setup function before EVERY single test in the current describe block, ensuring a clean state", "It runs after the tests finish", "It skips the current test"],
    "correct_answer": "It runs a setup function before EVERY single test in the current describe block, ensuring a clean state",
    "explanation": "If you need to reset a database, clear a mock, or re-initialize a class instance before every test so they don't interfere with each other, you put that logic inside `beforeEach()`."
  },
  {
    "id": 980,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Code Coverage",
    "question": "What does 'Code Coverage' measure in a test suite?",
    "code_snippet": null,
    "options": ["How fast the tests run", "The percentage of your source code (lines, functions, branches) that is actually executed during your tests", "How many bugs the tests found", "The size of the test files"],
    "correct_answer": "The percentage of your source code (lines, functions, branches) that is actually executed during your tests",
    "explanation": "If you have 100 lines of code, and your tests only trigger 80 of them, you have 80% code coverage. It's a great metric to find untested 'dead zones' in your application, though 100% coverage doesn't guarantee 0 bugs."
  }
]
[
  {
    "id": 981,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Jest Mocking",
    "question": "What does the `jest.fn()` function do?",
    "code_snippet": null,
    "options": ["Deletes a function from memory", "Creates a mock function that can track how many times it was called and with what arguments", "Compiles a function to machine code", "Converts an arrow function to a regular function"],
    "correct_answer": "Creates a mock function that can track how many times it was called and with what arguments",
    "explanation": "`jest.fn()` creates a 'spy' function. You can pass it as a callback to your code, and later assert things like `expect(mockFn).toHaveBeenCalledTimes(1)`."
  },
  {
    "id": 982,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Jest Spies",
    "question": "What is the difference between `jest.fn()` and `jest.spyOn()`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`jest.fn()` creates a brand new mock function; `jest.spyOn()` wraps an EXISTING method on an object to track its calls while optionally keeping its original behavior", "`jest.spyOn()` is for arrays, `jest.fn()` is for functions", "`jest.fn()` is deprecated"],
    "correct_answer": "`jest.fn()` creates a brand new mock function; `jest.spyOn()` wraps an EXISTING method on an object to track its calls while optionally keeping its original behavior",
    "explanation": "Use `jest.spyOn(obj, 'method')` when you want to verify that a specific method on a class or object was called, without completely replacing the object's structure."
  },
  {
    "id": 983,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Jest Module Mocking",
    "question": "What does `jest.mock('./api')` do at the top of a test file?",
    "code_snippet": null,
    "options": ["Deletes the api.js file", "Automatically mocks the entire exported module, replacing all its functions with `jest.fn()` instances before the test runs", "Renames the module", "Imports the module asynchronously"],
    "correct_answer": "Automatically mocks the entire exported module, replacing all its functions with `jest.fn()` instances before the test runs",
    "explanation": "Jest hoists `jest.mock()` calls to the top of the file. This ensures that any `import` or `require` of that module gets the mocked version, completely isolating your test from external APIs or databases."
  },
  {
    "id": 984,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Jest Fake Timers",
    "question": "Why would you use `jest.useFakeTimers()` in a test?",
    "code_snippet": null,
    "options": ["To make the test suite run faster by skipping network requests", "To replace the real JavaScript timer functions (setTimeout, setInterval) with mocks, allowing you to instantly fast-forward time without actually waiting", "To measure how long the test takes to run", "To pause the execution of the test"],
    "correct_answer": "To replace the real JavaScript timer functions (setTimeout, setInterval) with mocks, allowing you to instantly fast-forward time without actually waiting",
    "explanation": "If you have a function that waits 5 seconds before showing a tooltip, you don't want your test suite to actually wait 5 seconds. Fake timers let you simulate the passage of time instantly."
  },
  {
    "id": 985,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "code-fill-in-blank",
    "topic": "Jest Fake Timers",
    "question": "Fill in the blank to correctly advance all pending timers by 5000 milliseconds.",
    "code_snippet": "jest.useFakeTimers();\nstartCountdown();\n_______(5000);\nexpect(display.textContent).toBe('Done!');",
    "options": ["jest.advanceTimersByTime", "jest.fastForward", "jest.wait", "setTimeout"],
    "correct_answer": "jest.advanceTimersByTime",
    "explanation": "`jest.advanceTimersByTime(ms)` forces all scheduled timers to execute as if that amount of real time had passed, allowing you to test time-dependent logic synchronously."
  },
  {
    "id": 986,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Jest Async Testing",
    "question": "How must you handle asynchronous code (like Promises or async/await) in a Jest test?",
    "code_snippet": null,
    "options": ["Jest automatically waits for all Promises to resolve", "You must either return the Promise from the test function, use async/await, or use the `done` callback so Jest knows when the test is finished", "You cannot test async code in Jest", "You must wrap it in a setTimeout"],
    "correct_answer": "You must either return the Promise from the test function, use async/await, or use the `done` callback so Jest knows when the test is finished",
    "explanation": "If you don't return the Promise or use `done`, Jest will think the test finished immediately on the first synchronous line, resulting in a false positive (the test passes before the async code actually runs)."
  },
  {
    "id": 987,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Snapshot Testing",
    "question": "What is 'Snapshot Testing' (e.g., in Jest or React Testing Library)?",
    "code_snippet": null,
    "options": ["Taking a screenshot of the browser", "Capturing the rendered output of a component or object, saving it to a file, and automatically failing future tests if the output changes unexpectedly", "Testing the application's memory footprint", "Testing the database schema"],
    "correct_answer": "Capturing the rendered output of a component or object, saving it to a file, and automatically failing future tests if the output changes unexpectedly",
    "explanation": "Snapshot tests are great for catching accidental UI regressions. If you change a CSS class or a text label, the snapshot test will fail, prompting you to review the change and update the snapshot if it was intentional."
  },
  {
    "id": 988,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "CI/CD Basics",
    "question": "What does CI (Continuous Integration) mean in modern software development?",
    "code_snippet": null,
    "options": ["Writing code continuously without breaks", "The practice of frequently merging code changes into a central repository, automatically triggering builds and test suites to catch errors early", "Continually updating the production database", "Integrating new developers into the team"],
    "correct_answer": "The practice of frequently merging code changes into a central repository, automatically triggering builds and test suites to catch errors early",
    "explanation": "CI ensures that every time a developer pushes code, a server automatically runs `npm install`, `npm run lint`, and `npm test`. If any test fails, the team is alerted immediately."
  },
  {
    "id": 989,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "CI/CD Basics",
    "question": "What does CD (Continuous Delivery / Continuous Deployment) mean?",
    "code_snippet": null,
    "options": ["Compact Disc storage", "Automating the release process so that code that passes the CI pipeline can be automatically (or with one click) deployed to production", "Continuously downloading dependencies", "Creating documentation"],
    "correct_answer": "Automating the release process so that code that passes the CI pipeline can be automatically (or with one click) deployed to production",
    "explanation": "Continuous Deployment takes it a step further: if all tests pass in the CI pipeline, the new version is automatically pushed to the live production servers without any human intervention."
  },
  {
    "id": 990,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "CI/CD Tools",
    "question": "Which of the following is a highly popular, YAML-based CI/CD tool integrated directly into GitHub?",
    "code_snippet": null,
    "options": ["Jenkins", "GitHub Actions", "Docker", "Postman"],
    "correct_answer": "GitHub Actions",
    "explanation": "GitHub Actions allows you to define workflows in `.yml` files inside your `.github/workflows` directory. Every time you push or open a PR, GitHub's servers spin up and run your tests automatically."
  },
  {
    "id": 991,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Git Workflows",
    "question": "What is the 'Feature Branch' workflow in Git?",
    "code_snippet": null,
    "options": ["Pushing all code directly to the main branch", "Creating an isolated branch (e.g., `feature/login-page`) for every new feature or bug fix, and only merging it into `main` after it is complete and reviewed", "Deleting the main branch every week", "Using only one branch for the entire team"],
    "correct_answer": "Creating an isolated branch (e.g., `feature/login-page`) for every new feature or bug fix, and only merging it into `main` after it is complete and reviewed",
    "explanation": "Feature branches protect the `main` (or `master`) branch from broken code. It ensures that the production branch is always in a deployable state."
  },
  {
    "id": 992,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Pull Requests",
    "question": "What is the primary purpose of a Pull Request (PR) or Merge Request (MR)?",
    "code_snippet": null,
    "options": ["To request more memory from the server", "To propose changes from a feature branch, allowing teammates to review the code, discuss it, and run automated CI checks before merging", "To pull the latest code from the database", "To request a new feature from the product manager"],
    "correct_answer": "To propose changes from a feature branch, allowing teammates to review the code, discuss it, and run automated CI checks before merging",
    "explanation": "PRs are the heart of collaborative development. They provide a centralized place to see exactly what changed (the diff), leave comments on specific lines, and ensure quality control."
  },
  {
    "id": 993,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Code Reviews",
    "question": "What is a key best practice when conducting a Code Review?",
    "code_snippet": null,
    "options": ["Approve everything immediately to not block the team", "Focus solely on finding syntax errors", "Review the logic, architecture, and potential edge cases, while being constructive, polite, and asking questions rather than making demands", "Rewrite the entire code yourself"],
    "correct_answer": "Review the logic, architecture, and potential edge cases, while being constructive, polite, and asking questions rather than making demands",
    "explanation": "Good code reviews catch bugs, share knowledge across the team, and maintain code quality. Phrasing feedback as 'Have you considered what happens if...?' is much better than 'This is wrong'."
  },
  {
    "id": 994,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Semantic Versioning",
    "question": "What is Semantic Versioning (SemVer)?",
    "code_snippet": null,
    "options": ["A way to name variables", "A standardized versioning scheme (MAJOR.MINOR.PATCH) that communicates the impact of changes in a software release", "A method to compress code", "A Git branching strategy"],
    "correct_answer": "A standardized versioning scheme (MAJOR.MINOR.PATCH) that communicates the impact of changes in a software release",
    "explanation": "SemVer tells developers exactly what to expect when they update a dependency. For example, version `2.1.4` tells you the Major, Minor, and Patch levels of the release."
  },
  {
    "id": 995,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Semantic Versioning",
    "question": "In Semantic Versioning (e.g., `1.2.3`), what does incrementing the FIRST number (the MAJOR version) signify?",
    "code_snippet": null,
    "options": ["A minor bug fix", "A new feature added in a backwards-compatible way", "Breaking changes that are NOT backwards-compatible", "A security patch"],
    "correct_answer": "Breaking changes that are NOT backwards-compatible",
    "explanation": "If a library goes from `1.x.x` to `2.0.0`, it means the authors removed or changed existing APIs in a way that will break your code if you update without making changes."
  },
  {
    "id": 996,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Package Versioning",
    "question": "In `package.json`, what does the caret symbol (`^`) mean in a dependency version like `\"react\": \"^18.2.0\"`?",
    "code_snippet": null,
    "options": ["It locks the version exactly to 18.2.0", "It allows updates that do not change the left-most non-zero digit (so it will accept 18.3.0 or 18.9.9, but NOT 19.0.0)", "It means the package is deprecated", "It forces a downgrade to the lowest version"],
    "correct_answer": "It allows updates that do not change the left-most non-zero digit (so it will accept 18.3.0 or 18.9.9, but NOT 19.0.0)",
    "explanation": "The `^` symbol is the default in npm. It means 'accept minor and patch updates, but do not automatically download a new Major version' because Major versions contain breaking changes."
  },
  {
    "id": 997,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Bundlers",
    "question": "What is the primary job of a Module Bundler (like Webpack, Vite, or Rollup)?",
    "code_snippet": null,
    "options": ["To write JavaScript code for you", "To take all your separate JS, CSS, and image files and combine them into optimized, browser-ready files for production", "To test your code", "To manage your Git repository"],
    "correct_answer": "To take all your separate JS, CSS, and image files and combine them into optimized, browser-ready files for production",
    "explanation": "Modern development uses hundreds of small files with `import`/`export`. Browsers need fewer, optimized files. Bundlers resolve the dependency graph, tree-shake unused code, minify the output, and generate the final `dist` folder."
  },
  {
    "id": 998,
    "level": "intermediate",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Transpilers",
    "question": "What is the primary job of a Transpiler (like Babel)?",
    "code_snippet": null,
    "options": ["To translate code from one programming language to another at the same level (e.g., modern ES6+ JavaScript down to older ES5 JavaScript for legacy browsers)", "To compile JS to C++", "To format code", "To encrypt code"],
    "correct_answer": "To translate code from one programming language to another at the same level (e.g., modern ES6+ JavaScript down to older ES5 JavaScript for legacy browsers)",
    "explanation": "Transpilers (Source-to-Source compilers) allow you to write modern, cutting-edge JavaScript (or TypeScript) while ensuring it will still run on older browsers that don't support those new features yet."
  },
  {
    "id": 999,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "Monorepos",
    "question": "What is a 'Monorepo' in the JavaScript ecosystem?",
    "code_snippet": null,
    "options": ["A repository with only one file", "A single Git repository that contains multiple distinct, but related, projects or packages (often managed by tools like Nx, Turborepo, or Lerna)", "A database with one table", "A branch that cannot be merged"],
    "correct_answer": "A single Git repository that contains multiple distinct, but related, projects or packages (often managed by tools like Nx, Turborepo, or Lerna)",
    "explanation": "Companies like Google, Meta, and Vercel use monorepos. Instead of having 50 separate repos for their frontend, backend, and shared UI library, they keep them all in one massive repo to easily share code and run atomic commits across projects."
  },
  {
    "id": 1000,
    "level": "advanced",
    "module_id": "mod_17_tooling_testing",
    "module_name": "Testing, Tooling & Ecosystem",
    "type": "conceptual",
    "topic": "The JS Ecosystem",
    "question": "The JavaScript ecosystem changes incredibly fast, with new frameworks and tools releasing constantly. What is the most important skill for a JavaScript developer to maintain a long-term career?",
    "code_snippet": null,
    "options": ["Memorizing every single array method", "Learning how to learn: reading official documentation, understanding core fundamentals (like the Event Loop and Closures), and adapting to new tools without panic", "Sticking exclusively to one framework forever", "Avoiding open-source software"],
    "correct_answer": "Learning how to learn: reading official documentation, understanding core fundamentals (like the Event Loop and Closures), and adapting to new tools without panic",
    "explanation": "Frameworks come and go (jQuery, AngularJS, React, Svelte, etc.), but the core language (JavaScript), the DOM, HTTP, and computer science fundamentals remain constant. Mastering the fundamentals makes learning any new tool trivial."
  }
]
