[
  {
    "id": 861,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Timers",
    "question": "What does the `setTimeout()` function return?",
    "code_snippet": null,
    "options": ["undefined", "A Promise", "A unique numeric ID that can be used to cancel the timer", "The callback function itself"],
    "correct_answer": "A unique numeric ID that can be used to cancel the timer",
    "explanation": "When you call `setTimeout`, the browser returns a positive integer (the timer ID). You can pass this ID to `clearTimeout(id)` to cancel the timer before it executes."
  },
  {
    "id": 862,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "Timers",
    "question": "Fill in the blank to correctly cancel a scheduled timeout.",
    "code_snippet": "const timerId = setTimeout(() => console.log('Hi'), 5000);\n_______(timerId);",
    "options": ["stopTimeout", "cancelTimeout", "clearTimeout", "endTimer"],
    "correct_answer": "clearTimeout",
    "explanation": "`clearTimeout(id)` is the built-in browser method used to cancel a timer created by `setTimeout` before it has a chance to fire."
  },
  {
    "id": 863,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Timers",
    "question": "What is the main difference between `setTimeout()` and `setInterval()`?",
    "code_snippet": null,
    "options": ["`setTimeout` is for milliseconds, `setInterval` is for seconds", "`setTimeout` executes a function once after a delay; `setInterval` executes a function repeatedly at a specified interval", "`setInterval` is asynchronous, `setTimeout` is synchronous", "There is no difference"],
    "correct_answer": "`setTimeout` executes a function once after a delay; `setInterval` executes a function repeatedly at a specified interval",
    "explanation": "`setTimeout` is a one-time delayed execution. `setInterval` will keep firing the callback over and over until you explicitly stop it using `clearInterval()`."
  },
  {
    "id": 864,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "output-prediction",
    "topic": "Timers",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log('A');\nsetTimeout(() => console.log('B'), 1000);\nconsole.log('C');",
    "options": ["A, B, C", "A, C, B", "B, A, C", "C, A, B"],
    "correct_answer": "A, C, B",
    "explanation": "'A' and 'C' are synchronous and run immediately. The `setTimeout` callback is sent to the Web API and then the callback queue. Even with a 1000ms delay, it will only run after the synchronous code ('C') finishes."
  },
  {
    "id": 865,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Timers",
    "question": "What happens if you pass a negative number as the delay to `setTimeout()` (e.g., `setTimeout(fn, -100)`)?",
    "code_snippet": null,
    "options": ["It throws a RangeError", "It never executes", "It executes immediately (or as soon as the call stack is empty)", "It executes after 100 milliseconds"],
    "correct_answer": "It executes immediately (or as soon as the call stack is empty)",
    "explanation": "The HTML specification states that if the delay is less than 0 (or not a number), the browser treats it as 0. The callback is pushed to the queue and executes as soon as the synchronous call stack clears."
  },
  {
    "id": 866,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Web Storage",
    "question": "What is the main difference between `localStorage` and `sessionStorage`?",
    "code_snippet": null,
    "options": ["`localStorage` is limited to 5MB, `sessionStorage` is unlimited", "`localStorage` persists until explicitly cleared; `sessionStorage` is cleared when the browser tab is closed", "`sessionStorage` is sent to the server, `localStorage` is not", "There is no difference"],
    "correct_answer": "`localStorage` persists until explicitly cleared; `sessionStorage` is cleared when the browser tab is closed",
    "explanation": "`localStorage` has no expiration time and survives browser restarts. `sessionStorage` is tied to the specific tab; if you close the tab, the data is wiped."
  },
  {
    "id": 867,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "Web Storage",
    "question": "Because Web Storage only stores strings, how do you correctly save a JavaScript object to `localStorage`?",
    "code_snippet": "const user = { name: 'Alice' };\nlocalStorage.setItem('user', _______(user));",
    "options": ["JSON.parse()", "JSON.stringify()", "String()", "toString()"],
    "correct_answer": "JSON.stringify()",
    "explanation": "You must serialize the object into a JSON string using `JSON.stringify()` before saving it. When you read it back, you must use `JSON.parse()` to turn it back into an object."
  },
  {
    "id": 868,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "output-prediction",
    "topic": "Web Storage",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "localStorage.setItem('age', 25);\nconst storedAge = localStorage.getItem('age');\nconsole.log(typeof storedAge);",
    "options": ["'number'", "'string'", "'object'", "'undefined'"],
    "correct_answer": "'string'",
    "explanation": "Even though you passed the number `25`, `localStorage` automatically coerces it to a string. When you retrieve it with `getItem()`, it returns the string `'25'`."
  },
  {
    "id": 869,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "Web Storage",
    "question": "Fill in the blank to correctly remove a specific item from `localStorage`.",
    "code_snippet": "localStorage._______('theme');",
    "options": ["deleteItem()", "removeItem()", "clear()", "drop()"],
    "correct_answer": "removeItem()",
    "explanation": "`removeItem(key)` deletes a single specific key-value pair. If you want to wipe everything, you would use `localStorage.clear()`."
  },
  {
    "id": 870,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Web Storage",
    "question": "What is the typical storage capacity limit for `localStorage` in modern browsers?",
    "code_snippet": null,
    "options": ["100 KB", "1 MB", "5 MB to 10 MB", "Unlimited"],
    "correct_answer": "5 MB to 10 MB",
    "explanation": "Most browsers allocate about 5MB per origin (domain) for `localStorage`. If you exceed this, the browser will throw a `QuotaExceededError`."
  },
  {
    "id": 871,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Cookies",
    "question": "What is the primary difference between Cookies and `localStorage`?",
    "code_snippet": null,
    "options": ["Cookies are faster", "Cookies are automatically sent with every HTTP request to the server; `localStorage` is strictly client-side", "`localStorage` can store objects natively", "Cookies have no size limit"],
    "correct_answer": "Cookies are automatically sent with every HTTP request to the server; `localStorage` is strictly client-side",
    "explanation": "Because cookies are sent with every request, they are used for authentication (session tokens). `localStorage` is much larger and meant for client-side caching and preferences."
  },
  {
    "id": 872,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Cookies",
    "question": "What does the `HttpOnly` flag do when set on a cookie?",
    "code_snippet": null,
    "options": ["It makes the cookie load faster", "It prevents the cookie from being accessed or modified via client-side JavaScript (`document.cookie`)", "It ensures the cookie is only sent over HTTP, not HTTPS", "It restricts the cookie to a single domain"],
    "correct_answer": "It prevents the cookie from being accessed or modified via client-side JavaScript (`document.cookie`)",
    "explanation": "`HttpOnly` is a crucial security feature. It prevents XSS (Cross-Site Scripting) attacks from stealing sensitive cookies (like session IDs) because the JS `document.cookie` API cannot see them."
  },
  {
    "id": 873,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Cookies",
    "question": "What does the `Secure` flag on a cookie do?",
    "code_snippet": null,
    "options": ["It encrypts the cookie data", "It ensures the cookie is only sent over encrypted HTTPS connections, never over plain HTTP", "It prevents the cookie from being deleted", "It makes the cookie accessible to all subdomains"],
    "correct_answer": "It ensures the cookie is only sent over encrypted HTTPS connections, never over plain HTTP",
    "explanation": "The `Secure` flag protects the cookie from being intercepted in transit over unencrypted networks. It should always be used for sensitive authentication cookies."
  },
  {
    "id": 874,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "output-prediction",
    "topic": "Cookies",
    "question": "What format does `document.cookie` return when reading cookies?",
    "code_snippet": null,
    "options": ["A JSON object", "An array of strings", "A single string containing key-value pairs separated by semicolons", "A Map object"],
    "correct_answer": "A single string containing key-value pairs separated by semicolons",
    "explanation": "`document.cookie` returns a raw string like `'theme=dark; sessionId=abc123'`. You have to manually parse this string using `.split(';')` and `.split('=')` to work with the data."
  },
  {
    "id": 875,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "JSON",
    "question": "What does the `JSON.parse()` method do?",
    "code_snippet": null,
    "options": ["Converts a JavaScript object into a JSON string", "Converts a JSON string into a JavaScript object or value", "Formats a JSON string with indentation", "Validates if a string is valid JSON"],
    "correct_answer": "Converts a JSON string into a JavaScript object or value",
    "explanation": "`JSON.parse()` takes a properly formatted JSON string (usually from a server or `localStorage`) and deserializes it into a native JavaScript object, array, or primitive."
  },
  {
    "id": 876,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "JSON Quirks",
    "question": "What happens when `JSON.stringify()` encounters a property with a value of `undefined`, a function, or a Symbol inside an object?",
    "code_snippet": null,
    "options": ["It throws a SyntaxError", "It converts them to `null`", "It completely omits that key-value pair from the resulting JSON string", "It converts them to empty strings"],
    "correct_answer": "It completely omits that key-value pair from the resulting JSON string",
    "explanation": "JSON format does not support `undefined`, functions, or Symbols. When stringifying an object, `JSON.stringify` simply skips those properties entirely."
  },
  {
    "id": 877,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "output-prediction",
    "topic": "JSON Quirks",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = { a: 1, b: undefined, c: () => {}, d: 4 };\nconsole.log(JSON.stringify(obj));",
    "options": ["'{\"a\":1,\"b\":null,\"c\":null,\"d\":4}'", "'{\"a\":1,\"d\":4}'", "'{\"a\":1,\"b\":undefined,\"c\":function,\"d\":4}'", "Error"],
    "correct_answer": "'{\"a\":1,\"d\":4}'",
    "explanation": "Because `b` is `undefined` and `c` is a function, `JSON.stringify` omits them entirely. Only the valid JSON values (`a` and `d`) are included in the output string."
  },
  {
    "id": 878,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "JSON Methods",
    "question": "What is the purpose of the second argument (the 'replacer') in `JSON.stringify(obj, replacer)`?",
    "code_snippet": null,
    "options": ["To set the indentation spacing", "To filter or transform the values before they are stringified", "To catch parsing errors", "To specify the output file path"],
    "correct_answer": "To filter or transform the values before they are stringified",
    "explanation": "The replacer can be an array of keys to include (e.g., `['name', 'age']`), or a function that receives every key/value pair and can modify or exclude them on the fly."
  },
  {
    "id": 879,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "JSON Methods",
    "question": "Fill in the blank to correctly format the JSON string with an indentation of 2 spaces for readability.",
    "code_snippet": "const prettyJson = JSON.stringify(obj, null, _______);",
    "options": ["2", "'pretty'", "true", "format"],
    "correct_answer": "2",
    "explanation": "The third argument of `JSON.stringify` is the 'space' parameter. Passing a number (like 2) or a string (like '\\t') inserts that whitespace into the output for pretty-printing."
  },
  {
    "id": 880,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "output-prediction",
    "topic": "JSON Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const data = JSON.parse('{\"count\": \"5\", \"active\": true}');\nconsole.log(typeof data.count, typeof data.active);",
    "options": ["'number', 'boolean'", "'string', 'boolean'", "'string', 'string'", "'number', 'string'"],
    "correct_answer": "'string', 'boolean'",
    "explanation": "In the JSON string, `\"5\"` is wrapped in quotes, so `JSON.parse` correctly interprets it as a string. `true` is a valid JSON boolean literal, so it becomes a boolean. Always check your data types after parsing!"
  }
]
[
  {
    "id": 881,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Storage Events",
    "question": "How can you detect when `localStorage` is modified in a DIFFERENT browser tab?",
    "code_snippet": null,
    "options": ["By checking localStorage every second", "By listening for the 'storage' event on the window object", "By using a WebSocket", "You cannot detect changes across tabs"],
    "correct_answer": "By listening for the 'storage' event on the window object",
    "explanation": "The `window.addEventListener('storage', callback)` event fires whenever `localStorage` is changed, but ONLY in other tabs/windows sharing the same origin. It does NOT fire in the tab that made the change."
  },
  {
    "id": 882,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Storage Events",
    "question": "Which property of the `StorageEvent` object contains the new value that was just set?",
    "code_snippet": null,
    "options": ["event.value", "event.newValue", "event.updatedValue", "event.data"],
    "correct_answer": "event.newValue",
    "explanation": "The `StorageEvent` object provides `event.key`, `event.oldValue`, `event.newValue`, and `event.url` (the URL of the page that made the change), allowing you to sync state perfectly across tabs."
  },
  {
    "id": 883,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "History API",
    "question": "Which method allows you to add a new entry to the browser's history stack WITHOUT reloading the page?",
    "code_snippet": null,
    "options": ["window.navigate()", "history.pushState()", "history.addRoute()", "document.changeURL()"],
    "correct_answer": "history.pushState()",
    "explanation": "`history.pushState(state, title, url)` updates the URL in the address bar and adds a history entry, enabling Single Page Application (SPA) routing without full page reloads."
  },
  {
    "id": 884,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "History API",
    "question": "What is the difference between `history.pushState()` and `history.replaceState()`?",
    "code_snippet": null,
    "options": ["There is no difference", "`pushState` adds a new entry to the history stack; `replaceState` modifies the CURRENT entry in the history stack", "`replaceState` reloads the page", "`pushState` is for forward navigation, `replaceState` is for backward"],
    "correct_answer": "`pushState` adds a new entry to the history stack; `replaceState` modifies the CURRENT entry in the history stack",
    "explanation": "Use `pushState` when navigating to a new 'page' in your SPA. Use `replaceState` when you want to update the URL (like filtering a list) without creating a new back-button entry."
  },
  {
    "id": 885,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "History API",
    "question": "Fill in the blank to listen for the user clicking the browser's Back or Forward buttons.",
    "code_snippet": "window.addEventListener('_______', (event) => {\n  console.log('User navigated through history');\n});",
    "options": ["historychange", "navigate", "popstate", "routechange"],
    "correct_answer": "popstate",
    "explanation": "The `popstate` event is fired on the window whenever the active history entry changes (e.g., the user clicks Back or Forward). It does NOT fire for `pushState` or `replaceState`."
  },
  {
    "id": 886,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Geolocation",
    "question": "What is a strict security requirement for using the Geolocation API (`navigator.geolocation`) in modern browsers?",
    "code_snippet": null,
    "options": ["The user must be an administrator", "The page MUST be served over HTTPS (or localhost)", "The page must have a valid SSL certificate from a specific authority", "Geolocation only works on mobile devices"],
    "correct_answer": "The page MUST be served over HTTPS (or localhost)",
    "explanation": "Because location data is highly sensitive, browsers block the Geolocation API on insecure origins (HTTP). It will only work on HTTPS or when testing locally on `localhost`."
  },
  {
    "id": 887,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to request the user's current geographical position.",
    "code_snippet": "navigator.geolocation._______(\n  (position) => console.log(position.coords.latitude),\n  (error) => console.error(error)\n);",
    "options": ["getLocation()", "getCurrentPosition()", "fetchLocation()", "locate()"],
    "correct_answer": "getCurrentPosition()",
    "explanation": "`getCurrentPosition(successCallback, errorCallback)` prompts the user for permission and, if granted, returns their current coordinates."
  },
  {
    "id": 888,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Geolocation",
    "question": "What is the difference between `getCurrentPosition()` and `watchPosition()`?",
    "code_snippet": null,
    "options": ["`watchPosition` is faster", "`getCurrentPosition` gets the location once; `watchPosition` continuously monitors and fires the callback whenever the device moves", "`watchPosition` doesn't require user permission", "There is no difference"],
    "correct_answer": "`getCurrentPosition` gets the location once; `watchPosition` continuously monitors and fires the callback whenever the device moves",
    "explanation": "`watchPosition` is like `setInterval` for location. It's perfect for tracking a user on a map in real-time, like in a delivery app."
  },
  {
    "id": 889,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Animation Timers",
    "question": "Why is `requestAnimationFrame()` preferred over `setInterval()` for visual animations?",
    "code_snippet": null,
    "options": ["It runs on a separate thread", "It synchronizes with the browser's monitor refresh rate (usually 60fps) and pauses when the tab is in the background to save CPU", "It allows for CSS animations", "It is a synchronous function"],
    "correct_answer": "It synchronizes with the browser's monitor refresh rate (usually 60fps) and pauses when the tab is in the background to save CPU",
    "explanation": "`setInterval` doesn't know about the screen's refresh rate, which can cause 'jank' or dropped frames. `requestAnimationFrame` tells the browser to execute the callback right before the next repaint."
  },
  {
    "id": 890,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "Animation Timers",
    "question": "Fill in the blank to correctly create a continuous animation loop.",
    "code_snippet": "function animate() {\n  // update element position\n  _______(animate);\n}\nrequestAnimationFrame(animate);",
    "options": ["setTimeout", "requestAnimationFrame", "setInterval", "requestNextFrame"],
    "correct_answer": "requestAnimationFrame",
    "explanation": "To create a continuous animation, you recursively call `requestAnimationFrame` inside the callback. This ensures the animation runs smoothly at the monitor's maximum refresh rate."
  },
  {
    "id": 891,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "IntersectionObserver",
    "question": "What is the primary use case for the `IntersectionObserver` API?",
    "code_snippet": null,
    "options": ["Checking if two DOM elements overlap", "Efficiently detecting when an element enters or exits the viewport (used for lazy-loading images or infinite scroll)", "Observing changes to an element's CSS classes", "Tracking mouse movements over an element"],
    "correct_answer": "Efficiently detecting when an element enters or exits the viewport (used for lazy-loading images or infinite scroll)",
    "explanation": "Before this API, developers had to use expensive scroll event listeners and `getBoundingClientRect()`. `IntersectionObserver` runs asynchronously in the browser engine, making it incredibly performant."
  },
  {
    "id": 892,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "IntersectionObserver",
    "question": "Fill in the blank to correctly instantiate an IntersectionObserver.",
    "code_snippet": "const observer = new _______((entries) => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) {\n      loadImage(entry.target);\n    }\n  });\n});",
    "options": ["ViewportObserver", "ScrollWatcher", "IntersectionObserver", "VisibilityObserver"],
    "correct_answer": "IntersectionObserver",
    "explanation": "The `IntersectionObserver` takes a callback that receives an array of `entries`. Each entry has an `isIntersecting` boolean indicating if the target is currently visible in the root (usually the viewport)."
  },
  {
    "id": 893,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Clipboard API",
    "question": "What is the modern, secure way to copy text to the user's clipboard in JavaScript?",
    "code_snippet": null,
    "options": ["document.execCommand('copy')", "navigator.clipboard.writeText('text')", "window.copy('text')", "localStorage.setItem('clipboard', 'text')"],
    "correct_answer": "navigator.clipboard.writeText('text')",
    "explanation": "The modern Clipboard API is asynchronous and returns a Promise. It requires the page to be in focus and (usually) requires a user gesture like a click to work for security reasons."
  },
  {
    "id": 894,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Clipboard API",
    "question": "Why does `navigator.clipboard.writeText()` return a Promise?",
    "code_snippet": null,
    "options": ["Because it runs on a web worker", "Because it requires asynchronous permission checks and OS-level clipboard access, which might fail or be denied by the user", "Because it copies large files", "It doesn't return a Promise, it's synchronous"],
    "correct_answer": "Because it requires asynchronous permission checks and OS-level clipboard access, which might fail or be denied by the user",
    "explanation": "Accessing the clipboard is a sensitive security operation. The browser must asynchronously verify permissions, which is why it returns a Promise that can be caught with `.catch()`."
  },
  {
    "id": 895,
    "level": "intermediate",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Page Visibility API",
    "question": "How can you check if the user is currently looking at your browser tab?",
    "code_snippet": null,
    "options": ["window.isVisible", "document.visibilityState", "window.focusState", "document.hasFocus()"],
    "correct_answer": "document.visibilityState",
    "explanation": "`document.visibilityState` returns 'visible', 'hidden', 'prerender', or 'unloaded'. It's perfect for pausing video or stopping expensive animations when the user switches to another tab."
  },
  {
    "id": 896,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "code-fill-in-blank",
    "topic": "Page Visibility API",
    "question": "Fill in the blank to listen for the user switching to or away from your tab.",
    "code_snippet": "document.addEventListener('_______', () => {\n  if (document.hidden) pauseVideo();\n});",
    "options": ["tabchange", "focuschange", "visibilitychange", "blur"],
    "correct_answer": "visibilitychange",
    "explanation": "The `visibilitychange` event is fired on the `document` whenever the `visibilityState` changes. It is the most reliable way to know when a user leaves or returns to your tab."
  },
  {
    "id": 897,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Web Storage Quotas",
    "question": "What specific error is thrown if you try to save data to `localStorage` when it has reached its maximum capacity (usually ~5MB)?",
    "code_snippet": null,
    "options": ["StorageError", "QuotaExceededError", "CapacityError", "RangeError"],
    "correct_answer": "QuotaExceededError",
    "explanation": "If the storage is full, or if the user is in private/incognito mode (which often sets the quota to 0), `setItem()` will throw a `QuotaExceededError`. It's best practice to wrap `setItem` in a `try...catch`."
  },
  {
    "id": 898,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "Timers Quirks",
    "question": "What is the minimum delay time for nested `setTimeout` calls (5 levels deep or more) in modern browsers?",
    "code_snippet": null,
    "options": ["0ms", "1ms", "4ms", "16ms"],
    "correct_answer": "4ms",
    "explanation": "To prevent CPU battery drain from infinite recursive timers, the HTML5 specification mandates that any nested `setTimeout` or `setInterval` deeper than 5 levels will be clamped to a minimum delay of 4 milliseconds."
  },
  {
    "id": 899,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "conceptual",
    "topic": "ResizeObserver",
    "question": "What does the `ResizeObserver` API do?",
    "code_snippet": null,
    "options": ["Triggers when the browser window is resized", "Efficiently observes changes to the width and height of individual DOM elements, regardless of what caused the resize", "Changes the size of an element via CSS", "Observes the screen resolution of the monitor"],
    "correct_answer": "Efficiently observes changes to the width and height of individual DOM elements, regardless of what caused the resize",
    "explanation": "Unlike the `window.resize` event, `ResizeObserver` watches specific elements. It's perfect for building responsive components that need to redraw a chart or adjust layout when their container shrinks or grows."
  },
  {
    "id": 900,
    "level": "advanced",
    "module_id": "mod_15_web_apis",
    "module_name": "Web APIs & Storage",
    "type": "output-prediction",
    "topic": "Web Storage Quotas",
    "question": "What will happen when this code is executed in a browser's Private/Incognito mode?",
    "code_snippet": "try {\n  localStorage.setItem('test', 'data');\n} catch (e) {\n  console.log('Failed');\n}\nconsole.log('Done');",
    "options": ["It logs 'Done'", "It logs 'Failed', then 'Done'", "It throws an uncaught error and stops", "It logs 'Failed' and stops"],
    "correct_answer": "It logs 'Failed', then 'Done'",
    "explanation": "In older browsers, Private mode set the `localStorage` quota to 0, causing an immediate `QuotaExceededError`. The `try...catch` catches it, logs 'Failed', and execution continues to log 'Done'. (Note: Modern browsers often provide a temporary in-memory quota for private mode, but handling the error is still best practice)."
  }
]
