[
  {
    "id": 101,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "What is JavaScript",
    "question": "What is the primary role of JavaScript in web development?",
    "code_snippet": null,
    "options": ["Structuring the content of web pages", "Styling the layout of web pages", "Adding interactivity and dynamic behavior to web pages", "Managing database servers"],
    "correct_answer": "Adding interactivity and dynamic behavior to web pages",
    "explanation": "HTML is used for structure, CSS is used for styling, and JavaScript is used to add interactivity and dynamic behavior."
  },
  {
    "id": 102,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "What is JavaScript",
    "question": "JavaScript was originally designed to run in which environment?",
    "code_snippet": null,
    "options": ["The web browser (Client-side)", "The web server (Server-side)", "The operating system kernel", "Mobile app compilers only"],
    "correct_answer": "The web browser (Client-side)",
    "explanation": "JavaScript was created by Brendan Eich in 1995 specifically to run inside web browsers to make web pages interactive."
  },
  {
    "id": 103,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "What is JavaScript",
    "question": "Which technology allows JavaScript to run on the server-side (outside the browser)?",
    "code_snippet": null,
    "options": ["React", "Node.js", "jQuery", "Bootstrap"],
    "correct_answer": "Node.js",
    "explanation": "Node.js is a runtime environment that allows JavaScript to be executed on the server-side, outside of a web browser."
  },
  {
    "id": 104,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "What is JavaScript",
    "question": "Which of the following statements about JavaScript and Java is true?",
    "code_snippet": null,
    "options": ["They are the exact same language", "JavaScript is a simplified version of Java", "They are two completely different languages", "Java runs in the browser, JavaScript runs on the server"],
    "correct_answer": "They are two completely different languages",
    "explanation": "Despite the similar name (which was a marketing tactic in the 90s), JavaScript and Java are completely different languages with different syntax, semantics, and use cases."
  },
  {
    "id": 105,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "What is JavaScript",
    "question": "In a standard web page, JavaScript code is primarily executed by the browser's _______.",
    "code_snippet": null,
    "options": ["HTML parser", "CSS engine", "JavaScript engine", "Database"],
    "correct_answer": "JavaScript engine",
    "explanation": "Browsers contain a JavaScript engine (like V8 in Chrome or SpiderMonkey in Firefox) that reads and executes the JavaScript code."
  },
  {
    "id": 106,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "Which HTML tag is used to link an external JavaScript file to an HTML document?",
    "code_snippet": null,
    "options": ["<link>", "<script>", "<js>", "<style>"],
    "correct_answer": "<script>",
    "explanation": "The <script> tag is used to embed or reference executable JavaScript code in an HTML document."
  },
  {
    "id": 107,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "Which attribute of the <script> tag specifies the URL (path) of an external JavaScript file?",
    "code_snippet": "<script _______='app.js'></script>",
    "options": ["href", "src", "link", "url"],
    "correct_answer": "src",
    "explanation": "The 'src' (source) attribute specifies the URL of an external script file."
  },
  {
    "id": 108,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "Which attribute can be added to the <script> tag in the <head> to ensure it only executes after the HTML is fully parsed?",
    "code_snippet": "<script src='app.js' _______></script>",
    "options": ["async", "defer", "load", "wait"],
    "correct_answer": "defer",
    "explanation": "The 'defer' attribute tells the browser to download the script in the background while parsing the HTML, and only execute it after the HTML parsing is completely finished."
  },
  {
    "id": 109,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "What is the correct way to write an inline JavaScript alert when a button is clicked?",
    "code_snippet": "<button _______>Click Me</button>",
    "options": ["js='alert(\"Hi\")'", "onaction='alert(\"Hi\")'", "onclick='alert(\"Hi\")'", "script='alert(\"Hi\")'"],
    "correct_answer": "onclick='alert(\"Hi\")'",
    "explanation": "HTML event attributes like 'onclick' allow you to execute JavaScript directly within the HTML element."
  },
  {
    "id": 110,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "In modern HTML5, what is the default value of the 'type' attribute in a <script> tag, meaning you don't actually need to write it?",
    "code_snippet": null,
    "options": ["text/javascript", "text/ecmascript", "application/js", "text/typescript"],
    "correct_answer": "text/javascript",
    "explanation": "In HTML5, 'text/javascript' is the default MIME type for scripts, so writing <script type='text/javascript'> is redundant."
  },
  {
    "id": 111,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "Which method is used to print a message to the web browser's developer console?",
    "code_snippet": null,
    "options": ["print()", "console.log()", "document.write()", "window.alert()"],
    "correct_answer": "console.log()",
    "explanation": "console.log() is the standard method for writing messages to the browser's web console, primarily used for debugging."
  },
  {
    "id": 112,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "Which function displays a pop-up alert box with a specified message and an OK button in the browser?",
    "code_snippet": null,
    "options": ["msg()", "console.alert()", "alert()", "popup()"],
    "correct_answer": "alert()",
    "explanation": "The alert() function creates a small pop-up window with a message and an OK button that the user must click to dismiss."
  },
  {
    "id": 113,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "Which method writes text or HTML directly into the document stream (though generally discouraged in modern development)?",
    "code_snippet": null,
    "options": ["document.write()", "console.write()", "html.print()", "page.add()"],
    "correct_answer": "document.write()",
    "explanation": "document.write() writes directly to the HTML document. It is discouraged because if used after the page has loaded, it will overwrite the entire page."
  },
  {
    "id": 114,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "To change the text inside an HTML element with the ID 'demo', which property should you use?",
    "code_snippet": "document.getElementById('demo')._______ = 'Hello World';",
    "options": ["value", "innerHTML", "text", "content"],
    "correct_answer": "innerHTML",
    "explanation": "The innerHTML property gets or sets the HTML content inside an element. (textContent is also valid for plain text, but innerHTML is the classic answer here)."
  },
  {
    "id": 115,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Outputting Data",
    "question": "Why do developers primarily use console.log() instead of alert() for debugging code?",
    "code_snippet": null,
    "options": ["alert() is slower and blocks the execution of the code until dismissed", "console.log() can only print numbers", "alert() is deprecated in HTML5", "There is no difference, they are exactly the same"],
    "correct_answer": "alert() is slower and blocks the execution of the code until dismissed",
    "explanation": "alert() pauses the entire JavaScript execution thread until the user clicks 'OK', which ruins the user experience and makes debugging slow."
  },
  {
    "id": 116,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Comments",
    "question": "Which syntax is used to create a single-line comment in JavaScript?",
    "code_snippet": null,
    "options": ["<!-- comment -->", "# comment", "// comment", "' comment"],
    "correct_answer": "// comment",
    "explanation": "In JavaScript, two forward slashes (//) are used to comment out a single line of code."
  },
  {
    "id": 117,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Comments",
    "question": "Which syntax is used to create a multi-line comment in JavaScript?",
    "code_snippet": null,
    "options": ["<!-- comment -->", "// comment //", "/* comment */", "# comment #"],
    "correct_answer": "/* comment */",
    "explanation": "A forward slash followed by an asterisk (/*) starts a multi-line comment, and it is closed with an asterisk followed by a forward slash (*/)."
  },
  {
    "id": 118,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Comments",
    "question": "What happens to the code inside a JavaScript comment when the script is executed?",
    "code_snippet": null,
    "options": ["It is executed normally", "It is ignored by the JavaScript engine", "It throws a syntax error", "It is printed to the console"],
    "correct_answer": "It is ignored by the JavaScript engine",
    "explanation": "Comments are strictly for human readability. The JavaScript engine completely ignores them during execution."
  },
  {
    "id": 119,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Comments",
    "question": "Fill in the blank to correctly comment out the second line of code so it doesn't run.",
    "code_snippet": "let x = 5;\n_______ let y = 10;\nlet z = x + y;",
    "options": ["//", "/*", "--", "#"],
    "correct_answer": "//",
    "explanation": "Using // at the start of the line comments out the rest of that specific line, preventing 'let y = 10;' from executing."
  },
  {
    "id": 120,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "output-prediction",
    "topic": "Comments",
    "question": "What will be the exact output of the following code in the console?",
    "code_snippet": "// console.log('A');\nconsole.log('B');\n/* console.log('C'); */",
    "options": ["A", "B", "C", "B and C"],
    "correct_answer": "B",
    "explanation": "The first line is commented out with //, and the third line is commented out with /* */. Only the second line (console.log('B')) is executed."
  },
  {
    "id": 121,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "History & Ecosystem",
    "question": "Who is the original creator of JavaScript?",
    "code_snippet": null,
    "options": ["Tim Berners-Lee", "Brendan Eich", "James Gosling", "Guido van Rossum"],
    "correct_answer": "Brendan Eich",
    "explanation": "Brendan Eich created JavaScript in just 10 days in 1995 while working at Netscape Communications."
  },
  {
    "id": 122,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "History & Ecosystem",
    "question": "What is the official standardized name for the JavaScript language specification?",
    "code_snippet": null,
    "options": ["JavaStandard", "ECMAScript", "WebScript", "NodeStandard"],
    "correct_answer": "ECMAScript",
    "explanation": "ECMAScript (often abbreviated as ES) is the standard upon which JavaScript is based. You will often see versions referred to as ES6, ES2015, etc."
  },
  {
    "id": 123,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "History & Ecosystem",
    "question": "If HTML is the 'skeleton' of a webpage and CSS is the 'skin/clothing', what is JavaScript?",
    "code_snippet": null,
    "options": ["The blood", "The muscles and brain", "The environment", "The bones"],
    "correct_answer": "The muscles and brain",
    "explanation": "JavaScript provides the movement, interactivity, and logic (the muscles and brain) that brings the static HTML/CSS structure to life."
  },
  {
    "id": 124,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "Before the 'defer' and 'async' attributes were widely used, where was the recommended place to put the <script> tag in an HTML document to ensure the DOM was fully loaded?",
    "code_snippet": null,
    "options": ["Inside the <head> tag", "Right after the <body> opening tag", "Just before the </body> closing tag", "Inside the <footer> tag"],
    "correct_answer": "Just before the </body> closing tag",
    "explanation": "Placing scripts at the bottom of the <body> ensures that the HTML is fully parsed and the DOM is ready before the JavaScript tries to interact with it."
  },
  {
    "id": 125,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Linking JS to HTML",
    "question": "What is the correct syntax to write 'Internal JavaScript' directly inside an HTML file?",
    "code_snippet": null,
    "options": ["<javascript> ... </javascript>", "<js> ... </js>", "<script> ... </script>", "<code> ... </code>"],
    "correct_answer": "<script> ... </script>",
    "explanation": "The <script> tag is used for both internal JavaScript (code written directly between the tags) and external JavaScript (using the src attribute)."
  },
  {
    "id": 126,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Linking JS to HTML",
    "question": "What does adding `type=\"module\"` to a <script> tag allow you to do?",
    "code_snippet": null,
    "options": ["Write TypeScript instead of JavaScript", "Use ES6 import and export statements", "Run the script before the HTML loads", "Disable strict mode"],
    "correct_answer": "Use ES6 import and export statements",
    "explanation": "The type=\"module\" attribute tells the browser to treat the script as an ES6 module, enabling the use of import and export to share code between files."
  },
  {
    "id": 127,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "Which browser function displays a dialog box that prompts the user for input?",
    "code_snippet": null,
    "options": ["alert()", "confirm()", "prompt()", "input()"],
    "correct_answer": "prompt()",
    "explanation": "prompt() shows a dialog with a message, an input field, and OK/Cancel buttons. It returns the text the user entered."
  },
  {
    "id": 128,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Outputting Data",
    "question": "What data type does the `confirm()` function return?",
    "code_snippet": null,
    "options": ["String", "Number", "Boolean (true or false)", "Object"],
    "correct_answer": "Boolean (true or false)",
    "explanation": "confirm() displays a dialog with OK and Cancel buttons. It returns true if OK is clicked, and false if Cancel is clicked."
  },
  {
    "id": 129,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "Which console method is specifically used to log warning messages (often displayed in yellow in the browser console)?",
    "code_snippet": null,
    "options": ["console.log()", "console.warn()", "console.error()", "console.alert()"],
    "correct_answer": "console.warn()",
    "explanation": "console.warn() is used to output warning messages. It helps differentiate warnings from standard logs and errors in the developer console."
  },
  {
    "id": 130,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Outputting Data",
    "question": "If you want to view an array of objects in a nicely formatted table in the console, which method should you use?",
    "code_snippet": null,
    "options": ["console.list()", "console.grid()", "console.table()", "console.array()"],
    "correct_answer": "console.table()",
    "explanation": "console.table() is incredibly useful for visualizing arrays of objects or complex data structures as a readable table in the developer tools."
  },
  {
    "id": 131,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Basic Syntax Rules",
    "question": "Is JavaScript a case-sensitive language?",
    "code_snippet": null,
    "options": ["Yes, 'myVariable' and 'myvariable' are two different things", "No, 'myVariable' and 'myvariable' are exactly the same", "Only for variable names, not function names", "Only for function names, not variable names"],
    "correct_answer": "Yes, 'myVariable' and 'myvariable' are two different things",
    "explanation": "JavaScript is strictly case-sensitive. This applies to variables, function names, and keywords (e.g., 'While' will not work, it must be 'while')."
  },
  {
    "id": 132,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "Basic Syntax Rules",
    "question": "The standard naming convention for variables and functions in JavaScript is _______.",
    "code_snippet": null,
    "options": ["snake_case", "camelCase", "PascalCase", "kebab-case"],
    "correct_answer": "camelCase",
    "explanation": "camelCase (e.g., myFavoriteColor) is the universal standard in JavaScript for naming variables and functions. PascalCase is typically reserved for Classes."
  },
  {
    "id": 133,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Basic Syntax Rules",
    "question": "Are semicolons (;) strictly required at the end of every statement in JavaScript?",
    "code_snippet": null,
    "options": ["Yes, the code will throw an error without them", "No, JavaScript has Automatic Semicolon Insertion (ASI), but using them is highly recommended", "Only required for loops and functions", "Only required in strict mode"],
    "correct_answer": "No, JavaScript has Automatic Semicolon Insertion (ASI), but using them is highly recommended",
    "explanation": "JavaScript's ASI automatically inserts semicolons where it thinks they are needed. However, relying on it can lead to weird bugs, so most style guides recommend always typing them."
  },
  {
    "id": 134,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Basic Syntax Rules",
    "question": "Which of the following is a VALID variable name in JavaScript?",
    "code_snippet": null,
    "options": ["1stPlace", "my-variable", "_totalScore", "class"],
    "correct_answer": "_totalScore",
    "explanation": "Variable names must begin with a letter, underscore (_), or dollar sign ($). They cannot start with a number, contain hyphens, or be reserved keywords like 'class'."
  },
  {
    "id": 135,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Basic Syntax Rules",
    "question": "How do you include a double quote inside a double-quoted string without breaking the code?",
    "code_snippet": "let message = \"He said _______Hello_______ to me\";",
    "options": ["\\\"", "\\'", "&quot;", "%%"],
    "correct_answer": "\\\"",
    "explanation": "The backslash (\\) is the escape character in JavaScript. Using \\\" tells the engine to treat the quote as literal text, not the end of the string."
  },
  {
    "id": 136,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "output-prediction",
    "topic": "Outputting Data",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let age = 25;\nconsole.log(\"Age: \" + age);",
    "options": ["Age: age", "Age: 25", "Age: + 25", "Error"],
    "correct_answer": "Age: 25",
    "explanation": "The + operator is used here for string concatenation. It joins the string \"Age: \" with the string representation of the number 25."
  },
  {
    "id": 137,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "output-prediction",
    "topic": "Outputting Data",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"5\" + 5);",
    "options": ["10", "55", "5 + 5", "Error"],
    "correct_answer": "55",
    "explanation": "When you use the + operator with a string and a number, JavaScript converts the number to a string and concatenates them. \"5\" + \"5\" becomes \"55\"."
  },
  {
    "id": 138,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "History & Ecosystem",
    "question": "What is 'npm' in the JavaScript ecosystem?",
    "code_snippet": null,
    "options": ["A web browser", "A package manager for installing JS libraries", "A CSS framework", "A database system"],
    "correct_answer": "A package manager for installing JS libraries",
    "explanation": "npm (Node Package Manager) is the world's largest software registry, used by developers to share and borrow packages (libraries) for their JavaScript projects."
  },
  {
    "id": 139,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Basic Syntax Rules",
    "question": "Which characters are used to group code into a 'block' (like inside an if statement or a function)?",
    "code_snippet": null,
    "options": ["Parentheses ( )", "Square brackets [ ]", "Curly braces { }", "Angle brackets < >"],
    "correct_answer": "Curly braces { }",
    "explanation": "Curly braces { } define code blocks in JavaScript. Parentheses are for conditions/parameters, and square brackets are for arrays."
  },
  {
    "id": 140,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "output-prediction",
    "topic": "Basic Syntax Rules",
    "question": "What will happen when this code is executed?",
    "code_snippet": "console.log(Hello World);",
    "options": ["It logs 'Hello World'", "It logs 'Hello' and then 'World'", "It throws a SyntaxError", "It logs undefined"],
    "correct_answer": "It throws a SyntaxError",
    "explanation": "Strings in JavaScript must be wrapped in quotes (single, double, or backticks). Without quotes, the engine thinks 'Hello' and 'World' are variable names, causing a syntax error."
  },
  {
    "id": 141,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Strict Mode",
    "question": "What is the purpose of adding \"use strict\" at the top of a JavaScript file?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It enforces stricter parsing and error handling rules", "It allows the use of older JavaScript features", "It connects the file to a database"],
    "correct_answer": "It enforces stricter parsing and error handling rules",
    "explanation": "\"use strict\" puts the script into strict mode, which catches common coding mistakes, prevents the use of unsafe actions, and disables confusing features."
  },
  {
    "id": 142,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Strict Mode",
    "question": "Where must the \"use strict\" directive be placed to apply to the entire script?",
    "code_snippet": "_______\nlet x = 10;",
    "options": ["At the very bottom of the file", "At the very top of the file or function", "Inside a comment", "After the first variable declaration"],
    "correct_answer": "At the very top of the file or function",
    "explanation": "The \"use strict\" directive must be the very first statement in a script or function to apply to the entire block. If placed after other code, it is ignored."
  },
  {
    "id": 143,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Console Methods",
    "question": "Which console method is best for displaying an interactive, tree-like list of properties for a specified JavaScript object?",
    "code_snippet": null,
    "options": ["console.log()", "console.dir()", "console.info()", "console.print()"],
    "correct_answer": "console.dir()",
    "explanation": "console.dir() displays an interactive list of the properties of the specified JavaScript object, which is especially useful for inspecting DOM elements."
  },
  {
    "id": 144,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Console Methods",
    "question": "Which pair of console methods is used to measure exactly how long a block of code takes to execute?",
    "code_snippet": null,
    "options": ["console.start() and console.stop()", "console.begin() and console.end()", "console.time() and console.timeEnd()", "console.clock() and console.clockEnd()"],
    "correct_answer": "console.time() and console.timeEnd()",
    "explanation": "console.time() starts a timer, and console.timeEnd() stops it and logs the elapsed time in milliseconds to the console."
  },
  {
    "id": 145,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Console Methods",
    "question": "Which console method writes an error message to the console ONLY if the first argument evaluates to false?",
    "code_snippet": null,
    "options": ["console.error()", "console.false()", "console.assert()", "console.check()"],
    "correct_answer": "console.assert()",
    "explanation": "console.assert() is used for debugging. If the assertion (the first argument) is false, the provided error message is written to the console. If true, nothing happens."
  },
  {
    "id": 146,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "Developer Tools",
    "question": "Which keyboard function key is universally used in most desktop browsers to open the Developer Tools?",
    "code_snippet": null,
    "options": ["F5", "F12", "F1", "F8"],
    "correct_answer": "F12",
    "explanation": "Pressing F12 (or Ctrl+Shift+I / Cmd+Option+I) opens the browser's Developer Tools, which are essential for debugging and inspecting web pages."
  },
  {
    "id": 147,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Basic Errors",
    "question": "What type of error occurs when you write code that violates the grammatical rules (syntax) of JavaScript, like forgetting a closing parenthesis?",
    "code_snippet": null,
    "options": ["ReferenceError", "TypeError", "SyntaxError", "LogicError"],
    "correct_answer": "SyntaxError",
    "explanation": "A SyntaxError is thrown when the JavaScript engine encounters code that does not conform to the language's structural rules. The code will not run at all."
  },
  {
    "id": 148,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Basic Errors",
    "question": "What type of error occurs when you try to use a variable that has not been declared yet?",
    "code_snippet": null,
    "options": ["SyntaxError", "ReferenceError", "TypeError", "RangeError"],
    "correct_answer": "ReferenceError",
    "explanation": "A ReferenceError is thrown when you try to access a variable that doesn't exist in the current scope (e.g., typo in the variable name or forgetting to declare it)."
  },
  {
    "id": 149,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Syntax Rules",
    "question": "Which of the following words is a RESERVED keyword in JavaScript and CANNOT be used as a variable name?",
    "code_snippet": null,
    "options": ["myVar", "total", "function", "data123"],
    "correct_answer": "function",
    "explanation": "'function' is a reserved keyword used to declare functions. Using it as a variable name will cause a SyntaxError. The other options are valid identifiers."
  },
  {
    "id": 150,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Syntax Rules",
    "question": "Which of the following special characters are ALLOWED as the first character of a variable name in JavaScript?",
    "code_snippet": null,
    "options": ["Numbers (0-9)", "Hyphens (-)", "Dollar signs ($) and Underscores (_)", "Spaces"],
    "correct_answer": "Dollar signs ($) and Underscores (_)",
    "explanation": "Variable names must begin with a letter, an underscore (_), or a dollar sign ($). They cannot start with a number or contain spaces/hyphens."
  },
  {
    "id": 151,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Syntax Rules",
    "question": "How do you insert a NEW LINE inside a standard double-quoted string in JavaScript?",
    "code_snippet": "let text = \"Line 1_______Line 2\";",
    "options": ["\\n", "\\b", "\\t", "<br>"],
    "correct_answer": "\\n",
    "explanation": "The \\n escape sequence represents a newline character. When printed, it moves the text to the next line. (<br> is for HTML, not JS strings)."
  },
  {
    "id": 152,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "code-fill-in-blank",
    "topic": "Console Methods",
    "question": "Which console method is used to clear all previous messages from the developer console?",
    "code_snippet": null,
    "options": ["console.delete()", "console.clear()", "console.remove()", "console.empty()"],
    "correct_answer": "console.clear()",
    "explanation": "console.clear() wipes the console clean. You can also achieve this by clicking the 'clear console' icon (a circle with a slash) in the browser's DevTools UI."
  },
  {
    "id": 153,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Console Methods",
    "question": "What is the purpose of `console.group()` and `console.groupEnd()`?",
    "code_snippet": null,
    "options": ["To group multiple variables into an array", "To create collapsible, nested blocks of messages in the console", "To group CSS styles together", "To prevent other scripts from running"],
    "correct_answer": "To create collapsible, nested blocks of messages in the console",
    "explanation": "console.group() starts a new inline group in the console, indenting subsequent logs. console.groupEnd() exits the group. This keeps complex logs organized."
  },
  {
    "id": 154,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "output-prediction",
    "topic": "Basic Math",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(10 + 5 * 2);",
    "options": ["30", "20", "25", "15"],
    "correct_answer": "20",
    "explanation": "Multiplication (*) has higher mathematical precedence than addition (+). So, 5 * 2 is calculated first (10), and then 10 + 10 equals 20."
  },
  {
    "id": 155,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "output-prediction",
    "topic": "String Concatenation",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"10\" + 5);",
    "options": ["15", "105", "\"105\"", "NaN"],
    "correct_answer": "105",
    "explanation": "When using the + operator with a string and a number, JavaScript converts the number to a string and concatenates them. \"10\" + \"5\" becomes the string \"105\"."
  },
  {
    "id": 156,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Browser Objects",
    "question": "In a web browser, what is the `window` object?",
    "code_snippet": null,
    "options": ["A pop-up advertisement", "The global object that represents the browser window", "A CSS styling tool", "A JavaScript framework"],
    "correct_answer": "The global object that represents the browser window",
    "explanation": "The `window` object is the global object in client-side JavaScript. It represents the browser's window, and all global variables and functions become properties of it."
  },
  {
    "id": 157,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Browser Objects",
    "question": "In a web browser, what does the `document` object represent?",
    "code_snippet": null,
    "options": ["A Microsoft Word file", "The entire HTML webpage loaded in the browser", "The browser's history", "The server's database"],
    "correct_answer": "The entire HTML webpage loaded in the browser",
    "explanation": "The `document` object is a property of the `window` object. It represents the HTML DOM (Document Object Model), allowing JavaScript to read and modify the webpage's content."
  },
  {
    "id": 158,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "theory-fill-in-blank",
    "topic": "Developer Tools",
    "question": "In the Browser Developer Tools, which specific tab allows you to see the output of `console.log()` and track errors?",
    "code_snippet": null,
    "options": ["Elements", "Network", "Console", "Sources"],
    "correct_answer": "Console",
    "explanation": "The Console tab is specifically designed to show log messages, warnings, errors, and allows you to execute JavaScript code directly in the browser."
  },
  {
    "id": 159,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Debugging Concepts",
    "question": "In programming, what is a \"bug\"?",
    "code_snippet": null,
    "options": ["A type of computer virus", "An error or flaw in the code that causes it to produce an incorrect or unexpected result", "A feature that is not yet implemented", "A hardware malfunction"],
    "correct_answer": "An error or flaw in the code that causes it to produce an incorrect or unexpected result",
    "explanation": "A bug is any mistake in the code's logic, syntax, or structure that prevents the program from running correctly or producing the expected output."
  },
  {
    "id": 160,
    "level": "beginner",
    "module_id": "mod_01_intro",
    "module_name": "Introduction & Basics",
    "type": "conceptual",
    "topic": "Debugging Concepts",
    "question": "What is the process of finding, analyzing, and fixing errors (bugs) in JavaScript code called?",
    "code_snippet": null,
    "options": ["Compiling", "Debugging", "Executing", "Deploying"],
    "correct_answer": "Debugging",
    "explanation": "Debugging is the systematic process of identifying and removing errors from code. Tools like console.log() and browser DevTools are essential for this process."
  }
]
