[
  {
    "id": 551,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Template Literals",
    "question": "Which character is used to define a Template Literal in JavaScript?",
    "code_snippet": "let greeting = _______Hello World_______;",
    "options": ["Single quotes (')", "Double quotes (\")", "Backticks (`)", "Parentheses ()"],
    "correct_answer": "Backticks (`)",
    "explanation": "Template literals are enclosed by backtick characters (`) instead of single or double quotes. This enables multi-line strings and embedded expressions."
  },
  {
    "id": 552,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Template Literals",
    "question": "What is a major advantage of using Template Literals over standard string concatenation with the `+` operator?",
    "code_snippet": null,
    "options": ["They run significantly faster", "They allow for easy multi-line strings and embedded expressions without messy concatenation", "They automatically translate text to other languages", "They prevent XSS attacks"],
    "correct_answer": "They allow for easy multi-line strings and embedded expressions without messy concatenation",
    "explanation": "Template literals preserve line breaks exactly as written and allow you to inject variables directly using `${variable}`, making code much cleaner and more readable."
  },
  {
    "id": 553,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Template Literals",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let a = 5;\nlet b = 10;\nconsole.log(`Fifteen is ${a + b} and not ${2 * a + b}.`);",
    "options": ["Fifteen is ${a + b} and not ${2 * a + b}.", "Fifteen is 15 and not 20.", "Fifteen is 510 and not 1010.", "Error"],
    "correct_answer": "Fifteen is 15 and not 20.",
    "explanation": "The expressions inside `${}` are evaluated as standard JavaScript code. `5 + 10` is 15, and `2 * 5 + 10` is 20."
  },
  {
    "id": 554,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Tagged Templates",
    "question": "What is a 'Tagged Template' in JavaScript?",
    "code_snippet": null,
    "options": ["A template literal with an HTML tag inside it", "A function that parses a template literal and returns a modified string or value", "A way to tag a string so it cannot be modified", "A template literal that automatically translates text"],
    "correct_answer": "A function that parses a template literal and returns a modified string or value",
    "explanation": "Tagged templates allow you to write a function (the 'tag') that receives the string parts and the interpolated values separately, allowing you to manipulate them before returning the final result (used heavily in libraries like styled-components or GraphQL)."
  },
  {
    "id": 555,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Tagged Templates",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function upper(strings, ...values) {\n  return strings[0] + values[0].toUpperCase();\n}\nconst name = 'alice';\nconsole.log(upper`Hello ${name}`);",
    "options": ["Hello alice", "Hello ALICE", "HELLO ALICE", "Error"],
    "correct_answer": "Hello ALICE",
    "explanation": "The tag function receives the string parts (`['Hello ']`) and the values (`['alice']`). It concatenates the first string part with the uppercased value, resulting in 'Hello ALICE'."
  },
  {
    "id": 556,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Array Destructuring",
    "question": "Fill in the blank to correctly destructure the first two elements of an array into variables.",
    "code_snippet": "const colors = ['red', 'green', 'blue'];\nconst [first, second] _______ colors;",
    "options": ["=", "==", "=>", ":"],
    "correct_answer": "=",
    "explanation": "Array destructuring uses the assignment operator `=`. The syntax on the left side `[first, second]` mirrors the array structure to extract the values."
  },
  {
    "id": 557,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Array Destructuring",
    "question": "What will be the exact output of the following code? (Notice the empty space!)",
    "code_snippet": "const numbers = [10, 20, 30, 40];\nconst [a, , b] = numbers;\nconsole.log(b);",
    "options": ["10", "20", "30", "40"],
    "correct_answer": "30",
    "explanation": "By leaving an empty space between the commas, you skip the second element (20). `a` gets 10, and `b` gets the third element, which is 30."
  },
  {
    "id": 558,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Array Destructuring",
    "question": "Fill in the blank to collect the remaining elements of the array into a new array called `rest`.",
    "code_snippet": "const [first, _______rest] = [1, 2, 3, 4];\nconsole.log(rest); // [2, 3, 4]",
    "options": ["...", "**", "@", "&"],
    "correct_answer": "...",
    "explanation": "The Rest parameter syntax (`...`) in destructuring gathers all remaining, unassigned elements into a new array."
  },
  {
    "id": 559,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Array Destructuring",
    "question": "How can you swap the values of two variables `a` and `b` without using a temporary third variable?",
    "code_snippet": null,
    "options": ["a = b; b = a;", "[a, b] = [b, a];", "swap(a, b);", "a <-> b;"],
    "correct_answer": "[a, b] = [b, a];",
    "explanation": "Array destructuring allows for elegant variable swapping. The right side creates a temporary array `[b, a]`, and the left side immediately destructures it back into `a` and `b` in reverse order."
  },
  {
    "id": 560,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Array Destructuring",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let x = 1, y = 2;\n[x, y] = [y, x];\nconsole.log(x, y);",
    "options": ["1, 2", "2, 1", "1, 1", "Error"],
    "correct_answer": "2, 1",
    "explanation": "The destructuring assignment swaps the values. `x` takes the value of `y` (2), and `y` takes the value of `x` (1)."
  },
  {
    "id": 561,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Array Destructuring",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const [a, b = 5] = [1];\nconsole.log(b);",
    "options": ["undefined", "null", "5", "Error"],
    "correct_answer": "5",
    "explanation": "The array only has one element, so `b` is assigned `undefined`. Because `undefined` triggers the default value in destructuring, `b` becomes 5."
  },
  {
    "id": 562,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Array Destructuring",
    "question": "What will be the exact output of the following nested array destructuring?",
    "code_snippet": "const [a, [b, c]] = [1, [2, 3]];\nconsole.log(c);",
    "options": ["1", "2", "3", "undefined"],
    "correct_answer": "3",
    "explanation": "The first element `1` goes to `a`. The second element is the array `[2, 3]`, which is immediately destructured into `b` (2) and `c` (3)."
  },
  {
    "id": 563,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Default Parameters",
    "question": "When are default parameters evaluated in JavaScript?",
    "code_snippet": null,
    "options": ["When the function is declared", "At call time, from left to right", "At call time, from right to left", "They are evaluated randomly"],
    "correct_answer": "At call time, from left to right",
    "explanation": "Default parameters are evaluated at the time the function is called, and they are processed sequentially from left to right. This allows later parameters to reference earlier ones."
  },
  {
    "id": 564,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Default Parameters TDZ",
    "question": "What will happen when this code is executed?",
    "code_snippet": "function foo(a = b, b = 2) {\n  console.log(a);\n}\nfoo();",
    "options": ["It logs 2", "It logs undefined", "It throws a ReferenceError", "It logs NaN"],
    "correct_answer": "It throws a ReferenceError",
    "explanation": "Because default parameters are evaluated left-to-right, when `a` is being initialized, it tries to access `b`. However, `b` hasn't been initialized yet (it's in the Temporal Dead Zone), resulting in a ReferenceError."
  },
  {
    "id": 565,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Default Parameters",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function greet(name = 'Stranger') {\n  console.log(`Hello ${name}`);\n}\ngreet(null);",
    "options": ["Hello Stranger", "Hello null", "Hello undefined", "Error"],
    "correct_answer": "Hello null",
    "explanation": "Default parameters are ONLY triggered by `undefined` or by omitting the argument entirely. Passing `null` is considered an intentional value, so the default is NOT used."
  },
  {
    "id": 566,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Default Parameters",
    "question": "Fill in the blank to set the default `height` to be the exact same value as the `width` (creating a square if height is omitted).",
    "code_snippet": "function createRect(width, height = _______) {\n  return { width, height };\n}",
    "options": ["width", "0", "undefined", "this.width"],
    "correct_answer": "width",
    "explanation": "Because default parameters are evaluated left-to-right, a parameter on the right can reference the value of a parameter on the left. If `height` is omitted, it defaults to whatever `width` is."
  },
  {
    "id": 567,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Spread Operator",
    "question": "Fill in the blank to create a true, independent shallow copy of an array using the Spread operator.",
    "code_snippet": "const original = [1, 2, 3];\nconst copy = [_______original];",
    "options": ["...", "**", "@", "&"],
    "correct_answer": "...",
    "explanation": "The spread operator `...` unpacks the elements of the `original` array. Wrapping it in brackets `[...]` creates a brand new array with the same values."
  },
  {
    "id": 568,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Spread Operator",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const a = [1, 2];\nconst b = [3, 4];\nconst c = [...a, ...b];\nconsole.log(c);",
    "options": ["[1, 2, 3, 4]", "[[1, 2], [3, 4]]", "[3, 4, 1, 2]", "Error"],
    "correct_answer": "[1, 2, 3, 4]",
    "explanation": "The spread operator expands both arrays into individual elements. They are then combined into a single, flat array in the order they were spread."
  },
  {
    "id": 569,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Rest Parameter",
    "question": "Where MUST the Rest parameter be placed when used inside an array destructuring assignment?",
    "code_snippet": null,
    "options": ["At the beginning", "In the middle", "At the very end", "Anywhere"],
    "correct_answer": "At the very end",
    "explanation": "Just like in function parameters, the Rest element in array destructuring must be the last element. It wouldn't make sense to have variables after it, because the Rest element 'catches' everything else."
  },
  {
    "id": 570,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Spread Operator",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const str = 'hello';\nconst chars = [...str];\nconsole.log(chars);",
    "options": ["['hello']", "['h', 'e', 'l', 'l', 'o']", "h, e, l, l, o", "Error"],
    "correct_answer": "['h', 'e', 'l', 'l', 'o']",
    "explanation": "Strings are iterable in JavaScript. The spread operator can expand a string into an array of its individual characters."
  }
]
[
  {
    "id": 571,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Map",
    "question": "What is the main advantage of using a `Map` over a standard JavaScript Object for key-value pairs?",
    "code_snippet": null,
    "options": ["Maps are faster to write", "Maps allow any data type (including objects and functions) to be used as a key, and they maintain insertion order", "Maps automatically sort the keys alphabetically", "Maps do not require the `new` keyword"],
    "correct_answer": "Maps allow any data type (including objects and functions) to be used as a key, and they maintain insertion order",
    "explanation": "Standard objects coerce keys to strings. Maps remember the exact reference of the key, meaning you can use an object or a function as a key. They also guarantee iteration in insertion order."
  },
  {
    "id": 572,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Map",
    "question": "Fill in the blank to correctly add a key-value pair to a Map.",
    "code_snippet": "const myMap = new Map();\nmyMap._______('name', 'Alice');",
    "options": ["add()", "set()", "put()", "push()"],
    "correct_answer": "set()",
    "explanation": "The `.set(key, value)` method is used to add or update a key-value pair in a Map. It returns the Map object, allowing for method chaining."
  },
  {
    "id": 573,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Map",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const userRoles = new Map();\nconst userObj = { id: 1 };\nuserRoles.set(userObj, 'Admin');\nconsole.log(userRoles.get(userObj));",
    "options": ["undefined", "Admin", "{ id: 1 }", "Error"],
    "correct_answer": "Admin",
    "explanation": "Because Maps use strict reference equality for keys, passing the exact same `userObj` reference to `.get()` successfully retrieves the value 'Admin'."
  },
  {
    "id": 574,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Map",
    "question": "How do you find out how many key-value pairs are currently stored in a Map?",
    "code_snippet": "const myMap = new Map([['a', 1], ['b', 2]]);\nconsole.log(myMap._______);",
    "options": ["length", "size", "count", "total"],
    "correct_answer": "size",
    "explanation": "Unlike arrays which use `.length`, Maps (and Sets) use the `.size` property to return the number of elements they contain."
  },
  {
    "id": 575,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Set",
    "question": "What is the defining characteristic of a `Set` in JavaScript?",
    "code_snippet": null,
    "options": ["It stores key-value pairs", "It stores a collection of unique values (no duplicates allowed)", "It stores values in a fixed-size array", "It automatically sorts values numerically"],
    "correct_answer": "It stores a collection of unique values (no duplicates allowed)",
    "explanation": "A Set is a collection of values where each value must be unique. If you try to add a duplicate, it is simply ignored."
  },
  {
    "id": 576,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Set",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const nums = new Set([1, 2, 2, 3, 3, 3]);\nconsole.log(nums.size);",
    "options": ["6", "3", "1", "Error"],
    "correct_answer": "3",
    "explanation": "The Set automatically removes the duplicate 2s and 3s during initialization. The final Set only contains the unique values: 1, 2, and 3. Therefore, the size is 3."
  },
  {
    "id": 577,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Set",
    "question": "Fill in the blank to add a new value to a Set.",
    "code_snippet": "const colors = new Set(['red', 'blue']);\ncolors._______('green');",
    "options": ["add()", "push()", "set()", "insert()"],
    "correct_answer": "add()",
    "explanation": "The `.add(value)` method appends a new element to the end of a Set object (if it isn't already present)."
  },
  {
    "id": 578,
    "level": "intermediate",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Set",
    "question": "What is the most common real-world use case for converting an Array to a Set and back to an Array?",
    "code_snippet": null,
    "options": ["Sorting the array", "Removing all duplicate values from the array", "Reversing the array", "Filtering out falsy values"],
    "correct_answer": "Removing all duplicate values from the array",
    "explanation": "The classic one-liner to deduplicate an array is `const uniqueArr = [...new Set(originalArr)];`. The Set removes duplicates, and the spread operator turns it back into an array."
  },
  {
    "id": 579,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Symbols",
    "question": "What is a `Symbol` in JavaScript?",
    "code_snippet": null,
    "options": ["A special type of string used for HTML tags", "A unique and immutable primitive data type, often used as an identifier for object properties", "A mathematical operator", "A deprecated feature from ES5"],
    "correct_answer": "A unique and immutable primitive data type, often used as an identifier for object properties",
    "explanation": "Symbols are guaranteed to be unique. Even if you create two symbols with the exact same description (`Symbol('id') === Symbol('id')` is false), they are completely different values."
  },
  {
    "id": 580,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Symbols",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const id1 = Symbol('id');\nconst id2 = Symbol('id');\nconsole.log(id1 === id2);",
    "options": ["true", "false", "undefined", "Error"],
    "correct_answer": "false",
    "explanation": "Every call to `Symbol()` creates a brand new, completely unique value. The string 'id' is just a description for debugging purposes; it does not make them equal."
  },
  {
    "id": 581,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Symbols",
    "question": "Why would you use a Symbol as an object property key instead of a string?",
    "code_snippet": null,
    "options": ["It makes the object run faster", "It 'hides' the property from standard enumeration (like `Object.keys()` or `for...in`), preventing naming collisions", "It allows the property to hold multiple values", "It encrypts the property value"],
    "correct_answer": "It 'hides' the property from standard enumeration (like `Object.keys()` or `for...in`), preventing naming collisions",
    "explanation": "Symbol-keyed properties are skipped by `Object.keys()`, `Object.getOwnPropertyNames()`, and `for...in` loops. They are 'hidden' unless you specifically know the Symbol or use `Object.getOwnPropertySymbols()`."
  },
  {
    "id": 582,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Iterators",
    "question": "What is the 'Iterator Protocol' in JavaScript?",
    "code_snippet": null,
    "options": ["A rule for how to write `for` loops", "A standard way for an object to produce a sequence of values by having a `next()` method that returns `{ value, done }`", "A method to sort arrays", "A way to connect to a database"],
    "correct_answer": "A standard way for an object to produce a sequence of values by having a `next()` method that returns `{ value, done }`",
    "explanation": "Any object that implements a `next()` method returning an object with `value` and `done` properties is an iterator. This is the engine under the hood of `for...of` loops."
  },
  {
    "id": 583,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "code-fill-in-blank",
    "topic": "Generators",
    "question": "Which syntax is used to declare a Generator function?",
    "code_snippet": "_______ function* countUp() {\n  yield 1;\n  yield 2;\n}",
    "options": ["async", "function*", "generator", "yield"],
    "correct_answer": "function*",
    "explanation": "Generator functions are declared using the `function*` syntax (the asterisk is mandatory). They return a Generator object which is an iterator."
  },
  {
    "id": 584,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Generators",
    "question": "What does the `yield` keyword do inside a generator function?",
    "code_snippet": null,
    "options": ["It throws an error and stops the function", "It pauses the function execution and returns a value to the caller, resuming from that exact spot later", "It returns a value and completely exits the function", "It loops back to the beginning of the function"],
    "correct_answer": "It pauses the function execution and returns a value to the caller, resuming from that exact spot later",
    "explanation": "`yield` is the magic of generators. It acts like a checkpoint. When `.next()` is called, it runs until the next `yield`, pauses, and hands the value back."
  },
  {
    "id": 585,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Generators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function* gen() {\n  yield 'A';\n  yield 'B';\n}\nconst iterator = gen();\nconsole.log(iterator.next().value);",
    "options": ["A", "B", "undefined", "{ value: 'A', done: false }"],
    "correct_answer": "A",
    "explanation": "Calling `gen()` returns the iterator object. Calling `.next()` runs the function until the first `yield` ('A') and returns `{ value: 'A', done: false }`. We then access the `.value` property, which is 'A'."
  },
  {
    "id": 586,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "output-prediction",
    "topic": "Generators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function* gen() {\n  yield 1;\n  yield 2;\n}\nconst it = gen();\nit.next();\nconsole.log(it.next().value);",
    "options": ["1", "2", "undefined", "Error"],
    "correct_answer": "2",
    "explanation": "The first `it.next()` runs until `yield 1` and pauses. The second `it.next()` resumes execution from where it left off, runs until `yield 2`, and returns `{ value: 2, done: false }`. We log the `.value`, which is 2."
  },
  {
    "id": 587,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Iterables",
    "question": "What makes an object 'iterable' (allowing it to be used in a `for...of` loop)?",
    "code_snippet": null,
    "options": ["It must have a `.length` property", "It must have a method keyed by `Symbol.iterator` that returns an iterator", "It must be an Array or a String", "It must be declared with the `iterable` keyword"],
    "correct_answer": "It must have a method keyed by `Symbol.iterator` that returns an iterator",
    "explanation": "The `for...of` loop looks for the `Symbol.iterator` method on the object. Arrays, Strings, Maps, and Sets all have this built-in. Plain objects do not, which is why `for...of` throws an error on them by default."
  },
  {
    "id": 588,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "Generators as Iterables",
    "question": "Why can you use a `for...of` loop directly on a generator function call (e.g., `for (let val of myGen())`)?",
    "code_snippet": null,
    "options": ["Because generators are just arrays in disguise", "Because the generator object returned by `function*` automatically implements the `Symbol.iterator` protocol", "Because `for...of` converts everything to strings", "You cannot use `for...of` on generators"],
    "correct_answer": "Because the generator object returned by `function*` automatically implements the `Symbol.iterator` protocol",
    "explanation": "Generator objects are both Iterators (they have `.next()`) AND Iterables (their `Symbol.iterator` returns `this`). This makes them perfectly compatible with `for...of` loops."
  },
  {
    "id": 589,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "WeakMap / WeakSet",
    "question": "What is the main difference between a `Map` and a `WeakMap`?",
    "code_snippet": null,
    "options": ["WeakMaps are faster", "WeakMaps only accept objects as keys, and they do not prevent those key objects from being garbage collected", "WeakMaps cannot store values, only keys", "WeakMaps automatically sort their keys"],
    "correct_answer": "WeakMaps only accept objects as keys, and they do not prevent those key objects from being garbage collected",
    "explanation": "In a standard Map, holding a reference to an object as a key prevents it from being deleted from memory (garbage collected). WeakMaps hold 'weak' references, meaning if the key object is no longer used anywhere else in your code, it can be garbage collected, preventing memory leaks."
  },
  {
    "id": 590,
    "level": "advanced",
    "module_id": "mod_09_es6",
    "module_name": "Modern JavaScript (ES6+ Features)",
    "type": "conceptual",
    "topic": "WeakMap / WeakSet",
    "question": "Why can't you iterate over a `WeakMap` or `WeakSet` using a `for...of` loop?",
    "code_snippet": null,
    "options": ["It's a syntax error in ES6", "Because the keys/values might be garbage collected at any moment, making a reliable iteration impossible", "Because they are empty by default", "Because they only hold primitive values"],
    "correct_answer": "Because the keys/values might be garbage collected at any moment, making a reliable iteration impossible",
    "explanation": "Since the JavaScript engine can silently remove entries from a WeakMap/WeakSet in the background when memory needs to be freed, there is no guaranteed list of items to iterate over at any given millisecond."
  }
]
