[
  {
    "id": 781,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "OOP Pillars",
    "question": "Which of the following is NOT one of the four fundamental pillars of Object-Oriented Programming?",
    "code_snippet": null,
    "options": ["Encapsulation", "Inheritance", "Compilation", "Polymorphism"],
    "correct_answer": "Compilation",
    "explanation": "The 4 pillars of OOP are Encapsulation, Abstraction, Inheritance, and Polymorphism. Compilation is a process of translating code, not an OOP concept."
  },
  {
    "id": 782,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Constructor Functions",
    "question": "Before ES6 Classes, what was the standard way to create multiple similar objects in JavaScript?",
    "code_snippet": null,
    "options": ["Using a `for` loop", "Using Constructor Functions (regular functions invoked with the `new` keyword)", "Using the `Object.clone()` method", "Using HTML templates"],
    "correct_answer": "Using Constructor Functions (regular functions invoked with the `new` keyword)",
    "explanation": "In ES5, developers used regular functions capitalized by convention (e.g., `function User() {}`) and called them with `new` to create object instances. ES6 `class` syntax is just syntactic sugar over this exact mechanism."
  },
  {
    "id": 783,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "The 'new' Keyword",
    "question": "What exactly happens behind the scenes when you call a function with the `new` keyword?",
    "code_snippet": null,
    "options": ["It compiles the function to machine code", "It creates a blank object, binds `this` to it, links its prototype, and returns it automatically", "It converts the function into an arrow function", "It prevents the function from accessing global variables"],
    "correct_answer": "It creates a blank object, binds `this` to it, links its prototype, and returns it automatically",
    "explanation": "The `new` keyword does 4 things: 1. Creates a new empty object. 2. Sets `this` to point to that new object. 3. Links the object's `__proto__` to the function's `prototype`. 4. Returns the object (unless the function explicitly returns a different object)."
  },
  {
    "id": 784,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "The 'new' Keyword",
    "question": "Fill in the blank to correctly create a new instance of the `Car` constructor.",
    "code_snippet": "function Car(brand) { this.brand = brand; }\nconst myCar = _______ Car('Toyota');",
    "options": ["create", "new", "instance", "make"],
    "correct_answer": "new",
    "explanation": "The `new` keyword is required to invoke a constructor function properly. Without it, `this` would default to the global object, and it would return `undefined`."
  },
  {
    "id": 785,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "The Prototype Property",
    "question": "What is the `prototype` property on a function used for?",
    "code_snippet": null,
    "options": ["To store the function's source code", "To define properties and methods that will be shared among all instances created by that constructor", "To prevent the function from being modified", "To link the function to the DOM"],
    "correct_answer": "To define properties and methods that will be shared among all instances created by that constructor",
    "explanation": "When you create an object with `new`, its internal `[[Prototype]]` (accessible via `__proto__`) is set to the constructor function's `.prototype` object. This allows all instances to share the same methods, saving memory."
  },
  {
    "id": 786,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Adding to Prototype",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function Dog(name) { this.name = name; }\nDog.prototype.bark = function() { return 'Woof!'; };\nconst rex = new Dog('Rex');\nconsole.log(rex.bark());",
    "options": ["undefined", "Error: rex.bark is not a function", "Woof!", "function() { return 'Woof!'; }"],
    "correct_answer": "Woof!",
    "explanation": "Even though `rex` doesn't have a `bark` method directly on itself, JavaScript looks up the prototype chain, finds `bark` on `Dog.prototype`, and executes it. `this` correctly refers to `rex`."
  },
  {
    "id": 787,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Prototype Chain",
    "question": "What is the 'Prototype Chain' in JavaScript?",
    "code_snippet": null,
    "options": ["A list of all variables in the global scope", "The mechanism where an object delegates property lookups to its prototype, which delegates to its prototype, all the way up to `Object.prototype` and finally `null`", "A method to chain array methods together", "A security feature that blocks access to private variables"],
    "correct_answer": "The mechanism where an object delegates property lookups to its prototype, which delegates to its prototype, all the way up to `Object.prototype` and finally `null`",
    "explanation": "If you ask an object for a property it doesn't have, JS checks its `__proto__`. If it's not there, it checks the `__proto__` of that prototype, continuing until it reaches `Object.prototype`, and finally `null`."
  },
  {
    "id": 788,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Prototype Chain Lookup",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = {};\nconsole.log(obj.toString === Object.prototype.toString);",
    "options": ["true", "false", "undefined", "Error"],
    "correct_answer": "true",
    "explanation": "The empty object `obj` doesn't have a `toString` method. JS looks up the prototype chain, finds `toString` on `Object.prototype`, and returns a reference to that exact function."
  },
  {
    "id": 789,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "Object.create()",
    "question": "Fill in the blank to create a new object that uses `personProto` as its direct prototype.",
    "code_snippet": "const personProto = { greet() { return 'Hi'; } };\nconst alice = Object._______(personProto);",
    "options": ["assign", "create", "link", "inherit"],
    "correct_answer": "create",
    "explanation": "`Object.create(proto)` creates a brand new object and sets its internal `[[Prototype]]` to the object you passed in. It's the purest form of prototypal inheritance."
  },
  {
    "id": 790,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Object.create() vs new",
    "question": "What is the main difference between `Object.create(proto)` and using the `new` keyword?",
    "code_snippet": null,
    "options": ["`Object.create` is faster", "`new` executes a constructor function to initialize properties, while `Object.create` simply links objects without running any initialization code", "`Object.create` is for arrays, `new` is for objects", "There is no difference"],
    "correct_answer": "`new` executes a constructor function to initialize properties, while `Object.create` simply links objects without running any initialization code",
    "explanation": "`new` is tied to constructor functions and runs their setup code. `Object.create` is purely about linking the prototype chain and requires you to manually set up properties afterward."
  },
  {
    "id": 791,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "hasOwnProperty",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function User() { this.name = 'Alice'; }\nUser.prototype.age = 25;\nconst u = new User();\nconsole.log(u.hasOwnProperty('name'), u.hasOwnProperty('age'));",
    "options": ["true, true", "true, false", "false, true", "false, false"],
    "correct_answer": "true, false",
    "explanation": "`hasOwnProperty` ONLY checks the object itself, NOT the prototype chain. `name` is directly on `u` (true), but `age` is on `User.prototype` (false)."
  },
  {
    "id": 792,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "instanceof",
    "question": "What does the `instanceof` operator check?",
    "code_snippet": null,
    "options": ["If an object has a specific property", "If an object's prototype chain includes the `.prototype` property of a specific constructor function", "If two objects are strictly equal", "If an object is an array"],
    "correct_answer": "If an object's prototype chain includes the `.prototype` property of a specific constructor function",
    "explanation": "`obj instanceof Car` walks up `obj`'s prototype chain looking for `Car.prototype`. If it finds it, it returns `true`."
  },
  {
    "id": 793,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "instanceof",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function Animal() {}\nfunction Dog() {}\nDog.prototype = Object.create(Animal.prototype);\nconst rex = new Dog();\nconsole.log(rex instanceof Dog, rex instanceof Animal);",
    "options": ["true, false", "false, true", "true, true", "false, false"],
    "correct_answer": "true, true",
    "explanation": "Because we set `Dog.prototype` to inherit from `Animal.prototype`, `rex` has both `Dog.prototype` and `Animal.prototype` in its prototype chain. Therefore, it is an instance of both."
  },
  {
    "id": 794,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Prototypal Inheritance",
    "question": "How do you manually set up inheritance so that `Dog` inherits from `Animal` in ES5?",
    "code_snippet": null,
    "options": ["Dog.inherits(Animal)", "Dog.prototype = Object.create(Animal.prototype)", "Dog extends Animal", "Object.link(Dog, Animal)"],
    "correct_answer": "Dog.prototype = Object.create(Animal.prototype)",
    "explanation": "To inherit, you must overwrite the child's `prototype` property with a new object that is linked to the parent's `prototype`. (You also need to fix the `constructor` property afterward)."
  },
  {
    "id": 795,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "Fixing the Constructor",
    "question": "After doing `Dog.prototype = Object.create(Animal.prototype)`, what line of code must you add to fix the `constructor` property?",
    "code_snippet": "Dog.prototype = Object.create(Animal.prototype);\n_______.constructor = Dog;",
    "options": ["Dog", "Dog.prototype", "Animal.prototype", "this"],
    "correct_answer": "Dog.prototype",
    "explanation": "When you overwrite `Dog.prototype`, you lose the default `.constructor` reference. You must manually restore it by setting `Dog.prototype.constructor = Dog;`."
  },
  {
    "id": 796,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Modifying Prototype Later",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function User() { this.name = 'Alice'; }\nconst u1 = new User();\nUser.prototype.age = 25;\nconst u2 = new User();\nconsole.log(u1.age, u2.age);",
    "options": ["undefined, 25", "25, 25", "undefined, undefined", "Error"],
    "correct_answer": "25, 25",
    "explanation": "Because `u1` and `u2` both hold a reference to `User.prototype` via their `__proto__` link, adding a property to the prototype AFTER creating `u1` means `u1` can still access it!"
  },
  {
    "id": 797,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Arrow Functions & Prototype",
    "question": "What happens if you try to access the `.prototype` property of an arrow function?",
    "code_snippet": null,
    "options": ["It returns an empty object", "It returns undefined", "It throws a SyntaxError", "It returns the global window"],
    "correct_answer": "It returns undefined",
    "explanation": "Arrow functions do not have a `.prototype` property because they cannot be used as constructors with the `new` keyword."
  },
  {
    "id": 798,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "this in Prototype Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function Counter() { this.count = 0; }\nCounter.prototype.increment = function() { this.count++; };\nconst c = new Counter();\nc.increment();\nc.increment();\nconsole.log(c.count);",
    "options": ["0", "1", "2", "NaN"],
    "correct_answer": "2",
    "explanation": "When `c.increment()` is called, `this` inside the prototype method correctly refers to the instance `c`. The `count` property on `c` is incremented twice, resulting in 2."
  },
  {
    "id": 799,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Property Shadowing",
    "question": "What is 'Property Shadowing' in the context of prototypes?",
    "code_snippet": null,
    "options": ["When a prototype method deletes an object property", "When an object has its own property with the same name as one on its prototype, hiding the prototype's property", "When two prototypes share the same property", "When a property is made private"],
    "correct_answer": "When an object has its own property with the same name as one on its prototype, hiding the prototype's property",
    "explanation": "If you do `obj.name = 'Bob'` and `obj`'s prototype also has a `name` property, JS stops looking at the prototype and uses the one directly on `obj`. The prototype's property is 'shadowed'."
  },
  {
    "id": 800,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Property Shadowing",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function User() {}\nUser.prototype.role = 'guest';\nconst u = new User();\nu.role = 'admin';\nconsole.log(User.prototype.role, u.role);",
    "options": ["admin, admin", "guest, guest", "guest, admin", "undefined, admin"],
    "correct_answer": "guest, admin",
    "explanation": "Assigning `u.role = 'admin'` does NOT change the prototype. It creates a new `role` property directly on the instance `u`, shadowing the prototype's `guest` value. The prototype remains unchanged."
  }
]
[
  {
    "id": 801,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "ES6 Classes",
    "question": "Under the hood, what is an ES6 `class` in JavaScript?",
    "code_snippet": null,
    "options": ["A completely new object-oriented engine", "Syntactic sugar over JavaScript's existing prototype-based inheritance", "A way to create private C++ style objects", "A special type of HTML element"],
    "correct_answer": "Syntactic sugar over JavaScript's existing prototype-based inheritance",
    "explanation": "ES6 classes do not introduce a new object-oriented model. They simply provide a much cleaner, more readable syntax for creating objects and setting up inheritance using the existing prototype chain."
  },
  {
    "id": 802,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "ES6 Classes",
    "question": "Fill in the blank to correctly define the initialization method for an ES6 class.",
    "code_snippet": "class User {\n  _______(name) {\n    this.name = name;\n  }\n}",
    "options": ["init", "constructor", "create", "new"],
    "correct_answer": "constructor",
    "explanation": "The `constructor` method is a special method that is automatically called when a new instance of the class is created with the `new` keyword. It is used to initialize properties."
  },
  {
    "id": 803,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "ES6 Classes",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "class Dog {}\nconst rex = new Dog();\nconsole.log(typeof rex);",
    "options": ["'class'", "'function'", "'object'", "'Dog'"],
    "correct_answer": "'object'",
    "explanation": "Even though we use the `class` keyword, JavaScript classes are just special functions. When instantiated with `new`, they return a standard JavaScript object. Therefore, `typeof` returns 'object'."
  },
  {
    "id": 804,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Class Hoisting",
    "question": "Can you use a class before it is declared in the code (e.g., calling `new User()` before the `class User {}` line)?",
    "code_snippet": null,
    "options": ["Yes, classes are fully hoisted like functions", "Yes, but it returns undefined", "No, class declarations are not hoisted and will throw a ReferenceError (Temporal Dead Zone)", "No, it throws a SyntaxError"],
    "correct_answer": "No, class declarations are not hoisted and will throw a ReferenceError (Temporal Dead Zone)",
    "explanation": "Unlike function declarations, class declarations behave like `let` and `const`. They are hoisted but remain in the Temporal Dead Zone until the line of declaration is reached."
  },
  {
    "id": 805,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "'this' in Classes",
    "question": "Inside a standard method of an ES6 class, what does the `this` keyword refer to?",
    "code_snippet": null,
    "options": ["The class blueprint itself", "The global window object", "The specific instance of the object that called the method", "undefined"],
    "correct_answer": "The specific instance of the object that called the method",
    "explanation": "Just like object methods, `this` inside a class method refers to the object to the left of the dot at the time the method is called (the instance)."
  },
  {
    "id": 806,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "'this' Trap in Classes",
    "question": "What will happen when this code is executed? (Classes are in strict mode by default!)",
    "code_snippet": "class Button {\n  constructor() { this.clicked = false; }\n  handleClick() { this.clicked = true; }\n}\nconst btn = new Button();\nsetTimeout(btn.handleClick, 100);",
    "options": ["It sets btn.clicked to true", "It throws a TypeError because 'this' is undefined inside the callback", "It sets window.clicked to true", "It logs undefined"],
    "correct_answer": "It throws a TypeError because 'this' is undefined inside the callback",
    "explanation": "Passing `btn.handleClick` to `setTimeout` detaches it from the `btn` instance. Because ES6 classes run in strict mode, `this` inside the callback becomes `undefined`. Trying to set `undefined.clicked = true` throws a TypeError."
  },
  {
    "id": 807,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Fixing 'this' in Classes",
    "question": "What is the modern ES6 syntax to permanently bind a class method's `this` to the instance, avoiding the callback trap?",
    "code_snippet": null,
    "options": ["Using the `static` keyword", "Defining the method as an arrow function class property (e.g., `handleClick = () => {}`)", "Using the `private` keyword", "Using `this.bind(this)` inside the method"],
    "correct_answer": "Defining the method as an arrow function class property (e.g., `handleClick = () => {}`)",
    "explanation": "By using class field syntax with an arrow function, the arrow function lexically captures the `this` of the constructor, permanently binding it to the instance regardless of how it's called."
  },
  {
    "id": 808,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "Inheritance",
    "question": "Fill in the blank to make the `Dog` class inherit from the `Animal` class.",
    "code_snippet": "class Animal {}\nclass Dog _______ Animal {\n  bark() { return 'Woof!'; }\n}",
    "options": ["inherits", "extends", "implements", "prototype"],
    "correct_answer": "extends",
    "explanation": "The `extends` keyword is used in class declarations to create a class that is a child of another class, setting up the prototype chain."
  },
  {
    "id": 809,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "The 'super' Keyword",
    "question": "What does calling `super()` inside a child class's constructor do?",
    "code_snippet": null,
    "options": ["It creates a new instance of the parent class", "It calls the parent class's constructor", "It overrides the parent class's methods", "It returns the parent class's prototype"],
    "correct_answer": "It calls the parent class's constructor",
    "explanation": "If a child class has its own constructor, it MUST call `super()` before it can use the `this` keyword. `super()` runs the parent's constructor to initialize the inherited properties."
  },
  {
    "id": 810,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "The 'super' Rule",
    "question": "What will happen when this code is executed?",
    "code_snippet": "class Animal { constructor(name) { this.name = name; } }\nclass Dog extends Animal {\n  constructor(name, breed) {\n    this.breed = breed;\n    super(name);\n  }\n}\nnew Dog('Rex', 'Lab');",
    "options": ["It creates the dog successfully", "It throws a ReferenceError: Must call super constructor in derived class before accessing 'this'", "It throws a SyntaxError", "It ignores the breed property"],
    "correct_answer": "It throws a ReferenceError: Must call super constructor in derived class before accessing 'this'",
    "explanation": "In a derived class (a class using `extends`), you cannot use the `this` keyword until AFTER you have called `super()`. The JavaScript engine enforces this rule to ensure the parent object is initialized first."
  },
  {
    "id": 811,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "Calling Parent Methods",
    "question": "Fill in the blank to call the parent class's `eat()` method from inside the child class's `eat()` method.",
    "code_snippet": "class Dog extends Animal {\n  eat() {\n    _______.eat();\n    console.log('The dog is eating.');\n  }\n}",
    "options": ["parent", "this", "super", "Animal"],
    "correct_answer": "super",
    "explanation": "While `super()` calls the parent constructor, `super.methodName()` calls a specific method from the parent class's prototype. This is useful for extending behavior rather than completely replacing it."
  },
  {
    "id": 812,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Static Methods",
    "question": "What is a `static` method in a class?",
    "code_snippet": null,
    "options": ["A method that cannot be changed", "A method that belongs to the class itself, rather than to instances of the class", "A method that runs automatically on page load", "A method that returns a static string"],
    "correct_answer": "A method that belongs to the class itself, rather than to instances of the class",
    "explanation": "Static methods are called on the class directly (e.g., `Math.random()`), not on the objects created from the class. They are typically used for utility or helper functions."
  },
  {
    "id": 813,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Static Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "class MathUtil {\n  static add(a, b) { return a + b; }\n}\nconst calc = new MathUtil();\nconsole.log(calc.add(2, 3));",
    "options": ["5", "undefined", "TypeError: calc.add is not a function", "NaN"],
    "correct_answer": "TypeError: calc.add is not a function",
    "explanation": "Because `add` is a static method, it exists ONLY on the `MathUtil` class itself (`MathUtil.add(2, 3)`). It is NOT copied to the instances. Trying to call it on `calc` results in a TypeError."
  },
  {
    "id": 814,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "code-fill-in-blank",
    "topic": "Private Fields",
    "question": "Fill in the blank to correctly declare a truly private field in an ES6 class.",
    "code_snippet": "class BankAccount {\n  _______ balance = 0;\n  deposit(amount) { this.balance += amount; }\n}",
    "options": ["private", "hidden", "#", "_"],
    "correct_answer": "#",
    "explanation": "In modern JavaScript, the `#` prefix denotes a private class field. Unlike the convention of using `_` (which is just a suggestion), `#` enforces true privacy at the engine level."
  },
  {
    "id": 815,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Private Fields",
    "question": "What will happen when this code is executed?",
    "code_snippet": "class User {\n  #secret = 'password123';\n}\nconst u = new User();\nconsole.log(u.#secret);",
    "options": ["password123", "undefined", "null", "SyntaxError"],
    "correct_answer": "SyntaxError",
    "explanation": "Private fields (`#`) cannot be accessed from outside the class body. Attempting to read or write them from the outside results in a SyntaxError at parse time, completely blocking access."
  },
  {
    "id": 816,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Getters",
    "question": "How do you define a getter in an ES6 class?",
    "code_snippet": null,
    "options": ["Using the `get` keyword before a method name", "Using the `@getter` decorator", "Using the `return` keyword inside the constructor", "Using the `Object.defineProperty()` method inside the constructor"],
    "correct_answer": "Using the `get` keyword before a method name",
    "explanation": "The `get` keyword binds an object property to a function that will be called when that property is looked up. It allows you to compute a value dynamically while using standard property access syntax."
  },
  {
    "id": 817,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Getters",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "class Circle {\n  constructor(radius) { this.radius = radius; }\n  get area() { return Math.PI * this.radius ** 2; }\n}\nconst c = new Circle(2);\nconsole.log(c.area);",
    "options": ["A function definition", "undefined", "12.566370614359172 (or similar PI calculation)", "Error: c.area is not a function"],
    "correct_answer": "12.566370614359172 (or similar PI calculation)",
    "explanation": "Because `area` is defined with the `get` keyword, you access it like a normal property (`c.area`), NOT like a method (`c.area()`). It automatically executes the function and returns the calculated value."
  },
  {
    "id": 818,
    "level": "intermediate",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Setters",
    "question": "What is the purpose of a `set` keyword in a class?",
    "code_snippet": null,
    "options": ["To make a property read-only", "To execute custom logic whenever a specific property is assigned a new value", "To set the default value of a property", "To delete a property"],
    "correct_answer": "To execute custom logic whenever a specific property is assigned a new value",
    "explanation": "A setter allows you to intercept assignments. For example, you could use a setter on a `temperature` property to automatically convert Fahrenheit to Celsius before storing it."
  },
  {
    "id": 819,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "output-prediction",
    "topic": "Setters & Validation",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "class User {\n  set age(val) {\n    if (val < 0) throw new Error('Age cannot be negative');\n    this._age = val;\n  }\n  get age() { return this._age; }\n}\nconst u = new User();\nu.age = -5;",
    "options": ["-5", "0", "undefined", "Error: Age cannot be negative"],
    "correct_answer": "Error: Age cannot be negative",
    "explanation": "When we assign `u.age = -5`, it triggers the setter. The setter checks the value, sees it is less than 0, and throws an Error. This is a great way to enforce data validation!"
  },
  {
    "id": 820,
    "level": "advanced",
    "module_id": "mod_13_oop",
    "module_name": "Object-Oriented JavaScript (OOP)",
    "type": "conceptual",
    "topic": "Class Expressions",
    "question": "Just like functions can be expressions (`const myFunc = function() {}`), can classes be expressions?",
    "code_snippet": null,
    "options": ["No, classes must always be declared with the `class` keyword at the top level", "Yes, you can assign a class to a variable (e.g., `const MyClass = class { ... }`)", "Only if they are anonymous", "Only if they don't use inheritance"],
    "correct_answer": "Yes, you can assign a class to a variable (e.g., `const MyClass = class { ... }`)",
    "explanation": "Class expressions are perfectly valid in JavaScript. They can be named or unnamed, and they are not hoisted, just like class declarations."
  }
]
