[
  {
    "id": 591,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "DOM Basics",
    "question": "What does DOM stand for in web development?",
    "code_snippet": null,
    "options": ["Document Object Model", "Data Object Management", "Digital Ordinance Map", "Document Order Method"],
    "correct_answer": "Document Object Model",
    "explanation": "The DOM (Document Object Model) is a programming interface for web documents. It represents the page as a tree of objects so that programming languages can interact with it."
  },
  {
    "id": 592,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "DOM Basics",
    "question": "In the browser, what does the global `document` object represent?",
    "code_snippet": null,
    "options": ["The browser's history tab", "The entire HTML webpage currently loaded in the window", "The server's database", "The CSS stylesheet"],
    "correct_answer": "The entire HTML webpage currently loaded in the window",
    "explanation": "The `document` object is the entry point to the web page. It is the root node of the DOM tree, representing all the HTML elements on the page."
  },
  {
    "id": 593,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Selecting Elements",
    "question": "Fill in the blank to select an HTML element by its unique ID.",
    "code_snippet": "const myElement = document._______('my-unique-id');",
    "options": ["getElementById()", "querySelector()", "getElement()", "findById()"],
    "correct_answer": "getElementById()",
    "explanation": "`getElementById()` is the oldest and fastest way to select a single element using its unique `id` attribute. You do not need to include the '#' symbol."
  },
  {
    "id": 594,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Selecting Elements",
    "question": "Fill in the blank to select the FIRST element that matches a specific CSS class.",
    "code_snippet": "const firstBtn = document._______('.btn-primary');",
    "options": ["getElementByClass()", "querySelector()", "querySelectorAll()", "findElement()"],
    "correct_answer": "querySelector()",
    "explanation": "`querySelector()` takes any valid CSS selector (like '.class', '#id', or 'div > p') and returns the VERY FIRST element that matches it."
  },
  {
    "id": 595,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Selecting Elements",
    "question": "What is the main difference between `querySelector()` and `querySelectorAll()`?",
    "code_snippet": null,
    "options": ["`querySelector` is for IDs, `querySelectorAll` is for classes", "`querySelector` returns the first match; `querySelectorAll` returns ALL matching elements as a NodeList", "`querySelectorAll` is faster", "There is no difference"],
    "correct_answer": "`querySelector` returns the first match; `querySelectorAll` returns ALL matching elements as a NodeList",
    "explanation": "`querySelector` stops searching after it finds the first match. `querySelectorAll` searches the entire document and returns a static NodeList containing every element that matched the selector."
  },
  {
    "id": 596,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Selecting Elements",
    "question": "Which method returns a live HTMLCollection of all `<p>` elements in the document?",
    "code_snippet": "const allParagraphs = document._______('p');",
    "options": ["querySelectorAll()", "getElementsByTagName()", "getElementsByClassName()", "getElements()"],
    "correct_answer": "getElementsByTagName()",
    "explanation": "`getElementsByTagName()` returns a live HTMLCollection of elements with the specified tag name. Unlike `querySelectorAll`, if you add a new `<p>` to the DOM later, this collection automatically updates!"
  },
  {
    "id": 597,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "NodeList vs Array",
    "question": "What does `querySelectorAll()` return?",
    "code_snippet": null,
    "options": ["A standard JavaScript Array", "A NodeList", "An HTMLCollection", "A single Element"],
    "correct_answer": "A NodeList",
    "explanation": "`querySelectorAll()` returns a static NodeList. While it looks like an array and has a `.length` property and `.forEach()` method, it lacks array methods like `.map()` or `.filter()` unless you convert it first."
  },
  {
    "id": 598,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "NodeList vs Array",
    "question": "How do you convert a NodeList into a true JavaScript Array so you can use methods like `.map()`?",
    "code_snippet": "const nodeList = document.querySelectorAll('.item');\nconst trueArray = Array._______(nodeList);",
    "options": ["convert()", "from()", "toArray()", "parse()"],
    "correct_answer": "from()",
    "explanation": "`Array.from(nodeList)` creates a new, true Array instance from the iterable NodeList, unlocking all standard array methods."
  },
  {
    "id": 599,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Manipulating Content",
    "question": "What is the difference between `textContent` and `innerHTML`?",
    "code_snippet": null,
    "options": ["`textContent` is for CSS, `innerHTML` is for JS", "`textContent` gets/sets only the raw text; `innerHTML` gets/sets the HTML markup and parses it", "`innerHTML` is faster", "They are exactly the same"],
    "correct_answer": "`textContent` gets/sets only the raw text; `innerHTML` gets/sets the HTML markup and parses it",
    "explanation": "If you set `innerHTML = '<b>Hello</b>'`, the browser renders bold text. If you set `textContent = '<b>Hello</b>'`, the browser literally displays the characters '<b>Hello</b>' on the screen."
  },
  {
    "id": 600,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Manipulating Content",
    "question": "Why is it considered a security risk to use `innerHTML` with user-provided input?",
    "code_snippet": null,
    "options": ["It makes the page load slower", "It can lead to Cross-Site Scripting (XSS) attacks if the user inputs malicious `<script>` tags", "It breaks the CSS layout", "It deletes the database"],
    "correct_answer": "It can lead to Cross-Site Scripting (XSS) attacks if the user inputs malicious `<script>` tags",
    "explanation": "Because `innerHTML` parses HTML, a malicious user could input `<script>alert('Hacked!')</script>`. If you render that with `innerHTML`, the script will execute. `textContent` is safe because it treats everything as plain text."
  },
  {
    "id": 601,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Manipulating Content",
    "question": "Fill in the blank to safely change the text inside a paragraph without parsing HTML.",
    "code_snippet": "const p = document.querySelector('p');\np._______ = 'This is safe text!';",
    "options": ["innerHTML", "textContent", "value", "text"],
    "correct_answer": "textContent",
    "explanation": "`textContent` is the standard, secure way to update the visible text of an element. It automatically escapes any HTML tags, preventing XSS attacks."
  },
  {
    "id": 602,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Navigating the DOM",
    "question": "Which property is used to select the direct parent element of a specific DOM node?",
    "code_snippet": "const child = document.querySelector('.child');\nconst parent = child._______;",
    "options": ["parent()", "parentNode", "parentElement", "up()"],
    "correct_answer": "parentElement",
    "explanation": "`parentElement` returns the parent as an Element node. (`parentNode` also works, but it can return other node types like the Document itself, whereas `parentElement` strictly returns an HTML element)."
  },
  {
    "id": 603,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Navigating the DOM",
    "question": "Which property returns a live HTMLCollection of an element's direct children?",
    "code_snippet": "const ul = document.querySelector('ul');\nconst items = ul._______;",
    "options": ["childNodes", "children", "items()", "descendants"],
    "correct_answer": "children",
    "explanation": "The `.children` property returns only the *element* nodes that are direct children. (`.childNodes` returns ALL nodes, including text nodes and whitespace/line breaks)."
  },
  {
    "id": 604,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Navigating the DOM",
    "question": "What is the difference between `nextSibling` and `nextElementSibling`?",
    "code_snippet": null,
    "options": ["There is no difference", "`nextSibling` includes text nodes (like whitespace/line breaks); `nextElementSibling` skips them and only returns the next HTML element", "`nextElementSibling` is deprecated", "`nextSibling` goes to the parent"],
    "correct_answer": "`nextSibling` includes text nodes (like whitespace/line breaks); `nextElementSibling` skips them and only returns the next HTML element",
    "explanation": "In the DOM, spaces and line breaks between HTML tags are actually considered 'text nodes'. `nextElementSibling` is almost always what you want, as it ignores those invisible text nodes."
  },
  {
    "id": 605,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Manipulating Attributes",
    "question": "Fill in the blank to get the value of the 'href' attribute from a link.",
    "code_snippet": "const link = document.querySelector('a');\nconst url = link._______('href');",
    "options": ["getAttribute()", "attr()", "getProperty()", "read()"],
    "correct_answer": "getAttribute()",
    "explanation": "`getAttribute(name)` returns the value of a specified attribute on the element. If the attribute doesn't exist, it returns `null`."
  },
  {
    "id": 606,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Manipulating Attributes",
    "question": "Fill in the blank to change the 'src' attribute of an image to a new URL.",
    "code_snippet": "const img = document.querySelector('img');\nimg._______('src', 'new-image.png');",
    "options": ["setAttribute()", "changeAttr()", "update()", "setAttribute()"],
    "correct_answer": "setAttribute()",
    "explanation": "`setAttribute(name, value)` sets the value of an attribute on the specified element. If the attribute already exists, the value is updated; if it does not exist, a new attribute is added."
  },
  {
    "id": 607,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Data Attributes",
    "question": "What is the purpose of `data-*` attributes in HTML (e.g., `<div data-user-id='123'>`)?",
    "code_snippet": null,
    "options": ["To style the element with CSS", "To store custom, private data on the element that can be easily accessed by JavaScript", "To make the element draggable", "To link the element to a database"],
    "correct_answer": "To store custom, private data on the element that can be easily accessed by JavaScript",
    "explanation": "`data-*` attributes allow you to store extra information directly in the HTML without using non-standard attributes or cluttering your JS with massive lookup objects."
  },
  {
    "id": 608,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Data Attributes",
    "question": "How do you access the `data-user-id` attribute using the element's `dataset` property?",
    "code_snippet": "const div = document.querySelector('div');\nconst userId = div.dataset._______;",
    "options": ["user-id", "userId", "user_id", "dataUserId"],
    "correct_answer": "userId",
    "explanation": "When accessing `data-*` attributes via the `dataset` object, hyphenated names are automatically converted to camelCase. So `data-user-id` becomes `dataset.userId`."
  },
  {
    "id": 609,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Creating Elements",
    "question": "Which method is used to create a brand new HTML element in JavaScript?",
    "code_snippet": "const newDiv = document._______('div');",
    "options": ["createElement()", "createNode()", "newElement()", "makeElement()"],
    "correct_answer": "createElement()",
    "explanation": "`document.createElement(tagName)` creates a new element in memory. Note that it is NOT automatically added to the page yet; you must append it to the DOM."
  },
  {
    "id": 610,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Appending Elements",
    "question": "Fill in the blank to add the newly created `newDiv` to the end of the `body`.",
    "code_snippet": "const newDiv = document.createElement('div');\ndocument.body._______(newDiv);",
    "options": ["addChild()", "append()", "insert()", "push()"],
    "correct_answer": "append()",
    "explanation": "The modern `.append()` method inserts a set of Node objects or string objects after the last child of the Parent node. (`.appendChild()` also works, but `.append()` is newer and can accept multiple nodes or strings)."
  }
]
[
  {
    "id": 611,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Event Listeners",
    "question": "Why is `addEventListener()` preferred over inline HTML event handlers (like `onclick=\"myFunc()\"`)?",
    "code_snippet": null,
    "options": ["It runs significantly faster", "It allows you to attach multiple event handlers to the same element and keeps HTML clean by separating structure from behavior", "It is the only way to handle keyboard events", "There is no difference"],
    "correct_answer": "It allows you to attach multiple event handlers to the same element and keeps HTML clean by separating structure from behavior",
    "explanation": "Inline handlers overwrite each other if you try to add two `onclick` attributes. `addEventListener` allows multiple listeners to coexist and follows the best practice of separating concerns."
  },
  {
    "id": 612,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Event Listeners",
    "question": "Fill in the blank to correctly attach a click event listener to a button.",
    "code_snippet": "const btn = document.querySelector('button');\nbtn._______('click', () => console.log('Clicked!'));",
    "options": ["onClick()", "addEvent()", "addEventListener()", "attachEvent()"],
    "correct_answer": "addEventListener()",
    "explanation": "`addEventListener(eventType, callback)` is the standard, modern method for attaching event handlers to DOM elements."
  },
  {
    "id": 613,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "The Event Object",
    "question": "What is the 'Event Object' (usually named `e` or `event`) that gets passed to the callback function?",
    "code_snippet": null,
    "options": ["The HTML element that was clicked", "A JavaScript object containing all the details and metadata about the event that just occurred", "The global window object", "A string containing the event name"],
    "correct_answer": "A JavaScript object containing all the details and metadata about the event that just occurred",
    "explanation": "The event object contains properties like the exact mouse coordinates (`e.clientX`), the key pressed (`e.key`), and the element that triggered the event (`e.target`)."
  },
  {
    "id": 614,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "preventDefault()",
    "question": "Fill in the blank to stop a form from reloading the page when submitted.",
    "code_snippet": "form.addEventListener('submit', (e) => {\n  e._______();\n  console.log('Form handled via JS');\n});",
    "options": ["stop()", "preventDefault()", "cancel()", "halt()"],
    "correct_answer": "preventDefault()",
    "explanation": "`e.preventDefault()` stops the browser's default behavior for that event. For a form submit, it prevents the page reload. For a link click, it prevents navigating to the `href`."
  },
  {
    "id": 615,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "e.target vs e.currentTarget",
    "question": "What is the difference between `e.target` and `e.currentTarget`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`e.target` is the element that actually triggered the event; `e.currentTarget` is the element the event listener is attached to", "`e.currentTarget` is the child, `e.target` is the parent", "`e.target` is deprecated"],
    "correct_answer": "`e.target` is the element that actually triggered the event; `e.currentTarget` is the element the event listener is attached to",
    "explanation": "If you click a `<span>` inside a `<button>`, and the listener is on the `<button>`, `e.target` is the `<span>` (what you actually clicked), but `e.currentTarget` is the `<button>` (where the listener lives)."
  },
  {
    "id": 616,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "output-prediction",
    "topic": "e.target vs e.currentTarget",
    "question": "What will be the exact output when the user clicks the inner `<span>`?",
    "code_snippet": "<button id=\"btn\"><span id=\"txt\">Click Me</span></button>\n\n<script>\n  document.getElementById('btn').addEventListener('click', (e) => {\n    console.log(e.target.id, e.currentTarget.id);\n  });\n</script>",
    "options": ["btn btn", "txt btn", "btn txt", "txt txt"],
    "correct_answer": "txt btn",
    "explanation": "The user physically clicked the `<span>` (`e.target.id` is 'txt'). However, the event listener is attached to the `<button>` (`e.currentTarget.id` is 'btn')."
  },
  {
    "id": 617,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Keyboard Events",
    "question": "Which event fires continuously as long as a key is held down?",
    "code_snippet": "document.addEventListener('_______', (e) => console.log(e.key));",
    "options": ["keypress", "keydown", "keyup", "keyhold"],
    "correct_answer": "keydown",
    "explanation": "`keydown` fires when the key is first pressed and continues to fire repeatedly if held. `keyup` only fires once when the key is released. (`keypress` is deprecated)."
  },
  {
    "id": 618,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Event Bubbling",
    "question": "What is 'Event Bubbling' in the DOM?",
    "code_snippet": null,
    "options": ["When an event is triggered multiple times by mistake", "The process where an event triggered on a child element propagates up to its parent, then grandparent, all the way to the root", "When an event is captured on the way down to the target", "When an event loops infinitely"],
    "correct_answer": "The process where an event triggered on a child element propagates up to its parent, then grandparent, all the way to the root",
    "explanation": "If you click a `<td>` inside a `<tr>` inside a `<table>`, the click event 'bubbles' up. The `<td>` handles it, then the `<tr>`, then the `<table>`, then the `<body>`, etc."
  },
  {
    "id": 619,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Event Delegation",
    "question": "What is 'Event Delegation' and why is it useful?",
    "code_snippet": null,
    "options": ["Deleting old event listeners to save memory", "Attaching a single event listener to a parent element to handle events for its children, leveraging event bubbling", "Passing events to a web worker", "Preventing events from bubbling"],
    "correct_answer": "Attaching a single event listener to a parent element to handle events for its children, leveraging event bubbling",
    "explanation": "Instead of adding 100 listeners to 100 list items, you add 1 listener to the `<ul>`. It's highly performant and automatically works for new items added dynamically later!"
  },
  {
    "id": 620,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "output-prediction",
    "topic": "Event Bubbling",
    "question": "What will be the exact output when the user clicks the inner div?",
    "code_snippet": "<div id=\"outer\">\n  <div id=\"inner\">Click Me</div>\n</div>\n\n<script>\n  outer.addEventListener('click', () => console.log('Outer'));\n  inner.addEventListener('click', () => console.log('Inner'));\n</script>",
    "options": ["Outer, Inner", "Inner, Outer", "Inner", "Outer"],
    "correct_answer": "Inner, Outer",
    "explanation": "Because of bubbling, the event starts at the target (`inner`) and bubbles up to the parent (`outer`). Therefore, 'Inner' logs first, then 'Outer'."
  },
  {
    "id": 621,
    "level": "advanced",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Event Capturing",
    "question": "By default, listeners fire during the bubbling phase. How do you tell `addEventListener` to fire during the capturing phase instead?",
    "code_snippet": "element.addEventListener('click', handler, _______);",
    "options": ["false", "true", "capture", "up"],
    "correct_answer": "true",
    "explanation": "The third argument of `addEventListener` is a boolean. `false` (default) means bubbling phase. `true` means capturing phase (the event travels top-down from the root to the target before bubbling back up)."
  },
  {
    "id": 622,
    "level": "advanced",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Capturing vs Bubbling",
    "question": "If an event listener is set to capture on the parent, and bubble on the child, what is the exact order of execution when the child is clicked?",
    "code_snippet": null,
    "options": ["Child bubbles, then Parent captures", "Parent captures (top-down), then Child bubbles (bottom-up)", "They fire at the exact same time", "Only the child fires"],
    "correct_answer": "Parent captures (top-down), then Child bubbles (bottom-up)",
    "explanation": "The event lifecycle is always: 1. Capturing Phase (Root -> Target), 2. Target Phase, 3. Bubbling Phase (Target -> Root). So the parent's capture listener fires first, then the child's target listener."
  },
  {
    "id": 623,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "stopPropagation()",
    "question": "Fill in the blank to prevent the click event from bubbling up to parent elements.",
    "code_snippet": "innerDiv.addEventListener('click', (e) => {\n  console.log('Inner clicked');\n  e._______();\n});",
    "options": ["preventDefault()", "stopPropagation()", "cancelBubble()", "halt()"],
    "correct_answer": "stopPropagation()",
    "explanation": "`e.stopPropagation()` stops the event from traveling any further up (or down) the DOM tree. Parent elements will not receive the event."
  },
  {
    "id": 624,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "preventDefault vs stopPropagation",
    "question": "What is the fundamental difference between `preventDefault()` and `stopPropagation()`?",
    "code_snippet": null,
    "options": ["They do the exact same thing", "`preventDefault` stops the browser's native action (like form submit); `stopPropagation` stops the event from traveling through the DOM tree", "`stopPropagation` is for forms, `preventDefault` is for clicks", "`preventDefault` is deprecated"],
    "correct_answer": "`preventDefault` stops the browser's native action (like form submit); `stopPropagation` stops the event from traveling through the DOM tree",
    "explanation": "Use `preventDefault` when you want to handle a form submit via AJAX instead of reloading. Use `stopPropagation` when you don't want a parent container's click handler to trigger when a child button is clicked."
  },
  {
    "id": 625,
    "level": "advanced",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "removeEventListener",
    "question": "Why does `element.removeEventListener('click', () => console.log('Hi'))` fail to remove the event listener?",
    "code_snippet": null,
    "options": ["You cannot remove event listeners in JS", "Because arrow functions are too fast", "Because the anonymous function passed to removeEventListener is a completely different function in memory than the one passed to addEventListener", "It only works if you pass `true` as the third argument"],
    "correct_answer": "Because the anonymous function passed to removeEventListener is a completely different function in memory than the one passed to addEventListener",
    "explanation": "To remove a listener, you must pass the EXACT same function reference. You must save the callback to a named variable first: `const handler = () => ...` and then use `removeEventListener('click', handler)`."
  },
  {
    "id": 626,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "removeEventListener",
    "question": "Fill in the blank to correctly remove the event listener.",
    "code_snippet": "function handleClick() { console.log('Clicked'); }\nbtn.addEventListener('click', handleClick);\n\n// Later in the code:\nbtn.removeEventListener('click', _______);",
    "options": ["handleClick()", "handleClick", "click", "null"],
    "correct_answer": "handleClick",
    "explanation": "You must pass the function reference (`handleClick`), NOT the executed function (`handleClick()`). Passing the executed function would pass `undefined` to the remover."
  },
  {
    "id": 627,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Mouse Events",
    "question": "What is the difference between `mouseover` and `mouseenter`?",
    "code_snippet": null,
    "options": ["There is no difference", "`mouseover` bubbles and fires when entering child elements; `mouseenter` does not bubble and only fires once when entering the parent element itself", "`mouseenter` is for touch screens", "`mouseover` is deprecated"],
    "correct_answer": "`mouseover` bubbles and fires when entering child elements; `mouseenter` does not bubble and only fires once when entering the parent element itself",
    "explanation": "If a `<div>` contains a `<span>`, moving your mouse from the `<div>` into the `<span>` triggers `mouseover` again. `mouseenter` ignores the children and only triggers when crossing the boundary of the actual element."
  },
  {
    "id": 628,
    "level": "beginner",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "code-fill-in-blank",
    "topic": "Form Events",
    "question": "Which event should you listen for to handle a form submission in JavaScript?",
    "code_snippet": "const form = document.querySelector('form');\nform.addEventListener('_______', handleSubmit);",
    "options": ["click", "submit", "change", "input"],
    "correct_answer": "submit",
    "explanation": "The `submit` event fires on the `<form>` element itself when the user submits it (e.g., by clicking a submit button or pressing Enter in an input field)."
  },
  {
    "id": 629,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Event Object Properties",
    "question": "In a keyboard event, what is the difference between `e.key` and `e.code`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`e.key` represents the character generated (e.g., 'A' or 'a' depending on Shift); `e.code` represents the physical key on the keyboard (e.g., 'KeyA')", "`e.code` is deprecated", "`e.key` is for numbers, `e.code` is for letters"],
    "correct_answer": "`e.key` represents the character generated (e.g., 'A' or 'a' depending on Shift); `e.code` represents the physical key on the keyboard (e.g., 'KeyA')",
    "explanation": "If you press Shift+A, `e.key` is 'A' and `e.code` is 'KeyA'. If you are building a game where WASD controls movement regardless of caps lock, you should use `e.code`."
  },
  {
    "id": 630,
    "level": "intermediate",
    "module_id": "mod_10_dom",
    "module_name": "The DOM (Document Object Model)",
    "type": "conceptual",
    "topic": "Event Delegation",
    "question": "Why is Event Delegation the ONLY way to handle clicks on list items that are added to the DOM dynamically AFTER the page loads?",
    "code_snippet": null,
    "options": ["Because dynamic elements don't support click events", "Because the dynamic elements don't exist yet when the initial JS runs, so you can't attach listeners directly to them; but the parent already exists and will catch their bubbled events", "Because dynamic elements are too slow", "It's not the only way, it's just a preference"],
    "correct_answer": "Because the dynamic elements don't exist yet when the initial JS runs, so you can't attach listeners directly to them; but the parent already exists and will catch their bubbled events",
    "explanation": "If you use `document.querySelectorAll('.item')` on page load, it only finds the items that exist at that exact millisecond. Event delegation on the parent `<ul>` solves this permanently."
  }
]
