[
  {
    "id": 491,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object Basics",
    "question": "What is an Object in JavaScript?",
    "code_snippet": null,
    "options": ["A single primitive value like a number or string", "A collection of related data and/or functionality stored in key-value pairs", "A loop that iterates through arrays", "A special type of HTML element"],
    "correct_answer": "A collection of related data and/or functionality stored in key-value pairs",
    "explanation": "Objects are the fundamental non-primitive data type in JS. They allow you to group related data (properties) and functions (methods) together into a single, organized structure."
  },
  {
    "id": 492,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Object Basics",
    "question": "Which syntax is used to create a new, empty object literal?",
    "code_snippet": "let myObject = _______;",
    "options": ["[]", "()", "{}", "<>"],
    "correct_answer": "{}",
    "explanation": "Curly braces `{}` are used to create object literals. Square brackets `[]` are for arrays, and parentheses `()` are for functions or grouping expressions."
  },
  {
    "id": 493,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Dot Notation",
    "question": "Fill in the blank to access the 'name' property of the 'user' object using dot notation.",
    "code_snippet": "let user = { name: 'Alice', age: 25 };\nconsole.log(user._______);",
    "options": ["name", "\"name\"", "[name]", "(name)"],
    "correct_answer": "name",
    "explanation": "Dot notation is the most common way to access object properties. You simply write the object name, a dot, and the exact property name (without quotes)."
  },
  {
    "id": 494,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Bracket Notation",
    "question": "Fill in the blank to access the 'age' property using bracket notation.",
    "code_snippet": "let user = { name: 'Alice', age: 25 };\nconsole.log(user[_______]);",
    "options": ["age", "'age'", "age()", ".age"],
    "correct_answer": "'age'",
    "explanation": "When using bracket notation, the property name must be provided as a string (wrapped in quotes). So, `user['age']` is the correct syntax."
  },
  {
    "id": 495,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Dot vs Bracket Notation",
    "question": "When MUST you use bracket notation instead of dot notation?",
    "code_snippet": null,
    "options": ["When the property value is a number", "When the property key contains spaces, special characters, or is stored in a variable", "When the object is declared with `const`", "You never have to use bracket notation"],
    "correct_answer": "When the property key contains spaces, special characters, or is stored in a variable",
    "explanation": "Dot notation only works for valid JS identifiers (no spaces, can't start with a number). If your key is `'first-name'` or `'my property'`, or if you need to dynamically access a key using a variable, you MUST use bracket notation."
  },
  {
    "id": 496,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Bracket Notation Variables",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let user = { name: 'Alice', age: 25 };\nlet key = 'age';\nconsole.log(user[key]);",
    "options": ["age", "25", "undefined", "Error"],
    "correct_answer": "25",
    "explanation": "When you put a variable inside the brackets, JavaScript evaluates the variable first. `key` holds the string `'age'`, so it effectively evaluates `user['age']`, which returns 25."
  },
  {
    "id": 497,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Adding Properties",
    "question": "Fill in the blank to add a new 'email' property to the existing 'user' object.",
    "code_snippet": "let user = { name: 'Alice' };\nuser._______ = 'alice@example.com';",
    "options": ["add", "push", "email", "new"],
    "correct_answer": "email",
    "explanation": "In JavaScript, objects are dynamic. You can add new properties at any time simply by assigning a value to a new property name using dot or bracket notation."
  },
  {
    "id": 498,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Updating Properties",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let car = { brand: 'Toyota', year: 2020 };\ncar.year = 2023;\nconsole.log(car.year);",
    "options": ["2020", "2023", "undefined", "Error"],
    "correct_answer": "2023",
    "explanation": "If you assign a value to an existing property using the assignment operator (`=`), it overwrites the old value. The year is updated from 2020 to 2023."
  },
  {
    "id": 499,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Deleting Properties",
    "question": "Which keyword is used to completely remove a property from an object?",
    "code_snippet": "let user = { name: 'Alice', age: 25 };\n_______ user.age;",
    "options": ["remove", "delete", "drop", "clear"],
    "correct_answer": "delete",
    "explanation": "The `delete` operator removes a property from an object. Subsequent attempts to access that property will return `undefined`."
  },
  {
    "id": 500,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Deleting Properties",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let obj = { a: 1, b: 2 };\ndelete obj.a;\nconsole.log(obj.a);",
    "options": ["1", "null", "undefined", "Error"],
    "correct_answer": "undefined",
    "explanation": "The `delete` operator removes the property `a` from the object. When you try to access a property that doesn't exist, JavaScript returns `undefined`."
  },
  {
    "id": 501,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Checking Properties",
    "question": "Which operator checks if a specific property exists in an object (or its prototype chain) and returns a boolean?",
    "code_snippet": null,
    "options": ["exists", "has", "in", "contains"],
    "correct_answer": "in",
    "explanation": "The `in` operator is used like this: `'name' in user`. It returns `true` if the property exists, and `false` if it doesn't."
  },
  {
    "id": 502,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Checking Properties",
    "question": "Fill in the blank to check if the 'email' property exists directly on the 'user' object (ignoring the prototype chain).",
    "code_snippet": "let user = { name: 'Alice' };\nlet hasEmail = user._______('email');",
    "options": ["has()", "exists()", "hasOwnProperty()", "includes()"],
    "correct_answer": "hasOwnProperty()",
    "explanation": "`hasOwnProperty()` is a built-in method that returns `true` only if the property is a direct property of the object itself, not inherited from its prototype chain."
  },
  {
    "id": 503,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object.keys()",
    "question": "What does the `Object.keys()` method return?",
    "code_snippet": null,
    "options": ["An array of the object's values", "An array of the object's own enumerable property names (keys)", "A single string of all keys", "The total number of properties"],
    "correct_answer": "An array of the object's own enumerable property names (keys)",
    "explanation": "`Object.keys(obj)` extracts all the keys from the object and returns them as a standard JavaScript Array of strings."
  },
  {
    "id": 504,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object.values()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let scores = { math: 90, science: 85 };\nconsole.log(Object.values(scores));",
    "options": ["['math', 'science']", "[90, 85]", "[['math', 90], ['science', 85]]", "undefined"],
    "correct_answer": "[90, 85]",
    "explanation": "`Object.values()` extracts all the values from the object and returns them as an array, in the same order as the keys."
  },
  {
    "id": 505,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Object.entries()",
    "question": "Fill in the blank to get an array of arrays, where each inner array contains a [key, value] pair.",
    "code_snippet": "let data = { a: 1, b: 2 };\nlet entries = Object._______(data);",
    "options": ["keys", "values", "entries", "pairs"],
    "correct_answer": "entries",
    "explanation": "`Object.entries()` returns an array of `[key, value]` arrays. For this example, it returns `[['a', 1], ['b', 2]]`. This is incredibly useful for looping through objects with `for...of`."
  },
  {
    "id": 506,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object Keys",
    "question": "What data type are object keys (property names) in JavaScript?",
    "code_snippet": null,
    "options": ["They can be any data type (numbers, booleans, objects)", "They are always converted to Strings (or Symbols)", "They are always Numbers", "They are always Booleans"],
    "correct_answer": "They are always converted to Strings (or Symbols)",
    "explanation": "Even if you use a number or a boolean as a key (e.g., `obj[1] = 'a'`), JavaScript automatically converts it to a string (`'1'`). The only exceptions are Symbols, which remain Symbols."
  },
  {
    "id": 507,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object Keys Coercion",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let obj = {};\nobj[1] = 'one';\nobj['1'] = 'ONE';\nconsole.log(obj[1]);",
    "options": ["'one'", "'ONE'", "undefined", "Error"],
    "correct_answer": "'ONE'",
    "explanation": "Because object keys are coerced to strings, `obj[1]` and `obj['1']` are actually the exact same property! The second assignment overwrites the first, so the value is 'ONE'."
  },
  {
    "id": 508,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Accessing Missing Properties",
    "question": "What happens if you try to access a property that does not exist on an object using dot notation?",
    "code_snippet": "let user = { name: 'Alice' };\nconsole.log(user._______);",
    "options": ["email", "age", "address", "All of the above will return undefined"],
    "correct_answer": "All of the above will return undefined",
    "explanation": "If you try to access any property that hasn't been defined on the object, JavaScript does not throw an error; it simply returns `undefined`."
  },
  {
    "id": 509,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object Property Order",
    "question": "In modern JavaScript, what is the iteration order of object properties when using `Object.keys()` or `for...in`?",
    "code_snippet": null,
    "options": ["They are always sorted alphabetically", "Integer-like keys are sorted numerically first, then string keys in insertion order", "They are in completely random order", "They are sorted by the length of the key name"],
    "correct_answer": "Integer-like keys are sorted numerically first, then string keys in insertion order",
    "explanation": "This is a crucial JS quirk! If you have keys like `'2'`, `'1'`, `'name'`, the engine will output `'1'`, `'2'`, then `'name'`. Integer-like strings are always sorted to the front numerically."
  },
  {
    "id": 510,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object Property Order",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let obj = { c: 3, a: 1, '2': 'two', b: 2, '1': 'one' };\nconsole.log(Object.keys(obj));",
    "options": ["['c', 'a', '2', 'b', '1']", "['1', '2', 'c', 'a', 'b']", "['a', 'b', 'c', '1', '2']", "['2', '1', 'c', 'a', 'b']"],
    "correct_answer": "['1', '2', 'c', 'a', 'b']",
    "explanation": "As mentioned, integer-like keys (`'1'` and `'2'`) are automatically sorted to the front in numerical order. The rest of the string keys (`c`, `a`, `b`) follow in the exact order they were inserted."
  }
]
[
  {
    "id": 511,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object Methods",
    "question": "What is a 'method' in the context of a JavaScript object?",
    "code_snippet": null,
    "options": ["A primitive value stored in the object", "A property that holds a function", "A loop that iterates through the object", "An array stored inside the object"],
    "correct_answer": "A property that holds a function",
    "explanation": "When a function is stored as a property of an object, it is called a 'method'. Methods are used to perform actions or calculations related to that specific object."
  },
  {
    "id": 512,
    "level": "beginner",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Object Methods",
    "question": "Fill in the blank to correctly define a method inside an object literal.",
    "code_snippet": "const user = {\n  name: 'Alice',\n  greet: _______ {\n    console.log('Hi');\n  }\n};",
    "options": ["function()", "def", "method", "func"],
    "correct_answer": "function()",
    "explanation": "To define a method, you assign a function to a property name. The standard syntax is `methodName: function() { ... }`."
  },
  {
    "id": 513,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "The 'this' keyword",
    "question": "What does the `this` keyword refer to when used inside a standard object method?",
    "code_snippet": null,
    "options": ["The global window object", "The function itself", "The object that is calling the method (the object to the left of the dot)", "It is always undefined"],
    "correct_answer": "The object that is calling the method (the object to the left of the dot)",
    "explanation": "In a regular function method, `this` is determined by *how* the function is called. If it's called via an object (like `obj.method()`), `this` refers to that specific object."
  },
  {
    "id": 514,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "The 'this' keyword",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const calculator = {\n  num: 10,\n  double: function() { return this.num * 2; }\n};\nconsole.log(calculator.double());",
    "options": ["10", "20", "undefined", "Error"],
    "correct_answer": "20",
    "explanation": "Inside the `double` method, `this` refers to the `calculator` object. Therefore, `this.num` is 10, and 10 * 2 equals 20."
  },
  {
    "id": 515,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "The 'this' trap",
    "question": "What will be the exact output of the following code? (Watch out for lost context!)",
    "code_snippet": "const user = { name: 'Bob', getName: function() { return this.name; } };\nconst extract = user.getName;\nconsole.log(extract());",
    "options": ["Bob", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "When you assign `user.getName` to a variable without calling it, it loses its connection to the `user` object. When `extract()` is called, it's called as a standalone function, so `this` defaults to the global object (where `this.name` is undefined)."
  },
  {
    "id": 516,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Arrow Functions as Methods",
    "question": "What happens if you use an arrow function as an object method and try to access `this`?",
    "code_snippet": null,
    "options": ["It refers to the object", "It refers to the global object", "It inherits `this` from the surrounding lexical scope, NOT the object itself", "It throws a SyntaxError"],
    "correct_answer": "It inherits `this` from the surrounding lexical scope, NOT the object itself",
    "explanation": "Arrow functions do not have their own `this` context. If used as an object method, `this` will NOT point to the object, but to whatever scope the object was defined in (often the global scope)."
  },
  {
    "id": 517,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Arrow Functions as Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = {\n  name: 'Alice',\n  greet: () => {\n    console.log(this.name);\n  }\n};\nuser.greet();",
    "options": ["Alice", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "Because `greet` is an arrow function, `this` does not refer to the `user` object. It inherits `this` from the outer scope (the global scope), where `this.name` does not exist, resulting in `undefined`."
  },
  {
    "id": 518,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Property Shorthand",
    "question": "What does 'Property Shorthand' mean in ES6 object literals?",
    "code_snippet": null,
    "options": ["Using dots instead of brackets", "If the property key and the variable name are the same, you can omit the colon and value (e.g., `{ name }` instead of `{ name: name }`)", "Automatically converting all values to strings", "Using the `this` keyword to assign values"],
    "correct_answer": "If the property key and the variable name are the same, you can omit the colon and value (e.g., `{ name }` instead of `{ name: name }`)",
    "explanation": "Property shorthand saves typing. If you have `let age = 25;`, you can just write `const user = { age };` and JavaScript understands it means `{ age: age }`."
  },
  {
    "id": 519,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Method Shorthand",
    "question": "Fill in the blank to correctly use ES6 method shorthand syntax.",
    "code_snippet": "const obj = {\n  value: 10,\n  getValue_______ {\n    return this.value;\n  }\n};",
    "options": ["() ", " = function() ", " => ", " : function() "],
    "correct_answer": "() ",
    "explanation": "ES6 introduced method shorthand. Instead of writing `getValue: function() { ... }`, you can simply write `getValue() { ... }`."
  },
  {
    "id": 520,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Computed Properties",
    "question": "Fill in the blank to use a variable as the property key (Computed Property Names).",
    "code_snippet": "const key = 'color';\nconst obj = {\n  [_______]: 'blue'\n};",
    "options": ["key", "'key'", "color", "[key]"],
    "correct_answer": "key",
    "explanation": "By wrapping a variable or expression in square brackets `[]` inside an object literal, JavaScript evaluates it and uses the result as the property key. Here, it creates a property named `'color'`."
  },
  {
    "id": 521,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Computed Properties",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const prefix = 'user';\nconst obj = {\n  [`${prefix}Name`]: 'Alice',\n  [`${prefix}Age`]: 25\n};\nconsole.log(obj.userName);",
    "options": ["Alice", "undefined", "Error", "userName"],
    "correct_answer": "Alice",
    "explanation": "The template literals evaluate to `'userName'` and `'userAge'`. These become the actual property keys. Therefore, `obj.userName` correctly returns 'Alice'."
  },
  {
    "id": 522,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Shallow Copy",
    "question": "What is a 'shallow copy' of an object?",
    "code_snippet": null,
    "options": ["A copy that duplicates all nested objects as well", "A copy that duplicates the top-level properties, but nested objects are still passed by reference", "A copy that freezes the object", "A copy that only copies the methods"],
    "correct_answer": "A copy that duplicates the top-level properties, but nested objects are still passed by reference",
    "explanation": "A shallow copy creates a new object and copies the top-level values. However, if a value is another object (nested), it only copies the *reference* to that nested object, not the object itself."
  },
  {
    "id": 523,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Spread Operator Copy",
    "question": "Fill in the blank to create a shallow copy of an object using the Spread operator.",
    "code_snippet": "const original = { a: 1, b: 2 };\nconst copy = { _______original };",
    "options": ["...", "**", "@", "&"],
    "correct_answer": "...",
    "explanation": "The spread operator `...` unpacks the properties of the `original` object into a brand new object literal `{}`, creating a shallow copy."
  },
  {
    "id": 524,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Shallow Copy Trap",
    "question": "What will be the exact output of the following code? (Watch out for nested objects!)",
    "code_snippet": "const original = { a: 1, nested: { b: 2 } };\nconst copy = { ...original };\ncopy.nested.b = 99;\nconsole.log(original.nested.b);",
    "options": ["2", "99", "undefined", "Error"],
    "correct_answer": "99",
    "explanation": "Because the spread operator only does a shallow copy, `copy.nested` and `original.nested` point to the exact same object in memory. Modifying the nested object in the copy also modifies it in the original!"
  },
  {
    "id": 525,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Object.assign()",
    "question": "Which method is used to copy the values of all enumerable own properties from one or more source objects to a target object?",
    "code_snippet": "const target = { a: 1 };\nconst source = { b: 2 };\nObject._______(target, source);",
    "options": ["merge", "assign", "combine", "concat"],
    "correct_answer": "assign",
    "explanation": "`Object.assign(target, source)` copies properties from the source to the target. It mutates the target object and returns it. It's often used for merging objects or creating shallow copies."
  },
  {
    "id": 526,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object.freeze()",
    "question": "What does `Object.freeze(obj)` do?",
    "code_snippet": null,
    "options": ["Deletes all properties", "Prevents new properties from being added, existing properties from being removed, and prevents changing the values of existing properties", "Converts the object to a string", "Makes the object immutable, including all deeply nested objects"],
    "correct_answer": "Prevents new properties from being added, existing properties from being removed, and prevents changing the values of existing properties",
    "explanation": "`Object.freeze()` makes an object 'immutable' at the top level. Note that it does NOT freeze nested objects deeply; you would need a custom deep-freeze function for that."
  },
  {
    "id": 527,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object.freeze()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = Object.freeze({ name: 'Alice', age: 25 });\nuser.age = 26;\nconsole.log(user.age);",
    "options": ["25", "26", "undefined", "Error"],
    "correct_answer": "25",
    "explanation": "Because the object is frozen, the assignment `user.age = 26` silently fails (or throws a TypeError in strict mode). The original value remains 25."
  },
  {
    "id": 528,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Pass by Reference",
    "question": "When you pass an object to a function as an argument, how is it passed?",
    "code_snippet": null,
    "options": ["By value (a completely independent copy is made)", "By reference (the function receives a reference to the original object in memory)", "By string conversion", "It is not allowed"],
    "correct_answer": "By reference (the function receives a reference to the original object in memory)",
    "explanation": "Objects are passed by reference. If the function modifies a property of the object, that change will be reflected in the original object outside the function."
  },
  {
    "id": 529,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Checking Empty Objects",
    "question": "How do you reliably check if an object is completely empty (has no own enumerable properties)?",
    "code_snippet": "const obj = {};\nconst isEmpty = _______ === 0;",
    "options": ["obj.length", "Object.keys(obj).length", "obj.isEmpty()", "obj === {}"],
    "correct_answer": "Object.keys(obj).length",
    "explanation": "Objects don't have a `.length` property. The standard way to check if an object is empty is to get its keys array and check if the length of that array is 0."
  },
  {
    "id": 530,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Pass by Reference",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function updateAge(person) {\n  person.age = 30;\n}\nconst myObj = { name: 'Bob', age: 25 };\nupdateAge(myObj);\nconsole.log(myObj.age);",
    "options": ["25", "30", "undefined", "Error"],
    "correct_answer": "30",
    "explanation": "Because objects are passed by reference, the `person` parameter inside the function points to the exact same object as `myObj`. Modifying `person.age` modifies `myObj.age`."
  }
]
[
  {
    "id": 531,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Getters and Setters",
    "question": "What is the purpose of a 'getter' in a JavaScript object?",
    "code_snippet": null,
    "options": ["To delete a property", "To define a method that gets executed when you try to access a specific property", "To set a property to null", "To loop through the object"],
    "correct_answer": "To define a method that gets executed when you try to access a specific property",
    "explanation": "Getters allow you to define a function that runs dynamically when a property is accessed using dot or bracket notation, making it look like a normal property access."
  },
  {
    "id": 532,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Getters and Setters",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = {\n  firstName: 'John',\n  lastName: 'Doe',\n  get fullName() {\n    return `${this.firstName} ${this.lastName}`;\n  }\n};\nconsole.log(user.fullName);",
    "options": ["function() { ... }", "John Doe", "undefined", "Error"],
    "correct_answer": "John Doe",
    "explanation": "Because `fullName` is defined with the `get` keyword, you access it like a normal property (without parentheses). It executes the function and returns the concatenated string."
  },
  {
    "id": 533,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Getters and Setters",
    "question": "Fill in the blank to correctly define a setter that updates the 'fullName' property.",
    "code_snippet": "const user = {\n  firstName: '',\n  lastName: '',\n  _______ fullName(value) {\n    const parts = value.split(' ');\n    this.firstName = parts[0];\n    this.lastName = parts[1];\n  }\n};",
    "options": ["get", "set", "put", "assign"],
    "correct_answer": "set",
    "explanation": "The `set` keyword binds an object property to a function that will be called whenever there is an attempt to assign a value to that property."
  },
  {
    "id": 534,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Object Destructuring",
    "question": "Fill in the blank to correctly extract the 'name' and 'age' properties into variables.",
    "code_snippet": "const user = { name: 'Alice', age: 25, role: 'admin' };\nconst { _______ } = user;",
    "options": ["name, age", "user.name, user.age", "name: user, age: user", "[name, age]"],
    "correct_answer": "name, age",
    "explanation": "Object destructuring uses curly braces `{}` and matches the property names to create variables with the exact same names and values."
  },
  {
    "id": 535,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object Destructuring",
    "question": "What will be the exact output of the following code? (Notice the renaming syntax!)",
    "code_snippet": "const obj = { x: 10, y: 20 };\nconst { x: first, y: second } = obj;\nconsole.log(first);",
    "options": ["x", "10", "undefined", "Error"],
    "correct_answer": "10",
    "explanation": "In destructuring, `x: first` means 'take the property `x` and assign its value to a new variable named `first`'. Therefore, `first` holds the value 10."
  },
  {
    "id": 536,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object Destructuring",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = { name: 'Bob' };\nconst { name, age = 18 } = user;\nconsole.log(age);",
    "options": ["undefined", "null", "18", "Error"],
    "correct_answer": "18",
    "explanation": "You can assign default values during destructuring. Since the `user` object does not have an `age` property (it evaluates to undefined), the default value of 18 is used."
  },
  {
    "id": 537,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Nested Destructuring",
    "question": "Fill in the blank to correctly extract the 'city' property from the nested 'address' object.",
    "code_snippet": "const user = { name: 'Eve', address: { city: 'NY', zip: '10001' } };\nconst { address: { _______ } } = user;\nconsole.log(city); // 'NY'",
    "options": ["city", "address.city", "user.address.city", "{city}"],
    "correct_answer": "city",
    "explanation": "To destructure nested objects, you mirror the object's structure. You open the `address` property and then destructure the `city` property inside it."
  },
  {
    "id": 538,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Optional Chaining",
    "question": "Fill in the blank to safely access the 'street' property without throwing an error if 'address' is null.",
    "code_snippet": "const user = { name: 'Eve', address: null };\nconst street = user.address_______.street;",
    "options": ["??", "?.", "||", "&&"],
    "correct_answer": "?.",
    "explanation": "The Optional Chaining operator (`?.`) stops evaluation and returns `undefined` if the value before it is null or undefined, preventing TypeErrors."
  },
  {
    "id": 539,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Optional Chaining",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = {};\nconsole.log(user.getAddress?.());",
    "options": ["undefined", "null", "Error: user.getAddress is not a function", "0"],
    "correct_answer": "undefined",
    "explanation": "Because `getAddress` does not exist on the `user` object, it is `undefined`. The optional chaining operator `?.()` detects this and short-circuits, returning `undefined` instead of throwing a TypeError."
  },
  {
    "id": 540,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object Comparison",
    "question": "Why does `{} === {}` evaluate to `false` in JavaScript?",
    "code_snippet": null,
    "options": ["Because they have different properties", "Because objects are compared by reference (memory address), not by their contents", "Because the strict equality operator doesn't work on objects", "Because they are created at different times"],
    "correct_answer": "Because objects are compared by reference (memory address), not by their contents",
    "explanation": "Every time you create an object literal `{}`, JavaScript allocates a brand new space in memory. Even if two objects have the exact same contents, they point to different memory addresses, so they are not strictly equal."
  },
  {
    "id": 541,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Object Comparison",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const a = { x: 1 };\nconst b = { x: 1 };\nconst c = a;\nconsole.log(a === b, a === c);",
    "options": ["true, true", "false, false", "false, true", "true, false"],
    "correct_answer": "false, true",
    "explanation": "`a` and `b` are two different objects in memory (false). `c` is just a reference pointing to the exact same memory address as `a` (true)."
  },
  {
    "id": 542,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "JSON.stringify()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = { a: 1, b: undefined, c: () => {}, d: 2 };\nconsole.log(JSON.stringify(obj));",
    "options": ["{\"a\":1,\"b\":null,\"c\":null,\"d\":2}", "{\"a\":1,\"d\":2}", "{\"a\":1,\"b\":undefined,\"c\":function,\"d\":2}", "Error"],
    "correct_answer": "{\"a\":1,\"d\":2}",
    "explanation": "When `JSON.stringify()` encounters `undefined`, a function, or a Symbol as an object property value, it completely omits that key-value pair from the resulting JSON string."
  },
  {
    "id": 543,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "JSON.parse()",
    "question": "Fill in the blank to correctly convert a JSON string back into a JavaScript object.",
    "code_snippet": "const jsonString = '{\"name\":\"Alice\",\"age\":25}';\nconst userObj = JSON._______(jsonString);",
    "options": ["stringify()", "parse()", "convert()", "decode()"],
    "correct_answer": "parse()",
    "explanation": "`JSON.parse()` takes a valid JSON string and transforms it into a JavaScript object."
  },
  {
    "id": 544,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Object.fromEntries()",
    "question": "Fill in the blank to convert an array of key-value pairs into an object.",
    "code_snippet": "const entries = [['a', 1], ['b', 2]];\nconst obj = Object._______(entries);",
    "options": ["entries()", "fromEntries()", "keys()", "values()"],
    "correct_answer": "fromEntries()",
    "explanation": "`Object.fromEntries()` is the exact inverse of `Object.entries()`. It takes an iterable of `[key, value]` pairs and returns a new object."
  },
  {
    "id": 545,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object.hasOwn()",
    "question": "What is the modern, recommended replacement for `obj.hasOwnProperty('prop')` introduced in ES2022?",
    "code_snippet": null,
    "options": ["Object.exists(obj, 'prop')", "Object.hasOwn(obj, 'prop')", "Object.contains(obj, 'prop')", "Object.check(obj, 'prop')"],
    "correct_answer": "Object.hasOwn(obj, 'prop')",
    "explanation": "`Object.hasOwn()` is a safer, more reliable static method that works even if the object was created with `Object.create(null)` (where `hasOwnProperty` wouldn't exist)."
  },
  {
    "id": 546,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Iterating Objects",
    "question": "What is the cleanest, most modern way to loop through both the keys AND values of an object?",
    "code_snippet": null,
    "options": ["Using a `for...in` loop", "Using `Object.keys()` and looking up the value manually", "Using a `for...of` loop combined with `Object.entries()`", "Using the `forEach()` method directly on the object"],
    "correct_answer": "Using a `for...of` loop combined with `Object.entries()`",
    "explanation": "Objects don't have a `forEach` method. The cleanest modern approach is `for (let [key, value] of Object.entries(obj))`, which gives you both the key and value neatly destructured."
  },
  {
    "id": 547,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Spread Operator Overriding",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const defaults = { theme: 'light', lang: 'en' };\nconst userPrefs = { theme: 'dark' };\nconst finalConfig = { ...defaults, ...userPrefs };\nconsole.log(finalConfig.theme);",
    "options": ["light", "dark", "undefined", "Error"],
    "correct_answer": "dark",
    "explanation": "When merging objects with the spread operator, if there are duplicate keys, the properties from the object that comes LATER (to the right) overwrite the earlier ones. `userPrefs` overwrites `defaults`."
  },
  {
    "id": 548,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "code-fill-in-blank",
    "topic": "Destructuring in Functions",
    "question": "Fill in the blank to destructure the 'name' and 'age' properties directly from the function's argument object.",
    "code_snippet": "function greet(_______) {\n  console.log(`Hello ${name}, you are ${age}`);\n}\ngreet({ name: 'Alice', age: 25 });",
    "options": ["user", "name, age", "{ name, age }", "[name, age]"],
    "correct_answer": "{ name, age }",
    "explanation": "You can use object destructuring directly in the function parameters. When the object is passed in, it automatically extracts `name` and `age` into local variables."
  },
  {
    "id": 549,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "conceptual",
    "topic": "Object.seal()",
    "question": "What is the difference between `Object.freeze()` and `Object.seal()`?",
    "code_snippet": null,
    "options": ["There is no difference", "`freeze()` prevents adding/deleting/changing properties; `seal()` prevents adding/deleting, but you CAN still change existing property values", "`seal()` is for arrays, `freeze()` is for objects", "`seal()` makes the object immutable, `freeze()` just hides it"],
    "correct_answer": "`freeze()` prevents adding/deleting/changing properties; `seal()` prevents adding/deleting, but you CAN still change existing property values",
    "explanation": "`Object.seal()` is slightly less strict than `freeze()`. It prevents the structure of the object from changing (no new properties, no deletions), but it allows you to mutate the values of the existing properties."
  },
  {
    "id": 550,
    "level": "intermediate",
    "module_id": "mod_08_objects",
    "module_name": "Objects",
    "type": "output-prediction",
    "topic": "Objects in Arrays",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const users = [{ id: 1, name: 'A' }, { id: 2, name: 'B' }];\nconst userA = users[0];\nuserA.name = 'Alice';\nconsole.log(users[0].name);",
    "options": ["A", "Alice", "undefined", "Error"],
    "correct_answer": "Alice",
    "explanation": "Because objects are passed by reference, `userA` is not a copy; it points to the exact same object stored at index 0 of the `users` array. Modifying `userA.name` modifies the object inside the array."
  }
]
