[
  {
    "id": 161,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Variables",
    "question": "What is the main difference between `let` and `const` in modern JavaScript?",
    "code_snippet": null,
    "options": ["`let` is for numbers, `const` is for strings", "`let` allows reassignment, `const` does not allow reassignment", "`const` is faster than `let`", "There is no difference"],
    "correct_answer": "`let` allows reassignment, `const` does not allow reassignment",
    "explanation": "Both `let` and `const` are block-scoped. The only difference is that a variable declared with `const` cannot be reassigned to a new value after its initial assignment."
  },
  {
    "id": 162,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Variables",
    "question": "Which keyword should you use to declare a variable that will hold the value of PI and should never change?",
    "code_snippet": "_______ PI = 3.14159;",
    "options": ["var", "let", "const", "static"],
    "correct_answer": "const",
    "explanation": "Use `const` for values that should remain constant and never be reassigned. This prevents accidental changes later in the code."
  },
  {
    "id": 163,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Variables",
    "question": "What happens if you try to reassign a value to a variable declared with `const`?",
    "code_snippet": null,
    "options": ["The value changes silently", "It throws a TypeError", "It throws a SyntaxError", "It creates a new variable"],
    "correct_answer": "It throws a TypeError",
    "explanation": "Attempting to reassign a `const` variable results in a TypeError: 'Assignment to constant variable.' The original value remains unchanged."
  },
  {
    "id": 164,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "Variables",
    "question": "What will happen when this code is executed?",
    "code_snippet": "const age = 25;\nage = 26;\nconsole.log(age);",
    "options": ["It logs 25", "It logs 26", "It throws a TypeError", "It throws a ReferenceError"],
    "correct_answer": "It throws a TypeError",
    "explanation": "Because `age` was declared with `const`, trying to reassign it (`age = 26`) immediately throws a TypeError and stops the execution."
  },
  {
    "id": 165,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Variables",
    "question": "What does it mean that `let` and `const` are 'block-scoped'?",
    "code_snippet": null,
    "options": ["They can only be used inside functions", "They are only accessible within the nearest curly braces `{}` where they are defined", "They can be accessed from any file", "They are only available in strict mode"],
    "correct_answer": "They are only accessible within the nearest curly braces `{}` where they are defined",
    "explanation": "Block scope means the variable only exists inside the `{}` block (like an `if` statement or a `for` loop) where it was declared. `var`, on the other hand, is function-scoped."
  },
  {
    "id": 166,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Variables",
    "question": "Which keyword allows you to declare a variable that CAN be reassigned later, but is block-scoped?",
    "code_snippet": "_______ score = 0;\nscore = 10; // This is allowed",
    "options": ["const", "let", "var", "final"],
    "correct_answer": "let",
    "explanation": "`let` is the modern standard for declaring variables that need to be reassigned. It is block-scoped, unlike `var` which is function-scoped."
  },
  {
    "id": 167,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Variables",
    "question": "What is the 'Temporal Dead Zone' (TDZ) in JavaScript?",
    "code_snippet": null,
    "options": ["A memory leak issue", "The time between a `let`/`const` variable being hoisted and it being initialized, where accessing it throws an error", "A deprecated feature in ES6", "A zone in the browser where JS doesn't run"],
    "correct_answer": "The time between a `let`/`const` variable being hoisted and it being initialized, where accessing it throws an error",
    "explanation": "Unlike `var` which is initialized as `undefined`, `let` and `const` are hoisted but not initialized. Accessing them before their declaration line causes a ReferenceError."
  },
  {
    "id": 168,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "Variables",
    "question": "What will be logged to the console?",
    "code_snippet": "console.log(x);\nvar x = 10;",
    "options": ["10", "undefined", "null", "It throws a ReferenceError"],
    "correct_answer": "undefined",
    "explanation": "Variables declared with `var` are hoisted and initialized with `undefined`. So the declaration is moved to the top, but the assignment (`x = 10`) stays where it is."
  },
  {
    "id": 169,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Variables",
    "question": "Can you change a property inside an object that was declared with `const`?",
    "code_snippet": null,
    "options": ["No, `const` makes the entire object immutable", "Yes, `const` only prevents reassignment of the variable itself, not mutation of its contents", "Only if you use the `mutate` keyword", "No, it will throw a TypeError"],
    "correct_answer": "Yes, `const` only prevents reassignment of the variable itself, not mutation of its contents",
    "explanation": "For objects and arrays, `const` ensures the variable identifier always points to the same memory reference. However, you can still add, remove, or change properties inside that object."
  },
  {
    "id": 170,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "theory-fill-in-blank",
    "topic": "Variables",
    "question": "In modern JavaScript (ES6+), it is highly recommended to use _______ and _______ instead of `var`.",
    "code_snippet": null,
    "options": ["let and const", "int and string", "var and let", "def and const"],
    "correct_answer": "let and const",
    "explanation": "`let` and `const` provide block-scoping and avoid the confusing hoisting behaviors of `var`. Most modern style guides recommend using them exclusively."
  },
  {
    "id": 171,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Variables",
    "question": "What will happen if you try to declare the same variable twice using `let` in the same scope?",
    "code_snippet": "let name = 'Alice';\nlet name = 'Bob';",
    "options": ["The second declaration overwrites the first", "It logs 'Bob'", "It throws a SyntaxError", "It creates an array of names"],
    "correct_answer": "It throws a SyntaxError",
    "explanation": "Unlike `var`, which allows redeclaration in the same scope, `let` and `const` do not. Redeclaring them throws a SyntaxError: 'Identifier already declared'."
  },
  {
    "id": 172,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "Variables",
    "question": "What will be the exact output of this code?",
    "code_snippet": "let x = 10;\n{\n  let x = 20;\n}\nconsole.log(x);",
    "options": ["10", "20", "undefined", "Error"],
    "correct_answer": "10",
    "explanation": "Because `let` is block-scoped, the `x = 20` inside the curly braces `{}` is a completely separate variable from the outer `x`. The outer `x` remains 10."
  },
  {
    "id": 173,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Data Types",
    "question": "How many primitive data types are there in standard JavaScript?",
    "code_snippet": null,
    "options": ["4", "5", "7", "9"],
    "correct_answer": "7",
    "explanation": "There are 7 primitive types: String, Number, Boolean, Null, Undefined, Symbol (ES6), and BigInt (ES2020). Everything else (like Objects and Arrays) is non-primitive."
  },
  {
    "id": 174,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "Which operator is used to check the data type of a variable?",
    "code_snippet": "let age = 25;\nconsole.log(_______ age); // Outputs 'number'",
    "options": ["check", "type", "typeof", "datatype"],
    "correct_answer": "typeof",
    "explanation": "The `typeof` operator returns a string indicating the type of the unevaluated operand."
  },
  {
    "id": 175,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "What does `typeof \"Hello\"` return?",
    "code_snippet": null,
    "options": ["'text'", "'string'", "'String'", "'char'"],
    "correct_answer": "'string'",
    "explanation": "The `typeof` operator always returns lowercase strings for primitive types. For text, it returns 'string'."
  },
  {
    "id": 176,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Data Types",
    "question": "What is the famous quirk/bug in JavaScript regarding the `typeof` operator?",
    "code_snippet": null,
    "options": ["typeof NaN returns 'string'", "typeof undefined returns 'null'", "typeof null returns 'object'", "typeof true returns 'boolean'"],
    "correct_answer": "typeof null returns 'object'",
    "explanation": "In the first version of JavaScript, values were represented as a type tag and a value. The type tag for objects was 0. `null` was represented as the NULL pointer (0x00), so its type tag was also 0, making `typeof null` return 'object'. This bug was never fixed to avoid breaking existing code."
  },
  {
    "id": 177,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "What does `typeof undefined` return?",
    "code_snippet": null,
    "options": ["'null'", "'undefined'", "'void'", "'empty'"],
    "correct_answer": "'undefined'",
    "explanation": "The `typeof` operator correctly returns the string 'undefined' for variables that have been declared but not assigned a value."
  },
  {
    "id": 178,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "What does `typeof true` return?",
    "code_snippet": null,
    "options": ["'boolean'", "'bool'", "'true'", "'logical'"],
    "correct_answer": "'boolean'",
    "explanation": "The `typeof` operator returns 'boolean' for both `true` and `false` values."
  },
  {
    "id": 179,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Data Types",
    "question": "What is the difference between `null` and `undefined`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`undefined` means a variable hasn't been assigned a value; `null` is an intentional assignment of 'no value'", "`null` is for numbers, `undefined` is for strings", "`undefined` is an object, `null` is a primitive"],
    "correct_answer": "`undefined` means a variable hasn't been assigned a value; `null` is an intentional assignment of 'no value'",
    "explanation": "`undefined` is the default state of a declared variable. `null` is a value you explicitly assign to a variable to indicate that it is intentionally empty."
  },
  {
    "id": 180,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "Data Types",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(typeof NaN);",
    "options": ["'NaN'", "'number'", "'undefined'", "'string'"],
    "correct_answer": "'number'",
    "explanation": "NaN stands for 'Not-a-Number', but ironically, in JavaScript, it is classified as a special numeric value. Therefore, `typeof NaN` returns 'number'."
  },
  {
    "id": 181,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "What does `typeof []` (an empty array) return?",
    "code_snippet": null,
    "options": ["'array'", "'list'", "'object'", "'undefined'"],
    "correct_answer": "'object'",
    "explanation": "In JavaScript, arrays are a special type of object. Therefore, `typeof []` returns 'object'. (To check if something is an array, you must use `Array.isArray()`)."
  },
  {
    "id": 182,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "What does `typeof {}` (an empty object) return?",
    "code_snippet": null,
    "options": ["'map'", "'dict'", "'object'", "'hash'"],
    "correct_answer": "'object'",
    "explanation": "Standard JavaScript objects (created with `{}`) return 'object' when checked with the `typeof` operator."
  },
  {
    "id": 183,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "Data Types",
    "question": "What is a 'String' in JavaScript?",
    "code_snippet": null,
    "options": ["A sequence of numeric characters", "A sequence of text characters wrapped in quotes", "A boolean value", "A special type of array"],
    "correct_answer": "A sequence of text characters wrapped in quotes",
    "explanation": "A string is a primitive data type used for storing and manipulating text. It must be enclosed in single quotes (' '), double quotes (\" \"), or backticks (` `)."
  },
  {
    "id": 184,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "Data Types",
    "question": "What does `typeof function() {}` return?",
    "code_snippet": null,
    "options": ["'object'", "'function'", "'method'", "'callable'"],
    "correct_answer": "'function'",
    "explanation": "Although functions are technically objects in JavaScript, the `typeof` operator has a special exception for them and returns 'function'."
  },
  {
    "id": 185,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which property is used to find the number of characters in a string?",
    "code_snippet": "let text = 'Hello';\nconsole.log(text._______); // Outputs 5",
    "options": ["size", "length", "count", "index"],
    "correct_answer": "length",
    "explanation": "The `.length` property returns the total number of characters in a string, including spaces and punctuation."
  },
  {
    "id": 186,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method converts all characters in a string to UPPERCASE?",
    "code_snippet": "let name = 'alice';\nconsole.log(name._______()); // Outputs 'ALICE'",
    "options": ["toUpper()", "toUpperCase()", "upper()", "capitalize()"],
    "correct_answer": "toUpperCase()",
    "explanation": "The `.toUpperCase()` method returns a new string with all alphabetic characters converted to uppercase."
  },
  {
    "id": 187,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method converts all characters in a string to lowercase?",
    "code_snippet": "let city = 'LONDON';\nconsole.log(city._______()); // Outputs 'london'",
    "options": ["toLower()", "toLowerCase()", "lower()", "small()"],
    "correct_answer": "toLowerCase()",
    "explanation": "The `.toLowerCase()` method returns a new string with all alphabetic characters converted to lowercase."
  },
  {
    "id": 188,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "String Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"JavaScript\".length);",
    "options": ["9", "10", "11", "8"],
    "correct_answer": "10",
    "explanation": "The string 'JavaScript' contains exactly 10 characters (J-a-v-a-S-c-r-i-p-t). Remember that spaces and capital letters count as characters."
  },
  {
    "id": 189,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method removes whitespace from both ends of a string?",
    "code_snippet": "let messy = '   hello   ';\nlet clean = messy._______();",
    "options": ["strip()", "clean()", "trim()", "cut()"],
    "correct_answer": "trim()",
    "explanation": "The `.trim()` method removes whitespace (spaces, tabs, newlines) from the beginning and end of a string. It does not affect spaces in the middle."
  },
  {
    "id": 190,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method returns the character at a specific index (position) in a string?",
    "code_snippet": "let word = 'Apple';\nconsole.log(word._______(0)); // Outputs 'A'",
    "options": ["get()", "index()", "charAt()", "char()"],
    "correct_answer": "charAt()",
    "explanation": "The `.charAt(index)` method returns the character at the specified index. Remember that strings are zero-indexed, so the first character is at index 0."
  },
  {
    "id": 191,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method searches a string for a specified value and returns the position (index) of the first match?",
    "code_snippet": "let text = 'Hello World';\nconsole.log(text._______('World')); // Outputs 6",
    "options": ["find()", "search()", "indexOf()", "locate()"],
    "correct_answer": "indexOf()",
    "explanation": "The `.indexOf(searchValue)` method returns the index of the first occurrence of the specified text. If it's not found, it returns -1."
  },
  {
    "id": 192,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "String Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"hello\".indexOf(\"z\"));",
    "options": ["0", "-1", "undefined", "false"],
    "correct_answer": "-1",
    "explanation": "If the `.indexOf()` method cannot find the specified character or string, it returns -1 to indicate that it was not found."
  },
  {
    "id": 193,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method extracts a part of a string and returns it as a new string, without modifying the original?",
    "code_snippet": "let text = 'Apple, Banana, Mango';\nlet part = text._______(7, 13); // Returns 'Banana'",
    "options": ["cut()", "extract()", "slice()", "substring()"],
    "correct_answer": "slice()",
    "explanation": "The `.slice(start, end)` method extracts a section of a string and returns it as a new string. The end index is not included in the extraction."
  },
  {
    "id": 194,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method is used to replace a specified value with another value in a string?",
    "code_snippet": "let greeting = 'Hello John';\nlet newGreeting = greeting._______('John', 'Alice');",
    "options": ["swap()", "change()", "replace()", "update()"],
    "correct_answer": "replace()",
    "explanation": "The `.replace(searchValue, newValue)` method returns a new string with the first matching value replaced. (Note: To replace all occurrences, you would use a regular expression or `.replaceAll()`)."
  },
  {
    "id": 195,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "conceptual",
    "topic": "String Methods",
    "question": "Are strings in JavaScript mutable (changeable in place)?",
    "code_snippet": null,
    "options": ["Yes, you can change individual characters like `str[0] = 'A'`", "No, strings are immutable; methods like `.toUpperCase()` return a brand new string", "Yes, but only in strict mode", "No, strings are deleted from memory after use"],
    "correct_answer": "No, strings are immutable; methods like `.toUpperCase()` return a brand new string",
    "explanation": "Once a string is created, it cannot be changed. String methods do not alter the original string; they always return a new string with the modifications."
  },
  {
    "id": 196,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "String Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"apple\".toUpperCase());",
    "options": ["'Apple'", "'APPLE'", "'apple'", "Error"],
    "correct_answer": "'APPLE'",
    "explanation": "The `.toUpperCase()` method converts all lowercase letters in the string to their uppercase equivalents."
  },
  {
    "id": 197,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which method checks if a string contains a specified substring and returns `true` or `false`?",
    "code_snippet": "let text = 'I love JavaScript';\nconsole.log(text._______('JavaScript')); // Outputs true",
    "options": ["has()", "contains()", "includes()", "find()"],
    "correct_answer": "includes()",
    "explanation": "The `.includes()` method performs a case-sensitive search and returns true if the string contains the specified text, otherwise false."
  },
  {
    "id": 198,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "String Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"  hi  \".trim().length);",
    "options": ["6", "2", "4", "8"],
    "correct_answer": "2",
    "explanation": "First, `.trim()` removes the leading and trailing spaces, turning '  hi  ' into 'hi'. Then, `.length` counts the characters in 'hi', which is 2."
  },
  {
    "id": 199,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "code-fill-in-blank",
    "topic": "String Methods",
    "question": "Which operator is primarily used to concatenate (join) two strings together?",
    "code_snippet": "let firstName = 'John';\nlet lastName = 'Doe';\nlet fullName = firstName _______ ' ' _______ lastName;",
    "options": ["&", "+", ".", "&&"],
    "correct_answer": "+",
    "explanation": "The `+` operator is used for string concatenation. It joins strings together end-to-end. (Note: Template literals with backticks are the modern alternative)."
  },
  {
    "id": 200,
    "level": "beginner",
    "module_id": "mod_02_variables",
    "module_name": "Variables & Data Types",
    "type": "output-prediction",
    "topic": "String Methods",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(\"Result: \" + (2 + 3));",
    "options": ["'Result: 23'", "'Result: 5'", "'Result: + 5'", "Error"],
    "correct_answer": "'Result: 5'",
    "explanation": "Because of the parentheses `(2 + 3)`, the math is calculated first, resulting in the number 5. Then, the string 'Result: ' is concatenated with the number 5, resulting in 'Result: 5'."
  }
]
