[
  {
    "id": 241,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Control Flow Basics",
    "question": "What does 'Control Flow' mean in programming?",
    "code_snippet": null,
    "options": ["The speed at which the code executes", "The order in which statements and instructions are executed in a program", "The process of downloading files from a server", "The way CSS styles are applied to HTML"],
    "correct_answer": "The order in which statements and instructions are executed in a program",
    "explanation": "Control flow determines how a computer reads and executes code. By default, it runs top-to-bottom, but control flow statements (like if/else or loops) allow it to make decisions and skip or repeat code."
  },
  {
    "id": 242,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "if/else",
    "question": "Which keyword is used to start a conditional statement that executes a block of code only if a specified condition is true?",
    "code_snippet": "_______ (isRaining) {\n  console.log('Take an umbrella');\n}",
    "options": ["when", "check", "if", "for"],
    "correct_answer": "if",
    "explanation": "The `if` keyword evaluates the condition inside the parentheses. If it's true, the code block inside the curly braces executes."
  },
  {
    "id": 243,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let age = 20;\nif (age >= 18) {\n  console.log('Adult');\n}",
    "options": ["Adult", "undefined", "Nothing is logged", "Error"],
    "correct_answer": "Adult",
    "explanation": "The condition `20 >= 18` evaluates to true, so the code inside the `if` block runs and logs 'Adult'."
  },
  {
    "id": 244,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let score = 50;\nif (score > 100) {\n  console.log('You win!');\n}\nconsole.log('Game over');",
    "options": ["You win!", "Game over", "You win! Game over", "Nothing is logged"],
    "correct_answer": "Game over",
    "explanation": "The condition `50 > 100` is false, so the `if` block is skipped. The code continues to the next line, logging 'Game over'."
  },
  {
    "id": 245,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "if/else",
    "question": "Which keyword is used to specify a block of code that will execute if the `if` condition is false?",
    "code_snippet": "if (isSunny) {\n  console.log('Go to the beach');\n} _______ {\n  console.log('Stay home');\n}",
    "options": ["else if", "otherwise", "else", "false"],
    "correct_answer": "else",
    "explanation": "The `else` keyword catches everything that isn't caught by the preceding `if` (or `else if`) conditions."
  },
  {
    "id": 246,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let hour = 20;\nif (hour < 18) {\n  console.log('Good day');\n} else {\n  console.log('Good evening');\n}",
    "options": ["Good day", "Good evening", "Good day Good evening", "Error"],
    "correct_answer": "Good evening",
    "explanation": "The condition `20 < 18` is false, so the `if` block is skipped and the `else` block executes, logging 'Good evening'."
  },
  {
    "id": 247,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "if/else",
    "question": "Which keyword allows you to test multiple conditions in a chain, after the initial `if`?",
    "code_snippet": "if (grade === 'A') {\n  console.log('Excellent');\n} _______ (grade === 'B') {\n  console.log('Good');\n}",
    "options": ["else if", "elseif", "elif", "or if"],
    "correct_answer": "else if",
    "explanation": "In JavaScript, the correct syntax to chain additional conditions is `else if` (two separate words)."
  },
  {
    "id": 248,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let num = 10;\nif (num > 0) {\n  console.log('Positive');\n} else if (num > 5) {\n  console.log('Greater than 5');\n} else {\n  console.log('Zero or negative');\n}",
    "options": ["Positive", "Greater than 5", "Positive Greater than 5", "Zero or negative"],
    "correct_answer": "Positive",
    "explanation": "In an `if...else if...else` chain, JavaScript executes ONLY the FIRST block where the condition is true. Since `10 > 0` is true, it logs 'Positive' and skips the rest of the chain."
  },
  {
    "id": 249,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "if/else",
    "question": "Why is the order of conditions important in an `if...else if` chain?",
    "code_snippet": null,
    "options": ["It doesn't matter, JavaScript sorts them automatically", "Because only the first true condition will execute, so broader conditions should usually come last", "Because the last condition always overrides the first", "Because it changes the data types of the variables"],
    "correct_answer": "Because only the first true condition will execute, so broader conditions should usually come last",
    "explanation": "If you put a broad condition first (like `if (num > 0)`), it will catch everything and the more specific conditions below it (like `else if (num > 100)`) will never run."
  },
  {
    "id": 250,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following nested `if` statements?",
    "code_snippet": "let isMember = true;\nlet hasCoupon = false;\n\nif (isMember) {\n  if (hasCoupon) {\n    console.log('Extra discount!');\n  } else {\n    console.log('Member discount');\n  }\n}",
    "options": ["Extra discount!", "Member discount", "Member discount Extra discount!", "Nothing is logged"],
    "correct_answer": "Member discount",
    "explanation": "The outer `if (isMember)` is true, so it enters the block. The inner `if (hasCoupon)` is false, so it drops to the inner `else` block, logging 'Member discount'."
  },
  {
    "id": 251,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Truthy/Falsy",
    "question": "In JavaScript, what is a 'falsy' value?",
    "code_snippet": null,
    "options": ["A value that is exactly equal to the string 'false'", "A value that translates to false when evaluated in a boolean context (like an if statement)", "Any number that is less than zero", "A variable that has been deleted"],
    "correct_answer": "A value that translates to false when evaluated in a boolean context (like an if statement)",
    "explanation": "JavaScript coerces values to booleans in conditions. Falsy values are treated as `false`, and everything else is 'truthy' and treated as `true`."
  },
  {
    "id": 252,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Truthy/Falsy",
    "question": "Which of the following values is considered TRUTHY in JavaScript?",
    "code_snippet": "if (_______) {\n  console.log('This will run');\n}",
    "options": ["0", "\"\"", "\"false\"", "null"],
    "correct_answer": "\"false\"",
    "explanation": "The string `\"false\"` is a non-empty string, so it is truthy! The others (`0`, `\"\"`, `null`) are all on the official list of falsy values."
  },
  {
    "id": 253,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let username = \"\";\nif (username) {\n  console.log('Welcome');\n} else {\n  console.log('Please log in');\n}",
    "options": ["Welcome", "Please log in", "undefined", "Error"],
    "correct_answer": "Please log in",
    "explanation": "An empty string (`\"\"`) is a falsy value in JavaScript. Therefore, the `if` condition evaluates to false, and the `else` block runs."
  },
  {
    "id": 254,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let itemsInCart = 0;\nif (itemsInCart) {\n  console.log('Checkout');\n} else {\n  console.log('Cart is empty');\n}",
    "options": ["Checkout", "Cart is empty", "0", "false"],
    "correct_answer": "Cart is empty",
    "explanation": "The number `0` is a falsy value. Even though the variable exists and holds a number, it evaluates to false in the `if` condition."
  },
  {
    "id": 255,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let isOffline = null;\nif (isOffline) {\n  console.log('Offline mode');\n} else {\n  console.log('Online mode');\n}",
    "options": ["Offline mode", "Online mode", "null", "Error"],
    "correct_answer": "Online mode",
    "explanation": "`null` is a falsy value. The condition evaluates to false, so the `else` block executes."
  },
  {
    "id": 256,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Truthy/Falsy",
    "question": "Which of the following is NOT one of the 6 standard falsy values in JavaScript?",
    "code_snippet": null,
    "options": ["false", "0", "\"\" (empty string)", "\"0\" (the string zero)"],
    "correct_answer": "\"0\" (the string zero)",
    "explanation": "The string `\"0\"` is a non-empty string, making it TRUTHY. The 6 falsy values are: `false`, `0`, `\"\"`, `null`, `undefined`, and `NaN`."
  },
  {
    "id": 257,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Ternary Operator",
    "question": "What is the Ternary Operator in JavaScript?",
    "code_snippet": null,
    "options": ["A loop that runs three times", "A shorthand way to write a simple if...else statement", "A method to compare three variables at once", "A way to declare three variables on one line"],
    "correct_answer": "A shorthand way to write a simple if...else statement",
    "explanation": "The ternary operator (`condition ? exprIfTrue : exprIfFalse`) is the only JavaScript operator that takes three operands. It's a concise alternative to basic if/else blocks."
  },
  {
    "id": 258,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Ternary Operator",
    "question": "Which two symbols are used to construct a ternary operator?",
    "code_snippet": "let status = age >= 18 _______ 'Adult' _______ 'Minor';",
    "options": ["&& and ||", "? and :", "== and ==", "?? and !"],
    "correct_answer": "? and :",
    "explanation": "The ternary operator uses the question mark (`?`) to separate the condition from the true expression, and the colon (`:`) to separate the true expression from the false expression."
  },
  {
    "id": 259,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Ternary Operator",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let time = 10;\nlet greeting = time < 12 ? 'Good morning' : 'Good afternoon';\nconsole.log(greeting);",
    "options": ["Good morning", "Good afternoon", "undefined", "Error"],
    "correct_answer": "Good morning",
    "explanation": "The condition `10 < 12` is true, so the ternary operator evaluates to the expression before the colon: 'Good morning'."
  },
  {
    "id": 260,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Ternary Operator",
    "question": "Rewrite this if/else statement using a ternary operator:\n`let canDrive; if (age >= 16) { canDrive = true; } else { canDrive = false; }`",
    "code_snippet": "let canDrive = age >= 16 _______ true _______ false;",
    "options": ["? , :", "if , else", "? , ?", ": , :"],
    "correct_answer": "? , :",
    "explanation": "The correct syntax is `condition ? valueIfTrue : valueIfFalse`. So, `age >= 16 ? true : false`."
  },
  {
    "id": 261,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "switch",
    "question": "When is a `switch` statement generally preferred over an `if...else if` chain?",
    "code_snippet": null,
    "options": ["When you need to check complex mathematical formulas", "When you are comparing a single variable against many specific, exact values (like menu options)", "When you need to loop through an array", "When you are checking if a variable is truthy or falsy"],
    "correct_answer": "When you are comparing a single variable against many specific, exact values (like menu options)",
    "explanation": "Switch statements are cleaner and more readable when you have a single variable that could match a dozen different specific values (e.g., days of the week, status codes)."
  },
  {
    "id": 262,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "switch",
    "question": "Which keyword is used to define a specific branch/block of code inside a `switch` statement?",
    "code_snippet": "switch (fruit) {\n  _______ 'apple':\n    console.log('Apples are $1');\n    break;\n}",
    "options": ["if", "when", "case", "match"],
    "correct_answer": "case",
    "explanation": "Inside a switch block, each possible value is defined using the `case` keyword, followed by a colon."
  },
  {
    "id": 263,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "switch",
    "question": "What is the purpose of the `break` keyword inside a `switch` statement?",
    "code_snippet": null,
    "options": ["It pauses the code for 1 second", "It exits the switch block and prevents the code from running into the next cases", "It restarts the switch statement from the top", "It throws an error to stop the program"],
    "correct_answer": "It exits the switch block and prevents the code from running into the next cases",
    "explanation": "Without `break`, JavaScript will continue executing the next `case` blocks regardless of whether they match. This is called 'fall-through'."
  },
  {
    "id": 264,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let day = 2;\nswitch (day) {\n  case 1:\n    console.log('Monday');\n    break;\n  case 2:\n    console.log('Tuesday');\n    break;\n  case 3:\n    console.log('Wednesday');\n    break;\n}",
    "options": ["Monday", "Tuesday", "Wednesday", "Monday Tuesday Wednesday"],
    "correct_answer": "Tuesday",
    "explanation": "The switch matches `case 2`, logs 'Tuesday', and then hits the `break` statement, which safely exits the switch block."
  },
  {
    "id": 265,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code (Notice the missing `break`)?",
    "code_snippet": "let score = 2;\nswitch (score) {\n  case 1:\n    console.log('One');\n  case 2:\n    console.log('Two');\n  case 3:\n    console.log('Three');\n}",
    "options": ["Two", "Two Three", "One Two Three", "Error"],
    "correct_answer": "Two Three",
    "explanation": "This is 'fall-through'. It matches `case 2` and logs 'Two'. Because there is no `break`, it falls through and executes `case 3` as well, logging 'Three'."
  },
  {
    "id": 266,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "switch",
    "question": "Which keyword is used to specify a default block of code to run if no `case` matches the switch expression?",
    "code_snippet": "switch (color) {\n  case 'red':\n    console.log('Stop');\n    break;\n  _______:\n    console.log('Unknown color');\n}",
    "options": ["else", "otherwise", "default", "fallback"],
    "correct_answer": "default",
    "explanation": "The `default` keyword acts like the `else` in an if/else statement. It runs if none of the `case` values match the switch expression."
  },
  {
    "id": 267,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let fruit = 'banana';\nswitch (fruit) {\n  case 'apple':\n    console.log('Apple');\n    break;\n  default:\n    console.log('Unknown fruit');\n}",
    "options": ["Apple", "Unknown fruit", "banana", "Nothing is logged"],
    "correct_answer": "Unknown fruit",
    "explanation": "Since `fruit` is 'banana', it doesn't match `case 'apple'`. It skips to the `default` block and logs 'Unknown fruit'."
  },
  {
    "id": 268,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "switch",
    "question": "What type of equality does a `switch` statement use to compare the expression to the `case` values?",
    "code_snippet": null,
    "options": ["Loose equality (==)", "Strict equality (===)", "Assignment (=)", "Reference equality"],
    "correct_answer": "Strict equality (===)",
    "explanation": "Switch statements use strict comparison (`===`). The values must match in both type and value. For example, the string `'1'` will NOT match the number `1`."
  },
  {
    "id": 269,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let value = '1';\nswitch (value) {\n  case 1:\n    console.log('Number one');\n    break;\n  default:\n    console.log('Not the number 1');\n}",
    "options": ["Number one", "Not the number 1", "1", "Error"],
    "correct_answer": "Not the number 1",
    "explanation": "Because `switch` uses strict equality (`===`), the string `'1'` does not match the number `1`. It falls through to the `default` case."
  },
  {
    "id": 270,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Control Flow Best Practices",
    "question": "When dealing with very complex conditions (e.g., checking age, membership status, and account balance all at once), what is a best practice to keep your code readable?",
    "code_snippet": null,
    "options": ["Put everything into one massive `if` statement", "Use a `switch` statement for everything", "Break the logic down into smaller, well-named functions or variables before the condition", "Avoid using conditions and just use `try...catch`"],
    "correct_answer": "Break the logic down into smaller, well-named functions or variables before the condition",
    "explanation": "Instead of `if (age > 18 && isMember && balance > 0)`, it's much cleaner to do `let canPurchase = age > 18 && isMember && balance > 0; if (canPurchase) { ... }`. This makes the code self-documenting."
  }
]
[
  {
    "id": 271,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Truthy/Falsy",
    "question": "In JavaScript, how is an empty array `[]` evaluated in an `if` statement condition?",
    "code_snippet": null,
    "options": ["It is falsy", "It is truthy", "It throws an error", "It evaluates to null"],
    "correct_answer": "It is truthy",
    "explanation": "In JavaScript, ALL objects (including empty arrays `[]` and empty objects `{}`) are truthy. Only the 6 specific primitive falsy values evaluate to false."
  },
  {
    "id": 272,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "if (\" \") {\n  console.log('A');\n} else {\n  console.log('B');\n}",
    "options": ["A", "B", "undefined", "Error"],
    "correct_answer": "A",
    "explanation": "A string containing a space (`\" \"`) is NOT an empty string. Because it has a length greater than 0, it is a truthy value, so the `if` block runs."
  },
  {
    "id": 273,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(Boolean(\"false\"));",
    "options": ["true", "false", "undefined", "Error"],
    "correct_answer": "true",
    "explanation": "The string `\"false\"` is a non-empty string. When converted to a boolean, any non-empty string becomes `true`."
  },
  {
    "id": 274,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Truthy/Falsy",
    "question": "Which built-in function can you use to explicitly convert any value into its boolean equivalent (true or false)?",
    "code_snippet": "let result = _______(0); // result is false",
    "options": ["toBool()", "Boolean()", "cast()", "convert()"],
    "correct_answer": "Boolean()",
    "explanation": "The `Boolean()` function takes any value and returns `true` or `false` based on whether the value is truthy or falsy."
  },
  {
    "id": 275,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Truthy/Falsy",
    "question": "What is the purpose of the 'Double Bang' (`!!`) operator in JavaScript?",
    "code_snippet": null,
    "options": ["It throws an error", "It reverses a string", "It forces any value into a strict boolean (true or false)", "It multiplies a number by 2"],
    "correct_answer": "It forces any value into a strict boolean (true or false)",
    "explanation": "The first `!` converts the value to a boolean and reverses it. The second `!` reverses it back. The net result is a clean `true` or `false` based on the value's truthiness."
  },
  {
    "id": 276,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Ternary Operator",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let age = 15;\nlet status = age >= 18 ? \"Adult\" : \"Minor\";\nconsole.log(status);",
    "options": ["Adult", "Minor", "undefined", "Error"],
    "correct_answer": "Minor",
    "explanation": "The condition `15 >= 18` is false. Therefore, the ternary operator evaluates to the expression after the colon (`:`), which is \"Minor\"."
  },
  {
    "id": 277,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Ternary Operator",
    "question": "Fill in the blank to complete the ternary operator syntax:",
    "code_snippet": "let message = count > 0 ? \"Items in cart\" _______ \"Cart is empty\";",
    "options": ["?", ":", "&&", "else"],
    "correct_answer": ":",
    "explanation": "The ternary operator requires a question mark `?` after the condition, and a colon `:` to separate the true result from the false result."
  },
  {
    "id": 278,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code (Notice the missing `break` statements)?",
    "code_snippet": "let x = 2;\nswitch(x) {\n  case 1: x += 1;\n  case 2: x += 2;\n  case 3: x += 3;\n}\nconsole.log(x);",
    "options": ["2", "4", "5", "7"],
    "correct_answer": "7",
    "explanation": "This is 'fall-through'. It matches `case 2`, so `x` becomes 4 (2+2). Because there is no `break`, it falls into `case 3` and adds 3 more, making `x` equal to 7."
  },
  {
    "id": 279,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "switch",
    "question": "How do you make multiple `case` values execute the exact same block of code in a switch statement?",
    "code_snippet": "switch(letter) {\n  _______ 'a':\n  _______ 'e':\n  _______ 'i':\n    console.log('Vowel');\n    break;\n}",
    "options": ["Group them with commas: case 'a', 'e', 'i':", "Stack them without breaks: case 'a': case 'e': case 'i':", "Use the || operator: case 'a' || 'e' || 'i':", "It is not possible in JavaScript"],
    "correct_answer": "Stack them without breaks: case 'a': case 'e': case 'i':",
    "explanation": "By stacking `case` labels without any code or `break` statements between them, they will all 'fall through' to the shared block of code at the bottom."
  },
  {
    "id": 280,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let user = null;\nif (user && user.age > 18) {\n  console.log('Adult');\n} else {\n  console.log('Guest');\n}",
    "options": ["Adult", "Guest", "null", "Error"],
    "correct_answer": "Guest",
    "explanation": "Because `user` is `null` (falsy), the `&&` operator short-circuits and doesn't even evaluate `user.age`. The whole condition is false, so it logs 'Guest'. (This prevents a TypeError!)."
  },
  {
    "id": 281,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "if/else",
    "question": "What is 'Short-Circuit Evaluation' with the `&&` operator?",
    "code_snippet": null,
    "options": ["It means the code runs faster", "If the first operand is falsy, the second operand is not evaluated at all", "It automatically adds a `break` statement", "It converts the values to strings"],
    "correct_answer": "If the first operand is falsy, the second operand is not evaluated at all",
    "explanation": "Since `&&` requires BOTH sides to be true, if the left side is false, JavaScript knows the whole expression will be false, so it skips evaluating the right side to save processing power."
  },
  {
    "id": 282,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "if (NaN) {\n  console.log('A');\n} else {\n  console.log('B');\n}",
    "options": ["A", "B", "NaN", "Error"],
    "correct_answer": "B",
    "explanation": "`NaN` (Not-a-Number) is one of the 6 standard falsy values in JavaScript. Therefore, the `if` condition evaluates to false, and the `else` block runs."
  },
  {
    "id": 283,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Ternary Operator",
    "question": "What will be the exact output of this nested ternary operator?",
    "code_snippet": "let num = 0;\nlet text = num > 0 ? \"Positive\" : num < 0 ? \"Negative\" : \"Zero\";\nconsole.log(text);",
    "options": ["Positive", "Negative", "Zero", "undefined"],
    "correct_answer": "Zero",
    "explanation": "First, `0 > 0` is false, so it moves to the second ternary. Then, `0 < 0` is false, so it moves to the final value after the last colon, which is \"Zero\"."
  },
  {
    "id": 284,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "if/else",
    "question": "Fill in the blank to check if `arr` is an array AND has at least one item inside it.",
    "code_snippet": "if (Array.isArray(arr) _______ arr.length > 0) {\n  console.log('Valid array');\n}",
    "options": ["||", "&&", "==", "?? "],
    "correct_answer": "&&",
    "explanation": "The Logical AND (`&&`) operator ensures that BOTH conditions must be true: it must be an array, AND its length must be greater than 0."
  },
  {
    "id": 285,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let val = true;\nswitch(val) {\n  case 1: console.log('One'); break;\n  case 'true': console.log('String true'); break;\n  default: console.log('Other');\n}",
    "options": ["One", "String true", "Other", "Error"],
    "correct_answer": "Other",
    "explanation": "Switch statements use strict equality (`===`). The boolean `true` does not strictly equal the number `1`, nor does it strictly equal the string `'true'`. It falls to the `default` case."
  },
  {
    "id": 286,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Control Flow Best Practices",
    "question": "What is a 'Guard Clause' (or Early Return) in a function?",
    "code_snippet": null,
    "options": ["A `try...catch` block", "An `if` statement at the very top of a function that returns early if an invalid condition is met, preventing deep nesting", "A `switch` statement at the end of a function", "A `while` loop that protects variables from changing"],
    "correct_answer": "An `if` statement at the very top of a function that returns early if an invalid condition is met, preventing deep nesting",
    "explanation": "Instead of wrapping your whole function in a massive `if (isValid) { ... }`, you do `if (!isValid) return;` at the top. This keeps your main logic flat and easy to read."
  },
  {
    "id": 287,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "if (\"false\") {\n  console.log('A');\n} else {\n  console.log('B');\n}",
    "options": ["A", "B", "false", "Error"],
    "correct_answer": "A",
    "explanation": "The string `\"false\"` is a non-empty string. In JavaScript, any non-empty string is truthy, so the `if` block executes."
  },
  {
    "id": 288,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Truthy/Falsy",
    "question": "Fill in the blank to force the variable `username` into a strict boolean (true/false) using the 'Double Bang' operator.",
    "code_snippet": "let hasUsername = _______ username;",
    "options": ["!!", "&&", "||", "Boolean="],
    "correct_answer": "!!",
    "explanation": "The `!!` operator applies Logical NOT twice, effectively coercing any value into its true boolean equivalent (`true` or `false`)."
  },
  {
    "id": 289,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "switch",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let day = 'Sunday';\nswitch(day) {\n  case 'Monday': console.log(1); break;\n  default: console.log(0); break;\n  case 'Tuesday': console.log(2);\n}",
    "options": ["0", "2", "0 2", "Error"],
    "correct_answer": "0",
    "explanation": "It matches the `default` case and logs `0`. Because there is a `break` statement immediately after `console.log(0)`, it exits the switch block and does NOT fall through to 'Tuesday'."
  },
  {
    "id": 290,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Control Flow Best Practices",
    "question": "Why is it generally considered bad practice to have more than 3 or 4 levels of nested `if` statements?",
    "code_snippet": null,
    "options": ["It makes the code run slower", "It causes memory leaks", "It makes the code very difficult to read, debug, and maintain (high cyclomatic complexity)", "JavaScript will throw an error if nesting goes past 3 levels"],
    "correct_answer": "It makes the code very difficult to read, debug, and maintain (high cyclomatic complexity)",
    "explanation": "Deeply nested code (often called the 'Arrow Anti-Pattern' because of the shape it makes) is hard for humans to follow. Refactoring into smaller functions or using guard clauses is highly recommended."
  }
]
[
  {
    "id": 291,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Short-Circuit Evaluation",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let username = \"\";\nlet displayName = username || \"Guest\";\nconsole.log(displayName);",
    "options": ["\"\"", "Guest", "undefined", "Error"],
    "correct_answer": "Guest",
    "explanation": "The `||` (OR) operator returns the first 'truthy' value it finds. Since an empty string is falsy, it skips it and returns the second value, \"Guest\"."
  },
  {
    "id": 292,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Short-Circuit Evaluation",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let isLoggedIn = true;\nlet result = isLoggedIn && \"Welcome back!\";\nconsole.log(result);",
    "options": ["true", "Welcome back!", "false", "undefined"],
    "correct_answer": "Welcome back!",
    "explanation": "The `&&` (AND) operator returns the first 'falsy' value it finds, or the LAST value if all are truthy. Since `true` is truthy, it moves to the next value and returns \"Welcome back!\"."
  },
  {
    "id": 293,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Nullish Coalescing",
    "question": "What is the main difference between the `||` (OR) operator and the `??` (Nullish Coalescing) operator?",
    "code_snippet": null,
    "options": ["There is no difference", "`||` checks for null/undefined, `??` checks for all falsy values", "`||` checks for all falsy values, `??` checks ONLY for null and undefined", "`??` is only used for numbers"],
    "correct_answer": "`||` checks for all falsy values, `??` checks ONLY for null and undefined",
    "explanation": "`||` will trigger the fallback for `0`, `\"\"`, and `false`. `??` is stricter and will ONLY trigger the fallback if the value is exactly `null` or `undefined`."
  },
  {
    "id": 294,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Nullish Coalescing",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let score = 0;\nlet displayScore = score ?? 10;\nconsole.log(displayScore);",
    "options": ["10", "0", "null", "undefined"],
    "correct_answer": "0",
    "explanation": "Because `??` only checks for null/undefined, and `0` is neither, it returns the original value `0`. (If we had used `||`, it would have returned 10, because 0 is falsy)."
  },
  {
    "id": 295,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Nullish Coalescing",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let isPremium = false;\nlet status = isPremium ?? \"Standard\";\nconsole.log(status);",
    "options": ["Standard", "false", "true", "undefined"],
    "correct_answer": "false",
    "explanation": "The boolean `false` is not `null` or `undefined`. Therefore, the `??` operator returns the left-hand value, `false`, and ignores the fallback."
  },
  {
    "id": 296,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Logical Assignment",
    "question": "Which modern operator means 'Assign the right value to the left variable ONLY if the left variable is falsy'?",
    "code_snippet": "let userRole _______ 'guest'; // If userRole is empty/null, make it 'guest'",
    "options": ["||=", "&&=", "??=", "=="],
    "correct_answer": "||=",
    "explanation": "The Logical OR Assignment (`||=`) operator is shorthand for `a = a || b`. It only assigns the new value if the current value is falsy."
  },
  {
    "id": 297,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else Traps",
    "question": "What will be the exact output of the following code? (Notice the missing curly braces!)",
    "code_snippet": "let isReady = true;\nif (isReady)\n  console.log('A');\n  console.log('B');",
    "options": ["A", "B", "A B", "Error"],
    "correct_answer": "A B",
    "explanation": "Without curly braces `{}`, an `if` statement only controls the VERY NEXT single line. So `console.log('A')` is conditional, but `console.log('B')` will ALWAYS run."
  },
  {
    "id": 298,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "if/else Traps",
    "question": "What will be the exact output of the following code? (Notice the semicolon!)",
    "code_snippet": "let x = 10;\nif (x > 5); {\n  console.log('Greater');\n}",
    "options": ["Greater", "Nothing is logged", "undefined", "Error"],
    "correct_answer": "Greater",
    "explanation": "The semicolon `;` immediately after the `if` condition acts as an empty statement. The `if` block is considered 'done'. The code inside the curly braces `{}` is just a standalone block that always executes."
  },
  {
    "id": 299,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "switch Quirks",
    "question": "If you use a `return` statement inside a `case` block of a `switch` inside a function, do you still need a `break` statement?",
    "code_snippet": null,
    "options": ["Yes, otherwise it throws an error", "No, because `return` immediately exits the entire function", "Yes, `break` is always required in a switch", "No, but you must use `exit` instead"],
    "correct_answer": "No, because `return` immediately exits the entire function",
    "explanation": "The `return` keyword stops the execution of the function and returns a value. Since the function stops, the switch block stops, making a `break` statement redundant."
  },
  {
    "id": 300,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "switch Quirks",
    "question": "Can you use a `switch` statement to compare objects or arrays?",
    "code_snippet": null,
    "options": ["No, switch only works with strings and numbers", "Yes, but it compares them by reference (memory address), not by their contents", "Yes, it compares them by their string representation", "No, it will throw a TypeError"],
    "correct_answer": "Yes, but it compares them by reference (memory address), not by their contents",
    "explanation": "Because `switch` uses strict equality (`===`), comparing two different array variables like `[] === []` will be false, even if they have the exact same contents."
  },
  {
    "id": 301,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy Edge Cases",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "if (-0) {\n  console.log('A');\n} else {\n  console.log('B');\n}",
    "options": ["A", "B", "-0", "Error"],
    "correct_answer": "B",
    "explanation": "In JavaScript, negative zero (`-0`) is mathematically equal to `0`. Since `0` is a falsy value, `-0` is also falsy, so the `else` block runs."
  },
  {
    "id": 302,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy Edge Cases",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "if (0n) {\n  console.log('A');\n} else {\n  console.log('B');\n}",
    "options": ["A", "B", "0n", "Error"],
    "correct_answer": "B",
    "explanation": "`0n` is the BigInt representation of zero. Just like the standard number `0`, BigInt zero is considered a falsy value in JavaScript."
  },
  {
    "id": 303,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "code-fill-in-blank",
    "topic": "Logical Assignment",
    "question": "Which operator means 'Assign the right value to the left variable ONLY if the left variable is null or undefined'?",
    "code_snippet": "let userData _______ fetchDefaultData();",
    "options": ["||=", "&&=", "??=", "==="],
    "correct_answer": "??=",
    "explanation": "The Logical Nullish Assignment (`??=`) is shorthand for `a = a ?? b`. It only assigns the new value if the current value is strictly `null` or `undefined`."
  },
  {
    "id": 304,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Short-Circuit Evaluation",
    "question": "What will be the exact output of the following chained `||` operators?",
    "code_snippet": "let val = null || undefined || 0 || \"found\" || \"ignored\";\nconsole.log(val);",
    "options": ["null", "0", "found", "ignored"],
    "correct_answer": "found",
    "explanation": "The `||` operator scans from left to right and returns the FIRST truthy value it encounters. `null`, `undefined`, and `0` are falsy. \"found\" is truthy, so it stops there and returns \"found\"."
  },
  {
    "id": 305,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Truthy/Falsy Edge Cases",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(Boolean(new Boolean(false)));",
    "options": ["true", "false", "undefined", "Error"],
    "correct_answer": "true",
    "explanation": "`new Boolean(false)` creates an *object*. In JavaScript, ALL objects are truthy, regardless of what data they hold inside them. Therefore, converting it to a boolean yields `true`."
  },
  {
    "id": 306,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Nullish Coalescing",
    "question": "What will happen when this code is executed?",
    "code_snippet": "let result = false ?? true && \"hello\";\nconsole.log(result);",
    "options": ["false", "hello", "true", "It throws a SyntaxError"],
    "correct_answer": "It throws a SyntaxError",
    "explanation": "JavaScript throws a SyntaxError if you mix the `??` operator directly with `&&` or `||` without using parentheses `()` to explicitly define the order of operations. This prevents ambiguous logic bugs."
  },
  {
    "id": 307,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "switch Quirks",
    "question": "What is the `switch(true)` pattern in JavaScript?",
    "code_snippet": null,
    "options": ["A syntax error", "A way to use a switch statement as a cleaner alternative to a long if/else if chain with complex conditions", "A way to force the switch to run twice", "A method to convert strings to booleans"],
    "correct_answer": "A way to use a switch statement as a cleaner alternative to a long if/else if chain with complex conditions",
    "explanation": "By writing `switch(true)`, you can put complex boolean expressions in the `case` labels (e.g., `case age > 18 && isMember:`). The first case that evaluates to `true` will execute."
  },
  {
    "id": 308,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "output-prediction",
    "topic": "Short-Circuit Evaluation",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let count = NaN;\nlet display = count || \"No items\";\nconsole.log(display);",
    "options": ["NaN", "No items", "0", "undefined"],
    "correct_answer": "No items",
    "explanation": "`NaN` is a falsy value in JavaScript. The `||` operator sees the falsy value on the left, skips it, and returns the fallback string \"No items\"."
  },
  {
    "id": 309,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Control Flow Best Practices",
    "question": "Instead of using a massive `switch` statement or a long `if/else if` chain to map specific keys to specific values (like translating country codes to names), what is a highly recommended alternative?",
    "code_snippet": null,
    "options": ["Using a `for` loop", "Using an Object Literal (Dictionary/Hash Map) for O(1) lookups", "Using nested ternary operators", "Using the `eval()` function"],
    "correct_answer": "Using an Object Literal (Dictionary/Hash Map) for O(1) lookups",
    "explanation": "Creating an object like `const names = { 'US': 'USA', 'UK': 'United Kingdom' };` and accessing it via `names['US']` is much cleaner, faster, and more readable than a giant switch statement."
  },
  {
    "id": 310,
    "level": "beginner",
    "module_id": "mod_04_control_flow",
    "module_name": "Control Flow (Making Decisions)",
    "type": "conceptual",
    "topic": "Ternary Operator",
    "question": "Why is it generally considered bad practice to use the ternary operator to execute functions with side effects (e.g., `isReady ? startEngine() : checkOil()`)?",
    "code_snippet": null,
    "options": ["It causes memory leaks", "It makes the code run slower", "It reduces readability; ternary operators are meant for assigning/returning values, not controlling program flow", "JavaScript will throw a SyntaxError"],
    "correct_answer": "It reduces readability; ternary operators are meant for assigning/returning values, not controlling program flow",
    "explanation": "While technically valid, using ternaries for side effects confuses other developers. Ternaries are best used as expressions that evaluate to a value (like `let status = isActive ? 'on' : 'off'`). For actions, use `if/else`."
  }
]
