[
  {
    "id": 711,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Closures",
    "question": "What is a 'Closure' in JavaScript?",
    "code_snippet": null,
    "options": ["A way to permanently lock a variable so it cannot be changed", "A function bundled together with references to its surrounding lexical environment", "A method to close a database connection", "A syntax error that occurs when brackets are mismatched"],
    "correct_answer": "A function bundled together with references to its surrounding lexical environment",
    "explanation": "A closure gives a function access to its outer scope's variables even after the outer function has finished executing. It 'closes over' those variables, keeping them alive in memory."
  },
  {
    "id": 712,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Closures",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function makeCounter() {\n  let count = 0;\n  return function() {\n    return ++count;\n  };\n}\nconst counter = makeCounter();\ncounter();\nconsole.log(counter());",
    "options": ["0", "1", "2", "undefined"],
    "correct_answer": "2",
    "explanation": "The first call to `counter()` increments `count` to 1. Because of the closure, the inner function remembers the `count` variable. The second call increments it again, making it 2."
  },
  {
    "id": 713,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Lexical Scope",
    "question": "What does 'Lexical Scope' mean in JavaScript?",
    "code_snippet": null,
    "options": ["Scope is determined dynamically at runtime based on how a function is called", "Scope is determined by the physical placement (nesting) of code in the source file", "Scope only applies to variables declared with `let`", "It is another name for Global Scope"],
    "correct_answer": "Scope is determined by the physical placement (nesting) of code in the source file",
    "explanation": "'Lexical' means 'related to text/source code'. An inner function can access variables of its outer function because of where it was physically written in the code, regardless of how it is called later."
  },
  {
    "id": 714,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Lexical Scope",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let a = 1;\nfunction outer() {\n  let b = 2;\n  function inner() {\n    let c = 3;\n    console.log(a + b + c);\n  }\n  inner();\n}\nouter();",
    "options": ["1", "3", "6", "ReferenceError"],
    "correct_answer": "6",
    "explanation": "The `inner` function looks for `c` in its own scope (finds 3). It looks for `b` in the `outer` scope (finds 2). It looks for `a` in the global scope (finds 1). 1 + 2 + 3 = 6."
  },
  {
    "id": 715,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Hoisting",
    "question": "What is 'Hoisting' in JavaScript?",
    "code_snippet": null,
    "options": ["Moving CSS files to the top of the HTML", "JavaScript's behavior of moving declarations to the top of the current scope during the compilation phase, before execution", "A method to speed up website loading times", "The process of converting JavaScript to TypeScript"],
    "correct_answer": "JavaScript's behavior of moving declarations to the top of the current scope during the compilation phase, before execution",
    "explanation": "Hoisting means that variable and function declarations are processed and moved to the top of their scope before the code actually runs line-by-line."
  },
  {
    "id": 716,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Hoisting",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(x);\nvar x = 10;",
    "options": ["10", "undefined", "null", "ReferenceError"],
    "correct_answer": "undefined",
    "explanation": "Variables declared with `var` are hoisted and automatically initialized with `undefined`. So the declaration is moved to the top, but the assignment (`x = 10`) stays on line 2."
  },
  {
    "id": 717,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Hoisting",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(y);\nlet y = 20;",
    "options": ["20", "undefined", "null", "ReferenceError"],
    "correct_answer": "ReferenceError",
    "explanation": "Unlike `var`, variables declared with `let` and `const` are hoisted but NOT initialized. Accessing them before their declaration line results in a ReferenceError."
  },
  {
    "id": 718,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Temporal Dead Zone",
    "question": "What is the 'Temporal Dead Zone' (TDZ)?",
    "code_snippet": null,
    "options": ["The time before a `var` is initialized", "The time between a `let`/`const` variable being hoisted and its initialization, where accessing it throws an error", "A memory leak area in the browser", "A deprecated feature from ES5"],
    "correct_answer": "The time between a `let`/`const` variable being hoisted and its initialization, where accessing it throws an error",
    "explanation": "The TDZ is the mechanism that prevents you from accessing `let` and `const` variables before the line of code where they are declared, helping to catch bugs early."
  },
  {
    "id": 719,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "code-fill-in-blank",
    "topic": "Temporal Dead Zone",
    "question": "What type of error is thrown if you try to access a `const` variable before its declaration?",
    "code_snippet": "console.log(a);\nconst a = 1;",
    "options": ["SyntaxError", "TypeError", "ReferenceError", "RangeError"],
    "correct_answer": "ReferenceError",
    "explanation": "Attempting to access a variable in the Temporal Dead Zone throws a ReferenceError, specifically indicating that the identifier cannot be accessed before initialization."
  },
  {
    "id": 720,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Function Hoisting",
    "question": "How do Function Declarations and Function Expressions differ regarding hoisting?",
    "code_snippet": null,
    "options": ["Both are fully hoisted", "Declarations are fully hoisted; Expressions are not (they act like `var`/`let` variables)", "Expressions are fully hoisted; Declarations are not", "Neither are hoisted"],
    "correct_answer": "Declarations are fully hoisted; Expressions are not (they act like `var`/`let` variables)",
    "explanation": "A standard `function myFunc() {}` is completely hoisted, meaning you can call it before it's written. A function expression (`const myFunc = function() {}`) is only hoisted as a variable declaration, not the function body."
  },
  {
    "id": 721,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Function Hoisting",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "greet();\n\nfunction greet() {\n  console.log('Hello');\n}",
    "options": ["Hello", "undefined", "TypeError", "ReferenceError"],
    "correct_answer": "Hello",
    "explanation": "Because `greet` is a Function Declaration, the entire function definition is hoisted to the top of the scope. It can be called before it appears in the code."
  },
  {
    "id": 722,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Function Hoisting",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "greet();\n\nconst greet = function() {\n  console.log('Hello');\n};",
    "options": ["Hello", "undefined", "TypeError", "ReferenceError"],
    "correct_answer": "ReferenceError",
    "explanation": "Because `greet` is declared with `const`, it is in the Temporal Dead Zone when `greet()` is called on line 1. It throws a ReferenceError."
  },
  {
    "id": 723,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "IIFE",
    "question": "What is an IIFE (Immediately Invoked Function Expression)?",
    "code_snippet": null,
    "options": ["A function that runs after 1 second", "A function that executes immediately right after it is created", "A function that loops infinitely", "A function that imports external files"],
    "correct_answer": "A function that executes immediately right after it is created",
    "explanation": "An IIFE runs as soon as the JS engine encounters it. It is created by wrapping a function expression in parentheses and immediately adding `()` at the end to invoke it."
  },
  {
    "id": 724,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "code-fill-in-blank",
    "topic": "IIFE",
    "question": "Fill in the blank to correctly write and invoke a standard IIFE.",
    "code_snippet": "_______ {\n  console.log('Runs immediately!');\n})();",
    "options": ["(function()", "function()", "=>", "new function()"],
    "correct_answer": "(function()",
    "explanation": "The outer parentheses `(function() { ... })` turn the function declaration into an expression. The trailing `()` immediately invokes it."
  },
  {
    "id": 725,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "IIFE",
    "question": "What is the primary historical use case for an IIFE?",
    "code_snippet": null,
    "options": ["To make code run faster", "To create a private scope and avoid polluting the global namespace with variables", "To handle async operations", "To define CSS styles"],
    "correct_answer": "To create a private scope and avoid polluting the global namespace with variables",
    "explanation": "Before ES6 introduced block-scoping with `let` and `const`, IIFEs were the standard way to encapsulate variables so they wouldn't leak into the global `window` object and cause naming collisions."
  },
  {
    "id": 726,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "IIFE",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "(function(a, b) {\n  console.log(a * b);\n})(3, 4);",
    "options": ["7", "12", "undefined", "Error"],
    "correct_answer": "12",
    "explanation": "The IIFE takes two parameters, `a` and `b`. It is immediately invoked with the arguments `3` and `4`. 3 * 4 equals 12."
  },
  {
    "id": 727,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Closures & Memory",
    "question": "How does the JavaScript Garbage Collector interact with closures?",
    "code_snippet": null,
    "options": ["It deletes all closures immediately to save memory", "It keeps the closed-over variables in memory as long as the inner function exists and might be called", "It converts closures to strings", "It throws a memory leak error"],
    "correct_answer": "It keeps the closed-over variables in memory as long as the inner function exists and might be called",
    "explanation": "Because the inner function holds a reference to the outer variables, the Garbage Collector cannot clean them up. They remain in memory until the inner function itself is destroyed."
  },
  {
    "id": 728,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Closures",
    "question": "What will be the exact output of the following code? (This is a 'Function Factory')",
    "code_snippet": "function multiplier(x) {\n  return function(y) {\n    return x * y;\n  };\n}\nconst double = multiplier(2);\nconsole.log(double(5));",
    "options": ["2", "5", "7", "10"],
    "correct_answer": "10",
    "explanation": "`multiplier(2)` returns a new function where `x` is permanently 'closed over' as 2. When we call `double(5)`, it calculates 2 * 5, which is 10."
  },
  {
    "id": 729,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Closures",
    "question": "What is a potential disadvantage of using closures extensively?",
    "code_snippet": null,
    "options": ["They make code run significantly faster", "They can lead to higher memory consumption if not managed properly, as variables are kept alive", "They cannot access outer variables", "They are deprecated in modern JavaScript"],
    "correct_answer": "They can lead to higher memory consumption if not managed properly, as variables are kept alive",
    "explanation": "If you create thousands of closures that hold references to large objects, those objects cannot be garbage collected, potentially leading to memory leaks in long-running applications."
  },
  {
    "id": 730,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Closures",
    "question": "What will be the exact output of the following code? (Closures with Objects)",
    "code_snippet": "function createWallet(initial) {\n  let balance = initial;\n  return {\n    spend(amount) { balance -= amount; },\n    getBalance() { return balance; }\n  };\n}\nconst myWallet = createWallet(100);\nmyWallet.spend(40);\nconsole.log(myWallet.getBalance());",
    "options": ["100", "40", "60", "undefined"],
    "correct_answer": "60",
    "explanation": "The `spend` and `getBalance` methods both share a closure over the `balance` variable. `spend(40)` reduces the closed-over `balance` from 100 to 60. `getBalance()` then returns 60."
  }
]
[
  {
    "id": 731,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "The 'this' keyword",
    "question": "In a standard web browser, what does the `this` keyword refer to in the global scope (outside of any function)?",
    "code_snippet": null,
    "options": ["undefined", "null", "The global `window` object", "The current HTML document"],
    "correct_answer": "The global `window` object",
    "explanation": "In the browser environment, the global object is `window`. Any variable declared globally with `var` becomes a property of `window`, and `this` at the top level points to it."
  },
  {
    "id": 732,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "The 'this' keyword",
    "question": "What will be the exact output of the following code in NON-STRICT mode?",
    "code_snippet": "function showThis() {\n  console.log(this);\n}\nshowThis();",
    "options": ["undefined", "null", "The global `window` object", "The `showThis` function itself"],
    "correct_answer": "The global `window` object",
    "explanation": "When a regular function is called without an object to the left of the dot (implicit binding), `this` defaults to the global object (`window` in browsers) in non-strict mode."
  },
  {
    "id": 733,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "The 'this' keyword",
    "question": "What will be the exact output of the following code in STRICT mode (`\"use strict\"`)?",
    "code_snippet": "\"use strict\";\nfunction showThis() {\n  console.log(this);\n}\nshowThis();",
    "options": ["The global `window` object", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "In strict mode, JavaScript disables 'default binding'. If a regular function is called without an explicit context, `this` remains `undefined` instead of falling back to the global object."
  },
  {
    "id": 734,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Implicit Binding",
    "question": "When a function is called as a method of an object (e.g., `user.getName()`), what does `this` refer to?",
    "code_snippet": null,
    "options": ["The global object", "The function itself", "The object to the left of the dot (`user`)", "undefined"],
    "correct_answer": "The object to the left of the dot (`user`)",
    "explanation": "This is called 'Implicit Binding'. The rule is simple: look at the object to the left of the dot at the time the function is called. That object becomes `this`."
  },
  {
    "id": 735,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Lost Context",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = { name: 'Alice', greet: function() { return this.name; } };\nconst sayHi = user.greet;\nconsole.log(sayHi());",
    "options": ["Alice", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "When you assign `user.greet` to a variable without calling it, it loses its connection to `user`. When `sayHi()` is called, there is no object to the left of the dot, so `this` defaults to the global object (where `this.name` is undefined)."
  },
  {
    "id": 736,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Arrow Functions & 'this'",
    "question": "How does an arrow function determine the value of `this`?",
    "code_snippet": null,
    "options": ["It looks at the object to the left of the dot", "It uses the global `window` object", "It inherits `this` from the surrounding lexical scope where it was defined", "It is always undefined"],
    "correct_answer": "It inherits `this` from the surrounding lexical scope where it was defined",
    "explanation": "Arrow functions do not have their own `this`. They permanently capture the `this` value of the enclosing function or global scope at the time they are written."
  },
  {
    "id": 737,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Arrow Function Trap",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = {\n  name: 'Bob',\n  greet: () => {\n    console.log(this.name);\n  }\n};\nuser.greet();",
    "options": ["Bob", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "Because `greet` is an arrow function, it ignores the `user` object. It inherits `this` from the global scope, where `this.name` does not exist, resulting in `undefined`."
  },
  {
    "id": 738,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Explicit Binding",
    "question": "What do the methods `call()`, `apply()`, and `bind()` all have in common?",
    "code_snippet": null,
    "options": ["They all execute the function immediately", "The first argument passed to all of them specifies the `this` context for the function", "They all return a new function", "They are used to create closures"],
    "correct_answer": "The first argument passed to all of them specifies the `this` context for the function",
    "explanation": "These are 'Explicit Binding' methods. They allow you to manually force `this` to be exactly the object you pass as the first argument."
  },
  {
    "id": 739,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "call vs apply",
    "question": "What is the main difference between `call()` and `apply()`?",
    "code_snippet": null,
    "options": ["`call` is for objects, `apply` is for arrays", "`call` takes arguments as a comma-separated list; `apply` takes arguments as a single array", "`call` is asynchronous, `apply` is synchronous", "There is no difference"],
    "correct_answer": "`call` takes arguments as a comma-separated list; `apply` takes arguments as a single array",
    "explanation": "Both invoke the function immediately with a specified `this`. The only difference is how you pass subsequent arguments: `func.call(obj, arg1, arg2)` vs `func.apply(obj, [arg1, arg2])`."
  },
  {
    "id": 740,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "call()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function greet(greeting, punctuation) {\n  console.log(`${greeting}, ${this.name}${punctuation}`);\n}\nconst user = { name: 'Alice' };\ngreet.call(user, 'Hello', '!');",
    "options": ["Hello, undefined!", "Hello, Alice!", "undefined, Alice!", "Error"],
    "correct_answer": "Hello, Alice!",
    "explanation": "`call` sets `this` to `user`. The subsequent arguments ('Hello' and '!') are passed to the `greeting` and `punctuation` parameters respectively."
  },
  {
    "id": 741,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "apply()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function sum(a, b, c) {\n  return a + b + c;\n}\nconsole.log(sum.apply(null, [10, 20, 30]));",
    "options": ["60", "102030", "NaN", "Error"],
    "correct_answer": "60",
    "explanation": "`apply` takes the array `[10, 20, 30]` and spreads it into the arguments `a`, `b`, and `c`. The first argument `null` means `this` defaults to the global object (which we don't use here). 10 + 20 + 30 = 60."
  },
  {
    "id": 742,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "bind()",
    "question": "How does `bind()` differ from `call()` and `apply()`?",
    "code_snippet": null,
    "options": ["`bind` executes the function immediately", "`bind` does NOT execute the function; it returns a brand new function with `this` permanently bound", "`bind` only works with arrow functions", "`bind` is deprecated"],
    "correct_answer": "`bind` does NOT execute the function; it returns a brand new function with `this` permanently bound",
    "explanation": "`bind` is used when you want to pass a function around (like as a callback) but ensure it keeps the correct `this` context when it eventually runs."
  },
  {
    "id": 743,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "bind()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const module = {\n  x: 42,\n  getX: function() { return this.x; }\n};\nconst unboundGetX = module.getX;\nconst boundGetX = unboundGetX.bind(module);\nconsole.log(boundGetX());",
    "options": ["undefined", "42", "0", "Error"],
    "correct_answer": "42",
    "explanation": "Normally, `unboundGetX()` would lose context. But `bind(module)` creates a new function where `this` is permanently locked to `module`. Calling it returns 42."
  },
  {
    "id": 744,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Partial Application",
    "question": "Besides binding `this`, what other common use case does `bind()` have?",
    "code_snippet": null,
    "options": ["Error handling", "Partial Application / Currying (presetting some arguments for later)", "Memory management", "Asynchronous looping"],
    "correct_answer": "Partial Application / Currying (presetting some arguments for later)",
    "explanation": "You can use `bind` to preset arguments. E.g., `const add5 = add.bind(null, 5);`. When you later call `add5(10)`, it passes 5 and 10 to the original `add` function."
  },
  {
    "id": 745,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "bind() re-binding",
    "question": "What will be the exact output of the following code? (Can you re-bind a bound function?)",
    "code_snippet": "function show() { console.log(this.name); }\nconst obj1 = { name: 'A' };\nconst obj2 = { name: 'B' };\nconst bound1 = show.bind(obj1);\nconst bound2 = bound1.bind(obj2);\nbound2();",
    "options": ["A", "B", "undefined", "Error"],
    "correct_answer": "A",
    "explanation": "Once a function is bound with `bind()`, its `this` context is permanently locked. Calling `bind()` again on an already bound function does nothing; it ignores `obj2` and still uses `obj1`."
  },
  {
    "id": 746,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "this in DOM Events",
    "question": "In a standard DOM event listener attached via `addEventListener`, what does `this` refer to inside the callback?",
    "code_snippet": null,
    "options": ["The `window` object", "The element that the event listener is attached to (e.currentTarget)", "The specific child element that was clicked (e.target)", "The event object itself"],
    "correct_answer": "The element that the event listener is attached to (e.currentTarget)",
    "explanation": "By default, `addEventListener` binds `this` to the element it was called on. (Note: Arrow function callbacks will ignore this and use lexical `this`)."
  },
  {
    "id": 747,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "this in Classes",
    "question": "What does `this` refer to inside the `constructor` of an ES6 Class?",
    "code_snippet": null,
    "options": ["The class blueprint itself", "The newly created instance of the object", "The global window", "undefined"],
    "correct_answer": "The newly created instance of the object",
    "explanation": "When you use the `new` keyword, JavaScript creates a blank object, sets `this` to point to that new object, and then runs the constructor to add properties to it."
  },
  {
    "id": 748,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Class Method Trap",
    "question": "What will happen when this code is executed?",
    "code_snippet": "class Button {\n  constructor() { this.clicked = false; }\n  handleClick() { this.clicked = true; }\n}\nconst btn = new Button();\nsetTimeout(btn.handleClick, 100);",
    "options": ["It sets btn.clicked to true", "It throws a TypeError because 'this' is undefined in strict mode (classes are strict by default)", "It sets window.clicked to true", "It logs undefined"],
    "correct_answer": "It throws a TypeError because 'this' is undefined in strict mode (classes are strict by default)",
    "explanation": "ES6 classes run in strict mode automatically. Passing `btn.handleClick` to `setTimeout` loses the context. When it fires, `this` is undefined, and trying to set `undefined.clicked = true` throws a TypeError."
  },
  {
    "id": 749,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Block Scope",
    "question": "How does `let` behave inside a `for` loop compared to `var`?",
    "code_snippet": null,
    "options": ["They behave exactly the same", "`let` creates a brand new binding for the variable on every single iteration; `var` creates only one shared variable for the whole loop", "`var` is block-scoped, `let` is function-scoped", "`let` cannot be used in for loops"],
    "correct_answer": "`let` creates a brand new binding for the variable on every single iteration; `var` creates only one shared variable for the whole loop",
    "explanation": "This is why `let` fixes the classic asynchronous loop trap. Each iteration gets its own private copy of the variable."
  },
  {
    "id": 750,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "The var Loop Trap",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    "options": ["0, 1, 2", "3, 3, 3", "0, 0, 0", "undefined, undefined, undefined"],
    "correct_answer": "3, 3, 3",
    "explanation": "Because `var` is function-scoped, there is only ONE `i` shared by all 3 callbacks. By the time the callbacks run, the loop has finished and `i` is 3."
  },
  {
    "id": 751,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "The let Loop Fix",
    "question": "What will be the exact output if we change `var` to `let` in the previous code?",
    "code_snippet": "for (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    "options": ["0, 1, 2", "3, 3, 3", "0, 0, 0", "undefined"],
    "correct_answer": "0, 1, 2",
    "explanation": "Because `let` is block-scoped, each iteration gets its own private `i`. The callback closes over the specific `i` for that exact iteration."
  },
  {
    "id": 752,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Variable Shadowing",
    "question": "What is 'Variable Shadowing'?",
    "code_snippet": null,
    "options": ["When a variable is deleted from memory", "When an inner scope declares a variable with the same name as one in an outer scope, effectively hiding the outer one", "When two variables share the same memory address", "When a variable is declared twice in the same scope"],
    "correct_answer": "When an inner scope declares a variable with the same name as one in an outer scope, effectively hiding the outer one",
    "explanation": "If you have `let x = 10` globally, and `let x = 20` inside a function, the inner `x` 'shadows' the outer `x`. Inside the function, any reference to `x` will be 20."
  },
  {
    "id": 753,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Module Pattern",
    "question": "Before ES6 Modules (`import`/`export`), how did developers create private variables and public methods using closures?",
    "code_snippet": null,
    "options": ["Using the `private` keyword", "The Revealing Module Pattern (using an IIFE that returns an object with methods that close over private variables)", "Using `Object.freeze()`", "Using `try...catch` blocks"],
    "correct_answer": "The Revealing Module Pattern (using an IIFE that returns an object with methods that close over private variables)",
    "explanation": "By wrapping code in an IIFE, variables declared inside are private. You then return an object containing functions that have access to those private variables via closures, exposing a public API."
  },
  {
    "id": 754,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Nested Functions & 'this'",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = {\n  name: 'Alice',\n  doStuff: function() {\n    function inner() { console.log(this.name); }\n    inner();\n  }\n};\nobj.doStuff();",
    "options": ["Alice", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "Even though `inner` is defined inside a method, it is called as a standalone function (`inner()`). Therefore, it loses the `obj` context and `this` defaults to the global object."
  },
  {
    "id": 755,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "The 'self = this' pattern",
    "question": "Before arrow functions existed, what was the common workaround to preserve `this` context inside nested callbacks?",
    "code_snippet": null,
    "options": ["Using `bind()` on every function", "Assigning `const self = this;` (or `var that = this;`) in the outer function and using `self` inside the inner callback", "Using the `new` keyword", "Using `eval()`"],
    "correct_answer": "Assigning `const self = this;` (or `var that = this;`) in the outer function and using `self` inside the inner callback",
    "explanation": "Because closures capture variables from the outer scope, developers would save the correct `this` reference to a variable like `self` or `that`, and use that variable inside the callback instead of the `this` keyword."
  },
  {
    "id": 756,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Constructors & 'new'",
    "question": "What happens if you call a constructor function WITHOUT the `new` keyword?",
    "code_snippet": null,
    "options": ["It throws a SyntaxError", "It returns undefined", "In non-strict mode, `this` becomes the global window, and you accidentally pollute the global scope with properties", "It automatically adds the `new` keyword for you"],
    "correct_answer": "In non-strict mode, `this` becomes the global window, and you accidentally pollute the global scope with properties",
    "explanation": "Without `new`, it acts like a normal function. `this` defaults to `window`. If the constructor does `this.name = 'Alice'`, it actually creates `window.name = 'Alice'`, which is a massive bug."
  },
  {
    "id": 757,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Arrow Functions as Constructors",
    "question": "Can you use the `new` keyword with an arrow function?",
    "code_snippet": null,
    "options": ["Yes, it works exactly like a regular function", "No, it will throw a TypeError because arrow functions do not have their own `this` or `prototype`", "Yes, but only in strict mode", "Yes, but it ignores the arguments"],
    "correct_answer": "No, it will throw a TypeError because arrow functions do not have their own `this` or `prototype`",
    "explanation": "Arrow functions cannot be used as constructors. They lack the internal `[[Construct]]` method and the `prototype` property required by the `new` keyword."
  },
  {
    "id": 758,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Scope Chain",
    "question": "When a variable is referenced, how does the JavaScript engine find its value?",
    "code_snippet": null,
    "options": ["It searches the global scope first, then goes inward", "It searches the current local scope, then steps outward to the parent scope, continuing until it hits the global scope", "It searches randomly", "It only searches the global scope"],
    "correct_answer": "It searches the current local scope, then steps outward to the parent scope, continuing until it hits the global scope",
    "explanation": "This is the Scope Chain. It always looks 'up' the chain of nested functions. If it reaches the global scope and still hasn't found it, it throws a ReferenceError."
  },
  {
    "id": 759,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Scope Chain",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let x = 10;\nfunction outer() {\n  let x = 20;\n  function inner() {\n    let x = 30;\n    console.log(x);\n  }\n  inner();\n}\nouter();",
    "options": ["10", "20", "30", "undefined"],
    "correct_answer": "30",
    "explanation": "The `inner` function has its own local variable `x = 30`. Because it finds `x` in its own immediate scope, it uses that value and doesn't need to look up the scope chain."
  },
  {
    "id": 760,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Dynamic vs Lexical Scope",
    "question": "JavaScript uses Lexical Scoping. What would 'Dynamic Scoping' mean?",
    "code_snippet": null,
    "options": ["Scope is determined by where functions are called at runtime, not where they are written", "Scope changes based on the browser window size", "Variables can change their data type dynamically", "Scope is determined by the `this` keyword"],
    "correct_answer": "Scope is determined by where functions are called at runtime, not where they are written",
    "explanation": "In a dynamically scoped language, a function would look at the variables of the function that *called* it. JavaScript doesn't do this; it looks at where the function was *written* (Lexical). (Note: The `this` keyword is the one exception in JS that behaves somewhat dynamically!)."
  }
]
[
  {
    "id": 761,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Currying",
    "question": "What is 'Currying' in JavaScript?",
    "code_snippet": null,
    "options": ["Splitting a string into characters", "Transforming a function that takes multiple arguments into a sequence of nested functions that each take a single argument", "Caching the results of a function", "Converting an arrow function to a regular function"],
    "correct_answer": "Transforming a function that takes multiple arguments into a sequence of nested functions that each take a single argument",
    "explanation": "Currying allows you to partially apply arguments. Instead of `add(2, 3)`, you write `add(2)(3)`. It's heavily used in functional programming and libraries like Redux."
  },
  {
    "id": 762,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Currying",
    "question": "What will be the exact output of the following curried function?",
    "code_snippet": "const multiply = a => b => a * b;\nconst double = multiply(2);\nconsole.log(double(5));",
    "options": ["2", "5", "7", "10"],
    "correct_answer": "10",
    "explanation": "`multiply(2)` returns a new function where `a` is closed over as 2. We assign this to `double`. When we call `double(5)`, it executes `2 * 5`, returning 10."
  },
  {
    "id": 763,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Memoization",
    "question": "What is 'Memoization' and how do closures enable it?",
    "code_snippet": null,
    "options": ["Deleting old functions to save memory", "Caching the results of expensive function calls and returning the cached result when the same inputs occur again, using a closure to hold the cache", "Running functions in parallel", "Converting synchronous code to asynchronous"],
    "correct_answer": "Caching the results of expensive function calls and returning the cached result when the same inputs occur again, using a closure to hold the cache",
    "explanation": "By wrapping a function in an outer function that holds a `cache` object, the inner function can check the cache before doing heavy math. The closure keeps the `cache` alive between calls."
  },
  {
    "id": 764,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "code-fill-in-blank",
    "topic": "Memoization",
    "question": "Fill in the blank to correctly store the calculated result in the cache for future use.",
    "code_snippet": "function memoize(fn) {\n  const cache = {};\n  return function(arg) {\n    if (cache[arg] !== undefined) return cache[arg];\n    const result = fn(arg);\n    _______ = result;\n    return result;\n  };\n}",
    "options": ["cache.result", "cache[arg]", "cache.fn", "this.cache"],
    "correct_answer": "cache[arg]",
    "explanation": "To memoize, you use the input `arg` as the key in the `cache` object, and store the computed `result` as the value. Next time the same `arg` is passed, it returns instantly."
  },
  {
    "id": 765,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Function Arity",
    "question": "What does the `.length` property of a function return?",
    "code_snippet": null,
    "options": ["The number of arguments actually passed to the function", "The number of characters in the function's name", "The number of parameters expected by the function (excluding those with default values)", "The memory size of the function in bytes"],
    "correct_answer": "The number of parameters expected by the function (excluding those with default values)",
    "explanation": "Function arity is the number of arguments a function expects. `function(a, b, c) {}.length` is 3. However, `function(a, b, c = 3) {}.length` is 2, because default parameters stop the count."
  },
  {
    "id": 766,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Function Arity",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function test(a, b, c = 3, d) {\n  console.log('Hello');\n}\nconsole.log(test.length);",
    "options": ["4", "3", "2", "0"],
    "correct_answer": "2",
    "explanation": "This is a tricky JS quirk! The `.length` property counts parameters up to the FIRST parameter with a default value. Since `c` has a default value of 3, the count stops there. It only counts `a` and `b`."
  },
  {
    "id": 767,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "The 'arguments' object",
    "question": "What is the `arguments` object in JavaScript?",
    "code_snippet": null,
    "options": ["A standard Array containing all passed arguments", "An array-like object available inside all regular functions that contains the values of the arguments passed to that function", "A global variable containing all variables in the program", "A method to parse JSON"],
    "correct_answer": "An array-like object available inside all regular functions that contains the values of the arguments passed to that function",
    "explanation": "`arguments` looks like an array (it has a `.length` and indices) but lacks array methods like `.map()` or `.forEach()`. In modern JS, Rest parameters (`...args`) are preferred because they create a real Array."
  },
  {
    "id": 768,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "The 'arguments' object",
    "question": "What happens if you try to use the `arguments` object inside an arrow function?",
    "code_snippet": null,
    "options": ["It works exactly like in a regular function", "It throws a SyntaxError", "It does not have its own `arguments` object; it inherits it from the enclosing lexical scope", "It returns an empty array"],
    "correct_answer": "It does not have its own `arguments` object; it inherits it from the enclosing lexical scope",
    "explanation": "Just like the `this` keyword, arrow functions do not bind their own `arguments` object. If you use `arguments` inside an arrow function, it looks up the scope chain to find the `arguments` of the nearest parent regular function."
  },
  {
    "id": 769,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Recursion",
    "question": "What is a 'base case' in a recursive function?",
    "code_snippet": null,
    "options": ["The first argument passed to the function", "The condition that stops the recursion and prevents an infinite loop", "The return value of the function", "The global scope"],
    "correct_answer": "The condition that stops the recursion and prevents an infinite loop",
    "explanation": "Every recursive function must have a base case (e.g., `if (n === 0) return 1;`). Without it, the function will call itself forever until the call stack overflows."
  },
  {
    "id": 770,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Recursion",
    "question": "What error is thrown if a recursive function lacks a base case and runs infinitely?",
    "code_snippet": "function loop() { loop(); }\nloop();",
    "options": ["SyntaxError", "TypeError", "RangeError: Maximum call stack size exceeded", "ReferenceError"],
    "correct_answer": "RangeError: Maximum call stack size exceeded",
    "explanation": "Every function call adds a frame to the Call Stack. If the stack grows beyond the engine's limit (usually around 10,000 frames), it throws a RangeError to prevent the browser/node process from crashing."
  },
  {
    "id": 771,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Higher-Order Functions",
    "question": "What defines a 'Higher-Order Function' in JavaScript?",
    "code_snippet": null,
    "options": ["A function declared at the top of the file", "A function that takes one or more functions as arguments, OR returns a function as its result", "A function that uses the `async` keyword", "A function that has more than 5 parameters"],
    "correct_answer": "A function that takes one or more functions as arguments, OR returns a function as its result",
    "explanation": "Functions in JS are first-class citizens. Methods like `.map()`, `.filter()`, and `.reduce()` are higher-order functions because they take a callback function as an argument."
  },
  {
    "id": 772,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Pure Functions",
    "question": "What is a 'side effect' in the context of functions?",
    "code_snippet": null,
    "options": ["When a function returns undefined", "When a function modifies external state, mutates arguments, or performs I/O (like network requests or DOM manipulation)", "When a function throws an error", "When a function takes too long to execute"],
    "correct_answer": "When a function modifies external state, mutates arguments, or performs I/O (like network requests or DOM manipulation)",
    "explanation": "A 'Pure Function' has NO side effects. Given the same inputs, it ALWAYS returns the same output, and it doesn't alter anything outside its own scope. Pure functions are the foundation of React and Redux."
  },
  {
    "id": 773,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Hoisting Quirks",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(foo);\nvar foo = function() { return 1; };",
    "options": ["function() { return 1; }", "1", "undefined", "ReferenceError"],
    "correct_answer": "undefined",
    "explanation": "This is a Function Expression assigned to a `var`. Only the variable declaration (`var foo`) is hoisted and initialized to `undefined`. The actual function assignment happens on line 2. Therefore, line 1 logs `undefined`."
  },
  {
    "id": 774,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Closure Loop Trap",
    "question": "What will be the exact output of the following classic interview code?",
    "code_snippet": "const funcs = [];\nfor (var i = 0; i < 3; i++) {\n  funcs[i] = function() { return i; };\n}\nconsole.log(funcs[0]());",
    "options": ["0", "1", "2", "3"],
    "correct_answer": "3",
    "explanation": "Because `var` is function-scoped, there is only ONE `i` shared by all 3 functions. By the time `funcs[0]()` is called, the loop has finished and `i` is 3. All functions return 3."
  },
  {
    "id": 775,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Function.name",
    "question": "What does the `.name` property of a function return?",
    "code_snippet": null,
    "options": ["The code inside the function as a string", "The name of the function as a string", "The number of parameters", "The memory address"],
    "correct_answer": "The name of the function as a string",
    "explanation": "Every function has a read-only `.name` property. For `function myFunc() {}`, `myFunc.name` is `'myFunc'`. For anonymous functions, it might be an empty string, unless ES6 name inference applies."
  },
  {
    "id": 776,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "ES6 Name Inference",
    "question": "What will be the exact output of the following code? (Notice the anonymous function!)",
    "code_snippet": "const calculateTotal = function() { return 42; };\nconsole.log(calculateTotal.name);",
    "options": ["'' (empty string)", "'calculateTotal'", "'function'", "undefined"],
    "correct_answer": "'calculateTotal'",
    "explanation": "In ES6, if you assign an anonymous function to a variable, the JavaScript engine infers the function's name from the variable name. Therefore, `.name` returns `'calculateTotal'`."
  },
  {
    "id": 777,
    "level": "intermediate",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Rest vs Arguments",
    "question": "Why is the Rest parameter (`...args`) generally preferred over the legacy `arguments` object?",
    "code_snippet": null,
    "options": ["It runs significantly faster", "It creates a true Array (allowing .map/.filter), works in arrow functions, and makes the function signature clearer", "It allows the function to return multiple values", "It automatically removes duplicate arguments"],
    "correct_answer": "It creates a true Array (allowing .map/.filter), works in arrow functions, and makes the function signature clearer",
    "explanation": "`arguments` is an awkward array-like object that doesn't work in arrow functions. Rest parameters (`...args`) give you a real, modern JavaScript Array right in the parameter list."
  },
  {
    "id": 778,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "IIFE Return Values",
    "question": "Can an IIFE (Immediately Invoked Function Expression) return a value that you can use later?",
    "code_snippet": null,
    "options": ["No, IIFEs are strictly for side effects and cannot return values", "Yes, if you assign the IIFE to a variable (e.g., `const x = (function() { return 5; })();`)", "Only if it is an async IIFE", "Only if it returns a Promise"],
    "correct_answer": "Yes, if you assign the IIFE to a variable (e.g., `const x = (function() { return 5; })();`)",
    "explanation": "An IIFE is just a function that runs immediately. Like any function, it can return a value. If you wrap it in an assignment, that variable receives the returned value."
  },
  {
    "id": 779,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "conceptual",
    "topic": "Tail Call Optimization",
    "question": "What is 'Tail Call Optimization' (TCO) in JavaScript?",
    "code_snippet": null,
    "options": ["A way to make loops run faster", "An engine optimization where if a function's last action is calling another function (a tail call), the engine reuses the current stack frame instead of creating a new one, preventing stack overflow in deep recursion", "A method to optimize CSS rendering", "A way to automatically cache function results"],
    "correct_answer": "An engine optimization where if a function's last action is calling another function (a tail call), the engine reuses the current stack frame instead of creating a new one, preventing stack overflow in deep recursion",
    "explanation": "TCO allows infinite recursive loops without blowing the call stack. Note: Currently, only Safari's JavaScriptCore fully supports TCO. V8 (Chrome/Node) has it behind a flag or disabled due to debugging complexities."
  },
  {
    "id": 780,
    "level": "advanced",
    "module_id": "mod_12_advanced_functions",
    "module_name": "Advanced Functions & Scope",
    "type": "output-prediction",
    "topic": "Closure Memory",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function buildFun() {\n  const arr = [];\n  for (let i = 0; i < 3; i++) {\n    arr.push(function() { console.log(i); });\n  }\n  return arr;\n}\nconst funcs = buildFun();\nfuncs[1]();",
    "options": ["0", "1", "2", "3"],
    "correct_answer": "1",
    "explanation": "Because we used `let`, each iteration of the loop creates a brand new block scope with its own `i`. The function pushed at index 1 closes over the `i` that was exactly `1` during that specific iteration."
  }
]
