[
  {
    "id": 901,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Garbage Collection",
    "question": "What is the primary algorithm used by modern JavaScript engines (like V8) for Garbage Collection?",
    "code_snippet": null,
    "options": ["Reference Counting", "Mark and Sweep", "First In, First Out (FIFO)", "Manual Memory Management"],
    "correct_answer": "Mark and Sweep",
    "explanation": "The 'Mark and Sweep' algorithm starts from 'root' objects (like the global window), 'marks' all objects reachable from them, and then 'sweeps' (deletes) any memory that wasn't marked. This elegantly handles circular references that break older 'Reference Counting' systems."
  },
  {
    "id": 902,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Garbage Collection",
    "question": "What makes an object 'eligible' for Garbage Collection in JavaScript?",
    "code_snippet": null,
    "options": ["When it is declared with `var`", "When it has no reachable references from the root (global) scope", "When it is older than 5 seconds", "When it is inside a function that has finished executing"],
    "correct_answer": "When it has no reachable references from the root (global) scope",
    "explanation": "If the Garbage Collector cannot find a 'path' from the global root to an object (e.g., all variables pointing to it have been reassigned or gone out of scope), the object is considered unreachable and its memory is reclaimed."
  },
  {
    "id": 903,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Memory Leaks",
    "question": "What is a 'Memory Leak' in JavaScript?",
    "code_snippet": null,
    "options": ["When the browser crashes immediately", "When memory that is no longer needed is not returned to the operating system, usually due to accidental lingering references", "When a variable is declared but never used", "When you use too many `let` variables"],
    "correct_answer": "When memory that is no longer needed is not returned to the operating system, usually due to accidental lingering references",
    "explanation": "Because JS has automatic garbage collection, memory leaks happen when you accidentally keep a reference to an object you no longer need (like an uncleared interval, a forgotten closure, or a detached DOM node), preventing the GC from cleaning it up."
  },
  {
    "id": 904,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Memory Leaks",
    "question": "Fill in the blank to correctly prevent a memory leak caused by a recurring timer.",
    "code_snippet": "const intervalId = setInterval(() => updateUI(), 1000);\n\n// Later, when the component is destroyed:\n_______(intervalId);",
    "options": ["stopInterval", "clearInterval", "removeInterval", "deleteInterval"],
    "correct_answer": "clearInterval",
    "explanation": "If you navigate away from a page but forget to clear an interval, the callback and all the variables it closes over will remain in memory forever. Always use `clearInterval` or `clearTimeout` in cleanup functions."
  },
  {
    "id": 905,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Browser Rendering",
    "question": "What is a 'Reflow' (or Layout) in the browser rendering pipeline?",
    "code_snippet": null,
    "options": ["Changing the colors of elements", "The process of recalculating the positions and geometries of elements to re-render part or all of the page", "Downloading new CSS files", "Executing JavaScript on the main thread"],
    "correct_answer": "The process of recalculating the positions and geometries of elements to re-render part or all of the page",
    "explanation": "Reflows are incredibly expensive for the CPU. They happen when you change an element's size, position, or when you read layout properties (like `offsetHeight`). Batching DOM reads and writes is crucial to avoid 'thrashing' the layout."
  },
  {
    "id": 906,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Browser Rendering",
    "question": "What is a 'Repaint' in the browser rendering pipeline?",
    "code_snippet": null,
    "options": ["Recalculating the layout of the page", "Updating the pixels on the screen when visual changes occur that DO NOT affect the layout (e.g., changing background-color or visibility)", "Compiling JavaScript to machine code", "Fetching images from the server"],
    "correct_answer": "Updating the pixels on the screen when visual changes occur that DO NOT affect the layout (e.g., changing background-color or visibility)",
    "explanation": "Repaints are less expensive than Reflows, but still cost performance. Changing properties like `color`, `background-color`, or `visibility` triggers a repaint but skips the expensive layout recalculation."
  },
  {
    "id": 907,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "DOM Performance",
    "question": "What is a `DocumentFragment` and why is it useful for performance?",
    "code_snippet": null,
    "options": ["A lightweight, invisible DOM node used to batch multiple element insertions, triggering only ONE reflow instead of many", "A way to split the HTML file into multiple files", "A deprecated HTML tag", "A method to hide elements from the user"],
    "correct_answer": "A lightweight, invisible DOM node used to batch multiple element insertions, triggering only ONE reflow instead of many",
    "explanation": "Appending 100 items to the live DOM causes 100 reflows. Appending 100 items to a `DocumentFragment` (which is not in the live DOM) causes 0 reflows. Appending the fragment to the live DOM causes exactly 1 reflow."
  },
  {
    "id": 908,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "DOM Performance",
    "question": "Fill in the blank to correctly create a DocumentFragment for batching DOM updates.",
    "code_snippet": "const fragment = document._______();\nfor (let i = 0; i < 100; i++) {\n  fragment.appendChild(createListItem(i));\n}\ndocument.querySelector('ul').appendChild(fragment);",
    "options": ["createElement", "createNode", "createDocumentFragment", "createBatch"],
    "correct_answer": "createDocumentFragment",
    "explanation": "`document.createDocumentFragment()` creates an empty, lightweight container. You can append children to it, and when you finally append the fragment to the real DOM, only the fragment's children are inserted, not the fragment itself."
  },
  {
    "id": 909,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (XSS)",
    "question": "What does XSS stand for in web security?",
    "code_snippet": null,
    "options": ["Cross-Server Scripting", "Cross-Site Scripting", "XML Standard Syntax", "Quick Site Security"],
    "correct_answer": "Cross-Site Scripting",
    "explanation": "XSS is a vulnerability where an attacker injects malicious client-side scripts (usually JavaScript) into web pages viewed by other users. It is one of the most common and dangerous web vulnerabilities."
  },
  {
    "id": 910,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (XSS)",
    "question": "Which of the following actions is the MOST likely to cause a Stored XSS vulnerability?",
    "code_snippet": null,
    "options": ["Using `textContent` to display user input", "Taking user input from a comment form and rendering it directly using `innerHTML` without sanitization", "Using HTTPS for all network requests", "Storing data in `localStorage`"],
    "correct_answer": "Taking user input from a comment form and rendering it directly using `innerHTML` without sanitization",
    "explanation": "If a user submits `<script>stealCookies()</script>` in a comment, and you render it with `innerHTML`, the script executes in the browser of EVERY user who views that comment. This is a classic Stored XSS attack."
  },
  {
    "id": 911,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Security (XSS Prevention)",
    "question": "To safely display user-generated text on the page without risking XSS, which property should you use instead of `innerHTML`?",
    "code_snippet": "const userInput = '<script>alert(\"Hacked!\")</script>';\ndocument.getElementById('output')._______ = userInput;",
    "options": ["innerHTML", "textContent", "outerHTML", "insertAdjacentHTML"],
    "correct_answer": "textContent",
    "explanation": "`textContent` treats the input strictly as plain text. The browser will literally display the characters `<script>...` on the screen, completely neutralizing the attack."
  },
  {
    "id": 912,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (CSP)",
    "question": "What is a Content Security Policy (CSP)?",
    "code_snippet": null,
    "options": ["A JavaScript library for encrypting data", "An HTTP response header that allows website admins to declare which resources (scripts, styles, images) the browser is allowed to load", "A CSS framework for secure layouts", "A method to hash passwords"],
    "correct_answer": "An HTTP response header that allows website admins to declare which resources (scripts, styles, images) the browser is allowed to load",
    "explanation": "CSP is a powerful defense-in-depth mechanism. By setting a CSP header, you can tell the browser to block all inline scripts and only load JavaScript from your own domain, effectively neutralizing most XSS attacks."
  },
  {
    "id": 913,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Security (CSP)",
    "question": "Which HTTP header is used to define a Content Security Policy?",
    "code_snippet": "HTTP/1.1 200 OK\n_______: script-src 'self' https://apis.example.com;",
    "options": ["X-Frame-Options", "Content-Security-Policy", "Access-Control-Allow-Origin", "Strict-Transport-Security"],
    "correct_answer": "Content-Security-Policy",
    "explanation": "The `Content-Security-Policy` header is the standard way to instruct the browser on what is allowed. The example above restricts script execution to the current origin ('self') and one specific API domain."
  },
  {
    "id": 914,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (Sanitization)",
    "question": "If you are building a rich-text editor and MUST allow users to submit HTML (like `<b>` or `<a>` tags), how do you prevent XSS?",
    "code_snippet": null,
    "options": ["Use `innerHTML` and hope the users are nice", "Strip all tags using a simple Regex", "Use a trusted sanitization library like DOMPurify to parse the HTML and strip out dangerous elements like `<script>` and event handlers before rendering", "Convert the HTML to a JSON string"],
    "correct_answer": "Use a trusted sanitization library like DOMPurify to parse the HTML and strip out dangerous elements like `<script>` and event handlers before rendering",
    "explanation": "Writing your own Regex to filter HTML is notoriously difficult and prone to bypasses. Libraries like DOMPurify use the browser's own DOM parser to safely remove malicious payloads while keeping safe formatting tags."
  },
  {
    "id": 915,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Event Delegation)",
    "question": "Why is 'Event Delegation' considered a best practice for performance when dealing with a list of 1,000 items?",
    "code_snippet": null,
    "options": ["It makes the items load faster from the server", "It uses less memory and reduces initialization time by attaching ONE event listener to the parent `<ul>` instead of 1,000 listeners to the `<li>` elements", "It prevents the user from clicking too fast", "It automatically paginates the list"],
    "correct_answer": "It uses less memory and reduces initialization time by attaching ONE event listener to the parent `<ul>` instead of 1,000 listeners to the `<li>` elements",
    "explanation": "Every event listener consumes memory. Attaching 1,000 listeners causes a massive memory footprint and a slow initial render. One listener on the parent leverages event bubbling to handle all clicks efficiently."
  },
  {
    "id": 916,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Throttle vs Debounce)",
    "question": "What is the difference between 'Throttling' and 'Debouncing' a function?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "Throttling ensures a function runs at most once every X milliseconds; Debouncing ensures a function only runs after a pause of X milliseconds", "Throttling is for CSS, Debouncing is for JS", "Throttling speeds up code, Debouncing slows it down"],
    "correct_answer": "Throttling ensures a function runs at most once every X milliseconds; Debouncing ensures a function only runs after a pause of X milliseconds",
    "explanation": "Use Throttling for continuous events like scrolling or resizing (e.g., update the UI every 100ms). Use Debouncing for discrete events like search input or window resizing (e.g., wait until the user stops typing for 500ms before firing the API call)."
  },
  {
    "id": 917,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Debouncing)",
    "question": "Which scenario is the PERFECT use case for a Debounced function?",
    "code_snippet": null,
    "options": ["Updating a 'scroll progress' bar at the top of the page", "An autocomplete search bar that fetches API results as the user types", "Tracking mouse coordinates for a drawing app", "Animating an element across the screen"],
    "correct_answer": "An autocomplete search bar that fetches API results as the user types",
    "explanation": "You don't want to fire an API call for every single keystroke ('a', 'ap', 'app', 'appl', 'apple'). A debounce function waits until the user pauses typing for, say, 300ms, before firing the API call with the final string."
  },
  {
    "id": 918,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Memory (WeakRef)",
    "question": "What is a `WeakRef` in modern JavaScript?",
    "code_snippet": null,
    "options": ["A reference that throws an error if the object is deleted", "An object that holds a weak reference to another object, allowing it to be garbage collected even if the WeakRef still exists", "A deprecated way to declare variables", "A reference to a Web Worker"],
    "correct_answer": "An object that holds a weak reference to another object, allowing it to be garbage collected even if the WeakRef still exists",
    "explanation": "Normally, if variable A points to object B, B cannot be garbage collected. A `WeakRef` allows you to point to B without preventing its garbage collection. You can check if it's still alive using `.deref()`."
  },
  {
    "id": 919,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Memory (FinalizationRegistry)",
    "question": "What is the purpose of the `FinalizationRegistry` API?",
    "code_snippet": null,
    "options": ["To manually trigger the Garbage Collector", "To register callback functions that will be invoked when specific objects are garbage collected", "To track how much memory your app is using", "To prevent objects from being garbage collected"],
    "correct_answer": "To register callback functions that will be invoked when specific objects are garbage collected",
    "explanation": "It allows you to perform cleanup tasks (like releasing external resources or closing a WebRTC connection) exactly when an object is reclaimed by the Garbage Collector, working hand-in-hand with `WeakRef`."
  },
  {
    "id": 920,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (eval)",
    "question": "Why is using the `eval()` function considered a massive security risk and a performance killer?",
    "code_snippet": null,
    "options": ["It makes the code run too fast", "It executes arbitrary strings as code, opening the door to code injection/XSS, and prevents the JS engine from optimizing the code ahead of time", "It only works in strict mode", "It deletes the global window object"],
    "correct_answer": "It executes arbitrary strings as code, opening the door to code injection/XSS, and prevents the JS engine from optimizing the code ahead of time",
    "explanation": "If you `eval(userInput)`, an attacker can execute any code they want. Furthermore, because the engine doesn't know what the string contains until runtime, it cannot compile or optimize the surrounding code, resulting in severe performance penalties."
  }
]
[
  {
    "id": 921,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (CSRF)",
    "question": "What does CSRF (or XSRF) stand for, and what is its primary goal?",
    "code_snippet": null,
    "options": ["Cross-Site Request Forgery; tricking a logged-in user into performing unwanted actions on their current session", "Client-Side Resource Filtering; blocking malicious scripts", "Cross-Server Routing Framework; directing traffic", "Cookie Security Request Format; encrypting session data"],
    "correct_answer": "Cross-Site Request Forgery; tricking a logged-in user into performing unwanted actions on their current session",
    "explanation": "In a CSRF attack, an attacker embeds a hidden image or form on a malicious site that automatically sends a request to your bank (or any site where the user is logged in). Because the browser automatically attaches the user's session cookies, the bank thinks the user made the request."
  },
  {
    "id": 922,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Security (CSRF Prevention)",
    "question": "Which modern cookie attribute tells the browser to ONLY send the cookie if the request originates from the same site, effectively preventing most CSRF attacks?",
    "code_snippet": "Set-Cookie: sessionId=abc123; _______=Strict;",
    "options": ["HttpOnly", "Secure", "SameSite", "NoCross"],
    "correct_answer": "SameSite",
    "explanation": "The `SameSite` attribute (set to `Strict` or `Lax`) prevents the browser from sending the cookie along with cross-site requests. If the user is on `evil.com`, the browser will not attach the `sessionId` cookie when `evil.com` tries to request `bank.com`."
  },
  {
    "id": 923,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (Clickjacking)",
    "question": "What is 'Clickjacking' (UI Redressing)?",
    "code_snippet": null,
    "options": ["Stealing a user's mouse cursor", "Tricking a user into clicking on something different from what they perceive, often by overlaying a transparent, malicious iframe over a legitimate button", "Hacking the user's clipboard", "Stealing cookies via the URL bar"],
    "correct_answer": "Tricking a user into clicking on something different from what they perceive, often by overlaying a transparent, malicious iframe over a legitimate button",
    "explanation": "An attacker might show a 'You won a prize!' button, but invisibly overlay your bank's 'Transfer Funds' iframe on top of it. When the user clicks the prize button, they actually click the hidden transfer button."
  },
  {
    "id": 924,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "question": "Which HTTP response header prevents your website from being embedded inside an `<iframe>` on a malicious site, stopping Clickjacking?",
    "code_snippet": "HTTP/1.1 200 OK\n_______: DENY",
    "options": ["X-Frame-Options", "X-Content-Type-Options", "Content-Security-Policy", "Access-Control-Allow-Origin"],
    "correct_answer": "X-Frame-Options",
    "explanation": "Setting `X-Frame-Options: DENY` (or `SAMEORIGIN`) tells the browser to refuse to render the page if it is loaded inside an `<iframe>`. (Note: The modern alternative is the CSP `frame-ancestors` directive)."
  },
  {
    "id": 925,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (CORS)",
    "question": "What is the primary purpose of CORS (Cross-Origin Resource Sharing)?",
    "code_snippet": null,
    "options": ["To encrypt data sent between the client and server", "To relax the browser's Same-Origin Policy in a controlled way, allowing a server to explicitly declare which external domains can access its resources", "To prevent SQL injection", "To compress HTTP responses"],
    "correct_answer": "To relax the browser's Same-Origin Policy in a controlled way, allowing a server to explicitly declare which external domains can access its resources",
    "explanation": "By default, browsers block JS on `siteA.com` from fetching data from `api.siteB.com` (Same-Origin Policy). CORS is the mechanism where `api.siteB` sends specific headers saying 'Yes, `siteA.com` is allowed to read my data'."
  },
  {
    "id": 926,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "question": "Which HTTP header must a server send to allow a specific external domain to read its response?",
    "code_snippet": "HTTP/1.1 200 OK\n_______: https://frontend.example.com",
    "options": ["Access-Control-Allow-Origin", "X-Allow-Domain", "Content-Security-Policy", "Accept-Origin"],
    "correct_answer": "Access-Control-Allow-Origin",
    "explanation": "The `Access-Control-Allow-Origin` header is the core of CORS. If the requesting origin matches the value in this header, the browser allows the frontend JS to read the response data."
  },
  {
    "id": 927,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (CORS Preflight)",
    "question": "What is a CORS 'Preflight' request?",
    "code_snippet": null,
    "options": ["The first request sent by the server", "An automatic `OPTIONS` request sent by the browser before the actual request to check if the cross-origin action is safe and permitted", "A request to download a file", "A request to clear the browser cache"],
    "correct_answer": "An automatic `OPTIONS` request sent by the browser before the actual request to check if the cross-origin action is safe and permitted",
    "explanation": "For 'non-simple' requests (like those with custom headers or a `DELETE` method), the browser first sends an `OPTIONS` request. If the server replies with the correct CORS headers, the browser then sends the actual `DELETE` request."
  },
  {
    "id": 928,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Reflow vs Repaint",
    "question": "Which of the following CSS property changes will trigger a REFLOW (Layout recalculation)?",
    "code_snippet": null,
    "options": ["color", "background-color", "visibility", "width"],
    "correct_answer": "width",
    "explanation": "Changing `width` alters the geometry of the element, forcing the browser to recalculate the positions of that element and potentially all surrounding elements (a Reflow). Changing `color` only requires a Repaint."
  },
  {
    "id": 929,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Layout Thrashing",
    "question": "What is 'Layout Thrashing' (or Forced Synchronous Layout)?",
    "code_snippet": null,
    "options": ["Using too many CSS animations", "Interleaving DOM reads and DOM writes in a loop, forcing the browser to recalculate the layout repeatedly before it can paint", "Loading too many images at once", "Using `eval()` in a loop"],
    "correct_answer": "Interleaving DOM reads and DOM writes in a loop, forcing the browser to recalculate the layout repeatedly before it can paint",
    "explanation": "If you read `element.offsetHeight`, then change its `style.height`, then read `offsetHeight` again in a loop, the browser is forced to synchronously calculate the layout on every single iteration. This destroys performance. Always batch reads together, then batch writes."
  },
  {
    "id": 930,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "GPU Acceleration",
    "question": "Which two CSS properties are considered 'compositor-only' and can be animated smoothly without triggering Reflow or Repaint?",
    "code_snippet": null,
    "options": ["width and height", "margin and padding", "transform and opacity", "color and background-color"],
    "correct_answer": "transform and opacity",
    "explanation": "When you animate `transform` (like `translateX`) or `opacity`, the browser can hand the element off to the GPU (Compositor thread). It moves the pixels directly on the screen without recalculating layout or repainting pixels, resulting in buttery smooth 60fps animations."
  },
  {
    "id": 931,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "CSS Performance",
    "question": "What does the `will-change` CSS property do?",
    "code_snippet": null,
    "options": ["It forces an element to change its state immediately", "It hints to the browser that an element will be animated soon, allowing the browser to set up optimizations (like GPU layers) ahead of time", "It prevents the element from being changed by JS", "It automatically applies `transform: translateZ(0)`"],
    "correct_answer": "It hints to the browser that an element will be animated soon, allowing the browser to set up optimizations (like GPU layers) ahead of time",
    "explanation": "Applying `will-change: transform` tells the browser to prepare for an upcoming change. However, it should be used sparingly and removed after the animation, as overusing it consumes massive amounts of memory."
  },
  {
    "id": 932,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Web Workers",
    "question": "What is a 'Web Worker' in JavaScript?",
    "code_snippet": null,
    "options": ["A background thread that can execute heavy JavaScript computations without blocking the main UI thread", "A tool for minifying CSS", "A server-side Node.js process", "A method to download files in the background"],
    "correct_answer": "A background thread that can execute heavy JavaScript computations without blocking the main UI thread",
    "explanation": "JavaScript is single-threaded. If you run a massive calculation on the main thread, the UI freezes. Web Workers run in a completely separate thread, allowing the main thread to remain responsive to user clicks and scrolls."
  },
  {
    "id": 933,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to send data from the main thread to a Web Worker.",
    "code_snippet": "const worker = new Worker('math.js');\nworker._______({ numbers: [1, 2, 3] });",
    "options": ["send()", "postMessage()", "emit()", "dispatch()"],
    "correct_answer": "postMessage()",
    "explanation": "Web Workers do not share memory with the main thread. You must use `postMessage()` to send data back and forth. The data is serialized (copied) or transferred."
  },
  {
    "id": 934,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Web Workers Limitations",
    "question": "What is a major limitation of a standard Dedicated Web Worker?",
    "code_snippet": null,
    "options": ["It cannot use the `fetch()` API", "It cannot access the DOM or the `window` object", "It can only run for 5 seconds", "It cannot perform mathematical calculations"],
    "correct_answer": "It cannot access the DOM or the `window` object",
    "explanation": "Because the DOM is not thread-safe, Web Workers are completely isolated from it. If a Worker needs to update the UI, it must `postMessage` the result back to the main thread, and the main thread must perform the DOM update."
  },
  {
    "id": 935,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Service Workers",
    "question": "How does a 'Service Worker' differ from a standard 'Web Worker'?",
    "code_snippet": null,
    "options": ["Service Workers can access the DOM; Web Workers cannot", "Service Workers act as a programmable network proxy, enabling offline caching and push notifications; they also terminate when idle", "Service Workers run on the server; Web Workers run in the browser", "There is no difference"],
    "correct_answer": "Service Workers act as a programmable network proxy, enabling offline caching and push notifications; they also terminate when idle",
    "explanation": "Service Workers are a type of Web Worker specifically designed to intercept network requests, manage caches, and enable Progressive Web App (PWA) features. They live in a separate lifecycle and die when not in use to save memory."
  },
  {
    "id": 936,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Memory Leaks (Detached Nodes)",
    "question": "What is a 'Detached DOM Node' memory leak?",
    "code_snippet": null,
    "options": ["When a DOM element is removed from the page, but a JavaScript variable still holds a reference to it, preventing Garbage Collection", "When the DOM takes too long to parse", "When an element is hidden with CSS", "When an element is moved to an iframe"],
    "correct_answer": "When a DOM element is removed from the page, but a JavaScript variable still holds a reference to it, preventing Garbage Collection",
    "explanation": "If you do `const el = document.querySelector('.modal'); el.remove();`, the element is gone from the screen. But if `el` is still in scope, the entire DOM tree attached to that node remains in memory. You must set `el = null` to free it."
  },
  {
    "id": 937,
    "level": "intermediate",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to use the native browser API to lazy-load an image only when it scrolls near the viewport.",
    "code_snippet": "<img src='large-photo.jpg' _______='lazy' alt='Photo' />",
    "options": ["defer", "async", "loading", "lazy"],
    "correct_answer": "loading",
    "explanation": "The `loading='lazy'` attribute tells the browser to delay fetching the image until the user scrolls near it. This drastically reduces initial page load time and saves bandwidth."
  },
  {
    "id": 938,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance API",
    "question": "Why should you use `performance.now()` instead of `Date.now()` for benchmarking code execution time?",
    "code_snippet": null,
    "options": ["`performance.now()` is faster to type", "`performance.now()` provides a high-resolution, monotonically increasing timestamp in milliseconds, unaffected by system clock changes (like NTP syncs)", "`Date.now()` is deprecated", "`performance.now()` runs on a Web Worker"],
    "correct_answer": "`performance.now()` provides a high-resolution, monotonically increasing timestamp in milliseconds, unaffected by system clock changes (like NTP syncs)",
    "explanation": "`Date.now()` returns the current system time, which can jump forward or backward if the OS syncs its clock. `performance.now()` measures time relative to the page load, providing microsecond precision that is guaranteed to always move forward."
  },
  {
    "id": 939,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "requestIdleCallback",
    "question": "What is the purpose of `requestIdleCallback()`?",
    "code_snippet": null,
    "options": ["To run code immediately on the next frame", "To schedule low-priority background tasks that will execute when the browser is idle and the main thread has spare time", "To pause the execution of code", "To request data from the server during idle time"],
    "correct_answer": "To schedule low-priority background tasks that will execute when the browser is idle and the main thread has spare time",
    "explanation": "If you need to do heavy, non-urgent work (like analytics logging or pre-rendering off-screen DOM nodes), `requestIdleCallback` ensures you only do it when the user isn't interacting with the page, preventing UI jank."
  },
  {
    "id": 940,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Script Loading)",
    "question": "When optimizing page load performance, why is it recommended to use `<script src='app.js' defer></script>` instead of a standard `<script>` tag in the `<head>`?",
    "code_snippet": null,
    "options": ["`defer` makes the JS run faster", "A standard script blocks HTML parsing; `defer` downloads the script in the background and executes it only AFTER the HTML is fully parsed", "`defer` compresses the file", "`defer` prevents XSS attacks"],
    "correct_answer": "A standard script blocks HTML parsing; `defer` downloads the script in the background and executes it only AFTER the HTML is fully parsed",
    "explanation": "Standard `<script>` tags halt the HTML parser, making the page load slowly. `defer` tells the browser to download the JS in parallel with HTML parsing, but wait to execute it until the DOM is fully built. This is the modern best practice."
  }
]
[
  {
    "id": 941,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (Subresource Integrity)",
    "question": "What is the purpose of the `integrity` attribute on a `<script>` or `<link>` tag (Subresource Integrity or SRI)?",
    "code_snippet": null,
    "options": ["To compress the file for faster loading", "To ensure the browser only executes the file if its cryptographic hash matches the expected hash, preventing tampered CDN files", "To tell the browser to load the script asynchronously", "To prevent the script from accessing cookies"],
    "correct_answer": "To ensure the browser only executes the file if its cryptographic hash matches the expected hash, preventing tampered CDN files",
    "explanation": "If a hacker compromises a popular CDN (like cdnjs) and injects malware into a library, SRI prevents the browser from executing it because the file's hash will no longer match the hash you specified in your HTML."
  },
  {
    "id": 942,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Security (Subresource Integrity)",
    "question": "Fill in the blank to correctly implement Subresource Integrity for an external script.",
    "code_snippet": "<script src='https://cdn.example.com/lib.js' _______='sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC'></script>",
    "options": ["hash", "checksum", "integrity", "security"],
    "correct_answer": "integrity",
    "explanation": "The `integrity` attribute takes the algorithm (like sha384) and the base64-encoded hash. If the downloaded file doesn't match, the browser blocks it."
  },
  {
    "id": 943,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (HSTS)",
    "question": "What does HTTP Strict Transport Security (HSTS) do?",
    "code_snippet": null,
    "options": ["It forces the browser to only connect to the server via HTTPS, even if the user types 'http://' or clicks an HTTP link", "It encrypts the database", "It prevents Cross-Site Scripting", "It blocks all third-party cookies"],
    "correct_answer": "It forces the browser to only connect to the server via HTTPS, even if the user types 'http://' or clicks an HTTP link",
    "explanation": "HSTS tells the browser, 'Never even attempt to connect to this domain over HTTP again.' It completely eliminates SSL-stripping downgrade attacks."
  },
  {
    "id": 944,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Security (HSTS)",
    "question": "Which HTTP response header is used to enable HSTS?",
    "code_snippet": "HTTP/1.1 200 OK\n_______: max-age=31536000; includeSubDomains; preload",
    "options": ["X-Frame-Options", "Strict-Transport-Security", "Content-Security-Policy", "Access-Control-Allow-Origin"],
    "correct_answer": "Strict-Transport-Security",
    "explanation": "The `Strict-Transport-Security` header instructs the browser to remember to only use HTTPS for the specified `max-age` (in seconds)."
  },
  {
    "id": 945,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Critical Rendering Path",
    "question": "What is the 'Critical Rendering Path' in web performance?",
    "code_snippet": null,
    "options": ["The physical cable connecting the server to the user", "The sequence of steps the browser takes to convert HTML, CSS, and JS into actual pixels on the screen (DOM -> CSSOM -> Render Tree -> Layout -> Paint)", "The path a user takes through a website", "The route a network packet takes to reach the CDN"],
    "correct_answer": "The sequence of steps the browser takes to convert HTML, CSS, and JS into actual pixels on the screen (DOM -> CSSOM -> Render Tree -> Layout -> Paint)",
    "explanation": "Optimizing the Critical Rendering Path means minimizing the time it takes for the browser to complete these steps, resulting in a faster 'First Contentful Paint' (FCP)."
  },
  {
    "id": 946,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Tree Shaking",
    "question": "What is 'Tree Shaking' in modern JavaScript bundlers (like Webpack or Rollup)?",
    "code_snippet": null,
    "options": ["A method to randomize array elements", "The process of eliminating dead code (unused exports) from the final bundle by analyzing ES6 import/export statements", "A way to compress images", "A technique to sort CSS classes"],
    "correct_answer": "The process of eliminating dead code (unused exports) from the final bundle by analyzing ES6 import/export statements",
    "explanation": "If you import one function from a massive library, tree shaking ensures the other 99 unused functions in that library are not included in your final production JavaScript file, drastically reducing bundle size."
  },
  {
    "id": 947,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Code Splitting",
    "question": "What is 'Code Splitting' (or Route-based Lazy Loading)?",
    "code_snippet": null,
    "options": ["Breaking your CSS into multiple files", "Dividing your JavaScript bundle into smaller chunks that are only downloaded when the user navigates to a specific route or needs a specific feature", "Splitting your code between the client and the server", "Using multiple programming languages in one project"],
    "correct_answer": "Dividing your JavaScript bundle into smaller chunks that are only downloaded when the user navigates to a specific route or needs a specific feature",
    "explanation": "Instead of forcing the user to download a 5MB `app.js` file on the homepage, code splitting allows you to send a 200KB initial bundle, and dynamically `import()` the rest of the code only when the user clicks on the 'Dashboard' route."
  },
  {
    "id": 948,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "V8 Hidden Classes",
    "question": "What are 'Hidden Classes' (or 'Shapes') in the V8 JavaScript engine?",
    "code_snippet": null,
    "options": ["Private CSS classes", "Internal structures V8 creates to optimize property access for objects that share the same structure and property addition order", "Variables that are hidden from the console", "A type of memory leak"],
    "correct_answer": "Internal structures V8 creates to optimize property access for objects that share the same structure and property addition order",
    "explanation": "When V8 sees objects being created with the same properties in the same order, it groups them into a 'Hidden Class'. This allows V8 to use highly optimized machine code (Inline Caching) to access properties, rather than doing slow dictionary lookups."
  },
  {
    "id": 949,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "V8 Optimization Quirks",
    "question": "Why is it a performance anti-pattern to add properties to an object in a random, inconsistent order?",
    "code_snippet": null,
    "options": ["It causes a SyntaxError", "It prevents the V8 engine from assigning them to the same 'Hidden Class', forcing V8 to use slower dictionary lookups instead of optimized inline caching", "It uses more network bandwidth", "It breaks the Garbage Collector"],
    "correct_answer": "It prevents the V8 engine from assigning them to the same 'Hidden Class', forcing V8 to use slower dictionary lookups instead of optimized inline caching",
    "explanation": "If Object A adds `x` then `y`, and Object B adds `y` then `x`, V8 treats them as completely different shapes. Always initialize object properties in the constructor in the exact same order for maximum V8 performance."
  },
  {
    "id": 950,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "output-prediction",
    "topic": "Forced Synchronous Layout",
    "question": "Which of the following JavaScript property reads will force the browser to immediately pause and perform a synchronous Reflow (Layout) if the DOM was just modified?",
    "code_snippet": null,
    "options": ["element.className", "element.dataset.id", "element.offsetTop", "element.getAttribute('id')"],
    "correct_answer": "element.offsetTop",
    "explanation": "Properties that return geometric/layout data (like `offsetTop`, `offsetHeight`, `scrollTop`, or `getBoundingClientRect()`) force the browser to synchronously calculate the current layout if it has been invalidated by recent JS changes. This is a major performance bottleneck."
  },
  {
    "id": 951,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Passive Event Listeners",
    "question": "What does adding `{ passive: true }` to an `addEventListener` do?",
    "code_snippet": null,
    "options": ["It prevents the event from bubbling", "It tells the browser that the callback will NEVER call `preventDefault()`, allowing the browser to scroll immediately without waiting for the JS to finish executing", "It makes the event listener run on a Web Worker", "It automatically removes the listener after one use"],
    "correct_answer": "It tells the browser that the callback will NEVER call `preventDefault()`, allowing the browser to scroll immediately without waiting for the JS to finish executing",
    "explanation": "By default, the browser must wait for touch/wheel event listeners to finish executing just in case they call `preventDefault()` to stop a scroll. `passive: true` guarantees they won't, resulting in instantly smooth, 60fps scrolling."
  },
  {
    "id": 952,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "topic": "Passive Event Listeners",
    "question": "Fill in the blank to correctly attach a highly performant, passive scroll listener.",
    "code_snippet": "window.addEventListener('scroll', handleScroll, { _______: true });",
    "options": ["capture", "passive", "async", "defer"],
    "correct_answer": "passive",
    "explanation": "Modern browsers actually default touch-start and wheel events to `passive: true` automatically, but it is best practice to explicitly declare it for all scroll/touch listeners to guarantee smooth performance."
  },
  {
    "id": 953,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (Open Redirect)",
    "question": "What is an 'Open Redirect' vulnerability?",
    "code_snippet": null,
    "options": ["When a website fails to load", "When a website accepts a user-controlled URL and redirects the user to it without validation, allowing attackers to craft phishing links that look like they come from a trusted domain", "When a redirect loop crashes the browser", "When a server redirects HTTP to HTTPS"],
    "correct_answer": "When a website accepts a user-controlled URL and redirects the user to it without validation, allowing attackers to craft phishing links that look like they come from a trusted domain",
    "explanation": "If `bank.com/login?redirect=evil.com` blindly sends the user to `evil.com` after logging in, an attacker can send a phishing email with the `bank.com` URL. The user trusts the domain, logs in, and is seamlessly sent to the attacker's fake site."
  },
  {
    "id": 954,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Resource Hints)",
    "question": "What is the difference between `<link rel='preload'>` and `<link rel='prefetch'>`?",
    "code_snippet": null,
    "options": ["They are the exact same", "`preload` fetches critical resources needed for the CURRENT page with high priority; `prefetch` fetches resources likely needed for a FUTURE navigation during browser idle time", "`prefetch` is for CSS, `preload` is for JS", "`preload` blocks rendering, `prefetch` executes the JS immediately"],
    "correct_answer": "`preload` fetches critical resources needed for the CURRENT page with high priority; `prefetch` fetches resources likely needed for a FUTURE navigation during browser idle time",
    "explanation": "Use `preload` for the custom font or hero image needed right now. Use `prefetch` for the heavy JS bundle of the 'Checkout' page while the user is still reading the 'Homepage'."
  },
  {
    "id": 955,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly tell the browser to fetch a critical font file as early as possible.",
    "code_snippet": "<link rel='_______' href='font.woff2' as='font' type='font/woff2' crossorigin>",
    "options": ["prefetch", "preload", "preconnect", "dns-prefetch"],
    "correct_answer": "preload",
    "explanation": "`rel='preload'` tells the browser to download this specific resource immediately with high priority, preventing the 'Flash of Unstyled Text' (FOUT) caused by late-loading fonts."
  },
  {
    "id": 956,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Image Formats)",
    "question": "Why are modern image formats like WebP and AVIF preferred over JPEG and PNG for web performance?",
    "code_snippet": null,
    "options": ["They are supported by older browsers", "They provide significantly better compression (smaller file sizes) at the same or better visual quality, reducing bandwidth and load times", "They are vector graphics", "They automatically resize based on the screen"],
    "correct_answer": "They provide significantly better compression (smaller file sizes) at the same or better visual quality, reducing bandwidth and load times",
    "explanation": "WebP and AVIF use advanced algorithms to reduce image file sizes by 25-50% compared to JPEG/PNG without noticeable quality loss, which is crucial for mobile users on slow networks."
  },
  {
    "id": 957,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Memory (DevTools)",
    "question": "Which specific panel in Chrome DevTools is used to take 'Heap Snapshots' to find memory leaks?",
    "code_snippet": null,
    "options": ["Elements", "Console", "Memory", "Network"],
    "correct_answer": "Memory",
    "explanation": "The Memory tab allows you to take Heap Snapshots, compare them over time, and see exactly which objects are retaining memory and what variables are holding references to them."
  },
  {
    "id": 958,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Lighthouse)",
    "question": "What is Google Lighthouse?",
    "code_snippet": null,
    "options": ["A CSS framework", "An open-source, automated tool for auditing web page performance, accessibility, SEO, and best practices", "A Node.js web server", "A database management tool"],
    "correct_answer": "An open-source, automated tool for auditing web page performance, accessibility, SEO, and best practices",
    "explanation": "Lighthouse (built into Chrome DevTools) generates a comprehensive report card for your website, giving you actionable advice on how to improve load times, fix accessibility issues, and optimize SEO."
  },
  {
    "id": 959,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Security (Dependency Confusion)",
    "question": "What is a 'Dependency Confusion' (or Substitution) attack?",
    "code_snippet": null,
    "options": ["When a package.json file has too many dependencies", "When an attacker publishes a malicious package to a public registry (like npm) with the exact same name as a company's private internal package, tricking the build server into downloading the malware", "When two dependencies require conflicting versions of a library", "When a dependency is deprecated"],
    "correct_answer": "When an attacker publishes a malicious package to a public registry (like npm) with the exact same name as a company's private internal package, tricking the build server into downloading the malware",
    "explanation": "If a company uses an internal package named `@mycompany/auth-lib`, and an attacker publishes a malicious `@mycompany/auth-lib` to the public npm registry, the company's CI/CD pipeline might accidentally download and execute the attacker's code instead of their own."
  },
  {
    "id": 960,
    "level": "advanced",
    "module_id": "mod_16_memory_perf_security",
    "module_name": "Memory, Performance & Security",
    "type": "conceptual",
    "topic": "Performance (Preconnect)",
    "question": "What does `<link rel='preconnect'>` do?",
    "code_snippet": null,
    "options": ["Downloads the full JavaScript file", "Establishes an early connection (DNS lookup, TCP handshake, TLS negotiation) to an external origin to speed up future resource loading", "Connects to a WebSocket server", "Preloads the database"],
    "correct_answer": "Establishes an early connection (DNS lookup, TCP handshake, TLS negotiation) to an external origin to speed up future resource loading",
    "explanation": "If you know you will need to fetch a font or an API call from `api.example.com` later, `<link rel='preconnect' href='https://api.example.com'>` does the expensive network handshake early, saving hundreds of milliseconds when the actual request is made."
  }
]
