[
  {
    "id": 821,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "try...catch Basics",
    "question": "What is the primary purpose of a `try...catch` block in JavaScript?",
    "code_snippet": null,
    "options": ["To speed up code execution", "To test code for errors and handle them gracefully without crashing the entire program", "To loop through an array safely", "To prevent variables from being changed"],
    "correct_answer": "To test code for errors and handle them gracefully without crashing the entire program",
    "explanation": "If an error occurs inside the `try` block, execution immediately jumps to the `catch` block. This prevents the entire script from crashing and allows you to show a user-friendly message or log the error."
  },
  {
    "id": 822,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "try...catch Basics",
    "question": "Fill in the blank to correctly catch an error thrown inside the `try` block.",
    "code_snippet": "try {\n  JSON.parse('invalid json');\n} _______ (error) {\n  console.log('Failed to parse!');\n}",
    "options": ["error", "catch", "handle", "except"],
    "correct_answer": "catch",
    "explanation": "The `catch` block receives the error object (conventionally named `error` or `err`) as a parameter, allowing you to inspect what went wrong."
  },
  {
    "id": 823,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "The 'finally' Block",
    "question": "When does the code inside a `finally` block execute?",
    "code_snippet": null,
    "options": ["Only if an error is caught in the `catch` block", "Only if NO error occurs in the `try` block", "Always, regardless of whether an error was thrown or caught", "Only if the `catch` block is omitted"],
    "correct_answer": "Always, regardless of whether an error was thrown or caught",
    "explanation": "The `finally` block is guaranteed to execute no matter what happens in `try` or `catch`. It is typically used for cleanup tasks, like closing a database connection or hiding a loading spinner."
  },
  {
    "id": 824,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "The 'finally' Block",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "try {\n  console.log('A');\n  throw new Error('Oops');\n  console.log('B');\n} catch (e) {\n  console.log('C');\n} finally {\n  console.log('D');\n}",
    "options": ["A, B, C, D", "A, C, D", "A, D", "Error: Oops"],
    "correct_answer": "A, C, D",
    "explanation": "'A' logs. The `throw` immediately exits the `try` block, so 'B' is skipped. The `catch` block runs and logs 'C'. Finally, the `finally` block always runs and logs 'D'."
  },
  {
    "id": 825,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Error Types",
    "question": "What type of error is thrown when you try to access a variable that has not been declared?",
    "code_snippet": null,
    "options": ["TypeError", "SyntaxError", "ReferenceError", "RangeError"],
    "correct_answer": "ReferenceError",
    "explanation": "A `ReferenceError` occurs when you try to reference a variable that doesn't exist in the current scope (e.g., a typo in the variable name)."
  },
  {
    "id": 826,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Error Types",
    "question": "What type of error is thrown when you try to call something that is not a function (e.g., `const x = 5; x();`)?",
    "code_snippet": null,
    "options": ["ReferenceError", "TypeError", "SyntaxError", "LogicError"],
    "correct_answer": "TypeError",
    "explanation": "A `TypeError` is thrown when a value is not of the expected type. Trying to execute a number, or reading a property of `null` or `undefined`, are classic TypeErrors."
  },
  {
    "id": 827,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "Throwing Errors",
    "question": "Fill in the blank to manually trigger an error if a user's age is under 18.",
    "code_snippet": "if (age < 18) {\n  _______ new Error('Must be 18 or older');\n}",
    "options": ["throw", "error", "catch", "return"],
    "correct_answer": "throw",
    "explanation": "The `throw` keyword is used to create custom errors. It is highly recommended to throw an actual `Error` object (or a subclass of it) rather than just a string, so you get a stack trace."
  },
  {
    "id": 828,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Custom Errors",
    "question": "How do you create a custom error class in modern JavaScript?",
    "code_snippet": null,
    "options": ["class MyError extends Error {}", "class MyError implements Error {}", "new Error('MyError')", "Error.create('MyError')"],
    "correct_answer": "class MyError extends Error {}",
    "explanation": "By extending the built-in `Error` class, you can create custom error types (like `ValidationError` or `AuthenticationError`) that can be specifically caught using `instanceof` checks."
  },
  {
    "id": 829,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Custom Errors",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "class ValidationError extends Error {}\ntry {\n  throw new ValidationError('Invalid email');\n} catch (e) {\n  console.log(e instanceof ValidationError, e instanceof Error);\n}",
    "options": ["true, true", "true, false", "false, true", "Error"],
    "correct_answer": "true, true",
    "explanation": "Because `ValidationError` extends `Error`, an instance of it is considered BOTH a `ValidationError` and a standard `Error`. This allows you to catch specific custom errors while still treating them as standard errors."
  },
  {
    "id": 830,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Error Properties",
    "question": "Which property of an `Error` object contains the detailed stack trace showing where the error occurred?",
    "code_snippet": null,
    "options": ["e.trace", "e.message", "e.stack", "e.location"],
    "correct_answer": "e.stack",
    "explanation": "The `.stack` property provides a string containing the sequence of function calls that led to the error, including file names and line numbers. It is invaluable for debugging."
  },
  {
    "id": 831,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "Object.defineProperty()",
    "question": "Fill in the blank to add a non-enumerable property 'id' to the 'user' object.",
    "code_snippet": "const user = { name: 'Alice' };\nObject._______(user, 'id', { value: 123, enumerable: false });",
    "options": ["addProperty", "defineProperty", "setProperty", "createProperty"],
    "correct_answer": "defineProperty",
    "explanation": "`Object.defineProperty()` allows you to add or modify a property on an object while precisely controlling its behavior (writable, enumerable, configurable) via a descriptor object."
  },
  {
    "id": 832,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Property Descriptors",
    "question": "What happens if you set `enumerable: false` on an object property?",
    "code_snippet": null,
    "options": ["The property is deleted", "The property cannot be changed", "The property is hidden from `for...in` loops and `Object.keys()`", "The property becomes read-only"],
    "correct_answer": "The property is hidden from `for...in` loops and `Object.keys()`",
    "explanation": "Non-enumerable properties still exist and can be accessed directly (e.g., `obj.id`), but they are skipped when iterating over the object's keys. This is how built-in properties like `Array.prototype.length` work."
  },
  {
    "id": 833,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Property Descriptors",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = {};\nObject.defineProperty(obj, 'a', { value: 1, enumerable: true });\nObject.defineProperty(obj, 'b', { value: 2, enumerable: false });\nconsole.log(Object.keys(obj));",
    "options": ["['a', 'b']", "['a']", "['b']", "[]"],
    "correct_answer": "['a']",
    "explanation": "`Object.keys()` only returns properties where `enumerable` is true. Since 'b' is non-enumerable, it is excluded from the resulting array."
  },
  {
    "id": 834,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Property Descriptors",
    "question": "What does setting `writable: false` on a property descriptor do?",
    "code_snippet": null,
    "options": ["Prevents the property from being deleted", "Prevents the property's value from being changed using the assignment operator (=)", "Hides the property from console.log", "Makes the property enumerable"],
    "correct_answer": "Prevents the property's value from being changed using the assignment operator (=)",
    "explanation": "If `writable` is false, attempting to change the value via `obj.prop = newValue` will silently fail in non-strict mode, or throw a `TypeError` in strict mode."
  },
  {
    "id": 835,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Property Descriptors",
    "question": "What will be the exact output of the following code in strict mode?",
    "code_snippet": "\"use strict\";\nconst obj = {};\nObject.defineProperty(obj, 'x', { value: 10, writable: false });\nobj.x = 20;\nconsole.log(obj.x);",
    "options": ["10", "20", "undefined", "It throws a TypeError before logging"],
    "correct_answer": "It throws a TypeError before logging",
    "explanation": "In strict mode, attempting to modify a non-writable property throws a `TypeError: Cannot assign to read only property 'x'`. The `console.log` is never reached."
  },
  {
    "id": 836,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Object.freeze()",
    "question": "What is the effect of calling `Object.freeze(obj)`?",
    "code_snippet": null,
    "options": ["It deletes all properties of the object", "It prevents new properties from being added, existing properties from being removed, and prevents changing the values of existing properties", "It converts the object to a string", "It makes the object enumerable"],
    "correct_answer": "It prevents new properties from being added, existing properties from being removed, and prevents changing the values of existing properties",
    "explanation": "`Object.freeze()` is essentially a shortcut that sets `writable: false` and `configurable: false` for all existing properties, and sets `extensible: false` on the object itself."
  },
  {
    "id": 837,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Object.freeze()",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const user = Object.freeze({ name: 'Alice', address: { city: 'NY' } });\nuser.name = 'Bob';\nuser.address.city = 'LA';\nconsole.log(user.name, user.address.city);",
    "options": ["Alice, NY", "Bob, LA", "Alice, LA", "Bob, NY"],
    "correct_answer": "Alice, LA",
    "explanation": "`Object.freeze()` is a SHALLOW freeze. It prevents changing `user.name`, but the `address` property holds a reference to another object. That nested object is NOT frozen, so `city` can still be changed to 'LA'."
  },
  {
    "id": 838,
    "level": "intermediate",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Shallow vs Deep Copy",
    "question": "What is the difference between a 'shallow copy' and a 'deep copy' of an object?",
    "code_snippet": null,
    "options": ["A shallow copy is faster", "A shallow copy only copies the top-level properties (nested objects remain shared references); a deep copy recursively copies all levels of nesting", "A deep copy freezes the object", "There is no difference"],
    "correct_answer": "A shallow copy only copies the top-level properties (nested objects remain shared references); a deep copy recursively copies all levels of nesting",
    "explanation": "If you use the spread operator `{ ...obj }`, nested objects are still passed by reference. A true deep copy creates entirely independent copies of all nested objects and arrays."
  },
  {
    "id": 839,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "Deep Copying",
    "question": "Fill in the blank to correctly create a true, independent deep copy of an object using the modern built-in browser/Node.js API.",
    "code_snippet": "const original = { a: 1, nested: { b: 2 } };\nconst deepCopy = _______(original);",
    "options": ["Object.clone", "JSON.parse", "structuredClone", "Object.deepCopy"],
    "correct_answer": "structuredClone",
    "explanation": "Introduced recently, `structuredClone()` is the native, modern way to deep clone objects. It handles circular references, Maps, Sets, Dates, and RegExps, unlike the old `JSON.parse(JSON.stringify())` hack."
  },
  {
    "id": 840,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Deep Copying",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const original = { date: new Date('2023-01-01'), nested: { val: 1 } };\nconst copy = structuredClone(original);\ncopy.date.setFullYear(2025);\ncopy.nested.val = 99;\nconsole.log(original.date.getFullYear(), original.nested.val);",
    "options": ["2025, 99", "2023, 1", "2025, 1", "2023, 99"],
    "correct_answer": "2023, 1",
    "explanation": "Because `structuredClone` creates a true deep copy, the nested object and the Date object are completely independent. Modifying the copy has absolutely zero effect on the original."
  }
]
[
  {
    "id": 841,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Global Error Handling",
    "question": "What is the purpose of the `window.onerror` function in a browser environment?",
    "code_snippet": null,
    "options": ["To catch errors inside Promises", "To act as a global catch-all for any uncaught synchronous JavaScript errors", "To prevent the browser from crashing", "To log CSS errors"],
    "correct_answer": "To act as a global catch-all for any uncaught synchronous JavaScript errors",
    "explanation": "`window.onerror` is a legacy but still widely used global handler that fires whenever an uncaught error bubbles up to the window object. It's often used to send error reports to monitoring services like Sentry."
  },
  {
    "id": 842,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "Global Error Handling",
    "question": "Fill in the blank to listen for ANY unhandled Promise rejections globally in the browser.",
    "code_snippet": "window.addEventListener('_______', (event) => {\n  console.error('Unhandled Promise:', event.reason);\n});",
    "options": ["error", "promiseError", "unhandledrejection", "catch"],
    "correct_answer": "unhandledrejection",
    "explanation": "The `unhandledrejection` event is fired whenever a Promise is rejected and no `.catch()` handler is attached. It is the Promise equivalent of `window.onerror`."
  },
  {
    "id": 843,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Async Error Traps",
    "question": "Why does a standard `try...catch` block FAIL to catch an error thrown inside a `setTimeout` callback?",
    "code_snippet": null,
    "options": ["Because setTimeout is deprecated", "Because the callback executes asynchronously, AFTER the try...catch block has already finished executing and been removed from the call stack", "Because setTimeout runs on a separate thread", "Because try...catch only works with Promises"],
    "correct_answer": "Because the callback executes asynchronously, AFTER the try...catch block has already finished executing and been removed from the call stack",
    "explanation": "When `setTimeout` fires, the original `try` block is long gone. The error happens in a completely new execution context. To catch async errors, you must put the `try...catch` INSIDE the callback, or use Promises/async-await."
  },
  {
    "id": 844,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Async Error Traps",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "try {\n  setTimeout(() => {\n    throw new Error('Async Fail');\n  }, 0);\n} catch (e) {\n  console.log('Caught!');\n}",
    "options": ["Caught!", "Async Fail", "Caught! followed by an Uncaught Error", "undefined"],
    "correct_answer": "Caught! followed by an Uncaught Error",
    "explanation": "Wait, no! The `try` block finishes immediately. The `catch` block is skipped. Later, the timer fires, throws the error, and because there is no catch block inside the timer, it results in an 'Uncaught Error: Async Fail' in the console."
  },
  {
    "id": 845,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Fetch API Errors",
    "question": "What is a major 'gotcha' with the `fetch()` API regarding HTTP errors (like 404 Not Found or 500 Internal Server Error)?",
    "code_snippet": null,
    "options": ["fetch() automatically retries on 500 errors", "fetch() does NOT reject the Promise on HTTP error statuses; it only rejects on network failures. You must manually check response.ok", "fetch() throws a SyntaxError on 404", "fetch() automatically redirects to the homepage on 404"],
    "correct_answer": "fetch() does NOT reject the Promise on HTTP error statuses; it only rejects on network failures. You must manually check response.ok",
    "explanation": "This is a classic trap! If a server returns a 404, `fetch()` still resolves successfully. You must check `if (!response.ok) { throw new Error(...) }` to trigger your `catch` block."
  },
  {
    "id": 846,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Proxy API",
    "question": "What is a `Proxy` in JavaScript?",
    "code_snippet": null,
    "options": ["A way to send network requests", "An object that wraps another object and intercepts fundamental operations (like getting or setting properties)", "A method to hide variables from the console", "A deprecated feature from ES5"],
    "correct_answer": "An object that wraps another object and intercepts fundamental operations (like getting or setting properties)",
    "explanation": "Proxies allow you to define custom behavior for core operations. You can intercept property reads, writes, function calls, and more. They are the foundation of reactivity in frameworks like Vue 3."
  },
  {
    "id": 847,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "Proxy API",
    "question": "Fill in the blank to correctly create a Proxy that intercepts property reads.",
    "code_snippet": "const handler = {\n  get(target, prop) {\n    return 'Intercepted!';\n  }\n};\nconst myProxy = new _______(targetObj, handler);",
    "options": ["Proxy", "Interceptor", "Wrapper", "Reflect"],
    "correct_answer": "Proxy",
    "explanation": "The `new Proxy(target, handler)` constructor creates a proxy object. The `target` is the original object, and the `handler` contains the 'traps' (like `get` or `set`) that define the custom behavior."
  },
  {
    "id": 848,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Proxy API",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const handler = {\n  get(target, prop) {\n    return prop in target ? target[prop] : 'Default Value';\n  }\n};\nconst p = new Proxy({ a: 1, b: 2 }, handler);\nconsole.log(p.a, p.c);",
    "options": ["1, undefined", "1, Default Value", "undefined, Default Value", "Error"],
    "correct_answer": "1, Default Value",
    "explanation": "When accessing `p.a`, the proxy finds it in the target and returns 1. When accessing `p.c`, the `get` trap intercepts it, sees it doesn't exist in the target, and returns the custom 'Default Value'."
  },
  {
    "id": 849,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Proxy Traps",
    "question": "In the context of Proxies, what is a 'trap'?",
    "code_snippet": null,
    "options": ["An error thrown by the proxy", "A method inside the handler object (like `get`, `set`, or `apply`) that intercepts an operation", "A way to trap memory leaks", "A loop inside the proxy"],
    "correct_answer": "A method inside the handler object (like `get`, `set`, or `apply`) that intercepts an operation",
    "explanation": "Traps are the specific functions you define in the handler object. They 'trap' the intercepted operation, allowing you to run custom code before (or instead of) passing it to the target object."
  },
  {
    "id": 850,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Reflect API",
    "question": "What is the `Reflect` API in JavaScript?",
    "code_snippet": null,
    "options": ["A tool to measure code performance", "A built-in object providing methods for interceptable JavaScript operations, mirroring Proxy traps", "A way to reflect CSS changes to JS", "A debugging tool for the console"],
    "correct_answer": "A built-in object providing methods for interceptable JavaScript operations, mirroring Proxy traps",
    "explanation": "`Reflect` provides methods like `Reflect.get()`, `Reflect.set()`, and `Reflect.apply()`. These methods do exactly what the default JS engine behavior does, but as callable functions."
  },
  {
    "id": 851,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "code-fill-in-blank",
    "topic": "Reflect API",
    "question": "Fill in the blank to correctly use the Reflect API to get a property value.",
    "code_snippet": "const user = { name: 'Alice' };\nconst val = Reflect._______(user, 'name');",
    "options": ["getProperty", "get", "read", "fetch"],
    "correct_answer": "get",
    "explanation": "`Reflect.get(target, propertyKey)` is the functional equivalent of `target[propertyKey]`. It is often used inside Proxy `get` traps to forward the operation to the original target."
  },
  {
    "id": 852,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Reflect vs Old Methods",
    "question": "Why is it recommended to use `Reflect` methods inside Proxy traps instead of older methods like `Object.defineProperty`?",
    "code_snippet": null,
    "options": ["Reflect is faster", "Reflect methods return boolean success/failure values instead of throwing errors, making it easier to forward operations to the target without breaking the proxy", "Reflect is required by ES6 syntax", "There is no difference"],
    "correct_answer": "Reflect methods return boolean success/failure values instead of throwing errors, making it easier to forward operations to the target without breaking the proxy",
    "explanation": "If an operation fails (e.g., trying to set a non-writable property), `Object.defineProperty` throws an error. `Reflect.set()` simply returns `false`. This makes writing robust Proxy traps much cleaner."
  },
  {
    "id": 853,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "WeakMap",
    "question": "What is the main difference between a standard `Map` and a `WeakMap`?",
    "code_snippet": null,
    "options": ["WeakMaps are faster", "WeakMaps only accept objects as keys, and they hold those keys 'weakly' (allowing them to be garbage collected)", "WeakMaps cannot store values, only keys", "WeakMaps automatically sort their keys"],
    "correct_answer": "WeakMaps only accept objects as keys, and they hold those keys 'weakly' (allowing them to be garbage collected)",
    "explanation": "In a standard Map, holding a reference to an object as a key prevents it from being deleted from memory. WeakMaps hold 'weak' references, preventing memory leaks if the key object is removed from the DOM or deleted elsewhere."
  },
  {
    "id": 854,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "WeakMap Iteration",
    "question": "Why can't you iterate over a `WeakMap` using a `for...of` loop or `Object.keys()`?",
    "code_snippet": null,
    "options": ["It's a syntax error in ES6", "Because the keys might be garbage collected at any moment by the JS engine, making a reliable, consistent iteration impossible", "Because they are empty by default", "Because they only hold primitive values"],
    "correct_answer": "Because the keys might be garbage collected at any moment by the JS engine, making a reliable, consistent iteration impossible",
    "explanation": "Since the JavaScript engine can silently remove entries from a WeakMap in the background when memory needs to be freed, there is no guaranteed list of items to iterate over at any given millisecond."
  },
  {
    "id": 855,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "WeakSet",
    "question": "What is a `WeakSet`?",
    "code_snippet": null,
    "options": ["A Set that only holds strings", "A Set that only holds objects, and holds them weakly (allowing garbage collection)", "A Set that automatically removes duplicates after 1 second", "A deprecated version of the standard Set"],
    "correct_answer": "A Set that only holds objects, and holds them weakly (allowing garbage collection)",
    "explanation": "Just like WeakMap, WeakSet only accepts objects and does not prevent them from being garbage collected. It's useful for tracking object states (e.g., 'has this DOM element been processed yet?') without causing memory leaks."
  },
  {
    "id": 856,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "WeakMap Use Cases",
    "question": "What is a classic real-world use case for a `WeakMap`?",
    "code_snippet": null,
    "options": ["Storing user passwords", "Storing private data associated with DOM elements, ensuring the data is cleaned up when the element is removed from the page", "Caching API responses", "Storing global configuration"],
    "correct_answer": "Storing private data associated with DOM elements, ensuring the data is cleaned up when the element is removed from the page",
    "explanation": "If you use a standard Map to store data about DOM elements, removing the element from the HTML doesn't remove it from the Map, causing a memory leak. A WeakMap automatically cleans up the entry when the DOM element is garbage collected."
  },
  {
    "id": 857,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "output-prediction",
    "topic": "Proxy set trap",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const handler = {\n  set(target, prop, value) {\n    if (typeof value !== 'number') {\n      console.log('Must be a number!');\n      return false;\n    }\n    return Reflect.set(target, prop, value);\n  }\n};\nconst p = new Proxy({ age: 20 }, handler);\np.age = 'old';\nconsole.log(p.age);",
    "options": ["Must be a number!, old", "Must be a number!, 20", "20", "old"],
    "correct_answer": "Must be a number!, 20",
    "explanation": "The `set` trap intercepts the assignment. It sees 'old' is not a number, logs the warning, and returns `false` (which prevents the assignment in strict mode, or silently fails). The original value of 20 remains unchanged."
  },
  {
    "id": 858,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Proxy Revocable",
    "question": "What does `Proxy.revocable(target, handler)` do?",
    "code_snippet": null,
    "options": ["Creates a proxy that cannot be modified", "Creates a proxy and returns an object with a `revoke()` function that completely disables the proxy, throwing an error on any subsequent operation", "Creates a proxy that automatically deletes itself after 1 second", "It is not a real JavaScript method"],
    "correct_answer": "Creates a proxy and returns an object with a `revoke()` function that completely disables the proxy, throwing an error on any subsequent operation",
    "explanation": "`Proxy.revocable()` is useful when you need to completely cut off access to an object. Once `revoke()` is called, any attempt to interact with the proxy throws a `TypeError`."
  },
  {
    "id": 859,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Reflect.construct",
    "question": "What is the purpose of `Reflect.construct(target, argsList, newTarget)`?",
    "code_snippet": null,
    "options": ["To create a new object without using the `new` keyword, while correctly setting up the prototype chain", "To copy an object", "To freeze an object", "To convert a function to a class"],
    "correct_answer": "To create a new object without using the `new` keyword, while correctly setting up the prototype chain",
    "explanation": "`Reflect.construct` behaves exactly like the `new` operator, but as a function. It's incredibly useful inside Proxy `construct` traps to forward the instantiation to the original target."
  },
  {
    "id": 860,
    "level": "advanced",
    "module_id": "mod_14_advanced_objects_errors",
    "module_name": "Advanced Object & Error Handling",
    "type": "conceptual",
    "topic": "Error Handling Best Practices",
    "question": "Why is it considered bad practice to use `try...catch` for standard control flow (e.g., checking if a variable exists)?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It is significantly slower than standard conditional checks (like `if`), and makes debugging harder by masking the actual source of logical errors", "It is deprecated in ES6", "It causes memory leaks"],
    "correct_answer": "It is significantly slower than standard conditional checks (like `if`), and makes debugging harder by masking the actual source of logical errors",
    "explanation": "Throwing and catching errors is an expensive operation for the JS engine. `try...catch` should be reserved for truly exceptional, unrecoverable situations (like network failures or parsing invalid JSON), not for everyday logic."
  }
]
