[
  {
    "id": 381,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Function Basics",
    "question": "What is the primary purpose of a function in JavaScript?",
    "code_snippet": null,
    "options": ["To store a single data value", "To create a reusable block of code that performs a specific task", "To loop through an array", "To style HTML elements"],
    "correct_answer": "To create a reusable block of code that performs a specific task",
    "explanation": "Functions allow you to write code once and reuse it many times by 'calling' or 'invoking' the function, making your code modular and easier to maintain."
  },
  {
    "id": 382,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Function Declarations",
    "question": "Which keyword is used to declare a standard function in JavaScript?",
    "code_snippet": "_______ greet() {\n  console.log('Hello');\n}",
    "options": ["func", "def", "function", "method"],
    "correct_answer": "function",
    "explanation": "The `function` keyword is used to create a function declaration (also known as a function statement)."
  },
  {
    "id": 383,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Function Invocation",
    "question": "How do you execute (or 'call') a function named `calculateTotal`?",
    "code_snippet": "function calculateTotal() { /* code */ }\n\n// Call the function here:\n_______",
    "options": ["call calculateTotal", "execute calculateTotal", "calculateTotal()", "run calculateTotal[]"],
    "correct_answer": "calculateTotal()",
    "explanation": "To invoke a function, you write its name followed by parentheses `()`. If the function requires arguments, they go inside the parentheses."
  },
  {
    "id": 384,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Parameters vs Arguments",
    "question": "What is the difference between a 'parameter' and an 'argument'?",
    "code_snippet": null,
    "options": ["They are exactly the same thing", "Parameters are the names listed in the function definition; arguments are the real values passed to the function", "Arguments are the names in the definition; parameters are the real values", "Parameters are for numbers, arguments are for strings"],
    "correct_answer": "Parameters are the names listed in the function definition; arguments are the real values passed to the function",
    "explanation": "In `function add(a, b) { }`, `a` and `b` are parameters. When you call `add(5, 10)`, `5` and `10` are the arguments."
  },
  {
    "id": 385,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Parameters & Arguments",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function multiply(a, b) {\n  console.log(a * b);\n}\nmultiply(4, 5);",
    "options": ["45", "20", "9", "undefined"],
    "correct_answer": "20",
    "explanation": "The function `multiply` is called with arguments 4 and 5. Inside the function, `a` is 4 and `b` is 5. 4 * 5 equals 20."
  },
  {
    "id": 386,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Missing Arguments",
    "question": "What will be the exact output of the following code if we forget to pass the second argument?",
    "code_snippet": "function add(a, b) {\n  console.log(a + b);\n}\nadd(10);",
    "options": ["10", "NaN (Not-a-Number)", "undefined", "Error"],
    "correct_answer": "NaN (Not-a-Number)",
    "explanation": "If you pass fewer arguments than there are parameters, the missing parameters are set to `undefined`. In JS, `10 + undefined` evaluates to `NaN`."
  },
  {
    "id": 387,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "The return statement",
    "question": "What happens when a JavaScript function reaches a `return` statement?",
    "code_snippet": null,
    "options": ["It logs the value to the console", "It immediately stops executing the function and sends the value back to the caller", "It pauses the function for 1 second", "It returns the value but keeps running the rest of the function"],
    "correct_answer": "It immediately stops executing the function and sends the value back to the caller",
    "explanation": "The `return` keyword halts function execution and specifies the value to be returned to the code that called the function. Any code after `return` is ignored."
  },
  {
    "id": 388,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Implicit return",
    "question": "What will be the exact output of the following code? (Notice there is no `return` keyword!)",
    "code_snippet": "function sayHello() {\n  console.log('Hello');\n}\nlet result = sayHello();\nconsole.log(result);",
    "options": ["Hello", "undefined", "Hello undefined", "null"],
    "correct_answer": "undefined",
    "explanation": "The function logs 'Hello' to the console, but because it doesn't explicitly `return` a value, it implicitly returns `undefined`. Therefore, `result` is `undefined`."
  },
  {
    "id": 389,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "The return statement",
    "question": "Fill in the blank to correctly return the sum of `x` and `y` from the function.",
    "code_snippet": "function sum(x, y) {\n  _______ x + y;\n}",
    "options": ["give", "output", "return", "send"],
    "correct_answer": "return",
    "explanation": "The `return` keyword is the only way to output a value from a function back to the variable that called it."
  },
  {
    "id": 390,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Function Declarations vs Expressions",
    "question": "What is a 'Function Expression'?",
    "code_snippet": null,
    "options": ["A function that is written inside an HTML tag", "A function that is assigned to a variable (e.g., `const myFunc = function() {}`)", "A function that automatically runs when the page loads", "A function that returns an expression"],
    "correct_answer": "A function that is assigned to a variable (e.g., `const myFunc = function() {}`)",
    "explanation": "A function expression creates a function and assigns it to a variable. The function itself can be named or anonymous, but it is stored in the variable."
  },
  {
    "id": 391,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Hoisting Declarations",
    "question": "What will be the exact output of the following code? (Notice the function is called BEFORE it is declared!)",
    "code_snippet": "greet();\n\nfunction greet() {\n  console.log('Hi there');\n}",
    "options": ["Error", "undefined", "Hi there", "null"],
    "correct_answer": "Hi there",
    "explanation": "Function declarations are fully 'hoisted' to the top of their scope. This means you can call them before they appear in the code, and JavaScript will still know what they are."
  },
  {
    "id": 392,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Hoisting Expressions",
    "question": "What will happen when this code is executed? (Notice it's a function expression using `const`!)",
    "code_snippet": "greet();\n\nconst greet = function() {\n  console.log('Hi there');\n};",
    "options": ["It logs 'Hi there'", "It logs undefined", "It throws a ReferenceError", "It throws a SyntaxError"],
    "correct_answer": "It throws a ReferenceError",
    "explanation": "Unlike function declarations, function expressions are NOT hoisted. Because `greet` is declared with `const`, trying to call it before its initialization line results in a ReferenceError (Temporal Dead Zone)."
  },
  {
    "id": 393,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Function Scope",
    "question": "Variables declared inside a function with `let` or `const` are accessible from where?",
    "code_snippet": null,
    "options": ["Anywhere in the file", "Only inside that specific function (Local Scope)", "Only in the browser console", "In all other functions"],
    "correct_answer": "Only inside that specific function (Local Scope)",
    "explanation": "Variables declared inside a function are 'locally scoped'. They cannot be accessed from outside the function, which helps prevent naming collisions and keeps data safe."
  },
  {
    "id": 394,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Function Scope",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let message = 'Hello';\nfunction changeMessage() {\n  let message = 'Goodbye';\n}\nchangeMessage();\nconsole.log(message);",
    "options": ["Hello", "Goodbye", "undefined", "Error"],
    "correct_answer": "Hello",
    "explanation": "The `message` inside the function is a completely separate local variable. Changing it does not affect the global `message` variable. The global `message` remains 'Hello'."
  },
  {
    "id": 395,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Global Scope",
    "question": "If you declare a variable outside of any function, what scope does it belong to?",
    "code_snippet": null,
    "options": ["Local Scope", "Block Scope", "Global Scope", "Function Scope"],
    "correct_answer": "Global Scope",
    "explanation": "Variables declared outside of any function or block belong to the Global Scope. They can be accessed and modified from anywhere in the script."
  },
  {
    "id": 396,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Extra Arguments",
    "question": "What will be the exact output of the following code? (Notice we passed 3 arguments, but the function only has 2 parameters!)",
    "code_snippet": "function add(a, b) {\n  console.log(a + b);\n}\nadd(5, 10, 20);",
    "options": ["35", "15", "Error", "undefined"],
    "correct_answer": "15",
    "explanation": "JavaScript functions do not throw an error if you pass too many arguments. The extra arguments are simply ignored by the named parameters (though they can be accessed via the `arguments` object). 5 + 10 is 15."
  },
  {
    "id": 397,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Callbacks",
    "question": "What is a 'callback function'?",
    "code_snippet": null,
    "options": ["A function that calls itself", "A function passed as an argument to another function, to be executed later", "A function that returns another function", "A function that runs automatically when the page loads"],
    "correct_answer": "A function passed as an argument to another function, to be executed later",
    "explanation": "Callbacks are fundamental in JS. For example, in `setTimeout(myFunc, 1000)`, `myFunc` is the callback because it is passed as an argument and executed later by `setTimeout`."
  },
  {
    "id": 398,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Early Return",
    "question": "Fill in the blank to make the function stop executing and return false immediately if the user is not an admin.",
    "code_snippet": "function deleteAccount(user) {\n  if (!user.isAdmin) _______ false;\n  // Code to delete account...\n  return true;\n}",
    "options": ["stop", "exit", "return", "break"],
    "correct_answer": "return",
    "explanation": "This is called an 'early return' or 'guard clause'. If the condition is met, `return false;` immediately exits the function, preventing the deletion code from running."
  },
  {
    "id": 399,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Returning Expressions",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function isAdult(age) {\n  return age >= 18;\n}\nconsole.log(isAdult(20));",
    "options": ["true", "false", "18", "undefined"],
    "correct_answer": "true",
    "explanation": "You don't just have to return variables or strings; you can return the result of an expression. `20 >= 18` evaluates to the boolean `true`, which is then returned and logged."
  },
  {
    "id": 400,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Function Best Practices",
    "question": "What does the 'Single Responsibility Principle' mean when writing functions?",
    "code_snippet": null,
    "options": ["A function should only take one parameter", "A function should do one thing, and do it well", "A function should only have one line of code", "A function should only be called once"],
    "correct_answer": "A function should do one thing, and do it well",
    "explanation": "Functions should be small and focused. If a function is named `calculateTaxAndSendEmail()`, it's doing two things and should probably be split into two separate functions."
  }
]
[
  {
    "id": 401,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Arrow Functions",
    "question": "Fill in the blank to correctly write an arrow function that adds two numbers.",
    "code_snippet": "const add = (a, b) _______ a + b;",
    "options": ["->", "=>", ">>", "<="],
    "correct_answer": "=>",
    "explanation": "The arrow function syntax uses the 'fat arrow' (`=>`) to separate the parameters from the function body."
  },
  {
    "id": 402,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Arrow Functions",
    "question": "What is an 'implicit return' in an arrow function?",
    "code_snippet": null,
    "options": ["Using the return keyword explicitly", "Omitting the curly braces and return keyword for single-expression functions", "Returning undefined automatically", "Returning the function itself"],
    "correct_answer": "Omitting the curly braces and return keyword for single-expression functions",
    "explanation": "If an arrow function has only one expression and no curly braces `{}`, it automatically returns the result of that expression without needing the `return` keyword."
  },
  {
    "id": 403,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Arrow Functions",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const obj = {\n  name: 'Alice',\n  greet: () => {\n    console.log(this.name);\n  }\n};\nobj.greet();",
    "options": ["Alice", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "Arrow functions do not have their own `this` context. They inherit `this` from the surrounding scope (the global scope in this case). Since `this.name` doesn't exist globally, it logs `undefined`."
  },
  {
    "id": 404,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Arrow Functions",
    "question": "How do you correctly return an object literal implicitly from an arrow function?",
    "code_snippet": "const createUser = (name) _______ ;",
    "options": ["=> { name: name }", "=> ({ name: name })", "-> { name: name }", "=> return { name: name }"],
    "correct_answer": "=> ({ name: name })",
    "explanation": "To implicitly return an object, you MUST wrap the object literal in parentheses `()`. Otherwise, JavaScript thinks the curly braces are the function body block, not an object."
  },
  {
    "id": 405,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Default Parameters",
    "question": "Fill in the blank to set a default value of 'guest' for the role parameter.",
    "code_snippet": "function createUser(name, role _______ 'guest') { ... }",
    "options": ["=", "==", ":", "?? "],
    "correct_answer": "=",
    "explanation": "In ES6, you can assign default values to parameters directly in the function signature using the assignment operator (`=`)."
  },
  {
    "id": 406,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Default Parameters",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function greet(name = 'Stranger') {\n  console.log(`Hello ${name}`);\n}\ngreet(undefined);",
    "options": ["Hello undefined", "Hello Stranger", "Hello null", "Error"],
    "correct_answer": "Hello Stranger",
    "explanation": "In JavaScript, passing `undefined` to a parameter with a default value will trigger the default value. It acts as if you passed nothing at all."
  },
  {
    "id": 407,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Default Parameters",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function greet(name = 'Stranger') {\n  console.log(`Hello ${name}`);\n}\ngreet(null);",
    "options": ["Hello undefined", "Hello Stranger", "Hello null", "Error"],
    "correct_answer": "Hello null",
    "explanation": "Unlike `undefined`, passing `null` does NOT trigger the default parameter. `null` is considered a valid, intentional value, so the function uses it."
  },
  {
    "id": 408,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Rest Parameters",
    "question": "What does the Rest parameter (`...args`) do in a function definition?",
    "code_snippet": null,
    "options": ["Spreads an array into individual arguments", "Collects all remaining arguments into an array", "Restricts the function to only accept one argument", "Restarts the function execution"],
    "correct_answer": "Collects all remaining arguments into an array",
    "explanation": "The Rest parameter gathers all leftover arguments passed to the function and packs them neatly into a real Array."
  },
  {
    "id": 409,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Rest Parameters",
    "question": "Fill in the blank to collect any number of arguments into an array called `nums`.",
    "code_snippet": "function sum(_______nums) { ... }",
    "options": ["...", "**", "@@", "&"],
    "correct_answer": "...",
    "explanation": "The three dots (`...`) syntax is used to denote the Rest parameter in function definitions."
  },
  {
    "id": 410,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Rest Parameters",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function logArgs(a, b, ...rest) {\n  console.log(rest.length);\n}\nlogArgs(1, 2, 3, 4, 5);",
    "options": ["5", "3", "2", "Error"],
    "correct_answer": "3",
    "explanation": "The first two arguments (1 and 2) are assigned to `a` and `b`. The rest parameter collects the remaining three arguments (3, 4, 5) into the `rest` array. Its length is 3."
  },
  {
    "id": 411,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Rest Parameters",
    "question": "Where must the Rest parameter be placed in a function's parameter list?",
    "code_snippet": null,
    "options": ["At the beginning", "In the middle", "At the very end", "Anywhere"],
    "correct_answer": "At the very end",
    "explanation": "The Rest parameter must always be the last parameter in the function definition. It wouldn't make sense to have parameters after it, because the Rest parameter 'catches' everything else."
  },
  {
    "id": 412,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Spread vs Rest",
    "question": "Although they use the same syntax (`...`), how do Rest and Spread differ in function contexts?",
    "code_snippet": null,
    "options": ["Rest is for objects, Spread is for arrays", "Rest gathers arguments into an array; Spread expands an array into individual arguments", "They are exactly the same", "Rest is deprecated"],
    "correct_answer": "Rest gathers arguments into an array; Spread expands an array into individual arguments",
    "explanation": "In a function definition (parameters), `...` is Rest (gathering). In a function call (arguments), `...` is Spread (expanding)."
  },
  {
    "id": 413,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Spread in Function Calls",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const numbers = [5, 1, 9, 2];\nconsole.log(Math.max(...numbers));",
    "options": ["[5, 1, 9, 2]", "9", "5", "Error"],
    "correct_answer": "9",
    "explanation": "The Spread operator expands the array into individual arguments. The code effectively becomes `Math.max(5, 1, 9, 2)`, which correctly returns the highest number: 9."
  },
  {
    "id": 414,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Arrow Functions",
    "question": "Do arrow functions have their own `arguments` object?",
    "code_snippet": null,
    "options": ["Yes, just like regular functions", "No, they inherit the `arguments` object from the enclosing regular function scope", "No, they throw an error if you use it", "Yes, but it's called `args`"],
    "correct_answer": "No, they inherit the `arguments` object from the enclosing regular function scope",
    "explanation": "Arrow functions do not bind their own `arguments` object. If you need a list of all arguments in an arrow function, you should use the Rest parameter (`...args`) instead."
  },
  {
    "id": 415,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Arrow Functions",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "const multiply = (a, b) => a * b;\nconsole.log(multiply(3, 4));",
    "options": ["12", "undefined", "Error", "34"],
    "correct_answer": "12",
    "explanation": "This is a standard arrow function with an implicit return. It multiplies 3 and 4, returning 12."
  },
  {
    "id": 416,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "Default Parameters",
    "question": "Fill in the blank to use the first parameter to calculate the default value of the second.",
    "code_snippet": "function createSquare(side, area = side _______ side) { ... }",
    "options": ["+", "*", "-", "/"],
    "correct_answer": "*",
    "explanation": "Default parameters can reference previously defined parameters. Here, if `area` isn't provided, it defaults to `side * side`."
  },
  {
    "id": 417,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "IIFE",
    "question": "What is an IIFE (Immediately Invoked Function Expression)?",
    "code_snippet": null,
    "options": ["A function that runs after 1 second", "A function that is executed immediately right after it is created", "A function that imports external files", "A function that loops infinitely"],
    "correct_answer": "A function that is executed immediately right after it is created",
    "explanation": "An IIFE runs as soon as the JS engine encounters it. It's often used to create a private scope and avoid polluting the global namespace."
  },
  {
    "id": 418,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "IIFE",
    "question": "Fill in the blank to correctly write and invoke an arrow function IIFE.",
    "code_snippet": "_______ => { console.log('Runs immediately!'); })();",
    "options": ["(()", "(function", "func", "=>"],
    "correct_answer": "(()",
    "explanation": "To make an arrow function an IIFE, you wrap the entire arrow function in parentheses `(() => { ... })` and then add `()` at the very end to invoke it."
  },
  {
    "id": 419,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Spread in Function Calls",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function introduce(firstName, lastName) {\n  console.log(`${firstName} ${lastName}`);\n}\nconst names = ['John', 'Doe'];\nintroduce(...names);",
    "options": ["John Doe", "['John', 'Doe']", "John undefined", "Error"],
    "correct_answer": "John Doe",
    "explanation": "The Spread operator unpacks the `names` array. The function call effectively becomes `introduce('John', 'Doe')`."
  },
  {
    "id": 420,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Arrow Functions",
    "question": "Why can't an arrow function be used as a constructor with the `new` keyword?",
    "code_snippet": null,
    "options": ["It's too slow", "It doesn't have its own `this` context or prototype property", "It's a syntax error in strict mode", "Arrow functions can only return strings"],
    "correct_answer": "It doesn't have its own `this` context or prototype property",
    "explanation": "Constructors require their own `this` context to bind to the newly created object. Because arrow functions inherit `this` lexically, using `new` with them throws a TypeError."
  }
]

[
  {
    "id": 421,
    "level": "advanced",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Closures",
    "question": "What is a 'Closure' in JavaScript?",
    "code_snippet": null,
    "options": ["A way to permanently lock a variable so it cannot be changed", "A function bundled together with references to its surrounding lexical environment", "A method to close a database connection", "A syntax error that occurs when brackets are mismatched"],
    "correct_answer": "A function bundled together with references to its surrounding lexical environment",
    "explanation": "A closure gives a function access to its outer scope's variables even after the outer function has finished executing. It 'closes over' those variables, keeping them alive in memory."
  },
  {
    "id": 422,
    "level": "advanced",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Closures",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function createCounter() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nconst counter = createCounter();\nconsole.log(counter());\nconsole.log(counter());",
    "options": ["1, 1", "1, 2", "0, 1", "Error"],
    "correct_answer": "1, 2",
    "explanation": "Because of the closure, the inner function remembers the `count` variable from `createCounter`'s scope. The first call increments it to 1. The second call remembers it was 1, and increments it to 2."
  },
  {
    "id": 423,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "The 'this' keyword",
    "question": "When a standard function is called as a method of an object (e.g., `obj.myMethod()`), what does the `this` keyword refer to?",
    "code_snippet": null,
    "options": ["The global window object", "The function itself", "The object that is calling the method (the object to the left of the dot)", "It is always undefined"],
    "correct_answer": "The object that is calling the method (the object to the left of the dot)",
    "explanation": "In a regular function, `this` is determined by *how* the function is called. If it's called via an object (like `obj.method()`), `this` refers to that specific object."
  },
  {
    "id": 424,
    "level": "advanced",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "The 'this' keyword",
    "question": "What will be the exact output of the following code? (Watch out for lost context!)",
    "code_snippet": "const user = {\n  name: 'Alice',\n  getName: function() { return this.name; }\n};\nconst extractName = user.getName;\nconsole.log(extractName());",
    "options": ["Alice", "undefined", "null", "Error"],
    "correct_answer": "undefined",
    "explanation": "When you assign `user.getName` to a variable without calling it, it loses its connection to the `user` object. When `extractName()` is called, it's called as a standalone function, so `this` defaults to the global object (where `this.name` is undefined)."
  },
  {
    "id": 425,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "code-fill-in-blank",
    "topic": "call, apply, bind",
    "question": "Which method allows you to explicitly set the `this` context for a function and returns a BRAND NEW function without immediately executing it?",
    "code_snippet": "const boundFunc = originalFunc._______(newContext);",
    "options": ["call()", "apply()", "bind()", "this()"],
    "correct_answer": "bind()",
    "explanation": "`bind()` creates a new function with `this` permanently bound to the provided value. It does not execute the original function immediately, unlike `call()` and `apply()`."
  },
  {
    "id": 426,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "call, apply, bind",
    "question": "What is the main difference between `call()` and `apply()`?",
    "code_snippet": null,
    "options": ["`call()` is for objects, `apply()` is for arrays", "`call()` takes arguments as a comma-separated list; `apply()` takes arguments as an array", "`call()` is asynchronous, `apply()` is synchronous", "There is no difference"],
    "correct_answer": "`call()` takes arguments as a comma-separated list; `apply()` takes arguments as an array",
    "explanation": "Both methods immediately invoke the function with a specified `this` context. The only difference is how they handle subsequent arguments: `func.call(obj, arg1, arg2)` vs `func.apply(obj, [arg1, arg2])`."
  },
  {
    "id": 427,
    "level": "advanced",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "call, apply, bind",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "function greet(greeting) {\n  console.log(`${greeting}, ${this.name}`);\n}\nconst user = { name: 'Bob' };\ngreet.call(user, 'Hello');",
    "options": ["Hello, undefined", "Hello, Bob", "undefined, Bob", "Error"],
    "correct_answer": "Hello, Bob",
    "explanation": "`call()` is used to invoke the function. The first argument sets `this` to the `user` object. The second argument ('Hello') is passed as the `greeting` parameter. It correctly logs 'Hello, Bob'."
  },
  {
    "id": 428,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Scope Chain",
    "question": "How does the 'Scope Chain' work in JavaScript?",
    "code_snippet": null,
    "options": ["Functions can only access global variables", "An inner function can access variables of its outer function, which can access global variables, but not vice versa", "Variables in the same scope overwrite each other automatically", "Scope only applies to `var`, not `let` or `const`"],
    "correct_answer": "An inner function can access variables of its outer function, which can access global variables, but not vice versa",
    "explanation": "When a variable is used, JS looks in the local scope. If not found, it looks in the outer scope, and so on up to the global scope. It never looks 'down' into inner scopes."
  },
  {
    "id": 429,
    "level": "advanced",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "output-prediction",
    "topic": "Scope Chain",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let x = 10;\nfunction outer() {\n  let x = 20;\n  function inner() {\n    let x = 30;\n    console.log(x);\n  }\n  inner();\n}\nouter();",
    "options": ["10", "20", "30", "undefined"],
    "correct_answer": "30",
    "explanation": "The `inner` function has its own local variable `x = 30`. Because it finds `x` in its own immediate scope, it uses that value and doesn't need to look up the scope chain to the `outer` function or the global scope."
  },
  {
    "id": 430,
    "level": "intermediate",
    "module_id": "mod_06_functions",
    "module_name": "Functions",
    "type": "conceptual",
    "topic": "Pure Functions",
    "question": "What defines a 'Pure Function' in JavaScript?",
    "code_snippet": null,
    "options": ["A function that only uses arrow syntax", "A function that always returns the same output for the same input and has no side effects", "A function that does not take any parameters", "A function that only contains a single return statement"],
    "correct_answer": "A function that always returns the same output for the same input and has no side effects",
    "explanation": "Pure functions are a core concept of functional programming. They don't modify external variables, don't make API calls, and don't rely on external state. Given the same arguments, they will *always* return the exact same result."
  }
]
