[
  {
    "id": 201,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Operators Basics",
    "question": "In JavaScript, what is an 'operator'?",
    "code_snippet": null,
    "options": ["A special type of variable", "A symbol or keyword used to perform operations on operands (values/variables)", "A function that loops through an array", "A method to connect to a database"],
    "correct_answer": "A symbol or keyword used to perform operations on operands (values/variables)",
    "explanation": "Operators are the building blocks of logic and math in JS. For example, in '5 + 3', the '+' is the operator, and 5 and 3 are the operands."
  },
  {
    "id": 202,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Arithmetic Operators",
    "question": "Which operator is used to add two numbers together in JavaScript?",
    "code_snippet": "let sum = 10 _______ 5; // sum is 15",
    "options": ["&", "+", "add", "plus"],
    "correct_answer": "+",
    "explanation": "The plus sign (+) is the standard arithmetic operator for addition."
  },
  {
    "id": 203,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Arithmetic Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(8 - 3);",
    "options": ["5", "11", "24", "-5"],
    "correct_answer": "5",
    "explanation": "The minus sign (-) is the subtraction operator. 8 minus 3 equals 5."
  },
  {
    "id": 204,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Arithmetic Operators",
    "question": "Which operator is used for multiplication?",
    "code_snippet": "let area = width _______ height;",
    "options": ["x", "*", "×", "m"],
    "correct_answer": "*",
    "explanation": "The asterisk (*) is the multiplication operator in JavaScript. You cannot use the letter 'x' or the mathematical symbol '×'."
  },
  {
    "id": 205,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Arithmetic Operators",
    "question": "Which operator is used to divide one number by another?",
    "code_snippet": "let half = 100 _______ 2; // half is 50",
    "options": ["÷", "/", "div", "\\"],
    "correct_answer": "/",
    "explanation": "The forward slash (/) is the division operator in JavaScript."
  },
  {
    "id": 206,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Arithmetic Operators",
    "question": "What does the Modulus operator (%) do?",
    "code_snippet": null,
    "options": ["Calculates the percentage of a number", "Returns the remainder of a division", "Divides a number by 100", "Rounds a number to the nearest integer"],
    "correct_answer": "Returns the remainder of a division",
    "explanation": "The modulus operator (%) divides the numbers and returns the remainder. For example, 10 % 3 is 1, because 3 goes into 10 three times (9) with 1 left over."
  },
  {
    "id": 207,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Arithmetic Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(14 % 4);",
    "options": ["3.5", "3", "2", "4"],
    "correct_answer": "2",
    "explanation": "14 divided by 4 is 3 with a remainder of 2. The modulus operator (%) returns that remainder, which is 2."
  },
  {
    "id": 208,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Arithmetic Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(10 % 2);",
    "options": ["5", "0", "1", "2"],
    "correct_answer": "0",
    "explanation": "10 divided by 2 is exactly 5 with no remainder. Therefore, the modulus is 0. (This is a common way to check if a number is even!)."
  },
  {
    "id": 209,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Arithmetic Operators",
    "question": "Which operator is used for exponentiation (raising a number to a power) in modern JavaScript (ES7+)?",
    "code_snippet": "let square = 5 _______ 2; // square is 25",
    "options": ["^", "**", "^^", "pow"],
    "correct_answer": "**",
    "explanation": "The double asterisk (**) is the exponentiation operator. 5 ** 2 means 5 to the power of 2 (5 * 5 = 25)."
  },
  {
    "id": 210,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Arithmetic Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(2 ** 3);",
    "options": ["6", "8", "5", "23"],
    "correct_answer": "8",
    "explanation": "2 ** 3 means 2 to the power of 3 (2 * 2 * 2), which equals 8."
  },
  {
    "id": 211,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Assignment Operators",
    "question": "What is the primary purpose of the single equals sign (=) operator in JavaScript?",
    "code_snippet": null,
    "options": ["To check if two values are equal", "To assign a value to a variable", "To add two numbers together", "To declare a function"],
    "correct_answer": "To assign a value to a variable",
    "explanation": "The single equals sign (=) is the assignment operator. It assigns the value on its right to the variable on its left. (Do not confuse it with == or ===, which check for equality)."
  },
  {
    "id": 212,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Assignment Operators",
    "question": "Which operator adds a value to a variable and then reassigns the result to that same variable?",
    "code_snippet": "let score = 10;\nscore _______ 5; // score is now 15",
    "options": ["=+", "+=", "add=", "plus="],
    "correct_answer": "+=",
    "explanation": "The addition assignment operator (+=) adds the right operand to the left operand and assigns the result. 'score += 5' is shorthand for 'score = score + 5'."
  },
  {
    "id": 213,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Assignment Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let x = 10;\nx -= 4;\nconsole.log(x);",
    "options": ["14", "6", "4", "10"],
    "correct_answer": "6",
    "explanation": "The '-=' operator subtracts the right value from the left and reassigns it. 10 - 4 equals 6."
  },
  {
    "id": 214,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Assignment Operators",
    "question": "Fill in the blank with the correct shorthand operator to multiply 'y' by 3.",
    "code_snippet": "let y = 5;\ny _______ 3; // y is now 15",
    "options": ["*= ", "x= ", "mul= ", "*= "],
    "correct_answer": "*= ",
    "explanation": "The multiplication assignment operator (*=) multiplies the variable by the value and reassigns it. 'y *= 3' is the same as 'y = y * 3'."
  },
  {
    "id": 215,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Assignment Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "let z = 20;\nz /= 4;\nconsole.log(z);",
    "options": ["5", "80", "16", "4"],
    "correct_answer": "5",
    "explanation": "The '/=' operator divides the variable by the value and reassigns it. 20 divided by 4 equals 5."
  },
  {
    "id": 216,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Assignment Operators",
    "question": "Which shorthand operator would you use to find the remainder of a division and assign it back to the variable?",
    "code_snippet": "let num = 10;\nnum _______ 3; // num is now 1",
    "options": ["%= ", "/= ", "%= ", "rem= "],
    "correct_answer": "%= ",
    "explanation": "The remainder assignment operator (%=) divides the variable by the value and assigns the remainder back to the variable."
  },
  {
    "id": 217,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Operator Precedence",
    "question": "What does 'Operator Precedence' mean in JavaScript?",
    "code_snippet": null,
    "options": ["The order in which variables are declared", "The rulebook that determines which operations are performed first in an expression", "The speed at which operators execute", "The priority of functions over variables"],
    "correct_answer": "The rulebook that determines which operations are performed first in an expression",
    "explanation": "Operator precedence determines the order of evaluation. For example, multiplication has higher precedence than addition, so it happens first (just like in standard math)."
  },
  {
    "id": 218,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Operator Precedence",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(2 + 3 * 4);",
    "options": ["20", "14", "24", "9"],
    "correct_answer": "14",
    "explanation": "Multiplication (*) has higher precedence than addition (+). So, 3 * 4 is calculated first (12), and then 2 is added, resulting in 14."
  },
  {
    "id": 219,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Operator Precedence",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log((2 + 3) * 4);",
    "options": ["20", "14", "24", "9"],
    "correct_answer": "20",
    "explanation": "Parentheses () have the highest precedence. They force the addition (2 + 3 = 5) to happen first, and then the result is multiplied by 4 (5 * 4 = 20)."
  },
  {
    "id": 220,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Operator Precedence",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(10 - 2 * 3);",
    "options": ["24", "4", "16", "6"],
    "correct_answer": "4",
    "explanation": "Multiplication happens before subtraction. 2 * 3 is 6. Then, 10 - 6 equals 4."
  },
  {
    "id": 221,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Comparison Operators",
    "question": "What data type do comparison operators (like >, <, ==) always return in JavaScript?",
    "code_snippet": null,
    "options": ["String", "Number", "Boolean", "Object"],
    "correct_answer": "Boolean",
    "explanation": "Comparison operators evaluate an expression and always return a boolean value: either `true` or `false`."
  },
  {
    "id": 222,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Comparison Operators",
    "question": "Which operator is used to check if the left operand is greater than OR equal to the right operand?",
    "code_snippet": "let age = 18;\nlet canVote = age _______ 18;",
    "options": [">", "<=", ">=", "=="],
    "correct_answer": ">=",
    "explanation": "The `>=` operator checks if the value on the left is greater than or exactly equal to the value on the right."
  },
  {
    "id": 223,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Comparison Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(10 < 5);",
    "options": ["true", "false", "10", "5"],
    "correct_answer": "false",
    "explanation": "10 is not less than 5, so the less-than operator (<) evaluates to false."
  },
  {
    "id": 224,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Comparison Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(7 <= 7);",
    "options": ["true", "false", "7", "Error"],
    "correct_answer": "true",
    "explanation": "The `<=` operator means 'less than OR equal to'. Since 7 is exactly equal to 7, the expression evaluates to true."
  },
  {
    "id": 225,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Equality Operators",
    "question": "What is the main difference between the `==` and `===` operators?",
    "code_snippet": null,
    "options": ["`==` is for strings, `===` is for numbers", "`==` checks value and type, `===` checks only value", "`==` checks value with type coercion, `===` checks both value and type strictly", "There is no difference"],
    "correct_answer": "`==` checks value with type coercion, `===` checks both value and type strictly",
    "explanation": "The double equals (`==`) performs type conversion before comparing (e.g., `5 == '5'` is true). The triple equals (`===`) does not convert types; both the value and the data type must match (e.g., `5 === '5'` is false)."
  },
  {
    "id": 226,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Equality Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(10 == '10');",
    "options": ["true", "false", "10", "Error"],
    "correct_answer": "true",
    "explanation": "The `==` operator performs type coercion. It converts the string `'10'` to the number `10` before comparing, making them loosely equal."
  },
  {
    "id": 227,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Equality Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(10 === '10');",
    "options": ["true", "false", "10", "Error"],
    "correct_answer": "false",
    "explanation": "The `===` operator is strict. It checks both value and type. Since 10 is a Number and '10' is a String, they are not strictly equal."
  },
  {
    "id": 228,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Equality Operators",
    "question": "What is 'Type Coercion' in JavaScript?",
    "code_snippet": null,
    "options": ["Deleting a variable from memory", "The automatic or implicit conversion of values from one data type to another", "Writing code in TypeScript instead of JavaScript", "A method to sort an array"],
    "correct_answer": "The automatic or implicit conversion of values from one data type to another",
    "explanation": "Type coercion is when JavaScript automatically converts a value from one type to another (like String to Number) to make an operation work, which is what happens with the `==` operator."
  },
  {
    "id": 229,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Equality Operators",
    "question": "Which equality operator is considered best practice in modern JavaScript development?",
    "code_snippet": null,
    "options": ["== (Loose equality)", "=== (Strict equality)", "Both are equally good", "Neither, you should use ="],
    "correct_answer": "=== (Strict equality)",
    "explanation": "Using `===` is highly recommended because it prevents unexpected bugs caused by JavaScript's confusing type coercion rules. It makes your code more predictable."
  },
  {
    "id": 230,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Equality Operators",
    "question": "What will be the exact output of this famous JavaScript quirk?",
    "code_snippet": "console.log(null == undefined);",
    "options": ["true", "false", "null", "Error"],
    "correct_answer": "true",
    "explanation": "In JavaScript, `null` and `undefined` are considered loosely equal when using `==`. (However, `null === undefined` is false, because they are different types)."
  },
  {
    "id": 231,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Equality Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(null === undefined);",
    "options": ["true", "false", "null", "Error"],
    "correct_answer": "false",
    "explanation": "Because `===` checks both value and type, and `null` is an object while `undefined` is its own type, they are not strictly equal."
  },
  {
    "id": 232,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Logical Operators",
    "question": "What does the Logical AND (`&&`) operator do?",
    "code_snippet": null,
    "options": ["Returns true if AT LEAST ONE operand is true", "Returns true if BOTH operands are true", "Reverses the boolean value", "Adds two numbers together"],
    "correct_answer": "Returns true if BOTH operands are true",
    "explanation": "The `&&` operator evaluates to true only if both the left and right sides are true. If either side is false, the whole expression is false."
  },
  {
    "id": 233,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "conceptual",
    "topic": "Logical Operators",
    "question": "What does the Logical OR (`||`) operator do?",
    "code_snippet": null,
    "options": ["Returns true if AT LEAST ONE operand is true", "Returns true only if BOTH operands are true", "Reverses the boolean value", "Checks if two strings are equal"],
    "correct_answer": "Returns true if AT LEAST ONE operand is true",
    "explanation": "The `||` operator evaluates to true if the left side is true, OR if the right side is true. It only evaluates to false if BOTH sides are false."
  },
  {
    "id": 234,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "code-fill-in-blank",
    "topic": "Logical Operators",
    "question": "Which operator is used for Logical NOT, which reverses a boolean value?",
    "code_snippet": "let isRaining = true;\nlet isSunny = _______ isRaining;",
    "options": ["!!", "&&", "||", "!"],
    "correct_answer": "!",
    "explanation": "The exclamation mark (`!`) is the Logical NOT operator. It turns `true` into `false`, and `false` into `true`."
  },
  {
    "id": 235,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Logical Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(true && false);",
    "options": ["true", "false", "null", "Error"],
    "correct_answer": "false",
    "explanation": "The `&&` (AND) operator requires both sides to be true. Since the right side is false, the entire expression evaluates to false."
  },
  {
    "id": 236,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Logical Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(false || true);",
    "options": ["true", "false", "null", "Error"],
    "correct_answer": "true",
    "explanation": "The `||` (OR) operator only needs one side to be true. Since the right side is true, the entire expression evaluates to true."
  },
  {
    "id": 237,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Logical Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(!false);",
    "options": ["true", "false", "-1", "Error"],
    "correct_answer": "true",
    "explanation": "The `!` (NOT) operator reverses the boolean value. The opposite of `false` is `true`."
  },
  {
    "id": 238,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Logical Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log((5 > 2) && (10 < 20));",
    "options": ["true", "false", "5", "Error"],
    "correct_answer": "true",
    "explanation": "First, `5 > 2` evaluates to true. Second, `10 < 20` evaluates to true. Finally, `true && true` evaluates to true."
  },
  {
    "id": 239,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Logical Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log((10 === '10') || (5 > 3));",
    "options": ["true", "false", "5", "Error"],
    "correct_answer": "true",
    "explanation": "First, `10 === '10'` evaluates to false (strict equality). Second, `5 > 3` evaluates to true. Finally, `false || true` evaluates to true because it's an OR statement."
  },
  {
    "id": 240,
    "level": "beginner",
    "module_id": "mod_03_operators",
    "module_name": "Operators & Expressions",
    "type": "output-prediction",
    "topic": "Logical Operators",
    "question": "What will be the exact output of the following code?",
    "code_snippet": "console.log(!(10 > 5));",
    "options": ["true", "false", "10", "Error"],
    "correct_answer": "false",
    "explanation": "First, `10 > 5` evaluates to true. Then, the `!` (NOT) operator reverses it, turning `true` into `false`."
  }
]
