[
  {
    "id": 1,
    "level": "beginner",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "What is IaC?",
    "question": "What is the core philosophy of 'Infrastructure as Code' (IaC)?",
    "code_snippet": null,
    "options": ["Writing bash scripts to manually configure servers", "Managing and provisioning infrastructure through machine-readable definition files (code) rather than physical hardware configuration or interactive configuration tools", "Using the cloud provider's web console to click and create resources", "Storing your infrastructure passwords in a Git repository"],
    "correct_answer": "Managing and provisioning infrastructure through machine-readable definition files (code) rather than physical hardware configuration or interactive configuration tools",
    "explanation": "IaC treats infrastructure exactly like application software. It can be version-controlled (Git), peer-reviewed (Pull Requests), tested, and automated, eliminating 'configuration drift' and human error."
  },
  {
    "id": 2,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Declarative vs Imperative",
    "question": "Terraform is a 'Declarative' IaC tool. How does Declarative differ from 'Imperative' (like a bash script or Ansible)?",
    "code_snippet": null,
    "options": ["Declarative specifies the exact step-by-step commands to reach a state; Imperative specifies the final desired state", "Declarative specifies the final desired state, and the tool figures out the steps to get there; Imperative specifies the exact step-by-step commands to execute", "Declarative is for databases; Imperative is for networks", "There is no difference"],
    "correct_answer": "Declarative specifies the final desired state, and the tool figures out the steps; Imperative specifies the exact step-by-step commands",
    "explanation": "In Imperative code, you write: 'Check if VPC exists. If not, create it. Then check if subnet exists...' In Declarative Terraform, you just write: 'I want a VPC and a Subnet.' Terraform's engine calculates the exact API calls needed to make reality match your code."
  },
  {
    "id": 3,
    "level": "beginner",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Providers",
    "question": "What is a 'Provider' in Terraform?",
    "code_snippet": null,
    "options": ["A cloud computing server", "A plugin that Terraform downloads to understand and interact with a specific API (like AWS, Azure, GCP, or GitHub)", "A type of database", "A security group"],
    "correct_answer": "A plugin that Terraform downloads to understand and interact with a specific API",
    "explanation": "Terraform core doesn't know what an 'AWS EC2 Instance' is. The `aws` provider acts as the translator, taking your Terraform code and converting it into the specific AWS API calls required to create that instance."
  },
  {
    "id": 4,
    "level": "beginner",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "terraform init",
    "question": "What does the `terraform init` command do?",
    "code_snippet": null,
    "options": ["Creates the actual cloud resources", "Initializes the working directory, downloads the required Provider plugins, and configures the backend for State storage", "Deletes the state file", "Formats the code"],
    "correct_answer": "Initializes the working directory, downloads the required Provider plugins, and configures the backend for State storage",
    "explanation": "You must run `terraform init` every time you clone a new Terraform repository or add a new Provider to your code. It prepares your local environment to execute the code."
  },
  {
    "id": 5,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "terraform plan",
    "question": "Why is running `terraform plan` considered a mandatory safety step before applying changes?",
    "code_snippet": null,
    "options": ["It automatically fixes syntax errors", "It performs a 'dry run', comparing your code to the current State file and showing you exactly what resources will be created, updated, or destroyed before you commit", "It deploys the code to a staging environment", "It backs up the database"],
    "correct_answer": "It performs a 'dry run', showing you exactly what resources will be created, updated, or destroyed before you commit",
    "explanation": "A plan might reveal that a seemingly small change (like modifying a security group) will actually force the destruction and recreation of your production database. `terraform plan` catches these catastrophic surprises before they happen."
  },
  {
    "id": 6,
    "level": "beginner",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "terraform apply",
    "question": "What does `terraform apply` do?",
    "code_snippet": null,
    "options": ["It only formats the code", "It executes the plan, making the actual API calls to the cloud provider to create, modify, or destroy resources to match your code", "It deletes the Terraform code", "It downloads the providers"],
    "correct_answer": "It executes the plan, making the actual API calls to the cloud provider to match your code",
    "explanation": "When you run `terraform apply`, Terraform shows you the plan again and asks for explicit confirmation (typing 'yes'). Once confirmed, it provisions the real-world infrastructure."
  },
  {
    "id": 7,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "The State File",
    "question": "What is the purpose of the `terraform.tfstate` file?",
    "code_snippet": null,
    "options": ["It stores the source code", "It is a JSON file that maps your Terraform configuration to the real-world resources (IDs, attributes) in the cloud, acting as the source of truth", "It stores your AWS credentials", "It is a backup of the cloud database"],
    "correct_answer": "It maps your Terraform configuration to the real-world resources, acting as the source of truth",
    "explanation": "Because cloud resources have dynamic IDs (like `i-0123456789abcdef0`), Terraform needs a way to remember which code block created which real-world ID. The State file holds this mapping. Without it, Terraform wouldn't know what to update or destroy."
  },
  {
    "id": 8,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Remote State",
    "question": "Why is storing the State file locally on your laptop considered a terrible practice for team environments?",
    "code_snippet": null,
    "options": ["It makes the code run slower", "It prevents team collaboration, risks accidental deletion, and exposes sensitive data (like database passwords stored in state) to anyone with access to your laptop", "Local state is deprecated", "It doesn't support AWS"],
    "correct_answer": "It prevents team collaboration, risks accidental deletion, and exposes sensitive data",
    "explanation": "State files often contain sensitive outputs (like RDS passwords). By using a Remote Backend (like AWS S3), the state is securely stored, shared with the whole team, and encrypted at rest."
  },
  {
    "id": 9,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "State Locking",
    "question": "When using an S3 bucket for remote state, why must you also configure a DynamoDB table for 'State Locking'?",
    "code_snippet": null,
    "options": ["To encrypt the state file", "To prevent two team members (or CI pipelines) from running `terraform apply` at the exact same time, which would corrupt the state file", "To back up the state file", "To format the code"],
    "correct_answer": "To prevent concurrent `terraform apply` executions, which would corrupt the state file",
    "explanation": "If Developer A and Developer B run `apply` simultaneously, they will both read the same state, make conflicting changes, and overwrite each other. DynamoDB locks the state file during an `apply`, forcing the second person to wait."
  },
  {
    "id": 10,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "code-fill-in-blank",
    "topic": "Variables",
    "question": "Fill in the blank to correctly declare an input variable in Terraform.",
    "code_snippet": "_______ \"region\" {\n  type    = string\n  default = \"us-east-1\"\n}",
    "options": ["input", "variable", "param", "const"],
    "correct_answer": "variable",
    "explanation": "The `variable` block defines an input parameter that can be passed in at runtime, making your Terraform code reusable across different environments (dev, staging, prod)."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Variable Precedence",
    "question": "If a variable has a `default` value in your code, but you also provide a value for it in a `terraform.tfvars` file, which value does Terraform use?",
    "code_snippet": null,
    "options": ["The default value in the code", "The value in the `terraform.tfvars` file", "It throws an error", "It merges them together"],
    "correct_answer": "The value in the `terraform.tfvars` file",
    "explanation": "Terraform has a strict variable precedence order. Values provided in `.tfvars` files (or via CLI flags) will always override the `default` values defined in the `variable` block."
  },
  {
    "id": 12,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Outputs",
    "question": "What is the purpose of an `output` block in Terraform?",
    "code_snippet": null,
    "options": ["To create cloud resources", "To export specific values (like an IP address or database URL) after resources are created, making them available to humans or other Terraform modules", "To delete resources", "To format the code"],
    "correct_answer": "To export specific values after resources are created, making them available to humans or other modules",
    "explanation": "If you create a Load Balancer, its DNS name is randomly generated by AWS. You use an `output` block to print that DNS name to the terminal so you know where to point your domain."
  },
  {
    "id": 13,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Data Sources",
    "question": "What is the difference between a `resource` block and a `data` block in Terraform?",
    "code_snippet": null,
    "options": ["They are the same", "`resource` creates and manages new infrastructure; `data` fetches read-only information about EXISTING infrastructure that was created outside of Terraform", "`data` creates resources; `resource` reads them", "`data` is deprecated"],
    "correct_answer": "`resource` creates new infrastructure; `data` fetches read-only info about EXISTING infrastructure",
    "explanation": "If your company already has a shared VPC created by another team, you don't recreate it. You use a `data \"aws_vpc\" \"existing\"` block to look it up and reference its ID in your own code."
  },
  {
    "id": 14,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Local Values",
    "question": "What is the purpose of the `locals` block in Terraform?",
    "code_snippet": null,
    "options": ["To store sensitive passwords", "To define named expressions (like string concatenation or conditional logic) to keep your code DRY (Don't Repeat Yourself) and readable", "To create local variables on the cloud server", "To format the code"],
    "correct_answer": "To define named expressions to keep your code DRY and readable",
    "explanation": "If you need to use the exact same complex string (like `\"${var.project}-${var.environment}-app\"`) in 10 different resources, you define it once in `locals` and reference it as `local.app_name`."
  },
  {
    "id": 15,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Implicit vs Explicit Dependencies",
    "question": "When should you use the `depends_on` meta-argument?",
    "code_snippet": null,
    "options": ["For every single resource", "Only when Terraform cannot automatically infer a dependency (e.g., an app depends on a database, but the connection string is passed via a separate ConfigMap)", "It is deprecated", "Only for destroying resources"],
    "correct_answer": "Only when Terraform cannot automatically infer a dependency",
    "explanation": "Terraform is smart: if Resource A references Resource B's ID, Terraform knows to build B first. You only use `depends_on` as a last resort to force ordering when the dependency isn't explicitly referenced in the code."
  },
  {
    "id": 16,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "count vs for_each",
    "question": "Why is `for_each` generally preferred over `count` when creating multiple similar resources (like 3 S3 buckets)?",
    "code_snippet": null,
    "options": ["`count` is deprecated", "`for_each` uses explicit keys (names), so if you remove the 2nd item from the list, it doesn't destroy and recreate the 3rd item (which `count` would do due to index shifting)", "`for_each` is faster", "`count` only supports strings"],
    "correct_answer": "`for_each` uses explicit keys, preventing index shifting issues when items are removed from the middle of a list",
    "explanation": "If `count = 3` creates buckets A, B, C. If you delete B, `count` becomes 2. Terraform sees index 2 is gone, so it destroys C and recreates it at index 1. `for_each` uses names, so deleting B only destroys B."
  },
  {
    "id": 17,
    "level": "beginner",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "terraform fmt & validate",
    "question": "What do `terraform fmt` and `terraform validate` do?",
    "code_snippet": null,
    "options": ["They deploy the code", "`fmt` automatically formats the code to a canonical style; `validate` checks the syntax and ensures the configuration is internally consistent without needing cloud credentials", "They delete the state", "They download providers"],
    "correct_answer": "`fmt` formats the code; `validate` checks syntax and internal consistency",
    "explanation": "These are essential CI/CD and pre-commit checks. `validate` catches typos and missing variables before you even run `terraform init` or talk to the cloud API."
  },
  {
    "id": 18,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "terraform destroy",
    "question": "What does `terraform destroy` do?",
    "code_snippet": null,
    "options": ["Deletes the Terraform code files", "Reads the State file and makes API calls to delete ALL real-world resources managed by that state", "Deletes the cloud provider account", "Removes the providers"],
    "correct_answer": "Reads the State file and deletes ALL real-world resources managed by that state",
    "explanation": "This is the nuclear option. It is incredibly useful for tearing down temporary testing environments, but extremely dangerous in production. It relies entirely on the State file to know what to delete."
  },
  {
    "id": 19,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Provisioners (Anti-Pattern)",
    "question": "Why are Terraform Provisioners (like `local-exec` or `remote-exec`) considered an anti-pattern?",
    "code_snippet": null,
    "options": ["They are too fast", "They introduce imperative, stateful scripts into a declarative tool, often failing silently and breaking Terraform's ability to manage the resource lifecycle reliably", "They are required for all resources", "They encrypt the state"],
    "correct_answer": "They introduce imperative scripts into a declarative tool, often failing silently and breaking lifecycle management",
    "explanation": "If a `remote-exec` script fails halfway through, Terraform doesn't know how to roll it back. Best practice is to use cloud-native tools (like AWS EC2 User Data, Cloud-Init, or Packer) to configure the instance upon boot."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've covered the core Terraform workflow, State management, and HCL syntax. What is the most critical rule of Terraform State?",
    "code_snippet": null,
    "options": ["Always store it in Git", "Never manually edit the State file; if the state drifts from reality, use `terraform import` or `terraform state` commands to fix it", "Delete it every week", "Share it via email"],
    "correct_answer": "Never manually edit the State file; use `terraform import` or state commands to fix drift",
    "explanation": "The State file is a fragile, complex JSON database. Manually editing it with a text editor will almost certainly corrupt it, causing Terraform to lose track of your infrastructure or accidentally destroy production resources."
  }
]
[
  {
    "id": 21,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Modules (Concept)",
    "question": "What is a 'Terraform Module' and why is it the fundamental building block of reusable IaC?",
    "code_snippet": null,
    "options": ["A single Terraform file", "A container for multiple resources that are used together; modules allow you to package, version, and reuse infrastructure configurations (like a standard VPC or EKS cluster) across different projects", "A cloud provider plugin", "A type of variable"],
    "correct_answer": "A container for multiple resources that are used together; modules allow you to package, version, and reuse infrastructure configurations",
    "explanation": "Every Terraform configuration is technically a module (the 'root module'). By extracting common patterns (like a 3-tier web architecture) into child modules, you create a standardized, tested library of infrastructure that your entire company can deploy with just a few lines of code."
  },
  {
    "id": 22,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "code-fill-in-blank",
    "topic": "Calling a Module",
    "question": "Fill in the blank to correctly call a local child module located in the `./modules/vpc` directory.",
    "code_snippet": "_______ \"network\" {\n  source = \"./modules/vpc\"\n  cidr_block = \"10.0.0.0/16\"\n}",
    "options": ["resource", "module", "include", "import"],
    "correct_answer": "module",
    "explanation": "The `module` block is used to instantiate a child module. The label (`\"network\"`) is the local name you give this instance, and the `source` argument tells Terraform where to find the module's code (local path, Git repo, or Terraform Registry)."
  },
  {
    "id": 23,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Workspaces",
    "question": "What is the purpose of 'Terraform Workspaces' (e.g., `terraform workspace new staging`)?",
    "code_snippet": null,
    "options": ["To switch between different cloud providers", "To maintain multiple, distinct State files for the exact same Terraform configuration, allowing you to deploy the same code to 'dev', 'staging', and 'prod' environments", "To manage Git branches", "To encrypt the state file"],
    "correct_answer": "To maintain multiple, distinct State files for the exact same Terraform configuration",
    "explanation": "Workspaces allow you to use one set of `.tf` files but deploy to different environments by simply switching the active workspace. Each workspace gets its own isolated `.tfstate` file (e.g., `env:/staging/terraform.tfstate`)."
  },
  {
    "id": 24,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Workspaces vs Directory Separation",
    "question": "Why do many enterprise teams prefer separate directories (and separate state backends) for 'prod' vs 'dev' instead of using Terraform Workspaces?",
    "code_snippet": null,
    "options": ["Workspaces are deprecated", "Separate directories provide strict isolation, prevent accidental cross-environment deployments, and allow for different IAM permissions and CI/CD pipelines per environment", "Directories are faster", "Workspaces don't support AWS"],
    "correct_answer": "Separate directories provide strict isolation, prevent accidental cross-environment deployments, and allow for different IAM permissions",
    "explanation": "Workspaces share the same backend and credentials. If a developer accidentally runs `terraform apply` while on the 'prod' workspace, they could destroy production. Separate directories with isolated state buckets and strict IAM roles are much safer for critical environments."
  },
  {
    "id": 25,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Pulumi (Code-First IaC)",
    "question": "How does Pulumi fundamentally differ from Terraform in its approach to Infrastructure as Code?",
    "code_snippet": null,
    "options": ["Pulumi only supports Azure", "Pulumi allows you to define infrastructure using general-purpose programming languages (TypeScript, Python, Go) instead of a custom DSL like HCL", "Pulumi does not use state files", "Pulumi is an imperative tool"],
    "correct_answer": "Pulumi allows you to define infrastructure using general-purpose programming languages (TypeScript, Python, Go) instead of a custom DSL like HCL",
    "explanation": "With Pulumi, you can use standard `for` loops, `if/else` logic, classes, and import existing npm/pip packages to generate infrastructure. This lowers the barrier to entry for software developers who don't want to learn a new configuration language."
  },
  {
    "id": 26,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Configuration Drift",
    "question": "What is 'Configuration Drift' in the context of IaC, and how does Terraform detect it?",
    "code_snippet": null,
    "options": ["When the code changes rapidly", "When the real-world cloud infrastructure is manually changed outside of Terraform, causing it to no longer match the State file; detected by running `terraform plan`", "When the state file is deleted", "When providers are updated"],
    "correct_answer": "When the real-world cloud infrastructure is manually changed outside of Terraform, causing it to no longer match the State file",
    "explanation": "If an admin manually adds a rule to an AWS Security Group via the console, Terraform's State file doesn't know about it. When you run `terraform plan`, Terraform queries the live AWS API, sees the mismatch, and proposes a plan to revert the manual change back to the code-defined state."
  },
  {
    "id": 27,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Resolving Drift",
    "question": "If `terraform plan` shows drift, how do you decide whether to update your code or run `terraform apply`?",
    "code_snippet": null,
    "options": ["Always run `terraform apply` to overwrite the cloud", "If the manual cloud change was intentional and correct, update your Terraform code to match it. If the change was an accident or unauthorized, run `terraform apply` to revert it", "Always update the code", "Always delete the resource"],
    "correct_answer": "If the manual cloud change was intentional, update your code. If it was an accident, run `terraform apply` to revert it",
    "explanation": "The golden rule of IaC: The code is the source of truth. If the real-world change was a necessary emergency fix, you must update the code to reflect that new reality. If it was a mistake, you enforce the code's reality onto the cloud."
  },
  {
    "id": 28,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Import",
    "question": "You have an existing S3 bucket that was created manually in the AWS Console. How do you bring it under Terraform's management without destroying and recreating it?",
    "code_snippet": null,
    "options": ["You cannot; you must delete it and recreate it", "By writing the `resource` block in your code and using the `terraform import` command (or the `import` block) to link the real-world ID to the State file", "By running `terraform apply`", "By using `terraform state rm`"],
    "correct_answer": "By writing the `resource` block in your code and using the `terraform import` command to link the real-world ID to the State file",
    "explanation": "`terraform import aws_s3_bucket.my_bucket my-existing-bucket-name` tells Terraform: 'Read the current state of this real bucket and save it into the State file.' After importing, you must write the matching `resource` block in your code so future plans don't try to modify it."
  },
  {
    "id": 29,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Cloud / Enterprise",
    "question": "What is Terraform Cloud (or Terraform Enterprise)?",
    "code_snippet": null,
    "options": ["A cloud provider like AWS", "A SaaS application that provides remote state storage, secure collaboration, VCS integration (GitHub/GitLab), policy enforcement (Sentinel), and private module registries", "A tool for writing HCL", "A monitoring dashboard"],
    "correct_answer": "A SaaS application that provides remote state storage, secure collaboration, VCS integration, and policy enforcement",
    "explanation": "Terraform Cloud is HashiCorp's managed backend. Instead of setting up your own S3 bucket and DynamoDB table for state, TFC handles it. It also provides a beautiful UI to see plan outputs, manage variables, and enforce security policies before an apply is allowed."
  },
  {
    "id": 30,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "CI/CD for IaC (Pipeline Steps)",
    "question": "What is the standard sequence of commands in a Terraform CI/CD pipeline?",
    "code_snippet": null,
    "options": ["apply -> plan -> destroy", "init -> fmt -> validate -> plan -> (manual approval) -> apply", "plan -> apply -> fmt", "validate -> destroy -> apply"],
    "correct_answer": "init -> fmt -> validate -> plan -> (manual approval) -> apply",
    "explanation": "A safe pipeline initializes the backend, checks formatting and syntax, generates a plan for peer review, waits for a human to approve the plan (especially for prod), and finally executes the apply."
  },
  {
    "id": 31,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "CI/CD for IaC (Credentials)",
    "question": "How should AWS credentials be securely provided to a GitHub Actions or GitLab CI pipeline running Terraform?",
    "code_snippet": null,
    "options": ["Hardcoded in the `.tf` files", "Stored in CI/CD Secrets and injected as environment variables, or preferably using OIDC (OpenID Connect) for temporary, passwordless federation", "Committed to a private Git repo", "Stored in the State file"],
    "correct_answer": "Stored in CI/CD Secrets and injected as environment variables, or preferably using OIDC for temporary, passwordless federation",
    "explanation": "Never hardcode credentials. Modern best practice is OIDC, where GitHub Actions authenticates directly to AWS IAM using a short-lived token, completely eliminating the need to store long-lived Access Keys in CI secrets."
  },
  {
    "id": 32,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Static Security Analysis (Checkov / tfsec)",
    "question": "What is the purpose of tools like Checkov, tfsec, or tflint in an IaC pipeline?",
    "code_snippet": null,
    "options": ["To format the code", "To scan the Terraform code (HCL) for security misconfigurations, compliance violations, and exposed secrets BEFORE the infrastructure is deployed", "To manage state files", "To test the application code"],
    "correct_answer": "To scan the Terraform code for security misconfigurations and compliance violations BEFORE deployment",
    "explanation": "These tools act as a linter for security. They can catch things like 'S3 bucket is public', 'Security Group allows 0.0.0.0/0 on port 22', or 'RDS instance is not encrypted', failing the CI pipeline before the bad infrastructure is ever created."
  },
  {
    "id": 33,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Automated Testing (Terratest)",
    "question": "What is 'Terratest' and how does it differ from static analysis tools like Checkov?",
    "code_snippet": null,
    "options": ["It is a static analysis tool", "It is a Go library used to write automated integration tests that actually deploy the infrastructure, verify it works (e.g., via HTTP requests or SSH), and then destroy it", "It is a state management tool", "It is a cloud provider"],
    "correct_answer": "It is a Go library used to write automated integration tests that actually deploy, verify, and destroy the infrastructure",
    "explanation": "While Checkov looks at the code, Terratest actually runs `terraform apply` in an isolated environment, tests the real-world output (e.g., 'Can I connect to this database?'), and runs `terraform destroy`. It proves the infrastructure actually works."
  },
  {
    "id": 34,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "State Manipulation (Moving Resources)",
    "question": "If you refactor your code and move a resource from one module to another, Terraform will try to destroy the old one and create a new one. How do you prevent this?",
    "code_snippet": null,
    "options": ["Delete the state file", "Use the `terraform state mv` command to move the resource's identity in the State file to match the new code path", "Run `terraform apply -refresh-only`", "You cannot prevent it"],
    "correct_answer": "Use the `terraform state mv` command to move the resource's identity in the State file",
    "explanation": "`terraform state mv 'module.old.aws_instance.web' 'module.new.aws_instance.web'` tells Terraform: 'This is the exact same real-world server, just referenced in a different place in the code now.' This prevents destructive downtime."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "State Manipulation (Tainting / Replacing)",
    "question": "How do you force Terraform to destroy and recreate a specific resource on the next `apply`, even if the code hasn't changed?",
    "code_snippet": null,
    "options": ["Delete the resource from the cloud console", "Use the `terraform apply -replace=\"aws_instance.web\"` flag (formerly `terraform taint`)", "Run `terraform destroy`", "Edit the state file manually"],
    "correct_answer": "Use the `terraform apply -replace=\"aws_instance.web\"` flag",
    "explanation": "If a server is corrupted or stuck in a bad state, you can 'taint' it. The `-replace` flag tells Terraform to mark that specific resource for destruction and recreation in the very next plan/apply cycle, leaving all other resources untouched."
  },
  {
    "id": 36,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Provider Versioning",
    "question": "Why is it critical to explicitly pin Provider versions in the `required_providers` block?",
    "code_snippet": null,
    "options": ["To make the code run faster", "To prevent unexpected breaking changes or deprecations from auto-upgrading to a new major version of the provider during a routine `terraform init`", "To encrypt the state", "It is required by AWS"],
    "correct_answer": "To prevent unexpected breaking changes from auto-upgrading to a new major version",
    "explanation": "If you don't pin versions, `terraform init` might download AWS Provider v5.0 when your code was written for v4.0, causing syntax errors or unexpected behavior. Pinning ensures reproducible, predictable builds."
  },
  {
    "id": 37,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Graph",
    "question": "What does the `terraform graph` command output, and what is it used for?",
    "code_snippet": null,
    "options": ["A JSON state file", "A DOT-format visual representation of the resource dependency graph, which can be rendered into an image to understand resource creation order", "A list of variables", "A security report"],
    "correct_answer": "A DOT-format visual representation of the resource dependency graph",
    "explanation": "By piping `terraform graph` into a tool like Graphviz, you can generate a visual map of your infrastructure. This is incredibly helpful for debugging complex dependency chains or understanding why Terraform is waiting on a specific resource."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Remote Backends (Types)",
    "question": "Which of the following is NOT a valid remote backend for storing Terraform state?",
    "code_snippet": null,
    "options": ["AWS S3", "HashiCorp Consul", "GitHub Repository (storing the `.tfstate` file directly in a Git commit)", "Terraform Cloud"],
    "correct_answer": "GitHub Repository (storing the `.tfstate` file directly in a Git commit)",
    "explanation": "While you store your *code* in Git, you should NEVER store the *state file* in Git. State files contain sensitive data and change constantly. Storing them in Git causes massive merge conflicts and security leaks. Use S3, GCS, AzureRM, Consul, or Terraform Cloud."
  },
  {
    "id": 39,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Refresh",
    "question": "What does `terraform refresh` (or `terraform apply -refresh-only`) do?",
    "code_snippet": null,
    "options": ["It restarts the cloud servers", "It queries the real-world cloud APIs to update the State file with the current attributes of the resources, without making any changes to the actual infrastructure", "It deletes the state file", "It formats the code"],
    "correct_answer": "It queries the real-world cloud APIs to update the State file with the current attributes",
    "explanation": "If someone manually changed a server's tags in the AWS console, `refresh` updates the State file to reflect those new tags. It brings the State file up to date with reality, but does NOT change the code or the infrastructure."
  },
  {
    "id": 40,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (IaC Maturity)",
    "question": "You've covered Modules, Pulumi, Drift, and CI/CD pipelines. What is the ultimate hallmark of a mature IaC practice?",
    "code_snippet": null,
    "options": ["Writing all infrastructure in a single massive file", "Treating infrastructure exactly like application code: enforcing peer reviews, automated testing, security scanning, and automated deployments via CI/CD, ensuring zero manual console clicks", "Using Workspaces for everything", "Disabling state locking"],
    "correct_answer": "Treating infrastructure exactly like application code: enforcing peer reviews, automated testing, security scanning, and automated deployments via CI/CD",
    "explanation": "Mature IaC means the cloud console is essentially read-only. Every change, no matter how small, goes through a Pull Request, passes automated security checks, and is deployed by a CI/CD pipeline. This guarantees auditability, security, and reproducibility."
  }
]
[
  {
    "id": 41,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "State File Bloat",
    "question": "What happens when a single Terraform State file grows to manage thousands of resources (e.g., an entire company's infrastructure in one file)?",
    "code_snippet": null,
    "options": ["Terraform automatically compresses it", "Every `terraform plan` becomes incredibly slow because it must query the live API for every single resource, and a single typo could destroy the entire company's infrastructure (massive blast radius)", "The state file automatically splits into smaller files", "Nothing, Terraform handles infinite state sizes perfectly"],
    "correct_answer": "Every `terraform plan` becomes incredibly slow because it must query the live API for every single resource, and a single typo could destroy the entire company's infrastructure",
    "explanation": "A massive state file causes severe performance degradation and creates a single point of failure. Enterprise teams solve this by splitting the state into smaller, isolated files based on components (e.g., `networking/`, `database/`, `compute/`) or environments."
  },
  {
    "id": 42,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "State Splitting & Blast Radius",
    "question": "What is the concept of 'Blast Radius' in the context of splitting Terraform State files?",
    "code_snippet": null,
    "options": ["The physical size of the server rack", "Limiting the scope of potential damage if a `terraform apply` goes wrong; smaller state files mean a bug only destroys a single component (like a dev database) rather than the entire production network", "The speed of the API calls", "The number of developers working on the repo"],
    "correct_answer": "Limiting the scope of potential damage if a `terraform apply` goes wrong; smaller state files mean a bug only destroys a single component rather than the entire network",
    "explanation": "By isolating state, you isolate risk. If the 'Database' state file has a bug, it can only affect the database. The web servers, networking, and IAM roles remain completely untouched and online."
  },
  {
    "id": 43,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terragrunt (DRY Terraform)",
    "question": "What specific problem does the wrapper tool 'Terragrunt' solve for large Terraform deployments?",
    "code_snippet": null,
    "options": ["It translates HCL to Python", "It keeps Terraform DRY by allowing you to define remote backends and common variables in a single parent file, preventing duplication across hundreds of environment directories", "It replaces the Terraform binary", "It automatically writes unit tests"],
    "correct_answer": "It keeps Terraform DRY by allowing you to define remote backends and common variables in a single parent file, preventing duplication",
    "explanation": "When you split state into 50 different directories, you end up copying and pasting the `backend "s3"` block 50 times. Terragrunt allows you to define it once in a root `terragrunt.hcl` file and inherit it everywhere."
  },
  {
    "id": 44,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "The Multi-Cloud Abstraction Trap",
    "question": "Why do most DevOps experts advise AGAINST trying to write a 'lowest-common-denominator' Terraform abstraction layer to support AWS, Azure, and GCP simultaneously?",
    "code_snippet": null,
    "options": ["Terraform doesn't support multiple providers", "Because cloud services are fundamentally different; abstracting them forces you to ignore unique, powerful features of each cloud, resulting in a fragile, unmaintainable codebase that pleases no one", "It makes the state file too small", "It is illegal"],
    "correct_answer": "Because cloud services are fundamentally different; abstracting them forces you to ignore unique features, resulting in fragile code",
    "explanation": "An AWS Lambda and an Azure Function have completely different IAM models, networking, and limits. Trying to write a generic `resource "cloud_function"` module usually results in a leaky abstraction that breaks the moment you need a cloud-specific feature."
  },
  {
    "id": 45,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Refactoring with the 'moved' Block",
    "question": "Introduced in Terraform 1.1, what does the `moved` block allow you to do directly in your code?",
    "code_snippet": null,
    "options": ["Move files between directories", "Declaratively refactor resource names or move resources between modules without needing to run manual `terraform state mv` CLI commands", "Move resources to a different cloud region", "Move state files to S3"],
    "correct_answer": "Declaratively refactor resource names or move resources between modules without needing to run manual CLI commands",
    "explanation": "Instead of running `terraform state mv` (which is imperative and easy to forget), you add a `moved { from = aws_instance.old, to = aws_instance.new }` block to your code. Terraform reads this during the plan and automatically updates the state file."
  },
  {
    "id": 46,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "code-fill-in-blank",
    "topic": "The 'moved' Block Syntax",
    "question": "Fill in the blank to correctly declare a moved block that renames a resource from `aws_s3_bucket.old` to `aws_s3_bucket.new`.",
    "code_snippet": "_______ {\n  from = aws_s3_bucket.old\n  to   = aws_s3_bucket.new\n}",
    "options": ["moved", "shift", "rename", "refactor"],
    "correct_answer": "moved",
    "explanation": "The `moved` block is a first-class citizen in HCL. It allows teams to review infrastructure refactoring in Pull Requests just like application code, ensuring the state migration is safe and auditable."
  },
  {
    "id": 47,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Handling Sensitive Data in State",
    "question": "How do you prevent Terraform from printing sensitive outputs (like database passwords) to the console during a `terraform apply`?",
    "code_snippet": null,
    "options": ["You cannot; Terraform always prints everything", "By marking the variable or output with `sensitive = true`, which tells Terraform to redact it from CLI logs and UI outputs", "By encrypting the HCL file", "By using the `--quiet` flag"],
    "correct_answer": "By marking the variable or output with `sensitive = true`",
    "explanation": "While `sensitive = true` redacts the value from the terminal and Terraform Cloud UI, remember that the value is STILL stored in plaintext in the remote State file. This is why securing the State file bucket with strict IAM and encryption at rest is mandatory."
  },
  {
    "id": 48,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "FinOps (Infracost)",
    "question": "What does a tool like 'Infracost' do in a Terraform CI/CD pipeline?",
    "code_snippet": null,
    "options": ["It formats the code", "It analyzes the `terraform plan` and posts a comment on the Pull Request showing the estimated monthly cost impact of the proposed infrastructure changes", "It automatically buys Reserved Instances", "It encrypts the state"],
    "correct_answer": "It analyzes the `terraform plan` and posts a comment on the PR showing the estimated monthly cost impact",
    "explanation": "Infracost bridges the gap between DevOps and Finance. If a developer accidentally changes an instance type from `t3.micro` to `p4d.24xlarge`, Infracost will flag the $20,000/month cost increase directly in the GitHub PR before it's merged."
  },
  {
    "id": 49,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Native Terraform Testing",
    "question": "Introduced in Terraform 1.6, what is the purpose of the native `terraform test` command and `.tftest.hcl` files?",
    "code_snippet": null,
    "options": ["To test application code", "To run automated unit and integration tests against Terraform modules, including the ability to mock cloud providers so tests run without hitting real APIs", "To format the code", "To validate the state file"],
    "correct_answer": "To run automated unit and integration tests against Terraform modules, including the ability to mock cloud providers",
    "explanation": "You can now write assertions like `assert { condition = aws_s3_bucket.test.bucket == \"my-bucket\" }`. With mock providers, you can test complex module logic, variable validations, and edge cases in milliseconds without needing AWS credentials."
  },
  {
    "id": 50,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Declarative Import Blocks",
    "question": "How does the declarative `import` block (introduced in Terraform 1.5) improve upon the legacy `terraform import` CLI command?",
    "code_snippet": null,
    "options": ["It is faster", "It allows you to define resources to be imported directly in your `.tf` code, meaning the import process is version-controlled, peer-reviewed, and executed safely via CI/CD", "It doesn't require a state file", "It automatically writes the HCL for you"],
    "correct_answer": "It allows you to define resources to be imported directly in your `.tf` code, making the process version-controlled and safe for CI/CD",
    "explanation": "The old CLI command was imperative and hard to automate. The `import { to = aws_instance.web, id = \"i-123\" }` block allows your CI/CD pipeline to seamlessly adopt existing cloud resources just by merging a Pull Request."
  },
  {
    "id": 51,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Removing Resources from State",
    "question": "If you want to stop Terraform from managing a resource (like an S3 bucket) but you DO NOT want to delete the actual bucket from AWS, what command do you use?",
    "code_snippet": null,
    "options": ["terraform destroy -target", "terraform state rm", "terraform apply -refresh-only", "terraform fmt"],
    "correct_answer": "terraform state rm",
    "explanation": "`terraform state rm aws_s3_bucket.my_bucket` removes the resource from the State file. Terraform will now completely ignore it. The actual bucket remains safely in AWS, untouched by future `terraform apply` or `destroy` commands."
  },
  {
    "id": 52,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "IaC Supply Chain Security",
    "question": "When consuming third-party Terraform modules from the public Registry, what is the most secure way to prevent supply-chain attacks (where a malicious actor updates a module with harmful code)?",
    "code_snippet": null,
    "options": ["Always use the `latest` tag", "Pin the module source to a specific Git commit SHA or a strict semantic version (e.g., `version = \"~> 2.0\"`) rather than a branch name", "Download the module to your local hard drive", "Use the `--insecure` flag"],
    "correct_answer": "Pin the module source to a specific Git commit SHA or a strict semantic version",
    "explanation": "If you point your module source to `ref=main`, a compromised upstream repository can instantly inject malicious code into your production pipeline. Pinning to a commit hash (`ref=a1b2c3d4`) guarantees immutability."
  },
  {
    "id": 53,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Least Privilege for CI/CD",
    "question": "What is a common security anti-pattern when configuring the IAM Role that your CI/CD pipeline uses to run `terraform apply`?",
    "code_snippet": null,
    "options": ["Using OIDC federation", "Granting the pipeline `AdministratorAccess` (full root access) to the AWS account", "Using short-lived credentials", "Restricting access to specific resources"],
    "correct_answer": "Granting the pipeline `AdministratorAccess` (full root access) to the AWS account",
    "explanation": "Developers often give the CI/CD role full Admin rights to avoid 'permission denied' errors during `plan`. This is catastrophic: if the CI/CD system is compromised, the attacker has full control of the entire cloud environment. Use tools like iamlive to generate the exact least-privilege policy."
  },
  {
    "id": 54,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Workspaces in CI/CD",
    "question": "When running Terraform in a CI/CD pipeline, how do you programmatically tell Terraform which Workspace (e.g., 'staging') to use without running interactive CLI prompts?",
    "code_snippet": null,
    "options": ["You cannot use workspaces in CI/CD", "By setting the `TF_WORKSPACE=staging` environment variable before running `terraform plan/apply`", "By hardcoding it in the state file", "By using the `--auto-approve` flag"],
    "correct_answer": "By setting the `TF_WORKSPACE=staging` environment variable",
    "explanation": "The `TF_WORKSPACE` environment variable overrides the default workspace. This allows a single CI/CD pipeline template to deploy to `dev`, `staging`, or `prod` simply by injecting a different environment variable based on the Git branch."
  },
  {
    "id": 55,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Handling Flaky Cloud APIs",
    "question": "Cloud provider APIs occasionally return transient errors (e.g., 'Throttling' or 'Internal Server Error'). How does modern Terraform handle this?",
    "code_snippet": null,
    "options": ["It immediately fails the entire apply", "The Provider includes built-in retry logic with exponential backoff for known transient errors, though severe bugs sometimes require the `retryable` custom logic or upgrading the provider", "It deletes the state", "It switches to a different cloud provider"],
    "correct_answer": "The Provider includes built-in retry logic with exponential backoff for known transient errors",
    "explanation": "AWS and Azure providers are written in Go and include sophisticated retry mechanisms. If an API throttles you, Terraform will wait and retry automatically, preventing false-negative failures in your CI/CD pipeline."
  },
  {
    "id": 56,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "The OpenTofu Fork",
    "question": "In late 2023, HashiCorp changed Terraform's license to BSL (Business Source License). What was the community's response, and what is OpenTofu?",
    "code_snippet": null,
    "options": ["The community abandoned IaC", "The Linux Foundation created 'OpenTofu', a fully open-source (MPL 2.0) fork of Terraform, ensuring the tool remains community-governed and free from corporate license restrictions", "HashiCorp open-sourced the core", "Terraform was shut down"],
    "correct_answer": "The Linux Foundation created 'OpenTofu', a fully open-source fork of Terraform",
    "explanation": "OpenTofu is a drop-in replacement for Terraform. It guarantees that the IaC ecosystem remains open, preventing vendor lock-in and ensuring that enterprise companies can use the tool without fearing sudden license changes."
  },
  {
    "id": 57,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Terraform Destroy -target",
    "question": "Why is using `terraform destroy -target=aws_instance.web` considered a dangerous operation that should be avoided in production?",
    "code_snippet": null,
    "options": ["It is too slow", "It destroys only the targeted resource but ignores its dependencies, potentially leaving orphaned resources (like unattached EBS volumes or dangling Security Groups) that cost money and cause state drift", "It deletes the state file", "It requires a password"],
    "correct_answer": "It destroys only the targeted resource but ignores its dependencies, potentially leaving orphaned resources",
    "explanation": "The `-target` flag is explicitly documented by HashiCorp as a 'last resort' for troubleshooting. It breaks the dependency graph. To safely remove a resource, you should remove it from the code and run a standard `terraform apply`."
  },
  {
    "id": 58,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Policy as Code (Sentinel / OPA)",
    "question": "How do tools like HashiCorp Sentinel or Open Policy Agent (OPA) integrate with Terraform?",
    "code_snippet": null,
    "options": ["They format the code", "They act as a middleware between `plan` and `apply`, evaluating the proposed infrastructure changes against custom rules (e.g., 'No S3 buckets can be public') and blocking the apply if violated", "They manage the state file", "They generate the HCL code"],
    "correct_answer": "They act as a middleware between `plan` and `apply`, evaluating the proposed changes against custom rules",
    "explanation": "This is the ultimate guardrail. Even if a developer has the IAM permissions to create a public S3 bucket, OPA will intercept the `terraform plan`, see the violation, and block the `apply` from ever executing."
  },
  {
    "id": 59,
    "level": "intermediate",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Generated Code (cdktf / Terraform CDK)",
    "question": "What is the 'CDK for Terraform' (CDKTF)?",
    "code_snippet": null,
    "options": ["A tool to deploy to Kubernetes", "A framework that allows you to define Terraform infrastructure using familiar programming languages (TypeScript, Python, Java) which then compiles down to standard HCL and State", "A monitoring tool", "A cloud provider"],
    "correct_answer": "A framework that allows you to define infrastructure using familiar languages which compiles down to standard HCL and State",
    "explanation": "CDKTF bridges the gap between Pulumi and Terraform. You get the power of TypeScript/Python loops and classes, but the underlying engine is still standard Terraform, meaning you can use all existing Terraform modules and providers."
  },
  {
    "id": 60,
    "level": "advanced",
    "module_id": "devops_mod_03_iac",
    "module_name": "Infrastructure as Code (IaC)",
    "type": "conceptual",
    "topic": "Module 3 Wrap-up (The IaC Architect's Zen)",
    "question": "You have now completed the 60-question deep dive into Infrastructure as Code. What is the ultimate hallmark of an IaC Architect?",
    "code_snippet": null,
    "options": ["Memorizing every AWS resource type", "Understanding that IaC is not just about writing code, but about establishing a single, version-controlled, peer-reviewed, and automated source of truth that eliminates human error, drift, and cloud console access entirely", "Using the largest state file possible", "Writing all code in a single file"],
    "correct_answer": "Understanding that IaC is about establishing a single, version-controlled, automated source of truth that eliminates human error and cloud console access entirely",
    "explanation": "The Zen of IaC is that the Cloud Console becomes a read-only dashboard. If it isn't in Git, it doesn't exist. By treating infrastructure with the same rigor as application code, you unlock infinite scalability, perfect disaster recovery, and absolute auditability. Congratulations on completing Module 3!"
  }
]
