[
  {
    "id": 1,
    "level": "beginner",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Containers vs Virtual Machines",
    "question": "What is the fundamental architectural difference between a Container and a Virtual Machine (VM)?",
    "code_snippet": null,
    "options": ["Containers require a dedicated hypervisor; VMs do not", "Containers share the host OS kernel and isolate only the application processes; VMs include a full guest OS and require a hypervisor, making them much heavier", "VMs start in milliseconds; Containers take minutes to boot", "Containers cannot run Linux applications"],
    "correct_answer": "Containers share the host OS kernel and isolate only the application processes; VMs include a full guest OS and require a hypervisor, making them much heavier",
    "explanation": "Because containers don't need to boot a full OS (like Windows or Ubuntu), they are megabytes in size and start in milliseconds. VMs are gigabytes in size and take minutes to boot because they virtualize the actual hardware and run a complete OS."
  },
  {
    "id": 2,
    "level": "beginner",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Docker Image vs Container",
    "question": "What is the difference between a Docker 'Image' and a Docker 'Container'?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "An Image is the immutable, read-only blueprint (template); a Container is the running, executable instance created from that image", "A Container is the template; an Image is the running app", "Images are for storage; Containers are for networking"],
    "correct_answer": "An Image is the immutable, read-only blueprint; a Container is the running, executable instance created from that image",
    "explanation": "Think of a Docker Image as a class in Object-Oriented Programming, and a Docker Container as the object (instance) created from that class. You can run 50 identical containers from a single image."
  },
  {
    "id": 3,
    "level": "beginner",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "code-fill-in-blank",
    "topic": "Dockerfile Base Image",
    "question": "Fill in the blank with the mandatory first instruction in a Dockerfile that specifies the starting operating system and environment.",
    "code_snippet": "_______ node:18-alpine\nWORKDIR /app\nCOPY . .",
    "options": ["BASE", "FROM", "START", "INIT"],
    "correct_answer": "FROM",
    "explanation": "The `FROM` instruction pulls a base image (like `node:18-alpine` or `ubuntu:22.04`) from a registry. Every Dockerfile must start with a `FROM` instruction to establish the foundation of your container."
  },
  {
    "id": 4,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Dockerfile COPY vs ADD",
    "question": "What is the primary difference between the `COPY` and `ADD` instructions in a Dockerfile?",
    "code_snippet": null,
    "options": ["They are exact aliases", "`COPY` transfers local files from the host to the image; `ADD` does the same but also supports downloading remote URLs and automatically extracting local `.tar` archives", "`ADD` is faster", "`COPY` is deprecated"],
    "correct_answer": "`COPY` transfers local files; `ADD` does the same but also supports remote URLs and automatic tar extraction",
    "explanation": "Docker best practices dictate that you should almost always use `COPY` because it is more transparent. Only use `ADD` when you specifically need its auto-extraction or URL-fetching capabilities."
  },
  {
    "id": 5,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "CMD vs ENTRYPOINT",
    "question": "How do `CMD` and `ENTRYPOINT` differ when defining the default execution command of a container?",
    "code_snippet": null,
    "options": ["They are the same", "`ENTRYPOINT` defines the main executable that always runs; `CMD` provides default arguments that can be easily overridden by the user at runtime", "`CMD` cannot be overridden", "`ENTRYPOINT` is only for shell scripts"],
    "correct_answer": "`ENTRYPOINT` defines the main executable; `CMD` provides default arguments that can be easily overridden",
    "explanation": "If `ENTRYPOINT` is `['node']` and `CMD` is `['server.js']`, running `docker run myimage` executes `node server.js`. If the user runs `docker run myimage app.js`, it overrides the CMD and executes `node app.js`. The ENTRYPOINT remains intact."
  },
  {
    "id": 6,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Multi-Stage Builds",
    "question": "What is the primary benefit of using 'Multi-Stage Builds' in a Dockerfile?",
    "code_snippet": null,
    "options": ["It allows running multiple containers at once", "It drastically reduces the final image size by separating the heavy build environment (compilers, dev dependencies) from the lightweight runtime environment", "It speeds up the network download", "It encrypts the source code"],
    "correct_answer": "It drastically reduces the final image size by separating the build environment from the runtime environment",
    "explanation": "You use a heavy image (like `node:18`) to run `npm install` and compile TypeScript in Stage 1. In Stage 2, you use a tiny image (like `node:18-alpine` or `distroless`) and ONLY copy the compiled JavaScript and `node_modules`. The final image drops from 1GB to 150MB."
  },
  {
    "id": 7,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Docker Volumes vs Bind Mounts",
    "question": "What is the difference between a Docker 'Volume' and a 'Bind Mount'?",
    "code_snippet": null,
    "options": ["Volumes are for RAM; Bind Mounts are for Disk", "Volumes are managed entirely by Docker and stored in a dedicated host directory; Bind Mounts map a specific, arbitrary path on the host filesystem directly into the container", "Bind Mounts are faster", "Volumes are deprecated"],
    "correct_answer": "Volumes are managed by Docker; Bind Mounts map a specific, arbitrary path on the host filesystem directly into the container",
    "explanation": "Use Volumes for database storage or persistent app data (Docker handles backups and portability). Use Bind Mounts for local development (e.g., mounting your local `./src` folder into the container so hot-reloading works)."
  },
  {
    "id": 8,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Docker Networking (Bridge vs Host)",
    "question": "If you run a container with the `--network host` flag, what happens to its network isolation?",
    "code_snippet": null,
    "options": ["It gets a completely isolated, private IP", "It shares the host machine's exact network namespace; the container's ports are directly bound to the host's IP, bypassing Docker's virtual bridge and port mapping", "It cannot access the internet", "It connects to the default bridge network"],
    "correct_answer": "It shares the host machine's exact network namespace, bypassing Docker's virtual bridge and port mapping",
    "explanation": "By default, Docker uses a 'bridge' network (isolated virtual network). `--network host` removes all network isolation. If your app listens on port 8080 inside the container, it is instantly accessible on the host's port 8080 without needing `-p 8080:8080`."
  },
  {
    "id": 9,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Docker Compose",
    "question": "What is the primary use case for Docker Compose?",
    "code_snippet": null,
    "options": ["Deploying to production Kubernetes clusters", "Defining and running multi-container applications locally using a single YAML file (`docker-compose.yml`)", "Building Docker images", "Monitoring container CPU usage"],
    "correct_answer": "Defining and running multi-container applications locally using a single YAML file",
    "explanation": "If your app needs a Node.js backend, a React frontend, a PostgreSQL database, and a Redis cache, Docker Compose lets you define all 4 in one file and spin them up together with a single command: `docker-compose up`."
  },
  {
    "id": 10,
    "level": "beginner",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Container Registry",
    "question": "What is a Container Registry (like Docker Hub, AWS ECR, or GitHub Container Registry)?",
    "code_snippet": null,
    "options": ["A database for storing application data", "A centralized storage and distribution system for Docker images, allowing teams to push built images and pull them to deploy", "A tool for writing Dockerfiles", "A monitoring dashboard"],
    "correct_answer": "A centralized storage and distribution system for Docker images",
    "explanation": "Just like npm is a registry for JavaScript packages, a Container Registry is where you store your compiled Docker images. Your CI/CD pipeline builds the image, pushes it to the registry, and your production servers pull it to run."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Kubernetes Control Plane",
    "question": "What is the role of the 'Control Plane' (Master Node) in a Kubernetes cluster?",
    "code_snippet": null,
    "options": ["It runs the actual application containers", "It is the 'brain' of the cluster, responsible for making global scheduling decisions, maintaining the desired state, and exposing the API (components include API Server, etcd, Scheduler, Controller Manager)", "It stores the application database", "It acts as the Load Balancer"],
    "correct_answer": "It is the 'brain' of the cluster, responsible for making global scheduling decisions and maintaining the desired state",
    "explanation": "You never run your app on the Control Plane. It manages the cluster. `etcd` holds the cluster state, the API Server is the front door for `kubectl`, the Scheduler decides which worker node gets a new Pod, and the Controller Manager ensures the actual state matches the desired state."
  },
  {
    "id": 12,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Kubernetes Worker Node",
    "question": "What are the core components running on every Kubernetes 'Worker Node'?",
    "code_snippet": null,
    "options": ["etcd and the API Server", "The Kubelet (agent that talks to the Control Plane), kube-proxy (network routing), and the Container Runtime (like containerd or Docker)", "The Load Balancer", "The CI/CD pipeline"],
    "correct_answer": "The Kubelet, kube-proxy, and the Container Runtime",
    "explanation": "Worker nodes are the 'muscle'. The Container Runtime actually pulls and runs the containers. The Kubelet listens to the Control Plane and ensures the containers on its specific node are healthy. kube-proxy handles network routing and IP translation."
  },
  {
    "id": 13,
    "level": "beginner",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "The Kubernetes Pod",
    "question": "What is a 'Pod' in Kubernetes, and why doesn't K8s just deploy Containers directly?",
    "code_snippet": null,
    "options": ["A Pod is a physical server", "A Pod is the smallest deployable unit in K8s; it wraps one or more tightly coupled containers that share the same network IP, storage volumes, and lifecycle", "A Pod is a database", "Pods are deprecated in favor of raw containers"],
    "correct_answer": "A Pod is the smallest deployable unit; it wraps one or more tightly coupled containers sharing the same network IP and storage",
    "explanation": "Sometimes you need a 'sidecar' container (like a logging agent or a service mesh proxy) to run alongside your main app container. A Pod groups them together so they share `localhost` networking and can be scheduled, scaled, and destroyed as a single unit."
  },
  {
    "id": 14,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Deployments vs ReplicaSets",
    "question": "In modern Kubernetes, why do we use a 'Deployment' resource instead of creating a 'ReplicaSet' directly?",
    "code_snippet": null,
    "options": ["ReplicaSets are deprecated", "Deployments provide a declarative, higher-level abstraction that manages ReplicaSets for you, enabling zero-downtime rolling updates, rollbacks, and version history", "Deployments are for databases; ReplicaSets are for APIs", "There is no difference"],
    "correct_answer": "Deployments provide a declarative abstraction that manages ReplicaSets, enabling zero-downtime rolling updates and rollbacks",
    "explanation": "A ReplicaSet just ensures 'X copies of this Pod are running'. A Deployment says 'I want to upgrade from v1 to v2'. The Deployment automatically creates a new ReplicaSet for v2, scales it up, scales down v1, and if it fails, rolls back to v1. Always use Deployments."
  },
  {
    "id": 15,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Kubernetes Services (ClusterIP vs NodePort vs LoadBalancer)",
    "question": "What is the difference between a `ClusterIP`, `NodePort`, and `LoadBalancer` Service in Kubernetes?",
    "code_snippet": null,
    "options": ["ClusterIP is for TCP; NodePort is for UDP", "ClusterIP exposes the service internally within the cluster; NodePort exposes it on a static port on every Node's IP; LoadBalancer provisions an external cloud Load Balancer to route traffic to the Service", "LoadBalancer is internal; ClusterIP is external", "NodePort is deprecated"],
    "correct_answer": "ClusterIP is internal; NodePort exposes it on a static port on every Node; LoadBalancer provisions an external cloud Load Balancer",
    "explanation": "ClusterIP (default) is only reachable by other Pods inside the cluster. NodePort opens a port (e.g., 30000) on every server in the cluster. LoadBalancer asks your cloud provider (AWS/GCP) to create an external IP/ALB that routes traffic into the cluster."
  },
  {
    "id": 16,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Kubernetes Namespaces",
    "question": "What is the purpose of 'Namespaces' in Kubernetes?",
    "code_snippet": null,
    "options": ["To encrypt data", "To create virtual clusters within the same physical cluster, providing scope for names, resource isolation, and access control (e.g., separating 'dev', 'staging', 'prod')", "To connect to external databases", "To manage Docker images"],
    "correct_answer": "To create virtual clusters within the same physical cluster, providing scope for names and resource isolation",
    "explanation": "Namespaces prevent naming collisions (you can have a `redis` pod in `dev` and another in `prod`). They also allow you to apply ResourceQuotas (limit CPU/RAM per namespace) and RBAC (restricting a team's access to only their namespace)."
  },
  {
    "id": 17,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "ConfigMaps vs Secrets",
    "question": "How do 'ConfigMaps' and 'Secrets' differ in Kubernetes?",
    "code_snippet": null,
    "options": ["ConfigMaps are for databases; Secrets are for APIs", "ConfigMaps store non-sensitive configuration (environment variables, config files); Secrets store sensitive data (passwords, TLS certs) and are base64 encoded (though not encrypted by default unless etcd encryption is enabled)", "Secrets are encrypted at rest by default; ConfigMaps are not", "There is no difference"],
    "correct_answer": "ConfigMaps store non-sensitive config; Secrets store sensitive data and are base64 encoded",
    "explanation": "Both are injected into Pods as environment variables or mounted files. The only difference is that Secrets are meant for sensitive data and have slightly stricter RBAC controls. Note: Base64 is encoding, NOT encryption. For true encryption, you need external tools like HashiCorp Vault or AWS Secrets Manager."
  },
  {
    "id": 18,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Liveness vs Readiness Probes",
    "question": "What is the critical difference between a 'Liveness Probe' and a 'Readiness Probe' in a Kubernetes Pod?",
    "code_snippet": null,
    "options": ["Liveness checks CPU; Readiness checks RAM", "If a Liveness Probe fails, K8s restarts the container; if a Readiness Probe fails, K8s stops sending network traffic to the Pod but does NOT restart it", "Readiness restarts the container; Liveness stops traffic", "They are the exact same thing"],
    "correct_answer": "Liveness failure restarts the container; Readiness failure stops network traffic to the Pod without restarting it",
    "explanation": "Use Liveness to fix deadlocks (e.g., the app is running but frozen; K8s kills and restarts it). Use Readiness for startup delays or temporary overload (e.g., the app is booting up or the DB is slow; K8s removes it from the Service Load Balancer until it's ready, preventing user errors)."
  },
  {
    "id": 19,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Declarative vs Imperative (kubectl apply vs create)",
    "question": "Why is `kubectl apply -f deployment.yaml` (Declarative) considered a best practice over `kubectl create` (Imperative) in production?",
    "code_snippet": null,
    "options": "`apply` is faster", "`apply` is idempotent; it compares the YAML file to the current cluster state and makes only the necessary changes to reach the desired state, making it safe to run repeatedly in CI/CD pipelines", "`create` is deprecated", "`apply` encrypts the file"],
    "correct_answer": "`apply` is idempotent; it compares the YAML to the cluster state and makes only necessary changes, making it safe for CI/CD",
    "explanation": "If you run `kubectl create` twice, it fails on the second time because the resource exists. `kubectl apply` says 'Make the cluster look like this file.' If the file hasn't changed, it does nothing. If it has changed, it updates it. This is the foundation of GitOps."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've covered Docker fundamentals and Kubernetes architecture. What is the core paradigm shift when moving from Docker Compose to Kubernetes?",
    "code_snippet": null,
    "options": ["Moving from containers to VMs", "Moving from 'imperative, local, single-node orchestration' to 'declarative, self-healing, multi-node cluster management' where you define the desired state and the system automatically handles the rest", "Moving from Linux to Windows", "Moving from YAML to JSON"],
    "correct_answer": "Moving from 'imperative, local orchestration' to 'declarative, self-healing, multi-node cluster management'",
    "explanation": "Docker Compose is great for local dev, but it doesn't handle node failures, auto-scaling, or rolling updates. Kubernetes is a self-healing system: if a server dies, K8s automatically reschedules your Pods to a healthy server without you lifting a finger."
  }
]
[
  {
    "id": 21,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Ingress vs LoadBalancer Service",
    "question": "Why is it considered a best practice to use an 'Ingress' controller instead of creating a separate 'LoadBalancer' Service for every single microservice?",
    "code_snippet": null,
    "options": ["Ingress is faster than a LoadBalancer", "An Ingress provides Layer 7 (HTTP/HTTPS) routing, SSL termination, and host/path-based rules, allowing dozens of services to share a single external Load Balancer IP", "LoadBalancer Services are deprecated", "Ingress does not support HTTPS"],
    "correct_answer": "An Ingress provides Layer 7 routing, SSL termination, and host/path-based rules, allowing dozens of services to share a single external Load Balancer IP",
    "explanation": "If you have 20 microservices and use a LoadBalancer Service for each, you pay for 20 external cloud load balancers. An Ingress sits behind ONE LoadBalancer and routes traffic based on the URL path (e.g., `/api/*` goes to the API service, `/admin/*` goes to the Admin service), saving massive amounts of money and complexity."
  },
  {
    "id": 22,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "StatefulSets vs Deployments",
    "question": "When should you use a 'StatefulSet' instead of a standard 'Deployment' in Kubernetes?",
    "code_snippet": null,
    "options": ["StatefulSets are faster to deploy", "When running stateful applications (like databases or message queues) that require stable, unique network identifiers, ordered scaling, and dedicated persistent storage per Pod", "Deployments are deprecated for databases", "StatefulSets do not support scaling"],
    "correct_answer": "When running stateful applications that require stable, unique network identifiers, ordered scaling, and dedicated persistent storage per Pod",
    "explanation": "A Deployment treats all Pods as identical and interchangeable. A StatefulSet gives each Pod a sticky identity (e.g., `postgres-0`, `postgres-1`). If `postgres-0` dies and restarts, it reattaches to the exact same persistent storage volume and keeps the same network name, which is mandatory for distributed databases."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "DaemonSets",
    "question": "What is the primary use case for a 'DaemonSet' in Kubernetes?",
    "code_snippet": null,
    "options": ["Running a central database", "Ensuring a copy of a specific Pod runs on ALL (or a specific subset of) nodes in the cluster, such as log collectors or monitoring agents", "Scaling web traffic", "Managing DNS"],
    "correct_answer": "Ensuring a copy of a specific Pod runs on ALL (or a specific subset of) nodes in the cluster",
    "explanation": "DaemonSets are perfect for node-level infrastructure tasks. If you want to collect logs from every server using Fluentd, or monitor CPU metrics using Prometheus Node Exporter, you deploy them as a DaemonSet. When you add a new node to the cluster, K8s automatically schedules the DaemonSet Pod on it."
  },
  {
    "id": 24,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Persistent Volumes (PV) vs Claims (PVC)",
    "question": "What is the relationship between a 'PersistentVolume' (PV) and a 'PersistentVolumeClaim' (PVC)?",
    "code_snippet": null,
    "options": ["They are the same thing", "A PV is the actual storage resource provisioned by the admin/cloud; a PVC is a request for storage by a user/Pod that binds to an available PV", "A PVC is the physical disk; a PV is the request", "PVCs are deprecated"],
    "correct_answer": "A PV is the actual storage resource; a PVC is a request for storage by a user/Pod that binds to an available PV",
    "explanation": "Think of the PV as the physical hard drive in the cloud (e.g., an AWS EBS volume). The PVC is the 'ticket' your application holds that says 'I need 10GB of storage.' Kubernetes matches the PVC to a compatible PV and mounts it into your Pod."
  },
  {
    "id": 25,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Resource Requests vs Limits",
    "question": "What is the critical difference between a Resource 'Request' and a Resource 'Limit' in a Kubernetes Pod spec?",
    "code_snippet": null,
    "options": ["Request is the maximum; Limit is the minimum", "Request is the guaranteed minimum resources the scheduler uses to place the Pod; Limit is the absolute maximum the container is allowed to consume", "Limits are only for CPU; Requests are only for RAM", "They are the same"],
    "correct_answer": "Request is the guaranteed minimum for scheduling; Limit is the absolute maximum the container is allowed to consume",
    "explanation": "The Scheduler looks at 'Requests' to decide which node has enough free space to run the Pod. The Kubelet looks at 'Limits' at runtime to enforce boundaries. If a Pod asks for 100m CPU (Request) but is capped at 500m CPU (Limit), it is guaranteed 100m, but can burst up to 500m if the node has spare capacity."
  },
  {
    "id": 26,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "OOMKilled (Memory Limits)",
    "question": "If a container exceeds its Memory 'Limit', what does Kubernetes do?",
    "code_snippet": null,
    "options": ["It throttles the container's CPU", "It immediately terminates the container with an 'OOMKilled' (Out Of Memory) status and restarts it according to the restart policy", "It ignores the limit", "It moves the Pod to another node"],
    "correct_answer": "It immediately terminates the container with an 'OOMKilled' status and restarts it",
    "explanation": "Unlike CPU, memory cannot be easily throttled. If a Node.js app has a memory leak and exceeds its hard Limit (e.g., 512Mi), the Linux kernel's OOM killer steps in, K8s marks the container as OOMKilled, and restarts it to protect the rest of the node."
  },
  {
    "id": 27,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "CPU Throttling",
    "question": "If a container exceeds its CPU 'Limit', what happens?",
    "code_snippet": null,
    "options": ["It is OOMKilled", "It is throttled (its CPU usage is artificially slowed down), causing latency spikes, but it is NOT killed", "It is restarted", "It is evicted from the node"],
    "correct_answer": "It is throttled (its CPU usage is artificially slowed down), causing latency spikes, but it is NOT killed",
    "explanation": "CPU is a 'compressible' resource. If your limit is 1 CPU core, and your app tries to use 2 cores, K8s just caps it at 1 core. The app doesn't crash, but it will run slower, which might cause HTTP requests to time out."
  },
  {
    "id": 28,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Horizontal Pod Autoscaler (HPA)",
    "question": "How does the Horizontal Pod Autoscaler (HPA) decide when to scale up a Deployment?",
    "code_snippet": null,
    "options": ["By checking the total CPU of the physical node", "By continuously monitoring metrics (via the Metrics Server) and scaling the replica count up or down to maintain a target utilization (e.g., 70% CPU)", "By guessing based on the time of day", "HPA requires manual intervention"],
    "correct_answer": "By continuously monitoring metrics and scaling the replica count to maintain a target utilization",
    "explanation": "You define an HPA: 'Keep CPU at 70%'. If traffic spikes and average CPU hits 85%, the HPA calculates that it needs 2 more Pods to bring the average back down to 70%, and automatically updates the Deployment's replica count."
  },
  {
    "id": 29,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Taints and Tolerations",
    "question": "What is the purpose of 'Taints' and 'Tolerations' in Kubernetes scheduling?",
    "code_snippet": null,
    "options": ["To encrypt Pods", "Taints are applied to Nodes to repel Pods; Tolerations are applied to Pods to allow them to schedule on those tainted Nodes (e.g., keeping regular apps off GPU or Master nodes)", "They are used for load balancing", "They manage DNS"],
    "correct_answer": "Taints repel Pods from Nodes; Tolerations allow Pods to schedule on those tainted Nodes",
    "explanation": "If you have specialized GPU nodes, you 'taint' them so normal web apps can't accidentally schedule there. Only Pods that have a matching GPU 'toleration' will be allowed to run on those nodes. It is also how K8s protects the Control Plane nodes."
  },
  {
    "id": 30,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Node Affinity vs Taints",
    "question": "How does 'Node Affinity' differ from 'Taints and Tolerations'?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "Node Affinity is a 'pull' mechanism (attracting Pods to specific nodes based on labels); Taints are a 'push/repel' mechanism (repelling Pods unless they have a toleration)", "Affinity is for storage; Taints are for CPU", "Taints are deprecated"],
    "correct_answer": "Node Affinity is a 'pull' mechanism; Taints are a 'push/repel' mechanism",
    "explanation": "Use Affinity when you want to say 'I specifically want to run on a node in the US-East region.' Use Taints when you want to say 'No one is allowed on this node unless they have explicit permission.'"
  },
  {
    "id": 31,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Helm (Concept)",
    "question": "What is Helm in the Kubernetes ecosystem?",
    "code_snippet": null,
    "options": ["A monitoring tool", "The package manager for Kubernetes that bundles multiple YAML manifests into a single deployable 'Chart' with templating capabilities", "A container runtime", "A CI/CD pipeline"],
    "correct_answer": "The package manager for Kubernetes that bundles YAML manifests into a 'Chart' with templating",
    "explanation": "Writing raw YAML for a production app (Deployments, Services, Ingress, ConfigMaps) is tedious and hard to reuse. Helm allows you to template these files, inject variables, and package them into a single 'Chart' that can be installed with one command: `helm install`."
  },
  {
    "id": 32,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Helm Values",
    "question": "How do you customize a Helm Chart for different environments (dev, staging, prod) without changing the base template?",
    "code_snippet": null,
    "options": ["By manually editing the YAML every time", "By providing custom `values.yaml` files or using `--set` flags to override the Chart's default variables at install time", "By using different Kubernetes clusters", "Helm does not support environments"],
    "correct_answer": "By providing custom `values.yaml` files or using `--set` flags to override the Chart's default variables",
    "explanation": "A Helm Chart has a default `values.yaml`. For production, you pass a `prod-values.yaml` file that overrides the defaults (e.g., `replicaCount: 10` instead of `3`, or `resources.limits.memory: 2Gi`). This keeps your templates clean and reusable."
  },
  {
    "id": 33,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Kustomize vs Helm",
    "question": "What is the fundamental difference between Kustomize and Helm?",
    "code_snippet": null,
    "options": ["Helm uses a templating language (Go templates); Kustomize uses directory overlays and patching without a templating language, and is built directly into `kubectl`", "Kustomize is for databases; Helm is for APIs", "Helm is deprecated", "There is no difference"],
    "correct_answer": "Helm uses Go templates; Kustomize uses directory overlays and patching without a templating language, built into `kubectl`",
    "explanation": "Helm requires you to learn its templating syntax and manage a Chart repository. Kustomize takes raw, untemplated YAML and applies 'overlays' (patches) on top of a base directory. Because Kustomize is native to `kubectl` (`kubectl apply -k`), it is favored by teams who want to avoid template complexity."
  },
  {
    "id": 34,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Service Mesh (Concept)",
    "question": "What problem does a Service Mesh (like Istio or Linkerd) solve in a Kubernetes cluster?",
    "code_snippet": null,
    "options": ["It manages database backups", "It provides uniform observability, security (mTLS), and traffic routing across all service-to-service communication without modifying application code", "It replaces the Ingress controller", "It compiles code"],
    "correct_answer": "It provides uniform observability, security (mTLS), and traffic routing across service-to-service communication",
    "explanation": "If you have 50 microservices, adding retry logic, timeouts, and encryption to every single app is a nightmare. A Service Mesh intercepts all network traffic at the infrastructure layer, giving you golden metrics, distributed tracing, and zero-trust security automatically."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Sidecar Pattern & Webhooks",
    "question": "How does a Service Mesh typically inject its proxy (e.g., Envoy) into a Pod?",
    "code_snippet": null,
    "options": ["By manually editing the Deployment YAML", "Using a Mutating Admission Webhook that automatically injects the sidecar container into Pods when they are created in a labeled namespace", "By using a DaemonSet", "By modifying the Docker image"],
    "correct_answer": "Using a Mutating Admission Webhook that automatically injects the sidecar container",
    "explanation": "When you label a namespace with `istio-injection=enabled`, the K8s API server intercepts every Pod creation request in that namespace and silently adds the Envoy sidecar container before the Pod is scheduled. The developer never sees it in their YAML."
  },
  {
    "id": 36,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Network Policies",
    "question": "By default, all Pods in a Kubernetes cluster can communicate with each other (flat network). How do you restrict this?",
    "code_snippet": null,
    "options": ["By using AWS Security Groups", "By creating 'Network Policies', which act as an internal firewall to allow/deny traffic between Pods based on labels and namespaces", "By using Ingress rules", "You cannot restrict Pod-to-Pod traffic"],
    "correct_answer": "By creating 'Network Policies', which act as an internal firewall to allow/deny traffic between Pods",
    "explanation": "If an attacker compromises your frontend Pod, they shouldn't be able to directly query your database Pod. Network Policies let you say 'Only Pods with the label `role: backend` can send traffic to the database on port 5432.'"
  },
  {
    "id": 37,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Jobs and CronJobs",
    "question": "When would you use a Kubernetes 'CronJob' instead of a 'Deployment'?",
    "code_snippet": null,
    "options": ["For hosting a long-running web server", "For running finite, scheduled tasks to completion (e.g., nightly database backups, report generation, or cleanup scripts)", "For load balancing traffic", "For storing persistent data"],
    "correct_answer": "For running finite, scheduled tasks to completion",
    "explanation": "Deployments are for long-running, infinite processes (web servers). Jobs and CronJobs are for batch processes that start, do their work, and exit with a success/fail code. K8s ensures the Job runs exactly once (or on a cron schedule) and cleans up the finished Pods."
  },
  {
    "id": 38,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Pod Disruption Budgets (PDB)",
    "question": "What is the purpose of a 'PodDisruptionBudget' (PDB)?",
    "code_snippet": null,
    "options": ["To limit CPU usage", "To ensure a minimum number or percentage of Pods remain available during voluntary disruptions (like node drains or cluster upgrades) to maintain high availability", "To encrypt Pods", "To scale Pods automatically"],
    "correct_answer": "To ensure a minimum number of Pods remain available during voluntary disruptions",
    "explanation": "If you have 5 replicas and a PDB saying 'minAvailable: 3', and an admin tries to drain a node, K8s will only allow 2 Pods to be evicted. It blocks the eviction if it would drop the available replicas below 3, preventing accidental outages during maintenance."
  },
  {
    "id": 39,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Init Containers",
    "question": "What is the execution order and purpose of 'Init Containers' in a Pod?",
    "code_snippet": null,
    "options": ["They run after the main containers", "They run sequentially BEFORE the main application containers start, used for setup tasks like waiting for a database or downloading config files", "They run in parallel with the main containers", "They are used for logging"],
    "correct_answer": "They run sequentially BEFORE the main containers start, used for setup tasks",
    "explanation": "If your Node.js app crashes when it starts because the PostgreSQL database isn't ready yet, you add an Init Container that runs a `wait-for-it.sh` script. The main app container will NOT start until the Init container exits successfully."
  },
  {
    "id": 40,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've mastered StatefulSets, Ingress, Helm, and Autoscaling. What is the core philosophy of Kubernetes resource management?",
    "code_snippet": null,
    "options": ["Give every Pod the maximum resources possible", "Define clear boundaries (Requests/Limits), automate scaling (HPA), and let the declarative engine handle the chaos of distributed infrastructure", "Manually scale Pods based on traffic", "Avoid using namespaces"],
    "correct_answer": "Define clear boundaries, automate scaling, and let the declarative engine handle the chaos",
    "explanation": "Kubernetes is a massive, self-healing engine. Your job as a DevOps engineer is not to micromanage every server, but to define the rules (Limits, PDBs, HPAs, Ingress) and let the Control Plane execute them flawlessly at scale."
  }
]
[
  {
    "id": 41,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "GitOps (Concept)",
    "question": "What is the core, foundational principle of 'GitOps'?",
    "code_snippet": null,
    "options": ["Using Git to store application source code", "Using Git as the single source of truth for the entire declarative infrastructure and application state, with automated tooling pulling changes from Git into the cluster", "Using GitHub Actions to run `kubectl apply`", "Storing Docker images in Git"],
    "correct_answer": "Using Git as the single source of truth for the entire declarative infrastructure and application state, with automated tooling pulling changes from Git into the cluster",
    "explanation": "In GitOps, humans do not run `kubectl`. Humans merge Pull Requests to the Git repository. An in-cluster agent (like ArgoCD) detects the Git change and automatically reconciles the live cluster state to match the Git state."
  },
  {
    "id": 42,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "ArgoCD vs Flux",
    "question": "How does ArgoCD (or Flux) keep the Kubernetes cluster in sync with the Git repository?",
    "code_snippet": null,
    "options": ["It pushes changes from a CI server", "It runs a continuous reconciliation loop inside the cluster, comparing the live cluster state against the Git state and applying corrections if drift is detected", "It requires a developer to manually click 'Sync'", "It uses WebSockets to stream Git commits"],
    "correct_answer": "It runs a continuous reconciliation loop inside the cluster, comparing the live cluster state against the Git state and applying corrections if drift is detected",
    "explanation": "If a rogue admin manually changes a Deployment replica count via `kubectl`, ArgoCD detects the 'drift' from the Git repository and automatically reverts the cluster back to the Git-defined state."
  },
  {
    "id": 43,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Push vs Pull CI/CD",
    "question": "Why is the 'Pull' model (GitOps) considered vastly superior and more secure than the traditional 'Push' model (where Jenkins/GitHub Actions runs `kubectl apply`) for Kubernetes deployments?",
    "code_snippet": null,
    "options": ["Pull is faster", "In the Pull model, the CI server never needs cluster credentials; the in-cluster agent pulls the manifests, drastically reducing the attack surface and preventing credential leaks in the CI pipeline", "Push is deprecated", "Pull uses less network bandwidth"],
    "correct_answer": "In the Pull model, the CI server never needs cluster credentials; the in-cluster agent pulls the manifests, drastically reducing the attack surface",
    "explanation": "If your CI server is compromised in a Push model, the attacker gets your Kubeconfig and full control of production. In a Pull model, the CI server only has access to the Git repository, and the cluster agent only has access to pull from Git."
  },
  {
    "id": 44,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "RBAC (Role vs ClusterRole)",
    "question": "What is the difference between a 'Role' and a 'ClusterRole' in Kubernetes RBAC?",
    "code_snippet": null,
    "options": ["Roles are for humans; ClusterRoles are for machines", "A Role is namespaced (applies only to resources within a specific namespace); a ClusterRole is non-namespaced (applies cluster-wide, or to cluster-scoped resources like Nodes)", "ClusterRoles are deprecated", "Roles are for reading; ClusterRoles are for writing"],
    "correct_answer": "A Role is namespaced; a ClusterRole is non-namespaced and applies cluster-wide",
    "explanation": "If you want to grant a developer access to Pods only in the `dev` namespace, you use a `Role`. If you want to grant an admin the ability to read Nodes or manage PersistentVolumes across the entire cluster, you use a `ClusterRole`."
  },
  {
    "id": 45,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "ServiceAccounts",
    "question": "What is a 'ServiceAccount' in Kubernetes?",
    "code_snippet": null,
    "options": ["A user account for developers", "An identity used by Pods and processes running inside the cluster to authenticate with the Kubernetes API or external cloud services (like AWS IAM)", "A database user", "An SSH key"],
    "correct_answer": "An identity used by Pods and processes running inside the cluster to authenticate with the Kubernetes API or external cloud services",
    "explanation": "While 'Users' are for humans (managed externally), 'ServiceAccounts' are for machines. Every Pod is automatically assigned a default ServiceAccount, which you can bind to RBAC Roles to grant the Pod specific permissions."
  },
  {
    "id": 46,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "External Secrets Operator",
    "question": "Why is checking Kubernetes 'Secrets' YAML files into Git considered a bad practice, and how does the External Secrets Operator solve this?",
    "code_snippet": null,
    "options": ["Secrets are too large for Git", "Base64 is not encryption; the Operator fetches secrets from secure vaults (AWS Secrets Manager, HashiCorp Vault) at runtime and injects them as native K8s Secrets", "Git cannot store YAML", "Secrets must be stored in ConfigMaps"],
    "correct_answer": "Base64 is not encryption; the Operator fetches secrets from secure vaults at runtime and injects them as native K8s Secrets",
    "explanation": "Instead of putting passwords in Git, you commit an `ExternalSecret` manifest that says 'Fetch the DB password from AWS Secrets Manager.' The Operator syncs it into the cluster, keeping Git clean and secrets secure."
  },
  {
    "id": 47,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Policy Engines (OPA / Kyverno)",
    "question": "What is the purpose of a policy engine like OPA Gatekeeper or Kyverno in Kubernetes?",
    "code_snippet": null,
    "options": ["To monitor CPU usage", "To enforce 'Policy as Code' by intercepting API requests (via Admission Controllers) and rejecting deployments that violate security or compliance rules", "To manage network traffic", "To scale Pods"],
    "correct_answer": "To enforce 'Policy as Code' by intercepting API requests and rejecting deployments that violate rules",
    "explanation": "You can write a Kyverno policy that says: 'Reject any Pod that runs as root, or any Deployment that doesn't have resource limits defined.' The API server blocks the `kubectl apply` before the bad resource is ever created."
  },
  {
    "id": 48,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Pod Security Standards (PSS)",
    "question": "What replaced the deprecated 'PodSecurityPolicy' (PSP) in modern Kubernetes?",
    "code_snippet": null,
    "options": ["Network Policies", "Pod Security Standards (PSS), enforced via the built-in PodSecurity Admission Controller at the namespace level", "IAM Roles", "Helm Charts"],
    "correct_answer": "Pod Security Standards (PSS), enforced via the built-in PodSecurity Admission Controller",
    "explanation": "PSS provides three profiles: Privileged, Baseline, and Restricted. You label a namespace (e.g., `pod-security.kubernetes.io/enforce: restricted`), and K8s automatically blocks any Pod in that namespace from running with dangerous privileges."
  },
  {
    "id": 49,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Troubleshooting: CrashLoopBackOff",
    "question": "If a Pod is stuck in `CrashLoopBackOff`, what does this indicate?",
    "code_snippet": null,
    "options": ["The Pod cannot be scheduled on any node", "The container is starting, but immediately crashing or exiting with a non-zero code, causing K8s to repeatedly restart it with exponential backoff", "The image is downloading slowly", "The Pod is waiting for a user to approve it"],
    "correct_answer": "The container is starting, but immediately crashing or exiting with a non-zero code, causing K8s to repeatedly restart it",
    "explanation": "Common causes: application bugs (e.g., Node.js syntax error), missing environment variables, failed Liveness Probes, or the app simply finishing its task and exiting (which K8s interprets as a crash for long-running Deployments)."
  },
  {
    "id": 50,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Troubleshooting: ImagePullBackOff",
    "question": "What causes a Pod to enter the `ImagePullBackOff` state?",
    "code_snippet": null,
    "options": ["The node is out of memory", "The Kubelet cannot pull the container image from the registry due to a typo in the tag, a missing `imagePullSecret` for private repos, or network issues", "The Pod exceeded its CPU limit", "The Ingress controller is down"],
    "correct_answer": "The Kubelet cannot pull the container image from the registry due to a typo, missing credentials, or network issues",
    "explanation": "Always check `kubectl describe pod <name>` and look at the 'Events' section. It will tell you exactly why the pull failed (e.g., 'manifest unknown' means the tag doesn't exist; 'unauthorized' means you need a Secret for the registry)."
  },
  {
    "id": 51,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Troubleshooting: Pending State",
    "question": "If a Pod is stuck in the `Pending` state, what are the most likely causes?",
    "code_snippet": null,
    "options": ["The application code has a bug", "The Scheduler cannot find a suitable Node (insufficient CPU/RAM, no matching Node Affinity, unbound PVC, or tainted nodes)", "The container is crashing", "The Service is misconfigured"],
    "correct_answer": "The Scheduler cannot find a suitable Node (insufficient resources, unbound PVC, or affinity/taint mismatches)",
    "explanation": "Pending means the Pod has been accepted by the API server, but the Scheduler is waiting for a node with enough capacity or matching labels to place it. Check `kubectl describe pod` for 'FailedScheduling' events."
  },
  {
    "id": 52,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "code-fill-in-blank",
    "topic": "Troubleshooting: CoreDNS",
    "question": "Fill in the blank with the standard command to test if internal Kubernetes DNS resolution is working from inside a debug Pod.",
    "code_snippet": "_______ kubernetes.default",
    "options": ["ping", "nslookup", "curl", "traceroute"],
    "correct_answer": "nslookup",
    "explanation": "`nslookup kubernetes.default` queries the cluster's CoreDNS service. If it returns the internal ClusterIP, DNS is healthy. If it times out, your CoreDNS Pods might be crashed, overloaded, or blocked by a Network Policy."
  },
  {
    "id": 53,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Ephemeral Containers (kubectl debug)",
    "question": "How do you debug a production Pod running a 'Distroless' or minimal image that doesn't contain a shell (`/bin/sh`) or debugging tools?",
    "code_snippet": null,
    "options": ["You cannot debug it", "By using `kubectl debug` to inject an 'Ephemeral Container' into the running Pod's namespace, sharing its process and network stack", "By restarting the Pod with a different image", "By checking the cloud provider logs"],
    "correct_answer": "By using `kubectl debug` to inject an 'Ephemeral Container' into the running Pod's namespace",
    "explanation": "Ephemeral containers allow you to temporarily inject a full Ubuntu/Busybox image into a running, read-only, or distroless Pod to inspect `/proc`, check network connections, or view memory dumps without altering the actual Deployment."
  },
  {
    "id": 54,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "CRDs and Operators",
    "question": "What is a 'Custom Resource Definition' (CRD) and a Kubernetes 'Operator'?",
    "code_snippet": null,
    "options": ["A way to write custom Docker images", "A CRD extends the K8s API with custom resource types; an Operator is a custom controller that automates the deployment and management of complex, stateful applications using those CRDs", "A tool for monitoring", "A type of Ingress rule"],
    "correct_answer": "A CRD extends the K8s API; an Operator is a custom controller that automates complex, stateful applications using those CRDs",
    "explanation": "Operators encode human operational knowledge into software. Instead of manually setting up a PostgreSQL cluster, you install the CloudNativePG Operator, create a `PostgresCluster` CRD, and the Operator automatically handles backups, failovers, and scaling."
  },
  {
    "id": 55,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Helm Hooks",
    "question": "What are 'Helm Hooks' used for during a Helm release?",
    "code_snippet": null,
    "options": ["Connecting to external databases", "Executing specific Kubernetes Jobs or Pods at specific points in the Helm lifecycle (e.g., running a DB migration Job before the main app Pods are upgraded)", "Encrypting secrets", "Scaling Pods"],
    "correct_answer": "Executing specific Jobs or Pods at specific points in the Helm lifecycle",
    "explanation": "If your new app version requires a database schema migration, you use a `pre-upgrade` Helm Hook to run a migration Job. Helm waits for the Job to succeed before proceeding to upgrade the main Deployment."
  },
  {
    "id": 56,
    "level": "intermediate",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Metrics Server vs Prometheus",
    "question": "What is the difference between the Kubernetes 'Metrics Server' and 'Prometheus'?",
    "code_snippet": null,
    "options": ["They are the same", "Metrics Server provides short-term, in-memory metrics strictly for the HPA and `kubectl top`; Prometheus is a robust, long-term time-series database for alerting, historical analysis, and dashboards", "Prometheus is for HPA; Metrics Server is for alerting", "Metrics Server is deprecated"],
    "correct_answer": "Metrics Server provides short-term metrics for HPA; Prometheus is a long-term time-series database for alerting and dashboards",
    "explanation": "You MUST install the Metrics Server if you want to use the Horizontal Pod Autoscaler. But for Grafana dashboards and PagerDuty alerting, you need Prometheus (or a managed equivalent like Datadog/CloudWatch)."
  },
  {
    "id": 57,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "VPA vs HPA",
    "question": "How does the 'Vertical Pod Autoscaler' (VPA) differ from the Horizontal Pod Autoscaler (HPA)?",
    "code_snippet": null,
    "options": ["VPA adds more Pods; HPA adds more CPU", "HPA scales the number of Pod replicas (horizontal); VPA automatically adjusts the CPU and Memory Requests/Limits of existing Pods (vertical), often requiring a restart", "VPA is for databases; HPA is for APIs", "They do the exact same thing"],
    "correct_answer": "HPA scales the number of Pod replicas; VPA automatically adjusts the CPU and Memory Requests/Limits of existing Pods",
    "explanation": "If your app is suffering from memory leaks or poor baseline sizing, HPA won't help (it just adds more broken Pods). VPA analyzes historical usage and rewrites the Pod spec to give it more RAM. Note: VPA and HPA should generally not be used on the same metric."
  },
  {
    "id": 58,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Kubernetes Upgrades (Version Skew)",
    "question": "When performing a Kubernetes cluster upgrade, what is the strict rule regarding the 'Version Skew' between the Control Plane and Worker Nodes?",
    "code_snippet": null,
    "options": ["They must be exactly the same version", "The Control Plane must be upgraded first, and Worker Nodes can be at most one minor version older than the Control Plane (e.g., Control Plane 1.28, Nodes 1.27)", "Worker nodes must be upgraded first", "Version skew doesn't matter"],
    "correct_answer": "The Control Plane must be upgraded first, and Worker Nodes can be at most one minor version older",
    "explanation": "Kubernetes guarantees compatibility between the API server and the Kubelet across a +/- 1 minor version. Always upgrade the Control Plane (API, etcd, Scheduler) first, then drain and upgrade the Worker Nodes one by one."
  },
  {
    "id": 59,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Cluster Backup (Velero)",
    "question": "Since `etcd` only holds cluster state (not application data), what tool is the industry standard for backing up K8s manifests, PVs, and entire namespaces for disaster recovery?",
    "code_snippet": null,
    "options": ["kubectl export", "Velero", "Helm", "Prometheus"],
    "correct_answer": "Velero",
    "explanation": "Velero backs up your K8s resource YAMLs and can snapshot the underlying cloud Persistent Volumes (like AWS EBS). If a cluster is completely destroyed, Velero can restore the entire application state and data to a brand new cluster."
  },
  {
    "id": 60,
    "level": "advanced",
    "module_id": "devops_mod_02_containers_k8s",
    "module_name": "Containerization & Orchestration",
    "type": "conceptual",
    "topic": "Module 2 Wrap-up (The K8s Architect's Zen)",
    "question": "You have now completed the 60-question deep dive into Containerization & Orchestration. What is the ultimate hallmark of a Kubernetes Architect?",
    "code_snippet": null,
    "options": ["Writing every deployment YAML by hand", "Understanding that Kubernetes is not just a deployment tool, but a declarative, self-healing operating system for the cloud; and knowing when to use its native primitives versus when to keep things simple", "Using Kubernetes for absolutely everything, including local development", "Disabling all security policies for speed"],
    "correct_answer": "Understanding that Kubernetes is a declarative, self-healing operating system for the cloud; and knowing when to use its native primitives versus when to keep things simple",
    "explanation": "The true master of K8s knows that while it can solve infinite scaling and complex stateful orchestration, it also introduces massive operational overhead. They use K8s where it shines (microservices, auto-scaling, GitOps) and avoid it where it's overkill. Congratulations on completing Module 2!"
  }
]
