[
  {
    "id": 1,
    "level": "beginner",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Regions vs Availability Zones",
    "question": "What is the fundamental difference between a Cloud 'Region' and an 'Availability Zone' (AZ)?",
    "code_snippet": null,
    "options": ["A Region is a single data center; an AZ is a rack of servers", "A Region is a geographic area containing multiple, isolated data centers (AZs); an AZ is one or more discrete data centers with independent power and networking", "An AZ is a geographic area; a Region is a single server", "They are the same thing"],
    "correct_answer": "A Region is a geographic area containing multiple, isolated data centers (AZs); an AZ is one or more discrete data centers with independent power and networking",
    "explanation": "Regions (e.g., us-east-1) provide geographic redundancy. Availability Zones (e.g., us-east-1a, us-east-1b) provide data center redundancy within that region. If one data center burns down, the others in the same Region survive."
  },
  {
    "id": 2,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "VPC (Virtual Private Cloud)",
    "question": "What is a VPC?",
    "code_snippet": null,
    "options": ["A virtual machine", "A logically isolated section of the Cloud where you launch your resources in a virtual network that you define, including IP ranges, subnets, and route tables", "A type of database", "A firewall rule"],
    "correct_answer": "A logically isolated section of the Cloud where you launch your resources in a virtual network that you define",
    "explanation": "Think of a VPC as your own private data center in the cloud. You control the IP address ranges (CIDR blocks), how traffic flows (Route Tables), and what is allowed in/out (Security Groups)."
  },
  {
    "id": 3,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Public vs Private Subnets",
    "question": "What determines if a Subnet is 'Public' or 'Private'?",
    "code_snippet": null,
    "options": ["The size of the IP range", "A Subnet is 'Public' if its Route Table has a route to an Internet Gateway (IGW); it is 'Private' if it does not", "Public subnets are always in Region A; Private in Region B", "Public subnets use IPv4; Private use IPv6"],
    "correct_answer": "A Subnet is 'Public' if its Route Table has a route to an Internet Gateway (IGW); it is 'Private' if it does not",
    "explanation": "A subnet is just a range of IP addresses. It becomes 'Public' only when you attach a Route Table that says 'Traffic destined for the internet goes to the Internet Gateway.' Without that route, it is isolated (Private)."
  },
  {
    "id": 4,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Internet Gateway (IGW)",
    "question": "What is the function of an Internet Gateway (IGW)?",
    "code_snippet": null,
    "options": ["It encrypts traffic", "It acts as a router that connects your VPC to the public internet, allowing resources in public subnets to send/receive traffic", "It blocks all incoming traffic", "It connects two VPCs together"],
    "correct_answer": "It acts as a router that connects your VPC to the public internet",
    "explanation": "The IGW is the 'door' to the internet. Without it, your VPC is a closed island. You attach ONE IGW to a VPC, and then your Route Tables point traffic to that door."
  },
  {
    "id": 5,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "NAT Gateway",
    "question": "Why do you need a NAT Gateway for instances in a Private Subnet?",
    "code_snippet": null,
    "options": ["To allow the internet to initiate connections to the private instances", "To allow instances in a Private Subnet to initiate outbound connections to the internet (e.g., for updates) while preventing the internet from initiating connections to them", "To encrypt the database", "To load balance traffic"],
    "correct_answer": "To allow instances in a Private Subnet to initiate outbound connections to the internet while preventing inbound connections",
    "explanation": "Private subnets have no route to the IGW. A NAT Gateway sits in a Public Subnet. Private instances send traffic to the NAT, which forwards it to the internet. The internet cannot reach back through the NAT to the private instances."
  },
  {
    "id": 6,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Security Groups vs NACLs",
    "question": "What is the key difference between a Security Group and a Network ACL (NACL)?",
    "code_snippet": null,
    "options": ["Security Groups are for databases; NACLs are for servers", "Security Groups are STATEFUL (return traffic is automatically allowed); NACLs are STATELESS (you must explicitly allow return traffic)", "NACLs are faster", "Security Groups are deprecated"],
    "correct_answer": "Security Groups are STATEFUL; NACLs are STATELESS",
    "explanation": "If you allow an inbound request on port 80 in a Security Group, the response is automatically allowed out. In a NACL, you must explicitly write a rule to allow the outbound response. Security Groups operate at the instance level; NACLs operate at the subnet level."
  },
  {
    "id": 7,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "IAM (Identity and Access Management)",
    "question": "What is the difference between an IAM 'User' and an IAM 'Role'?",
    "code_snippet": null,
    "options": ["Users are for humans; Roles are for services/applications to assume temporary credentials", "Users are for admins; Roles are for developers", "Roles are deprecated", "There is no difference"],
    "correct_answer": "Users are for humans; Roles are for services/applications to assume temporary credentials",
    "explanation": "An IAM User has long-term credentials (password/keys). An IAM Role is an identity that can be assumed by anyone (or anything, like an EC2 instance or Lambda function) to get temporary security tokens. NEVER hardcode User credentials in your app; use Roles."
  },
  {
    "id": 8,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "IAM Policies (Least Privilege)",
    "question": "What does the 'Principle of Least Privilege' mean in IAM?",
    "code_snippet": null,
    "options": ["Giving everyone admin access for speed", "Granting only the permissions necessary to perform a specific task, and nothing more", "Using only passwords, no keys", "Disabling all permissions by default"],
    "correct_answer": "Granting only the permissions necessary to perform a specific task, and nothing more",
    "explanation": "If a service only needs to read from S3, do not give it `S3FullAccess`. Give it `S3ReadOnlyAccess` restricted to a specific bucket. This minimizes the 'blast radius' if credentials are compromised."
  },
  {
    "id": 9,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Object Storage (S3)",
    "question": "What is the core characteristic of Object Storage (like AWS S3) compared to Block Storage (like a hard drive)?",
    "code_snippet": null,
    "options": ["Object storage is faster for databases", "Object storage stores data as discrete units (objects) with metadata and a unique ID in a flat structure (buckets), scalable infinitely, rather than a hierarchical file system", "Object storage is only for images", "Block storage is cheaper"],
    "correct_answer": "Object storage stores data as discrete units with metadata in a flat structure, scalable infinitely",
    "explanation": "Block storage (EBS) acts like a raw hard drive (good for OS/Databases). Object storage (S3) is a massive key-value store perfect for backups, images, and static assets. You cannot 'mount' S3 like a hard drive efficiently; you access it via API."
  },
  {
    "id": 10,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "S3 Consistency",
    "question": "What consistency model does modern S3 provide for all applications?",
    "code_snippet": null,
    "options": ["Eventual Consistency", "Strong Read/Write After Write Consistency", "No Consistency", "Daily Consistency"],
    "correct_answer": "Strong Read/Write After Write Consistency",
    "explanation": "Historically, S3 was eventually consistent. Now, it provides strong consistency. If you upload a file, the very next GET request will return that exact file, not an old version. This is critical for modern applications."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Load Balancers (Layer 4 vs 7)",
    "question": "When would you choose a Network Load Balancer (Layer 4) over an Application Load Balancer (Layer 7)?",
    "code_snippet": null,
    "options": ["When you need to route based on URL paths", "When you need extreme performance, static IP addresses, and load balancing for non-HTTP protocols (like TCP/UDP or WebSockets)", "When you need SSL termination", "When you need sticky sessions"],
    "correct_answer": "When you need extreme performance, static IP addresses, and load balancing for non-HTTP protocols",
    "explanation": "ALB (Layer 7) understands HTTP/HTTPS (routes by path/host). NLB (Layer 4) just passes TCP packets. Use NLB for high-throughput database traffic, gaming, or WebSockets where HTTP inspection is unnecessary overhead."
  },
  {
    "id": 12,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "DNS (A Record vs CNAME)",
    "question": "What is the difference between a DNS 'A Record' and a 'CNAME'?",
    "code_snippet": null,
    "options": ["A Record maps a name to an IPv4 address; CNAME maps a name to another domain name (alias)", "CNAME maps to an IP; A Record maps to a name", "A Record is for email; CNAME is for web", "There is no difference"],
    "correct_answer": "A Record maps a name to an IPv4 address; CNAME maps a name to another domain name",
    "explanation": "Use an A Record to point `example.com` to `1.2.3.4`. Use a CNAME to point `www.example.com` to `example.com` (or to a Load Balancer DNS name like `my-lb.amazonaws.com`)."
  },
  {
    "id": 13,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Route 53 (Failover Routing)",
    "question": "How does 'Failover Routing' in DNS work?",
    "code_snippet": null,
    "options": ["It routes traffic randomly", "It routes traffic to a primary resource, but if a Health Check fails, it automatically switches to a secondary (backup) resource", "It routes based on user location", "It routes based on latency"],
    "correct_answer": "It routes traffic to a primary resource, but if a Health Check fails, it switches to a secondary resource",
    "explanation": "This is the foundation of Active-Passive disaster recovery. DNS monitors the primary server. If it goes down, DNS updates the record to point to the backup region, ensuring continuity."
  },
  {
    "id": 14,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "CDN (Content Delivery Network)",
    "question": "What is the primary benefit of a CDN (like CloudFront)?",
    "code_snippet": null,
    "options": ["It encrypts the database", "It caches content at Edge Locations globally, reducing latency for users far from the origin server", "It replaces the need for a Load Balancer", "It manages DNS"],
    "correct_answer": "It caches content at Edge Locations globally, reducing latency",
    "explanation": "If your server is in Virginia, a user in Japan waits 200ms. A CDN caches your images/CSS on a server in Tokyo. The Japanese user downloads from Tokyo (5ms) instead of Virginia."
  },
  {
    "id": 15,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "CloudFront (Signed URLs)",
    "question": "How do you securely serve private video content via a CDN without making the bucket public?",
    "code_snippet": null,
    "options": ["Share the bucket password", "Use Signed URLs or Signed Cookies, which grant temporary, time-limited access to specific objects for authenticated users", "Use a stronger firewall", "You cannot serve private content via CDN"],
    "correct_answer": "Use Signed URLs or Signed Cookies",
    "explanation": "Your backend generates a URL with a cryptographic signature and an expiration time. The CDN validates the signature. If valid, it serves the file. If expired, it blocks it. This allows secure, pay-per-view content delivery."
  },
  {
    "id": 16,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "VPC Peering",
    "question": "What does VPC Peering allow you to do?",
    "code_snippet": null,
    "options": ["Connect your VPC to the internet", "Connect two VPCs together using private IP addresses, as if they were on the same network", "Connect your VPC to your on-premise data center", "Merge two VPCs into one"],
    "correct_answer": "Connect two VPCs together using private IP addresses",
    "explanation": "Peering allows resources in VPC A to talk to resources in VPC B via private IPs. It is not transitive (A peered to B, and B peered to C, does NOT mean A can talk to C)."
  },
  {
    "id": 17,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Transit Gateway",
    "question": "Why would you use a Transit Gateway instead of VPC Peering?",
    "code_snippet": null,
    "options": ["It is cheaper", "It acts as a central hub to connect thousands of VPCs and on-premise networks in a star topology, solving the complexity of managing hundreds of peering connections", "It is faster", "It provides internet access"],
    "correct_answer": "It acts as a central hub to connect thousands of VPCs, solving the complexity of managing hundreds of peering connections",
    "explanation": "If you have 50 VPCs, full-mesh peering requires 1,225 connections. Transit Gateway requires only 50 connections (one per VPC to the Gateway). It is the enterprise standard for hub-and-spoke networking."
  },
  {
    "id": 18,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Elastic IP (EIP)",
    "question": "What is an Elastic IP (EIP)?",
    "code_snippet": null,
    "options": ["A random IP address", "A static, fixed public IPv4 address that you can remap to different instances instantly, surviving a reboot", "An IP address that changes every hour", "An internal private IP"],
    "correct_answer": "A static, fixed public IPv4 address that you can remap to different instances instantly",
    "explanation": "Standard public IPs change when you stop/start an instance. An Elastic IP is yours until you release it. You use it for critical services (like a NAT Gateway or a legacy app) where the IP address must never change."
  },
  {
    "id": 19,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Direct Connect",
    "question": "What is AWS Direct Connect (or Azure ExpressRoute)?",
    "code_snippet": null,
    "options": ["A faster internet connection", "A dedicated, private physical network link from your on-premise data center directly to the Cloud provider's network, bypassing the public internet", "A type of VPN", "A database connection"],
    "correct_answer": "A dedicated, private physical network link from your on-premise data center directly to the Cloud",
    "explanation": "VPN goes over the public internet (encrypted but variable latency). Direct Connect is a literal fiber cable plugged into the Cloud. It offers consistent low latency, higher throughput, and no internet congestion."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've covered VPCs, Subnets, IAM, and DNS. What is the golden rule of Cloud Networking?",
    "code_snippet": null,
    "options": ["Put everything in one public subnet", "Never expose a database or private resource to the public internet; use Load Balancers, NAT Gateways, and strict Security Groups to control every flow of traffic", "Use the default VPC for everything", "Disable all firewalls for speed"],
    "correct_answer": "Never expose a database or private resource to the public internet; use Load Balancers, NAT Gateways, and strict Security Groups",
    "explanation": "The cloud is just someone else's computer. Your job is to build a fortress (VPC) with guarded gates (Security Groups) and controlled exits (NAT), ensuring only authorized traffic enters and leaves."
  }
]
[
  {
    "id": 21,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "VPC Endpoints",
    "question": "What is the primary purpose of a VPC Endpoint?",
    "code_snippet": null,
    "options": ["To connect your VPC to the public internet", "To allow your private resources to access AWS services (like S3 or DynamoDB) without traffic ever leaving the private AWS network", "To connect two VPCs together", "To encrypt data at rest"],
    "correct_answer": "To allow your private resources to access AWS services without traffic ever leaving the private AWS network",
    "explanation": "Without a VPC Endpoint, a private EC2 instance trying to read from S3 would have to route traffic through a NAT Gateway to the public internet, and then back to AWS. A VPC Endpoint creates a private, direct tunnel to the AWS service, saving NAT costs and improving security."
  },
  {
    "id": 22,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "AWS PrivateLink",
    "question": "How does AWS PrivateLink differ from VPC Peering?",
    "code_snippet": null,
    "options": ["PrivateLink connects VPCs using public IPs", "PrivateLink allows you to access services hosted by OTHER AWS accounts or third parties in their VPCs without exposing your traffic to the internet or requiring complex VPC peering", "PrivateLink is only for S3", "PrivateLink replaces the Internet Gateway"],
    "correct_answer": "PrivateLink allows you to access services hosted by OTHER AWS accounts or third parties in their VPCs without exposing traffic to the internet or requiring VPC peering",
    "explanation": "VPC Peering requires overlapping IP resolution and complex routing. PrivateLink uses Elastic Network Interfaces (ENIs) to expose a service as a private endpoint. It is the gold standard for securely consuming SaaS or shared microservices across organizational boundaries."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "S3 Storage Classes",
    "question": "When should you use the S3 'Infrequent Access' (IA) storage class instead of 'Standard'?",
    "code_snippet": null,
    "options": ["For data accessed multiple times per second", "For data that is accessed less frequently but requires rapid access when needed, offering lower storage costs but higher retrieval fees", "For data that can be restored within 12 hours", "For data that must be encrypted"],
    "correct_answer": "For data that is accessed less frequently but requires rapid access when needed, offering lower storage costs but higher retrieval fees",
    "explanation": "Standard S3 is expensive for storage but cheap for access. Infrequent Access (IA) reduces the storage cost by about 40%, but charges a retrieval fee. It's perfect for monthly backups or logs that you rarely read but need instantly when an incident occurs."
  },
  {
    "id": 24,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "S3 Lifecycle Policies",
    "question": "What is the purpose of an S3 Lifecycle Policy?",
    "code_snippet": null,
    "options": ["To delete the S3 bucket automatically", "To automatically transition objects between storage classes (e.g., Standard to Glacier) or expire/delete them after a certain number of days to optimize costs", "To encrypt objects", "To replicate objects to another region"],
    "correct_answer": "To automatically transition objects between storage classes or expire/delete them after a certain number of days to optimize costs",
    "explanation": "A Lifecycle Policy can move data to cheaper storage (like Glacier) after 30 days, and permanently delete it after 365 days. This automates cost optimization so you don't pay premium prices for data you no longer need."
  },
  {
    "id": 25,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "RDS Multi-AZ",
    "question": "What is the primary benefit of deploying an RDS database in a 'Multi-AZ' configuration?",
    "code_snippet": null,
    "options": ["It improves read performance by distributing queries", "It provides high availability and automatic failover by maintaining a synchronous standby replica in a different Availability Zone", "It encrypts the database", "It reduces the cost of the database"],
    "correct_answer": "It provides high availability and automatic failover by maintaining a synchronous standby replica in a different Availability Zone",
    "explanation": "In Multi-AZ, every write to the primary database is synchronously replicated to the standby. If the primary AZ loses power, RDS automatically promotes the standby to primary, usually resulting in less than 60 seconds of downtime."
  },
  {
    "id": 26,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "RDS Read Replicas",
    "question": "How do RDS 'Read Replicas' differ from 'Multi-AZ' standby instances?",
    "code_snippet": null,
    "options": ["Read Replicas are synchronous; Multi-AZ is asynchronous", "Read Replicas are asynchronous replicas used to offload read traffic and scale read-heavy workloads; Multi-AZ is synchronous and used strictly for disaster recovery", "Read Replicas are only for NoSQL", "There is no difference"],
    "correct_answer": "Read Replicas are asynchronous replicas used to offload read traffic and scale read-heavy workloads; Multi-AZ is synchronous and used strictly for disaster recovery",
    "explanation": "Read Replicas introduce slight replication lag, meaning they are NOT safe for automatic failover. However, you can point your application's heavy `SELECT` queries to the Read Replica, freeing up the primary database to handle `INSERT/UPDATE` operations."
  },
  {
    "id": 27,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "KMS vs Secrets Manager",
    "question": "What is the primary difference between AWS KMS (Key Management Service) and AWS Secrets Manager?",
    "code_snippet": null,
    "options": ["KMS stores database passwords; Secrets Manager encrypts data", "KMS manages cryptographic keys for encryption/decryption; Secrets Manager is designed specifically to store, rotate, and retrieve application secrets like database credentials and API keys", "KMS is free; Secrets Manager costs money", "KMS is for S3; Secrets Manager is for EC2"],
    "correct_answer": "KMS manages cryptographic keys for encryption/decryption; Secrets Manager is designed specifically to store, rotate, and retrieve application secrets",
    "explanation": "KMS is used to encrypt an EBS volume or an S3 object. Secrets Manager is used to store the actual username/password for your RDS database, and it can automatically rotate that password every 30 days without breaking your application."
  },
  {
    "id": 28,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "IAM Policies",
    "question": "What is the difference between an 'Identity-based' policy and a 'Resource-based' policy in IAM?",
    "code_snippet": null,
    "options": ["Identity-based is attached to a user/role; Resource-based is attached to a resource (like an S3 bucket) and specifies who can access it", "Identity-based is for AWS services; Resource-based is for humans", "Resource-based is deprecated", "They are the same thing"],
    "correct_answer": "Identity-based is attached to a user/role; Resource-based is attached to a resource and specifies who can access it",
    "explanation": "An Identity-based policy says 'User A can access Bucket X'. A Resource-based policy (attached directly to Bucket X) says 'User A can access me'. Resource-based policies are crucial for cross-account access."
  },
  {
    "id": 29,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "WAF (Web Application Firewall)",
    "question": "What is the primary function of a Web Application Firewall (WAF)?",
    "code_snippet": null,
    "options": ["To block DDoS attacks at the network layer", "To inspect HTTP/HTTPS requests and block malicious web exploits like SQL injection and Cross-Site Scripting (XSS) based on customizable rules", "To encrypt web traffic", "To load balance traffic"],
    "correct_answer": "To inspect HTTP/HTTPS requests and block malicious web exploits like SQL injection and Cross-Site Scripting (XSS) based on customizable rules",
    "explanation": "Unlike a standard firewall that blocks IP addresses, a WAF looks inside the actual HTTP payload. It can block a request if it detects a malicious SQL string in a form field, protecting your application from Layer 7 attacks."
  },
  {
    "id": 30,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "AWS Shield",
    "question": "What is the difference between AWS Shield Standard and AWS Shield Advanced?",
    "code_snippet": null,
    "options": ["Standard is for S3; Advanced is for EC2", "Standard provides automatic protection against common network and transport layer DDoS attacks for free; Advanced provides enhanced protection for application layer attacks, 24/7 DDoS response team access, and cost protection", "Advanced is deprecated", "Standard requires a monthly fee"],
    "correct_answer": "Standard provides automatic protection for free; Advanced provides enhanced protection for application layer attacks, 24/7 DDoS response team access, and cost protection",
    "explanation": "Shield Advanced is expensive, but it includes 'DDoS cost protection'—if an attack causes your Auto Scaling to spin up 500 extra servers, AWS will credit you back for the unexpected bill."
  },
  {
    "id": 31,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Security Groups (Stateful)",
    "question": "If you add an inbound rule to a Security Group allowing traffic on port 443, what happens to the outbound response traffic?",
    "code_snippet": null,
    "options": ["You must explicitly add an outbound rule for port 443", "It is automatically allowed because Security Groups are stateful", "It is blocked by default", "It requires a NACL rule"],
    "correct_answer": "It is automatically allowed because Security Groups are stateful",
    "explanation": "Stateful means the firewall remembers the connection. If you let the request in, the firewall automatically lets the matching response out, regardless of your outbound rules."
  },
  {
    "id": 32,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "NACLs (Stateless & Ephemeral Ports)",
    "question": "Why must you explicitly allow 'Ephemeral Ports' (e.g., 1024-65535) in the outbound rules of a Network ACL when a server in the subnet initiates an HTTP request to the internet?",
    "code_snippet": null,
    "options": ["Because NACLs are stateless and do not automatically allow the return traffic", "Because the internet requires it", "Because Security Groups block it", "Because the VPC router requires it"],
    "explanation": "NACLs are stateless. When your server sends a request out on port 80, the internet responds to a random high-numbered ephemeral port on your server. You MUST explicitly allow outbound traffic to those ephemeral ports in the NACL, or the response will be dropped."
  },
  {
    "id": 33,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "CloudTrail",
    "question": "What is the primary purpose of AWS CloudTrail?",
    "code_snippet": null,
    "options": ["To monitor CPU utilization", "To log and audit all API calls and management events made against your AWS account, providing a history of who did what and when", "To encrypt data in transit", "To manage DNS records"],
    "correct_answer": "To log and audit all API calls and management events made against your AWS account",
    "explanation": "If an S3 bucket is accidentally deleted, CloudTrail will show you exactly which IAM User or Role made the `DeleteBucket` API call, at what time, and from what IP address."
  },
  {
    "id": 34,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "AWS Config",
    "question": "How does AWS Config differ from CloudTrail?",
    "code_snippet": null,
    "options": ["CloudTrail logs API calls; AWS Config records the configuration state of your resources over time and evaluates them against desired compliance rules", "AWS Config is for billing; CloudTrail is for security", "AWS Config is deprecated", "They are the same thing"],
    "correct_answer": "CloudTrail logs API calls; AWS Config records the configuration state of your resources over time and evaluates them against desired compliance rules",
    "explanation": "CloudTrail tells you 'Who changed the Security Group?'. AWS Config tells you 'Is this Security Group currently compliant with our company policy that forbids port 22 to the world?' Config is essential for continuous compliance."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "GuardDuty",
    "question": "What is Amazon GuardDuty?",
    "code_snippet": null,
    "options": ["A firewall", "A continuous security monitoring service that uses machine learning to analyze VPC Flow Logs, CloudTrail, and DNS logs to detect anomalous behavior and potential threats like compromised instances or crypto-mining", "A database service", "A load balancer"],
    "correct_answer": "A continuous security monitoring service that uses machine learning to analyze VPC Flow Logs, CloudTrail, and DNS logs to detect anomalous behavior and potential threats",
    "explanation": "GuardDuty doesn't just look for known bad IPs; it looks for weird behavior. If your web server suddenly starts sending massive amounts of traffic to a known crypto-mining pool, GuardDuty will alert you."
  },
  {
    "id": 36,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "VPC Flow Logs",
    "question": "What information do VPC Flow Logs capture?",
    "code_snippet": null,
    "options": ["The exact payload of the packets", "Metadata about the IP traffic going to and from network interfaces in your VPC (source/destination IPs, ports, protocols, accept/reject status)", "The CPU usage of the instances", "The database queries"],
    "correct_answer": "Metadata about the IP traffic going to and from network interfaces in your VPC",
    "explanation": "Flow Logs do NOT capture the actual data (like passwords or emails) inside the packet. They capture the envelope: 'IP A talked to IP B on port 443, and the NACL accepted it.' This is critical for debugging network connectivity issues."
  },
  {
    "id": 37,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "CloudHSM",
    "question": "When would you choose AWS CloudHSM over AWS KMS?",
    "code_snippet": null,
    "options": ["When you need cheaper encryption", "When you require dedicated, FIPS 140-2 Level 3 validated hardware security modules where YOU control the encryption keys and the hardware is single-tenant", "When you need to encrypt S3 buckets", "When you need to manage IAM users"],
    "correct_answer": "When you require dedicated, FIPS 140-2 Level 3 validated hardware security modules where YOU control the encryption keys and the hardware is single-tenant",
    "explanation": "KMS is multi-tenant (AWS manages the hardware). CloudHSM gives you a dedicated, physical cryptographic appliance in the AWS data center. It is required for highly regulated industries (like banking or government) where AWS itself must not have access to the keys."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Amazon Macie",
    "question": "What is the primary function of Amazon Macie?",
    "code_snippet": null,
    "options": ["To encrypt databases", "To automatically discover, classify, and protect sensitive data (like PII or financial data) stored in S3 using machine learning", "To block DDoS attacks", "To manage SSL certificates"],
    "correct_answer": "To automatically discover, classify, and protect sensitive data stored in S3 using machine learning",
    "explanation": "Macie scans your S3 buckets and alerts you if it finds Credit Card numbers, Social Security Numbers, or API keys that were accidentally uploaded, helping you maintain GDPR and PCI compliance."
  },
  {
    "id": 39,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Amazon Inspector",
    "question": "What does Amazon Inspector do?",
    "code_snippet": null,
    "options": ["It load balances traffic", "It performs automated vulnerability assessments of EC2 instances and container images against common security best practices and CVEs", "It manages DNS", "It encrypts EBS volumes"],
    "correct_answer": "It performs automated vulnerability assessments of EC2 instances and container images against common security best practices and CVEs",
    "explanation": "Inspector acts like an automated penetration tester. It scans your running servers to see if you have outdated software, open ports that shouldn't be open, or known vulnerabilities (CVEs) that need patching."
  },
  {
    "id": 40,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (Defense in Depth)",
    "question": "You've covered advanced networking, storage classes, database high availability, and deep cloud security. What is the core philosophy of Cloud Security?",
    "code_snippet": null,
    "options": ["To rely solely on passwords", "To implement 'Defense in Depth'—layering multiple security controls (network isolation, encryption, identity verification, and monitoring) so that if one layer fails, others remain to protect the system", "To make all buckets public for speed", "To disable all logging to save money"],
    "correct_answer": "To implement 'Defense in Depth'—layering multiple security controls so that if one layer fails, others remain to protect the system",
    "explanation": "No single security measure is perfect. You use a VPC to isolate, Security Groups to filter, IAM to authenticate, KMS to encrypt, and GuardDuty to monitor. If an attacker bypasses the firewall, they still need the IAM role. If they get the role, the data is still encrypted. This is Defense in Depth."
  }
]
[
  {
    "id": 41,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "AWS Lambda (Concept)",
    "question": "What is the fundamental paradigm shift of AWS Lambda compared to traditional EC2 servers?",
    "code_snippet": null,
    "options": ["Lambda is a faster type of EC2 instance", "Lambda is a serverless compute service where you upload code and AWS automatically provisions, scales, and manages the underlying infrastructure; you pay only for the exact milliseconds your code executes", "Lambda is a database service", "Lambda requires you to manage the operating system"],
    "correct_answer": "Lambda is a serverless compute service where you upload code and AWS manages the infrastructure; you pay only for the exact milliseconds your code executes",
    "explanation": "With EC2, you pay for the server 24/7 even if it's idle. With Lambda, if your function runs for 200ms and then stops, you pay for exactly 200ms. Zero servers to patch, zero capacity planning, infinite auto-scaling."
  },
  {
    "id": 42,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Lambda Cold Starts",
    "question": "What is a 'Cold Start' in AWS Lambda, and why does it cause latency?",
    "code_snippet": null,
    "options": ["When the Lambda function is deleted", "When Lambda must provision a new execution environment (download code, initialize runtime, run init code) because no warm container is available to handle the request", "When the database is cold", "When the network is slow"],
    "correct_answer": "When Lambda must provision a new execution environment because no warm container is available to handle the request",
    "explanation": "The first request to a Lambda function (or a request after a period of inactivity) triggers a cold start, which can add 200ms–2s of latency. Subsequent requests hit 'warm' containers and execute instantly. Strategies like Provisioned Concurrency keep containers warm to eliminate cold starts."
  },
  {
    "id": 43,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Lambda Concurrency",
    "question": "What is the default 'Reserved Concurrency' limit for Lambda in an AWS account, and what happens when it's exceeded?",
    "code_snippet": null,
    "options": ["100 concurrent executions; requests are queued", "1,000 concurrent executions; additional invocations are throttled and receive a 429 Too Many Requests error", "Unlimited; Lambda scales infinitely", "10,000 concurrent executions; requests are dropped"],
    "correct_answer": "1,000 concurrent executions; additional invocations are throttled and receive a 429 error",
    "explanation": "AWS sets a default account-level limit of 1,000 concurrent Lambda executions to protect you from runaway costs. If a traffic spike triggers 5,000 concurrent invocations, 4,000 of them will be throttled. You can request limit increases or use Reserved Concurrency to guarantee capacity for critical functions."
  },
  {
    "id": 44,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "API Gateway (REST vs HTTP API)",
    "question": "What is the primary difference between API Gateway REST APIs and HTTP APIs?",
    "code_snippet": null,
    "options": ["REST APIs are faster", "HTTP APIs are a newer, cheaper, lower-latency option with fewer features; REST APIs offer advanced features like request validation, caching, WAF integration, and usage plans", "HTTP APIs are deprecated", "REST APIs only support GET requests"],
    "correct_answer": "HTTP APIs are a newer, cheaper, lower-latency option with fewer features; REST APIs offer advanced features like request validation, caching, WAF integration, and usage plans",
    "explanation": "If you just need a simple proxy to Lambda, use HTTP APIs (up to 71% cheaper). If you need API keys, throttling per client, request/response transformation, or WAF integration, use REST APIs."
  },
  {
    "id": 45,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "API Gateway (Stages & Canary)",
    "question": "What are 'Stages' in API Gateway, and how do 'Canary Releases' work?",
    "code_snippet": null,
    "options": ["Stages are different AWS regions", "Stages represent deployment environments (e.g., dev, staging, prod); Canary Releases allow you to route a small percentage of traffic to a new deployment while the rest goes to the stable version", "Stages are database tables", "Canary Releases are for load balancing"],
    "correct_answer": "Stages represent deployment environments; Canary Releases allow you to route a small percentage of traffic to a new deployment",
    "explanation": "You deploy your API to the `prod` stage. When you release a new version, you enable Canary and route 10% of traffic to the new version. If error rates stay low, you gradually increase to 100%. If errors spike, you instantly roll back."
  },
  {
    "id": 46,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "EventBridge (Concept)",
    "question": "What is Amazon EventBridge, and how does it enable event-driven serverless architecture?",
    "code_snippet": null,
    "options": ["A load balancer for Lambda", "A serverless event bus that ingests events from AWS services, SaaS apps, and custom applications, and routes them to targets (Lambda, SQS, Step Functions) based on rules", "A database for storing events", "A monitoring dashboard"],
    "correct_answer": "A serverless event bus that ingests events and routes them to targets based on rules",
    "explanation": "EventBridge is the nervous system of serverless. When an S3 object is uploaded, an EC2 instance changes state, or a Stripe payment succeeds, EventBridge captures the event and fans it out to any number of Lambda functions, queues, or workflows."
  },
  {
    "id": 47,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "EventBridge (Schema Registry)",
    "question": "What is the EventBridge Schema Registry?",
    "code_snippet": null,
    "options": ["A database schema", "A service that automatically discovers and stores the structure of events flowing through the event bus, allowing you to generate code bindings for type-safe event processing", "A list of IAM users", "A DNS registry"],
    "correct_answer": "A service that automatically discovers and stores the structure of events, allowing you to generate code bindings for type-safe event processing",
    "explanation": "The Schema Registry watches your event bus, learns the JSON structure of every event type, and can generate TypeScript/Python classes for those events. This gives you compile-time type safety for your event-driven architecture."
  },
  {
    "id": 48,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "SQS (Standard vs FIFO)",
    "question": "What is the key difference between an SQS Standard Queue and an SQS FIFO Queue?",
    "code_snippet": null,
    "options": ["Standard is faster; FIFO is cheaper", "Standard offers unlimited throughput with best-effort ordering and at-least-once delivery; FIFO guarantees strict first-in-first-out ordering and exactly-once processing, but with limited throughput", "FIFO is deprecated", "Standard is for emails; FIFO is for databases"],
    "correct_answer": "Standard offers unlimited throughput with best-effort ordering; FIFO guarantees strict ordering and exactly-once processing, but with limited throughput",
    "explanation": "Use Standard queues for high-throughput, order-independent tasks (like sending emails). Use FIFO queues when order matters (like processing financial transactions), but be aware that FIFO queues have a throughput limit of 3,000 messages/second (or 300 without batching)."
  },
  {
    "id": 49,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "SNS vs SQS",
    "question": "What is the fundamental difference between SNS (Simple Notification Service) and SQS (Simple Queue Service)?",
    "code_snippet": null,
    "options": ["SNS is for databases; SQS is for APIs", "SNS is a Pub/Sub 'push' service that broadcasts messages to multiple subscribers instantly; SQS is a 'pull' queue where consumers retrieve messages at their own pace", "SQS is faster than SNS", "SNS is deprecated"],
    "correct_answer": "SNS is a Pub/Sub 'push' service that broadcasts messages to multiple subscribers; SQS is a 'pull' queue where consumers retrieve messages at their own pace",
    "explanation": "SNS is like a megaphone: one message goes to Lambda, an SQS queue, an email, and an SMS simultaneously. SQS is like a mailbox: messages sit in the queue until a worker picks them up. They are often used together: SNS fans out to multiple SQS queues."
  },
  {
    "id": 50,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Step Functions",
    "question": "What problem does AWS Step Functions solve in a serverless architecture?",
    "code_snippet": null,
    "options": ["It replaces Lambda entirely", "It orchestrates complex, multi-step workflows by chaining Lambda functions together with built-in error handling, retries, parallel execution, and human approval steps", "It encrypts Lambda functions", "It caches Lambda responses"],
    "correct_answer": "It orchestrates complex, multi-step workflows by chaining Lambda functions together with built-in error handling, retries, and parallel execution",
    "explanation": "If you have a 10-step order processing workflow (validate → charge → reserve inventory → ship → email), chaining Lambdas directly creates a fragile, hard-to-debug mess. Step Functions provides a visual state machine that manages the entire flow, handles failures, and retries automatically."
  },
  {
    "id": 51,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Cloud Cost (On-Demand vs Reserved)",
    "question": "What is the trade-off between On-Demand and Reserved Instances (RIs)?",
    "code_snippet": null,
    "options": ["Reserved Instances are more expensive but more flexible", "On-Demand offers maximum flexibility at the highest price; Reserved Instances offer up to 72% discount in exchange for a 1-3 year commitment", "On-Demand is for databases; Reserved is for compute", "There is no price difference"],
    "correct_answer": "On-Demand offers maximum flexibility at the highest price; Reserved Instances offer up to 72% discount in exchange for a 1-3 year commitment",
    "explanation": "If you know you will run a database server 24/7 for the next 2 years, a Reserved Instance saves you massive money. If you're experimenting or have unpredictable traffic, On-Demand lets you start/stop without commitment."
  },
  {
    "id": 52,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Compute Savings Plans",
    "question": "How do Compute Savings Plans differ from Reserved Instances?",
    "code_snippet": null,
    "options": ["Savings Plans are more expensive", "Savings Plans offer similar discounts to RIs but with much greater flexibility—you commit to a dollar amount per hour rather than a specific instance type, and the discount applies across EC2, Lambda, and Fargate", "Savings Plans only work for S3", "Savings Plans are deprecated"],
    "correct_answer": "Savings Plans offer similar discounts but with greater flexibility—you commit to a dollar amount per hour across EC2, Lambda, and Fargate",
    "explanation": "With an RI, you are locked into a specific instance family (e.g., m5.large). With a Compute Savings Plan, you commit to spending $10/hour, and the discount applies whether you use m5.large, c6g.xlarge, Lambda, or Fargate. It is the modern replacement for RIs."
  },
  {
    "id": 53,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Spot Instances",
    "question": "What are Spot Instances, and when should you use them?",
    "code_snippet": null,
    "options": ["Instances with the highest performance", "Instances that use spare AWS capacity at up to 90% discount, but can be interrupted with a 2-minute warning; ideal for fault-tolerant, stateless workloads like batch processing or CI/CD", "Instances that are always available", "Instances for databases"],
    "correct_answer": "Instances that use spare AWS capacity at up to 90% discount, but can be interrupted with a 2-minute warning; ideal for fault-tolerant, stateless workloads",
    "explanation": "Spot Instances are AWS's way of selling unused capacity cheaply. The catch: AWS can reclaim them at any time with a 2-minute notice. Never use Spot for databases or stateful services. Use them for batch jobs, data processing, and CI/CD runners where interruptions are tolerable."
  },
  {
    "id": 54,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Right-Sizing",
    "question": "What is 'Right-Sizing' in cloud cost optimization?",
    "code_snippet": null,
    "options": ["Using the largest instance available", "Analyzing actual resource utilization (CPU, RAM, I/O) and downsizing over-provisioned instances to the smallest size that meets performance requirements", "Migrating to a different cloud provider", "Deleting all unused resources"],
    "correct_answer": "Analyzing actual resource utilization and downsizing over-provisioned instances to the smallest size that meets performance requirements",
    "explanation": "Most developers over-provision out of fear. If your `r5.4xlarge` instance is using only 10% CPU and 15% RAM, you are wasting thousands of dollars per month. Right-sizing tools (like AWS Compute Optimizer) analyze your usage and recommend the correct, cheaper instance type."
  },
  {
    "id": 55,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Auto Scaling Strategies",
    "question": "What is the difference between 'Reactive' and 'Predictive' Auto Scaling?",
    "code_snippet": null,
    "options": ["Reactive is faster", "Reactive scales based on real-time metrics (CPU > 70%); Predictive uses machine learning to analyze historical traffic patterns and scales up BEFORE the anticipated traffic spike arrives", "Predictive is deprecated", "Reactive is for databases; Predictive is for APIs"],
    "correct_answer": "Reactive scales based on real-time metrics; Predictive uses ML to scale up BEFORE the anticipated traffic spike arrives",
    "explanation": "Reactive scaling means your users experience slow performance for the 5 minutes it takes to spin up new servers. Predictive scaling (available in AWS Auto Scaling) learns that traffic spikes every Monday at 9 AM and pre-provisions capacity at 8:45 AM."
  },
  {
    "id": 56,
    "level": "intermediate",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "AWS Budgets & Cost Anomaly Detection",
    "question": "How do AWS Budgets and Cost Anomaly Detection help prevent billing surprises?",
    "code_snippet": null,
    "options": ["They automatically shut down expensive resources", "Budgets send alerts when spending exceeds a threshold; Cost Anomaly Detection uses ML to identify unusual spending spikes (like a misconfigured Lambda loop) and alert you before the bill explodes", "They reduce the bill automatically", "They encrypt the billing data"],
    "correct_answer": "Budgets send alerts when spending exceeds a threshold; Cost Anomaly Detection uses ML to identify unusual spending spikes and alert you",
    "explanation": "A single misconfigured Lambda function running in an infinite loop can generate a $50,000 bill overnight. Cost Anomaly Detection catches the spike within hours and alerts you, allowing you to kill the function before the damage is catastrophic."
  },
  {
    "id": 57,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Well-Architected Framework",
    "question": "What are the six pillars of the AWS Well-Architected Framework?",
    "code_snippet": null,
    "options": ["Speed, Cost, Security, Reliability, Performance, Usability", "Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, and Sustainability", "Compute, Storage, Network, Database, Security, Analytics", "Frontend, Backend, Database, Cache, Queue, CDN"],
    "correct_answer": "Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, and Sustainability",
    "explanation": "The Well-Architected Framework is AWS's blueprint for building production-grade systems. Every architectural decision should be evaluated against these six pillars. For example, a design that is highly performant but costs $1M/month fails the Cost Optimization pillar."
  },
  {
    "id": 58,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Shared Responsibility Model",
    "question": "In the AWS Shared Responsibility Model, what is AWS responsible for vs. what is the customer responsible for?",
    "code_snippet": null,
    "options": ["AWS is responsible for everything", "AWS is responsible for the 'Security OF the Cloud' (hardware, data centers, hypervisor); the customer is responsible for 'Security IN the Cloud' (data encryption, IAM, OS patching, firewall rules)", "The customer is responsible for the hardware", "AWS is responsible for application code"],
    "correct_answer": "AWS is responsible for 'Security OF the Cloud'; the customer is responsible for 'Security IN the Cloud'",
    "explanation": "AWS guarantees the physical data center won't be breached and the hypervisor is patched. But if you leave your S3 bucket public or use a weak database password, that is YOUR responsibility. The cloud provider secures the infrastructure; you secure your data and applications."
  },
  {
    "id": 59,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Multi-Cloud Strategy",
    "question": "What are the primary trade-offs of a Multi-Cloud strategy (using AWS + GCP + Azure simultaneously)?",
    "code_snippet": null,
    "options": ["Multi-cloud is always cheaper", "Multi-cloud provides vendor lock-in avoidance and best-of-breed services, but dramatically increases operational complexity, requires cross-cloud networking, and multiplies the learning curve for the engineering team", "Multi-cloud eliminates all downtime", "Multi-cloud is only for startups"],
    "correct_answer": "Multi-cloud provides vendor lock-in avoidance and best-of-breed services, but dramatically increases operational complexity and multiplies the learning curve",
    "explanation": "While multi-cloud sounds ideal in theory, in practice it means your team must master three different IAM systems, three different networking models, and three different deployment pipelines. Most companies are better off going deep on one cloud and using abstraction layers (like Terraform) for portability."
  },
  {
    "id": 60,
    "level": "advanced",
    "module_id": "devops_mod_01_cloud_foundations",
    "module_name": "Cloud Foundations & Networking",
    "type": "conceptual",
    "topic": "Module 1 Wrap-up (The Cloud Architect's Zen)",
    "question": "You have now completed the 60-question deep dive into Cloud Foundations. What is the ultimate hallmark of a Cloud Architect?",
    "code_snippet": null,
    "options": ["Memorizing every AWS service", "Understanding that the cloud is not just 'someone else's computer'—it is a programmable, elastic, global infrastructure that must be architected with intention, secured with paranoia, optimized with data, and governed with discipline", "Using only serverless for everything", "Avoiding the cloud entirely"],
    "correct_answer": "Understanding that the cloud is a programmable, elastic, global infrastructure that must be architected with intention, secured with paranoia, optimized with data, and governed with discipline",
    "explanation": "The cloud gives you infinite power, but infinite power without discipline leads to infinite bills and infinite security breaches. A true Cloud Architect designs systems that are secure by default, cost-optimized by design, and resilient by architecture. Congratulations on completing Module 1!"
  }
]
