[
  {
    "id": 531,
    "level": "beginner",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Why Test TypeScript?",
    "question": "If TypeScript already catches type errors at compile-time, why is runtime testing still absolutely essential?",
    "code_snippet": null,
    "options": ["It isn't; TypeScript replaces all testing", "TypeScript catches structural/type errors, but NOT logical errors, incorrect algorithms, broken integrations, or unexpected runtime data shapes from external APIs", "Testing is only for JavaScript projects", "TypeScript tests are slower than JavaScript tests"],
    "correct_answer": "TypeScript catches structural/type errors, but NOT logical errors, incorrect algorithms, broken integrations, or unexpected runtime data shapes from external APIs",
    "explanation": "TypeScript guarantees your data has the right shape. It does NOT guarantee your business logic is correct. A function can be perfectly typed and still return the wrong calculation, hit the wrong API endpoint, or fail on edge-case inputs."
  },
  {
    "id": 532,
    "level": "beginner",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Vitest vs Jest",
    "question": "What is the primary advantage of Vitest over Jest for modern TypeScript projects?",
    "code_snippet": null,
    "options": ["Vitest supports more assertion methods", "Vitest is built on Vite, providing native ESM support, significantly faster execution via esbuild, and seamless TypeScript handling without additional configuration", "Vitest can test CSS", "Vitest replaces TypeScript"],
    "correct_answer": "Vitest is built on Vite, providing native ESM support, significantly faster execution via esbuild, and seamless TypeScript handling without additional configuration",
    "explanation": "Jest requires `ts-jest` or `babel-jest` to handle TypeScript, adding configuration overhead. Vitest understands `.ts` files natively out of the box, supports ESM imports, and runs tests 2-5x faster due to Vite's on-demand compilation."
  },
  {
    "id": 533,
    "level": "beginner",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Basic Unit Test (Vitest)",
    "question": "Fill in the blank to correctly write a basic unit test in Vitest that asserts a function returns the expected value.",
    "code_snippet": "import { describe, it, _______ } from 'vitest';\nimport { add } from './math';\n\ndescribe('add', () => {\n  it('should add two numbers', () => {\n    expect(add(2, 3)).toBe(5);\n  });\n});",
    "options": ["assert", "expect", "test", "check"],
    "correct_answer": "expect",
    "explanation": "The `expect` function is the core assertion API. It wraps a value and provides chainable matchers like `.toBe()`, `.toEqual()`, `.toThrow()`, and `.toContain()` to verify behavior."
  },
  {
    "id": 534,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "toBe vs toEqual",
    "question": "What is the critical difference between `.toBe()` and `.toEqual()` in Vitest/Jest?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`.toBe()` uses strict reference equality (`===`); `.toEqual()` performs a deep structural comparison of objects/arrays", "`.toEqual()` is for strings, `.toBe()` is for numbers", "`.toBe()` is deprecated"],
    "correct_answer": "`.toBe()` uses strict reference equality (`===`); `.toEqual()` performs a deep structural comparison of objects/arrays",
    "explanation": "`expect({ a: 1 }).toBe({ a: 1 })` FAILS because they are different object references. `expect({ a: 1 }).toEqual({ a: 1 })` PASSES because the structures are identical. Always use `.toEqual()` for objects and arrays."
  },
  {
    "id": 535,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Testing Async Code",
    "question": "Fill in the blank to correctly test an async function that returns a Promise.",
    "code_snippet": "it('should fetch user', _______ () => {\n  const user = await fetchUser(1);\n  expect(user.name).toBe('Alice');\n});",
    "options": ["function", "async", "promise", "deferred"],
    "correct_answer": "async",
    "explanation": "By marking the test callback as `async`, you can use `await` inside it. Vitest/Jest will automatically wait for the Promise to resolve before evaluating the assertions."
  },
  {
    "id": 536,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Mocking (Concept)",
    "question": "What is 'Mocking' in the context of unit testing?",
    "code_snippet": null,
    "options": ["Making fun of bad code", "Replacing a real dependency (like a database call or API request) with a fake, controllable implementation to isolate the unit under test", "Running tests in production", "Deleting test files"],
    "correct_answer": "Replacing a real dependency (like a database call or API request) with a fake, controllable implementation to isolate the unit under test",
    "explanation": "Unit tests should be fast, deterministic, and isolated. By mocking external dependencies, you ensure the test only verifies YOUR logic, not the behavior of a third-party API or database."
  },
  {
    "id": 537,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Mocking Functions (vi.fn)",
    "question": "Fill in the blank to create a mock function in Vitest that you can pass as a callback and later assert was called.",
    "code_snippet": "const mockCallback = _______();\nmyFunction(mockCallback);\nexpect(mockCallback).toHaveBeenCalledOnce();",
    "options": ["jest.fn()", "vi.fn()", "mock()", "spy()"],
    "correct_answer": "vi.fn()",
    "explanation": "`vi.fn()` creates a 'spy' function that records every call, its arguments, and its return value. You can then assert it was called the correct number of times with the correct arguments."
  },
  {
    "id": 538,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Mocking Modules (vi.mock)",
    "question": "How do you mock an entire external module (like `axios` or a database client) in Vitest?",
    "code_snippet": null,
    "options": ["By deleting the module from node_modules", "By calling `vi.mock('module-name', () => ({ ... }))` at the top of the test file", "By using `import * as mock from 'module'`", "By setting an environment variable"],
    "correct_answer": "By calling `vi.mock('module-name', () => ({ ... }))` at the top of the test file",
    "explanation": "`vi.mock` is hoisted to the top of the file by Vitest's transformer, ensuring the mock is in place before any imports execute. You provide a factory function that returns the fake module implementation."
  },
  {
    "id": 539,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "TypeScript Testing (Type-Level Tests)",
    "question": "How can you write tests that verify TypeScript TYPES (not runtime values) are correct?",
    "code_snippet": null,
    "options": ["You cannot test types", "By using `expectTypeOf<T>().toEqualTypeOf<U>()` from Vitest, or `// @ts-expect-error` comments to assert that invalid assignments produce compile errors", "By using `typeof` at runtime", "By using `instanceof`"],
    "correct_answer": "By using `expectTypeOf<T>().toEqualTypeOf<U>()` from Vitest, or `// @ts-expect-error` comments to assert that invalid assignments produce compile errors",
    "explanation": "Vitest provides `expectTypeOf` for compile-time type assertions. Alternatively, `// @ts-expect-error` on the next line will FAIL the test if the next line does NOT produce a type error, ensuring your types reject invalid inputs."
  },
  {
    "id": 540,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Testing Library Philosophy",
    "question": "What is the core testing philosophy of React Testing Library (RTL)?",
    "code_snippet": null,
    "options": ["Test implementation details (state, lifecycle methods)", "Test behavior from the user's perspective: query by accessible roles, labels, and text, ignoring internal component structure", "Test CSS styles", "Test database queries"],
    "correct_answer": "Test behavior from the user's perspective: query by accessible roles, labels, and text, ignoring internal component structure",
    "explanation": "RTL forces you to interact with your components the way a real user (or screen reader) would. This makes tests resilient to internal refactoring—if you change a `div` to a `section`, your tests still pass as long as the user experience is unchanged."
  },
  {
    "id": 541,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Testing Library (Rendering)",
    "question": "Fill in the blank to correctly render a React component in a Vitest + RTL test.",
    "code_snippet": "import { _______ } from '@testing-library/react';\n\nit('renders the title', () => {\n  const { getByText } = render(<MyComponent title='Hello' />);\n  expect(getByText('Hello')).toBeInTheDocument();\n});",
    "options": ["mount", "render", "create", "shallow"],
    "correct_answer": "render",
    "explanation": "The `render` function mounts the component into a virtual DOM (via `jsdom` or `happy-dom`) and returns query utilities (`getByText`, `getByRole`, etc.) for interacting with the rendered output."
  },
  {
    "id": 542,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Testing Library (Queries Priority)",
    "question": "What is the recommended priority order for querying elements in React Testing Library?",
    "code_snippet": null,
    "options": ["getByTestId > getByText > getByRole", "getByRole > getByLabelText > getByText > getByTestId", "getByText > getByRole > getByTestId", "getByTestId > getByRole > getByText"],
    "correct_answer": "getByRole > getByLabelText > getByText > getByTestId",
    "explanation": "This priority mirrors how assistive technologies (screen readers) find elements. `getByRole` is the most accessible query. `getByTestId` is the last resort, used only when no semantic query is possible."
  },
  {
    "id": 543,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Test Structure (AAA Pattern)",
    "question": "What is the 'AAA' pattern for structuring unit tests?",
    "code_snippet": null,
    "options": ["Always Assert Again", "Arrange (set up data), Act (call the function), Assert (verify the result)", "Async Await Assert", "Assign Add Assert"],
    "correct_answer": "Arrange (set up data), Act (call the function), Assert (verify the result)",
    "explanation": "The AAA pattern creates a clear, readable test structure. 'Arrange' sets up inputs and mocks. 'Act' calls the unit under test. 'Assert' verifies the output. Each test should have exactly ONE 'Act'."
  },
  {
    "id": 544,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Test Isolation",
    "question": "Why must each test be completely independent and not rely on the state left by a previous test?",
    "code_snippet": null,
    "options": ["Because Vitest runs tests alphabetically", "Because tests can run in any order (or in parallel), and shared mutable state creates flaky, non-deterministic tests that pass locally but fail in CI", "Because TypeScript requires it", "Because it makes the tests run slower"],
    "correct_answer": "Because tests can run in any order (or in parallel), and shared mutable state creates flaky, non-deterministic tests that pass locally but fail in CI",
    "explanation": "Flaky tests destroy team confidence. By using `beforeEach` to reset state and avoiding shared variables, you ensure every test is a self-contained, reproducible verification of a single behavior."
  },
  {
    "id": 545,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Setup and Teardown",
    "question": "Fill in the blank to run a setup function before EVERY test in a `describe` block.",
    "code_snippet": "describe('UserService', () => {\n  _______(() => {\n    // Reset database, clear mocks, etc.\n  });\n\n  it('should create a user', () => { ... });\n});",
    "options": ["beforeAll", "beforeEach", "setup", "init"],
    "correct_answer": "beforeEach",
    "explanation": "`beforeEach` runs before every single `it` block, ensuring a clean slate. `beforeAll` runs only once before the entire `describe` block. Use `beforeEach` for state reset, `beforeAll` for expensive one-time setup."
  },
  {
    "id": 546,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Mocking Timers",
    "question": "How do you test code that uses `setTimeout` or `setInterval` without actually waiting for the real time to pass?",
    "code_snippet": null,
    "options": ["By using `await sleep(5000)`", "By using `vi.useFakeTimers()` to control time manually, then advancing it with `vi.advanceTimersByTime(ms)`", "By removing the timeout from the code", "By using `process.nextTick`"],
    "correct_answer": "By using `vi.useFakeTimers()` to control time manually, then advancing it with `vi.advanceTimersByTime(ms)`",
    "explanation": "Fake timers replace the global `setTimeout`/`setInterval` with controllable mocks. You can instantly advance time by any amount, making tests that would normally take 5 seconds complete in 5 milliseconds."
  },
  {
    "id": 547,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Coverage (Concept)",
    "question": "What does 'Code Coverage' measure in a test suite?",
    "code_snippet": null,
    "options": ["The number of test files", "The percentage of source code lines, branches, functions, and statements that are executed during the test run", "The speed of the tests", "The number of assertions"],
    "correct_answer": "The percentage of source code lines, branches, functions, and statements that are executed during the test run",
    "explanation": "Coverage tells you what percentage of your code is actually being tested. 100% coverage doesn't mean 100% correctness, but low coverage (e.g., 20%) guarantees you have massive untested blind spots."
  },
  {
    "id": 548,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Vitest Configuration",
    "question": "Where do you configure Vitest settings (like test environment, coverage thresholds, and file patterns)?",
    "code_snippet": null,
    "options": ["In `package.json` only", "In `vitest.config.ts` (or inside the `test` property of `vite.config.ts`)", "In `tsconfig.json`", "In `.env`"],
    "correct_answer": "In `vitest.config.ts` (or inside the `test` property of `vite.config.ts`)",
    "explanation": "Vitest reads its configuration from a dedicated config file. Here you set the test environment (`jsdom` for React, `node` for backend), coverage thresholds, include/exclude patterns, and setup files."
  },
  {
    "id": 549,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Test Environment (jsdom vs node)",
    "question": "When should you use the `jsdom` test environment vs the `node` test environment in Vitest?",
    "code_snippet": null,
    "options": ["Always use `jsdom`", "Use `jsdom` (or `happy-dom`) when testing code that interacts with the DOM (React components, browser APIs); use `node` for pure logic, backend code, and CLI tools", "Always use `node`", "Use `jsdom` for backend, `node` for frontend"],
    "correct_answer": "Use `jsdom` (or `happy-dom`) when testing code that interacts with the DOM (React components, browser APIs); use `node` for pure logic, backend code, and CLI tools",
    "explanation": "`jsdom` simulates a browser environment (providing `window`, `document`, etc.) but is slower. `node` is faster and more appropriate for server-side code that never touches the DOM."
  },
  {
    "id": 550,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "What is the ultimate goal of a well-written TypeScript test suite?",
    "code_snippet": null,
    "options": ["To achieve 100% code coverage at all costs", "To provide a safety net that allows developers to refactor, add features, and fix bugs with absolute confidence that existing behavior is preserved", "To replace TypeScript's type checker", "To slow down the development process"],
    "correct_answer": "To provide a safety net that allows developers to refactor, add features, and fix bugs with absolute confidence that existing behavior is preserved",
    "explanation": "Tests are not a chore; they are documentation and insurance. A comprehensive test suite transforms refactoring from a terrifying gamble into a confident, mechanical process, enabling teams to ship fearlessly."
  }
]
[
  {
    "id": 551,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "E2E Testing (Concept)",
    "question": "How does End-to-End (E2E) testing differ from Unit and Integration testing?",
    "code_snippet": null,
    "options": ["E2E tests only check TypeScript types", "E2E tests run the entire application (frontend, backend, database) in a real browser to simulate actual user workflows", "E2E tests are faster than unit tests", "E2E tests do not use assertions"],
    "correct_answer": "E2E tests run the entire application (frontend, backend, database) in a real browser to simulate actual user workflows",
    "explanation": "While unit tests isolate a single function, E2E tests (using tools like Playwright or Cypress) verify that the entire system works together. If a user clicks 'Checkout', E2E ensures the UI updates, the API receives the request, and the database records the order."
  },
  {
    "id": 552,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Playwright (Auto-waiting)",
    "question": "What is Playwright's 'auto-waiting' mechanism, and why is it a massive advantage over older testing tools?",
    "code_snippet": null,
    "options": ["It automatically waits for 5 seconds before every test", "It automatically waits for elements to be actionable (visible, stable, enabled) before interacting with them, eliminating the need for manual `sleep()` or `waitFor()` calls", "It waits for the database to connect", "It waits for TypeScript to compile"],
    "correct_answer": "It automatically waits for elements to be actionable (visible, stable, enabled) before interacting with them, eliminating the need for manual `sleep()` or `waitFor()` calls",
    "explanation": "Flaky tests are often caused by race conditions where the test clicks an element before it's fully rendered. Playwright's auto-waiting intelligently checks the DOM state, making E2E tests incredibly stable and reliable."
  },
  {
    "id": 553,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Playwright (Locators)",
    "question": "Fill in the blank to correctly use Playwright's recommended, accessibility-first locator to click a 'Submit' button.",
    "code_snippet": "await page._______('button', { name: 'Submit' }).click();",
    "options": ["getByRole", "querySelector", "findById", "locate"],
    "correct_answer": "getByRole",
    "explanation": "Just like React Testing Library, Playwright encourages querying by ARIA roles. `page.getByRole('button', { name: 'Submit' })` ensures you are testing the element exactly how a screen reader or keyboard user would find it."
  },
  {
    "id": 554,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Playwright (Visual Regression)",
    "question": "How do you perform Visual Regression Testing in Playwright to ensure CSS changes don't break the UI layout?",
    "code_snippet": null,
    "options": ["By manually comparing screenshots", "By using the `await expect(page).toHaveScreenshot()` assertion, which compares the current render against a baseline image and fails if pixels differ beyond a threshold", "By checking CSS coverage", "Playwright does not support visual testing"],
    "correct_answer": "By using the `await expect(page).toHaveScreenshot()` assertion, which compares the current render against a baseline image and fails if pixels differ beyond a threshold",
    "explanation": "Visual regression testing catches bugs that functional tests miss, like a CSS update that accidentally turns all text white on a white background, or a misaligned flex container."
  },
  {
    "id": 555,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "API Mocking (MSW Concept)",
    "question": "What is the core architectural advantage of using Mock Service Worker (MSW) over mocking `fetch` or `axios` directly in your tests?",
    "code_snippet": null,
    "options": ["MSW is faster", "MSW intercepts requests at the network level (via Service Workers in the browser, or interceptors in Node), meaning your application code doesn't need to know it's being mocked", "MSW automatically writes tests", "MSW replaces TypeScript"],
    "correct_answer": "MSW intercepts requests at the network level (via Service Workers in the browser, or interceptors in Node), meaning your application code doesn't need to know it's being mocked",
    "explanation": "Because MSW operates at the network boundary, you test your actual `fetch` logic, error handling, and loading states without changing a single line of your production code to accommodate test mocks."
  },
  {
    "id": 556,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "MSW (Handlers)",
    "question": "Fill in the blank to correctly define an MSW v2 handler that intercepts a GET request to `/api/user` and returns a JSON response.",
    "code_snippet": "import { http, HttpResponse } from 'msw';\n\nexport const handlers = [\n  http.get('/api/user', () => {\n    return HttpResponse._______({ id: 1, name: 'Alice' });\n  })\n];",
    "options": ["send", "json", "text", "return"],
    "correct_answer": "json",
    "explanation": "In MSW v2, `HttpResponse.json()` is the standard way to return mock JSON data. It automatically sets the correct `Content-Type: application/json` headers, perfectly mimicking a real backend."
  },
  {
    "id": 557,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Integration Testing (Concept)",
    "question": "What is the primary focus of an 'Integration Test' in a TypeScript application?",
    "code_snippet": null,
    "options": ["Testing a single pure function", "Testing how multiple modules (e.g., a React component, a custom hook, and an API call) work together to fulfill a specific feature", "Testing the database schema", "Testing CSS styles"],
    "correct_answer": "Testing how multiple modules (e.g., a React component, a custom hook, and an API call) work together to fulfill a specific feature",
    "explanation": "Integration tests sit between Unit and E2E tests. They verify that the 'glue' between your components is correct, catching bugs where Module A passes data to Module B in an unexpected format."
  },
  {
    "id": 558,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Database Testing (Testcontainers)",
    "question": "When testing backend TypeScript code that uses Prisma or Drizzle, what is the safest way to test database mutations without corrupting your local development database?",
    "code_snippet": null,
    "options": ["Using the production database", "Using Testcontainers to spin up a temporary, isolated Docker database for the test suite, which is destroyed afterward", "Mocking the database entirely", "Skipping database tests"],
    "correct_answer": "Using Testcontainers to spin up a temporary, isolated Docker database for the test suite, which is destroyed afterward",
    "explanation": "Testcontainers allows you to run real integration tests against a genuine PostgreSQL/MySQL instance in an ephemeral Docker container. This guarantees your SQL queries and ORM migrations work perfectly in CI."
  },
  {
    "id": 559,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "CI/CD (Concept)",
    "question": "What does 'CI' (Continuous Integration) automatically do every time a developer pushes code to a repository?",
    "code_snippet": null,
    "options": ["Deploys the app to production", "Runs the test suite, linter, and TypeScript compiler to verify the new code doesn't break existing functionality", "Writes unit tests for the new code", "Deletes old branches"],
    "correct_answer": "Runs the test suite, linter, and TypeScript compiler to verify the new code doesn't break existing functionality",
    "explanation": "CI is your automated quality gate. It ensures that no code is merged into the main branch unless it passes all TypeScript checks, formatting rules, and unit/integration tests."
  },
  {
    "id": 560,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "topic": "GitHub Actions (Triggers)",
    "question": "Fill in the blank to correctly configure a GitHub Actions workflow to run on every Pull Request targeting the 'main' branch.",
    "code_snippet": "name: CI\n_______:\n  pull_request:\n    branches: [main]",
    "options": ["on", "trigger", "run", "start"],
    "correct_answer": "on",
    "explanation": "The `on` key in GitHub Actions YAML defines the events that trigger the workflow. `on: pull_request` ensures the CI pipeline runs automatically whenever a developer opens or updates a PR."
  },
  {
    "id": 561,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "GitHub Actions (Caching)",
    "question": "Why is caching `node_modules` or the pnpm/yarn store critical in a CI pipeline?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It prevents the CI server from having to download and install all dependencies from scratch on every single run, reducing build times from minutes to seconds", "It encrypts the dependencies", "It is required by GitHub"],
    "correct_answer": "It prevents the CI server from having to download and install all dependencies from scratch on every single run, reducing build times from minutes to seconds",
    "explanation": "Actions like `actions/setup-node` have built-in caching. By caching the dependency tree, you save massive amounts of compute time and avoid hitting npm registry rate limits."
  },
  {
    "id": 562,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "GitHub Actions (Secrets)",
    "question": "How do you securely pass a database URL or API key to a GitHub Actions workflow without exposing it in the code?",
    "code_snippet": null,
    "options": ["Hardcoding it in the YAML file", "Storing it in GitHub Repository Secrets and accessing it via `${{ secrets.MY_SECRET_NAME }}`", "Putting it in a public `.env` file", "Emailing it to the CI server"],
    "correct_answer": "Storing it in GitHub Repository Secrets and accessing it via `${{ secrets.MY_SECRET_NAME }}`",
    "explanation": "GitHub Secrets are encrypted environment variables. They are injected into the CI runner at runtime and are automatically masked in the CI logs, preventing accidental credential leaks."
  },
  {
    "id": 563,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "GitHub Actions (Matrix Builds)",
    "question": "What is a 'Matrix Strategy' in GitHub Actions, and why is it useful for TypeScript libraries?",
    "code_snippet": null,
    "options": ["It runs tests in a random order", "It allows you to run the same test suite across multiple environments simultaneously (e.g., Node 18, Node 20, and Node 22) to ensure compatibility", "It compresses the code", "It translates the code"],
    "correct_answer": "It allows you to run the same test suite across multiple environments simultaneously (e.g., Node 18, Node 20, and Node 22) to ensure compatibility",
    "explanation": "If you are publishing an npm package, a matrix build guarantees that your TypeScript code compiles and runs correctly regardless of which Node.js version your consumers are using."
  },
  {
    "id": 564,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Docker (Multi-stage Builds)",
    "question": "Why are 'Multi-stage builds' considered a best practice when creating a Dockerfile for a TypeScript application?",
    "code_snippet": null,
    "options": ["They make the TypeScript code run faster", "They allow you to use a heavy image with all devDependencies to compile the TS code, and then copy ONLY the compiled JS and production dependencies into a tiny, secure final image", "They automatically write tests", "They encrypt the Docker container"],
    "correct_answer": "They allow you to use a heavy image with all devDependencies to compile the TS code, and then copy ONLY the compiled JS and production dependencies into a tiny, secure final image",
    "explanation": "A multi-stage build drastically reduces the final Docker image size (often from 1GB+ to under 150MB) and improves security by ensuring tools like TypeScript, Vitest, and ESLint are never present in the production environment."
  },
  {
    "id": 565,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank with the name of the file used to prevent Docker from copying unnecessary local files (like `node_modules` or `.git`) into the image.",
    "code_snippet": "_______\nnode_modules\n.git\n*.md",
    "options": [".dockerignore", ".gitignore", ".env", "Dockerfile"],
    "correct_answer": ".dockerignore",
    "explanation": "Just like `.gitignore` prevents files from being committed to Git, `.dockerignore` prevents local files from being sent to the Docker daemon during the build context, saving time and preventing local dev artifacts from polluting the container."
  },
  {
    "id": 566,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Monorepo CI (Affected Commands)",
    "question": "In a monorepo (using Turborepo or Nx), what does the `--filter` or `affected` command do during a CI run?",
    "code_snippet": null,
    "options": ["It runs all tests in the entire monorepo", "It analyzes the Git diff and dependency graph to ONLY build, test, and lint the specific packages that were actually modified by the PR", "It deletes unused packages", "It merges branches"],
    "correct_answer": "It analyzes the Git diff and dependency graph to ONLY build, test, and lint the specific packages that were actually modified by the PR",
    "explanation": "In a monorepo with 50 packages, running all tests on every PR would take hours. 'Affected' commands ensure CI only runs tests for the `ui-library` if a file inside `ui-library` changed, keeping CI lightning fast."
  },
  {
    "id": 567,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Monorepo CI (Remote Caching)",
    "question": "What is 'Remote Caching' in tools like Turborepo, and how does it revolutionize CI pipelines?",
    "code_snippet": null,
    "options": ["It stores code in the cloud", "If Developer A's CI already built and tested a package, Developer B's CI can download the cached artifacts instead of re-running the tasks, reducing CI times to near zero", "It backs up the database", "It compiles TypeScript to WebAssembly"],
    "correct_answer": "If Developer A's CI already built and tested a package, Developer B's CI can download the cached artifacts instead of re-running the tasks, reducing CI times to near zero",
    "explanation": "Remote caching shares the build cache across the entire team and the CI environment. If a package hasn't changed, its build output is mathematically guaranteed to be identical, allowing CI to simply download the result."
  },
  {
    "id": 568,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Preview Environments)",
    "question": "What is a 'Preview Environment' in modern CI/CD (like Vercel or Netlify)?",
    "code_snippet": null,
    "options": ["A local testing tool", "An automatically generated, fully functional, isolated URL deployed for every single Pull Request, allowing stakeholders to test changes before merging", "A CSS preprocessor", "A database migration tool"],
    "correct_answer": "An automatically generated, fully functional, isolated URL deployed for every single Pull Request, allowing stakeholders to test changes before merging",
    "explanation": "Preview environments bridge the gap between development and production. Designers, PMs, and QA can click a link in the GitHub PR and interact with the exact Server Components and Database changes proposed in the code."
  },
  {
    "id": 569,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Observability (Source Maps)",
    "question": "Why is it critical to upload TypeScript Source Maps to your error tracking service (like Sentry or Datadog) during the CI/CD deployment step?",
    "code_snippet": null,
    "options": ["To make the code run faster", "To translate the minified, compiled JavaScript stack traces back into the original, readable TypeScript code and exact line numbers when an error occurs in production", "To encrypt the code", "To compress the bundle"],
    "correct_answer": "To translate the minified, compiled JavaScript stack traces back into the original, readable TypeScript code and exact line numbers when an error occurs in production",
    "explanation": "When production JS crashes, the stack trace points to `main.js:14:5023`, which is useless. Source maps allow tools like Sentry to map that back to `src/components/Button.tsx:42`, enabling instant debugging."
  },
  {
    "id": 570,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (DevOps Philosophy)",
    "question": "What is the ultimate philosophy of mastering Testing, CI/CD, and DevOps for TypeScript applications?",
    "code_snippet": null,
    "options": ["To make the developer's life harder", "To automate every possible verification and deployment step, creating a fearless, high-velocity environment where code is continuously validated, securely containerized, and reliably delivered to users", "To replace TypeScript with JavaScript", "To avoid writing tests entirely"],
    "correct_answer": "To automate every possible verification and deployment step, creating a fearless, high-velocity environment where code is continuously validated, securely containerized, and reliably delivered to users",
    "explanation": "DevOps is not about bureaucracy; it's about velocity and confidence. When your CI/CD pipeline, type-checker, and test suite are perfectly tuned, you can deploy to production on a Friday afternoon with absolute peace of mind."
  }
]
[
  {
    "id": 571,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Playwright (Fixtures)",
    "question": "What are 'Fixtures' in Playwright, and why are they superior to standard `beforeEach` setup blocks?",
    "code_snippet": null,
    "options": ["They are CSS files for the test runner", "They provide a mechanism to compose custom test environments and setup/teardown logic that is automatically injected into the test function's parameters, ensuring perfect isolation", "They are database migration scripts", "They are used to mock network requests"],
    "correct_answer": "They provide a mechanism to compose custom test environments and setup/teardown logic that is automatically injected into the test function's parameters, ensuring perfect isolation",
    "explanation": "Fixtures allow you to define reusable test context (like a logged-in user or a pre-seeded database). Playwright automatically sets them up before the test and tears them down after, guaranteeing that tests never leak state into one another."
  },
  {
    "id": 572,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Playwright (Authentication State)",
    "question": "How do you prevent Playwright from having to log in via the UI before every single E2E test?",
    "code_snippet": null,
    "options": ["By hardcoding passwords in the test file", "By running a global setup script once to log in, saving the cookies/localStorage to a `storageState` JSON file, and loading that state in all subsequent tests", "By disabling authentication in the test environment", "Playwright does not support authentication testing"],
    "correct_answer": "By running a global setup script once to log in, saving the cookies/localStorage to a `storageState` JSON file, and loading that state in all subsequent tests",
    "explanation": "Using `storageState` bypasses the slow, flaky UI login process for every test. It injects the authenticated session directly into the browser context, saving minutes of CI time per test suite."
  },
  {
    "id": 573,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Contract Testing (Pact)",
    "question": "What is 'Contract Testing' (e.g., using Pact.js) in a microservices architecture?",
    "code_snippet": null,
    "options": ["Testing legal compliance", "Testing the exact JSON schema and HTTP expectations between a Consumer and a Provider independently, ensuring an update to one doesn't break the other", "Testing database schemas", "Testing CSS layouts"],
    "correct_answer": "Testing the exact JSON schema and HTTP expectations between a Consumer and a Provider independently, ensuring an update to one doesn't break the other",
    "explanation": "Instead of spinning up all microservices for an E2E test, Contract Testing verifies the 'contract' (the API payload). If the backend changes a field name, the contract test fails immediately, preventing a production outage."
  },
  {
    "id": 574,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Performance (Lighthouse CI)",
    "question": "How do you enforce Core Web Vitals performance budgets automatically in a CI pipeline?",
    "code_snippet": null,
    "options": ["By manually checking PageSpeed Insights", "By integrating Lighthouse CI (`lhci`) to run audits on every PR and fail the build if metrics like LCP or CLS exceed defined thresholds", "By using a CSS minifier", "You cannot automate performance testing"],
    "correct_answer": "By integrating Lighthouse CI (`lhci`) to run audits on every PR and fail the build if metrics like LCP or CLS exceed defined thresholds",
    "explanation": "Lighthouse CI acts as an automated performance gatekeeper. If a developer accidentally imports a massive 2MB JavaScript bundle, `lhci` will catch the LCP regression and block the PR from merging."
  },
  {
    "id": 575,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Security (Dependency Auditing)",
    "question": "What is the purpose of running `npm audit` or using tools like Snyk/Socket in a CI pipeline?",
    "code_snippet": null,
    "options": ["To format the code", "To scan the `node_modules` dependency tree for known CVEs (Common Vulnerabilities and Exposures) and block the build if critical vulnerabilities are found", "To check for TypeScript type errors", "To compress the bundle"],
    "correct_answer": "To scan the `node_modules` dependency tree for known CVEs (Common Vulnerabilities and Exposures) and block the build if critical vulnerabilities are found",
    "explanation": "Supply chain attacks are a massive threat. Automated dependency scanning ensures you aren't accidentally shipping a package with a known security flaw into production."
  },
  {
    "id": 576,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Security (Secrets Scanning)",
    "question": "How do you prevent developers from accidentally committing AWS keys or `.env` secrets to the Git repository?",
    "code_snippet": null,
    "options": ["By trusting developers to remember", "By using pre-commit hooks (like Husky) and tools like TruffleHog or GitGuardian to scan diffs for high-entropy strings and block the commit", "By deleting the `.git` folder", "By using `any` types"],
    "correct_answer": "By using pre-commit hooks (like Husky) and tools like TruffleHog or GitGuardian to scan diffs for high-entropy strings and block the commit",
    "explanation": "Once a secret is pushed to GitHub, it is considered compromised, even if deleted later. Pre-commit hooks and CI secret scanners act as the ultimate safety net to catch leaks before they leave the developer's machine."
  },
  {
    "id": 577,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "CI/CD (Trunk-Based Development)",
    "question": "What is 'Trunk-Based Development'?",
    "code_snippet": null,
    "options": ["Using a single, massive Git branch for all features", "A branching model where developers commit to short-lived feature branches and merge into the main 'trunk' (main/master) multiple times a day, avoiding long-lived release branches", "Using SVN instead of Git", "Deploying directly to production without testing"],
    "correct_answer": "A branching model where developers commit to short-lived feature branches and merge into the main 'trunk' (main/master) multiple times a day, avoiding long-lived release branches",
    "explanation": "Trunk-based development minimizes merge conflicts, enables continuous integration, and ensures that the `main` branch is always in a deployable state, which is the foundation of modern DevOps."
  },
  {
    "id": 578,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Feature Flags)",
    "question": "How do Feature Flags (e.g., LaunchDarkly, Unleash) decouple 'deployment' from 'release'?",
    "code_snippet": null,
    "options": ["They compress the code", "They allow developers to merge incomplete features into `main` and deploy them to production hidden behind a toggle, enabling safe, gradual rollouts and instant rollbacks", "They encrypt the database", "They automatically write tests"],
    "correct_answer": "They allow developers to merge incomplete features into `main` and deploy them to production hidden behind a toggle, enabling safe, gradual rollouts and instant rollbacks",
    "explanation": "With Feature Flags, you deploy the code continuously. The 'release' to users is controlled by flipping a boolean flag. If a bug is found, you turn the flag off instantly without needing to revert code and redeploy."
  },
  {
    "id": 579,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Testing (Snapshot Testing)",
    "question": "What is the primary danger of relying too heavily on Snapshot Testing (e.g., Jest/Vitest `toMatchSnapshot()`)?",
    "code_snippet": null,
    "options": ["They make tests run slower", "Developers often blindly update snapshots (`-u`) when a test fails without actually verifying if the UI change was intentional, leading to bugs slipping into production", "They cannot test React components", "They require a database"],
    "correct_answer": "Developers often blindly update snapshots (`-u`) when a test fails without actually verifying if the UI change was intentional, leading to bugs slipping into production",
    "explanation": "Snapshot tests verify what the output *is*, not what it *should be*. They are great for catching accidental regressions, but terrible for verifying business logic or intentional design changes."
  },
  {
    "id": 580,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Testing (Mutation Testing)",
    "question": "What is 'Mutation Testing' (e.g., using Stryker)?",
    "code_snippet": null,
    "options": ["Testing CSS animations", "Automatically introducing small bugs (mutations) into your source code to verify that your test suite actually catches them and fails", "Testing database migrations", "Testing TypeScript types"],
    "correct_answer": "Automatically introducing small bugs (mutations) into your source code to verify that your test suite actually catches them and fails",
    "explanation": "Mutation testing measures the *quality* of your tests, not just code coverage. If Stryker changes a `>` to a `>=` and your tests still pass, it proves your tests are too weak to catch that logical bug."
  },
  {
    "id": 581,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "DevOps (Infrastructure as Code - Pulumi)",
    "question": "What is the primary advantage of using Pulumi over Terraform for TypeScript engineers?",
    "code_snippet": null,
    "options": ["Pulumi is written in Rust", "Pulumi allows you to define cloud infrastructure (AWS, GCP, Azure) using native TypeScript, leveraging IDE autocomplete, type safety, and standard npm packages", "Pulumi does not support cloud providers", "Pulumi is only for frontend"],
    "correct_answer": "Pulumi allows you to define cloud infrastructure (AWS, GCP, Azure) using native TypeScript, leveraging IDE autocomplete, type safety, and standard npm packages",
    "explanation": "Instead of learning HCL (Terraform's custom language), TypeScript engineers can use familiar constructs like `for` loops, classes, and interfaces to provision secure, repeatable cloud infrastructure."
  },
  {
    "id": 582,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "DevOps (AWS CDK)",
    "question": "What is the AWS Cloud Development Kit (CDK)?",
    "code_snippet": null,
    "options": ["A CSS framework", "An open-source framework that lets you define AWS cloud resources (Lambda, DynamoDB, S3) using TypeScript, which compiles down to CloudFormation templates", "A testing library", "A database ORM"],
    "correct_answer": "An open-source framework that lets you define AWS cloud resources (Lambda, DynamoDB, S3) using TypeScript, which compiles down to CloudFormation templates",
    "explanation": "AWS CDK brings the power of TypeScript to cloud architecture. You can create reusable 'Constructs' (e.g., a standardized API Gateway + Lambda setup) and share them across your organization via npm."
  },
  {
    "id": 583,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Canary Releases)",
    "question": "What is a 'Canary Deployment'?",
    "code_snippet": null,
    "options": ["Deploying to a staging environment", "Routing a small percentage of production traffic (e.g., 5%) to the new version, monitoring for errors, and gradually increasing to 100% if stable", "Deploying only on weekends", "Rolling back a deployment"],
    "correct_answer": "Routing a small percentage of production traffic (e.g., 5%) to the new version, monitoring for errors, and gradually increasing to 100% if stable",
    "explanation": "Canary deployments minimize the 'blast radius' of a bad release. If the new TypeScript code throws a 500 error, it only affects 5% of users, and the load balancer can automatically route traffic back to the old version."
  },
  {
    "id": 584,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Observability (OpenTelemetry)",
    "question": "What is OpenTelemetry (OTel) in the context of a TypeScript backend?",
    "code_snippet": null,
    "options": ["A CSS framework", "A vendor-neutral standard for generating, collecting, and exporting telemetry data (Traces, Metrics, and Logs) to understand system performance", "A testing library", "A database"],
    "correct_answer": "A vendor-neutral standard for generating, collecting, and exporting telemetry data (Traces, Metrics, and Logs) to understand system performance",
    "explanation": "By instrumenting your Node.js/Next.js code with OTel, you can trace a single HTTP request as it travels from the frontend, through the API gateway, into the database, and back, making debugging distributed systems possible."
  },
  {
    "id": 585,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Observability (Structured Logging)",
    "question": "Why is 'Structured Logging' (outputting JSON instead of plain text) critical for production TypeScript applications?",
    "code_snippet": null,
    "options": ["It makes the logs look prettier", "It allows log aggregation tools (like Datadog, ELK, or CloudWatch) to automatically parse, index, and query specific fields (like `userId` or `traceId`)", "It compresses the logs", "It encrypts the logs"],
    "correct_answer": "It allows log aggregation tools (like Datadog, ELK, or CloudWatch) to automatically parse, index, and query specific fields (like `userId` or `traceId`)",
    "explanation": "Instead of grepping through millions of text lines, structured JSON logs let you query: `SELECT * FROM logs WHERE level='error' AND userId='123'`, reducing debugging time from hours to seconds."
  },
  {
    "id": 586,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Event-Driven)",
    "question": "What is an 'Event-Driven Architecture' in TypeScript?",
    "code_snippet": null,
    "options": ["Using React synthetic events", "Decoupling services by having them publish events to a message broker (like RabbitMQ, Kafka, or AWS SQS) rather than calling each other directly via HTTP", "Using CSS animations", "Using GraphQL"],
    "correct_answer": "Decoupling services by having them publish events to a message broker (like RabbitMQ, Kafka, or AWS SQS) rather than calling each other directly via HTTP",
    "explanation": "If a user signs up, the User Service publishes a `UserCreated` event. The Email Service and Analytics Service subscribe to it. This prevents tight coupling and allows services to scale independently."
  },
  {
    "id": 587,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Tooling (The Rise of Rust)",
    "question": "Why are tools like SWC, Rolldown, OXC, and Biome revolutionizing the TypeScript ecosystem?",
    "code_snippet": null,
    "options": ["They are written in Rust, making them 10x-100x faster than traditional JavaScript/Node.js-based tools like Babel, Webpack, and ESLint", "They are written in Python", "They replace TypeScript entirely", "They only work on Windows"],
    "correct_answer": "They are written in Rust, making them 10x-100x faster than traditional JavaScript/Node.js-based tools like Babel, Webpack, and ESLint",
    "explanation": "The JavaScript ecosystem is undergoing a 'Rust Renaissance'. By moving parsing, bundling, and linting to native Rust binaries, build times that used to take minutes are now reduced to milliseconds."
  },
  {
    "id": 588,
    "level": "intermediate",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Testing Philosophy (The Testing Trophy)",
    "question": "What is Guillermo Rauch's 'Testing Trophy' concept, and how does it differ from the traditional 'Testing Pyramid'?",
    "code_snippet": null,
    "options": ["It advocates for 100% unit test coverage", "It suggests investing heavily in Integration and E2E tests (the thick middle of the trophy) rather than obsessing over isolated unit tests, because integration tests provide the highest confidence for web apps", "It suggests only writing E2E tests", "It is a CSS layout model"],
    "correct_answer": "It suggests investing heavily in Integration and E2E tests (the thick middle of the trophy) rather than obsessing over isolated unit tests, because integration tests provide the highest confidence for web apps",
    "explanation": "In modern React/Next.js development, testing how components hook together (Integration) and how the user flows through the app (E2E) catches more real-world bugs than testing isolated utility functions (Unit)."
  },
  {
    "id": 589,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Monorepo (Task Orchestration)",
    "question": "In a massive TypeScript monorepo, what is the role of a task orchestrator like Turborepo or Nx?",
    "code_snippet": null,
    "options": ["To format the code", "To understand the dependency graph of all packages and execute build/test/lint tasks in parallel, while caching the results to skip unchanged work", "To write unit tests", "To deploy to AWS"],
    "correct_answer": "To understand the dependency graph of all packages and execute build/test/lint tasks in parallel, while caching the results to skip unchanged work",
    "explanation": "Without an orchestrator, a monorepo CI pipeline runs sequentially and rebuilds everything. Turborepo/Nx analyze the codebase, build the `ui-lib` before the `app` that depends on it, and cache the outputs so subsequent runs are instant."
  },
  {
    "id": 590,
    "level": "advanced",
    "module_id": "ts_mod_08_testing_devops",
    "module_name": "Testing, CI/CD & DevOps for TypeScript",
    "type": "conceptual",
    "topic": "Final Philosophy (The Zen of the TS Engineer)",
    "question": "You have now completed the entire TypeScript curriculum. What is the ultimate hallmark of a true Senior TypeScript Engineer?",
    "code_snippet": null,
    "options": ["Memorizing every generic utility type", "Understanding that TypeScript is just one part of the puzzle; true mastery lies in combining type safety, rigorous testing, automated CI/CD, and observability to deliver resilient, high-velocity software that solves real human problems", "Writing code without comments", "Avoiding third-party libraries"],
    "correct_answer": "Understanding that TypeScript is just one part of the puzzle; true mastery lies in combining type safety, rigorous testing, automated CI/CD, and observability to deliver resilient, high-velocity software that solves real human problems",
    "explanation": "TypeScript, React, Next.js, Vitest, Docker, and GitHub Actions are all just tools. The true Senior Engineer uses them in harmony to build systems that are safe to change, easy to understand, and a joy to maintain. Congratulations on completing this monumental journey!"
  }
]
