[
  {
    "id": 291,
    "level": "beginner",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "ES Modules Basics",
    "question": "What is the standard, modern way to organize and share code between files in TypeScript and JavaScript?",
    "code_snippet": null,
    "options": ["Using global variables", "Using ES Modules (import/export syntax)", "Using XML namespaces", "Using HTML script tags"],
    "correct_answer": "Using ES Modules (import/export syntax)",
    "explanation": "ES Modules (ESM) provide a static, compile-time analyzable system for importing and exporting code. TypeScript fully embraces ESM as the standard for modular architecture, enabling tree-shaking and strict dependency tracking."
  },
  {
    "id": 292,
    "level": "beginner",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "topic": "Default Exports",
    "question": "Fill in the blank to correctly export a class as the single 'default' export of a file.",
    "code_snippet": "_______ default class UserService {\n  // ...\n}",
    "options": ["export", "module.exports", "declare", "public"],
    "correct_answer": "export",
    "explanation": "The `export default` syntax marks a specific value (class, function, or object) as the primary export of the file. A module can only have ONE default export, and it can be imported using any name the consumer chooses."
  },
  {
    "id": 293,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Named vs Default Exports",
    "question": "What is the primary advantage of using 'Named Exports' over 'Default Exports'?",
    "code_snippet": null,
    "options": ["Named exports are faster at runtime", "Named exports enforce strict naming consistency, make refactoring easier, and allow multiple exports per file", "Default exports are deprecated", "Named exports automatically convert to CommonJS"],
    "correct_answer": "Named exports enforce strict naming consistency, make refactoring easier, and allow multiple exports per file",
    "explanation": "With named exports (`export const x = 1`), the importer MUST use the exact same name (`import { x }`). This prevents the chaos of a single file being imported under 50 different names across a large codebase."
  },
  {
    "id": 294,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "topic": "Namespace Imports",
    "question": "Fill in the blank to correctly import ALL named exports from a file into a single namespace object.",
    "code_snippet": "_______ * as Utils from './utils';",
    "options": ["import", "require", "include", "use"],
    "correct_answer": "import",
    "explanation": "The `import * as Name` syntax gathers all named exports into a single object. It's incredibly useful for utility libraries (e.g., `Utils.formatDate()`) and prevents polluting the local scope with dozens of individual imports."
  },
  {
    "id": 295,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Type-Only Imports (import type)",
    "question": "What is the specific purpose of the `import type` syntax introduced in TypeScript 3.8?",
    "code_snippet": null,
    "options": ["To import JSON files", "To import interfaces and types that are guaranteed to be completely erased during compilation, preventing circular dependency issues and reducing bundle size", "To import CSS modules", "To import runtime JavaScript functions"],
    "correct_answer": "To import interfaces and types that are guaranteed to be completely erased during compilation, preventing circular dependency issues and reducing bundle size",
    "explanation": "Because types don't exist at runtime, `import type` tells the compiler (and bundlers like Webpack/Vite) to strip this import out entirely. It guarantees you won't accidentally use a type as a runtime value, and it prevents circular import crashes."
  },
  {
    "id": 296,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "topic": "Type-Only Imports Syntax",
    "question": "Fill in the blank to correctly import ONLY the `User` interface from the './models' file.",
    "code_snippet": "import _______ { User } from './models';",
    "options": ["type", "interface", "typeof", "class"],
    "correct_answer": "type",
    "explanation": "You can also use the inline `import { type User }` syntax if you want to mix runtime values and types in a single import statement. But `import type { User }` is the standard for files that only need types."
  },
  {
    "id": 297,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "output-prediction",
    "topic": "Type-Only Erasure",
    "question": "What will the compiled JavaScript output look like for the following TypeScript code?",
    "code_snippet": "import type { Config } from './config';\nconst myConfig: Config = { port: 3000 };",
    "code_snippet_options": [
      "const myConfig = { port: 3000 };",
      "const config_1 = require('./config');\nconst myConfig = { port: 3000 };",
      "import { Config } from './config';\nconst myConfig = { port: 3000 };",
      "It throws a compile-time error"
    ],
    "options": ["Option A: const myConfig = { port: 3000 };", "Option B: const config_1 = require...;", "Option C: import { Config }...;", "Option D: Error"],
    "correct_answer": "Option A: const myConfig = { port: 3000 };",
    "explanation": "Because `Config` is imported via `import type`, the TypeScript compiler completely erases the import statement from the final JavaScript output. The resulting JS only contains the runtime variable assignment."
  },
  {
    "id": 298,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "CommonJS Interop (export =)",
    "question": "How do you correctly type a TypeScript module that uses the legacy CommonJS `module.exports = ...` pattern?",
    "code_snippet": null,
    "options": ["export default", "export = myFunction", "module.exports: myFunction", "export commonjs"],
    "correct_answer": "export = myFunction",
    "explanation": "The `export =` syntax is TypeScript's way of modeling CommonJS `module.exports`. To import it, the consumer MUST use the `import x = require('...')` syntax or enable `esModuleInterop` to use standard default imports."
  },
  {
    "id": 299,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Declaration Files (.d.ts)",
    "question": "What is the purpose of a `.d.ts` file in the TypeScript ecosystem?",
    "code_snippet": null,
    "options": ["To store CSS styles", "To provide type definitions for JavaScript libraries that don't have native TypeScript code, allowing TS to type-check them", "To compile TypeScript to C++", "To store environment variables"],
    "correct_answer": "To provide type definitions for JavaScript libraries that don't have native TypeScript code, allowing TS to type-check them",
    "explanation": "Declaration files contain ONLY type information (interfaces, function signatures) and zero runtime JavaScript. They are usually distributed via DefinitelyTyped (`@types/package-name`) so TS developers can use popular JS libraries safely."
  },
  {
    "id": 300,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "topic": "Ambient Declarations",
    "question": "Fill in the blank to correctly tell TypeScript about a global variable `__APP_VERSION__` that is injected at runtime by a build tool.",
    "code_snippet": "_______ const __APP_VERSION__: string;",
    "options": ["declare", "global", "ambient", "extern"],
    "correct_answer": "declare",
    "explanation": "The `declare` keyword creates an 'ambient declaration'. It tells TypeScript, 'Trust me, this variable exists at runtime (injected by Webpack/Vite), don't throw an error even though you can't see its implementation.'"
  },
  {
    "id": 301,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Module Augmentation (declare module)",
    "question": "How do you add custom types to a third-party library (like Express or React) that doesn't include them natively?",
    "code_snippet": null,
    "options": ["By editing the library's source code in node_modules", "By using `declare module 'library-name' { ... }` in a global `.d.ts` file to merge your types with theirs", "By using `@ts-ignore`", "You cannot augment third-party libraries"],
    "correct_answer": "By using `declare module 'library-name' { ... }` in a global `.d.ts` file to merge your types with theirs",
    "explanation": "Module augmentation allows you to safely extend the types of external libraries without forking them. For example, adding a `user` property to Express's `Request` object so it's typed everywhere in your app."
  },
  {
    "id": 302,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Global Augmentation (declare global)",
    "question": "If you are inside a module (a file with `import`/`export`), how do you augment the global scope (like the `Window` interface)?",
    "code_snippet": null,
    "options": ["Just write `interface Window { ... }`", "Wrap your interface in a `declare global { ... }` block", "Use `export global`", "Use `window.extend()`"],
    "correct_answer": "Wrap your interface in a `declare global { ... }` block",
    "explanation": "Because files with `import`/`export` are scoped modules, their declarations don't leak globally. `declare global` explicitly breaks out of the module scope to merge with the global environment."
  },
  {
    "id": 303,
    "level": "beginner",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "tsconfig.json Basics",
    "question": "What is the primary purpose of the `tsconfig.json` file?",
    "code_snippet": null,
    "options": ["To define the project's database schema", "To configure the TypeScript compiler's behavior, strictness rules, and which files to include/exclude", "To store the application's runtime environment variables", "To format the code automatically"],
    "correct_answer": "To configure the TypeScript compiler's behavior, strictness rules, and which files to include/exclude",
    "explanation": "The presence of a `tsconfig.json` file in a directory tells the TypeScript compiler that this is the root of a TS project. It is the absolute source of truth for your build pipeline."
  },
  {
    "id": 304,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "moduleResolution",
    "question": "What does the `moduleResolution` compiler option control?",
    "code_snippet": null,
    "options": ["How CSS modules are resolved", "The algorithm TypeScript uses to figure out what a reference in an `import` statement actually points to (e.g., Node vs Bundler)", "How React components are rendered", "The speed of the compiler"],
    "correct_answer": "The algorithm TypeScript uses to figure out what a reference in an `import` statement actually points to (e.g., Node vs Bundler)",
    "explanation": "Modern TS 5.0 introduced `moduleResolution: 'bundler'`, which perfectly mimics how tools like Vite and Webpack resolve imports (allowing extensionless imports, `package.json` exports maps, etc.), bridging the gap between TS and modern JS bundlers."
  },
  {
    "id": 305,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "topic": "Path Mapping",
    "question": "Fill in the blank to correctly configure an alias in `tsconfig.json` so that `@components/Button` maps to `./src/components/Button`.",
    "code_snippet": "{\n  \"compilerOptions\": {\n    \"baseUrl\": \".\",\n    \"_______\": {\n      \"@components/*\": [\"src/components/*\"]\n    }\n  }\n}",
    "options": ["aliases", "paths", "routes", "links"],
    "correct_answer": "paths",
    "explanation": "The `paths` option allows you to create custom import aliases. Note: `paths` ONLY tells TypeScript how to resolve types; your bundler (Webpack/Vite) must ALSO be configured with the same aliases to resolve the runtime JavaScript."
  },
  {
    "id": 306,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Triple-Slash Directives",
    "question": "What is the purpose of the `/// <reference path=\"...\" />` directive?",
    "code_snippet": null,
    "options": ["To import CSS files", "To tell the compiler to include an additional file in the compilation process, primarily used in older projects or for global `.d.ts` files", "To create a comment block", "To define a React component"],
    "correct_answer": "To tell the compiler to include an additional file in the compilation process, primarily used in older projects or for global `.d.ts` files",
    "explanation": "While ES Modules (`import`) are the modern standard, triple-slash references are still used to link global declaration files (like `/// <reference types=\"node\" />`) or in legacy codebases that rely on script concatenation."
  },
  {
    "id": 307,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Namespaces vs Modules",
    "question": "Why are TypeScript 'Namespaces' (`namespace`) generally discouraged in modern development?",
    "code_snippet": null,
    "options": ["They are deprecated and throw errors", "They rely on global scope pollution and legacy script loading, whereas ES Modules provide strict, isolated, and tree-shakable scope", "They cannot contain classes", "They only work in Internet Explorer"],
    "correct_answer": "They rely on global scope pollution and legacy script loading, whereas ES Modules provide strict, isolated, and tree-shakable scope",
    "explanation": "Namespaces were TS's original way of organizing code before ES Modules existed. Today, they are mostly kept alive for internal compiler typings and legacy DefinitelyTyped definitions, but new code should always use `import`/`export`."
  },
  {
    "id": 308,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Namespace Merging",
    "question": "How can you use a Namespace to add static properties to a Function or Class?",
    "code_snippet": null,
    "options": ["By declaring a namespace with the exact same name as the function/class, allowing them to merge", "By using the `static` keyword inside the namespace", "By using `Object.assign()`", "You cannot merge namespaces with functions"],
    "correct_answer": "By declaring a namespace with the exact same name as the function/class, allowing them to merge",
    "explanation": "This is a classic TS pattern (Declaration Merging). If you have `function build() {}` and `namespace build { export const version = 1; }`, TS merges them, allowing you to call `build()` and access `build.version` safely."
  },
  {
    "id": 309,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Re-exporting",
    "question": "What is the syntax to re-export a named export from another file, creating a centralized 'barrel' file?",
    "code_snippet": null,
    "options": ["import { x } from './file'; export x;", "export { x } from './file';", "re-export { x } from './file';", "module.exports = require('./file');"],
    "correct_answer": "export { x } from './file';",
    "explanation": "Barrel files (usually `index.ts`) use `export { ... } from` to aggregate and expose a clean public API for a folder, hiding the internal file structure from the consumer."
  },
  {
    "id": 310,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "isolatedModules",
    "question": "What does the `isolatedModules: true` compiler flag enforce?",
    "code_snippet": null,
    "options": ["It prevents the use of global variables", "It ensures every file can be safely transpiled by single-file transpilers like Babel or esbuild, requiring explicit `export type` for type-only exports", "It isolates CSS modules", "It disables the `any` type"],
    "correct_answer": "It ensures every file can be safely transpiled by single-file transpilers like Babel or esbuild, requiring explicit `export type` for type-only exports",
    "explanation": "Tools like Babel don't do full type-checking; they just strip types file-by-file. `isolatedModules` forces you to write code that these fast transpilers can handle without breaking, which is mandatory if you use Create React App, Vite, or Next.js."
  }
]
[
  {
    "id": 311,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "noUncheckedIndexedAccess",
    "question": "What does the `noUncheckedIndexedAccess` compiler flag do?",
    "code_snippet": null,
    "options": ["It prevents you from using array indexes", "It adds `undefined` to the type of any property accessed via an index signature (e.g., `arr[0]` becomes `T | undefined`), preventing out-of-bounds errors", "It disables the `any` type", "It forces all arrays to be tuples"],
    "correct_answer": "It adds `undefined` to the type of any property accessed via an index signature (e.g., `arr[0]` becomes `T | undefined`), preventing out-of-bounds errors",
    "explanation": "Because TypeScript cannot guarantee that an array index or object key actually exists at runtime, this strict flag forces you to handle the `undefined` case, eliminating an entire category of 'cannot read property of undefined' runtime crashes."
  },
  {
    "id": 312,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "useUnknownInCatchVariables",
    "question": "What does the `useUnknownInCatchVariables: true` flag change about `catch (e)` blocks?",
    "code_snippet": null,
    "options": ["It prevents catch blocks from being used", "It changes the default type of the caught error variable `e` from `any` to `unknown`, forcing you to narrow or validate the error before using it", "It automatically logs the error to the console", "It converts the error to a string"],
    "correct_answer": "It changes the default type of the caught error variable `e` from `any` to `unknown`, forcing you to narrow or validate the error before using it",
    "explanation": "In JavaScript, you can `throw` anything (a string, a number, a custom object). By typing `e` as `unknown`, TypeScript forces you to prove what the error is (e.g., `if (e instanceof Error)`) before accessing properties like `.message`."
  },
  {
    "id": 313,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "noPropertyAccessFromIndexSignature",
    "question": "What does the `noPropertyAccessFromIndexSignature` flag enforce?",
    "code_snippet": null,
    "options": ["It prevents using dot notation on classes", "It forces you to use bracket notation (`obj['key']`) instead of dot notation (`obj.key`) when accessing properties that come from an index signature, making dynamic access explicit", "It disables index signatures entirely", "It converts all objects to Maps"],
    "correct_answer": "It forces you to use bracket notation (`obj['key']`) instead of dot notation (`obj.key`) when accessing properties that come from an index signature, making dynamic access explicit",
    "explanation": "If an object has a `[key: string]: any` signature, TS normally lets you use dot notation for known keys. This flag says, 'If it's a dynamic dictionary, treat it like one,' preventing typos on dictionary keys from silently passing as `undefined`."
  },
  {
    "id": 314,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly tell the TypeScript compiler to output `.d.ts` declaration files alongside the compiled `.js` files.",
    "code_snippet": "{\n  \"compilerOptions\": {\n    \"_______\": true\n  }\n}",
    "options": ["types", "declaration", "emit", "definitions"],
    "correct_answer": "declaration",
    "explanation": "The `\"declaration\": true` flag is mandatory if you are publishing a TypeScript library to npm. It generates the `.d.ts` files so that consumers of your library get full IntelliSense and type-checking."
  },
  {
    "id": 315,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "emitDeclarationOnly",
    "question": "If you are using a separate, ultra-fast bundler (like Vite, esbuild, or swc) to compile your JavaScript, but you still want TypeScript to generate the `.d.ts` type definitions, which flag should you use?",
    "code_snippet": null,
    "options": ["\"skipLibCheck\": true", "\"emitDeclarationOnly\": true", "\"noEmit\": true", "\"isolatedModules\": true"],
    "correct_answer": "\"emitDeclarationOnly\": true",
    "explanation": "This flag tells the TS compiler, 'Don't bother outputting the `.js` files, my bundler handles that. Just give me the `.d.ts` files.' This is the standard setup for modern, high-performance frontend toolchains."
  },
  {
    "id": 316,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "declarationMap",
    "question": "What is the purpose of the `\"declarationMap\": true` compiler option?",
    "code_snippet": null,
    "options": ["It minifies the `.d.ts` files", "It generates `.d.ts.map` files that allow IDEs to 'Go to Definition' and jump directly to the original `.ts` source code of a consumed library, rather than the compiled `.d.ts` file", "It creates a visual graph of your types", "It maps CSS modules"],
    "correct_answer": "It generates `.d.ts.map` files that allow IDEs to 'Go to Definition' and jump directly to the original `.ts` source code of a consumed library, rather than the compiled `.d.ts` file",
    "explanation": "Without declaration maps, clicking 'Go to Definition' on a third-party library takes you to the unreadable, generated `.d.ts` file. With it, your IDE seamlessly navigates back to the library author's original, beautifully typed `.ts` source code."
  },
  {
    "id": 317,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Project References (composite)",
    "question": "What is the purpose of TypeScript Project References (`\"composite\": true` and `\"references\": []`)?",
    "code_snippet": null,
    "options": ["To import CSS files", "They allow you to split a massive codebase into smaller, independently compilable sub-projects, enabling incremental builds and faster type-checking across monorepos", "To connect to a remote database", "To compile TypeScript to WebAssembly"],
    "correct_answer": "They allow you to split a massive codebase into smaller, independently compilable sub-projects, enabling incremental builds and faster type-checking across monorepos",
    "explanation": "In a massive monorepo, type-checking everything takes forever. Project References allow TS to build a dependency graph of your packages and only re-check the specific packages that actually changed, saving minutes of build time."
  },
  {
    "id": 318,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "tsconfig.json extends",
    "question": "How do you share a base `tsconfig.json` configuration across multiple packages in a monorepo?",
    "code_snippet": null,
    "options": ["By copying and pasting the file", "By using the `\"extends\": \"./tsconfig.base.json\"` property in the child `tsconfig.json` files", "By using environment variables", "You cannot share configurations"],
    "correct_answer": "By using the `\"extends\": \"./tsconfig.base.json\"` property in the child `tsconfig.json` files",
    "explanation": "The `extends` property allows you to define a strict, standardized base configuration (like `strict: true`) once, and have every package in your monorepo inherit it, ensuring absolute consistency."
  },
  {
    "id": 319,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "DefinitelyTyped (@types)",
    "question": "What is the standard naming convention for installing type definitions for a JavaScript library (e.g., `lodash`) from the DefinitelyTyped repository?",
    "code_snippet": null,
    "options": ["npm install lodash-types", "npm install --save-dev @types/lodash", "npm install --save @typings/lodash", "npm install lodash.d.ts"],
    "correct_answer": "npm install --save-dev @types/lodash",
    "explanation": "DefinitelyTyped is the massive, community-driven GitHub repository that hosts `.d.ts` files for almost every popular JavaScript library. The `@types` scope is the official namespace for these packages."
  },
  {
    "id": 320,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "typesVersions",
    "question": "What does the `\"typesVersions\"` field in a library's `package.json` allow a library author to do?",
    "code_snippet": null,
    "options": ["It sets the minimum Node.js version", "It allows the library to serve different `.d.ts` declaration files based on the TypeScript version the consumer is using (e.g., providing newer TS features only to TS 4.7+ users)", "It tracks the download count of the types", "It converts the types to JavaScript"],
    "correct_answer": "It allows the library to serve different `.d.ts` declaration files based on the TypeScript version the consumer is using (e.g., providing newer TS features only to TS 4.7+ users)",
    "explanation": "This is an advanced feature for library authors. If you write a library that uses cutting-edge TS features, you can use `typesVersions` to provide a fallback `.d.ts` file for users on older TS versions, preventing compilation errors."
  },
  {
    "id": 321,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "tsx vs ts-node",
    "question": "Why has `tsx` largely replaced `ts-node` for running TypeScript scripts and servers in modern development?",
    "code_snippet": null,
    "options": ["It has a better logo", "It uses the highly optimized `esbuild` under the hood, making it significantly faster and more compatible with modern ESM/CJS interop than `ts-node`'s traditional compiler approach", "It automatically deploys to the cloud", "It converts TS to Python"],
    "correct_answer": "It uses the highly optimized `esbuild` under the hood, making it significantly faster and more compatible with modern ESM/CJS interop than `ts-node`'s traditional compiler approach",
    "explanation": "`ts-node` uses the full TypeScript compiler, which is slow and struggles with ESM. `tsx` uses `esbuild` to strip types instantly, making it the modern standard for running TS scripts, CLIs, and local dev servers."
  },
  {
    "id": 322,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Module Resolution: NodeNext",
    "question": "When using `\"moduleResolution\": \"NodeNext\"`, what strict rule does TypeScript enforce regarding relative imports?",
    "code_snippet": null,
    "options": ["It forbids relative imports entirely", "It requires you to include the explicit file extension (e.g., `import { x } from './file.js'`) to perfectly match the native Node.js ESM resolution algorithm", "It forces all imports to be absolute URLs", "It converts all imports to CommonJS"],
    "correct_answer": "It requires you to include the explicit file extension (e.g., `import { x } from './file.js'`) to perfectly match the native Node.js ESM resolution algorithm",
    "explanation": "Native Node.js ESM does not magically add `.js` to your imports like Webpack does. `NodeNext` forces you to write the exact file extension (even for `.ts` files, you write `.js`) so your TS code perfectly matches the runtime behavior."
  },
  {
    "id": 323,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Triple-slash lib reference",
    "question": "What does the `/// <reference lib=\"dom\" />` directive do?",
    "code_snippet": null,
    "options": ["It imports a CSS file", "It explicitly tells the TypeScript compiler to include the built-in DOM type definitions (like `Window`, `Document`, `HTMLElement`) in the current file's global scope", "It creates a new HTML file", "It links to a CDN"],
    "correct_answer": "It explicitly tells the TypeScript compiler to include the built-in DOM type definitions (like `Window`, `Document`, `HTMLElement`) in the current file's global scope",
    "explanation": "While `tsconfig.json` usually handles global libs, triple-slash directives are useful in standalone `.d.ts` files or specific scripts where you need to guarantee the DOM types are present without relying on the global config."
  },
  {
    "id": 324,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "The TS Compiler API",
    "question": "What is the primary entry point for programmatically analyzing or transforming TypeScript code using the TS Compiler API?",
    "code_snippet": null,
    "options": ["ts.transpile()", "ts.createProgram()", "ts.compile()", "ts.parse()"],
    "correct_answer": "ts.createProgram()",
    "explanation": "`ts.createProgram()` takes an array of file names and compiler options, and builds the entire Abstract Syntax Tree (AST) and type-checker in memory. It is the foundation for building custom linters, formatters, and code generators."
  },
  {
    "id": 325,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "AST (Abstract Syntax Tree)",
    "question": "In the context of the TypeScript Compiler API, what is an AST?",
    "code_snippet": null,
    "options": ["A CSS layout model", "A tree-like data structure that represents the syntactic structure of the source code, allowing tools to analyze, lint, or transform code programmatically", "A type of database", "A runtime error"],
    "correct_answer": "A tree-like data structure that represents the syntactic structure of the source code, allowing tools to analyze, lint, or transform code programmatically",
    "explanation": "When TS reads your code, it converts the text into an AST (e.g., a 'FunctionDeclaration' node containing 'Identifier' nodes). Tools like ESLint, Prettier, and custom transformers walk this tree to understand and modify your code."
  },
  {
    "id": 326,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "@ts-expect-error vs @ts-ignore",
    "question": "Why is `@ts-expect-error` considered vastly superior to `@ts-ignore`?",
    "code_snippet": null,
    "options": ["It runs faster", "`@ts-expect-error` suppresses the error on the next line, but if the next line DOESN'T have an error, `@ts-expect-error` will throw a new error, ensuring the suppression is removed once the underlying bug is fixed", "It automatically fixes the code", "It is shorter to type"],
    "correct_answer": "`@ts-expect-error` suppresses the error on the next line, but if the next line DOESN'T have an error, `@ts-expect-error` will throw a new error, ensuring the suppression is removed once the underlying bug is fixed",
    "explanation": "`@ts-ignore` is dangerous because if you refactor the code and the error goes away, the `@ts-ignore` stays there silently. `@ts-expect-error` acts as a self-cleaning suppression, alerting you when it's no longer needed."
  },
  {
    "id": 327,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "@ts-nocheck",
    "question": "What does the `// @ts-nocheck` comment do when placed at the very top of a TypeScript file?",
    "code_snippet": null,
    "options": ["It deletes the file", "It completely disables type-checking for the entire file, treating it as if it were a standard JavaScript file (useful for migrating legacy code)", "It minifies the file", "It converts the file to JSX"],
    "correct_answer": "It completely disables type-checking for the entire file, treating it as if it were a standard JavaScript file (useful for migrating legacy code)",
    "explanation": "When migrating a massive JavaScript codebase to TypeScript, you can rename files to `.ts` and slap `// @ts-nocheck` at the top. This lets you compile the project immediately, and you can gradually remove the comment and fix types file-by-file."
  },
  {
    "id": 328,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "JSDoc Typing in JS files",
    "question": "How can you add TypeScript type checking to a standard `.js` file without converting it to `.ts`?",
    "code_snippet": null,
    "options": ["You cannot", "By using JSDoc comments (e.g., `/** @type {string} */` or `/** @param {number} x */`) which the TypeScript compiler can parse and enforce", "By using XML tags", "By adding a `.ts` extension to the end of the filename"],
    "correct_answer": "By using JSDoc comments (e.g., `/** @type {string} */` or `/** @param {number} x */`) which the TypeScript compiler can parse and enforce",
    "explanation": "TypeScript has deep support for JSDoc. You can get 90% of TypeScript's safety in pure `.js` files by using standardized JSDoc annotations, which is perfect for teams not ready to adopt a full TS build pipeline."
  },
  {
    "id": 329,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "JSDoc @typedef",
    "question": "How do you define a custom interface or type alias inside a standard `.js` file using JSDoc?",
    "code_snippet": null,
    "options": ["interface MyType {}", "By using the `/** @typedef {Object} MyType */` and `/** @property {string} name */` tags", "type MyType = {}", "def MyType:"],
    "correct_answer": "By using the `/** @typedef {Object} MyType */` and `/** @property {string} name */` tags",
    "explanation": "JSDoc allows you to create complex, reusable type definitions purely through comments. The TypeScript compiler reads these `@typedef` blocks and enforces them exactly as if they were written in a `.ts` file."
  },
  {
    "id": 330,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (Philosophy of Tooling)",
    "question": "What is the ultimate philosophy of mastering TypeScript's tooling, compiler options, and declaration ecosystem?",
    "code_snippet": null,
    "options": ["To memorize every compiler flag", "Understanding that TypeScript is not just a language, but a highly configurable, programmable platform; mastering its tooling allows you to tailor the compiler to your team's exact architectural needs and guarantee safety across massive codebases", "To avoid using third-party libraries", "To compile everything to assembly code"],
    "correct_answer": "Understanding that TypeScript is not just a language, but a highly configurable, programmable platform; mastering its tooling allows you to tailor the compiler to your team's exact architectural needs and guarantee safety across massive codebases",
    "explanation": "TypeScript's true power isn't just in its syntax; it's in its ecosystem. By mastering `tsconfig`, declaration files, and the compiler API, you transition from a 'user' of TypeScript to an 'architect' of your entire development environment."
  }
]
[
  {
    "id": 331,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Module Resolution: Bundler",
    "question": "What is the primary advantage of setting `\"moduleResolution\": \"Bundler\"` in your `tsconfig.json` when using tools like Vite, Webpack, or esbuild?",
    "code_snippet": null,
    "options": ["It compiles the code faster", "It allows extensionless imports, trailing commas in JSON, and respects the `exports` field in `package.json`, perfectly mimicking modern JS bundlers", "It automatically converts TS to JS", "It disables type checking"],
    "correct_answer": "It allows extensionless imports, trailing commas in JSON, and respects the `exports` field in `package.json`, perfectly mimicking modern JS bundlers",
    "explanation": "Historically, TS forced you to use Node's strict resolution rules (requiring `.js` extensions). `Bundler` mode bridges the gap, allowing TS to understand the relaxed, modern import rules that tools like Vite and Webpack actually use at runtime."
  },
  {
    "id": 332,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "skipLibCheck",
    "question": "What does the `\"skipLibCheck\": true` compiler flag do, and why is it highly recommended for large projects?",
    "code_snippet": null,
    "options": ["It skips checking your source code", "It skips type-checking all `.d.ts` declaration files, drastically speeding up compilation and preventing conflicts between mismatched third-party library types", "It skips checking CSS files", "It skips checking JSON files"],
    "correct_answer": "It skips type-checking all `.d.ts` declaration files, drastically speeding up compilation and preventing conflicts between mismatched third-party library types",
    "explanation": "If two different libraries depend on slightly different versions of `@types/react`, TS will normally throw a massive conflict error. `skipLibCheck` tells TS to trust the published `.d.ts` files and only type-check YOUR code, saving minutes of build time."
  },
  {
    "id": 333,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "verbatimModuleSyntax",
    "question": "What does the modern `\"verbatimModuleSyntax\": true` flag (introduced in TS 5.0) enforce?",
    "code_snippet": null,
    "options": ["It prevents the use of the `any` type", "It requires you to explicitly use `import type` and `export type` for anything that isn't a runtime value, ensuring tools like Babel/esbuild can safely strip types without breaking the code", "It forces all imports to be CommonJS", "It verifies that all modules have a license"],
    "correct_answer": "It requires you to explicitly use `import type` and `export type` for anything that isn't a runtime value, ensuring tools like Babel/esbuild can safely strip types without breaking the code",
    "explanation": "This flag replaces the older `importsNotUsedAsValues` and `preserveValueImports`. It guarantees that the TypeScript code you write looks exactly like the JavaScript code that will run, making single-file transpilation 100% safe."
  },
  {
    "id": 334,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "resolveJsonModule",
    "question": "What does the `\"resolveJsonModule\": true` flag allow you to do?",
    "code_snippet": null,
    "options": ["Parse JSON at runtime", "Import `.json` files directly into your TypeScript code with full, automatic type inference based on the JSON structure", "Convert TS objects to JSON", "Validate JSON schemas"],
    "correct_answer": "Import `.json` files directly into your TypeScript code with full, automatic type inference based on the JSON structure",
    "explanation": "With this flag enabled, you can write `import config from './config.json'`, and TypeScript will automatically infer the exact types of `config` based on the keys and values in the JSON file."
  },
  {
    "id": 335,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "code-fill-in-blank",
    "topic": "CSS Module Typing",
    "question": "Fill in the blank with the standard global declaration to allow TypeScript to import `.module.css` files without throwing an error.",
    "code_snippet": "declare module '*._______' {\n  const classes: { readonly [key: string]: string };\n  export default classes;\n}",
    "options": ["css", "scss", "module.css", "style"],
    "correct_answer": "module.css",
    "explanation": "TypeScript doesn't understand CSS out of the box. By adding this ambient module declaration to a global `.d.ts` file, you tell TS that any import ending in `.module.css` resolves to an object of strings, enabling perfect autocomplete for CSS class names."
  },
  {
    "id": 336,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "The TS Server API (tsserver)",
    "question": "What is `tsserver` and what role does it play in the TypeScript ecosystem?",
    "code_snippet": null,
    "options": ["It is the runtime engine for TS", "It is the background language server that powers IDE features like autocomplete, 'Go to Definition', refactoring, and real-time error squiggles in VS Code", "It is a testing framework", "It is a CSS preprocessor"],
    "correct_answer": "It is the background language server that powers IDE features like autocomplete, 'Go to Definition', refactoring, and real-time error squiggles in VS Code",
    "explanation": "When you type in VS Code, you aren't talking to the `tsc` compiler; you are talking to `tsserver`. It keeps your project's AST in memory and responds to IDE requests in milliseconds, providing the 'magic' TypeScript developer experience."
  },
  {
    "id": 337,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "TS Server Plugins",
    "question": "How do tools like `typescript-eslint` or `ts-plugin` integrate with the TypeScript language server?",
    "code_snippet": null,
    "options": ["They replace the TS compiler", "They hook into `tsserver` via the `plugins` array in `tsconfig.json`, allowing them to inject custom linting rules, virtual files, or framework-specific intelligence directly into the IDE", "They run as a separate web server", "They modify the JavaScript output"],
    "correct_answer": "They hook into `tsserver` via the `plugins` array in `tsconfig.json`, allowing them to inject custom linting rules, virtual files, or framework-specific intelligence directly into the IDE",
    "explanation": "This is how frameworks like Vue, Svelte, or Angular provide rich TypeScript support in VS Code. They register a plugin with `tsserver` that intercepts file reads and provides custom type-checking logic for `.vue` or `.svelte` files."
  },
  {
    "id": 338,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "noImplicitOverride",
    "question": "What does the `\"noImplicitOverride\": true` flag enforce in classes?",
    "code_snippet": null,
    "options": ["It prevents classes from being extended", "It forces you to use the `override` keyword when a subclass method overrides a base class method, preventing accidental shadowing if the base class method is renamed", "It makes all methods static", "It prevents the use of `super()`"],
    "correct_answer": "It forces you to use the `override` keyword when a subclass method overrides a base class method, preventing accidental shadowing if the base class method is renamed",
    "explanation": "If you have a `save()` method in a base class, and you write a `save()` method in a child class, TS won't warn you if the base class later renames it to `saveToDb()`. The `override` keyword guarantees the method actually exists in the parent."
  },
  {
    "id": 339,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "strictBindCallApply",
    "question": "What does the `\"strictBindCallApply\": true` flag do?",
    "code_snippet": null,
    "options": ["It prevents the use of `.bind()`, `.call()`, and `.apply()`", "It ensures that the arguments passed to `.bind()`, `.call()`, and `.apply()` are strictly type-checked against the original function's signature", "It converts them to arrow functions", "It forces them to return `void`"],
    "correct_answer": "It ensures that the arguments passed to `.bind()`, `.call()`, and `.apply()` are strictly type-checked against the original function's signature",
    "explanation": "Without this flag, you could call `myFunc.call(null, 'wrong', 'types')` and TS wouldn't care. With it enabled, TS checks the `this` context and the exact parameter types, catching subtle bugs in functional programming patterns."
  },
  {
    "id": 340,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Custom Transformers (ts-patch)",
    "question": "Because the standard `tsc` compiler doesn't support custom AST transformers out of the box, what tool is commonly used to enable them?",
    "code_snippet": null,
    "options": ["ts-node", "ts-patch or ttypescript", "Webpack", "Babel"],
    "correct_answer": "ts-patch or ttypescript",
    "explanation": "Tools like `ts-patch` patch the TypeScript compiler to allow custom transformers (functions that modify the AST during compilation). This is heavily used for things like auto-generating GraphQL types, stripping `console.log` statements, or implementing custom decorators."
  },
  {
    "id": 341,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "GlobalThis Augmentation",
    "question": "What is the modern, standard way to add a custom property to the global scope in TypeScript?",
    "code_snippet": null,
    "options": ["interface Window { ... }", "declare global { var myProp: string; }", "declare module 'global' { ... }", "export global myProp: string;", "declare global { interface typeof globalThis { myProp: string; } }"],
    "correct_answer": "declare global { var myProp: string; }",
    "explanation": "While `interface Window` works for browser environments, `declare global { var ... }` or augmenting `typeof globalThis` is the universal, environment-agnostic way to add global variables that work in Node.js, Deno, and the Browser."
  },
  {
    "id": 342,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "DefinitelyTyped Structure",
    "question": "If you are contributing to DefinitelyTyped to add types for a library called `my-lib`, what is the mandatory file structure you must follow?",
    "code_snippet": null,
    "options": ["A single `my-lib.ts` file", "A folder named `types/my-lib` containing an `index.d.ts` file, a `package.json` with `types` pointing to it, and tests", "A `my-lib.d.ts` file in the root directory", "A JSON schema file"],
    "correct_answer": "A folder named `types/my-lib` containing an `index.d.ts` file, a `package.json` with `types` pointing to it, and tests",
    "explanation": "DefinitelyTyped has strict structural requirements. Every library must have its own folder, an entry point (`index.d.ts`), metadata (`package.json`), and a `my-lib-tests.ts` file that proves the types work correctly."
  },
  {
    "id": 343,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Package.json 'exports' field",
    "question": "How does TypeScript interact with the `"exports"` field in a library's `package.json` when using modern module resolution?",
    "code_snippet": null,
    "options": ["It ignores it completely", "It strictly enforces the subpath exports, meaning consumers can ONLY import the exact paths the library author explicitly exposed, hiding internal files", "It automatically converts it to CommonJS", "It deletes the internal files"],
    "correct_answer": "It strictly enforces the subpath exports, meaning consumers can ONLY import the exact paths the library author explicitly exposed, hiding internal files",
    "explanation": "The `"exports"` field is the modern replacement for `"main"`. If a library uses it, TS will block you from importing `my-lib/internal/utils` unless the author explicitly added it to the `"exports"` map, enforcing strict API boundaries."
  },
  {
    "id": 344,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Monorepo Tooling (Project References)",
    "question": "When using TypeScript Project References in a monorepo, what command do you run to build the entire dependency graph in the correct order?",
    "code_snippet": null,
    "options": ["tsc --build (or tsc -b)", "tsc --watch", "tsc --init", "npm run build"],
    "correct_answer": "tsc --build (or tsc -b)",
    "explanation": "`tsc --build` reads the `references` array in your `tsconfig.json`, figures out the dependency graph, and compiles the packages in the exact order required, caching the results for lightning-fast incremental builds."
  },
  {
    "id": 345,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Type-Only Export Erasure",
    "question": "If you have `export { User } from './models'` and `User` is ONLY an interface, what happens when compiled with `verbatimModuleSyntax: true`?",
    "code_snippet": null,
    "options": ["It compiles normally", "It throws a compile-time error, forcing you to change it to `export type { User }` to ensure the bundler safely erases it", "It converts it to a runtime object", "It throws a runtime error"],
    "correct_answer": "It throws a compile-time error, forcing you to change it to `export type { User }` to ensure the bundler safely erases it",
    "explanation": "Because `verbatimModuleSyntax` requires absolute clarity on what is a value and what is a type, it will flag this export. You must explicitly write `export type { User }` so fast transpilers like esbuild know to delete it entirely."
  },
  {
    "id": 346,
    "level": "intermediate",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "ESM vs CJS Interop",
    "question": "What does the `\"esModuleInterop\": true` flag allow you to do when importing legacy CommonJS modules?",
    "code_snippet": null,
    "options": ["It converts CommonJS to ESM at runtime", "It allows you to use standard default import syntax (e.g., `import React from 'react'`) for CommonJS modules that use `module.exports = ...`", "It prevents the use of `require()`", "It disables type checking for CJS"],
    "correct_answer": "It allows you to use standard default import syntax (e.g., `import React from 'react'`) for CommonJS modules that use `module.exports = ...`",
    "explanation": "Without this flag, importing a CJS module requires the clunky `import * as React from 'react'` syntax. `esModuleInterop` injects a tiny helper function that creates a synthetic default export, making ESM and CJS play nicely together."
  },
  {
    "id": 347,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "The 'types' vs 'typeRoots' config",
    "question": "What is the difference between the `\"types\"` and `\"typeRoots\"` options in `tsconfig.json`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`typeRoots` specifies the directories to search for `@types` packages (defaulting to `node_modules/@types`); `types` specifies exactly WHICH packages from those roots to include globally", "`types` is for CSS, `typeRoots` is for JS", "`typeRoots` is deprecated"],
    "correct_answer": "`typeRoots` specifies the directories to search for `@types` packages (defaulting to `node_modules/@types`); `types` specifies exactly WHICH packages from those roots to include globally",
    "explanation": "By default, TS includes EVERY `@types` package it finds in `node_modules`. If you want to restrict global types to ONLY `@types/node` and ignore `@types/jest` globally, you use the `\"types\": [\"node\"]` array."
  },
  {
    "id": 348,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Typing Environment Variables",
    "question": "How do you provide strict typing for `process.env.MY_API_KEY` in a Node.js TypeScript project?",
    "code_snippet": null,
    "options": ["You cannot type environment variables", "By augmenting the `NodeJS.ProcessEnv` interface via `declare global { namespace NodeJS { interface ProcessEnv { MY_API_KEY: string; } } }`", "By using `@ts-ignore`", "By casting it as `any`"],
    "correct_answer": "By augmenting the `NodeJS.ProcessEnv` interface via `declare global { namespace NodeJS { interface ProcessEnv { MY_API_KEY: string; } } }`",
    "explanation": "By using declaration merging on the global `NodeJS.ProcessEnv` interface, you tell TypeScript exactly which environment variables are expected to exist, turning `process.env.MY_API_KEY` from `string | undefined` into a strictly typed `string`."
  },
  {
    "id": 349,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "The TS Build Info File (.tsbuildinfo)",
    "question": "What is the purpose of the `.tsbuildinfo` file generated when using `tsc --build` or `composite: true`?",
    "code_snippet": null,
    "options": ["It stores the compiled JavaScript", "It acts as a highly optimized cache graph, allowing the compiler to instantly know which files changed and which can be skipped during incremental builds", "It stores environment variables", "It is a log file for errors"],
    "correct_answer": "It acts as a highly optimized cache graph, allowing the compiler to instantly know which files changed and which can be skipped during incremental builds",
    "explanation": "Without `.tsbuildinfo`, TS has to re-parse and re-check the entire project every time. With it, TS reads the graph, sees that only `fileA.ts` changed, and only re-checks `fileA.ts` and its direct dependents, reducing build times from minutes to milliseconds."
  },
  {
    "id": 350,
    "level": "advanced",
    "module_id": "ts_mod_05_modules_tooling",
    "module_name": "Modules, Namespaces, Declaration Files & Tooling",
    "type": "conceptual",
    "topic": "Module 5 Wrap-up (The Zen of Tooling)",
    "question": "You have now completed the deep dive into TypeScript Modules, Declarations, and Tooling. What is the ultimate hallmark of a developer who has mastered this ecosystem?",
    "code_snippet": null,
    "options": ["They never use third-party libraries", "They can architect a massive, multi-package monorepo with perfect type safety, zero circular dependencies, lightning-fast incremental builds, and seamless IDE integration across any framework", "They write all their own `.d.ts` files from scratch", "They disable strict mode to make builds faster"],
    "correct_answer": "They can architect a massive, multi-package monorepo with perfect type safety, zero circular dependencies, lightning-fast incremental builds, and seamless IDE integration across any framework",
    "explanation": "Mastering the TS ecosystem means you stop viewing TypeScript as just a 'syntax layer' and start viewing it as the central nervous system of your entire development environment. You control the compiler, the IDE, and the build pipeline to create an unbreakable developer experience."
  }
]
