[
  {
    "id": 351,
    "level": "beginner",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing Functional Components",
    "question": "What is the modern, recommended way to type the props of a standard React functional component?",
    "code_snippet": null,
    "options": ["Using the `React.FC<Props>` generic type", "Defining an interface/type for the props and annotating the function's argument directly (e.g., `function MyComponent({ name }: Props)`)", "Using the `PropTypes` library", "You cannot type functional components in TS"],
    "correct_answer": "Defining an interface/type for the props and annotating the function's argument directly (e.g., `function MyComponent({ name }: Props)`)",
    "explanation": "While `React.FC` was popular in the past, the React team and TS community now recommend standard function annotations. It provides better type inference for generics, doesn't implicitly add `children`, and correctly types the return value."
  },
  {
    "id": 352,
    "level": "beginner",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Typing Children",
    "question": "Fill in the blank to correctly type a prop that accepts any renderable React content (strings, numbers, elements, or fragments).",
    "code_snippet": "import { _______ } from 'react';\n\ninterface ModalProps {\n  children: _______;\n}",
    "options": ["ReactNode", "JSX.Element", "ReactElement", "Component"],
    "correct_answer": "ReactNode",
    "explanation": "`ReactNode` is the broadest and most correct type for the `children` prop. It includes everything that can be rendered: strings, numbers, booleans, null, undefined, and React elements."
  },
  {
    "id": 353,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React.FC Drawbacks",
    "question": "Why is the `React.FC` (FunctionComponent) type generally discouraged in modern TypeScript React development?",
    "code_snippet": null,
    "options": ["It is deprecated and throws errors", "It implicitly adds `children` to your props (even if you don't want them) and prevents the component from returning `null` or strings in older TS versions", "It makes the bundle size larger", "It disables React Hooks"],
    "correct_answer": "It implicitly adds `children` to your props (even if you don't want them) and prevents the component from returning `null` or strings in older TS versions",
    "explanation": "Because `React.FC` includes `children?: ReactNode` by default, you lose the ability to strictly enforce that a component takes NO children. Standard function annotations give you exact control over your props."
  },
  {
    "id": 354,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "useState Typing",
    "question": "Fill in the blank to correctly type a `useState` hook that holds either a `User` object or `null`.",
    "code_snippet": "const [user, setUser] = useState<_______>(null);",
    "options": ["User", "User | null", "User | undefined", "any"],
    "correct_answer": "User | null",
    "explanation": "When initializing `useState` with `null` or an empty array, TypeScript cannot infer the full type. You must explicitly provide the generic type argument (`User | null`) so TS knows what `user` will eventually hold."
  },
  {
    "id": 355,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "useEffect Return Type",
    "question": "What is the only valid return type for the callback function passed to `useEffect`?",
    "code_snippet": null,
    "options": ["Any data type", "`void` or a cleanup function `() => void`", "`Promise<void>`", "`ReactNode`"],
    "correct_answer": "`void` or a cleanup function `() => void`",
    "explanation": "TypeScript strictly enforces that `useEffect` callbacks cannot be `async` (they must return `void`). If you need to fetch data, you must define an async function INSIDE the effect and call it immediately."
  },
  {
    "id": 356,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Event Handlers (Mouse)",
    "question": "Fill in the blank to correctly type an `onClick` event handler for a standard HTML button.",
    "code_snippet": "const handleClick = (event: React._______<HTMLButtonElement>) => {\n  console.log(event.currentTarget.disabled);\n};",
    "options": ["MouseEvent", "ClickEvent", "PointerEvent", "Event"],
    "correct_answer": "MouseEvent",
    "explanation": "React provides specific synthetic event types under the `React` namespace. For a button click, `React.MouseEvent<HTMLButtonElement>` gives you perfect autocomplete for button-specific properties like `.disabled` or `.form`."
  },
  {
    "id": 357,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Event Handlers (Input)",
    "question": "Fill in the blank to correctly type an `onChange` event handler for a text input.",
    "code_snippet": "const handleChange = (event: React._______<HTMLInputElement>) => {\n  setvalue(event.target.value);\n};",
    "options": ["ChangeEvent", "InputEvent", "FormEvent", "KeyboardEvent"],
    "correct_answer": "ChangeEvent",
    "explanation": "`React.ChangeEvent<HTMLInputElement>` is the exact type for input changes. It provides strict typing for `event.target.value`, ensuring you are reading a string from an input element."
  },
  {
    "id": 358,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "useRef (DOM Elements)",
    "question": "Fill in the blank to correctly type a `useRef` that will be attached to an `<input>` DOM element.",
    "code_snippet": "const inputRef = useRef<_______>(null);",
    "options": ["HTMLInputElement", "InputElement", "HTMLInput", "Input"],
    "correct_answer": "HTMLInputElement",
    "explanation": "When using `useRef` for DOM nodes, you must pass the specific HTML interface (like `HTMLInputElement`, `HTMLDivElement`, etc.) and initialize it with `null`."
  },
  {
    "id": 359,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "useRef (Mutable Values)",
    "question": "If you want to use `useRef` to store a mutable value (like a timer ID or a previous state) that does NOT trigger a re-render, how should you type it?",
    "code_snippet": null,
    "options": ["useRef<number>(0)", "useRef<number | null>(null)", "useRef<number>(null)", "useRef<number>(undefined)"],
    "correct_answer": "useRef<number>(0)",
    "explanation": "Unlike DOM refs which start as `null`, mutable value refs should be initialized with their actual starting value (e.g., `0` for a number). This tells TypeScript that `.current` will ALWAYS be a number, preventing annoying `null` checks."
  },
  {
    "id": 360,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Context Typing",
    "question": "What is a major TypeScript pain point when using `React.createContext()` with a complex object, and how is it usually solved?",
    "code_snippet": null,
    "options": ["Context cannot be typed", "TS forces you to provide a default value, which might be fake data; the solution is to create a custom `useMyContext` hook that throws an error if the context is `undefined`", "Context only accepts strings", "Context automatically infers types from the Provider"],
    "correct_answer": "TS forces you to provide a default value, which might be fake data; the solution is to create a custom `useMyContext` hook that throws an error if the context is `undefined`",
    "explanation": "By creating a context with `createContext<MyType | undefined>(undefined)` and wrapping `useContext` in a custom hook that asserts the value is not undefined, you guarantee type safety without needing fake default data."
  },
  {
    "id": 361,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "forwardRef",
    "question": "Fill in the blank to correctly type a component that forwards a ref to an underlying `<input>` element.",
    "code_snippet": "const CustomInput = _______<HTMLInputElement, InputProps>((props, ref) => {\n  return <input ref={ref} {...props} />;\n});",
    "options": ["forwardRef", "createRef", "useRef", "memo"],
    "correct_answer": "forwardRef",
    "explanation": "`forwardRef` takes two generic type arguments: the type of the DOM element the ref points to (`HTMLInputElement`), and the type of the component's props (`InputProps`)."
  },
  {
    "id": 362,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Generic Components",
    "question": "How do you create a generic React component, like a `<List<T>>` that renders an array of any type?",
    "code_snippet": null,
    "options": ["You cannot make generic components in React", "By defining the component as a function with a generic type parameter (e.g., `function List<T>({ items }: { items: T[] })`)", "By using the `any` type for the items", "By using `React.GenericComponent`"],
    "correct_answer": "By defining the component as a function with a generic type parameter (e.g., `function List<T>({ items }: { items: T[] })`)",
    "explanation": "Standard function declarations support generics perfectly. When you use `<List items={users} />`, TypeScript infers `T` as `User`, giving you perfect autocomplete inside the render prop or children."
  },
  {
    "id": 363,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "ComponentProps Utility",
    "question": "What does the `React.ComponentProps<typeof MyComponent>` utility type do?",
    "code_snippet": null,
    "options": ["It renders the component", "It extracts the exact props interface of an existing component or HTML element, allowing you to extend or wrap it without rewriting the types", "It converts props to state", "It removes the `children` prop"],
    "correct_answer": "It extracts the exact props interface of an existing component or HTML element, allowing you to extend or wrap it without rewriting the types",
    "explanation": "If you are building a custom `<Button>` that wraps a native `<button>`, you can use `ComponentProps<'button'>` to automatically inherit all native button props (like `type`, `disabled`, `onClick`) without typing them manually."
  },
  {
    "id": 364,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Form Events",
    "question": "Fill in the blank to correctly type an `onSubmit` event handler for a `<form>` element.",
    "code_snippet": "const handleSubmit = (event: React._______<HTMLFormElement>) => {\n  event.preventDefault();\n};",
    "options": ["FormEvent", "SubmitEvent", "ChangeEvent", "MouseEvent"],
    "correct_answer": "FormEvent",
    "explanation": "`React.FormEvent<HTMLFormElement>` is the correct synthetic event type for form submissions. It gives you access to `.preventDefault()` and form-specific properties."
  },
  {
    "id": 365,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "ReactNode vs JSX.Element",
    "question": "What is the difference between `ReactNode` and `JSX.Element`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`JSX.Element` represents ONLY a React element (the result of calling `React.createElement`), while `ReactNode` is a broader type that includes elements, strings, numbers, arrays, and null", "`ReactNode` is for classes, `JSX.Element` is for functions", "`JSX.Element` is deprecated"],
    "correct_answer": "`JSX.Element` represents ONLY a React element (the result of calling `React.createElement`), while `ReactNode` is a broader type that includes elements, strings, numbers, arrays, and null",
    "explanation": "If a function returns a string or `null`, it is a valid `ReactNode`, but it is NOT a `JSX.Element`. Always use `ReactNode` for props and return types unless you strictly need to enforce that a component returns a JSX tag."
  },
  {
    "id": 366,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Typing Custom Hooks",
    "question": "Fill in the blank to correctly type a custom hook that returns a tuple of a string and a function.",
    "code_snippet": "function useLocalStorage(key: string): [string, (val: string) => void] {\n  // ...\n}",
    "code_snippet_options": [],
    "options": ["You don't need to type it, TS infers it perfectly", "You must explicitly type the return tuple", "You must use `React.Hook`", "You must use `any`"],
    "correct_answer": "You don't need to type it, TS infers it perfectly",
    "explanation": "TypeScript's inference engine is incredibly smart with hooks. If you return `[state, setState]`, TS automatically infers the exact tuple type. Explicit return typing is only needed for complex, generic, or highly public API hooks."
  },
  {
    "id": 367,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Optional Props & Default Values",
    "question": "If you define a prop as optional (`name?: string`) and provide a default value in the function signature (`{ name = 'Guest' }`), what is the type of `name` INSIDE the component body?",
    "code_snippet": null,
    "options": ["string | undefined", "string", "string | null", "any"],
    "correct_answer": "string",
    "explanation": "Because the default value guarantees that `name` will never be `undefined` inside the function body, TypeScript smartly narrows the type from `string | undefined` to just `string`. You don't need to do any null checks!"
  },
  {
    "id": 368,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing React.memo",
    "question": "When wrapping a generic component in `React.memo`, what is a known TypeScript limitation?",
    "code_snippet": null,
    "options": ["`React.memo` cannot be used with TypeScript", "`React.memo` often strips or breaks the generic type parameters, requiring workarounds like casting or using a custom `memo` wrapper", "`React.memo` forces all props to be optional", "`React.memo` only works on class components"],
    "correct_answer": "`React.memo` often strips or breaks the generic type parameters, requiring workarounds like casting or using a custom `memo` wrapper",
    "explanation": "The built-in `React.memo` type definition doesn't perfectly preserve generic type parameters (`<T>`). Developers often have to use type assertions (`as <T>(...)`) or write a custom generic memo function to retain full type safety."
  },
  {
    "id": 369,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Keyboard Events",
    "question": "Fill in the blank to correctly type an `onKeyDown` event handler.",
    "code_snippet": "const handleKeyDown = (event: React._______<HTMLInputElement>) => {\n  if (event.key === 'Enter') { ... }\n};",
    "options": ["KeyboardEvent", "KeyEvent", "KeyPressEvent", "InputEvent"],
    "correct_answer": "KeyboardEvent",
    "explanation": "`React.KeyboardEvent<HTMLInputElement>` provides strict typing for keyboard interactions, including `.key`, `.code`, `.ctrlKey`, and `.altKey`."
  },
  {
    "id": 370,
    "level": "beginner",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "What is the core benefit of strictly typing React components, hooks, and events?",
    "code_snippet": null,
    "options": ["It makes the React runtime faster", "It transforms the React development experience from a game of 'guessing what props an element takes' into a fully guided, autocomplete-driven, and error-free workflow", "It automatically writes unit tests", "It removes the need for React DevTools"],
    "correct_answer": "It transforms the React development experience from a game of 'guessing what props an element takes' into a fully guided, autocomplete-driven, and error-free workflow",
    "explanation": "React's API surface is massive. TypeScript acts as an interactive documentation layer, instantly telling you exactly what props a component accepts, what events are available, and what type a hook returns, drastically reducing cognitive load."
  }
]
[
  {
    "id": 371,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Polymorphic Components (Concept)",
    "question": "What is a 'Polymorphic Component' in React?",
    "code_snippet": null,
    "options": ["A component that changes its internal state based on props", "A component that can render as different HTML elements or components via an `as` prop while maintaining correct prop types for the chosen element", "A component that uses CSS-in-JS", "A component that renders its children conditionally"],
    "correct_answer": "A component that can render as different HTML elements or components via an `as` prop while maintaining correct prop types for the chosen element",
    "explanation": "Polymorphic components (like those in Radix UI or Chakra) allow you to write `<Button as=\"a\" href=\"/home\" />`. TypeScript must be advanced enough to know that because `as=\"a\"`, the `href` prop is now valid, but `type=\"submit\"` is not."
  },
  {
    "id": 372,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Polymorphic Components (Typing Challenge)",
    "question": "What is the primary TypeScript challenge when building a Polymorphic component with an `as` prop?",
    "code_snippet": null,
    "options": ["It is impossible to type in TypeScript", "Ensuring that the props passed to the component dynamically match the specific HTML element or component passed to the `as` prop (e.g., passing `href` only when `as=\"a\"`)", "It makes the bundle size too large", "It breaks React DevTools"],
    "correct_answer": "Ensuring that the props passed to the component dynamically match the specific HTML element or component passed to the `as` prop (e.g., passing `href` only when `as=\"a\"`)",
    "explanation": "You have to use advanced generic constraints and conditional types (often combining `React.ComponentPropsWithRef<ElementType>`) to intersect your custom props with the native props of the dynamically chosen element."
  },
  {
    "id": 373,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Extracting Props with Refs",
    "question": "Fill in the blank to correctly extract the props of a native HTML element, INCLUDING its `ref` prop.",
    "code_snippet": "type ButtonProps = React._______<'button'>;",
    "options": ["ComponentProps", "ComponentPropsWithRef", "ComponentPropsWithoutRef", "PropsWithRef"],
    "correct_answer": "ComponentPropsWithRef",
    "explanation": "`ComponentPropsWithRef` is essential when building wrapper components that need to forward a ref to the underlying native element. `ComponentPropsWithoutRef` strips the `ref` prop out."
  },
  {
    "id": 374,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Typing Render Props",
    "question": "Fill in the blank to correctly type a 'Render Prop' function that receives a `user` object and returns a ReactNode.",
    "code_snippet": "interface ListProps {\n  items: User[];\n  renderItem: (user: User) => _______;\n}",
    "options": ["JSX.Element", "ReactNode", "ReactElement", "Component"],
    "correct_answer": "ReactNode",
    "explanation": "Always use `ReactNode` for render props. It allows the consumer to return strings, numbers, fragments, arrays, or actual JSX elements, giving them maximum flexibility."
  },
  {
    "id": 375,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generic Custom Hooks",
    "question": "Fill in the blank to correctly type a generic custom hook `useFetch<T>` that takes a URL and returns data of type `T`.",
    "code_snippet": "function useFetch<_______>(url: string): { data: T | null, loading: boolean } {\n  // ...\n}",
    "options": ["T", "any", "unknown", "Data"],
    "correct_answer": "T",
    "explanation": "By making the hook generic, the caller can specify the exact shape of the API response: `const { data } = useFetch<User>('/api/user')`. TypeScript will then strictly type `data` as `User | null`."
  },
  {
    "id": 376,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing Higher-Order Components (HOCs)",
    "question": "What is the standard generic signature for a Higher-Order Component (HOC) that wraps a component and injects a `user` prop?",
    "code_snippet": null,
    "options": ["function withAuth<P extends { user: User }>(Component: React.ComponentType<P>): React.ComponentType<Omit<P, 'user'>>", "function withAuth<P>(Component: React.FC<P>): React.FC<P>", "function withAuth(Component: any): React.FC", "function withAuth<P>(Component: React.ComponentType<P>): React.ComponentType<P & { user: User }>"],
    "correct_answer": "function withAuth<P extends { user: User }>(Component: React.ComponentType<P>): React.ComponentType<Omit<P, 'user'>>",
    "explanation": "The wrapped component expects the `user` prop (`P extends { user: User }`), but the HOC *injects* it. Therefore, the returned component type must use `Omit<P, 'user'>` so the parent component doesn't have to pass it manually."
  },
  {
    "id": 377,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React 19 `use` Hook",
    "question": "What is the primary purpose of the new React 19 `use` hook?",
    "code_snippet": null,
    "options": ["To replace `useState`", "To read a resource like a Promise or Context during render, allowing for Suspense integration without needing `useEffect` or `useContext`", "To fetch data on the server", "To animate components"],
    "correct_answer": "To read a resource like a Promise or Context during render, allowing for Suspense integration without needing `useEffect` or `useContext`",
    "explanation": "The `use` hook is a game-changer. It allows you to pass a Promise directly into a component, and React will suspend rendering until the Promise resolves, completely eliminating the need for manual loading states."
  },
  {
    "id": 378,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "output-prediction",
    "topic": "`use` Hook Return Type",
    "question": "If you pass a `Promise<User>` to the `use` hook, what is the inferred return type of the hook?",
    "code_snippet": "const user = use(fetchUserPromise);",
    "options": ["Promise<User>", "User", "User | null", "Awaited<Promise<User>>"],
    "correct_answer": "User",
    "explanation": "Because `use` unwraps the Promise synchronously during the render phase (via Suspense), the return type is the resolved value itself (`User`), not the Promise."
  },
  {
    "id": 379,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useContext`",
    "question": "How does TypeScript infer the return type of `useContext(MyContext)`?",
    "code_snippet": null,
    "options": ["It always returns `any`", "It infers it directly from the generic type provided to `React.createContext<T>()`", "It requires an explicit type annotation on the `useContext` call", "It returns `ReactNode`"],
    "correct_answer": "It infers it directly from the generic type provided to `React.createContext<T>()`",
    "explanation": "This is why it's crucial to properly type your context creation: `const ThemeContext = createContext<Theme>(defaultTheme)`. `useContext(ThemeContext)` will automatically know it returns a `Theme` object."
  },
  {
    "id": 380,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Forwarding Refs with Generic Components",
    "question": "What is a known TypeScript limitation when combining `forwardRef` with Generic components?",
    "code_snippet": null,
    "options": ["It is fully supported without any issues", "TypeScript struggles to infer the generic type `T` when using `forwardRef`, often requiring a type assertion or a custom wrapper function to preserve the generic signature", "It automatically converts the component to a class", "It disables the ref"],
    "correct_answer": "TypeScript struggles to infer the generic type `T` when using `forwardRef`, often requiring a type assertion or a custom wrapper function to preserve the generic signature",
    "explanation": "The built-in `forwardRef` type definition doesn't perfectly preserve generic type parameters (`<T>`). Developers often have to use type assertions (`as <T>(...)`) or write a custom generic memo/forwardRef function to retain full type safety."
  },
  {
    "id": 381,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useReducer` Actions",
    "question": "When typing a `useReducer` hook, what is the best practice for defining the `action` parameter in the reducer function?",
    "code_snippet": null,
    "options": ["action: any", "action: { type: string }", "A Discriminated Union of action objects (e.g., `{ type: 'INCREMENT' } | { type: 'DECREMENT', payload: number }`)", "action: React.Action"],
    "correct_answer": "A Discriminated Union of action objects (e.g., `{ type: 'INCREMENT' } | { type: 'DECREMENT', payload: number }`)",
    "explanation": "Discriminated unions allow TypeScript to perfectly narrow the `action` type inside each `switch` case. If the action is `INCREMENT`, TS knows `payload` doesn't exist. If it's `DECREMENT`, TS knows `payload` is a number."
  },
  {
    "id": 382,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useReducer` State",
    "question": "If you provide an initial state to `useReducer(reducer, initialState)`, does TypeScript require you to explicitly type the state?",
    "code_snippet": null,
    "options": ["Yes, always", "No, TypeScript usually infers the state type perfectly from the `initialState` argument and the reducer's return type", "Yes, but only for objects", "No, it defaults to `any`"],
    "correct_answer": "No, TypeScript usually infers the state type perfectly from the `initialState` argument and the reducer's return type",
    "explanation": "Just like `useState`, if you pass a fully formed initial object, TS infers the shape. You only need to explicitly type it if the initial state is empty (e.g., `null` or `[]`) or if you want to enforce optional properties."
  },
  {
    "id": 383,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useImperativeHandle`",
    "question": "What does the `useImperativeHandle` hook allow you to do in TypeScript?",
    "code_snippet": null,
    "options": ["Type the DOM element", "Customize the instance value that is exposed to parent components when they use a `ref` on your component", "Type the component's props", "Type the context value"],
    "correct_answer": "Customize the instance value that is exposed to parent components when they use a `ref` on your component",
    "explanation": "Instead of exposing the entire DOM node, `useImperativeHandle` lets you expose a specific, typed interface (like `{ focus: () => void, reset: () => void }`) to the parent, encapsulating your component's internals."
  },
  {
    "id": 384,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Imperative Handle Interface",
    "question": "Fill in the blank to correctly type the interface that defines the methods exposed via `useImperativeHandle`.",
    "code_snippet": "export interface InputHandle {\n  focus: () => void;\n}\n\nconst CustomInput = forwardRef<_______, InputProps>((props, ref) => {\n  useImperativeHandle(ref, () => ({ focus: () => inputRef.current?.focus() }));\n  return <input ref={inputRef} {...props} />;\n});",
    "options": ["InputHandle", "HTMLInputElement", "React.RefObject", "any"],
    "correct_answer": "InputHandle",
    "explanation": "By passing your custom `InputHandle` interface as the first generic to `forwardRef`, you tell TypeScript that any parent component using `ref={myRef}` will get an object typed exactly as `InputHandle`."
  },
  {
    "id": 385,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useCallback` Dependencies",
    "question": "What is a common TypeScript/React pitfall when using `useCallback` with an inline object or array in the dependency array?",
    "code_snippet": null,
    "options": ["It throws a syntax error", "The object/array is recreated on every render, causing the `useCallback` to constantly re-memoize and defeat the purpose of memoization", "It automatically types the dependencies", "It converts the dependencies to strings"],
    "correct_answer": "The object/array is recreated on every render, causing the `useCallback` to constantly re-memoize and defeat the purpose of memoization",
    "explanation": "Because `useCallback` uses `Object.is` for dependency comparison, a new inline object `{ id: 1 }` is never equal to the previous one. You must extract the dependencies to `useMemo` or primitive values outside the callback."
  },
  {
    "id": 386,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useMemo`",
    "question": "How does TypeScript infer the return type of `useMemo(() => computeExpensiveValue(a, b), [a, b])`?",
    "code_snippet": null,
    "options": ["It always returns `any`", "It infers it from the return type of the callback function `computeExpensiveValue`", "It requires an explicit generic type argument", "It returns the type of the dependency array"],
    "correct_answer": "It infers it from the return type of the callback function `computeExpensiveValue`",
    "explanation": "TypeScript looks at what the factory function returns and uses that as the type for the memoized value. You rarely need to explicitly type `useMemo` unless the inference fails."
  },
  {
    "id": 387,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "output-prediction",
    "topic": "Typing `useTransition`",
    "question": "What is the exact return type of the `useTransition` hook in React 18+?",
    "code_snippet": null,
    "options": ["[boolean, () => void]", "[isPending: boolean, startTransition: (callback: () => void) => void]", "{ isPending: boolean, startTransition: Function }", "Promise<void>"],
    "correct_answer": "[isPending: boolean, startTransition: (callback: () => void) => void]",
    "explanation": "`useTransition` returns a tuple. `isPending` is a boolean indicating if the transition is active, and `startTransition` is a function that takes a callback containing the state updates to be deferred."
  },
  {
    "id": 388,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "output-prediction",
    "topic": "Typing `useDeferredValue`",
    "question": "If you pass a `string` to `useDeferredValue(value)`, what is the inferred return type?",
    "code_snippet": null,
    "options": ["string", "string | undefined", "DeferredValue<string>", "Promise<string>"],
    "correct_answer": "string",
    "explanation": "`useDeferredValue` returns a deferred version of the exact same type you passed in. If you pass a `string`, it returns a `string`. If you pass a `User` object, it returns a `User` object."
  },
  {
    "id": 389,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing `useId`",
    "question": "What does the `useId` hook return, and how is it typed?",
    "code_snippet": null,
    "options": ["A number", "A unique string identifier (e.g., `:r1:`) for accessibility attributes", "A React Element", "A boolean"],
    "correct_answer": "A unique string identifier (e.g., `:r1:`) for accessibility attributes",
    "explanation": "`useId` returns a `string`. It is specifically designed to generate stable, unique IDs for `aria-labelledby` or `id` attributes, ensuring they match perfectly between server-side rendering and client-side hydration."
  },
  {
    "id": 390,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've now covered Polymorphic components, Render Props, HOCs, and advanced Hook typing. What is the ultimate benefit of mastering these advanced TypeScript React patterns?",
    "code_snippet": null,
    "options": ["It makes the React runtime faster", "It allows you to build highly reusable, type-safe component libraries and APIs that provide perfect autocomplete and catch logical errors before the code even runs", "It eliminates the need for React DevTools", "It automatically generates CSS"],
    "correct_answer": "It allows you to build highly reusable, type-safe component libraries and APIs that provide perfect autocomplete and catch logical errors before the code even runs",
    "explanation": "Mastering advanced React typing means you can build internal design systems and open-source libraries that are a joy to use. Consumers of your components get perfect IntelliSense, and the compiler guarantees they are using your API correctly."
  }
]
[
  {
    "id": 391,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React Server Components (Async)",
    "question": "How does TypeScript handle a React Server Component that needs to fetch data before rendering?",
    "code_snippet": null,
    "options": ["It throws an error because components must be synchronous", "It allows the component to be an `async` function that returns a `Promise<React.ReactNode>`", "It requires you to use `useEffect` to fetch the data", "It forces you to use a class component"],
    "correct_answer": "It allows the component to be an `async` function that returns a `Promise<React.ReactNode>`",
    "explanation": "React Server Components (RSC) broke the long-standing rule that React components must be synchronous. In modern React (and Next.js App Router), you can write `async function UserProfile({ id }: Props) { const user = await fetchUser(id); return <div>{user.name}</div>; }`, and TypeScript fully supports the `Promise<ReactNode>` return type."
  },
  {
    "id": 392,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Server Actions (FormData)",
    "question": "When typing a Next.js Server Action that handles a form submission, what is the type of the first parameter?",
    "code_snippet": "async function createPost(formData: _______) {\n  const title = formData.get('title');\n}",
    "options": ["React.FormEvent", "HTMLFormElement", "FormData", "SubmitEvent"],
    "correct_answer": "FormData",
    "explanation": "Server Actions bypass the traditional React synthetic event system. They receive the native Web API `FormData` object directly, allowing you to extract values using `.get('key')`. TypeScript provides perfect autocomplete for `FormData` methods."
  },
  {
    "id": 393,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "RSC Serialization Limits",
    "question": "What TypeScript/React error occurs if you try to pass a class instance or a function as a prop from a Server Component to a Client Component?",
    "code_snippet": null,
    "options": ["It compiles fine but crashes at runtime", "TypeScript warns you, and React throws a serialization error because props crossing the Server/Client boundary must be JSON-serializable", "It automatically converts the function to a string", "It strips the function out silently"],
    "correct_answer": "TypeScript warns you, and React throws a serialization error because props crossing the Server/Client boundary must be JSON-serializable",
    "explanation": "The boundary between Server and Client components is a serialization boundary. You can only pass primitive types, plain objects, arrays, and JSX. Passing functions, class instances, or Dates will result in a runtime error, and tools like the Next.js ESLint plugin will catch this at compile-time."
  },
  {
    "id": 394,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React 19: ref as a Prop",
    "question": "In React 19, how has the typing of the `ref` prop changed for function components?",
    "code_snippet": null,
    "options": ["`forwardRef` is now strictly mandatory", "You can now pass `ref` as a standard prop in your props interface, completely eliminating the need for `forwardRef` in most cases", "Refs are now typed as `string`", "Refs can only be used on class components"],
    "correct_answer": "You can now pass `ref` as a standard prop in your props interface, completely eliminating the need for `forwardRef` in most cases",
    "explanation": "React 19 officially supports `ref` as a regular prop. You can now write `interface Props { ref?: React.Ref<HTMLDivElement>; }` and accept it directly in your function arguments, making generic components with refs infinitely easier to type."
  },
  {
    "id": 395,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "ElementType vs ComponentType",
    "question": "What is the exact difference between `React.ElementType` and `React.ComponentType`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`ElementType` includes both React components AND intrinsic string tags (like `'div'`, `'span'`); `ComponentType` ONLY includes actual React components (functions/classes)", "`ComponentType` includes strings, `ElementType` does not", "`ElementType` is deprecated"],
    "correct_answer": "`ElementType` includes both React components AND intrinsic string tags (like `'div'`, `'span'`); `ComponentType` ONLY includes actual React components (functions/classes)",
    "explanation": "If you are building a polymorphic component that accepts an `as` prop (e.g., `as=\"a\"` or `as={Link}`), you MUST use `React.ElementType`. If you only expect actual React components, use `ComponentType`."
  },
  {
    "id": 396,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly use the built-in utility type to add `children` to an existing props interface.",
    "code_snippet": "interface CardProps {\n  title: string;\n}\n\n// Adds 'children?: ReactNode' automatically\ntype CardWithChildren = React._______<CardProps>;",
    "options": ["PropsWithChildren", "WithChildren", "AddChildren", "ChildrenProps"],
    "correct_answer": "PropsWithChildren",
    "explanation": "`React.PropsWithChildren<T>` is the standard utility to inject the `children` prop into an existing interface. It's incredibly useful when wrapping third-party components or creating layout wrappers."
  },
  {
    "id": 397,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "The 'key' Prop Restriction",
    "question": "Why does TypeScript prevent you from accessing or destructuring the `key` prop inside a component's body?",
    "code_snippet": null,
    "options": ["It's a syntax error", "Because `key` is a reserved React prop used for reconciliation; React strips it from the `props` object before passing it to the component", "It is typed as `private`", "It causes an infinite loop"],
    "correct_answer": "Because `key` is a reserved React prop used for reconciliation; React strips it from the `props` object before passing it to the component",
    "explanation": "If you try to write `function MyComponent({ key, id }: Props)`, TypeScript will throw an error. `key` is not meant for the component's internal logic; it is exclusively consumed by the React renderer."
  },
  {
    "id": 398,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Callback Refs Typing",
    "question": "How do you correctly type a 'callback ref' (a function passed to the `ref` prop) instead of an object ref?",
    "code_snippet": null,
    "options": ["React.RefObject<HTMLDivElement>", "React.RefCallback<HTMLDivElement> or (el: HTMLDivElement | null) => void", "React.MutableRefObject", "HTMLDivElement"],
    "correct_answer": "React.RefCallback<HTMLDivElement> or (el: HTMLDivElement | null) => void",
    "explanation": "Callback refs are called with the DOM element when it mounts, and `null` when it unmounts. Typing it as `(el: HTMLDivElement | null) => void` ensures you handle the unmounting cleanup correctly."
  },
  {
    "id": 399,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "defaultProps Deprecation",
    "question": "Why is the static `defaultProps` property heavily discouraged on function components in modern TypeScript React?",
    "code_snippet": null,
    "options": ["It throws a runtime error", "It breaks TypeScript's generic type inference and is redundant; modern TS perfectly handles native JavaScript default parameters in the function signature", "It is incompatible with React.memo", "It only works on class components"],
    "correct_answer": "It breaks TypeScript's generic type inference and is redundant; modern TS perfectly handles native JavaScript default parameters in the function signature",
    "explanation": "Writing `function Button({ size = 'md' }: Props)` natively tells TypeScript that `size` is optional but guaranteed to be a string inside the function. `defaultProps` creates conflicting type layers and is officially deprecated by the React team."
  },
  {
    "id": 400,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React 19 'use' Hook with Context",
    "question": "How does the new React 19 `use` hook change the way we consume Context compared to the traditional `useContext`?",
    "code_snippet": null,
    "options": ["It requires a generic type argument", "It can be called conditionally (inside loops or if-statements), whereas `useContext` must follow the Rules of Hooks", "It returns a Promise", "It automatically creates the Context"],
    "correct_answer": "It can be called conditionally (inside loops or if-statements), whereas `useContext` must follow the Rules of Hooks",
    "explanation": "The `use` hook is a true React API that reads a resource. Unlike `useContext`, which is bound by the strict Rules of Hooks, `use(MyContext)` can be placed anywhere in your render logic, providing massive flexibility for conditional context consumption."
  },
  {
    "id": 401,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly type the `fallback` prop of a `<Suspense>` component.",
    "code_snippet": "<Suspense fallback={<_______ />}>\n  <AsyncComponent />\n</Suspense>",
    "options": ["LoadingSpinner", "ReactNode", "JSX.Element", "Component"],
    "correct_answer": "LoadingSpinner",
    "explanation": "While the underlying type for `fallback` is `React.ReactNode`, in practice, you pass a JSX element (like `<LoadingSpinner />`) to display while the suspended component loads. TypeScript will enforce that whatever you pass is a valid renderable node."
  },
  {
    "id": 402,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Native vs Synthetic Events",
    "question": "If you are attaching an event listener using native JavaScript (`element.addEventListener('click', ...)`), which type should you use for the event parameter?",
    "code_snippet": null,
    "options": ["React.MouseEvent", "MouseEvent (from the global DOM lib)", "React.SyntheticEvent", "HTMLClickEvent"],
    "correct_answer": "MouseEvent (from the global DOM lib)",
    "explanation": "React Synthetic Events (`React.MouseEvent`) only exist inside JSX `onClick` props. If you are using native DOM APIs (like `addEventListener` or inside a `useEffect`), you must use the standard DOM `MouseEvent` type provided by TypeScript's `lib.dom.d.ts`."
  },
  {
    "id": 403,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Generic Constraints in Components",
    "question": "How do you constrain a generic React component to ensure that the items passed to it always have an `id: string` property?",
    "code_snippet": null,
    "options": ["function List<T>({ items }: { items: T[] })", "function List<T extends { id: string }>({ items }: { items: T[] })", "function List<T = { id: string }>({ items }: { items: T[] })", "function List<T implements { id: string }>({ items }: { items: T[] })"],
    "correct_answer": "function List<T extends { id: string }>({ items }: { items: T[] })",
    "explanation": "The `extends` keyword in generics acts as a constraint. It tells TypeScript, 'T can be any type (User, Product, etc.), as long as it has at least an `id` property that is a string.' This allows you to safely use `item.id` as a React `key` inside the component."
  },
  {
    "id": 404,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing Select onChange",
    "question": "When handling an `onChange` event on a `<select multiple>` element, what is the type of `event.target.value`?",
    "code_snippet": null,
    "options": ["string", "string[]", "number[]", "FormData"],
    "correct_answer": "string[]",
    "explanation": "While a standard `<select>` returns a single `string`, adding the `multiple` attribute changes the underlying HTMLSelectElement behavior, and TypeScript correctly types `event.target.value` as an array of strings (`string[]`)."
  },
  {
    "id": 405,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Children as a Function (Render Props)",
    "question": "If you are building a component that uses the 'Render Prop' pattern (where `children` is a function), how do you type the `children` prop?",
    "code_snippet": null,
    "options": ["children: React.ReactNode", "children: (state: StateType) => React.ReactNode", "children: React.FC", "children: Function"],
    "correct_answer": "children: (state: StateType) => React.ReactNode",
    "explanation": "Render props invert control. The parent component holds the state and passes a function to the child. Typing `children` as a function that returns `ReactNode` allows the consumer to decide exactly how to render the internal state."
  },
  {
    "id": 406,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "StrictNullChecks Impact",
    "question": "How does enabling `strictNullChecks` in `tsconfig.json` fundamentally change how you write React components?",
    "code_snippet": null,
    "options": ["It disables all React hooks", "It forces you to explicitly handle `undefined` or `null` states (e.g., using optional chaining `user?.name` or conditional rendering) before accessing properties", "It makes all props required", "It converts all types to `any`"],
    "correct_answer": "It forces you to explicitly handle `undefined` or `null` states (e.g., using optional chaining `user?.name` or conditional rendering) before accessing properties",
    "explanation": "Without `strictNullChecks`, TS assumes variables can never be null, leading to the dreaded 'Cannot read property of undefined' runtime crash. With it enabled, TS forces you to write resilient, defensive UI code."
  },
  {
    "id": 407,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "ComponentPropsWithoutRef",
    "question": "When building a custom `<Button>` wrapper around a native `<button>`, why is `React.ComponentPropsWithoutRef<'button'>` the preferred way to type the props?",
    "code_snippet": null,
    "options": ["It automatically adds React state", "It extracts all native button props (like 'type', 'disabled', 'onClick') so you don't have to manually rewrite them, while stripping 'ref' so you can handle it yourself", "It converts the button to a div", "It removes the 'children' prop"],
    "correct_answer": "It extracts all native button props (like 'type', 'disabled', 'onClick') so you don't have to manually rewrite them, while stripping 'ref' so you can handle it yourself",
    "explanation": "This utility type is the secret to building accessible, perfectly typed design systems. It guarantees your custom button supports every single native attribute a standard button does, ensuring zero loss of functionality."
  },
  {
    "id": 408,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Handling 'null' vs 'undefined' in Props",
    "question": "In React, what is the difference between passing `prop={null}` and `prop={undefined}` (or omitting it entirely) to a component?",
    "code_snippet": null,
    "options": ["They are exactly the same", "React treats `undefined` as 'use the default value', but `null` forces the prop to be explicitly empty/null, bypassing default values", "`null` triggers a re-render, `undefined` does not", "React throws an error for `null`"],
    "correct_answer": "React treats `undefined` as 'use the default value', but `null` forces the prop to be explicitly empty/null, bypassing default values",
    "explanation": "If you have `{ title = 'Default' }`, passing `undefined` results in 'Default'. Passing `null` results in `null`. TypeScript's `strictNullChecks` helps you enforce which of these two distinct states your component actually accepts."
  },
  {
    "id": 409,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing displayName for Generics",
    "question": "Why is it notoriously difficult to set the `displayName` property on a Generic React component in TypeScript?",
    "code_snippet": null,
    "options": ["Generic components cannot have a displayName", "Because assigning a generic function to a variable and then attaching `.displayName` often breaks the generic type signature, requiring a type assertion or a namespace merge", "It is deprecated in React 19", "TypeScript automatically generates it"],
    "correct_answer": "Because assigning a generic function to a variable and then attaching `.displayName` often breaks the generic type signature, requiring a type assertion or a namespace merge",
    "explanation": "To fix this, developers often use Declaration Merging (creating a `namespace` with the same name as the component) to safely attach `displayName` without destroying the generic `<T>` signature."
  },
  {
    "id": 410,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Part 3 Wrap-up",
    "question": "You've now mastered Server Components, React 19 features, and advanced generic patterns. What is the ultimate hallmark of a React + TypeScript expert?",
    "code_snippet": null,
    "options": ["They never use 'any'", "They can design component APIs and architectural boundaries where the TypeScript compiler guarantees the correct flow of data between the Server, the Client, and the DOM, making invalid UI states impossible to render", "They write all their own utility types", "They avoid using third-party libraries"],
    "correct_answer": "They can design component APIs and architectural boundaries where the TypeScript compiler guarantees the correct flow of data between the Server, the Client, and the DOM, making invalid UI states impossible to render",
    "explanation": "React + TypeScript is not just about adding `: string` to variables. It's about creating a self-documenting, mathematically provable UI architecture where the compiler acts as your co-pilot, ensuring your app is robust, accessible, and maintainable at any scale."
  }
]
[
  {
    "id": 411,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Testing (React Testing Library)",
    "question": "When using React Testing Library, what is the most accessible and recommended way to query for an element, and how does TypeScript support it?",
    "code_snippet": null,
    "options": ["getByTestId", "getByRole, which provides strict autocomplete for valid ARIA roles (e.g., 'button', 'heading')", "querySelector", "getByText"],
    "correct_answer": "getByRole, which provides strict autocomplete for valid ARIA roles (e.g., 'button', 'heading')",
    "explanation": "RTL's `getByRole` is fully typed in TypeScript. If you type `screen.getByRole('')`, TS will show a dropdown of every valid ARIA role, preventing typos and encouraging accessible testing practices."
  },
  {
    "id": 412,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Testing (Mocking Modules)",
    "question": "When using Vitest or Jest to mock an external module, how do you ensure the mock implementation matches the original TypeScript interface?",
    "code_snippet": null,
    "options": ["You cannot type mocks", "By using `vi.mocked(originalFunction).mockImplementation(...)` or casting the mock object `as jest.Mocked<typeof originalModule>`", "By using the `any` type on the mock", "By rewriting the interface manually"],
    "correct_answer": "By using `vi.mocked(originalFunction).mockImplementation(...)` or casting the mock object `as jest.Mocked<typeof originalModule>`",
    "explanation": "TypeScript doesn't automatically know that `vi.mock()` replaces the real implementation. Using the `Mocked` utility type or `vi.mocked()` helper bridges the gap, giving you full autocomplete on `.mockReturnValue()` and `.mockImplementation()`."
  },
  {
    "id": 413,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "React Router (useParams)",
    "question": "Fill in the blank to correctly type the `useParams` hook to extract a specific `postId` string parameter.",
    "code_snippet": "const { postId } = useParams<_______>();",
    "options": ["{ postId: string }", "postId", "string", "Params"],
    "correct_answer": "{ postId: string }",
    "explanation": "By default, `useParams` returns `{ [key: string]: string | undefined }`. Passing a generic type argument like `{ postId: string }` narrows the type, allowing you to use `postId` directly without undefined checks (assuming your route guarantees it)."
  },
  {
    "id": 414,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React Router (Navigate State)",
    "question": "How do you type the state object passed via `navigate('/dashboard', { state: ... })` in React Router v6?",
    "code_snippet": null,
    "options": ["React Router automatically infers it", "You must define a custom interface for the location state and use `useLocation<MyStateType>()` to read it", "It is always typed as `any`", "You must use `useParams` instead"],
    "correct_answer": "You must define a custom interface for the location state and use `useLocation<MyStateType>()` to read it",
    "explanation": "React Router's `state` is essentially a black box to the router. To get type safety when reading `location.state` on the destination page, you must provide the generic type to `useLocation<T>()`."
  },
  {
    "id": 415,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React Router (Loaders)",
    "question": "In React Router v6.4+ (or Remix), what is the standard type for the argument passed to a `loader` function?",
    "code_snippet": null,
    "options": ["React.Request", "LoaderFunctionArgs (which includes request, params, and context)", "FormData", "useLoaderData"],
    "correct_answer": "LoaderFunctionArgs (which includes request, params, and context)",
    "explanation": "Typing your loader as `export async function loader({ request, params }: LoaderFunctionArgs)` gives you perfect TypeScript autocomplete for the incoming HTTP request and the dynamic route parameters."
  },
  {
    "id": 416,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Forms (React Hook Form)",
    "question": "Fill in the blank to correctly type the `useForm` hook with a specific form schema.",
    "code_snippet": "interface LoginForm { email: string; password: string; }\nconst { register } = useForm<_______>();",
    "options": ["LoginForm", "FormData", "FormSchema", "any"],
    "correct_answer": "LoginForm",
    "explanation": "Passing your form's interface to `useForm<LoginForm>()` ensures that `register('email')` provides autocomplete and throws a compile-time error if you try to register a field that doesn't exist in your schema."
  },
  {
    "id": 417,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Forms (Zod Integration)",
    "question": "How do you connect a Zod schema to React Hook Form for runtime validation AND compile-time type safety?",
    "code_snippet": null,
    "options": ["By manually writing the TypeScript interface to match the Zod schema", "By using `z.infer<typeof schema>` to automatically generate the TS type from the Zod schema, and passing it to `zodResolver(schema)`", "By using the `any` type", "Zod does not support TypeScript"],
    "correct_answer": "By using `z.infer<typeof schema>` to automatically generate the TS type from the Zod schema, and passing it to `zodResolver(schema)`",
    "explanation": "`z.infer` extracts the exact TypeScript type from your Zod validation schema. This creates a single source of truth: your Zod schema handles runtime validation, and the inferred type handles compile-time checking."
  },
  {
    "id": 418,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Data Fetching (TanStack Query)",
    "question": "Fill in the blank to correctly type the `useQuery` hook, specifying the expected data type and error type.",
    "code_snippet": "const { data, error } = useQuery<_______, Error>({\n  queryKey: ['user'],\n  queryFn: fetchUser,\n});",
    "options": ["User", "any", "Response", "Promise"],
    "correct_answer": "User",
    "explanation": "`useQuery<TData, TError>` allows you to explicitly define the shape of the resolved data (`User`) and the type of the error object (`Error`), giving you perfect type safety in your loading and error states."
  },
  {
    "id": 419,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Data Fetching (Query Options)",
    "question": "What is the purpose of the `queryOptions` helper in TanStack Query v5?",
    "code_snippet": null,
    "options": ["It minifies the query key", "It allows you to pre-define and type a query configuration object outside of a component, ensuring the queryKey, queryFn, and return types are perfectly linked and reusable", "It caches the data to disk", "It converts the query to a mutation"],
    "correct_answer": "It allows you to pre-define and type a query configuration object outside of a component, ensuring the queryKey, queryFn, and return types are perfectly linked and reusable",
    "explanation": "By using `const userQueryOptions = queryOptions({ queryKey: [...], queryFn: ... })`, TypeScript infers the exact return type of the `queryFn`. When you pass this object to `useQuery(userQueryOptions)`, the `data` variable is automatically typed correctly without needing manual generics."
  },
  {
    "id": 420,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "topic": "State Management (Zustand)",
    "question": "Fill in the blank to correctly type a Zustand store that holds a `count` number and an `increment` function.",
    "code_snippet": "interface BearState { count: number; increment: () => void; }\nconst useBearStore = create<_______>()((set) => ({ ... }));",
    "options": ["BearState", "State", "Store", "any"],
    "correct_answer": "BearState",
    "explanation": "Passing your state interface to `create<BearState>()` ensures that the `set` function provided by Zustand only accepts valid updates to the `BearState` shape, preventing accidental state corruption."
  },
  {
    "id": 421,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "State Management (Zustand Actions)",
    "question": "When defining actions in Zustand that need to read the current state (using `get`), how do you ensure `get()` returns the correctly typed state?",
    "code_snippet": null,
    "options": ["`get()` is always typed as `any`", "By defining the entire store interface (state + actions) in a single generic type passed to `create<StoreInterface>()`", "By manually casting `get() as BearState`", "Zustand does not support `get()`"],
    "correct_answer": "By defining the entire store interface (state + actions) in a single generic type passed to `create<StoreInterface>()`",
    "explanation": "If your generic type includes both the data and the functions (e.g., `interface Store { count: number; add: () => void }`), Zustand's `get()` function will automatically return the fully typed `Store` object, allowing you to read `get().count` safely."
  },
  {
    "id": 422,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Performance (React.memo Comparison)",
    "question": "When providing a custom comparison function to `React.memo(Component, areEqual)`, what is the required TypeScript signature for `areEqual`?",
    "code_snippet": null,
    "options": ["(prevProps: Props, nextProps: Props) => boolean", "(props: Props) => void", "(prev: any, next: any) => any", "(state: State) => boolean"],
    "correct_answer": "(prevProps: Props, nextProps: Props) => boolean",
    "explanation": "The comparison function receives the previous and next props and must return a boolean. Returning `true` means the props are equal (skip re-render); `false` means they differ (trigger re-render). TS enforces that both arguments match the component's `Props` interface."
  },
  {
    "id": 423,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Context (Complex State Pattern)",
    "question": "When building a complex Context provider using the `useReducer` pattern, what is the best way to type the Context value to avoid unnecessary re-renders?",
    "code_snippet": null,
    "options": ["Put the state and dispatch in a single object", "Split the Context into two separate contexts: one for State and one for Dispatch, so components that only dispatch don't re-render when state changes", "Use `any` for the dispatch", "Context cannot be used with useReducer"],
    "correct_answer": "Split the Context into two separate contexts: one for State and one for Dispatch, so components that only dispatch don't re-render when state changes",
    "explanation": "By creating `StateContext` and `DispatchContext`, TypeScript allows you to type them separately (`React.Context<State>` and `React.Context<Dispatch<Action>>`). Components that only need to trigger actions won't re-render when the state object changes."
  },
  {
    "id": 424,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Portals",
    "question": "What is the required TypeScript type for the `container` argument when using `ReactDOM.createPortal(children, container)`?",
    "code_snippet": null,
    "options": ["string", "Element (a native DOM Element)", "ReactNode", "HTMLElement"],
    "correct_answer": "Element (a native DOM Element)",
    "explanation": "The `createPortal` function requires an actual, mounted DOM `Element` (like `document.body` or a specific `div` ref). TypeScript enforces this to prevent you from accidentally passing a React component or a string selector."
  },
  {
    "id": 425,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Error Boundaries",
    "question": "Since Error Boundaries currently still require Class Components, how do you type the `componentDidCatch` lifecycle method?",
    "code_snippet": null,
    "options": ["(error: Error, info: React.ErrorInfo) => void", "(error: any) => void", "(error: string) => void", "Error boundaries cannot be typed"],
    "correct_answer": "(error: Error, info: React.ErrorInfo) => void",
    "explanation": "React provides the `React.ErrorInfo` interface, which contains the `componentStack` string. Typing `componentDidCatch(error: Error, info: React.ErrorInfo)` gives you perfect autocomplete for logging the exact component tree that failed."
  },
  {
    "id": 426,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Third-Party Libraries (Missing Types)",
    "question": "If you install a JavaScript library that doesn't have `@types` available and doesn't ship its own `.d.ts` files, how do you prevent TypeScript from throwing 'Could not find a declaration file' errors?",
    "code_snippet": null,
    "options": ["Disable TypeScript", "Create an `ambient.d.ts` file with `declare module 'library-name';`", "Use `@ts-ignore` on every import", "Rewrite the library in TypeScript"],
    "correct_answer": "Create an `ambient.d.ts` file with `declare module 'library-name';`",
    "explanation": "By declaring the module as an ambient module, TypeScript treats it as `any`. This stops the compilation errors immediately, allowing you to use the library while you optionally write custom type definitions for it later."
  },
  {
    "id": 427,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Strict Mode & Pure Functions",
    "question": "How does React's Strict Mode (which double-invokes components in development) interact with TypeScript's type system?",
    "code_snippet": null,
    "options": ["TS throws an error", "TS doesn't care, but it enforces that your component bodies and initializers must be 'pure functions' (no side effects), because if they mutate external variables, the double-render will cause bugs", "TS disables Strict Mode", "TS automatically fixes the side effects"],
    "correct_answer": "TS doesn't care, but it enforces that your component bodies and initializers must be 'pure functions' (no side effects), because if they mutate external variables, the double-render will cause bugs",
    "explanation": "TypeScript ensures your types are correct, but it cannot enforce 'purity'. However, understanding that TS types assume pure data flow is crucial. If you mutate a global variable during render, Strict Mode will expose the bug, even if TS says the types are valid."
  },
  {
    "id": 428,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing CSS Modules",
    "question": "When using CSS Modules (e.g., `import styles from './Button.module.css'`), what does TypeScript infer the type of `styles` to be (assuming proper global declarations)?",
    "code_snippet": null,
    "options": ["string", "{ readonly [key: string]: string }", "React.CSSProperties", "HTMLElement"],
    "correct_answer": "{ readonly [key: string]: string }",
    "explanation": "CSS Modules map class names to hashed strings at runtime. By declaring the module type as a readonly dictionary of strings, TypeScript allows `styles.container` while preventing you from accidentally assigning a new value to it."
  },
  {
    "id": 429,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Typing Children (Specific Elements)",
    "question": "If you want to restrict a component's `children` prop to ONLY accept `<Tab>` components and nothing else, what is the best TypeScript approach?",
    "code_snippet": null,
    "options": ["children: React.ReactElement[]", "children: React.ReactElement<TabProps, typeof Tab>[]", "children: JSX.Element", "You cannot restrict children in TS"],
    "correct_answer": "children: React.ReactElement<TabProps, typeof Tab>[]",
    "explanation": "By using `React.ReactElement<ExpectedProps, ExpectedType>`, TypeScript will check the `type` property of the React elements passed as children. If a user passes a `<div>` instead of a `<Tab>`, TS will throw a compile-time error."
  },
  {
    "id": 430,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Part 4 Wrap-up",
    "question": "You've now covered Testing, Routing, Forms, and Data Fetching in React + TypeScript. What is the ultimate benefit of strictly typing your ecosystem tools?",
    "code_snippet": null,
    "options": ["It makes the tests run faster", "It creates an unbroken chain of type safety from your database schema, through your API, into your form validation, and finally to your UI components, catching mismatches before deployment", "It removes the need for a backend", "It automatically deploys the app"],
    "correct_answer": "It creates an unbroken chain of type safety from your database schema, through your API, into your form validation, and finally to your UI components, catching mismatches before deployment",
    "explanation": "When you type your Zod schemas, your React Query hooks, and your React Router params, you create an end-to-end type-safe pipeline. If the backend changes a field name, TypeScript will highlight every single UI component and test that needs updating."
  }
]
[
  {
    "id": 431,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "State Machines (XState Concept)",
    "question": "What is the primary benefit of using a State Machine library like XState in a TypeScript React application?",
    "code_snippet": null,
    "options": ["It makes CSS animations faster", "It models complex UI logic as finite states and transitions, allowing TypeScript to mathematically guarantee that invalid states and impossible transitions are literally unrepresentable", "It replaces React Context", "It automatically generates unit tests"],
    "correct_answer": "It models complex UI logic as finite states and transitions, allowing TypeScript to mathematically guarantee that invalid states and impossible transitions are literally unrepresentable",
    "explanation": "State machines eliminate 'impossible states'. By defining exactly what states exist and what events trigger transitions, TypeScript can enforce that your UI only ever renders valid, predictable combinations of data."
  },
  {
    "id": 432,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "XState Context Typing",
    "question": "How do you define the strongly-typed 'context' (data) for an XState machine?",
    "code_snippet": null,
    "options": ["By passing a generic type to `createMachine<{ count: number }>()`", "By defining a TypeScript interface for the context and passing it to the machine's type configuration", "By using `any`", "XState does not support typing context"],
    "correct_answer": "By defining a TypeScript interface for the context and passing it to the machine's type configuration",
    "explanation": "By explicitly typing the context, every time you read `state.context` in your React component, TypeScript provides perfect autocomplete and guarantees the data shape matches your interface."
  },
  {
    "id": 433,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "XState Event Typing",
    "question": "How does XState ensure type safety for the events sent to a machine?",
    "code_snippet": null,
    "options": ["Events are always strings", "By defining a discriminated union of event objects (e.g., `{ type: 'INCREMENT' } | { type: 'DECREMENT', payload: number }`) in the machine's type schema", "By using `any`", "Events cannot be typed"],
    "correct_answer": "By defining a discriminated union of event objects (e.g., `{ type: 'INCREMENT' } | { type: 'DECREMENT', payload: number }`) in the machine's type schema",
    "explanation": "Because events are typed as a discriminated union, the `send` function provided by `useMachine` will throw a compile-time error if you try to dispatch an event that doesn't exist or pass the wrong payload."
  },
  {
    "id": 434,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "XState useMachine Hook",
    "question": "What does the `useMachine` hook return, and how is it typed?",
    "code_snippet": null,
    "options": ["A single state object", "A tuple of `[state, send]`, where `state` contains the typed current state/context, and `send` is a strictly typed function for dispatching events", "A Promise", "A React Ref"],
    "correct_answer": "A tuple of `[state, send]`, where `state` contains the typed current state/context, and `send` is a strictly typed function for dispatching events",
    "explanation": "The `state` object includes typed properties like `state.matches('loading')` and `state.context`, while `send` only accepts the exact event objects defined in your machine's schema."
  },
  {
    "id": 435,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Accessibility (ARIA Attributes)",
    "question": "How does TypeScript support ARIA attributes in React JSX?",
    "code_snippet": null,
    "options": ["It doesn't, you must use `any`", "React's JSX type definitions include strict typing for all valid `aria-*` attributes, ensuring you only use correct names and value types (e.g., `aria-expanded` must be a boolean)", "It converts them to CSS classes", "It throws a runtime error"],
    "correct_answer": "React's JSX type definitions include strict typing for all valid `aria-*` attributes, ensuring you only use correct names and value types (e.g., `aria-expanded` must be a boolean)",
    "explanation": "If you try to write `aria-expanded='true'` (a string), TypeScript will flag it as an error, forcing you to use the correct boolean type `aria-expanded={true}`."
  },
  {
    "id": 436,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly type a keyboard event handler for a custom accessible button that triggers on 'Enter' or 'Space'.",
    "code_snippet": "const handleKeyDown = (e: React._______<HTMLDivElement>) => {\n  if (e.key === 'Enter' || e.key === ' ') { ... }\n};",
    "options": ["MouseEvent", "KeyboardEvent", "FocusEvent", "SyntheticEvent"],
    "correct_answer": "KeyboardEvent",
    "explanation": "`React.KeyboardEvent` provides strict typing for the `.key` and `.code` properties, ensuring you are checking for the exact string literals defined by the DOM specification."
  },
  {
    "id": 437,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Accessibility (Testing Library)",
    "question": "How do you add TypeScript support for custom accessibility matchers like `toBeInTheDocument()` or `toHaveAttribute('aria-label', ...)` in your tests?",
    "code_snippet": null,
    "options": ["They are automatically included", "By importing `@testing-library/jest-dom` and ensuring its type definitions are included in your `tsconfig.json` or test setup file", "By using `@ts-ignore`", "You must write the types manually"],
    "correct_answer": "By importing `@testing-library/jest-dom` and ensuring its type definitions are included in your `tsconfig.json` or test setup file",
    "explanation": "The `@testing-library/jest-dom` package ships with its own `.d.ts` files that extend the global `expect` interface, giving you perfect autocomplete for all DOM and ARIA matchers."
  },
  {
    "id": 438,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Framer Motion (Variants)",
    "question": "What is the standard TypeScript type used to define a set of named animation states (variants) in Framer Motion?",
    "code_snippet": null,
    "options": ["React.CSSProperties", "Variants (a record of string keys mapping to Variant objects)", "AnimationOptions", "Keyframes"],
    "correct_answer": "Variants (a record of string keys mapping to Variant objects)",
    "explanation": "The `Variants` type allows you to define complex, multi-property animations (like `hidden`, `visible`, `hover`) and pass them to the `variants` prop with full type safety."
  },
  {
    "id": 439,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Framer Motion (Custom Components)",
    "question": "How do you animate a custom React component using Framer Motion's `motion()` factory?",
    "code_snippet": null,
    "options": ["You cannot animate custom components", "By wrapping it with `motion(MyCustomComponent)`, provided the component correctly forwards refs and accepts `MotionProps`", "By using CSS-in-JS only", "By converting it to a class component"],
    "correct_answer": "By wrapping it with `motion(MyCustomComponent)`, provided the component correctly forwards refs and accepts `MotionProps`",
    "explanation": "Framer Motion needs to attach animation props and a ref to the underlying DOM node. If your custom component doesn't use `forwardRef` and spread the remaining props, TypeScript and the runtime will throw errors."
  },
  {
    "id": 440,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Framer Motion (onAnimationComplete)",
    "question": "How do you type the callback for `onAnimationComplete` in Framer Motion?",
    "code_snippet": null,
    "options": ["() => void", "(definition: VariantLabels | string) => void", "(event: AnimationEvent) => void", "It cannot be typed"],
    "correct_answer": "(definition: VariantLabels | string) => void",
    "explanation": "The callback receives the name of the variant (or the animation definition) that just finished, allowing you to chain animations or update state based on exactly which animation completed."
  },
  {
    "id": 441,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Compound Components (Concept)",
    "question": "What is the 'Compound Components' pattern in React, and how does TypeScript enhance it?",
    "code_snippet": null,
    "options": ["A pattern where components are styled together; TS adds CSS types", "A pattern where a parent component provides implicit state to child components (e.g., `<Select>` and `<Select.Option>`); TS enhances it by strictly typing the children and ensuring they are only used within the parent", "A pattern for routing; TS types the URLs", "A pattern for forms; TS validates the inputs"],
    "correct_answer": "A pattern where a parent component provides implicit state to child components (e.g., `<Select>` and `<Select.Option>`); TS enhances it by strictly typing the children and ensuring they are only used within the parent",
    "explanation": "TypeScript allows you to restrict the `children` prop of the parent to ONLY accept the specific sub-components, preventing users from accidentally passing invalid elements like `<div>` into a `<Select>`."
  },
  {
    "id": 442,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Compound Components (Typing)",
    "question": "How do you typically attach sub-components to a parent component in TypeScript to create a Compound Component API?",
    "code_snippet": null,
    "options": ["By exporting them separately", "By assigning them as static properties on the parent function (e.g., `Parent.Child = Child`) and typing the parent interface to include them", "By using React Context only", "By using a global variable"],
    "correct_answer": "By assigning them as static properties on the parent function (e.g., `Parent.Child = Child`) and typing the parent interface to include them",
    "explanation": "This creates a clean, namespaced API (`<Menu><Menu.Item /></Menu>`) while keeping the types tightly coupled and easily discoverable in the IDE."
  },
  {
    "id": 443,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Control Props (Concept)",
    "question": "What does it mean for a React component to support both 'Controlled' and 'Uncontrolled' usage, and how is it typed?",
    "code_snippet": null,
    "options": ["It means the component can be styled in two ways", "It means the component can manage its own state (uncontrolled) OR accept state from a parent (controlled); TS types this using intersection and union types to enforce that either `value` or `defaultValue` is provided, but not both", "It means the component can be rendered on server or client", "It means the component can use two different hooks"],
    "correct_answer": "It means the component can manage its own state (uncontrolled) OR accept state from a parent (controlled); TS types this using intersection and union types to enforce that either `value` or `defaultValue` is provided, but not both",
    "explanation": "By using advanced generic constraints, you can tell TypeScript: 'If the user provides `value`, they MUST also provide `onChange`. If they provide `defaultValue`, `onChange` is optional.'"
  },
  {
    "id": 444,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React 19 (useActionState)",
    "question": "What is the primary purpose of the new React 19 `useActionState` hook (formerly `useFormState`)?",
    "code_snippet": null,
    "options": ["To replace useState", "To manage the state and pending status of a Server Action, returning the action's result and an `isPending` boolean", "To animate forms", "To validate form inputs"],
    "correct_answer": "To manage the state and pending status of a Server Action, returning the action's result and an `isPending` boolean",
    "explanation": "`useActionState` is fully typed. If your Server Action returns a specific error object or success message, TypeScript will infer the exact shape of the state returned by the hook."
  },
  {
    "id": 445,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "React 19 (useOptimistic)",
    "question": "How does the `useOptimistic` hook improve the user experience, and how is it typed?",
    "code_snippet": null,
    "options": ["It compresses the bundle size", "It allows you to immediately render an optimistic UI update while a Server Action is processing, typed as a tuple of `[optimisticState, setOptimisticState]`", "It caches the database", "It replaces useReducer"],
    "correct_answer": "It allows you to immediately render an optimistic UI update while a Server Action is processing, typed as a tuple of `[optimisticState, setOptimisticState]`",
    "explanation": "You pass the real state and an 'optimistic' update function. TypeScript ensures the optimistic state matches the shape of the real state, preventing UI crashes when the server response finally arrives."
  },
  {
    "id": 446,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "End-to-End Type Safety (tRPC)",
    "question": "How does a library like tRPC achieve 'End-to-End Type Safety' between a TypeScript backend and a React frontend?",
    "code_snippet": null,
    "options": ["By using GraphQL schemas", "By inferring the TypeScript types directly from the backend router procedures and sharing them with the frontend client, ensuring API calls are 100% type-checked without code generation", "By using REST APIs", "By writing manual `.d.ts` files"],
    "correct_answer": "By inferring the TypeScript types directly from the backend router procedures and sharing them with the frontend client, ensuring API calls are 100% type-checked without code generation",
    "explanation": "If you change a database column name in your backend procedure, tRPC instantly highlights every single React component and test that relies on that field, eliminating an entire class of integration bugs."
  },
  {
    "id": 447,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Colocation)",
    "question": "What is the concept of 'Colocation' in React and TypeScript architecture?",
    "code_snippet": null,
    "options": ["Putting all CSS in one file", "Keeping related code (components, hooks, types, tests, and styles) as close together as possible in the file tree, reducing cognitive load and improving maintainability", "Using only one component per file", "Hosting the backend and frontend on the same server"],
    "correct_answer": "Keeping related code (components, hooks, types, tests, and styles) as close together as possible in the file tree, reducing cognitive load and improving maintainability",
    "explanation": "Instead of having separate `components/`, `hooks/`, and `types/` folders at the root of your app, colocation suggests putting the `Button.types.ts` and `Button.test.tsx` right next to `Button.tsx`."
  },
  {
    "id": 448,
    "level": "intermediate",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Barrel Files)",
    "question": "What is a 'Barrel File' (e.g., `index.ts`) in a TypeScript React project, and what is a potential performance drawback of overusing them?",
    "code_snippet": null,
    "options": ["A file that stores environment variables; it slows down the database", "A file that re-exports modules to create a clean public API; overusing them can defeat tree-shaking and increase bundle size if not configured correctly", "A file that stores images; it increases memory usage", "A file that compiles TypeScript; it slows down the build"],
    "correct_answer": "A file that re-exports modules to create a clean public API; overusing them can defeat tree-shaking and increase bundle size if not configured correctly",
    "explanation": "If a barrel file imports a massive component just to re-export it, bundlers might include the entire component in the final JS bundle, even if the consumer only needed a tiny utility function from that folder."
  },
  {
    "id": 449,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Design Systems)",
    "question": "When building a shared Design System or Component Library in TypeScript, what is the most critical practice for the public API?",
    "code_snippet": null,
    "options": ["Using `any` for flexibility", "Strictly exporting only the necessary types, components, and hooks, while keeping internal utilities and types private to prevent breaking changes for consumers", "Writing all components as class components", "Avoiding TypeScript entirely"],
    "correct_answer": "Strictly exporting only the necessary types, components, and hooks, while keeping internal utilities and types private to prevent breaking changes for consumers",
    "explanation": "By carefully curating your `index.ts` exports, you create a stable contract. You can refactor internal implementation details without breaking the apps that depend on your library."
  },
  {
    "id": 450,
    "level": "advanced",
    "module_id": "ts_mod_06_react",
    "module_name": "React & TypeScript",
    "type": "conceptual",
    "topic": "Final Philosophy",
    "question": "You have now completed the entire 100-question deep dive into React and TypeScript. What is the ultimate philosophy of mastering this combination?",
    "code_snippet": null,
    "options": ["To write as much TypeScript as possible, even if it slows down development", "To view TypeScript not as a burden, but as a powerful design tool that forces you to think deeply about your component contracts, data flow, and edge cases, ultimately resulting in resilient, self-documenting, and joyful applications", "To avoid using React Hooks", "To manually test every component"],
    "correct_answer": "To view TypeScript not as a burden, but as a powerful design tool that forces you to think deeply about your component contracts, data flow, and edge cases, ultimately resulting in resilient, self-documenting, and joyful applications",
    "explanation": "TypeScript shifts the debugging process from 'runtime panic' to 'compile-time design'. When you master it, you stop fighting the compiler and start using it as your most trusted co-pilot in building world-class user interfaces."
  }
]

