[
  {
    "id": 51,
    "level": "beginner",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Inline Object Types",
    "question": "What is the correct syntax to define an inline object type in TypeScript?",
    "code_snippet": null,
    "options": ["Object(name: string, age: number)", "{ name: string, age: number }", "type Object { name: string }", "[string, number]"],
    "correct_answer": "{ name: string, age: number }",
    "explanation": "Inline object types are defined using curly braces `{}` containing a list of properties and their corresponding types, separated by commas or semicolons."
  },
  {
    "id": 52,
    "level": "beginner",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Inline Object Types",
    "question": "Fill in the blank to correctly type a `user` variable as an object with a `name` (string) and `age` (number).",
    "code_snippet": "let user: _______ = { name: 'Alice', age: 30 };",
    "options": ["{ name: string, age: number }", "Object<string, number>", "type user", "map(name, age)"],
    "correct_answer": "{ name: string, age: number }",
    "explanation": "The variable `user` is strictly bound to this shape. If you try to add a `email` property or miss the `age` property, the compiler will immediately throw an error."
  },
  {
    "id": 53,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Optional Properties",
    "question": "How do you define an optional property in a TypeScript object type?",
    "code_snippet": null,
    "options": ["name: string | undefined", "name?: string", "optional name: string", "name: string?"],
    "correct_answer": "name?: string",
    "explanation": "The `?` suffix immediately following the property name marks it as optional. This means the property can either be a `string` or be completely missing from the object."
  },
  {
    "id": 54,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Optional Properties",
    "question": "Fill in the blank to correctly make the `nickname` property optional in this interface.",
    "code_snippet": "interface User {\n  name: string;\n  nickname: _______ string;\n}",
    "options": ["?", "| undefined", "optional", "maybe"],
    "correct_answer": "?",
    "explanation": "Placing the `?` before the colon tells TypeScript, 'This property might not exist on the object at all.' This is essential for modeling real-world APIs where fields are often omitted."
  },
  {
    "id": 55,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "type vs interface",
    "question": "What is the primary difference between a `type` alias and an `interface` when defining object shapes?",
    "code_snippet": null,
    "options": ["`type` is for primitives, `interface` is for objects", "`interface` can be extended and merged (re-opened), while `type` aliases cannot be re-opened but can represent unions and primitives", "They are exactly the same in every way", "`type` is deprecated in modern TypeScript"],
    "correct_answer": "`interface` can be extended and merged (re-opened), while `type` aliases cannot be re-opened but can represent unions and primitives",
    "explanation": "Use `interface` for defining the 'shape' of objects and classes (especially public APIs). Use `type` for unions (`A | B`), tuples, and complex mapped types. Both are highly valid, but they have slightly different superpowers."
  },
  {
    "id": 56,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Extending Interfaces",
    "question": "How do you make one interface inherit all properties from another interface?",
    "code_snippet": null,
    "options": ["interface Admin implements User { ... }", "interface Admin extends User { ... }", "interface Admin + User { ... }", "interface Admin inherits User { ... }"],
    "correct_answer": "interface Admin extends User { ... }",
    "explanation": "The `extends` keyword allows you to copy all properties from a parent interface into a child interface, and then add new, specific properties on top. This promotes code reuse and clear hierarchies."
  },
  {
    "id": 57,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Extending Interfaces",
    "question": "Fill in the blank to correctly extend the `User` interface to create an `Admin` interface.",
    "code_snippet": "interface Admin _______ User {\n  role: string;\n}",
    "options": ["extends", "implements", "inherits", "merges"],
    "correct_answer": "extends",
    "explanation": "An `Admin` will now require a `name`, an `age` (from `User`), AND a `role` (from `Admin`). If you miss any of these three properties, the compiler will throw an error."
  },
  {
    "id": 58,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Intersection Types",
    "question": "What does the intersection operator (`&`) do when combining two object types?",
    "code_snippet": null,
    "options": ["It creates a union where an object can be either type", "It creates a new type that requires the properties of BOTH types to be present simultaneously", "It removes overlapping properties", "It converts the objects to arrays"],
    "correct_answer": "It creates a new type that requires the properties of BOTH types to be present simultaneously",
    "explanation": "If `A` has `name` and `B` has `age`, `A & B` requires an object to have BOTH `name` AND `age`. It 'intersects' the requirements of both types into a single, stricter type."
  },
  {
    "id": 59,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Intersection vs Extends",
    "question": "When should you use an Intersection (`&`) instead of `extends`?",
    "code_snippet": null,
    "options": ["When you want to combine two `type` aliases (since `type` cannot use the `extends` keyword)", "When you want to make properties optional", "When you are working with classes", "You should never use `&`, it is deprecated"],
    "correct_answer": "When you want to combine two `type` aliases (since `type` cannot use the `extends` keyword)",
    "explanation": "Because `type` aliases don't support the `extends` keyword, you use intersections to combine them: `type Admin = User & { role: string };`. For interfaces, `extends` is generally preferred for readability."
  },
  {
    "id": 60,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "readonly Modifier",
    "question": "What does the `readonly` modifier do to an object property?",
    "code_snippet": null,
    "options": ["It makes the property optional", "It prevents the property from being reassigned after the object is initially created", "It makes the property private to the module", "It converts the property to a string"],
    "correct_answer": "It prevents the property from being reassigned after the object is initially created",
    "explanation": "`readonly` enforces immutability at the compile-time level. If you try to do `user.id = 5` after the object is created, TypeScript will block it, preventing accidental state mutations."
  },
  {
    "id": 61,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "readonly Modifier",
    "question": "Fill in the blank to correctly mark the `id` property as immutable.",
    "code_snippet": "interface User {\n  _______ id: number;\n  name: string;\n}",
    "options": ["readonly", "const", "immutable", "final"],
    "correct_answer": "readonly",
    "explanation": "The `readonly` keyword is placed before the property name. It is the TypeScript equivalent of `Object.freeze()`, but it happens entirely at compile-time with zero runtime performance cost."
  },
  {
    "id": 62,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Index Signatures",
    "question": "What is an 'Index Signature' in TypeScript?",
    "code_snippet": null,
    "options": ["A way to sort object keys alphabetically", "A way to define an object where the exact property names are not known in advance, but the type of the values is known", "A method to index into an array", "A deprecated feature for dictionaries"],
    "correct_answer": "A way to define an object where the exact property names are not known in advance, but the type of the values is known",
    "explanation": "If you are building a dictionary or a cache where the keys are dynamic (like user IDs), but you know every value will be a `number`, you use an index signature to tell TypeScript this rule."
  },
  {
    "id": 63,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Index Signatures",
    "question": "Fill in the blank to correctly define an object that accepts any string key, provided the values are numbers.",
    "code_snippet": "interface Scores {\n  [key: _______]: number;\n}",
    "options": ["string", "any", "key", "index"],
    "correct_answer": "string",
    "explanation": "The syntax `[key: string]: number` reads as: 'For any property name (key) that is a string, the value must be a number.' You can also use `number` or `symbol` as the key type."
  },
  {
    "id": 64,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Specific + Index Signatures",
    "question": "If you have an index signature `[key: string]: number`, can you also have a specific property `name: string` in the same interface?",
    "code_snippet": null,
    "options": ["Yes, without any issues", "No, TypeScript will throw an error because the specific property's type (`string`) must be assignable to the index signature's type (`number`)", "Yes, but only if you use the `&` operator", "No, index signatures must be the only properties in the object"],
    "correct_answer": "No, TypeScript will throw an error because the specific property's type (`string`) must be assignable to the index signature's type (`number`)",
    "explanation": "TypeScript enforces that ALL properties in the object must match the index signature's value type. If the signature says 'all values are numbers', you cannot sneak in a `name: string` property."
  },
  {
    "id": 65,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "exactOptionalPropertyTypes",
    "question": "What does the `exactOptionalPropertyTypes` compiler flag do?",
    "code_snippet": null,
    "options": ["It forces all properties to be required", "It distinguishes between a property being completely missing vs. a property explicitly set to `undefined`", "It removes all optional properties", "It makes all strings exact literal types"],
    "correct_answer": "It distinguishes between a property being completely missing vs. a property explicitly set to `undefined`",
    "explanation": "By default, TS allows you to set an optional property to `undefined`. With this strict flag enabled, `nickname?: string` means the key can be omitted, but if it IS present, it MUST be a string (not `undefined`)."
  },
  {
    "id": 66,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Missing Required Property",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "interface User { name: string; age: number; }\nlet user: User = { name: 'Alice' };",
    "options": ["It compiles successfully", "It throws a compile-time Error: Property 'age' is missing in type '{ name: string; }' but required in type 'User'", "It throws an error because 'Alice' is not a number", "It compiles but age is undefined at runtime"],
    "correct_answer": "It throws a compile-time Error: Property 'age' is missing in type '{ name: string; }' but required in type 'User'",
    "explanation": "Because `age` is not marked with a `?`, it is strictly required. The compiler performs 'excess property checking' and 'missing property checking' to ensure the object perfectly matches the interface."
  },
  {
    "id": 67,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Readonly Assignment Error",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "interface Config { readonly port: number; }\nlet config: Config = { port: 3000 };\nconfig.port = 4000;",
    "options": ["It compiles successfully", "It throws a compile-time Error: Cannot assign to 'port' because it is a read-only property", "It throws an error because 4000 is not a number", "The port is updated to 4000 at runtime"],
    "correct_answer": "It throws a compile-time Error: Cannot assign to 'port' because it is a read-only property",
    "explanation": "The `readonly` modifier strictly prevents reassignment. If you need to change the port, you must create a brand new `Config` object with the new value, preserving the immutability of the original."
  },
  {
    "id": 68,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Structural Typing",
    "question": "TypeScript uses 'structural typing' (often called Duck Typing) for objects. What does this mean?",
    "code_snippet": null,
    "options": ["Objects must have the exact same interface name to be compatible", "If an object has all the required properties of a type, it is considered compatible with that type, regardless of its explicit name or declaration", "Objects are compared by their memory address", "TypeScript requires explicit casting for all objects"],
    "correct_answer": "If an object has all the required properties of a type, it is considered compatible with that type, regardless of its explicit name or declaration",
    "explanation": "If it walks like a duck and quacks like a duck, TS treats it like a duck. You don't need to explicitly say `implements User`. If your anonymous object has a `name` and `age`, TS accepts it as a `User`."
  },
  {
    "id": 69,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Object Type Inference",
    "question": "If you declare `const config = { theme: 'dark', version: 1 };`, what is the inferred type of `config`?",
    "code_snippet": null,
    "options": ["{ theme: string, version: number }", "{ theme: 'dark', version: 1 }", "any", "Record<string, any>"],
    "correct_answer": "{ theme: string, version: number }",
    "explanation": "Because `config` is declared with `const` (the reference can't change) but the properties inside could theoretically be mutated, TS widens the literal values to their base primitive types: `string` and `number`."
  },
  {
    "id": 70,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Module Wrap-up",
    "question": "Why are Interfaces and Type Aliases considered the backbone of TypeScript application architecture?",
    "code_snippet": null,
    "options": ["They make the compiled JavaScript run faster", "They allow you to define strict contracts for your data, ensuring that components, functions, and APIs communicate with exactly the expected shape of information", "They are required to compile to JavaScript", "They replace the need for classes entirely"],
    "correct_answer": "They allow you to define strict contracts for your data, ensuring that components, functions, and APIs communicate with exactly the expected shape of information",
    "explanation": "By defining clear shapes for your data, you create a self-documenting codebase. Any developer (or your IDE) can instantly see what data a function expects and what it returns, eliminating entire categories of runtime bugs."
  }
]
[
  {
    "id": 71,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "keyof Operator",
    "question": "What does the `keyof` operator do in TypeScript?",
    "code_snippet": null,
    "options": ["It returns the values of an object", "It creates a union type of all the public property names (keys) of a given type", "It converts an object to an array", "It deletes keys from an object"],
    "correct_answer": "It creates a union type of all the public property names (keys) of a given type",
    "explanation": "If you have an interface `User { name: string, age: number }`, `keyof User` evaluates to the union type `'name' | 'age'`. It is the foundation for creating dynamic, type-safe utility types."
  },
  {
    "id": 72,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "keyof Syntax",
    "question": "Fill in the blank to correctly extract the keys of the `User` interface as a union type.",
    "code_snippet": "interface User { name: string; age: number; }\ntype UserKeys = _______ User;",
    "options": ["keys", "keyof", "extract", "typeof"],
    "correct_answer": "keyof",
    "explanation": "The `keyof` keyword takes an object type and produces a string or numeric literal union of its keys."
  },
  {
    "id": 73,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "keyof with Index Signatures",
    "question": "What is the resulting type of `keyof` when applied to an object with a string index signature like `{ [key: string]: number }`?",
    "code_snippet": null,
    "options": ["string", "number", "string | number", "any"],
    "correct_answer": "string | number",
    "explanation": "In JavaScript, object keys are technically always strings or symbols, but when you access an object with a number (e.g., `obj[0]`), it coerces it to a string. TypeScript reflects this by returning `string | number` for `keyof` on a string index signature."
  },
  {
    "id": 74,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "The 'in' Operator (Type Narrowing)",
    "question": "How does the `in` operator help with type narrowing when dealing with a union of different object types?",
    "code_snippet": null,
    "options": ["It checks if a property is undefined", "It checks if a specific property key exists in the object, narrowing the union to the type that contains that property", "It iterates over the object", "It converts the object to an array"],
    "correct_answer": "It checks if a specific property key exists in the object, narrowing the union to the type that contains that property",
    "explanation": "The `in` operator is a 'discriminant' check. If you have a union of `Fish | Bird`, checking `if ('swim' in animal)` tells TypeScript that inside that block, `animal` MUST be the `Fish` type."
  },
  {
    "id": 75,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "The 'in' Operator (Output Prediction)",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "type Fish = { swim: () => void };\ntype Bird = { fly: () => void };\nfunction move(animal: Fish | Bird) {\n  if ('swim' in animal) {\n    animal.swim();\n  }\n}",
    "options": ["It throws an error because 'swim' is not a string", "It compiles successfully, narrowing `animal` to `Fish` inside the if block", "It throws an error because `animal` is a union", "It compiles but crashes at runtime"],
    "correct_answer": "It compiles successfully, narrowing `animal` to `Fish` inside the if block",
    "explanation": "Because only the `Fish` type has a `swim` property, TypeScript safely narrows the union down to `Fish` inside the `if` block, allowing you to call `.swim()` without errors."
  },
  {
    "id": 76,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Mapped Types Basics",
    "question": "What is a 'Mapped Type' in TypeScript?",
    "code_snippet": null,
    "options": ["A type that maps strings to numbers", "A way to create a new type by iterating over the keys of an existing type and transforming their property types", "A type used for React components", "A deprecated feature"],
    "correct_answer": "A way to create a new type by iterating over the keys of an existing type and transforming their property types",
    "explanation": "Mapped types are like `map()` for types. They allow you to take an existing type and transform every single property in it (e.g., making them all optional, or all readonly) in a single line of code."
  },
  {
    "id": 77,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Mapped Types Syntax",
    "question": "Fill in the blank to correctly create a mapped type that makes all properties of `T` optional.",
    "code_snippet": "type MyPartial<T> = {\n  [K in _______]?: T[K];\n};",
    "options": ["T", "keyof T", "keys of T", "Object.keys(T)"],
    "correct_answer": "keyof T",
    "explanation": "The syntax `[K in keyof T]` reads as: 'For every key `K` that exists in the keys of `T`'. The `?` makes it optional, and `T[K]` (a Lookup Type) grabs the original type of that specific property."
  },
  {
    "id": 78,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Partial<T> Utility Type",
    "question": "What does the built-in `Partial<T>` utility type do?",
    "code_snippet": null,
    "options": ["Makes all properties of `T` required", "Makes all properties of `T` optional", "Makes all properties of `T` readonly", "Removes all properties of `T`"],
    "correct_answer": "Makes all properties of `T` optional",
    "explanation": "`Partial<T>` is incredibly useful for update functions. If you have a `User` object, `Partial<User>` allows you to pass an object with just `{ age: 31 }` to update only the age, without requiring the `name` or `email`."
  },
  {
    "id": 79,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Partial<T> Usage",
    "question": "Fill in the blank to correctly use `Partial` to allow updating only specific fields of a `User` object.",
    "code_snippet": "function updateUser(id: number, updates: _______<User>) {\n  // updates can contain any subset of User properties\n}",
    "options": ["Optional", "Partial", "Maybe", "Some"],
    "correct_answer": "Partial",
    "explanation": "By typing the `updates` parameter as `Partial<User>`, you tell TypeScript, 'Expect an object that looks like a User, but every property is now optional.'"
  },
  {
    "id": 80,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Required<T> Utility Type",
    "question": "What does the built-in `Required<T>` utility type do?",
    "code_snippet": null,
    "options": ["Makes all optional properties of `T` required", "Makes all properties of `T` readonly", "Removes all properties of `T`", "Converts `T` to a primitive"],
    "correct_answer": "Makes all optional properties of `T` required",
    "explanation": "`Required<T>` is the exact opposite of `Partial<T>`. It takes an interface where some properties are optional (`?`) and forces them all to be strictly required."
  },
  {
    "id": 81,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Readonly<T> Utility Type",
    "question": "What does the built-in `Readonly<T>` utility type do?",
    "code_snippet": null,
    "options": ["Makes all properties of `T` optional", "Makes all properties of `T` readonly, preventing reassignment", "Converts `T` to a string", "Deletes `T` from memory"],
    "correct_answer": "Makes all properties of `T` readonly, preventing reassignment",
    "explanation": "`Readonly<T>` takes an existing interface and adds the `readonly` modifier to every single property, ensuring the object cannot be mutated after creation."
  },
  {
    "id": 82,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Shallow vs Deep Readonly",
    "question": "What is a major limitation of the built-in `Readonly<T>` utility type?",
    "code_snippet": null,
    "options": ["It only works on arrays", "It is 'shallow'—it only makes the top-level properties readonly, but nested objects can still be mutated", "It makes the entire object immutable at runtime", "It prevents the object from being logged to the console"],
    "correct_answer": "It is 'shallow'—it only makes the top-level properties readonly, but nested objects can still be mutated",
    "explanation": "If `User` has a nested `address: { city: string }` object, `Readonly<User>` prevents you from reassigning `address`, but it DOES NOT prevent you from doing `user.address.city = 'New York'`. To fix this, you need a custom 'DeepReadonly' mapped type."
  },
  {
    "id": 83,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Pick<T, K> Utility Type",
    "question": "What does the built-in `Pick<T, K>` utility type do?",
    "code_snippet": null,
    "options": ["Removes properties from `T`", "Creates a new type by selecting a specific set of properties `K` from `T`", "Makes all properties optional", "Combines two types"],
    "correct_answer": "Creates a new type by selecting a specific set of properties `K` from `T`",
    "explanation": "`Pick` allows you to create a subset of an existing type. If you have a massive `User` interface but a specific component only needs the `id` and `name`, you can `Pick<User, 'id' | 'name'>`."
  },
  {
    "id": 84,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Pick<T, K> Syntax",
    "question": "Fill in the blank to correctly create a type that only includes the `name` and `email` properties from the `User` interface.",
    "code_snippet": "type UserPreview = _______<User, 'name' | 'email'>;",
    "options": ["Select", "Pick", "Extract", "Omit"],
    "correct_answer": "Pick",
    "explanation": "The second argument to `Pick` must be a union of literal strings that exactly match the keys of the original type `T`."
  },
  {
    "id": 85,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Omit<T, K> Utility Type",
    "question": "What does the built-in `Omit<T, K>` utility type do?",
    "code_snippet": null,
    "options": ["Selects specific properties from `T`", "Creates a new type by excluding a specific set of properties `K` from `T`", "Makes all properties optional", "Converts `T` to an array"],
    "correct_answer": "Creates a new type by excluding a specific set of properties `K` from `T`",
    "explanation": "`Omit` is the exact opposite of `Pick`. It takes the original type and removes the specified keys. It is perfect for creating 'safe' versions of objects, like stripping out a `password` field before sending data to the client."
  },
  {
    "id": 86,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Omit<T, K> Syntax",
    "question": "Fill in the blank to correctly create a type that includes all properties of `User` EXCEPT `password`.",
    "code_snippet": "type SafeUser = _______<User, 'password'>;",
    "options": ["Pick", "Exclude", "Omit", "Remove"],
    "correct_answer": "Omit",
    "explanation": "`Omit<User, 'password'>` creates a new type that has every property of `User` except `password`. It is heavily used in API responses to ensure sensitive data is never accidentally typed or exposed."
  },
  {
    "id": 87,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Record<K, T> vs Index Signatures",
    "question": "How does `Record<K, T>` differ from a standard index signature like `[key: string]: T`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`Record` allows you to specify an exact union of literal keys (e.g., `Record<'a' | 'b', number>`), whereas index signatures only accept broad types like `string` or `number`", "`Record` is for arrays, index signatures are for objects", "`Record` is deprecated"],
    "correct_answer": "`Record` allows you to specify an exact union of literal keys (e.g., `Record<'a' | 'b', number>`), whereas index signatures only accept broad types like `string` or `number`",
    "explanation": "If you want an object that MUST have exactly the keys 'theme' and 'language', and both must be strings, you use `Record<'theme' | 'language', string>`. An index signature would allow ANY random string key."
  },
  {
    "id": 88,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Combining Pick and Omit",
    "question": "What will be the resulting type of `type Result = Omit<Pick<User, 'name' | 'age' | 'email'>, 'email'>;`?",
    "code_snippet": null,
    "options": ["{ name: string, age: number, email: string }", "{ name: string, age: number }", "{ email: string }", "Error"],
    "correct_answer": "{ name: string, age: number }",
    "explanation": "First, `Pick` extracts the three properties. Then, `Omit` removes 'email' from that newly created subset. The final type only contains 'name' and 'age'. Utility types can be chained infinitely!"
  },
  {
    "id": 89,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Utility Types and Interfaces",
    "question": "Can you use utility types like `Partial<T>` or `Pick<T, K>` directly in an `interface` declaration (e.g., `interface MyInterface extends Partial<User>`)?",
    "code_snippet": null,
    "options": ["Yes, interfaces can extend utility types", "No, interfaces can only extend other interfaces or object types; to use utility types, you must use a `type` alias", "Yes, but only with `Pick`", "No, utility types cannot be used with interfaces at all"],
    "correct_answer": "No, interfaces can only extend other interfaces or object types; to use utility types, you must use a `type` alias",
    "explanation": "This is a very common TS gotcha! Interfaces cannot extend mapped types or utility types like `Partial`. If you need to use a utility type, you must define it using the `type` keyword: `type MyType = Partial<User>;`."
  },
  {
    "id": 90,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Module Wrap-up",
    "question": "You've now mastered Object Shapes, Interfaces, Aliases, and Utility Types. What is the ultimate benefit of using these features in a large codebase?",
    "code_snippet": null,
    "options": ["It makes the JavaScript file size smaller", "It allows you to transform, filter, and reshape complex data structures at compile-time, ensuring that data flows through your application with absolute type safety and zero runtime overhead", "It automatically fixes runtime bugs", "It replaces the need for a database"],
    "correct_answer": "It allows you to transform, filter, and reshape complex data structures at compile-time, ensuring that data flows through your application with absolute type safety and zero runtime overhead",
    "explanation": "Utility types like `Pick`, `Omit`, and `Partial` are completely erased during compilation. They provide massive architectural safety and developer experience (IDE autocomplete) without adding a single byte to your final production JavaScript bundle."
  }
]
[
  {
    "id": 91,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Advanced Intersections (Conflicting Types)",
    "question": "What happens if you intersect two types with conflicting property types, like `{ a: string } & { a: number }`?",
    "code_snippet": null,
    "options": ["It throws a compile-time error immediately", "The property `a` becomes the type `never`, making it impossible to satisfy", "It defaults to `any`", "It creates a union `string | number`"],
    "correct_answer": "The property `a` becomes the type `never`, making it impossible to satisfy",
    "explanation": "TypeScript calculates intersections mathematically. The intersection of `string` and `number` is `never` (a value that cannot exist). Therefore, you can never create an object that satisfies `{ a: string } & { a: number }`."
  },
  {
    "id": 92,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Advanced Intersections (Functions)",
    "question": "What happens when you intersect two function types with different parameters?",
    "code_snippet": null,
    "options": ["It throws an error", "It creates an overloaded function type that can be called with either signature", "It merges the parameters into a single required object", "It cancels them out to `never`"],
    "correct_answer": "It creates an overloaded function type that can be called with either signature",
    "explanation": "Intersecting functions is how TypeScript models function overloads. `type Func = ((a: string) => void) & ((a: number) => void)` means the function can be called with EITHER a string OR a number."
  },
  {
    "id": 93,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Discriminated Unions (Concept)",
    "question": "What is a 'Discriminated Union' (or Tagged Union) in TypeScript?",
    "code_snippet": null,
    "options": ["A union of primitive types", "A union of object types that all share a common, literal property (the discriminant) used to safely narrow the type", "An array of mixed types", "A deprecated feature"],
    "correct_answer": "A union of object types that all share a common, literal property (the discriminant) used to safely narrow the type",
    "explanation": "Discriminated Unions are the absolute best way to model complex states (like API responses: 'loading' | 'success' | 'error'). The shared literal property acts as a 'tag' that tells TypeScript exactly which object shape you are dealing with."
  },
  {
    "id": 94,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Discriminated Unions (Syntax)",
    "question": "Fill in the blank to correctly define a Discriminated Union for API states.",
    "code_snippet": "type ApiResponse = \n  | { status: 'loading' }\n  | { status: 'success', data: string }\n  | { status: 'error', _______: Error };",
    "options": ["message", "error", "code", "reason"],
    "correct_answer": "error",
    "explanation": "The `status` property is the 'discriminant'. When you check `if (response.status === 'error')`, TypeScript knows with 100% certainty that the `error` property exists on the object."
  },
  {
    "id": 95,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Discriminated Unions (Switch Narrowing)",
    "question": "How does TypeScript narrow a Discriminated Union inside a `switch` statement?",
    "code_snippet": null,
    "options": ["It doesn't, you must use type assertions", "By checking the discriminant property in each `case` block, TS automatically narrows the type to the specific object shape for that block", "It narrows it to `any`", "It requires a custom type guard"],
    "correct_answer": "By checking the discriminant property in each `case` block, TS automatically narrows the type to the specific object shape for that block",
    "explanation": "If you write `switch(response.status)`, TS knows that inside `case 'success':`, the `response` variable is strictly the `{ status: 'success', data: string }` shape. You can safely access `.data` without errors."
  },
  {
    "id": 96,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Exhaustiveness Checking",
    "question": "How do you ensure a `switch` statement handles ALL possible cases of a Discriminated Union?",
    "code_snippet": null,
    "options": ["Add a `default: break;` case", "Assign the switched variable to a variable of type `never` in the `default` case. If a new case is added to the union later and not handled, TS throws an error", "Use an `if/else` chain instead", "You cannot guarantee exhaustiveness in TS"],
    "correct_answer": "Assign the switched variable to a variable of type `never` in the `default` case. If a new case is added to the union later and not handled, TS throws an error",
    "explanation": "This is called 'Exhaustiveness Checking'. Because `never` can only hold a value that doesn't exist, if you forget to handle a new state (like 'pending'), TS will say: 'Type pending is not assignable to type never', forcing you to update your switch statement."
  },
  {
    "id": 97,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Custom Type Guards (Concept)",
    "question": "What is a 'Custom Type Guard' in TypeScript?",
    "code_snippet": null,
    "options": ["A CSS class that hides elements", "A function that returns a boolean and uses a special return type syntax (`param is Type`) to tell the compiler to narrow the type of the parameter", "A JavaScript `try/catch` block", "A way to prevent null values"],
    "correct_answer": "A function that returns a boolean and uses a special return type syntax (`param is Type`) to tell the compiler to narrow the type of the parameter",
    "explanation": "Custom type guards allow you to encapsulate complex type-checking logic (like checking for multiple specific object properties) into a reusable function that TypeScript's control flow analysis understands."
  },
  {
    "id": 98,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Custom Type Guards (Syntax)",
    "question": "Fill in the blank to correctly define a custom type guard function that checks if a value is a string.",
    "code_snippet": "function isString(val: unknown): val _______ string {\n  return typeof val === 'string';\n}",
    "options": ["as", "is", "equals", "type"],
    "correct_answer": "is",
    "explanation": "The `val is string` syntax is called a 'Type Predicate'. It tells the compiler, 'If this function returns true, you can safely treat `val` as a `string` from this point forward.'"
  },
  {
    "id": 99,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Custom Type Guards (Complex Logic)",
    "question": "Why are custom type guards useful compared to just using `typeof` or `instanceof` inline?",
    "code_snippet": null,
    "options": ["They run faster at runtime", "They allow you to encapsulate complex, multi-step type checking logic (like checking for specific object properties) into a reusable function that TS understands", "They prevent runtime errors entirely", "They are required for all interfaces"],
    "correct_answer": "They allow you to encapsulate complex, multi-step type checking logic (like checking for specific object properties) into a reusable function that TS understands",
    "explanation": "Instead of writing `if ('swim' in animal && typeof animal.swim === 'function')` everywhere, you write `if (isFish(animal))`. It keeps your code clean, DRY, and perfectly type-safe."
  },
  {
    "id": 100,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Assertion Functions (Concept)",
    "question": "What is an 'Assertion Function' in TypeScript?",
    "code_snippet": null,
    "options": ["A function that returns a boolean", "A function that throws an error if a condition is not met, and uses the `asserts` keyword to tell TS that if the function returns, the narrowed type is guaranteed", "A function that converts types", "A deprecated feature"],
    "correct_answer": "A function that throws an error if a condition is not met, and uses the `asserts` keyword to tell TS that if the function returns, the narrowed type is guaranteed",
    "explanation": "Assertion functions are perfect for validation logic. If `assertIsString(val)` doesn't throw an error, TypeScript knows that any code executing on the next line can safely treat `val` as a string."
  },
  {
    "id": 101,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Assertion Functions (Syntax)",
    "question": "Fill in the blank to correctly define an assertion function that guarantees `val` is a string if it doesn't throw.",
    "code_snippet": "function assertIsString(val: unknown): _______ val is string {\n  if (typeof val !== 'string') throw new Error('Not a string!');\n}",
    "options": ["returns", "asserts", "guarantees", "is"],
    "correct_answer": "asserts",
    "explanation": "The `asserts` keyword modifies the return type. It tells the compiler, 'This function returns `void`, but as a side-effect, it guarantees that `val` is a `string` if execution continues past this call.'"
  },
  {
    "id": 102,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "The 'satisfies' Operator (Concept)",
    "question": "What does the `satisfies` operator (introduced in TS 4.9) do?",
    "code_snippet": null,
    "options": ["It converts an object to a different type", "It validates that an expression matches a type without altering the resulting inferred type of the expression", "It makes all properties readonly", "It is an alias for `instanceof`"],
    "correct_answer": "It validates that an expression matches a type without altering the resulting inferred type of the expression",
    "explanation": "`satisfies` is the perfect middle-ground. It checks that your object is compatible with a broad type (like `Record<string, string>`), but it keeps the exact, narrow literal types of the properties you actually wrote."
  },
  {
    "id": 103,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "The 'satisfies' Operator (vs Explicit Typing)",
    "question": "How does `satisfies` differ from explicitly typing a variable (e.g., `const x: Type = ...`)?",
    "code_snippet": null,
    "options": ["There is no difference", "Explicit typing widens the type to `Type`, losing literal inference. `satisfies` checks against `Type` but keeps the exact, narrow inferred literal type", "`satisfies` is slower", "Explicit typing is deprecated"],
    "correct_answer": "Explicit typing widens the type to `Type`, losing literal inference. `satisfies` checks against `Type` but keeps the exact, narrow inferred literal type",
    "explanation": "If you write `const x: Record<string, string> = { red: 'crimson' }`, the type of `x.red` is just `string`. If you write `const x = { red: 'crimson' } satisfies Record<string, string>`, the type of `x.red` is the exact literal `'crimson'`."
  },
  {
    "id": 104,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "The 'satisfies' Operator (Output Prediction)",
    "question": "What is the exact inferred type of `palette.red` in the following code?",
    "code_snippet": "const palette = { red: 'crimson', blue: 'navy' } satisfies Record<string, string>;",
    "options": ["string", "The literal type 'crimson'", "Record<string, string>", "any"],
    "correct_answer": "The literal type 'crimson'",
    "explanation": "Because `satisfies` does not widen the type of the expression, TypeScript remembers that `red` was specifically assigned the literal string `'crimson'`, giving you perfect autocomplete and strictness."
  },
  {
    "id": 105,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Intersection of Unions",
    "question": "What is the resulting type of `('a' | 'b') & ('a' | 'c')`?",
    "code_snippet": null,
    "options": ["'a' | 'b' | 'c'", "'a'", "never", "'b' | 'c'"],
    "correct_answer": "'a'",
    "explanation": "The intersection of two unions is the intersection of their members. The only literal that exists in BOTH the first union and the second union is `'a'`."
  },
  {
    "id": 106,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Object Type Intersection (Requirements)",
    "question": "If you intersect `{ a: string } & { b: number }`, what properties must an object have to be assignable to this type?",
    "code_snippet": null,
    "options": ["Either `a` or `b`", "It must have BOTH `a` (string) AND `b` (number)", "It must have `a` and `b`, but they can be any type", "It must have neither"],
    "correct_answer": "It must have BOTH `a` (string) AND `b` (number)",
    "explanation": "An intersection (`&`) means 'AND'. The object must satisfy the requirements of the first type AND the requirements of the second type simultaneously."
  },
  {
    "id": 107,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Type Guards (instanceof)",
    "question": "What does the `instanceof` operator do for type narrowing?",
    "code_snippet": null,
    "options": ["It checks if a property exists", "It checks if an object's prototype chain includes a specific class constructor, narrowing the type to that class or its subclasses", "It converts an object to a class", "It throws an error if the object is null"],
    "correct_answer": "It checks if an object's prototype chain includes a specific class constructor, narrowing the type to that class or its subclasses",
    "explanation": "If you have `function process(val: Date | string)`, you can write `if (val instanceof Date)`. Inside that block, TS knows `val` is strictly a `Date` object and allows you to call `.getFullYear()`."
  },
  {
    "id": 108,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Type Guards (Equality Narrowing)",
    "question": "How does TypeScript narrow types when you use strict equality (`===`) to compare a union type to a literal?",
    "code_snippet": null,
    "options": ["It doesn't narrow types based on equality", "It narrows the union to the specific type or literal that matches the comparison, and excludes it in the `else` block", "It converts the union to `any`", "It throws an error"],
    "correct_answer": "It narrows the union to the specific type or literal that matches the comparison, and excludes it in the `else` block",
    "explanation": "If `let x: string | number`, and you write `if (x === 'hello')`, TS knows that inside the `if`, `x` is the literal `'hello'`. In the `else` block, TS knows `x` is `string | number` MINUS `'hello'`."
  },
  {
    "id": 109,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Discriminated Unions (Array Filtering)",
    "question": "How do you correctly filter an array of a Discriminated Union to extract only the items of a specific variant?",
    "code_snippet": null,
    "options": ["Use `.filter(item => item.type === 'success')`", "Use `.filter((item): item is Success => item.type === 'success')`", "Use `.map(item => item as Success)`", "Use `.reduce()`"],
    "correct_answer": "Use `.filter((item): item is Success => item.type === 'success')",
    "explanation": "Standard `.filter()` returns the same array type. By adding the `item is Success` type predicate to the callback, you tell TypeScript that the resulting array should be strictly typed as `Success[]`."
  },
  {
    "id": 110,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Module Wrap-up (Philosophy)",
    "question": "What is the core philosophy behind Discriminated Unions, Type Guards, and the `satisfies` operator?",
    "code_snippet": null,
    "options": ["To make the code run faster", "They allow you to model complex, mutually exclusive states in your application and let the TypeScript compiler mathematically prove that you have handled every possible state safely", "To replace the need for interfaces", "To automatically fix runtime bugs"],
    "correct_answer": "They allow you to model complex, mutually exclusive states in your application and let the TypeScript compiler mathematically prove that you have handled every possible state safely",
    "explanation": "These features transform TypeScript from a simple 'syntax checker' into a powerful theorem prover for your data. If it compiles, you have mathematical certainty that your logic handles every possible shape of data correctly."
  }
]
[
  {
    "id": 111,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Optional Chaining (?.)",
    "question": "What does the optional chaining operator (`?.`) do when accessing deeply nested object properties?",
    "code_snippet": null,
    "options": ["It throws an error if the property is missing", "It short-circuits and returns `undefined` immediately if it encounters a `null` or `undefined` value in the chain, preventing runtime crashes", "It converts the value to an empty string", "It creates the missing properties automatically"],
    "correct_answer": "It short-circuits and returns `undefined` immediately if it encounters a `null` or `undefined` value in the chain, preventing runtime crashes",
    "explanation": "Instead of writing `user && user.address && user.address.city`, you can simply write `user?.address?.city`. If `user` or `address` is null/undefined, the expression evaluates to `undefined` safely."
  },
  {
    "id": 112,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Optional Chaining (Type Inference)",
    "question": "Given `interface User { address?: { city: string } }`, what is the exact inferred type of `user?.address?.city`?",
    "code_snippet": null,
    "options": ["string", "string | null", "string | undefined", "any"],
    "correct_answer": "string | undefined",
    "explanation": "Because the `?.` operator short-circuits to `undefined` (not `null`) when a property is missing, TypeScript automatically appends `| undefined` to the resulting type. You must handle the `undefined` case before using it as a pure `string`."
  },
  {
    "id": 113,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Nullish Coalescing (??)",
    "question": "How does the nullish coalescing operator (`??`) differ from the logical OR (`||`) when providing fallback values for object properties?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`??` only falls back if the value is strictly `null` or `undefined`; `||` falls back on ANY falsy value (like `0`, `''`, or `false`)", "`||` is for strings, `??` is for numbers", "`??` is deprecated"],
    "correct_answer": "`??` only falls back if the value is strictly `null` or `undefined`; `||` falls back on ANY falsy value (like `0`, `''`, or `false`)",
    "explanation": "If you have `user.age || 18`, and the user's age is actually `0`, it will incorrectly fallback to `18`. Using `user.age ?? 18` correctly preserves the `0` because `0` is not null/undefined."
  },
  {
    "id": 114,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Deeply Nested Optional Types",
    "question": "If you have a deeply nested interface where every level is optional, what is the cleanest way to type a function parameter that accepts a partial version of it?",
    "code_snippet": null,
    "options": ["Rewrite the entire interface manually with `?` on every property", "Use a recursive 'DeepPartial<T>' mapped type utility", "Use the `any` type", "Use the `Partial<T>` utility type, which automatically applies recursively to all nested levels"],
    "correct_answer": "Use a recursive 'DeepPartial<T>' mapped type utility",
    "explanation": "The built-in `Partial<T>` is shallow; it only makes the top-level properties optional. To make deeply nested objects optional, you must define a custom recursive mapped type: `type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P] }`."
  },
  {
    "id": 115,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "topic": "Optional Method Calls",
    "question": "Fill in the blank to safely call a method on an object only if the method exists.",
    "code_snippet": "let callback: (() => void) | undefined = getCallback();\ncallback_______();",
    "options": ["?.", "??", "!.", "&."],
    "correct_answer": "?.",
    "explanation": "Optional chaining works on functions too! `callback?.()` will only execute the function if `callback` is not `null` or `undefined`. If it is undefined, the expression simply evaluates to `undefined` without throwing a 'not a function' error."
  },
  {
    "id": 116,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "The Polymorphic 'this' Type",
    "question": "What is the polymorphic `this` type in TypeScript?",
    "code_snippet": null,
    "options": ["A reference to the global window object", "A special type that represents the containing class or interface, allowing methods to return the exact subclass type for fluent method chaining", "A type that means the object is immutable", "A deprecated alias for `any`"],
    "correct_answer": "A special type that represents the containing class or interface, allowing methods to return the exact subclass type for fluent method chaining",
    "explanation": "If a base class `Animal` has a method `eat(): this`, and a subclass `Dog` extends it, calling `dog.eat()` returns a `Dog`, not an `Animal`. This preserves the subclass type through the chain."
  },
  {
    "id": 117,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly type a method so that it returns the exact instance type for method chaining.",
    "code_snippet": "class Builder {\n  setName(name: string): _______ {\n    this.name = name;\n    return this;\n  }\n}",
    "options": ["Builder", "this", "self", "instance"],
    "correct_answer": "this",
    "explanation": "Returning `this` instead of the class name (`Builder`) ensures that if another class extends `Builder`, the chained methods will correctly resolve to the child class's type, not the base class."
  },
  {
    "id": 118,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "'this' Type Guards",
    "question": "How can you use the `this` keyword to create a custom type guard for a class?",
    "code_snippet": null,
    "options": ["return this is Admin;", "return typeof this === 'Admin';", "this instanceof Admin;", "return this as Admin;"],
    "correct_answer": "return this is Admin;",
    "explanation": "You can write a method like `isAdmin(): this is Admin`. If this method returns `true`, TypeScript narrows the type of the object instance to `Admin` for the rest of the code block."
  },
  {
    "id": 119,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Declaration Merging (Concept)",
    "question": "What is 'Declaration Merging' in TypeScript?",
    "code_snippet": null,
    "options": ["Combining two variables into one", "When the TypeScript compiler automatically merges multiple `interface` declarations with the same name into a single, unified interface", "Merging two JavaScript files", "A deprecated feature for classes"],
    "correct_answer": "When the TypeScript compiler automatically merges multiple `interface` declarations with the same name into a single, unified interface",
    "explanation": "If you write `interface User { name: string }` and later `interface User { age: number }`, TypeScript merges them. The final `User` type requires BOTH `name` and `age`. This is impossible with `type` aliases."
  },
  {
    "id": 120,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Declaration Merging (Use Cases)",
    "question": "What is the most common real-world use case for Interface Declaration Merging?",
    "code_snippet": null,
    "options": ["Creating loops", "Extending global types (like adding custom properties to the `Window` object) or augmenting third-party libraries that don't have complete type definitions", "Merging CSS classes", "Combining arrays"],
    "correct_answer": "Extending global types (like adding custom properties to the `Window` object) or augmenting third-party libraries that don't have complete type definitions",
    "explanation": "If you attach a custom property to the global `window` object (e.g., `window.__MY_APP_CONFIG__), you can use declaration merging to tell TypeScript about it: `interface Window { __MY_APP_CONFIG__: Config }`."
  },
  {
    "id": 121,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Declaration Merging (Conflicts)",
    "question": "What happens if you try to merge two interfaces with the same name, but they define the same property with incompatible types?",
    "code_snippet": "interface User { id: string; }\ninterface User { id: number; }",
    "options": ["The second interface overwrites the first", "They merge into a union type `string | number`", "The TypeScript compiler throws an Error: Subsequent variable declarations must have the same type", "It defaults to `any`"],
    "correct_answer": "The TypeScript compiler throws an Error: Subsequent variable declarations must have the same type",
    "explanation": "Declaration merging only works if the properties are compatible. You cannot merge a `string` and a `number` into the same property name. TS will halt compilation and force you to fix the conflict."
  },
  {
    "id": 122,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Excess Property Checking (Concept)",
    "question": "What is 'Excess Property Checking' in TypeScript?",
    "code_snippet": null,
    "options": ["A linting rule that prevents long variable names", "A strict check that prevents you from passing object literals with extra, unknown properties to a function or variable expecting a specific type", "A method to delete unused properties", "A way to count the number of properties in an object"],
    "correct_answer": "A strict check that prevents you from passing object literals with extra, unknown properties to a function or variable expecting a specific type",
    "explanation": "Because of structural typing, an object with extra properties is technically compatible. But TS adds 'Excess Property Checking' specifically for object literals to catch typos (like passing `{ colour: 'red' }` instead of `{ color: 'red' }`)."
  },
  {
    "id": 123,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "output-prediction",
    "topic": "Excess Property Checking (Trigger)",
    "question": "When does TypeScript trigger Excess Property Checking?",
    "code_snippet": null,
    "options": ["Whenever an object is created", "Only when an object literal is passed directly to a function or assigned to a typed variable", "Only when using the `any` type", "It never triggers, it's just a warning"],
    "correct_answer": "Only when an object literal is passed directly to a function or assigned to a typed variable",
    "explanation": "If you assign the object to a variable first (`let obj = { a: 1, b: 2 }; let x: { a: number } = obj;`), TS does NOT trigger excess property checking, because `obj` might be used elsewhere where `b` is needed."
  },
  {
    "id": 124,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Bypassing Excess Property Checking",
    "question": "If you absolutely must pass an object literal with extra properties to a strictly typed function, how can you bypass Excess Property Checking?",
    "code_snippet": null,
    "options": ["Use the `any` type", "Use a type assertion (e.g., `as MyType`) or assign it to a broader variable first", "Use the `!` operator", "You cannot bypass it"],
    "correct_answer": "Use a type assertion (e.g., `as MyType`) or assign it to a broader variable first",
    "explanation": "Type assertions tell the compiler, 'I know what I'm doing, ignore the excess properties.' Alternatively, assigning the literal to a variable of a broader type (like `Record<string, any>`) bypasses the literal check."
  },
  {
    "id": 125,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "keyof on Classes",
    "question": "How does the `keyof` operator behave differently when applied to a `class` versus an `interface`?",
    "code_snippet": null,
    "options": ["It behaves exactly the same", "On a class, `keyof` includes the names of the class's METHODS as well as its properties; on an interface, it only includes properties", "`keyof` cannot be used on classes", "`keyof` only returns private properties on classes"],
    "correct_answer": "On a class, `keyof` includes the names of the class's METHODS as well as its properties; on an interface, it only includes properties",
    "explanation": "Classes in TS have methods attached to their prototype. Therefore, `keyof MyClass` will return a union of both property names AND method names. Interfaces only describe data shapes, so `keyof` only returns property names."
  },
  {
    "id": 126,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Index Signatures with Optional Properties",
    "question": "If an interface has an index signature `[key: string]: number`, can it also have an optional property like `count?: number`?",
    "code_snippet": null,
    "options": ["No, optional properties are forbidden with index signatures", "Yes, because the optional property's type (`number | undefined`) is compatible with the index signature's requirement that all string keys map to numbers (with strictNullChecks handled)", "Yes, but only if the index signature is `any`", "No, index signatures must be the only members"],
    "correct_answer": "Yes, because the optional property's type (`number | undefined`) is compatible with the index signature's requirement that all string keys map to numbers (with strictNullChecks handled)",
    "explanation": "TypeScript allows optional properties alongside index signatures, provided their types align. Since `count` is a number (or undefined), it doesn't violate the rule that 'any string key yields a number'."
  },
  {
    "id": 127,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Object Spread Operator (...)",
    "question": "When you use the object spread operator (`const newObj = { ...oldObj, newProp: 1 }`), how does TypeScript infer the type of `newObj`?",
    "code_snippet": null,
    "options": ["It remains exactly the same as `oldObj`", "It creates an intersection type of `oldObj` and `{ newProp: number }`, effectively adding the new property to the type", "It converts the object to `any`", "It throws an error"],
    "correct_answer": "It creates an intersection type of `oldObj` and `{ newProp: number }`, effectively adding the new property to the type",
    "explanation": "TypeScript understands the spread operator. If `oldObj` is `{ a: string }`, spreading it and adding `b: number` results in the type `{ a: string, b: number }`. It's fully type-safe."
  },
  {
    "id": 128,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Spread Operator (Overriding Types)",
    "question": "If you spread an object and override a property with a different type (e.g., `{ ...user, age: 'thirty' }` when `age` was originally a `number`), what does TypeScript do?",
    "code_snippet": null,
    "options": ["It throws a compile-time error because you cannot change property types via spread", "It updates the resulting type, changing the `age` property from `number` to `string` in the new object's type", "It defaults to `any`", "It keeps the original `number` type and ignores the new value"],
    "correct_answer": "It updates the resulting type, changing the `age` property from `number` to `string` in the new object's type",
    "explanation": "TypeScript's spread type inference processes properties left-to-right. If a later property overrides an earlier one, the final type reflects the overridden type. The resulting type is `{ ...Omit<User, 'age'>, age: string }`."
  },
  {
    "id": 129,
    "level": "intermediate",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Structural Typing (Empty Interfaces)",
    "question": "In TypeScript's structural typing system, what is the consequence of creating an empty interface (e.g., `interface Empty {}`)?",
    "code_snippet": null,
    "options": ["It throws an error", "It acts as a 'top type' for objects; literally ANY non-nullish object (like `{ a: 1 }` or a class instance) is assignable to it because they all have 'at least zero properties'", "It can only be assigned to other empty interfaces", "It is automatically converted to `null`"],
    "correct_answer": "It acts as a 'top type' for objects; literally ANY non-nullish object (like `{ a: 1 }` or a class instance) is assignable to it because they all have 'at least zero properties'",
    "explanation": "Because TS uses structural typing, if an interface requires nothing, then everything satisfies it. This is why the official TS documentation warns against empty interfaces, as they provide zero type safety."
  },
  {
    "id": 130,
    "level": "advanced",
    "module_id": "ts_mod_02_objects",
    "module_name": "Object Shapes, Interfaces & Aliases",
    "type": "conceptual",
    "topic": "Module 2 Wrap-up",
    "question": "You have now mastered Object Shapes, Interfaces, Aliases, Utility Types, and Advanced Narrowing. What is the ultimate hallmark of a TypeScript developer who has truly mastered this module?",
    "code_snippet": null,
    "options": ["They never use the `any` type", "They can look at any complex, nested API response and instantly model it using strict interfaces, discriminated unions, and utility types, ensuring the rest of the application is 100% type-safe", "They memorize all 50 built-in utility types", "They write TypeScript without using an IDE"],
    "correct_answer": "They can look at any complex, nested API response and instantly model it using strict interfaces, discriminated unions, and utility types, ensuring the rest of the application is 100% type-safe",
    "explanation": "Mastering object shapes means mastering the 'contract' of your application. If your data models are perfectly typed at the boundary (the API), the rest of your UI and logic practically type themselves."
  }
]
