[
  {
    "id": 131,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Basic Function Typing",
    "question": "Fill in the blank to correctly type the return value of this addition function.",
    "code_snippet": "function add(a: number, b: number) _______ number {\n  return a + b;\n}",
    "options": ["->", ":", "=>", "returns"],
    "correct_answer": ":",
    "explanation": "In TypeScript, function return types are annotated using a colon `:` after the parameter list, just like variable types. `->` is used in some other languages, but TS uses `:`."
  },
  {
    "id": 132,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Return Type Inference",
    "question": "If you don't explicitly annotate the return type of a function, what does TypeScript do?",
    "code_snippet": null,
    "options": ["It throws an error", "It automatically infers the return type based on the `return` statements inside the function body", "It defaults to `any`", "It defaults to `void`"],
    "correct_answer": "It automatically infers the return type based on the `return` statements inside the function body",
    "explanation": "TypeScript's inference engine is very smart. If you `return a + b` where `a` and `b` are numbers, TS infers the return type is `number`. However, explicitly typing returns is a best practice for public APIs to prevent accidental changes."
  },
  {
    "id": 133,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "The 'void' Return Type",
    "question": "What does the `void` return type signify in TypeScript?",
    "code_snippet": null,
    "options": ["The function returns `null`", "The function returns `undefined`", "The function does not return any meaningful value (often used for side-effects)", "The function returns an empty object"],
    "correct_answer": "The function does not return any meaningful value (often used for side-effects)",
    "explanation": "When a function performs an action (like `console.log` or updating the DOM) but doesn't `return` data, its return type is `void`. It tells the developer, 'Do not use the result of this function.'"
  },
  {
    "id": 134,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Optional Parameters",
    "question": "Fill in the blank to correctly mark the `middleName` parameter as optional.",
    "code_snippet": "function getFullName(firstName: string, middleName _______ string, lastName: string) {\n  // ...\n}",
    "options": ["?", ":", "| undefined", "optional"],
    "correct_answer": "?",
    "explanation": "Placing a `?` after the parameter name and before the `:` marks it as optional. The type of `middleName` inside the function becomes `string | undefined`."
  },
  {
    "id": 135,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Optional Parameters Order",
    "question": "Where must optional parameters be placed in a function's parameter list?",
    "code_snippet": null,
    "options": ["At the beginning", "Anywhere", "At the end, after all required parameters", "Before the rest parameters, but before required ones"],
    "correct_answer": "At the end, after all required parameters",
    "explanation": "Just like in JavaScript, optional parameters must come after required ones. If you put an optional param first, the caller wouldn't know which argument maps to which parameter."
  },
  {
    "id": 136,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Default Parameters",
    "question": "Fill in the blank to correctly set a default value for the `role` parameter.",
    "code_snippet": "function createUser(name: string, role: string _______ 'user') {\n  // ...\n}",
    "options": [":", "=", "?", "=>"],
    "correct_answer": "=",
    "explanation": "Default parameters use the standard JavaScript `=` syntax. TypeScript automatically infers that the parameter is optional and its type includes the default value's type."
  },
  {
    "id": 137,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "output-prediction",
    "topic": "Default Parameters Inference",
    "question": "What is the inferred type of the `timeout` parameter in this function?",
    "code_snippet": "function fetchData(url: string, timeout = 5000) { ... }",
    "options": ["number", "number | undefined", "5000 (literal type)", "any"],
    "correct_answer": "number",
    "explanation": "Because `timeout` has a default value, it is implicitly optional. However, because it's a binding that can be overridden by the caller, TS widens the literal `5000` to the base primitive type `number`."
  },
  {
    "id": 138,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Rest Parameters",
    "question": "Fill in the blank to correctly type a rest parameter that accepts any number of string arguments.",
    "code_snippet": "function logMessages(...messages: _______) {\n  messages.forEach(m => console.log(m));\n}",
    "options": ["string", "string[]", "...string", "array<string>"],
    "correct_answer": "string[]",
    "explanation": "The rest parameter syntax (`...`) gathers all remaining arguments into an array. Therefore, the type annotation must be an array type, like `string[]` or `Array<string>`."
  },
  {
    "id": 139,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Callback Function Types",
    "question": "Fill in the blank to correctly type a callback parameter that takes a number and returns a boolean.",
    "code_snippet": "function processNumber(num: number, callback: (val: number) _______ boolean) {\n  // ...\n}",
    "options": [":", "=>", "->", "returns"],
    "correct_answer": "=>",
    "explanation": "When defining a function type inline, the syntax is `(params) => ReturnType`. The `=>` separates the parameters from the return type."
  },
  {
    "id": 140,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Callback Type Aliases",
    "question": "Why is it considered a best practice to use a `type` alias for complex callback signatures instead of writing them inline?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It improves readability, allows reuse across multiple functions, and provides a clear name for the callback's purpose in IDE tooltips", "It is required by TypeScript", "It prevents memory leaks"],
    "correct_answer": "It improves readability, allows reuse across multiple functions, and provides a clear name for the callback's purpose in IDE tooltips",
    "explanation": "Instead of `(data: User, error: Error) => void` everywhere, you can define `type UserCallback = (data: User, error: Error) => void;`. This makes your code self-documenting."
  },
  {
    "id": 141,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Function Overloads (Concept)",
    "question": "What is the primary purpose of Function Overloads in TypeScript?",
    "code_snippet": null,
    "options": ["To make the function run faster", "To allow a single function to be called with different numbers or types of arguments, returning different types based on the input", "To create multiple functions with the same name in different files", "To prevent the function from being called recursively"],
    "correct_answer": "To allow a single function to be called with different numbers or types of arguments, returning different types based on the input",
    "explanation": "Unlike Union types (`string | number` -> `string | number`), overloads let you say: 'If input is string, return number. If input is number, return string.' It provides precise, correlated typing."
  },
  {
    "id": 142,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Function Overloads (Syntax)",
    "question": "How many 'signatures' does an overloaded function have in TypeScript?",
    "code_snippet": null,
    "options": ["Only one implementation signature", "One overload signature for every variation, plus exactly one implementation signature at the end", "Only overload signatures, no implementation", "Two implementation signatures"],
    "correct_answer": "One overload signature for every variation, plus exactly one implementation signature at the end",
    "explanation": "You write multiple 'overload signatures' (which the caller sees) followed by a single 'implementation signature' (which contains the actual logic and must be compatible with all overloads)."
  },
  {
    "id": 143,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Function Overloads (Order)",
    "question": "Why is the order of overload signatures important?",
    "code_snippet": null,
    "options": ["It doesn't matter", "TypeScript resolves overloads from top to bottom; the first matching signature is used, so more specific signatures must come before general ones", "The implementation must be first", "Alphabetical order is required"],
    "correct_answer": "TypeScript resolves overloads from top to bottom; the first matching signature is used, so more specific signatures must come before general ones",
    "explanation": "If you put a general signature (like `function parse(val: any): any`) at the top, it will match everything, and the specific signatures below it will never be reached."
  },
  {
    "id": 144,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Arrow Functions Typing",
    "question": "Fill in the blank to correctly type an arrow function variable that takes two numbers and returns a number.",
    "code_snippet": "const multiply: (a: number, b: number) _______ number = (a, b) => a * b;",
    "options": [":", "=>", "->", "="],
    "correct_answer": "=>",
    "explanation": "When typing the arrow function variable itself (rather than the parameters inline), you use the function type syntax: `(params) => ReturnType`."
  },
  {
    "id": 145,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Arrow Functions and 'this'",
    "question": "How do arrow functions handle the `this` keyword compared to regular functions?",
    "code_snippet": null,
    "options": ["They create their own `this` context based on how they are called", "They do not have their own `this`; they lexically capture the `this` value of the enclosing scope", "They always bind `this` to the global window object", "They throw an error if `this` is used"],
    "correct_answer": "They do not have their own `this`; they lexically capture the `this` value of the enclosing scope",
    "explanation": "This is why arrow functions are perfect for callbacks inside class methods. You never need to write `const self = this;` or use `.bind(this)` when using arrow functions."
  },
  {
    "id": 146,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "The 'never' Return Type",
    "question": "When should a function's return type be explicitly typed as `never`?",
    "code_snippet": null,
    "options": ["When it returns `null` or `undefined`", "When it always throws an error or contains an infinite loop, meaning it never successfully reaches the end of its body", "When it returns an empty array", "When it is an async function"],
    "correct_answer": "When it always throws an error or contains an infinite loop, meaning it never successfully reaches the end of its body",
    "explanation": "A `never` return type indicates that the function never completes normally. It is heavily used in exhaustive switch statements and error-handling utility functions."
  },
  {
    "id": 147,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Declaring 'this' Type",
    "question": "Fill in the blank to correctly declare the expected type of `this` inside a regular function (as a fake first parameter).",
    "code_snippet": "function handleClick(_______: HTMLButtonElement, event: MouseEvent) {\n  this.disabled = true;\n}",
    "options": ["self", "this", "context", "scope"],
    "correct_answer": "this",
    "explanation": "TypeScript allows you to explicitly type `this` by making it the first parameter of a function. It is erased during compilation and doesn't affect the actual runtime arguments."
  },
  {
    "id": 148,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Using 'unknown' in Parameters",
    "question": "Why is it safer to use `unknown` instead of `any` for a function that processes external data (like an API response)?",
    "code_snippet": null,
    "options": ["`unknown` makes the function run faster", "`unknown` forces the developer to narrow the type (using typeof or instanceof) before using it, preventing runtime errors from unexpected data shapes", "`any` is deprecated", "`unknown` automatically converts the data to JSON"],
    "correct_answer": "`unknown` forces the developer to narrow the type (using typeof or instanceof) before using it, preventing runtime errors from unexpected data shapes",
    "explanation": "If you type a parameter as `any`, you can call `.foo.bar()` on it and TS won't complain, leading to crashes. `unknown` forces you to prove what the data is before interacting with it."
  },
  {
    "id": 149,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Typing Functions (Type vs Interface)",
    "question": "Can you use an `interface` to define the shape of a function?",
    "code_snippet": null,
    "options": ["No, only `type` can be used for functions", "Yes, by using 'call signatures' inside the interface (e.g., `interface MathFunc { (a: number, b: number): number; }`)", "No, interfaces are only for objects", "Yes, but only for arrow functions"],
    "correct_answer": "Yes, by using 'call signatures' inside the interface (e.g., `interface MathFunc { (a: number, b: number): number; }`)",
    "explanation": "While `type` is more common for functions, interfaces can also describe callable structures using call signatures. This is often used when you want the function to also have static properties attached to it."
  },
  {
    "id": 150,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've now covered the essentials of TypeScript functions. What is the most significant benefit of strictly typing function parameters and return values?",
    "code_snippet": null,
    "options": ["It reduces the file size of the JavaScript output", "It creates a strict contract between the caller and the function, ensuring data flows correctly and catching mismatched arguments at compile-time rather than runtime", "It makes the code execute faster", "It automatically generates documentation"],
    "correct_answer": "It creates a strict contract between the caller and the function, ensuring data flows correctly and catching mismatched arguments at compile-time rather than runtime",
    "explanation": "Functions are the boundaries where data enters and exits your logic. By strictly typing these boundaries, you guarantee that the internal logic of the function only ever receives exactly what it expects."
  }
]
[
  {
    "id": 151,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Class Basics",
    "question": "Fill in the blank to correctly define a class with a typed property and a method.",
    "code_snippet": "_______ User {\n  name: string;\n  greet() {\n    console.log(`Hello, ${this.name}`);\n  }\n}",
    "options": ["struct", "class", "object", "type"],
    "correct_answer": "class",
    "explanation": "The `class` keyword is used to define a blueprint for creating objects with both state (properties) and behavior (methods). TypeScript adds type annotations directly to the class members."
  },
  {
    "id": 152,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Access Modifiers (public)",
    "question": "What is the default access modifier for properties and methods in a TypeScript class if none is explicitly specified?",
    "code_snippet": null,
    "options": ["private", "protected", "public", "internal"],
    "correct_answer": "public",
    "explanation": "If you don't write an access modifier, TypeScript assumes `public`. This means the property or method can be accessed from anywhere: inside the class, in subclasses, and from the outside."
  },
  {
    "id": 153,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Access Modifiers (private)",
    "question": "What does the `private` access modifier do to a class member?",
    "code_snippet": null,
    "options": ["Makes it accessible from anywhere", "Restricts access so it can only be read or modified from within the same class", "Allows access in subclasses but not externally", "Makes the property immutable"],
    "correct_answer": "Restricts access so it can only be read or modified from within the same class",
    "explanation": "`private` enforces strict encapsulation. If you have a `private password` property, no external code (and no subclasses) can access or change it directly. It must be managed via public methods inside the class."
  },
  {
    "id": 154,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Access Modifiers (protected)",
    "question": "How does the `protected` access modifier differ from `private`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`protected` allows access within the defining class AND any classes that inherit from it (subclasses), whereas `private` blocks subclasses", "`protected` makes the property public", "`protected` is only for static methods"],
    "correct_answer": "`protected` allows access within the defining class AND any classes that inherit from it (subclasses), whereas `private` blocks subclasses",
    "explanation": "`protected` is perfect for base class logic that you want to hide from the outside world, but still need to be accessible to child classes that extend the base class."
  },
  {
    "id": 155,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "readonly Modifier",
    "question": "How do you ensure a class property can only be assigned once (either at declaration or inside the constructor)?",
    "code_snippet": null,
    "options": ["const", "final", "readonly", "static"],
    "correct_answer": "readonly",
    "explanation": "The `readonly` modifier prevents reassignment after initialization. If you try to do `this.id = 5` outside of the constructor, TypeScript will throw a compile-time error."
  },
  {
    "id": 156,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Parameter Properties",
    "question": "Fill in the blank to correctly use TypeScript's 'parameter property' shorthand to declare and assign a public `name` property in one step.",
    "code_snippet": "class User {\n  constructor(_______ name: string) {\n    // No need for this.name = name;\n  }\n}",
    "options": ["public", "this", "var", "let"],
    "correct_answer": "public",
    "explanation": "By adding an access modifier (like `public`, `private`, `protected`, or `readonly`) directly to a constructor parameter, TypeScript automatically creates and assigns the class property for you. It saves a massive amount of boilerplate code."
  },
  {
    "id": 157,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Getters and Setters",
    "question": "Fill in the blank to correctly define a getter method that intercepts access to the `fullName` property.",
    "code_snippet": "class User {\n  _______ fullName(): string {\n    return `${this.firstName} ${this.lastName}`;\n  }\n}",
    "options": ["get", "read", "fetch", "return"],
    "correct_answer": "get",
    "explanation": "The `get` keyword defines an accessor that is called when a property is accessed. You can also use `set` to define a setter. They allow you to add logic (like validation or formatting) when reading or writing a property."
  },
  {
    "id": 158,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Static Members",
    "question": "What does the `static` keyword do when applied to a class method or property?",
    "code_snippet": null,
    "options": ["Makes it immutable", "Makes it belong to the class itself rather than instances of the class, meaning it is called via `ClassName.method()`", "Makes it private", "Makes it execute asynchronously"],
    "correct_answer": "Makes it belong to the class itself rather than instances of the class, meaning it is called via `ClassName.method()`",
    "explanation": "Static members are shared across all instances. They are often used for utility functions (like `Math.random()`) or keeping track of global state related to the class, like a counter of how many instances have been created."
  },
  {
    "id": 159,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "implements Keyword",
    "question": "What is the purpose of the `implements` keyword in TypeScript?",
    "code_snippet": null,
    "options": ["To inherit behavior and code from another class", "To enforce that a class matches the structural contract of an interface", "To create a static method", "To prevent a class from being instantiated"],
    "correct_answer": "To enforce that a class matches the structural contract of an interface",
    "explanation": "While `extends` is for inheriting code from a parent class, `implements` is for checking that a class fulfills the requirements of an interface. It acts as a strict compile-time contract."
  },
  {
    "id": 160,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Abstract Classes",
    "question": "What is an `abstract` class in TypeScript?",
    "code_snippet": null,
    "options": ["A class that cannot be instantiated directly and is meant to be extended by other classes", "A class with only static methods", "A class that implements an interface", "A class with no properties"],
    "correct_answer": "A class that cannot be instantiated directly and is meant to be extended by other classes",
    "explanation": "You cannot write `new Animal()` if `Animal` is abstract. It serves as a base blueprint that provides shared logic and enforces rules, but must be subclassed (e.g., `class Dog extends Animal`) to actually be used."
  },
  {
    "id": 161,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Abstract Methods",
    "question": "What is the defining characteristic of an `abstract` method inside an abstract class?",
    "code_snippet": null,
    "options": ["It has a default implementation", "It has no implementation in the abstract class and MUST be implemented by any concrete subclass", "It is automatically static", "It cannot be overridden"],
    "correct_answer": "It has no implementation in the abstract class and MUST be implemented by any concrete subclass",
    "explanation": "An abstract method says, 'Every child class must have a method with this exact signature, but I am leaving the actual implementation details up to you.' It forces subclasses to provide specific behavior."
  },
  {
    "id": 162,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generics (Concept)",
    "question": "What is the primary purpose of Generics in TypeScript?",
    "code_snippet": null,
    "options": ["To generate random numbers", "To create reusable components and functions that can work over a variety of types rather than a single, hardcoded one", "To compile code faster", "To hide implementation details"],
    "correct_answer": "To create reusable components and functions that can work over a variety of types rather than a single, hardcoded one",
    "explanation": "Generics are like 'variables for types'. Instead of writing a function that only accepts `number`, you write a function that accepts `T`, allowing the caller to decide if `T` is a `number`, `string`, or `User`."
  },
  {
    "id": 163,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generics (Syntax)",
    "question": "Fill in the blank to correctly define a generic function that returns whatever type is passed into it.",
    "code_snippet": "function identity<T>(arg: T): _______ {\n  return arg;\n}",
    "options": ["any", "T", "unknown", "void"],
    "correct_answer": "T",
    "explanation": "The `<T>` declares the generic type variable. By using `T` as the return type, TypeScript knows that the output type is exactly the same as the input type, preserving type safety."
  },
  {
    "id": 164,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generics (Inference)",
    "question": "If you call the generic function `identity('hello')` without explicitly passing the type argument (like `identity<string>('hello')`), what does TypeScript do?",
    "code_snippet": null,
    "options": ["Throws an error", "Infers `T` as `string` based on the argument provided", "Infers `T` as `any`", "Infers `T` as `unknown`"],
    "correct_answer": "Infers `T` as `string` based on the argument provided",
    "explanation": "TypeScript's inference engine is incredibly smart. It looks at the argument `'hello'`, sees it's a string, and automatically sets `T` to `string` for that specific function call."
  },
  {
    "id": 165,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generics (Constraints)",
    "question": "How do you constrain a generic type `T` to ensure it MUST have a `length` property (like a string or an array)?",
    "code_snippet": null,
    "options": ["T extends { length: number }", "T implements Length", "T requires length", "T : length"],
    "correct_answer": "T extends { length: number }",
    "explanation": "The `extends` keyword in generics acts as a constraint. It tells TypeScript, 'T can be anything, as long as it has at least a `length` property that is a number.' This allows you to safely access `.length` inside the function."
  },
  {
    "id": 166,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generics (Multiple Parameters)",
    "question": "Fill in the blank to correctly define a generic function that takes two different type parameters.",
    "code_snippet": "function pair<_______>(first: T, second: U): [T, U] {\n  return [first, second];\n}",
    "options": ["T, U", "T & U", "T | U", "T extends U"],
    "correct_answer": "T, U",
    "explanation": "You can declare multiple generic type variables separated by commas. This allows the function to maintain the distinct types of both arguments, returning a strictly typed tuple `[T, U]`."
  },
  {
    "id": 167,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generic Classes",
    "question": "Fill in the blank to correctly define a generic `Box` class that holds a specific type of data.",
    "code_snippet": "class Box<_______> {\n  value: T;\n  constructor(val: T) {\n    this.value = val;\n  }\n}",
    "options": ["T", "any", "unknown", "type"],
    "correct_answer": "T",
    "explanation": "By placing `<T>` after the class name, you make the entire class generic. When you instantiate it (`new Box<string>('hello')`), `T` becomes `string` for that specific instance."
  },
  {
    "id": 168,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generic Interfaces",
    "question": "Fill in the blank to correctly define a generic interface for a standardized API response.",
    "code_snippet": "interface ApiResponse<_______> {\n  data: T;\n  error: string | null;\n}",
    "options": ["T", "any", "unknown", "type"],
    "correct_answer": "T",
    "explanation": "Generic interfaces are incredibly useful for API clients. You can define the shape once (`ApiResponse<T>`), and then use it as `ApiResponse<User>` or `ApiResponse<Product[]>`, keeping the `data` property strictly typed."
  },
  {
    "id": 169,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Class vs Interface",
    "question": "When should you use an `interface` instead of a `class` to define an object shape?",
    "code_snippet": null,
    "options": ["When you need to instantiate objects with the `new` keyword", "When you only need to define the 'shape' or contract of the data without runtime implementation, behavior, or constructors", "When you need private properties", "When you need to use access modifiers"],
    "correct_answer": "When you only need to define the 'shape' or contract of the data without runtime implementation, behavior, or constructors",
    "explanation": "Interfaces are completely erased at runtime and add zero bytes to your JS bundle. Use them for data shapes and contracts. Use classes when you need actual runtime logic, methods, memory allocation, and instantiation."
  },
  {
    "id": 170,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've now covered Classes, Access Modifiers, Abstract Classes, and Generics. What is the ultimate superpower of combining Generics with OOP in TypeScript?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It allows you to build highly reusable, type-safe data structures and components (like custom Collections or API clients) that adapt perfectly to whatever data type the user provides", "It eliminates the need for interfaces", "It automatically generates unit tests"],
    "correct_answer": "It allows you to build highly reusable, type-safe data structures and components (like custom Collections or API clients) that adapt perfectly to whatever data type the user provides",
    "explanation": "Generics transform your classes from rigid, single-purpose tools into flexible, universal engines. You write the logic once, and the TypeScript compiler guarantees type safety no matter what data the user passes in."
  }
] 
[
  {
    "id": 151,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Class Basics",
    "question": "Fill in the blank to correctly define a class with a typed property and a method.",
    "code_snippet": "_______ User {\n  name: string;\n  greet() {\n    console.log(`Hello, ${this.name}`);\n  }\n}",
    "options": ["struct", "class", "object", "type"],
    "correct_answer": "class",
    "explanation": "The `class` keyword is used to define a blueprint for creating objects with both state (properties) and behavior (methods). TypeScript adds type annotations directly to the class members."
  },
  {
    "id": 152,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Access Modifiers (public)",
    "question": "What is the default access modifier for properties and methods in a TypeScript class if none is explicitly specified?",
    "code_snippet": null,
    "options": ["private", "protected", "public", "internal"],
    "correct_answer": "public",
    "explanation": "If you don't write an access modifier, TypeScript assumes `public`. This means the property or method can be accessed from anywhere: inside the class, in subclasses, and from the outside."
  },
  {
    "id": 153,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Access Modifiers (private)",
    "question": "What does the `private` access modifier do to a class member?",
    "code_snippet": null,
    "options": ["Makes it accessible from anywhere", "Restricts access so it can only be read or modified from within the same class", "Allows access in subclasses but not externally", "Makes the property immutable"],
    "correct_answer": "Restricts access so it can only be read or modified from within the same class",
    "explanation": "`private` enforces strict encapsulation. If you have a `private password` property, no external code (and no subclasses) can access or change it directly. It must be managed via public methods inside the class."
  },
  {
    "id": 154,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Access Modifiers (protected)",
    "question": "How does the `protected` access modifier differ from `private`?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`protected` allows access within the defining class AND any classes that inherit from it (subclasses), whereas `private` blocks subclasses", "`protected` makes the property public", "`protected` is only for static methods"],
    "correct_answer": "`protected` allows access within the defining class AND any classes that inherit from it (subclasses), whereas `private` blocks subclasses",
    "explanation": "`protected` is perfect for base class logic that you want to hide from the outside world, but still need to be accessible to child classes that extend the base class."
  },
  {
    "id": 155,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "readonly Modifier",
    "question": "How do you ensure a class property can only be assigned once (either at declaration or inside the constructor)?",
    "code_snippet": null,
    "options": ["const", "final", "readonly", "static"],
    "correct_answer": "readonly",
    "explanation": "The `readonly` modifier prevents reassignment after initialization. If you try to do `this.id = 5` outside of the constructor, TypeScript will throw a compile-time error."
  },
  {
    "id": 156,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Parameter Properties",
    "question": "Fill in the blank to correctly use TypeScript's 'parameter property' shorthand to declare and assign a public `name` property in one step.",
    "code_snippet": "class User {\n  constructor(_______ name: string) {\n    // No need for this.name = name;\n  }\n}",
    "options": ["public", "this", "var", "let"],
    "correct_answer": "public",
    "explanation": "By adding an access modifier (like `public`, `private`, `protected`, or `readonly`) directly to a constructor parameter, TypeScript automatically creates and assigns the class property for you. It saves a massive amount of boilerplate code."
  },
  {
    "id": 157,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Getters and Setters",
    "question": "Fill in the blank to correctly define a getter method that intercepts access to the `fullName` property.",
    "code_snippet": "class User {\n  _______ fullName(): string {\n    return `${this.firstName} ${this.lastName}`;\n  }\n}",
    "options": ["get", "read", "fetch", "return"],
    "correct_answer": "get",
    "explanation": "The `get` keyword defines an accessor that is called when a property is accessed. You can also use `set` to define a setter. They allow you to add logic (like validation or formatting) when reading or writing a property."
  },
  {
    "id": 158,
    "level": "beginner",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Static Members",
    "question": "What does the `static` keyword do when applied to a class method or property?",
    "code_snippet": null,
    "options": ["Makes it immutable", "Makes it belong to the class itself rather than instances of the class, meaning it is called via `ClassName.method()`", "Makes it private", "Makes it execute asynchronously"],
    "correct_answer": "Makes it belong to the class itself rather than instances of the class, meaning it is called via `ClassName.method()`",
    "explanation": "Static members are shared across all instances. They are often used for utility functions (like `Math.random()`) or keeping track of global state related to the class, like a counter of how many instances have been created."
  },
  {
    "id": 159,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "implements Keyword",
    "question": "What is the purpose of the `implements` keyword in TypeScript?",
    "code_snippet": null,
    "options": ["To inherit behavior and code from another class", "To enforce that a class matches the structural contract of an interface", "To create a static method", "To prevent a class from being instantiated"],
    "correct_answer": "To enforce that a class matches the structural contract of an interface",
    "explanation": "While `extends` is for inheriting code from a parent class, `implements` is for checking that a class fulfills the requirements of an interface. It acts as a strict compile-time contract."
  },
  {
    "id": 160,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Abstract Classes",
    "question": "What is an `abstract` class in TypeScript?",
    "code_snippet": null,
    "options": ["A class that cannot be instantiated directly and is meant to be extended by other classes", "A class with only static methods", "A class that implements an interface", "A class with no properties"],
    "correct_answer": "A class that cannot be instantiated directly and is meant to be extended by other classes",
    "explanation": "You cannot write `new Animal()` if `Animal` is abstract. It serves as a base blueprint that provides shared logic and enforces rules, but must be subclassed (e.g., `class Dog extends Animal`) to actually be used."
  },
  {
    "id": 161,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Abstract Methods",
    "question": "What is the defining characteristic of an `abstract` method inside an abstract class?",
    "code_snippet": null,
    "options": ["It has a default implementation", "It has no implementation in the abstract class and MUST be implemented by any concrete subclass", "It is automatically static", "It cannot be overridden"],
    "correct_answer": "It has no implementation in the abstract class and MUST be implemented by any concrete subclass",
    "explanation": "An abstract method says, 'Every child class must have a method with this exact signature, but I am leaving the actual implementation details up to you.' It forces subclasses to provide specific behavior."
  },
  {
    "id": 162,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generics (Concept)",
    "question": "What is the primary purpose of Generics in TypeScript?",
    "code_snippet": null,
    "options": ["To generate random numbers", "To create reusable components and functions that can work over a variety of types rather than a single, hardcoded one", "To compile code faster", "To hide implementation details"],
    "correct_answer": "To create reusable components and functions that can work over a variety of types rather than a single, hardcoded one",
    "explanation": "Generics are like 'variables for types'. Instead of writing a function that only accepts `number`, you write a function that accepts `T`, allowing the caller to decide if `T` is a `number`, `string`, or `User`."
  },
  {
    "id": 163,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generics (Syntax)",
    "question": "Fill in the blank to correctly define a generic function that returns whatever type is passed into it.",
    "code_snippet": "function identity<T>(arg: T): _______ {\n  return arg;\n}",
    "options": ["any", "T", "unknown", "void"],
    "correct_answer": "T",
    "explanation": "The `<T>` declares the generic type variable. By using `T` as the return type, TypeScript knows that the output type is exactly the same as the input type, preserving type safety."
  },
  {
    "id": 164,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generics (Inference)",
    "question": "If you call the generic function `identity('hello')` without explicitly passing the type argument (like `identity<string>('hello')`), what does TypeScript do?",
    "code_snippet": null,
    "options": ["Throws an error", "Infers `T` as `string` based on the argument provided", "Infers `T` as `any`", "Infers `T` as `unknown`"],
    "correct_answer": "Infers `T` as `string` based on the argument provided",
    "explanation": "TypeScript's inference engine is incredibly smart. It looks at the argument `'hello'`, sees it's a string, and automatically sets `T` to `string` for that specific function call."
  },
  {
    "id": 165,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generics (Constraints)",
    "question": "How do you constrain a generic type `T` to ensure it MUST have a `length` property (like a string or an array)?",
    "code_snippet": null,
    "options": ["T extends { length: number }", "T implements Length", "T requires length", "T : length"],
    "correct_answer": "T extends { length: number }",
    "explanation": "The `extends` keyword in generics acts as a constraint. It tells TypeScript, 'T can be anything, as long as it has at least a `length` property that is a number.' This allows you to safely access `.length` inside the function."
  },
  {
    "id": 166,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generics (Multiple Parameters)",
    "question": "Fill in the blank to correctly define a generic function that takes two different type parameters.",
    "code_snippet": "function pair<_______>(first: T, second: U): [T, U] {\n  return [first, second];\n}",
    "options": ["T, U", "T & U", "T | U", "T extends U"],
    "correct_answer": "T, U",
    "explanation": "You can declare multiple generic type variables separated by commas. This allows the function to maintain the distinct types of both arguments, returning a strictly typed tuple `[T, U]`."
  },
  {
    "id": 167,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generic Classes",
    "question": "Fill in the blank to correctly define a generic `Box` class that holds a specific type of data.",
    "code_snippet": "class Box<_______> {\n  value: T;\n  constructor(val: T) {\n    this.value = val;\n  }\n}",
    "options": ["T", "any", "unknown", "type"],
    "correct_answer": "T",
    "explanation": "By placing `<T>` after the class name, you make the entire class generic. When you instantiate it (`new Box<string>('hello')`), `T` becomes `string` for that specific instance."
  },
  {
    "id": 168,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Generic Interfaces",
    "question": "Fill in the blank to correctly define a generic interface for a standardized API response.",
    "code_snippet": "interface ApiResponse<_______> {\n  data: T;\n  error: string | null;\n}",
    "options": ["T", "any", "unknown", "type"],
    "correct_answer": "T",
    "explanation": "Generic interfaces are incredibly useful for API clients. You can define the shape once (`ApiResponse<T>`), and then use it as `ApiResponse<User>` or `ApiResponse<Product[]>`, keeping the `data` property strictly typed."
  },
  {
    "id": 169,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Class vs Interface",
    "question": "When should you use an `interface` instead of a `class` to define an object shape?",
    "code_snippet": null,
    "options": ["When you need to instantiate objects with the `new` keyword", "When you only need to define the 'shape' or contract of the data without runtime implementation, behavior, or constructors", "When you need private properties", "When you need to use access modifiers"],
    "correct_answer": "When you only need to define the 'shape' or contract of the data without runtime implementation, behavior, or constructors",
    "explanation": "Interfaces are completely erased at runtime and add zero bytes to your JS bundle. Use them for data shapes and contracts. Use classes when you need actual runtime logic, methods, memory allocation, and instantiation."
  },
  {
    "id": 170,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've now covered Classes, Access Modifiers, Abstract Classes, and Generics. What is the ultimate superpower of combining Generics with OOP in TypeScript?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It allows you to build highly reusable, type-safe data structures and components (like custom Collections or API clients) that adapt perfectly to whatever data type the user provides", "It eliminates the need for interfaces", "It automatically generates unit tests"],
    "correct_answer": "It allows you to build highly reusable, type-safe data structures and components (like custom Collections or API clients) that adapt perfectly to whatever data type the user provides",
    "explanation": "Generics transform your classes from rigid, single-purpose tools into flexible, universal engines. You write the logic once, and the TypeScript compiler guarantees type safety no matter what data the user passes in."
  }
]
[
  {
    "id": 191,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Module Augmentation (Concept)",
    "question": "What is 'Module Augmentation' in TypeScript?",
    "code_snippet": null,
    "options": ["A way to minify module code", "A technique that allows you to add new declarations, methods, or types to an existing external module or namespace from outside its original source file", "A way to delete modules", "A build-time optimization"],
    "correct_answer": "A technique that allows you to add new declarations, methods, or types to an existing external module or namespace from outside its original source file",
    "explanation": "Module Augmentation is incredibly powerful for extending third-party libraries. If a popular library's type definitions are missing a method, you can augment its module to add it without forking the library."
  },
  {
    "id": 192,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "declare module",
    "question": "Fill in the blank to correctly augment the Express.js `Request` interface to include a custom `user` property.",
    "code_snippet": "_______ 'express' {\n  export interface Request {\n    user?: User;\n  }\n}",
    "options": ["augment", "extend", "declare module", "import"],
    "correct_answer": "declare module",
    "explanation": "By wrapping the interface inside `declare module 'express'`, TypeScript merges your custom `user` property into Express's official `Request` type. Now `req.user` is fully typed across your entire application!"
  },
  {
    "id": 193,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Constructor Types",
    "question": "How do you type a function that expects a CLASS constructor as its argument (not an instance of the class)?",
    "code_snippet": null,
    "options": ["Function", "typeof ClassName or `new (...args: any[]) => InstanceType`", "constructor", "ClassType"],
    "correct_answer": "typeof ClassName or `new (...args: any[]) => InstanceType`",
    "explanation": "The `new (...args: any[]) => T` syntax tells TypeScript, 'This value must be callable with the `new` keyword and produce an instance of type T.' It is the standard way to type class factories and mixins."
  },
  {
    "id": 194,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Constructor Types (Syntax)",
    "question": "Fill in the blank to correctly type a factory function that takes any class constructor and returns an instance of it.",
    "code_snippet": "function createInstance<T>(Ctor: _______) : T {\n  return new Ctor();\n}",
    "options": ["T", "new (...args: any[]) => T", "constructor<T>", "typeof T"],
    "correct_answer": "new (...args: any[]) => T",
    "explanation": "The `new (...args: any[]) => T` type is called a 'construct signature'. It describes any function that can be called with `new` and returns type `T`. This is how you write type-safe factory patterns."
  },
  {
    "id": 195,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Polymorphic this in Interfaces",
    "question": "How can you use the `this` type inside an interface to ensure fluent method chaining returns the exact implementing class?",
    "code_snippet": null,
    "options": ["Use `any` as the return type", "Use `this` as the return type in the interface methods; when a class implements it, `this` resolves to the concrete class", "Use `ClassName` as the return type", "Use `void` as the return type"],
    "correct_answer": "Use `this` as the return type in the interface methods; when a class implements it, `this` resolves to the concrete class",
    "explanation": "If `interface Builder` has methods that return `this`, and `class QueryBuilder implements Builder`, then calling `new QueryBuilder().select().where()` correctly returns `QueryBuilder`, not just `Builder`."
  },
  {
    "id": 196,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generic Inference from Context",
    "question": "What is 'contextual inference' in TypeScript generics?",
    "code_snippet": null,
    "options": ["Inferring the type from the function's internal logic", "Inferring the generic type from the expected return type or assignment context, not just the arguments", "Inferring the type from the DOM", "Inferring the type from CSS"],
    "correct_answer": "Inferring the generic type from the expected return type or assignment context, not just the arguments",
    "explanation": "If you write `let fn: () => string = identity`, TypeScript infers that `identity` must be `identity<string>` based on the left-hand side assignment, even without explicit type arguments."
  },
  {
    "id": 197,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generic Default Parameter Trick",
    "question": "What is the common trick `T = never` used for in generic constraints?",
    "code_snippet": null,
    "options": ["It makes the function throw an error", "It creates a generic parameter that MUST be explicitly provided by the caller, because `never` cannot be inferred naturally from arguments", "It deletes the generic parameter", "It defaults to the `any` type"],
    "correct_answer": "It creates a generic parameter that MUST be explicitly provided by the caller, because `never` cannot be inferred naturally from arguments",
    "explanation": "Setting a default of `never` is a clever way to force the developer to explicitly pass a type argument. If they forget, the type resolves to `never`, which will cause immediate, helpful compile-time errors."
  },
  {
    "id": 198,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Private Fields (#) vs private Keyword",
    "question": "What is the difference between JavaScript's native `#` private fields and TypeScript's `private` keyword?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`#` private fields are enforced at runtime by the JavaScript engine and are completely inaccessible; TS `private` is only a compile-time check and is erased in the JS output", "`private` is for methods, `#` is for properties", "`#` is deprecated"],
    "correct_answer": "`#` private fields are enforced at runtime by the JavaScript engine and are completely inaccessible; TS `private` is only a compile-time check and is erased in the JS output",
    "explanation": "If someone bypasses TypeScript and accesses a `private` property directly in the compiled JS, it works! But `#` private fields are baked into the JS runtime, making them truly inaccessible from outside the class."
  },
  {
    "id": 199,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "The 'as const' with Classes",
    "question": "If you pass an object literal with `as const` to a function, how does it affect generic type inference?",
    "code_snippet": null,
    "options": ["It widens the type to `any`", "It narrows the inference to exact literal types instead of widened primitive types, preserving the precise values", "It converts the object to a class instance", "It prevents the function from compiling"],
    "correct_answer": "It narrows the inference to exact literal types instead of widened primitive types, preserving the precise values",
    "explanation": "Without `as const`, `{ status: 'active' }` infers as `{ status: string }`. With `as const`, it infers as `{ readonly status: 'active' }`, giving you extremely precise generic inference for things like Redux actions or route configs."
  },
  {
    "id": 200,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Recursive Conditional Types",
    "question": "Can Conditional Types be recursive in TypeScript?",
    "code_snippet": null,
    "options": ["No, recursion is not supported in types", "Yes, a conditional type can reference itself, allowing you to deeply traverse and transform complex nested structures like deeply nested objects or arrays", "Only in abstract classes", "Only with the `infer` keyword"],
    "correct_answer": "Yes, a conditional type can reference itself, allowing you to deeply traverse and transform complex nested structures like deeply nested objects or arrays",
    "explanation": "Recursive conditional types are how utility types like `DeepPartial<T>` or `DeepReadonly<T>` are implemented. The type calls itself on nested objects until it reaches primitive values (the base case)."
  },
  {
    "id": 201,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Function Contravariance",
    "question": "What is 'contravariance' in the context of TypeScript function parameters?",
    "code_snippet": null,
    "options": ["Parameters must be exactly the same type", "A function that accepts a broader type can safely be used where a function that accepts a narrower type is expected", "A function that accepts a narrower type can be used where a broader type is expected", "Parameters are ignored by the type checker"],
    "correct_answer": "A function that accepts a broader type can safely be used where a function that accepts a narrower type is expected",
    "explanation": "If a callback expects `(animal: Animal) => void`, you can safely pass `(dog: Dog) => void`? No! You must pass a function that accepts at LEAST `Animal`, because the caller might pass a `Cat`. Parameters are contravariant; return types are covariant."
  },
  {
    "id": 202,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Covariance vs Contravariance",
    "question": "In TypeScript, are function return types covariant or contravariant?",
    "code_snippet": null,
    "options": ["Contravariant", "Covariant (a function returning a narrower type can be used where a broader return type is expected)", "Invariant", "Neither"],
    "correct_answer": "Covariant (a function returning a narrower type can be used where a broader return type is expected)",
    "explanation": "If a callback expects `() => Animal`, you can safely provide `() => Dog` because a `Dog` IS an `Animal`. Return types flow 'outward' and are covariant. This is a foundational concept in type theory."
  },
  {
    "id": 203,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "strictFunctionTypes",
    "question": "What does the `strictFunctionTypes` compiler flag do?",
    "code_snippet": null,
    "options": ["It makes all functions return `void`", "It enforces proper contravariance checking on function parameter types, preventing unsound assignments where a function expecting a narrower type is used in place of one expecting a broader type", "It prevents the use of arrow functions", "It disables function overloads"],
    "correct_answer": "It enforces proper contravariance checking on function parameter types, preventing unsound assignments where a function expecting a narrower type is used in place of one expecting a broader type",
    "explanation": "Without `strictFunctionTypes`, TypeScript uses bivariant checking (allowing both narrower and broader types in parameters), which can lead to subtle runtime crashes. Enabling this flag catches those bugs at compile-time."
  },
  {
    "id": 204,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generic Type Predicates",
    "question": "Can a custom type guard function use generics?",
    "code_snippet": null,
    "options": ["No, type guards must use concrete types", "Yes, you can write `function isType<T>(val: unknown): val is T` to create a reusable, generic narrowing function", "Only with the `infer` keyword", "Only in abstract classes"],
    "correct_answer": "Yes, you can write `function isType<T>(val: unknown): val is T` to create a reusable, generic narrowing function",
    "explanation": "Generic type guards are incredibly powerful. You can write a single `isInstanceOf<T>` function and reuse it for any class, maintaining full type safety when narrowing `unknown` API responses."
  },
  {
    "id": 205,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Abstract Constructor Types",
    "question": "How do you type a function that accepts an abstract class constructor (a class that cannot be instantiated directly)?",
    "code_snippet": null,
    "options": ["typeof AbstractClass", "abstract new (...args: any[]) => T", "constructor abstract T", "It is not possible"],
    "correct_answer": "abstract new (...args: any[]) => T",
    "explanation": "By adding the `abstract` keyword before the `new` construct signature, you tell TypeScript, 'This function accepts the constructor of a class that might be abstract.' This is essential for typing mixins and factory patterns."
  },
  {
    "id": 206,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generic Inference Priority",
    "question": "When TypeScript infers a generic type from multiple arguments, what happens if the arguments suggest conflicting types?",
    "code_snippet": null,
    "options": ["It throws an error immediately", "It creates a union of the inferred types (e.g., if one arg suggests `string` and another suggests `number`, `T` becomes `string | number`)", "It defaults to `any`", "It uses only the first argument's type"],
    "correct_answer": "It creates a union of the inferred types (e.g., if one arg suggests `string` and another suggests `number`, `T` becomes `string | number`)",
    "explanation": "TypeScript tries to find a type that satisfies all inference sites. If the arguments disagree, it widens to a union. This is why sometimes you need to explicitly provide the type argument to avoid unexpected widening."
  },
  {
    "id": 207,
    "level": "intermediate",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Generic Utility: InstanceType<T>",
    "question": "What does the built-in `InstanceType<T>` utility type do?",
    "code_snippet": null,
    "options": ["Returns the type of a class constructor", "Extracts the instance type from a constructor type using `infer` (e.g., `InstanceType<typeof MyClass>` returns `MyClass`)", "Creates a new instance of a class", "Converts a class to an interface"],
    "correct_answer": "Extracts the instance type from a constructor type using `infer` (e.g., `InstanceType<typeof MyClass>` returns `MyClass`)",
    "explanation": "`typeof MyClass` gives you the constructor function type. `InstanceType<typeof MyClass>` uses `infer` under the hood to extract what `new MyClass()` actually produces."
  },
  {
    "id": 208,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Higher-Order Functions & Generics",
    "question": "When writing a higher-order function (a function that takes another function as an argument), why is it critical to preserve the generic type parameters of the inner function?",
    "code_snippet": null,
    "options": ["It makes the code shorter", "It ensures that the wrapper function doesn't lose type information, maintaining full end-to-end type safety from the original function's inputs to its outputs", "It is required by the compiler", "It prevents memory leaks"],
    "correct_answer": "It ensures that the wrapper function doesn't lose type information, maintaining full end-to-end type safety from the original function's inputs to its outputs",
    "explanation": "If you write a `memoize` or `debounce` function, you MUST preserve the original function's parameter and return types using generics. Otherwise, the wrapped function loses all type safety."
  },
  {
    "id": 209,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "TypeScript's Type System Philosophy",
    "question": "TypeScript's type system is described as 'structurally typed' and 'Turing-complete'. What does this mean in practice?",
    "code_snippet": null,
    "options": ["It means TypeScript can run any JavaScript program", "It means types are compared by their shape (not their name), and the type system is expressive enough to perform complex computations, loops, and conditional logic entirely at compile-time", "It means TypeScript replaces the need for unit tests", "It means the type system can only handle simple objects"],
    "correct_answer": "It means types are compared by their shape (not their name), and the type system is expressive enough to perform complex computations, loops, and conditional logic entirely at compile-time",
    "explanation": "TypeScript's type system is essentially a pure functional programming language that runs at compile-time. You can write types that recursively parse strings, compute mathematical results, and validate complex data schemas before your code ever executes."
  },
  {
    "id": 210,
    "level": "advanced",
    "module_id": "ts_mod_03_functions_oop",
    "module_name": "Functions & OOP in TypeScript",
    "type": "conceptual",
    "topic": "Module 3 Wrap-up (Final)",
    "question": "You have now completed Functions, OOP, and Advanced Generics in TypeScript. What is the ultimate hallmark of a developer who has truly mastered this module?",
    "code_snippet": null,
    "options": ["They never use the `any` type", "They can design APIs, libraries, and architectural patterns where the TypeScript compiler acts as a tireless assistant—catching bugs, validating data, and providing perfect autocomplete—before a single line of code ever runs", "They memorize all built-in utility types", "They write TypeScript without an IDE"],
    "correct_answer": "They can design APIs, libraries, and architectural patterns where the TypeScript compiler acts as a tireless assistant—catching bugs, validating data, and providing perfect autocomplete—before a single line of code ever runs",
    "explanation": "Mastering TypeScript's function and type system means you have learned to think in contracts. Every function signature, every generic constraint, and every conditional type is a promise you make to the next developer (and to your future self) about exactly how data will flow through your system."
  }
]
