[
  {
    "id": 451,
    "level": "beginner",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "App Router vs Pages Router",
    "question": "What is the fundamental architectural difference between the Next.js 'App Router' and the legacy 'Pages Router'?",
    "code_snippet": null,
    "options": ["The App Router uses HTML files, the Pages Router uses JSX", "The App Router is built on React Server Components and uses file-system routing with folders, while the Pages Router uses client-side rendered React pages", "The Pages Router is faster", "The App Router does not support TypeScript"],
    "correct_answer": "The App Router is built on React Server Components and uses file-system routing with folders, while the Pages Router uses client-side rendered React pages",
    "explanation": "The App Router (`app/` directory) represents a paradigm shift. It leverages React Server Components by default, allowing you to fetch data and render UI on the server, drastically reducing the JavaScript sent to the client."
  },
  {
    "id": 452,
    "level": "beginner",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Server Components by Default",
    "question": "In the Next.js App Router, what is the default execution environment for a React component?",
    "code_snippet": null,
    "options": ["Client Component", "Server Component", "Web Worker", "Edge Function"],
    "correct_answer": "Server Component",
    "explanation": "Unless explicitly marked otherwise, every component in the `app/` directory is a React Server Component. It renders on the server, has zero impact on the client bundle size, and can directly access backend resources like databases."
  },
  {
    "id": 453,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "topic": "The 'use client' Directive",
    "question": "Fill in the blank to correctly mark a file as a Client Component, allowing the use of React Hooks and browser event listeners.",
    "code_snippet": "'_______ client';\n\nimport { useState } from 'react';\n\nexport default function Counter() { ... }",
    "options": ["use", "pragma", "directive", "mode"],
    "correct_answer": "use",
    "explanation": "The `'use client'` directive is a boundary marker. It tells the Next.js bundler: 'Everything in this file, and any components it imports, must be executed in the browser and included in the client-side JavaScript bundle.'"
  },
  {
    "id": 454,
    "level": "beginner",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Folder-Based Routing",
    "question": "In the Next.js App Router, how do you define a new URL route?",
    "code_snippet": null,
    "options": ["By creating a new `.tsx` file in the root directory", "By creating a new folder with a `page.tsx` file inside it", "By adding a route to a central `routes.json` file", "By using the `<Route>` component"],
    "correct_answer": "By creating a new folder with a `page.tsx` file inside it",
    "explanation": "The App Router uses folders to define routes. A folder named `app/dashboard/page.tsx` automatically maps to the URL `/dashboard`. Special files like `page.tsx`, `layout.tsx`, and `loading.tsx` give the folder its behavior."
  },
  {
    "id": 455,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly define a dynamic route segment for a blog post (e.g., `/blog/my-post`).",
    "code_snippet": "app/\n  blog/\n    [_______]/\n      page.tsx",
    "options": ["id", "slug", "post", "param"],
    "correct_answer": "slug",
    "explanation": "Wrapping a folder name in square brackets (e.g., `[slug]`) creates a dynamic segment. The `page.tsx` inside will receive `slug` as a parameter, allowing you to render different content based on the URL."
  },
  {
    "id": 456,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Catch-All Routes",
    "question": "What is the difference between `[...slug]` and `[[...slug]]` in Next.js routing?",
    "code_snippet": null,
    "options": ["There is no difference", "`[...slug]` matches one or more segments (required); `[[...slug]]` matches zero or more segments (optional)", "`[[...slug]]` is for API routes only", "`[...slug]` is deprecated"],
    "correct_answer": "`[...slug]` matches one or more segments (required); `[[...slug]]` matches zero or more segments (optional)",
    "explanation": "Double brackets `[[...slug]]` create an 'Optional Catch-all'. This means the route will match `/docs`, `/docs/a`, and `/docs/a/b`. A standard catch-all `[...slug]` would NOT match the base `/docs` route."
  },
  {
    "id": 457,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Route Groups",
    "question": "What is the purpose of wrapping a folder name in parentheses, like `(marketing)`, in the App Router?",
    "code_snippet": null,
    "options": ["It creates a private API route", "It organizes code logically without affecting the URL path segment", "It forces the route to be a Server Component", "It enables caching for that route"],
    "correct_answer": "It organizes code logically without affecting the URL path segment",
    "explanation": "Route Groups `(folder)` allow you to group routes for organizational purposes (e.g., separating `(marketing)` from `(dashboard)`) without adding that folder name to the actual URL."
  },
  {
    "id": 458,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Layouts (layout.tsx)",
    "question": "What is the primary characteristic of a `layout.tsx` file in the App Router?",
    "code_snippet": null,
    "options": ["It re-renders completely every time the user navigates to a new page", "It persists across navigations, preserving state and avoiding re-rendering when child pages change", "It can only be a Client Component", "It is used exclusively for SEO metadata"],
    "correct_answer": "It persists across navigations, preserving state and avoiding re-rendering when child pages change",
    "explanation": "Layouts wrap their child pages and do NOT unmount when navigating between sibling routes. This is perfect for sidebars and headers that should remain intact while the main content swaps out."
  },
  {
    "id": 459,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Templates (template.tsx)",
    "question": "How does a `template.tsx` file differ from a `layout.tsx` file?",
    "code_snippet": null,
    "options": ["Templates are for CSS, Layouts are for HTML", "Templates create a NEW instance of the component on every navigation, remounting the DOM and resetting state", "Templates are async, Layouts are sync", "There is no difference"],
    "correct_answer": "Templates create a NEW instance of the component on every navigation, remounting the DOM and resetting state",
    "explanation": "While Layouts persist, Templates behave like Pages—they unmount and remount on navigation. This is useful if you need to trigger an animation or reset a form every time the user enters a specific route segment."
  },
  {
    "id": 460,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Loading UI (loading.tsx)",
    "question": "What React feature does the `loading.tsx` file automatically integrate with?",
    "code_snippet": null,
    "options": ["React.memo", "React Suspense", "React Error Boundary", "React Portal"],
    "correct_answer": "React Suspense",
    "explanation": "When you create a `loading.tsx` file, Next.js automatically wraps the sibling `page.tsx` (and its children) in a `<Suspense>` boundary. The `loading.tsx` UI renders instantly while the page's async data fetching completes."
  },
  {
    "id": 461,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Error Handling (error.tsx)",
    "question": "What React component type must the `error.tsx` file export under the hood?",
    "code_snippet": null,
    "options": ["A Functional Component with Hooks", "A React Error Boundary (Class Component)", "A Server Component", "A Higher-Order Component"],
    "correct_answer": "A React Error Boundary (Class Component)",
    "explanation": "Because React Error Boundaries currently require Class Components, Next.js automatically wraps your `error.tsx` functional component in a Class-based Error Boundary to catch runtime JavaScript errors in the nested route segment."
  },
  {
    "id": 462,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Not Found (not-found.tsx)",
    "question": "How do you programmatically trigger the `not-found.tsx` UI from within a Server Component?",
    "code_snippet": null,
    "options": ["return <NotFound />", "throw new Error('404')", "import { notFound } from 'next/navigation'; notFound();", "return null"],
    "correct_answer": "import { notFound } from 'next/navigation'; notFound();",
    "explanation": "The `notFound()` function throws a special Next.js error that is caught by the framework, immediately rendering the nearest `not-found.tsx` file in the route hierarchy without crashing the entire app."
  },
  {
    "id": 463,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Async Params (Next.js 15+)",
    "question": "In Next.js 15+, how has the TypeScript typing of the `params` prop in Server Components changed?",
    "code_snippet": null,
    "options": ["It is now a synchronous object", "It is now a Promise that must be awaited, reflecting the underlying asynchronous nature of route resolution", "It has been removed entirely", "It is now typed as `any`"],
    "correct_answer": "It is now a Promise that must be awaited, reflecting the underlying asynchronous nature of route resolution",
    "explanation": "To support advanced caching and partial prerendering, Next.js 15 made `params` and `searchParams` asynchronous. You must now write `const { slug } = await params;` in your Server Components."
  },
  {
    "id": 464,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly type the props of a dynamic Server Component page in Next.js 15+.",
    "code_snippet": "export default async function BlogPost(\n  props: { params: _______<{ slug: string }> }\n) {\n  const { slug } = await props.params;\n}",
    "options": ["Promise", "Awaited", "Async", "Resolve"],
    "correct_answer": "Promise",
    "explanation": "Because `params` is now a Promise, you must wrap the expected object shape in `Promise<{ slug: string }>` to satisfy TypeScript, allowing you to safely `await` it inside the component body."
  },
  {
    "id": 465,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Metadata API (Static)",
    "question": "How do you define static SEO metadata (like title and description) for a page in the App Router?",
    "code_snippet": null,
    "options": ["Using the `<Head>` component from `next/head`", "By exporting a `metadata` object from the `page.tsx` or `layout.tsx` file", "By using the `useMetadata()` hook", "By adding a `meta.json` file"],
    "correct_answer": "By exporting a `metadata` object from the `page.tsx` or `layout.tsx` file",
    "explanation": "The Metadata API replaces `next/head`. You simply write `export const metadata = { title: 'My Page' };` and Next.js automatically injects the correct `<meta>` tags into the `<head>` of the HTML document."
  },
  {
    "id": 466,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Metadata API (Dynamic)",
    "question": "If you need to generate metadata based on dynamic route parameters (e.g., the blog post title), what must you export?",
    "code_snippet": null,
    "options": ["export const metadata", "export async function generateMetadata(props)", "export function getStaticProps()", "export const dynamicMetadata"],
    "correct_answer": "export async function generateMetadata(props)",
    "explanation": "`generateMetadata` is an async function that receives `params` and `searchParams`. It allows you to fetch data from your database and return a metadata object, ensuring the `<title>` tag matches the exact content of the page."
  },
  {
    "id": 467,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Linking (next/link)",
    "question": "Why is it crucial to use the `<Link>` component from `next/link` instead of a standard HTML `<a>` tag for internal navigation?",
    "code_snippet": null,
    "options": ["It looks better", "It enables client-side prefetching and smooth transitions without a full page reload", "It automatically adds CSS styles", "It is required for TypeScript to compile"],
    "correct_answer": "It enables client-side prefetching and smooth transitions without a full page reload",
    "explanation": "When a `<Link>` enters the viewport, Next.js automatically prefetches the code and data for the linked route in the background, making navigation feel instant."
  },
  {
    "id": 468,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Image Optimization (next/image)",
    "question": "What TypeScript error will you encounter if you use the `next/image` component without providing `width` and `height` props (or a `fill` prop)?",
    "code_snippet": null,
    "options": ["No error, it works fine", "TypeScript will flag it as missing required props to prevent Cumulative Layout Shift (CLS)", "It throws a runtime 500 error", "It automatically defaults to 100x100"],
    "correct_answer": "TypeScript will flag it as missing required props to prevent Cumulative Layout Shift (CLS)",
    "explanation": "Next.js enforces explicit dimensions at compile-time to reserve space for the image before it loads. This prevents the page layout from jumping around (CLS) when the image finally renders, which is a major Core Web Vital."
  },
  {
    "id": 469,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Server Actions (Concept)",
    "question": "What is a 'Server Action' in Next.js, and how is it defined in TypeScript?",
    "code_snippet": null,
    "options": ["A REST API endpoint", "An async function marked with the `'use server'` directive that can be called directly from Client Components to mutate server-side state", "A database migration script", "A background cron job"],
    "correct_answer": "An async function marked with the `'use server'` directive that can be called directly from Client Components to mutate server-side state",
    "explanation": "Server Actions eliminate the need to manually create API routes for form submissions. You write an async function, add `'use server'`, and pass it directly to a `<form action={...}>` or call it from an event handler."
  },
  {
    "id": 470,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "What is the core paradigm shift when moving from a traditional React SPA to the Next.js App Router?",
    "code_snippet": null,
    "options": ["You must stop using TypeScript", "You transition from 'fetching data on the client after render' to 'fetching data on the server during render', treating the server as the source of truth", "You must use Redux for all state", "You can no longer use CSS"],
    "correct_answer": "You transition from 'fetching data on the client after render' to 'fetching data on the server during render', treating the server as the source of truth",
    "explanation": "The App Router embraces the server. By default, your components live on the server, have direct access to your database, and send only the final HTML to the client. This results in faster load times, better SEO, and a drastically simplified data-fetching story."
  }
]
[
  {
    "id": 471,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Server Actions (revalidatePath)",
    "question": "After mutating data in a Server Action (e.g., creating a new blog post), how do you tell Next.js to purge the cached data for a specific route so it refetches on the next visit?",
    "code_snippet": null,
    "options": ["revalidateRoute()", "revalidatePath()", "clearCache()", "invalidateRoute()"],
    "correct_answer": "revalidatePath()",
    "explanation": "Imported from `next/cache`, `revalidatePath('/blog')` tells the Next.js server to invalidate the cached data for that specific route. The next time a user visits `/blog`, the Server Component will execute fresh database queries."
  },
  {
    "id": 472,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Server Actions (redirect)",
    "question": "Fill in the blank to correctly redirect a user to the dashboard after a successful form submission inside a Server Action.",
    "code_snippet": "import { _______ } from 'next/navigation';\n\nexport async function createPost(formData: FormData) {\n  // ... save to DB\n  redirect('/dashboard');\n}",
    "options": ["redirect", "navigate", "push", "replace"],
    "correct_answer": "redirect",
    "explanation": "The `redirect` function throws a special Next.js error that halts the current execution and triggers a navigation on the client. It works seamlessly in both Server Components and Server Actions."
  },
  {
    "id": 473,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Server Actions (Arguments vs FormData)",
    "question": "When calling a Server Action from a Client Component event handler (not a `<form>`), how can you pass complex typed data to it?",
    "code_snippet": null,
    "options": ["You can only pass FormData", "You can pass serializable arguments directly like `myAction({ id: 1, name: 'Alice' })`", "You must use a REST API", "You can only pass strings"],
    "correct_answer": "You can pass serializable arguments directly like `myAction({ id: 1, name: 'Alice' })`",
    "explanation": "While `<form>` submissions naturally pass `FormData`, you can invoke Server Actions like standard async functions from `onClick` handlers. TypeScript will enforce that the arguments you pass match the function's signature, provided they are JSON-serializable."
  },
  {
    "id": 474,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Middleware (Execution Environment)",
    "question": "Where does Next.js Middleware execute?",
    "code_snippet": null,
    "options": ["On the Node.js server runtime", "On the Edge Runtime (close to the user)", "In the browser", "In a Web Worker"],
    "correct_answer": "On the Edge Runtime (close to the user)",
    "explanation": "Middleware runs on the Edge Runtime, meaning it executes in data centers geographically close to the user. This allows for ultra-low latency authentication checks, A/B testing, and geolocation routing before the request even hits your main server."
  },
  {
    "id": 475,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Middleware (Matcher)",
    "question": "How do you restrict Middleware to only run on specific routes (e.g., `/dashboard/*`) to avoid slowing down static pages?",
    "code_snippet": null,
    "options": ["Using an `if` statement inside the middleware function", "By exporting a `matcher` configuration array from the middleware file", "By using the `@Route` decorator", "You cannot restrict it"],
    "correct_answer": "By exporting a `matcher` configuration array from the middleware file",
    "explanation": "By exporting `export const config = { matcher: ['/dashboard/:path*'] }`, Next.js optimizes the Edge function so it only wakes up for requests matching those specific paths, saving compute resources."
  },
  {
    "id": 476,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Middleware (NextResponse)",
    "question": "What does calling `NextResponse.next()` do in a Middleware function?",
    "code_snippet": null,
    "options": ["It cancels the request", "It allows the request to continue to the route handler/page", "It redirects the user to the homepage", "It throws a 500 error"],
    "correct_answer": "It allows the request to continue to the route handler/page",
    "explanation": "If your Middleware logic determines that the user is allowed to proceed (e.g., they have a valid auth cookie), you call `NextResponse.next()` to pass the request down the pipeline to the actual page or API route."
  },
  {
    "id": 477,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Middleware (Cookies)",
    "question": "Fill in the blank to correctly read a cookie named 'theme' inside a Middleware function.",
    "code_snippet": "export function middleware(request: NextRequest) {\n  const theme = request._______.get('theme');\n}",
    "options": ["headers", "cookies", "query", "body"],
    "correct_answer": "cookies",
    "explanation": "The `NextRequest` object provides a typed `.cookies` API. `request.cookies.get('theme')` returns a typed object containing the cookie's value, allowing you to rewrite the response or set headers based on user preferences."
  },
  {
    "id": 478,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Caching (Fetch Revalidation)",
    "question": "Fill in the blank to configure a `fetch` request in a Server Component to revalidate the cached data every 60 seconds.",
    "code_snippet": "const data = await fetch('https://api.com/data', {\n  _______: { revalidate: 60 }\n});",
    "options": ["cache", "next", "options", "revalidate"],
    "correct_answer": "next",
    "explanation": "The `next` extension allows you to pass Next.js specific caching rules to the native `fetch` API. `next: { revalidate: 60 }` creates a time-based cache that automatically refreshes in the background every minute."
  },
  {
    "id": 479,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Caching (Opting Out)",
    "question": "Which `fetch` option completely opts out of the Next.js Data Cache, forcing a fresh request on every single visit?",
    "code_snippet": null,
    "options": ["`cache: 'no-cache'`", "`cache: 'no-store'`", "`next: { revalidate: 0 }`", "`cache: 'force-dynamic'`"],
    "correct_answer": "`cache: 'no-store'`",
    "explanation": "While `no-cache` still stores the response but checks for validity, `no-store` tells Next.js to never cache the result at all. It is the equivalent of the old `getServerSideProps` behavior, ensuring the data is always fresh."
  },
  {
    "id": 480,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Route Handlers (Concept)",
    "question": "What is the purpose of a `route.ts` file in the App Router?",
    "code_snippet": null,
    "options": ["It defines a React page", "It creates a backend API endpoint (REST/GraphQL) that handles HTTP requests directly", "It defines middleware", "It handles static assets"],
    "correct_answer": "It creates a backend API endpoint (REST/GraphQL) that handles HTTP requests directly",
    "explanation": "If you need to build a public API, handle webhooks, or return non-HTML responses (like XML or raw JSON), you use a Route Handler. It replaces the legacy `pages/api` directory."
  },
  {
    "id": 481,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Route Handlers (Typing Request)",
    "question": "What is the standard TypeScript type for the `request` parameter in a Route Handler?",
    "code_snippet": null,
    "options": ["`NextRequest`", "`Request` (from Web API) or `NextRequest`", "`Express.Request`", "`Http.IncomingMessage`"],
    "correct_answer": "`Request` (from Web API) or `NextRequest`",
    "explanation": "Route Handlers use the standard Web `Request` API. Next.js extends this with `NextRequest`, which adds convenient methods for reading cookies, headers, and Next.js specific routing data."
  },
  {
    "id": 482,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "topic": "Route Handlers (Returning JSON)",
    "question": "Fill in the blank to correctly return a JSON response from a Route Handler.",
    "code_snippet": "export async function GET() {\n  return Response._______({ message: 'Hello World' });\n}",
    "options": ["send", "json", "text", "return"],
    "correct_answer": "json",
    "explanation": "The Web API `Response.json()` static method automatically serializes the object to a JSON string and sets the `Content-Type: application/json` header for you."
  },
  {
    "id": 483,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Route Handlers (Streaming)",
    "question": "How can you stream a large dataset or an AI text response from a Route Handler?",
    "code_snippet": null,
    "options": ["By returning a `ReadableStream` inside a `Response` object", "By using `res.write()`", "By using `useEffect`", "You cannot stream from Route Handlers"],
    "correct_answer": "By returning a `ReadableStream` inside a `Response` object",
    "explanation": "Because Route Handlers use the Web API, you can return `new Response(stream)` where `stream` is a `ReadableStream`. This is the foundation for building AI chat endpoints (like Vercel AI SDK) that stream tokens to the client."
  },
  {
    "id": 484,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Auth (Protecting Server Components)",
    "question": "What is the most secure way to protect a Server Component page so only authenticated users can view it?",
    "code_snippet": null,
    "options": ["Hiding the UI with CSS", "Checking the user's session/cookie directly inside the Server Component and redirecting if invalid", "Using a Client Component `useEffect`", "Using `localStorage`"],
    "correct_answer": "Checking the user's session/cookie directly inside the Server Component and redirecting if invalid",
    "explanation": "Because Server Components run on the server, you can read secure, HTTP-only cookies before any HTML is generated. If the session is invalid, you call `redirect('/login')`, ensuring the protected data never even reaches the client's browser."
  },
  {
    "id": 485,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Auth (Protecting Server Actions)",
    "question": "Why is it critical to verify the user's session INSIDE the Server Action function, even if the UI button is hidden from unauthenticated users?",
    "code_snippet": null,
    "options": ["Because Server Actions can be invoked directly via network requests, bypassing the UI", "Because it makes the code run faster", "Because TypeScript requires it", "It is not necessary"],
    "correct_answer": "Because Server Actions can be invoked directly via network requests, bypassing the UI",
    "explanation": "Security rule #1: Never trust the client. A malicious user can open DevTools and call your Server Action directly. You must re-verify the session inside the action: `const session = await auth(); if (!session) throw new Error('Unauthorized');`."
  },
  {
    "id": 486,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Environment Variables",
    "question": "What happens if you prefix an environment variable with `NEXT_PUBLIC_` in Next.js?",
    "code_snippet": null,
    "options": ["It remains strictly on the server", "It is embedded into the client-side JavaScript bundle and exposed to the browser", "It is encrypted", "It is only available in Middleware"],
    "correct_answer": "It is embedded into the client-side JavaScript bundle and exposed to the browser",
    "explanation": "Any variable starting with `NEXT_PUBLIC_` is injected into the client bundle at build time. NEVER put secret API keys or database URLs in these variables, as anyone can view them by inspecting the page source!"
  },
  {
    "id": 487,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Database (Prisma Singleton)",
    "question": "Why is it a best practice to store the Prisma Client instance on `globalThis` during development?",
    "code_snippet": null,
    "options": ["To make it run faster", "To prevent exhausting the database connection pool during hot-reloading (Fast Refresh)", "To encrypt the connection", "To bypass TypeScript checks"],
    "explanation": "In development, Next.js recompiles files on every save. If you create a `new PrismaClient()` in a module, it creates a new connection pool every time, quickly hitting your database's connection limit. Storing it on `globalThis` preserves the single instance across hot-reloads."
  },
  {
    "id": 488,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Data Fetching (Parallelization)",
    "question": "How do you ensure multiple independent database queries in a Server Component run in parallel rather than sequentially?",
    "code_snippet": null,
    "options": ["Using `await` on each query one by one", "Wrapping the queries in `Promise.all([...])`", "Using `useEffect`", "Using React Context"],
    "correct_answer": "Wrapping the queries in `Promise.all([...])`",
    "explanation": "If you `await` query A, then `await` query B, they run sequentially. By using `const [users, posts] = await Promise.all([getUsers(), getPosts()])`, TypeScript and the JS runtime execute both database calls simultaneously, drastically reducing page load time."
  },
  {
    "id": 489,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Error Handling (Global Error)",
    "question": "What file do you create at the root of the `app/` directory to catch errors that crash the root layout or global shell?",
    "code_snippet": null,
    "options": ["`error.tsx`", "`global-error.tsx`", "`crash.tsx`", "`fallback.tsx`"],
    "correct_answer": "`global-error.tsx`",
    "explanation": "Standard `error.tsx` files only catch errors in their nested route segment. If the root `layout.tsx` crashes, the entire app goes blank. `global-error.tsx` acts as the ultimate fallback to catch and recover from catastrophic failures."
  },
  {
    "id": 490,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (Philosophy)",
    "question": "What is the core philosophy of building Full-Stack TypeScript applications with Next.js?",
    "code_snippet": null,
    "options": ["Treating the server and client as completely separate entities", "Leveraging the server as the source of truth, using TypeScript to create an unbroken type-safe boundary from the database to the UI, and minimizing client-side JavaScript", "Writing all logic in the browser", "Avoiding databases"],
    "correct_answer": "Leveraging the server as the source of truth, using TypeScript to create an unbroken type-safe boundary from the database to the UI, and minimizing client-side JavaScript",
    "explanation": "Next.js allows you to write TypeScript that runs on the database, the server, the Edge, and the client. Mastering it means knowing exactly WHERE your code runs, and using the type system to guarantee safety across all those boundaries."
  }
]
[
  {
    "id": 491,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Optimization (next/font)",
    "question": "How does the `next/font` package guarantee zero Cumulative Layout Shift (CLS) for custom web fonts?",
    "code_snippet": null,
    "options": ["It loads fonts asynchronously after the page renders", "It downloads fonts at build time, self-hosts them, and uses CSS `size-adjust` to perfectly match the fallback font metrics", "It converts all fonts to SVG", "It disables font loading on mobile devices"],
    "correct_answer": "It downloads fonts at build time, self-hosts them, and uses CSS `size-adjust` to perfectly match the fallback font metrics",
    "explanation": "By self-hosting the font files and automatically generating CSS variables that match the exact dimensions of the fallback system font, the browser reserves the exact right amount of space before the custom font loads, eliminating visual jumping."
  },
  {
    "id": 492,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Optimization (next/og)",
    "question": "How do you generate dynamic Open Graph (social media preview) images at the Edge in the App Router?",
    "code_snippet": null,
    "options": ["By using the `<meta property='og:image'>` tag with a static URL", "By returning an `ImageResponse` from `next/og` inside a `route.tsx` or `opengraph-image.tsx` file", "By using a third-party API like Cloudinary", "You cannot generate dynamic OG images in Next.js"],
    "correct_answer": "By returning an `ImageResponse` from `next/og` inside a `route.tsx` or `opengraph-image.tsx` file",
    "explanation": "`ImageResponse` allows you to write JSX (HTML/CSS) that gets converted into a PNG image on the Edge Runtime. You can dynamically inject database data (like a blog post title) directly into the image before it's served to Twitter or LinkedIn."
  },
  {
    "id": 493,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Optimization (next/script)",
    "question": "What is the purpose of the `strategy` prop in the `next/script` component?",
    "code_snippet": null,
    "options": ["It minifies the script", "It controls exactly when the script loads relative to the page hydration (e.g., `beforeInteractive`, `afterInteractive`, `lazyOnload`)", "It determines which server the script runs on", "It converts the script to TypeScript"],
    "correct_answer": "It controls exactly when the script loads relative to the page hydration (e.g., `beforeInteractive`, `afterInteractive`, `lazyOnload`)",
    "explanation": "Loading heavy third-party scripts (like analytics or chat widgets) can block the main thread. The `strategy` prop allows you to defer non-critical scripts until after the page is interactive, drastically improving Core Web Vitals."
  },
  {
    "id": 494,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Routing (Parallel Routes)",
    "question": "What is the syntax for defining 'Parallel Routes' in the App Router, allowing you to render multiple pages in the same layout simultaneously?",
    "code_snippet": null,
    "options": ["Using the `&` prefix (e.g., `&modal`)", "Using the `@` prefix (e.g., `@modal` or `@team`)", "Using the `~` prefix", "Using the `#` prefix"],
    "correct_answer": "Using the `@` prefix (e.g., `@modal` or `@team`)",
    "explanation": "Parallel Routes allow you to conditionally or simultaneously render multiple pages within the same layout. The `@folder` convention creates a 'slot' that the parent `layout.tsx` can render alongside the default `children` prop."
  },
  {
    "id": 495,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Routing (Intercepting Routes)",
    "question": "How do you create an Intercepting Route (e.g., showing a photo in a modal when clicked from a feed, but keeping the URL as `/feed`)?",
    "code_snippet": null,
    "options": ["Using the `(.)` convention (e.g., `app/feed/(.)photo/[id]/page.tsx`)", "Using the `..` convention", "Using the `*` wildcard", "Using Middleware to rewrite the URL"],
    "correct_answer": "Using the `(.)` convention (e.g., `app/feed/(.)photo/[id]/page.tsx`)",
    "explanation": "The `(.)` convention tells Next.js to intercept a route one level above. If the user navigates directly to `/photo/123`, they see the full page. If they click it from `/feed`, Next.js intercepts the navigation and loads it as a modal overlay instead."
  },
  {
    "id": 496,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Caching (Full Route vs Data Cache)",
    "question": "What is the difference between the 'Full Route Cache' and the 'Data Cache' in Next.js?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "The Full Route Cache stores the rendered HTML and RSC payload; the Data Cache only stores the results of `fetch` requests", "The Data Cache is for client-side state", "The Full Route Cache is only for static assets"],
    "correct_answer": "The Full Route Cache stores the rendered HTML and RSC payload; the Data Cache only stores the results of `fetch` requests",
    "explanation": "When you visit a cached page, Next.js serves the pre-rendered HTML/RSC from the Full Route Cache. If that cache is invalidated, it uses the Data Cache to retrieve the `fetch` data without hitting the external database again, re-rendering the page on the server."
  },
  {
    "id": 497,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly define a function that statically generates all possible paths for a dynamic route at build time.",
    "code_snippet": "export async function _______() {\n  return [{ slug: 'post-1' }, { slug: 'post-2' }];\n}",
    "options": ["getStaticPaths", "generateStaticParams", "generatePaths", "staticRoutes"],
    "correct_answer": "generateStaticParams",
    "explanation": "In the App Router, `generateStaticParams` replaces the Pages Router's `getStaticPaths`. By returning an array of objects matching your dynamic segment (e.g., `slug`), Next.js pre-renders all those specific routes into static HTML at build time."
  },
  {
    "id": 498,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Internationalization (i18n)",
    "question": "How is internationalization (i18n) typically structured in the Next.js App Router?",
    "code_snippet": null,
    "options": ["Using a centralized `i18n.json` file", "By creating a dynamic `[lang]` segment (e.g., `app/[lang]/page.tsx`) and using Middleware to detect and redirect based on the user's locale", "Using the `<I18nProvider>` component", "Next.js does not support i18n in the App Router"],
    "correct_answer": "By creating a dynamic `[lang]` segment (e.g., `app/[lang]/page.tsx`) and using Middleware to detect and redirect based on the user's locale",
    "explanation": "The `[lang]` segment acts as the root for all localized content. Middleware intercepts the initial request, checks the `Accept-Language` header or cookies, and redirects the user to the correct `/en` or `/fr` path."
  },
  {
    "id": 499,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Testing (Server Actions)",
    "question": "What is the recommended architectural pattern for testing Server Actions in a Next.js application?",
    "code_snippet": null,
    "options": ["Mocking the entire `next/navigation` module", "Extracting the core business logic into a pure, testable TypeScript function, and testing the UI interaction separately", "Using Cypress to click the submit button", "Server Actions cannot be tested"],
    "correct_answer": "Extracting the core business logic into a pure, testable TypeScript function, and testing the UI interaction separately",
    "explanation": "Server Actions run on the server and interact with databases, making them hard to unit test directly in a browser environment. By extracting the logic into a pure function (e.g., `createUserInDB(data)`), you can easily unit test the logic with Vitest/Jest, and use Playwright to test the actual form submission."
  },
  {
    "id": 500,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Testing (Mocking next/navigation)",
    "question": "When unit testing a Client Component that uses `useRouter` from `next/navigation`, what must you do to prevent the test runner from crashing?",
    "code_snippet": null,
    "options": ["Nothing, it works out of the box", "Mock the `next/navigation` module using `vi.mock` or `jest.mock` to provide fake implementations of `push`, `replace`, etc.", "Import `useRouter` from `react-router-dom` instead", "Disable TypeScript for the test file"],
    "correct_answer": "Mock the `next/navigation` module using `vi.mock` or `jest.mock` to provide fake implementations of `push`, `replace`, etc.",
    "explanation": "Test runners like Vitest or Jest run in a Node environment, not a browser. `next/navigation` relies on browser APIs. Mocking it allows you to assert that `router.push('/dashboard')` was called when a button is clicked."
  },
  {
    "id": 501,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Standalone Output)",
    "question": "What does setting `output: 'standalone'` in `next.config.js` do during the build process?",
    "code_snippet": null,
    "options": ["It deploys the app to Vercel automatically", "It creates a minimal `.next/standalone` folder containing only the necessary files to run the app in a Docker container, without needing `node_modules`", "It converts the app to a static HTML site", "It removes all TypeScript types"],
    "correct_answer": "It creates a minimal `.next/standalone` folder containing only the necessary files to run the app in a Docker container, without needing `node_modules`",
    "explanation": "When deploying to AWS, Google Cloud, or a custom Docker setup, you don't want to ship the entire 500MB `node_modules` folder. The standalone output traces exactly which dependencies are needed and bundles them into a tiny, production-ready folder."
  },
  {
    "id": 502,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly force a specific Route Handler or Page to run on the Edge Runtime instead of the default Node.js runtime.",
    "code_snippet": "export const _______ = 'edge';\n\nexport async function GET() { ... }",
    "options": ["runtime", "environment", "server", "mode"],
    "correct_answer": "runtime",
    "explanation": "By exporting `runtime = 'edge'`, you tell Next.js to execute this specific file on the Edge Runtime. This is perfect for low-latency tasks like geolocation routing, A/B testing, or lightweight API responses, but it restricts you from using Node.js-only APIs."
  },
  {
    "id": 503,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Edge Cases (Dynamic Code)",
    "question": "Why does Next.js throw a build error if you use `eval()` or dynamic code execution inside a Server Component?",
    "code_snippet": null,
    "options": ["Because `eval()` is deprecated in JavaScript", "Because Server Components are statically analyzed and pre-rendered; dynamic code breaks this security and caching model", "Because TypeScript doesn't support `eval()`", "Because it slows down the client-side bundle"],
    "correct_answer": "Because Server Components are statically analyzed and pre-rendered; dynamic code breaks this security and caching model",
    "explanation": "Next.js relies on static analysis to determine exactly what code runs on the server vs. the client, and to safely cache the output. `eval()` introduces unpredictable runtime behavior that makes static analysis and secure caching impossible."
  },
  {
    "id": 504,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Edge Cases ('use server' scope)",
    "question": "Why does Next.js throw an error if you try to use a React Hook (like `useState`) inside a file marked with the `'use server'` directive at the top?",
    "code_snippet": null,
    "options": ["Because `'use server'` marks the entire file as a Server Action/Server-side module, which executes outside the React client rendering lifecycle", "Because Hooks are deprecated", "Because TypeScript doesn't allow Hooks in async functions", "Because the file is too large"],
    "correct_answer": "Because `'use server'` marks the entire file as a Server Action/Server-side module, which executes outside the React client rendering lifecycle",
    "explanation": "React Hooks are strictly tied to the client-side rendering tree. A `'use server'` file is a backend module that runs on the Node.js server. Mixing the two violates the fundamental boundary between the client and the server."
  },
  {
    "id": 505,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Caching (revalidateTag)",
    "question": "How do you invalidate a specific subset of cached data across multiple different routes simultaneously?",
    "code_snippet": null,
    "options": ["By calling `revalidatePath('/')`", "By tagging the `fetch` request with `next: { tags: ['my-tag'] }` and calling `revalidateTag('my-tag')` in a Server Action", "By clearing the browser cache", "By restarting the server"],
    "correct_answer": "By tagging the `fetch` request with `next: { tags: ['my-tag'] }` and calling `revalidateTag('my-tag')` in a Server Action",
    "explanation": "If you update a 'User' in the database, you might need to purge the cache for the `/profile` page, the `/settings` page, and the `/admin/users` page. By tagging all those `fetch` calls with `'user-data'`, a single `revalidateTag('user-data')` purges them all instantly."
  },
  {
    "id": 506,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Performance (Partial Prerendering)",
    "question": "What is 'Partial Prerendering' (PPR) in Next.js?",
    "code_snippet": null,
    "options": ["A way to only prerender CSS", "A rendering model that serves a static shell of the page instantly, then streams in the dynamic parts (like user data) in the exact same request", "A tool to compress images", "A way to disable caching"],
    "correct_answer": "A rendering model that serves a static shell of the page instantly, then streams in the dynamic parts (like user data) in the exact same request",
    "explanation": "PPR combines the best of static and dynamic rendering. The user sees the static layout (header, sidebar, skeleton) in milliseconds, while the dynamic content (personalized feed) streams in and 'pops' into place without a full page reload."
  },
  {
    "id": 507,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Security (CSRF Protection)",
    "question": "How do Server Actions inherently protect against CSRF (Cross-Site Request Forgery) attacks compared to traditional REST APIs?",
    "code_snippet": null,
    "options": ["They use GET requests instead of POST", "They use strict POST requests with framework-level CSRF tokens and same-origin checks built into Next.js", "They require a CAPTCHA", "They do not protect against CSRF"],
    "correct_answer": "They use strict POST requests with framework-level CSRF tokens and same-origin checks built into Next.js",
    "explanation": "Because Server Actions are tied to the React component tree and use secure POST requests, Next.js automatically validates the origin and injects CSRF tokens, making it incredibly difficult for a malicious third-party site to forge a request."
  },
  {
    "id": 508,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Monorepos)",
    "question": "What is the primary benefit of using a monorepo tool like Turborepo or Nx with a Next.js application?",
    "code_snippet": null,
    "options": ["It makes the CSS load faster", "It allows you to share TypeScript types, UI components, and configuration across multiple Next.js apps and backend packages with zero redundant builds", "It replaces the need for a database", "It automatically deploys to AWS"],
    "correct_answer": "It allows you to share TypeScript types, UI components, and configuration across multiple Next.js apps and backend packages with zero redundant builds",
    "explanation": "In a monorepo, you can have a `packages/ui` folder that your marketing site and your dashboard both import from. If you change a button in `packages/ui`, TypeScript instantly updates both apps, and Turborepo only rebuilds what actually changed."
  },
  {
    "id": 509,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Type Safety (Drizzle ORM)",
    "question": "How do modern TypeScript ORMs like Drizzle enhance the Full-Stack experience compared to traditional ORMs like Prisma?",
    "code_snippet": null,
    "options": ["They are written in Rust", "They infer the exact database schema types directly from SQL-like schema definitions, ensuring 100% end-to-end type safety from the DB query to the UI component", "They don't require a database", "They automatically generate REST APIs"],
    "correct_answer": "They infer the exact database schema types directly from SQL-like schema definitions, ensuring 100% end-to-end type safety from the DB query to the UI component",
    "explanation": "With Drizzle, if you change a column name in your database schema file, TypeScript will immediately highlight every single Server Component and Server Action that tries to access the old column name, preventing runtime database errors."
  },
  {
    "id": 510,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Part 3 Wrap-up (The Full-Stack Zen)",
    "question": "What is the ultimate hallmark of a Full-Stack TypeScript/Next.js expert?",
    "code_snippet": null,
    "options": ["Memorizing every Next.js configuration option", "Understanding the exact boundary between the Server, the Edge, and the Client, and using TypeScript to create a seamless, type-safe data flow across all three without ever writing a manual API endpoint", "Writing all code in the browser", "Avoiding databases entirely"],
    "correct_answer": "Understanding the exact boundary between the Server, the Edge, and the Client, and using TypeScript to create a seamless, type-safe data flow across all three without ever writing a manual API endpoint",
    "explanation": "Mastering Next.js means you stop thinking in terms of 'frontend' and 'backend'. You simply think in terms of 'data flow'. TypeScript acts as the glue that ensures your database schema, your server logic, and your UI components are all speaking the exact same language."
  }
]
[
  {
    "id": 511,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Middleware (URL Rewriting)",
    "question": "How do you internally rewrite a URL in Middleware (e.g., showing `/about-us` content when the user visits `/about`) without changing the URL in the browser's address bar?",
    "code_snippet": null,
    "options": ["NextResponse.redirect()", "NextResponse.rewrite()", "NextResponse.next()", "NextResponse.json()"],
    "correct_answer": "NextResponse.rewrite()",
    "explanation": "`NextResponse.rewrite(new URL('/about-us', request.url))` fetches the content from the target route but keeps the original URL (`/about`) visible to the user. This is perfect for A/B testing or legacy URL migrations."
  },
  {
    "id": 512,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Vercel AI SDK (useChat)",
    "question": "When using the Vercel AI SDK's `useChat` hook in a Client Component, what does the `messages` array contain, and how is it typed?",
    "code_snippet": null,
    "options": ["An array of raw strings", "An array of `Message` objects containing `id`, `role` ('user' | 'assistant'), and `content`", "A single concatenated string", "A Promise of the final response"],
    "correct_answer": "An array of `Message` objects containing `id`, `role` ('user' | 'assistant'), and `content`",
    "explanation": "The `Message` type ensures strict type safety when mapping over the chat history to render UI bubbles, guaranteeing that you are handling the correct roles and content structures."
  },
  {
    "id": 513,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Vercel AI SDK (streamText)",
    "question": "How do you stream an AI response from a Next.js Route Handler using the Vercel AI SDK?",
    "code_snippet": null,
    "options": ["By returning a standard JSON Response", "By calling `streamText()` and returning `.toDataStreamResponse()`", "By using `useEffect` to poll the server", "By using Server Actions only"],
    "correct_answer": "By calling `streamText()` and returning `.toDataStreamResponse()`",
    "explanation": "`streamText` handles the complex protocol of streaming tokens from the LLM provider. `.toDataStreamResponse()` converts it into a standard Web `Response` that the client-side `useChat` hook knows how to parse and render token-by-token."
  },
  {
    "id": 514,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Performance (next/dynamic)",
    "question": "How do you prevent a heavy Client Component (like a 3D map or rich text editor) from being included in the initial server-rendered HTML?",
    "code_snippet": null,
    "options": ["Using React.memo", "Using `next/dynamic` with the `ssr: false` option", "Using `useEffect`", "Using `React.lazy`"],
    "correct_answer": "Using `next/dynamic` with the `ssr: false` option",
    "explanation": "`dynamic(() => import('./Map'), { ssr: false })` tells Next.js to completely skip rendering this component on the server. It will only load and render in the browser, saving server compute and reducing initial HTML size."
  },
  {
    "id": 515,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Observability (instrumentation.ts)",
    "question": "What is the purpose of the `instrumentation.ts` file in the root of a Next.js project?",
    "code_snippet": null,
    "options": ["To define global CSS", "To register OpenTelemetry or custom tracing/logging logic that runs exactly once when the Next.js server starts", "To define Middleware", "To configure environment variables"],
    "correct_answer": "To register OpenTelemetry or custom tracing/logging logic that runs exactly once when the Next.js server starts",
    "explanation": "The `register()` function exported from `instrumentation.ts` is the perfect place to initialize Datadog, Sentry, or OpenTelemetry before any routes are served, ensuring 100% observability coverage."
  },
  {
    "id": 516,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Security (Content Security Policy)",
    "question": "How do you configure a strict Content Security Policy (CSP) to prevent XSS attacks in a Next.js application?",
    "code_snippet": null,
    "options": ["By adding a `<meta>` tag in `layout.tsx`", "By configuring the `headers()` function in `next.config.js` to inject the `Content-Security-Policy` header", "By using Middleware", "By installing an npm package"],
    "correct_answer": "By configuring the `headers()` function in `next.config.js` to inject the `Content-Security-Policy` header",
    "explanation": "Setting CSP headers at the `next.config.js` level ensures that every single response from your application includes the strict security rules, blocking unauthorized inline scripts and external resource loads."
  },
  {
    "id": 517,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Server Actions vs Route Handlers)",
    "question": "When should you choose a Server Action over a Route Handler (`route.ts`)?",
    "code_snippet": null,
    "options": ["When you need to build a public REST API for third parties", "When you need to mutate server state directly from a React component or form without managing manual `fetch` calls and loading states", "When you need to stream a large file", "When you need to return XML"],
    "correct_answer": "When you need to mutate server state directly from a React component or form without managing manual `fetch` calls and loading states",
    "explanation": "Server Actions are for internal, UI-driven mutations (like form submissions). Route Handlers are for external, HTTP-driven endpoints (like webhooks, public APIs, or streaming binary data)."
  },
  {
    "id": 518,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Testing (Playwright E2E)",
    "question": "What is the primary advantage of using Playwright over Cypress for End-to-End testing a Next.js App Router application?",
    "code_snippet": null,
    "options": ["Playwright is written in TypeScript natively", "Playwright supports multi-browser testing (Chromium, WebKit, Firefox) and parallel test execution out-of-the-box, matching Next.js's modern web standards", "Playwright doesn't require a browser", "Playwright automatically mocks databases"],
    "correct_answer": "Playwright supports multi-browser testing (Chromium, WebKit, Firefox) and parallel test execution out-of-the-box, matching Next.js's modern web standards",
    "explanation": "Because Next.js heavily utilizes modern Web APIs (like Server Components and Streaming), Playwright's robust, multi-browser engine ensures your app works flawlessly across Safari, Chrome, and Firefox."
  },
  {
    "id": 519,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "DX (Next.js ESLint Plugin)",
    "question": "What does the `next/core-web-vitals` ESLint configuration enforce?",
    "code_snippet": null,
    "options": ["It enforces TypeScript strict mode", "It extends the recommended Next.js rules and specifically flags patterns that negatively impact LCP, CLS, and INP (Core Web Vitals)", "It formats the code", "It checks for database security"],
    "correct_answer": "It extends the recommended Next.js rules and specifically flags patterns that negatively impact LCP, CLS, and INP (Core Web Vitals)",
    "explanation": "It will warn you if you use `<img>` instead of `<Image>`, or if you use synchronous Google Fonts, directly tying your code quality to real-world performance metrics."
  },
  {
    "id": 520,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Future (React Compiler)",
    "question": "How does the upcoming React Compiler (React 19) change the way we write TypeScript React code in Next.js?",
    "code_snippet": null,
    "options": ["It removes the need for TypeScript", "It automatically memoizes components and hooks at compile-time, drastically reducing the need for manual `useMemo`, `useCallback`, and `React.memo`", "It forces all components to be Server Components", "It disables Server Actions"],
    "correct_answer": "It automatically memoizes components and hooks at compile-time, drastically reducing the need for manual `useMemo`, `useCallback`, and `React.memo`",
    "explanation": "The React Compiler analyzes your TypeScript code and automatically applies memoization where needed. This means developers can write simpler, cleaner code without worrying about the performance cost of unnecessary re-renders."
  },
  {
    "id": 521,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Edge vs Serverless)",
    "question": "What is the fundamental difference between a Vercel Edge Function and a Vercel Serverless Function in Next.js?",
    "code_snippet": null,
    "options": ["Edge Functions run on Node.js; Serverless run on the browser", "Edge Functions run on lightweight V8 isolates globally (fast cold starts, limited APIs); Serverless run on full Node.js containers (slower cold starts, full API access)", "There is no difference", "Edge Functions are deprecated"],
    "correct_answer": "Edge Functions run on lightweight V8 isolates globally (fast cold starts, limited APIs); Serverless run on full Node.js containers (slower cold starts, full API access)",
    "explanation": "Use Edge Functions for Middleware, geolocation, and lightweight auth. Use Serverless Functions for database queries, heavy computation, and complex Node.js operations."
  },
  {
    "id": 522,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Vercel Cron Jobs)",
    "question": "How do you securely verify that a request to a Route Handler is actually coming from Vercel Cron Jobs and not a malicious user?",
    "code_snippet": null,
    "options": ["By checking the user's IP address", "By verifying the `authorization` header against the `CRON_SECRET` environment variable", "By checking the `User-Agent`", "Cron Jobs cannot be secured"],
    "correct_answer": "By verifying the `authorization` header against the `CRON_SECRET` environment variable",
    "explanation": "Vercel automatically injects the `CRON_SECRET` into the `authorization` header of cron requests. You must check `request.headers.get('authorization') === `Bearer ${process.env.CRON_SECRET}`` to prevent unauthorized execution."
  },
  {
    "id": 523,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Next.js 15 (Async Request APIs)",
    "question": "In Next.js 15, the `cookies()` and `headers()` functions imported from `next/headers` have changed. What is the new requirement?",
    "code_snippet": null,
    "options": ["They have been removed", "They are now asynchronous and must be awaited (e.g., `const cookieStore = await cookies()`)", "They now return Promises that cannot be awaited", "They only work in Middleware"],
    "correct_answer": "They are now asynchronous and must be awaited (e.g., `const cookieStore = await cookies()`)",
    "explanation": "This change aligns with the async nature of the App Router and prepares the framework for advanced caching and Partial Prerendering (PPR) by ensuring request data is accessed safely."
  },
  {
    "id": 524,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly type the props of a Server Component that needs to read the search parameters (e.g., `?sort=asc`) in Next.js 15.",
    "code_snippet": "export default async function Page(props: { searchParams: _______<{ sort: string }> }) {\n  const { sort } = await props.searchParams;\n}",
    "options": ["Promise", "Awaited", "Async", "Resolve"],
    "correct_answer": "Promise",
    "explanation": "Just like `params`, `searchParams` is now a Promise in Next.js 15. You must type it as `Promise<{ sort: string }>` and `await` it inside the component body."
  },
  {
    "id": 525,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Colocating Server Actions)",
    "question": "Where is the recommended place to define a Server Action that is only used by a single specific page?",
    "code_snippet": null,
    "options": ["In a global `actions/index.ts` file", "In a separate `actions.ts` file located right next to the `page.tsx` that uses it", "Inside the Client Component", "In a Route Handler"],
    "correct_answer": "In a separate `actions.ts` file located right next to the `page.tsx` that uses it",
    "explanation": "Colocating the action (`app/dashboard/actions.ts`) next to the page (`app/dashboard/page.tsx`) keeps the code tightly coupled to its feature, making it easier to find, test, and delete when the feature is removed."
  },
  {
    "id": 526,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Security (HTTPOnly Cookies)",
    "question": "Why is it critical to store authentication tokens in `HTTPOnly` cookies rather than `localStorage` in a Next.js application?",
    "code_snippet": null,
    "options": ["`localStorage` is too slow", "`HTTPOnly` cookies cannot be accessed by client-side JavaScript, completely neutralizing XSS (Cross-Site Scripting) token theft", "`localStorage` is deprecated", "There is no security difference"],
    "correct_answer": "`HTTPOnly` cookies cannot be accessed by client-side JavaScript, completely neutralizing XSS (Cross-Site Scripting) token theft",
    "explanation": "If an attacker injects a malicious script into your page, they can read `localStorage` and steal the token. They cannot read `HTTPOnly` cookies, keeping the user's session secure."
  },
  {
    "id": 527,
    "level": "intermediate",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Deployment (Vercel Preview Deployments)",
    "question": "What is the primary benefit of Vercel Preview Deployments for a TypeScript/Next.js team?",
    "code_snippet": null,
    "options": ["They replace the need for unit tests", "They automatically deploy a unique, live URL for every single Pull Request, allowing stakeholders to test exact changes before merging", "They compress the database", "They automatically fix TypeScript errors"],
    "correct_answer": "They automatically deploy a unique, live URL for every single Pull Request, allowing stakeholders to test exact changes before merging",
    "explanation": "Preview Deployments bridge the gap between development and production. Designers, PMs, and QA can click a link in the GitHub PR and interact with the exact Server Components and Database changes proposed in the code."
  },
  {
    "id": 528,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Edge Case (Revalidating in Server Actions)",
    "question": "If a Server Action calls `revalidatePath()`, when does the user actually see the updated data?",
    "code_snippet": null,
    "options": ["Immediately, via WebSockets", "On the next full page refresh, or immediately if the action was triggered by a `<form>` submission (which triggers a Router Refresh)", "They must clear their browser cache", "It only updates the server, not the client"],
    "correct_answer": "On the next full page refresh, or immediately if the action was triggered by a `<form>` submission (which triggers a Router Refresh)",
    "explanation": "Next.js automatically performs a 'Router Refresh' after a form-bound Server Action completes, fetching the newly revalidated data from the server and seamlessly patching the React tree without a full browser reload."
  },
  {
    "id": 529,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Architecture (Micro-Frontends)",
    "question": "While Next.js is primarily a monolithic framework, what pattern is used to integrate multiple distinct Next.js apps into a single unified URL experience?",
    "code_snippet": null,
    "options": ["React Context", "Module Federation / Next.js Multi-Zone Architecture", "Redux", "Web Components"],
    "correct_answer": "Module Federation / Next.js Multi-Zone Architecture",
    "explanation": "Multi-Zone allows different teams to own different subpaths (e.g., Team A owns `/docs`, Team B owns `/billing`) and stitches them together at the Edge or via a proxy, enabling massive enterprise scale."
  },
  {
    "id": 530,
    "level": "advanced",
    "module_id": "ts_mod_07_nextjs",
    "module_name": "Next.js & Full-Stack TypeScript",
    "type": "conceptual",
    "topic": "Module 7 Wrap-up (The Full-Stack Zen)",
    "question": "You have now completed the 80-question deep dive into Next.js and Full-Stack TypeScript. What is the ultimate hallmark of a Full-Stack expert?",
    "code_snippet": null,
    "options": ["Memorizing the entire React documentation", "The ability to architect systems where data flows securely and type-safely from the database, through the Edge, the Server, and into the Client, resulting in apps that are blazing fast, accessible, and unbreakable", "Writing all code in a single file", "Avoiding CSS entirely"],
    "correct_answer": "The ability to architect systems where data flows securely and type-safely from the database, through the Edge, the Server, and into the Client, resulting in apps that are blazing fast, accessible, and unbreakable",
    "explanation": "Full-Stack TypeScript is not about knowing every library; it's about mastering the boundaries. You understand exactly where code runs, how data is cached, and how TypeScript acts as the unbreakable contract that holds the entire distributed system together."
  }
]
