[
  {
    "id": 1,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "What is TypeScript?",
    "question": "What is the fundamental difference between JavaScript and TypeScript?",
    "code_snippet": null,
    "options": ["TypeScript is a completely different programming language with its own runtime engine", "TypeScript is a superset of JavaScript that adds static typing and compile-time error checking", "TypeScript runs faster in the browser than JavaScript", "TypeScript removes the need for HTML and CSS"],
    "correct_answer": "TypeScript is a superset of JavaScript that adds static typing and compile-time error checking",
    "explanation": "Any valid JavaScript code is also valid TypeScript code. TS adds a 'type layer' on top of JS, which is completely stripped away (transpiled) before the code ever runs in the browser."
  },
  {
    "id": 2,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Static vs Dynamic Typing",
    "question": "JavaScript is a 'dynamically typed' language. What does this mean?",
    "code_snippet": null,
    "options": ["Variables are locked to a specific type when declared", "Types are checked at compile-time before the code runs", "Variables can hold any type of value, and their type can change at runtime", "It requires a database to store variable types"],
    "correct_answer": "Variables can hold any type of value, and their type can change at runtime",
    "explanation": "In JS, you can write `let x = 5;` and later `x = 'hello';`. TypeScript introduces 'static typing', meaning once `x` is defined as a number, the compiler will throw an error if you try to assign a string to it later."
  },
  {
    "id": 3,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Compile-time vs Runtime",
    "question": "Why is catching errors at 'compile-time' (in TypeScript) vastly superior to catching them at 'runtime' (in JavaScript)?",
    "code_snippet": null,
    "options": ["It makes the final JavaScript file smaller", "It prevents bugs from ever reaching production or the user, because the code won't even compile if there are type mismatches", "It makes the code execute faster in the browser", "It automatically fixes the bugs for you"],
    "correct_answer": "It prevents bugs from ever reaching production or the user, because the code won't even compile if there are type mismatches",
    "explanation": "Runtime errors crash your app while the user is using it. Compile-time errors stop you in your tracks while you are writing code in your IDE, saving massive amounts of debugging time and preventing catastrophic production failures."
  },
  {
    "id": 4,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "The TypeScript Compiler",
    "question": "Fill in the blank with the standard CLI command to compile a TypeScript file (`app.ts`) into a JavaScript file (`app.js`).",
    "code_snippet": "_______ app.ts",
    "options": ["ts-compile", "tsc", "typescript", "node"],
    "correct_answer": "tsc",
    "explanation": "`tsc` stands for TypeScript Compiler. Running `tsc filename.ts` reads your TS code, checks for type errors, and outputs standard, browser-readable JavaScript."
  },
  {
    "id": 5,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "tsconfig.json",
    "question": "What is the purpose of the `tsconfig.json` file in a TypeScript project?",
    "code_snippet": null,
    "options": ["It stores the database credentials", "It configures the TypeScript compiler options, such as the target JS version, strictness rules, and which files to include/exclude", "It is the main entry point for the application", "It formats the code automatically"],
    "correct_answer": "It configures the TypeScript compiler options, such as the target JS version, strictness rules, and which files to include/exclude",
    "explanation": "When you run `tsc` without arguments, it looks for `tsconfig.json` in the root directory. This file is the absolute source of truth for how your TypeScript project should be compiled and checked."
  },
  {
    "id": 6,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "ts-node",
    "question": "What does the `ts-node` package do?",
    "code_snippet": null,
    "options": ["It converts JavaScript to TypeScript", "It allows you to execute TypeScript files directly in Node.js without having to manually compile them to JavaScript first", "It minifies TypeScript code", "It runs TypeScript in the browser"],
    "correct_answer": "It allows you to execute TypeScript files directly in Node.js without having to manually compile them to JavaScript first",
    "explanation": "`ts-node` is a lifesaver for local development and scripting. It compiles your TS code in memory on the fly and passes it to Node.js, allowing you to run `ts-node server.ts` instantly."
  },
  {
    "id": 7,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Basic Primitives (string)",
    "question": "Fill in the blank to correctly annotate the `username` variable as a string.",
    "code_snippet": "let username: _______ = 'Alice';",
    "options": ["String", "string", "str", "text"],
    "correct_answer": "string",
    "explanation": "In TypeScript, primitive types are written in lowercase (e.g., `string`, `number`, `boolean`). Using the uppercase `String` refers to the JavaScript String object wrapper, which is a common beginner mistake!"
  },
  {
    "id": 8,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Basic Primitives (number)",
    "question": "Fill in the blank to correctly annotate the `age` variable as a number.",
    "code_snippet": "let age: _______ = 30;",
    "options": ["Number", "int", "float", "number"],
    "correct_answer": "number",
    "explanation": "Unlike languages like C++ or Java that separate `int` and `float`, TypeScript has a single `number` type. It handles both integers and floating-point numbers (because all JS numbers are IEEE 754 floating-point)."
  },
  {
    "id": 9,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Basic Primitives (boolean)",
    "question": "Fill in the blank to correctly annotate the `isActive` variable as a boolean.",
    "code_snippet": "let isActive: _______ = true;",
    "options": ["Boolean", "bool", "boolean", "bit"],
    "correct_answer": "boolean",
    "explanation": "The primitive type for true/false values is lowercase `boolean`. It can only ever hold the values `true` or `false`."
  },
  {
    "id": 10,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Type Mismatch Error",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "let score: number = 100;\nscore = 'high';",
    "options": ["It compiles successfully", "It throws a compile-time Error: Type 'string' is not assignable to type 'number'", "It automatically converts the string to a number", "It throws a runtime error in the browser"],
    "correct_answer": "It throws a compile-time Error: Type 'string' is not assignable to type 'number'",
    "explanation": "This is the core value of TypeScript! Because `score` was explicitly typed as a `number`, the compiler catches the attempt to assign a `string` to it and halts the compilation process, preventing a potential bug."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Type Inference",
    "question": "What is 'Type Inference' in TypeScript?",
    "code_snippet": null,
    "options": ["When the developer manually writes out every single type", "When the TypeScript compiler automatically deduces the type of a variable based on the value assigned to it, even if no explicit annotation is written", "When the browser guesses the type at runtime", "When TypeScript converts strings to numbers automatically"],
    "correct_answer": "When the TypeScript compiler automatically deduces the type of a variable based on the value assigned to it, even if no explicit annotation is written",
    "explanation": "If you write `let name = 'Alice';`, TypeScript is smart enough to infer that `name` is a `string`. You don't need to write `let name: string = 'Alice';`. Inference keeps your code clean while maintaining safety."
  },
  {
    "id": 12,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Inference (let vs const)",
    "question": "What is the inferred type of `x` and `y` in the following code?",
    "code_snippet": "let x = 5;\nconst y = 5;",
    "options": ["Both are inferred as `number`", "Both are inferred as the literal type `5`", "`x` is inferred as `number`; `y` is inferred as the literal type `5`", "`x` is inferred as the literal type `5`; `y` is inferred as `number`"],
    "correct_answer": "`x` is inferred as `number`; `y` is inferred as the literal type `5`",
    "explanation": "Because `let` allows reassignment, TS widens the type to `number` so you can later do `x = 10`. Because `const` cannot be reassigned, TS knows it will ALWAYS be `5`, so it infers the highly specific literal type `5`."
  },
  {
    "id": 13,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "When to use Explicit Annotations",
    "question": "If TypeScript has type inference, when should you explicitly write type annotations (e.g., `let x: number`)?",
    "code_snippet": null,
    "options": ["On every single variable, no matter what", "When declaring a variable without initializing it, when defining function parameters/returns, or when you want to prevent the type from widening", "Never, inference is always perfect", "Only when using the `var` keyword"],
    "correct_answer": "When declaring a variable without initializing it, when defining function parameters/returns, or when you want to prevent the type from widening",
    "explanation": "If you write `let userId;`, TS infers `any` (which is bad). You must write `let userId: number;`. Also, function parameters cannot be inferred because the function doesn't know what arguments will be passed to it later."
  },
  {
    "id": 14,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Arrays (Standard Syntax)",
    "question": "Fill in the blank to correctly annotate an array of strings using the standard shorthand syntax.",
    "code_snippet": "let colors: _______ = ['red', 'green', 'blue'];",
    "options": ["string[]", "array[string]", "[string]", "StringArray"],
    "correct_answer": "string[]",
    "explanation": "The most common way to type an array is to append `[]` to the element type. `string[]` means 'an array where every item must be a string'."
  },
  {
    "id": 15,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Arrays (Generic Syntax)",
    "question": "Fill in the blank to correctly annotate an array of numbers using the Generic Array syntax.",
    "code_snippet": "let scores: _______ = [100, 95, 88];",
    "options": ["number[]", "Array<number>", "array<number>", "[number]"],
    "correct_answer": "Array<number>",
    "explanation": "TypeScript also supports the generic `Array<T>` syntax. `Array<number>` is functionally identical to `number[]`, but you will see this syntax often when dealing with more complex generic types later on."
  },
  {
    "id": 16,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Array Type Strictness",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "let ages: number[] = [25, 30];\nages.push('thirty-five');",
    "options": ["It compiles successfully", "It throws a compile-time Error: Argument of type 'string' is not assignable to parameter of type 'number'", "It converts the string to a number automatically", "It throws a runtime error"],
    "correct_answer": "It throws a compile-time Error: Argument of type 'string' is not assignable to parameter of type 'number'",
    "explanation": "TypeScript's type checking applies to array methods too! Because `ages` is strictly a `number[]`, the `.push()` method will only accept numbers. Trying to push a string triggers a compile-time error."
  },
  {
    "id": 17,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Tuples",
    "question": "What is a 'Tuple' in TypeScript?",
    "code_snippet": null,
    "options": ["An array that can hold an infinite number of items", "An array with a fixed length and specific, known types at each index position", "An object with string keys", "A read-only array"],
    "correct_answer": "An array with a fixed length and specific, known types at each index position",
    "explanation": "While a standard array like `string[]` means 'any number of strings', a tuple like `[string, number]` means 'exactly two items: the first MUST be a string, and the second MUST be a number'. It's perfect for representing things like coordinates or key-value pairs."
  },
  {
    "id": 18,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly define a tuple that holds a string (the user's name) followed by a number (their age).",
    "code_snippet": "let user: _______ = ['Alice', 28];",
    "options": ["string | number", "[string, number]", "Array<string, number>", "(string, number)"],
    "correct_answer": "[string, number]",
    "explanation": "Tuples are defined using square brackets `[]` with comma-separated types. The order matters strictly: index 0 must be a string, index 1 must be a number."
  },
  {
    "id": 19,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Tuple Strictness",
    "question": "What will happen when the TypeScript compiler processes the following tuple code?",
    "code_snippet": "let point: [number, number] = [10, 20];\npoint[0] = 'x';",
    "options": ["It compiles successfully", "It throws a compile-time Error: Type 'string' is not assignable to type 'number'", "It changes the tuple into a standard array", "It throws a runtime error"],
    "correct_answer": "It throws a compile-time Error: Type 'string' is not assignable to type 'number'",
    "explanation": "Tuples are strictly typed by index. Because index `0` was defined as a `number` in the `[number, number]` tuple, attempting to assign a string to it will immediately fail compilation."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "The 'any' Type",
    "question": "What is the `any` type in TypeScript, and why is it generally considered a bad practice?",
    "code_snippet": null,
    "options": ["It represents a null value", "It tells the compiler to skip type checking entirely for that variable, effectively turning it back into standard, unsafe JavaScript", "It means the variable can only hold numbers", "It is the default type for all constants"],
    "correct_answer": "It tells the compiler to skip type checking entirely for that variable, effectively turning it back into standard, unsafe JavaScript",
    "explanation": "If you type a variable as `any`, you can assign a string, then a number, then call a method that doesn't exist, and TS won't warn you. It completely defeats the purpose of using TypeScript. It should only be used as a last-resort 'escape hatch' when migrating legacy JS code."
  }
]
[
  {
    "id": 21,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Union Types",
    "question": "Fill in the blank to correctly define a variable that can hold EITHER a string OR a number.",
    "code_snippet": "let userId: string _______ number = '12345';",
    "options": ["&", "|", "+", "or"],
    "correct_answer": "|",
    "explanation": "The pipe symbol (`|`) creates a Union Type. It tells TypeScript that the variable can be one of several specified types. This is incredibly common for IDs that might come from a database as a number or an API as a string."
  },
  {
    "id": 22,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Union Types (Common Properties)",
    "question": "If you have a variable typed as `string | number`, what operations can you safely perform on it without narrowing it first?",
    "code_snippet": null,
    "options": ["Call `.toUpperCase()` on it", "Call `.toFixed()` on it", "Only access properties and methods that are common to BOTH strings and numbers (like `.toString()`)", "Perform mathematical addition on it"],
    "correct_answer": "Only access properties and methods that are common to BOTH strings and numbers (like `.toString()`)",
    "explanation": "When dealing with a Union type, TypeScript only allows you to use members (properties/methods) that are shared by ALL types in the union. Since `.toUpperCase()` is only on strings, TS will block it until you prove the variable is actually a string."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Literal Types",
    "question": "What is a 'Literal Type' in TypeScript?",
    "code_snippet": null,
    "options": ["A type that only holds text", "A type that restricts a variable to one exact, specific value (e.g., `let direction: 'left' | 'right'`)", "A type that cannot be changed", "A type used only for HTML elements"],
    "correct_answer": "A type that restricts a variable to one exact, specific value (e.g., `let direction: 'left' | 'right'`)",
    "explanation": "Literal types allow you to be incredibly strict. Instead of accepting any `string`, you can force a variable to only accept the exact string `'left'` or `'right'`. This is perfect for state machines, configuration flags, and action types."
  },
  {
    "id": 24,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Literal Types (Strictness)",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "let alignment: 'left' | 'center' | 'right' = 'left';\nalignment = 'top';",
    "options": ["It compiles successfully", "It throws a compile-time Error: Type '\"top\"' is not assignable to type '\"left\" | \"center\" | \"right\"'", "It automatically converts 'top' to 'left'", "It throws a runtime error"],
    "correct_answer": "It throws a compile-time Error: Type '\"top\"' is not assignable to type '\"left\" | \"center\" | \"right\"'",
    "explanation": "Because `alignment` is restricted to those three exact string literals, the compiler catches the invalid assignment immediately. This prevents entire categories of bugs where invalid states are passed to components."
  },
  {
    "id": 25,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "null and undefined",
    "question": "In TypeScript, what are the types of the values `null` and `undefined`?",
    "code_snippet": null,
    "options": ["They are both of type `any`", "They are their own distinct types: `null` and `undefined`", "They are both of type `void`", "They do not have types"],
    "correct_answer": "They are their own distinct types: `null` and `undefined`",
    "explanation": "Just like `string` and `number`, `null` and `undefined` are fundamental types in TypeScript. By default (without strict mode), they can be assigned to any other type, which is why strict mode is crucial."
  },
  {
    "id": 26,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "strictNullChecks",
    "question": "What is the effect of setting `strictNullChecks: true` in your `tsconfig.json`?",
    "code_snippet": null,
    "options": ["It prevents variables from being reassigned", "It ensures that `null` and `undefined` cannot be assigned to types that don't explicitly include them, preventing many runtime errors", "It automatically converts `null` to `undefined`", "It removes the `null` type from the language"],
    "correct_answer": "It ensures that `null` and `undefined` cannot be assigned to types that don't explicitly include them, preventing many runtime errors",
    "explanation": "Without `strictNullChecks`, you can assign `null` to a `string` variable, leading to the dreaded `Cannot read property 'x' of null` at runtime. With it enabled, you MUST explicitly write `string | null` if a value can be missing."
  },
  {
    "id": 27,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Type Aliases",
    "question": "Fill in the blank to correctly create a custom Type Alias called `ID` that can be either a string or a number.",
    "code_snippet": "_______ ID = string | number;",
    "options": ["class", "interface", "type", "let"],
    "correct_answer": "type",
    "explanation": "The `type` keyword creates a Type Alias. It gives a complex or frequently used type a clear, readable name. Instead of writing `string | number` everywhere, you can just write `ID`."
  },
  {
    "id": 28,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "The 'unknown' Type",
    "question": "What is the `unknown` type in TypeScript?",
    "code_snippet": null,
    "options": ["A type that represents a null value", "A type-safe alternative to `any`; it can hold any value, but you cannot perform operations on it until you narrow its type", "A type that means the variable is undefined", "A type used for asynchronous functions"],
    "correct_answer": "A type-safe alternative to `any`; it can hold any value, but you cannot perform operations on it until you narrow its type",
    "explanation": "If you receive data from an API or `localStorage`, you don't know its shape. Instead of using `any` (which disables all safety), use `unknown`. It forces you to verify the type (using `typeof` or `instanceof`) before using it."
  },
  {
    "id": 29,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "unknown vs any",
    "question": "What is the fundamental difference between `unknown` and `any`?",
    "code_snippet": null,
    "options": ["There is no difference", "`any` disables type checking completely, allowing you to call any method; `unknown` enforces type checking and requires you to prove the type before using it", "`unknown` is for numbers, `any` is for strings", "`any` is deprecated"],
    "correct_answer": "`any` disables type checking completely, allowing you to call any method; `unknown` enforces type checking and requires you to prove the type before using it",
    "explanation": "If `x` is `any`, `x.toFixed()` compiles (but might crash at runtime). If `x` is `unknown`, `x.toFixed()` throws a compile-time error. You must first check `if (typeof x === 'number')` before calling `.toFixed()`."
  },
  {
    "id": 30,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "The 'void' Type",
    "question": "What does the `void` type represent in TypeScript?",
    "code_snippet": null,
    "options": ["A null value", "The absence of a return value in a function", "An undefined variable", "An empty array"],
    "correct_answer": "The absence of a return value in a function",
    "explanation": "When a function performs an action (like logging to the console or updating the DOM) but doesn't return any data, its return type is `void`. It tells the developer, 'Do not expect a value back from this function.'"
  },
  {
    "id": 31,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "void vs undefined",
    "question": "What is the difference between `void` and `undefined` as return types?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`void` means the function returns nothing (and you shouldn't use the result); `undefined` means the function explicitly returns the literal value `undefined`", "`undefined` is for async functions, `void` is for sync", "`void` is deprecated"],
    "correct_answer": "`void` means the function returns nothing (and you shouldn't use the result); `undefined` means the function explicitly returns the literal value `undefined`",
    "explanation": "While a `void` function technically returns `undefined` at runtime, TypeScript uses `void` to signal intent: 'This function is for side-effects only.' You cannot assign the result of a `void` function to a variable without getting a warning."
  },
  {
    "id": 32,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Type Assertions",
    "question": "Fill in the blank to correctly tell the TypeScript compiler to treat the `unknown` variable `input` as a string.",
    "code_snippet": "let input: unknown = 'Hello';\nlet strLength: number = (input _______ string).length;",
    "options": ["to", "as", "is", "cast"],
    "correct_answer": "as",
    "explanation": "The `as` keyword is a Type Assertion. It tells the compiler, 'Trust me, I know this variable is a string.' It does NOT convert the data at runtime; it only changes how the compiler views the variable."
  },
  {
    "id": 33,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Type Assertions (Runtime)",
    "question": "Does using a type assertion like `value as string` actually convert the underlying data at runtime?",
    "code_snippet": null,
    "options": ["Yes, it changes the data type in memory", "No, it is purely a compile-time instruction that tells the TypeScript compiler how to treat the variable; it has zero effect on the runtime JavaScript", "Yes, but only for numbers", "No, it throws a runtime error if the types don't match"],
    "correct_answer": "No, it is purely a compile-time instruction that tells the TypeScript compiler how to treat the variable; it has zero effect on the runtime JavaScript",
    "explanation": "TypeScript is completely erased when compiled to JavaScript. If you assert `5 as string`, the JavaScript output is still just `5`. If you try to call `.toUpperCase()` on it, your app will crash at runtime."
  },
  {
    "id": 34,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "The 'as const' Assertion",
    "question": "Fill in the blank to correctly assert that the array should be treated as a deeply readonly tuple with literal types for its elements.",
    "code_snippet": "const colors = ['red', 'green', 'blue'] _______ ;",
    "options": ["as readonly", "as const", "as tuple", "as literal"],
    "correct_answer": "as const",
    "explanation": "The `as const` assertion is incredibly powerful. It turns the array into a readonly tuple `readonly ['red', 'green', 'blue']` and infers the exact literal types instead of widening them to `string`."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "The 'as const' Assertion (Objects)",
    "question": "What is the exact inferred type of `config.theme` in the following code?",
    "code_snippet": "const config = { theme: 'dark', version: 2 } as const;",
    "options": ["string", "'dark'", "any", "unknown"],
    "correct_answer": "'dark'",
    "explanation": "Because of `as const`, TypeScript doesn't just see `theme` as a generic `string`. It knows it is the exact, literal string `'dark'`. This is essential for creating strict configuration objects and routing maps."
  },
  {
    "id": 36,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Function Return Inference",
    "question": "What is the inferred return type of the following function?",
    "code_snippet": "function multiply(a: number, b: number) {\n  return a * b;\n}",
    "options": ["void", "any", "number", "unknown"],
    "correct_answer": "number",
    "explanation": "TypeScript is smart enough to look at the `return` statement, see that it's multiplying two numbers, and automatically infer that the function returns a `number`. You rarely need to explicitly type function returns unless they are complex."
  },
  {
    "id": 37,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Implicit 'any' Error",
    "question": "Assuming `noImplicitAny` is true in `tsconfig.json`, what will happen when the compiler processes this code?",
    "code_snippet": "function processData(data) {\n  console.log(data);\n}",
    "options": ["It compiles successfully, inferring `data` as `any`", "It throws a compile-time Error: Parameter 'data' implicitly has an 'any' type", "It throws a runtime error", "It automatically infers `data` as `string`"],
    "correct_answer": "It throws a compile-time Error: Parameter 'data' implicitly has an 'any' type",
    "explanation": "Unlike variables, TypeScript cannot infer the type of a function parameter because it doesn't know what arguments will be passed to it later. You MUST explicitly type it: `function processData(data: string)`."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Non-null Assertion",
    "question": "Fill in the blank with the non-null assertion operator to tell the compiler that `user` is definitely not null or undefined at this specific line.",
    "code_snippet": "let user: { name: string } | null = getUser();\nconsole.log(user_______.name);",
    "options": ["!", "?", "#", "@"],
    "correct_answer": "!",
    "explanation": "The `!` operator is a Non-null Assertion. It tells TypeScript, 'I guarantee this value is not null or undefined, so don't throw an error.' It's useful when you know more about the runtime state than the compiler does."
  },
  {
    "id": 39,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "The 'never' Type",
    "question": "The `never` type represents values that NEVER occur. What is a common use case for `never`?",
    "code_snippet": null,
    "options": ["As the return type of a function that always throws an error or has an infinite loop", "As the type for empty arrays", "As the type for null values", "As the default type for variables"],
    "correct_answer": "As the return type of a function that always throws an error or has an infinite loop",
    "explanation": "If a function throws an error, it never successfully returns a value. Therefore, its return type is `never`. It is also used in exhaustive checks to ensure all possible union cases are handled."
  },
  {
    "id": 40,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Type Aliases vs Inline",
    "question": "Why is it considered a best practice to use Type Aliases (e.g., `type UserID = string | number`) instead of writing the union inline everywhere?",
    "code_snippet": null,
    "options": ["It makes the compiled JavaScript file smaller", "It creates a single source of truth; if the ID type needs to change later, you only update it in one place instead of hunting down every function", "It makes the code execute faster", "It is required by the TypeScript specification"],
    "correct_answer": "It creates a single source of truth; if the ID type needs to change later, you only update it in one place instead of hunting down every function",
    "explanation": "Type Aliases act as documentation and enforce consistency. If you decide that IDs should only be strings moving forward, you change the alias once, and the compiler will show you every place in your app that needs updating."
  }
]
[
  {
    "id": 41,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "object vs Object vs {}",
    "question": "What is the difference between the lowercase `object` type and the uppercase `Object` (or `{}`) type in TypeScript?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`object` refers to any non-primitive type (arrays, classes, custom objects); `Object` and `{}` refer to anything that isn't `null` or `undefined` (including primitives like `number` and `string`), which is usually a mistake", "`Object` is for arrays, `object` is for classes", "`object` is deprecated"],
    "correct_answer": "`object` refers to any non-primitive type (arrays, classes, custom objects); `Object` and `{}` refer to anything that isn't `null` or `undefined` (including primitives like `number` and `string`), which is usually a mistake",
    "explanation": "If you type a variable as `Object` or `{}`, TypeScript will let you assign the number `5` to it, but then block you from calling `.toString()` on it because it doesn't guarantee those methods exist. Always use lowercase `object` or a specific interface when you mean a non-primitive value."
  },
  {
    "id": 42,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Record<K, V>",
    "question": "Fill in the blank to correctly define an object where the keys are strings and the values are numbers, using the built-in `Record` utility type.",
    "code_snippet": "let scores: _______<string, number> = { alice: 100, bob: 95 };",
    "options": ["Map", "Dictionary", "Record", "KeyValue"],
    "correct_answer": "Record",
    "explanation": "`Record<K, V>` is one of TypeScript's most useful built-in utility types. It constructs an object type with property keys of type `K` and property values of type `V`. It is the standard way to type dictionaries or hash maps."
  },
  {
    "id": 43,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "The 'bigint' Type",
    "question": "What is the `bigint` type used for in TypeScript?",
    "code_snippet": null,
    "options": ["For floating-point numbers", "For integers larger than `Number.MAX_SAFE_INTEGER` (2^53 - 1), created by appending an 'n' to the end of an integer", "For very small decimal numbers", "It is an alias for `number`"],
    "correct_answer": "For integers larger than `Number.MAX_SAFE_INTEGER` (2^53 - 1), created by appending an 'n' to the end of an integer",
    "explanation": "Standard JS `number` types lose precision after 9 quadrillion. If you are working with cryptographic keys, massive financial calculations, or database IDs, you must use `bigint` (e.g., `let hugeNum: bigint = 9007199254740991n;`)."
  },
  {
    "id": 44,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "The 'symbol' Type",
    "question": "What is a `symbol` in TypeScript?",
    "code_snippet": null,
    "options": ["A special character like @ or #", "A unique, immutable primitive value often used as object keys to guarantee no naming collisions", "A type for HTML entities", "A deprecated string type"],
    "correct_answer": "A unique, immutable primitive value often used as object keys to guarantee no naming collisions",
    "explanation": "Every `Symbol()` is completely unique. If you use a Symbol as an object key, you are 100% guaranteed that no other piece of code will accidentally overwrite it, making it perfect for adding 'hidden' metadata to objects."
  },
  {
    "id": 45,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Readonly Arrays",
    "question": "Fill in the blank to correctly define an array of strings that cannot be mutated (no pushing, popping, or reassigning elements).",
    "code_snippet": "const colors: _______ = ['red', 'green', 'blue'];",
    "options": ["readonly string[]", "const string[]", "immutable string[]", "static string[]"],
    "correct_answer": "readonly string[]",
    "explanation": "The `readonly` modifier prevents any methods that would mutate the array (like `.push()` or `.pop()`) and prevents reassigning items by index. It is crucial for enforcing immutability in state management (like Redux)."
  },
  {
    "id": 46,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Enums",
    "question": "What is an `enum` in TypeScript?",
    "code_snippet": null,
    "options": ["A type for arrays", "A way to define a set of named, constant values (like directions or status codes) to make code more readable and self-documenting", "A type for mathematical equations", "A deprecated feature"],
    "correct_answer": "A way to define a set of named, constant values (like directions or status codes) to make code more readable and self-documenting",
    "explanation": "Instead of using 'magic numbers' like `0` for 'Pending' and `1` for 'Completed', you can define `enum Status { Pending, Completed }`. This makes your code infinitely more readable and type-safe."
  },
  {
    "id": 47,
    "level": "advanced",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "code-fill-in-blank",
    "topic": "Ambient Declarations (declare)",
    "question": "Fill in the blank to correctly tell TypeScript about a global variable `__APP_VERSION__` that is injected at runtime by a build tool, preventing compile errors.",
    "code_snippet": "_______ const __APP_VERSION__: string;",
    "options": ["declare", "global", "ambient", "extern"],
    "correct_answer": "declare",
    "explanation": "The `declare` keyword is used for 'ambient declarations'. It tells TypeScript, 'Trust me, this variable exists at runtime (injected by a script tag or build tool), don't throw an error even though you can't see its implementation.'"
  },
  {
    "id": 48,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Type Narrowing (typeof)",
    "question": "What is 'Type Narrowing' using the `typeof` operator?",
    "code_snippet": null,
    "options": ["Changing the type of a variable at runtime", "When TypeScript uses a `typeof` check inside an `if` statement to automatically narrow a Union type down to a single, specific type within that block", "Converting a string to a number", "Deleting a type definition"],
    "correct_answer": "When TypeScript uses a `typeof` check inside an `if` statement to automatically narrow a Union type down to a single, specific type within that block",
    "explanation": "If you have `let x: string | number`, and you write `if (typeof x === 'string')`, TypeScript is smart enough to know that inside that `if` block, `x` is strictly a `string`. This is the foundation of type-safe JavaScript."
  },
  {
    "id": 49,
    "level": "intermediate",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "output-prediction",
    "topic": "Type Narrowing (typeof) Output",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "function printLength(value: string | number) {\n  if (typeof value === 'string') {\n    console.log(value.toUpperCase());\n  } else {\n    console.log(value.toFixed(2));\n  }\n}",
    "options": ["It throws an error because `value` is a union type", "It compiles successfully because TypeScript narrows `value` to `string` in the first block, and `number` in the second block", "It throws an error because `toFixed` is not a valid number method", "It compiles but crashes at runtime"],
    "correct_answer": "It compiles successfully because TypeScript narrows `value` to `string` in the first block, and `number` in the second block",
    "explanation": "This is the beauty of TypeScript! It understands control flow. In the `if` block, `value` is treated as a `string` (so `.toUpperCase()` is allowed). In the `else` block, since it wasn't a string, TS narrows it to `number` (so `.toFixed()` is allowed)."
  },
  {
    "id": 50,
    "level": "beginner",
    "module_id": "ts_mod_01_basics",
    "module_name": "Introduction & Basic Types",
    "type": "conceptual",
    "topic": "Module 1 Wrap-up",
    "question": "You have now completed the fundamentals of TypeScript types. What is the most important mindset shift when moving from JavaScript to TypeScript?",
    "code_snippet": null,
    "options": ["You must write more code to achieve the same result", "You must stop thinking about what the data looks like at runtime, and start thinking about the 'shape' and 'contract' of the data at compile-time", "You must stop using functions", "You must memorize all the built-in types"],
    "correct_answer": "You must stop thinking about what the data looks like at runtime, and start thinking about the 'shape' and 'contract' of the data at compile-time",
    "explanation": "TypeScript is essentially 'designing your data structures before writing logic'. By defining clear types, interfaces, and contracts, you let the compiler do the heavy lifting of ensuring your code is safe, predictable, and self-documenting."
  }
]
