[
  {
    "id": 211,
    "level": "beginner",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Union Types",
    "question": "What does the union operator (`|`) do when combining types like `string | number`?",
    "code_snippet": null,
    "options": ["It creates a type that must be BOTH a string and a number simultaneously", "It creates a type that can be EITHER a string OR a number at any given time", "It merges the properties of strings and numbers", "It converts the string to a number"],
    "correct_answer": "It creates a type that can be EITHER a string OR a number at any given time",
    "explanation": "A Union type represents a value that can be one of several types. At runtime, the variable will hold exactly one of those types, and TypeScript forces you to figure out which one it is before using it."
  },
  {
    "id": 212,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Union Types (Common Members)",
    "question": "If you have a variable typed as `string | number`, what operations can you safely perform on it without narrowing it first?",
    "code_snippet": null,
    "options": ["Call `.toUpperCase()` on it", "Call `.toFixed()` on it", "Only access properties and methods that are common to BOTH strings and numbers (like `.toString()`)", "Perform mathematical addition on it"],
    "correct_answer": "Only access properties and methods that are common to BOTH strings and numbers (like `.toString()`)",
    "explanation": "When dealing with a Union type, TypeScript only allows you to use members (properties/methods) that are shared by ALL types in the union. Since `.toUpperCase()` is only on strings, TS will block it until you prove the variable is actually a string."
  },
  {
    "id": 213,
    "level": "beginner",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Literal Types",
    "question": "What is a 'Literal Type' in TypeScript?",
    "code_snippet": null,
    "options": ["A type that only holds text", "A type that restricts a variable to one exact, specific value (e.g., `let direction: 'left' | 'right'`)", "A type that cannot be changed", "A type used only for HTML elements"],
    "correct_answer": "A type that restricts a variable to one exact, specific value (e.g., `let direction: 'left' | 'right'`)",
    "explanation": "Literal types allow you to be incredibly strict. Instead of accepting any `string`, you can force a variable to only accept the exact string `'left'` or `'right'`. This is perfect for state machines, configuration flags, and action types."
  },
  {
    "id": 214,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Truthiness Narrowing",
    "question": "How does TypeScript narrow types using 'truthiness' checks like `if (value) { ... }`?",
    "code_snippet": null,
    "options": ["It checks if the value is strictly equal to `true`", "It eliminates `null`, `undefined`, `0`, `''`, `NaN`, and `false` from the type inside the `if` block", "It converts the value to a boolean", "It throws an error if the value is falsy"],
    "correct_answer": "It eliminates `null`, `undefined`, `0`, `''`, `NaN`, and `false` from the type inside the `if` block",
    "explanation": "If you have `let x: string | 0`, and you write `if (x)`, TypeScript knows that inside the block, `x` cannot be `0` (because `0` is falsy). Therefore, `x` is narrowed strictly to `string`."
  },
  {
    "id": 215,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Equality Narrowing",
    "question": "How does TypeScript narrow types when you use strict equality (`===`) to compare a union type to a literal?",
    "code_snippet": null,
    "options": ["It doesn't narrow types based on equality", "It narrows the union to the specific type or literal that matches the comparison, and excludes it in the `else` block", "It converts the union to `any`", "It throws an error"],
    "correct_answer": "It narrows the union to the specific type or literal that matches the comparison, and excludes it in the `else` block",
    "explanation": "If `let x: string | number`, and you write `if (x === 'hello')`, TS knows that inside the `if`, `x` is the literal `'hello'`. In the `else` block, TS knows `x` is `string | number` MINUS `'hello'`."
  },
  {
    "id": 216,
    "level": "beginner",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Type Narrowing (typeof)",
    "question": "What is 'Type Narrowing' using the `typeof` operator?",
    "code_snippet": null,
    "options": ["Changing the type of a variable at runtime", "When TypeScript uses a `typeof` check inside an `if` statement to automatically narrow a Union type down to a single, specific type within that block", "Converting a string to a number", "Deleting a type definition"],
    "correct_answer": "When TypeScript uses a `typeof` check inside an `if` statement to automatically narrow a Union type down to a single, specific type within that block",
    "explanation": "If you have `let x: string | number`, and you write `if (typeof x === 'string')`, TypeScript is smart enough to know that inside that `if` block, `x` is strictly a `string`. This is the foundation of type-safe JavaScript."
  },
  {
    "id": 217,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Type Narrowing (instanceof)",
    "question": "What does the `instanceof` operator do for type narrowing?",
    "code_snippet": null,
    "options": ["It checks if a property exists", "It checks if an object's prototype chain includes a specific class constructor, narrowing the type to that class or its subclasses", "It converts an object to a class", "It throws an error if the object is null"],
    "correct_answer": "It checks if an object's prototype chain includes a specific class constructor, narrowing the type to that class or its subclasses",
    "explanation": "If you have `function process(val: Date | string)`, you can write `if (val instanceof Date)`. Inside that block, TS knows `val` is strictly a `Date` object and allows you to call `.getFullYear()`."
  },
  {
    "id": 218,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Type Narrowing (in operator)",
    "question": "How does the `in` operator help with type narrowing when dealing with a union of different object types?",
    "code_snippet": null,
    "options": ["It checks if a property is undefined", "It checks if a specific property key exists in the object, narrowing the union to the type that contains that property", "It iterates over the object", "It converts the object to an array"],
    "correct_answer": "It checks if a specific property key exists in the object, narrowing the union to the type that contains that property",
    "explanation": "The `in` operator is a 'discriminant' check. If you have a union of `Fish | Bird`, checking `if ('swim' in animal)` tells TypeScript that inside that block, `animal` MUST be the `Fish` type."
  },
  {
    "id": 219,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Discriminated Unions (Concept)",
    "question": "What is a 'Discriminated Union' (or Tagged Union) in TypeScript?",
    "code_snippet": null,
    "options": ["A union of primitive types", "A union of object types that all share a common, literal property (the discriminant) used to safely narrow the type", "An array of mixed types", "A deprecated feature"],
    "correct_answer": "A union of object types that all share a common, literal property (the discriminant) used to safely narrow the type",
    "explanation": "Discriminated Unions are the absolute best way to model complex states (like API responses: 'loading' | 'success' | 'error'). The shared literal property acts as a 'tag' that tells TypeScript exactly which object shape you are dealing with."
  },
  {
    "id": 220,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "Discriminated Unions (Syntax)",
    "question": "Fill in the blank to correctly define a Discriminated Union for API states.",
    "code_snippet": "type ApiResponse = \n  | { status: 'loading' }\n  | { status: 'success', data: string }\n  | { status: 'error', _______: Error };",
    "options": ["message", "error", "code", "reason"],
    "correct_answer": "error",
    "explanation": "The `status` property is the 'discriminant'. When you check `if (response.status === 'error')`, TypeScript knows with 100% certainty that the `error` property exists on the object."
  },
  {
    "id": 221,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Discriminated Unions (Switch Narrowing)",
    "question": "How does TypeScript narrow a Discriminated Union inside a `switch` statement?",
    "code_snippet": null,
    "options": ["It doesn't, you must use type assertions", "By checking the discriminant property in each `case` block, TS automatically narrows the type to the specific object shape for that block", "It narrows it to `any`", "It requires a custom type guard"],
    "correct_answer": "By checking the discriminant property in each `case` block, TS automatically narrows the type to the specific object shape for that block",
    "explanation": "If you write `switch(response.status)`, TS knows that inside `case 'success':`, the `response` variable is strictly the `{ status: 'success', data: string }` shape. You can safely access `.data` without errors."
  },
  {
    "id": 222,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Exhaustiveness Checking (Concept)",
    "question": "How do you ensure a `switch` statement handles ALL possible cases of a Discriminated Union?",
    "code_snippet": null,
    "options": ["Add a `default: break;` case", "Assign the switched variable to a variable of type `never` in the `default` case. If a new case is added to the union later and not handled, TS throws an error", "Use an `if/else` chain instead", "You cannot guarantee exhaustiveness in TS"],
    "correct_answer": "Assign the switched variable to a variable of type `never` in the `default` case. If a new case is added to the union later and not handled, TS throws an error",
    "explanation": "This is called 'Exhaustiveness Checking'. Because `never` can only hold a value that doesn't exist, if you forget to handle a new state (like 'pending'), TS will say: 'Type pending is not assignable to type never', forcing you to update your switch statement."
  },
  {
    "id": 223,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "The 'never' Type (Bottom Type)",
    "question": "The `never` type represents values that NEVER occur. What is a common use case for `never` in control flow?",
    "code_snippet": null,
    "options": ["As the return type of a function that always throws an error or has an infinite loop", "As the type for empty arrays", "As the type for null values", "As the default type for variables"],
    "correct_answer": "As the return type of a function that always throws an error or has an infinite loop",
    "explanation": "If a function throws an error, it never successfully returns a value. Therefore, its return type is `never`. It is also used in exhaustive checks to ensure all possible union cases are handled."
  },
  {
    "id": 224,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "The 'satisfies' Operator (Concept)",
    "question": "What does the `satisfies` operator (introduced in TS 4.9) do?",
    "code_snippet": null,
    "options": ["It converts an object to a different type", "It validates that an expression matches a type without altering the resulting inferred type of the expression", "It makes all properties readonly", "It is an alias for `instanceof`"],
    "correct_answer": "It validates that an expression matches a type without altering the resulting inferred type of the expression",
    "explanation": "`satisfies` is the perfect middle-ground. It checks that your object is compatible with a broad type (like `Record<string, string>`), but it keeps the exact, narrow literal types of the properties you actually wrote."
  },
  {
    "id": 225,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "The 'satisfies' Operator (vs Explicit Typing)",
    "question": "How does `satisfies` differ from explicitly typing a variable (e.g., `const x: Type = ...`)?",
    "code_snippet": null,
    "options": ["There is no difference", "Explicit typing widens the type to `Type`, losing literal inference. `satisfies` checks against `Type` but keeps the exact, narrow inferred literal type", "`satisfies` is slower", "Explicit typing is deprecated"],
    "correct_answer": "Explicit typing widens the type to `Type`, losing literal inference. `satisfies` checks against `Type` but keeps the exact, narrow inferred literal type",
    "explanation": "If you write `const x: Record<string, string> = { red: 'crimson' }`, the type of `x.red` is just `string`. If you write `const x = { red: 'crimson' } satisfies Record<string, string>`, the type of `x.red` is the exact literal `'crimson'`."
  },
  {
    "id": 226,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Control Flow Analysis (CFG)",
    "question": "What is 'Control Flow Analysis' in TypeScript?",
    "code_snippet": null,
    "options": ["A tool to optimize runtime performance", "The compiler's ability to track the type of a variable through different branches of code (if/else, loops, returns) based on assignments and type guards", "A way to analyze CSS selectors", "A method to parse JSON"],
    "correct_answer": "The compiler's ability to track the type of a variable through different branches of code (if/else, loops, returns) based on assignments and type guards",
    "explanation": "CFG is the engine behind type narrowing. It allows TS to know that if you return early from a function, the code below it can safely assume the variable is not null."
  },
  {
    "id": 227,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Aliasing and Narrowing",
    "question": "If you narrow a variable using a type guard, and then assign it to a new `const` variable, does the new variable retain the narrowed type?",
    "code_snippet": null,
    "options": ["No, it reverts to the original union type", "Yes, assigning a narrowed value to a `const` preserves the narrowed type for the new variable", "Only if you use the `as` keyword", "Only if the original variable was a `let`"],
    "correct_answer": "Yes, assigning a narrowed value to a `const` preserves the narrowed type for the new variable",
    "explanation": "Because `const` cannot be reassigned, TypeScript knows the narrowed type is permanent for that specific variable. This is a great way to 'save' a narrowed type to use later in the function."
  },
  {
    "id": 228,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "output-prediction",
    "topic": "Type Narrowing (typeof) Output",
    "question": "What will happen when the TypeScript compiler processes the following code?",
    "code_snippet": "function printLength(value: string | number) {\n  if (typeof value === 'string') {\n    console.log(value.toUpperCase());\n  } else {\n    console.log(value.toFixed(2));\n  }\n}",
    "options": ["It throws an error because `value` is a union type", "It compiles successfully because TypeScript narrows `value` to `string` in the first block, and `number` in the second block", "It throws an error because `toFixed` is not a valid number method", "It compiles but crashes at runtime"],
    "correct_answer": "It compiles successfully because TypeScript narrows `value` to `string` in the first block, and `number` in the second block",
    "explanation": "This is the beauty of TypeScript! It understands control flow. In the `if` block, `value` is treated as a `string` (so `.toUpperCase()` is allowed). In the `else` block, since it wasn't a string, TS narrows it to `number` (so `.toFixed()` is allowed)."
  },
  {
    "id": 229,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "output-prediction",
    "topic": "The 'satisfies' Operator (Output Prediction)",
    "question": "What is the exact inferred type of `palette.red` in the following code?",
    "code_snippet": "const palette = { red: 'crimson', blue: 'navy' } satisfies Record<string, string>;",
    "options": ["string", "The literal type 'crimson'", "Record<string, string>", "any"],
    "correct_answer": "The literal type 'crimson'",
    "explanation": "Because `satisfies` does not widen the type of the expression, TypeScript remembers that `red` was specifically assigned the literal string `'crimson'`, giving you perfect autocomplete and strictness."
  },
  {
    "id": 230,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've now covered Union Types, Literal Types, Discriminated Unions, and the `satisfies` operator. What is the core philosophy of Type Narrowing?",
    "code_snippet": null,
    "options": ["To make the code run faster", "To allow developers to start with broad, flexible types (like unions or unknown) and progressively prove to the compiler exactly what the data is at any specific point in the code", "To eliminate the need for interfaces", "To automatically fix runtime bugs"],
    "correct_answer": "To allow developers to start with broad, flexible types (like unions or unknown) and progressively prove to the compiler exactly what the data is at any specific point in the code",
    "explanation": "Type narrowing bridges the gap between the dynamic nature of JavaScript and the strict safety of TypeScript. It allows you to handle unpredictable data (like API responses) safely, unlocking the exact shape of the data exactly when you need it."
  }
]
[
  {
    "id": 231,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Custom Type Guards (Concept)",
    "question": "What is a 'Custom Type Guard' in TypeScript?",
    "code_snippet": null,
    "options": ["A CSS class that hides elements", "A function that returns a boolean and uses a special return type syntax (`param is Type`) to tell the compiler to narrow the type of the parameter", "A JavaScript `try/catch` block", "A way to prevent null values"],
    "correct_answer": "A function that returns a boolean and uses a special return type syntax (`param is Type`) to tell the compiler to narrow the type of the parameter",
    "explanation": "Custom type guards allow you to encapsulate complex type-checking logic (like checking for multiple specific object properties) into a reusable function that TypeScript's control flow analysis understands."
  },
  {
    "id": 232,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "Custom Type Guards (Syntax)",
    "question": "Fill in the blank to correctly define a custom type guard function that checks if an unknown value is a string.",
    "code_snippet": "function isString(val: unknown): val _______ string {\n  return typeof val === 'string';\n}",
    "options": ["as", "is", "equals", "type"],
    "correct_answer": "is",
    "explanation": "The `val is string` syntax is called a 'Type Predicate'. It tells the compiler, 'If this function returns true, you can safely treat `val` as a `string` from this point forward.'"
  },
  {
    "id": 233,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Type Predicates in Array Methods",
    "question": "How do you correctly type the `.filter()` method to narrow an array of a Union type down to a specific subset?",
    "code_snippet": null,
    "options": ["Use `.filter(item => item.type === 'success')`", "Use `.filter((item): item is Success => item.type === 'success')`", "Use `.map(item => item as Success)`", "Use `.reduce()`"],
    "correct_answer": "Use `.filter((item): item is Success => item.type === 'success')",
    "explanation": "Standard `.filter()` returns the exact same array type. By adding the `item is Success` type predicate to the callback, you tell TypeScript that the resulting array should be strictly typed as `Success[]`."
  },
  {
    "id": 234,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Assertion Functions (Concept)",
    "question": "What is an 'Assertion Function' in TypeScript, and how does it differ from a Custom Type Guard?",
    "code_snippet": null,
    "options": ["It returns a boolean, while a Type Guard throws an error", "It throws an error if a condition is not met, and uses the `asserts` keyword to tell TS that if the function returns successfully, the narrowed type is guaranteed", "It converts types at runtime", "They are exactly the same"],
    "correct_answer": "It throws an error if a condition is not met, and uses the `asserts` keyword to tell TS that if the function returns successfully, the narrowed type is guaranteed",
    "explanation": "While a Type Guard returns `true/false` for use in `if` statements, an Assertion Function returns `void`. If it doesn't throw an error, TypeScript knows the condition passed and narrows the type for all subsequent code."
  },
  {
    "id": 235,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "Assertion Functions (Syntax)",
    "question": "Fill in the blank to correctly define an assertion function that guarantees `val` is a string if it doesn't throw.",
    "code_snippet": "function assertIsString(val: unknown): _______ val is string {\n  if (typeof val !== 'string') throw new Error('Not a string!');\n}",
    "options": ["returns", "asserts", "guarantees", "is"],
    "correct_answer": "asserts",
    "explanation": "The `asserts` keyword modifies the return type. It tells the compiler, 'This function returns `void`, but as a side-effect, it guarantees that `val` is a `string` if execution continues past this call.'"
  },
  {
    "id": 236,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Control Flow (Early Returns)",
    "question": "How does an 'early return' (e.g., `if (!user) return;`) affect TypeScript's control flow analysis for the rest of the function?",
    "code_snippet": null,
    "options": ["It does nothing", "It permanently removes `null` and `undefined` from the `user` variable's type for the remainder of the function scope", "It converts the variable to `any`", "It throws a compile-time error"],
    "correct_answer": "It permanently removes `null` and `undefined` from the `user` variable's type for the remainder of the function scope",
    "explanation": "This is called 'control flow narrowing'. By returning early if the value is falsy/nullish, you guarantee to the compiler that any code executing below that line is dealing with a valid, non-null object."
  },
  {
    "id": 237,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Control Flow (The Closure Limitation)",
    "question": "Why does TypeScript sometimes FAIL to narrow a `let` variable inside a nested function or callback (closure)?",
    "code_snippet": null,
    "options": ["Because closures are deprecated", "Because TypeScript cannot guarantee that the `let` variable wasn't reassigned by some other code before the closure actually executes", "Because closures don't support type narrowing", "Because the variable is out of scope"],
    "correct_answer": "Because TypeScript cannot guarantee that the `let` variable wasn't reassigned by some other code before the closure actually executes",
    "explanation": "If you narrow a `let` variable, but then pass a callback to `setTimeout`, TS 'forgets' the narrowing. It assumes that during the time delay, some other part of the code might have reassigned the `let` variable back to its original union type."
  },
  {
    "id": 238,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Control Flow (Fixing Closures)",
    "question": "What is the standard workaround to preserve type narrowing inside a closure or callback?",
    "code_snippet": null,
    "options": ["Use the `any` type", "Assign the narrowed `let` variable to a new `const` variable before passing it into the closure", "Use a `while` loop", "Use the `!` non-null assertion operator"],
    "correct_answer": "Assign the narrowed `let` variable to a new `const` variable before passing it into the closure",
    "explanation": "Because `const` variables cannot be reassigned, TypeScript knows their type is permanently locked. Passing the `const` copy into the closure preserves the narrowed type perfectly."
  },
  {
    "id": 239,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "NonNullable<T> Utility Type",
    "question": "What does the built-in `NonNullable<T>` utility type do?",
    "code_snippet": null,
    "options": ["Makes all properties required", "Removes `null` and `undefined` from the type `T`", "Converts the type to a boolean", "Makes the type readonly"],
    "correct_answer": "Removes `null` and `undefined` from the type `T`",
    "explanation": "If you have `type MaybeString = string | null | undefined`, `NonNullable<MaybeString>` evaluates to just `string`. It is the type-level equivalent of a null-check."
  },
  {
    "id": 240,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "typeof Limitations",
    "question": "What is a major limitation of using the `typeof` operator for type narrowing?",
    "code_snippet": null,
    "options": ["It is very slow at runtime", "It only returns broad JavaScript runtime types (like 'string', 'object', 'function') and cannot distinguish between specific custom interfaces or object shapes", "It cannot be used on arrays", "It throws an error on null values"],
    "correct_answer": "It only returns broad JavaScript runtime types (like 'string', 'object', 'function') and cannot distinguish between specific custom interfaces or object shapes",
    "explanation": "If you have a union of `User | Admin`, `typeof` will just return `'object'` for both. To narrow specific object shapes, you must use the `in` operator, Discriminated Unions, or Custom Type Guards."
  },
  {
    "id": 241,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Extracting Unions from 'as const'",
    "question": "How do you create a strict Union type of strings from an array of allowed values?",
    "code_snippet": null,
    "options": ["type Role = string[]", "const roles = ['admin', 'user'] as const; type Role = typeof roles[number];", "type Role = ['admin', 'user']", "const roles = ['admin', 'user']; type Role = typeof roles;"],
    "correct_answer": "const roles = ['admin', 'user'] as const; type Role = typeof roles[number];",
    "explanation": "The `as const` makes the array a readonly tuple of exact literals. `typeof roles[number]` tells TypeScript to look up the type of any valid index in that array, resulting in the union `'admin' | 'user'`."
  },
  {
    "id": 242,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Exhaustive Checks (Throwing)",
    "question": "Besides assigning to a `never` variable, what is another common way to enforce exhaustiveness checking in a `switch` statement?",
    "code_snippet": null,
    "options": ["Add a `default: break;` case", "Throw an error in the `default` case, passing the unhandled variable to the error message", "Use an `if/else` chain instead", "Return `null`"],
    "correct_answer": "Throw an error in the `default` case, passing the unhandled variable to the error message",
    "explanation": "Writing `default: throw new Error(`Unhandled case: ${val}`);` ensures that if a new variant is added to the union later and forgotten in the switch, TypeScript will flag the `val` variable in the error string as a type error (because it can't be assigned to `never`)."
  },
  {
    "id": 243,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "instanceof vs Custom Type Guards",
    "question": "When should you use the built-in `instanceof` operator instead of writing a Custom Type Guard?",
    "code_snippet": null,
    "options": ["When checking for primitive types like string or number", "When checking if an object is an instance of a specific, concrete `class`", "When checking for specific object interfaces", "You should never use `instanceof`"],
    "correct_answer": "When checking if an object is an instance of a specific, concrete `class`",
    "explanation": "`instanceof` checks the JavaScript prototype chain. It works perfectly for classes (like `Date` or `Error`). However, it does NOT work for `interface` or `type` aliases, because those are erased at runtime and don't exist in the prototype chain."
  },
  {
    "id": 244,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Advanced Discriminated Unions (Multiple Discriminants)",
    "question": "Can a Discriminated Union have more than one discriminant property?",
    "code_snippet": null,
    "options": ["No, it must have exactly one", "Yes, TypeScript will narrow the union based on the combination of multiple literal properties", "Only if they are both strings", "Only if using the `infer` keyword"],
    "correct_answer": "Yes, TypeScript will narrow the union based on the combination of multiple literal properties",
    "explanation": "If your objects have both `type: 'user'` and `role: 'admin'`, checking both properties in an `if` statement will allow TypeScript to narrow the union down to the exact, specific variant that matches both conditions."
  },
  {
    "id": 245,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Narrowing with 'in' (Multiple Properties)",
    "question": "If you check `if ('swim' in animal && 'quack' in animal)`, how does TypeScript narrow the type?",
    "code_snippet": null,
    "options": ["It throws an error", "It intersects the types, narrowing `animal` to only the types that possess BOTH the 'swim' AND 'quack' properties", "It narrows it to `any`", "It only checks the first property"],
    "correct_answer": "It intersects the types, narrowing `animal` to only the types that possess BOTH the 'swim' AND 'quack' properties",
    "explanation": "TypeScript's `in` operator can be chained with logical AND (`&&`). It will continuously intersect the possible types until only the ones that satisfy all property checks remain."
  },
  {
    "id": 246,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "satisfies with Functions",
    "question": "Can the `satisfies` operator be used to validate a function's signature while preserving its inferred parameter and return types?",
    "code_snippet": null,
    "options": ["No, it only works on objects", "Yes, it ensures the function matches a broad callback type, but keeps the exact inferred parameter/return types for the implementation", "Yes, but it forces the return type to be `void`", "No, it throws an error"],
    "correct_answer": "Yes, it ensures the function matches a broad callback type, but keeps the exact inferred parameter/return types for the implementation",
    "explanation": "This is incredibly useful for event handlers or middleware. You can ensure your function matches `ExpressHandler`, but TS will still remember the exact types of `req` and `res` inside your function body."
  },
  {
    "id": 247,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Control Flow (while loops)",
    "question": "How does TypeScript narrow types inside a `while (obj) { ... }` loop?",
    "code_snippet": null,
    "options": ["It doesn't narrow inside loops", "It removes `null` and `undefined` from the type inside the loop body, assuming the loop condition guarantees truthiness", "It converts the type to `boolean`", "It throws an error"],
    "correct_answer": "It removes `null` and `undefined` from the type inside the loop body, assuming the loop condition guarantees truthiness",
    "explanation": "Just like `if` statements, `while` and `for` loops trigger control flow narrowing. If the loop condition checks for the existence of an object, TS knows it's safe to use inside the block."
  },
  {
    "id": 248,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "User-Defined Type Guards for Generics",
    "question": "Can a Custom Type Guard be generic?",
    "code_snippet": null,
    "options": ["No, type guards must use concrete types", "Yes, you can write `function isType<T>(val: unknown): val is T` to create a reusable, generic narrowing function", "Only with the `infer` keyword", "Only in abstract classes"],
    "correct_answer": "Yes, you can write `function isType<T>(val: unknown): val is T` to create a reusable, generic narrowing function",
    "explanation": "Generic type guards are incredibly powerful. You can write a single `isInstanceOf<T>` function and reuse it for any class, maintaining full type safety when narrowing `unknown` API responses."
  },
  {
    "id": 249,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "The 'asserts' Keyword (Condition Only)",
    "question": "Can the `asserts` keyword be used without a type predicate (e.g., `asserts condition` instead of `asserts val is Type`)?",
    "code_snippet": null,
    "options": ["No, it must always include a type", "Yes, it simply asserts that the condition is truthy, narrowing out `null`/`undefined` or falsy values without changing the base type", "Yes, but it converts the type to `any`", "No, it throws a syntax error"],
    "correct_answer": "Yes, it simply asserts that the condition is truthy, narrowing out `null`/`undefined` or falsy values without changing the base type",
    "explanation": "You can write `function assert(condition: any, msg: string): asserts condition`. If the function returns, TS knows `condition` evaluated to true, which is perfect for custom assertion libraries like Chai or Jest."
  },
  {
    "id": 250,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've now mastered Custom Type Guards, Assertion Functions, and advanced Control Flow. What is the ultimate benefit of these advanced narrowing techniques?",
    "code_snippet": null,
    "options": ["They make the code execute faster at runtime", "They allow you to safely handle unpredictable, dynamic data (like API payloads or DOM events) by mathematically proving to the compiler exactly what the data is at every single step of your logic", "They eliminate the need for unit tests", "They automatically generate documentation"],
    "correct_answer": "They allow you to safely handle unpredictable, dynamic data (like API payloads or DOM events) by mathematically proving to the compiler exactly what the data is at every single step of your logic",
    "explanation": "Advanced narrowing transforms TypeScript from a simple syntax checker into a powerful reasoning engine. It allows you to embrace the messy, dynamic reality of JavaScript while maintaining the ironclad safety of a statically typed language."
  }
]
[
  {
    "id": 251,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Mapped Types (Concept)",
    "question": "What is a 'Mapped Type' in TypeScript?",
    "code_snippet": null,
    "options": ["A type that maps strings to numbers", "A way to create a new type by iterating over the keys of an existing type and transforming their property types or modifiers", "A type used for React components", "A deprecated feature"],
    "correct_answer": "A way to create a new type by iterating over the keys of an existing type and transforming their property types or modifiers",
    "explanation": "Mapped types are like `map()` for types. They allow you to take an existing type and transform every single property in it (e.g., making them all optional, or all readonly) in a single line of code."
  },
  {
    "id": 252,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "Mapped Types Syntax",
    "question": "Fill in the blank to correctly create a mapped type that makes all properties of `T` readonly.",
    "code_snippet": "type MyReadonly<T> = { _______: T[K] };",
    "options": ["[K in keyof T] readonly", "readonly [K in keyof T]", "[keyof T in K]", "readonly keyof T"],
    "correct_answer": "readonly [K in keyof T]",
    "explanation": "The syntax `readonly [K in keyof T]` reads as: 'For every key `K` in the keys of `T`, add the `readonly` modifier'. This is exactly how the built-in `Readonly<T>` utility type is implemented under the hood."
  },
  {
    "id": 253,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Modifiers in Mapped Types (+ / -)",
    "question": "How do you explicitly REMOVE the `readonly` modifier from all properties in a Mapped Type?",
    "code_snippet": null,
    "options": ["{-readonly [K in keyof T]}", "readonly- [K in keyof T]", "!readonly [K in keyof T]", "remove readonly [K in keyof T]"],
    "correct_answer": "{-readonly [K in keyof T]}",
    "explanation": "In mapped types, you can add or remove modifiers using `+` or `-`. By default, adding a modifier implies `+`. To remove `readonly` or the optional `?` modifier, you must explicitly prefix it with a minus sign `-`."
  },
  {
    "id": 254,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "Key Remapping (as clause)",
    "question": "Fill in the blank to correctly use the 'as' clause to rename keys in a Mapped Type, prepending 'get' to every property name.",
    "code_snippet": "type Getters<T> = { [K in keyof T _______ `get${Capitalize<string & K>}`]: () => T[K] };",
    "options": ["as", "to", "rename", "map"],
    "correct_answer": "as",
    "explanation": "The `as` clause (introduced in TS 4.1) allows you to transform the keys themselves during iteration. This is incredibly powerful for creating automatic getter/setter types or prefixing event handlers."
  },
  {
    "id": 255,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "Conditional Types Basics",
    "question": "Fill in the blank to correctly write a Conditional Type that returns `true` if `T` extends `string`, and `false` otherwise.",
    "code_snippet": "type IsString<T> = T _______ string ? true : false;",
    "options": ["extends", "implements", "==", "==="],
    "correct_answer": "extends",
    "explanation": "Conditional types follow the syntax `T extends U ? X : Y`. If `T` is assignable to `U`, the type resolves to `X`. Otherwise, it resolves to `Y`. It acts as an `if/else` statement for the type system."
  },
  {
    "id": 256,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Distributive Conditional Types",
    "question": "What happens when a generic conditional type `T extends any ? ...` is passed a Union type like `string | number`?",
    "code_snippet": null,
    "options": ["It evaluates the union as a single whole", "It distributes over the union, evaluating each member individually and returning a new union of the results", "It throws an error", "It converts the union to `never`"],
    "correct_answer": "It distributes over the union, evaluating each member individually and returning a new union of the results",
    "explanation": "This is called 'Distributive Conditional Types'. If you pass `string | number` to `T extends string ? true : false`, TS evaluates `string` (true) and `number` (false) separately, resulting in the union `true | false` (which simplifies to `boolean`)."
  },
  {
    "id": 257,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "output-prediction",
    "topic": "Distributive Conditional Types (Output)",
    "question": "What does the following conditional type evaluate to?\n`type Test<T> = T extends string ? 'yes' : 'no';`\n`type Result = Test<string | number>;`",
    "code_snippet": null,
    "options": ["'yes'", "'no'", "'yes' | 'no'", "never"],
    "correct_answer": "'yes' | 'no'",
    "explanation": "Because `Test` is a generic conditional type, it distributes over the union `string | number`. It evaluates `string` (resolving to 'yes') and `number` (resolving to 'no'), resulting in the final union `'yes' | 'no'`."
  },
  {
    "id": 258,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "The 'infer' Keyword (Concept)",
    "question": "What is the purpose of the `infer` keyword in TypeScript?",
    "code_snippet": null,
    "options": ["To declare a new runtime variable", "To conditionally extract and infer a type from within another type (usually inside the `extends` clause of a conditional type)", "To import a module", "To cast a type to `any`"],
    "correct_answer": "To conditionally extract and infer a type from within another type (usually inside the `extends` clause of a conditional type)",
    "explanation": "`infer` allows you to create a temporary type variable inside a conditional type. It's the magic behind built-in utility types like `ReturnType<T>`, `Parameters<T>`, and `Awaited<T>`."
  },
  {
    "id": 259,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "code-fill-in-blank",
    "topic": "The 'infer' Keyword (Usage)",
    "question": "Fill in the blank to correctly extract the return type of a function `T` using `infer`.",
    "code_snippet": "type MyReturnType<T> = T _______ (...args: any[]) => infer R ? R : never;",
    "options": ["extends", "returns", "is", "implements"],
    "correct_answer": "extends",
    "explanation": "The syntax `T extends (...args: any[]) => infer R` checks if `T` is a function. If it is, it infers the function's return type into the temporary variable `R`, which is then returned by the conditional type."
  },
  {
    "id": 260,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Template Literal Types",
    "question": "What do Template Literal Types allow you to do in TypeScript?",
    "code_snippet": null,
    "options": ["Execute JavaScript code inside type definitions", "Create complex string types by combining literal types and interpolating them, similar to JS template strings", "Parse JSON at compile-time", "Translate strings to other languages"],
    "correct_answer": "Create complex string types by combining literal types and interpolating them, similar to JS template strings",
    "explanation": "Template literal types allow you to build highly specific string patterns, like event names (`on${'Click' | 'Hover'}`) or CSS utility classes, enforcing strict naming conventions at compile-time."
  },
  {
    "id": 261,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Intrinsic String Manipulation Types",
    "question": "Which of the following is NOT a built-in intrinsic string manipulation type in TypeScript?",
    "code_snippet": null,
    "options": ["Uppercase", "Capitalize", "Reverse", "Uncapitalize"],
    "correct_answer": "Reverse",
    "explanation": "TypeScript provides four intrinsic string manipulations that work directly in the type system: `Uppercase`, `Lowercase`, `Capitalize`, and `Uncapitalize`. There is no built-in `Reverse` type."
  },
  {
    "id": 262,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "output-prediction",
    "topic": "Template Literal Types (Output)",
    "question": "What is the exact resulting type of the template literal type `` `user_${'admin' | 'guest'}` ``?",
    "code_snippet": null,
    "options": ["string", "`user_admin` | `user_guest`", "user_admin_guest", "any"],
    "correct_answer": "`user_admin` | `user_guest`",
    "explanation": "Just like JS template strings, TS distributes over unions. It creates every possible combination of the interpolated values, resulting in a strict union of the exact literal strings."
  },
  {
    "id": 263,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Recursive Types (Concept)",
    "question": "How do you define a recursive type in TypeScript, such as a nested JSON structure?",
    "code_snippet": null,
    "options": ["Using the `recursive` keyword", "By referencing the type alias within its own definition (e.g., `type JSON = ... | JSON[]`)", "Using the `this` keyword", "It is not possible in TypeScript"],
    "correct_answer": "By referencing the type alias within its own definition (e.g., `type JSON = ... | JSON[]`)",
    "explanation": "TypeScript allows type aliases to reference themselves, enabling the modeling of infinitely nested data structures like trees, linked lists, or JSON objects."
  },
  {
    "id": 264,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Recursive Types (JSON)",
    "question": "Which of the following correctly defines a recursive type for a JSON-serializable value?",
    "code_snippet": null,
    "options": ["type JSON = string | number | boolean | null | JSON[] | { [key: string]: JSON }", "type JSON = any", "type JSON = object", "type JSON = string | number"],
    "correct_answer": "type JSON = string | number | boolean | null | JSON[] | { [key: string]: JSON }",
    "explanation": "This type accurately reflects the JSON specification. It states that a JSON value is either a primitive, an array of JSON values, or an object where every value is also a JSON value. It references itself infinitely."
  },
  {
    "id": 265,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "DeepPartial Concept",
    "question": "Why doesn't the built-in `Partial<T>` utility type work for deeply nested objects?",
    "code_snippet": null,
    "options": ["It throws a compile-time error", "It is 'shallow'—it only makes the top-level properties optional, but nested objects remain strictly required", "It converts nested objects to `any`", "It removes nested properties entirely"],
    "correct_answer": "It is 'shallow'—it only makes the top-level properties optional, but nested objects remain strictly required",
    "explanation": "To make a deeply nested object optional, you must write a custom recursive mapped type: `type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P] }`."
  },
  {
    "id": 266,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Built-in Utility: ReturnType<T>",
    "question": "What does the built-in `ReturnType<T>` utility type do?",
    "code_snippet": null,
    "options": ["Returns the parameters of a function as a tuple", "Extracts the return type of a function type using the `infer` keyword", "Creates a new function with a different return type", "Converts a class to its return type"],
    "correct_answer": "Extracts the return type of a function type using the `infer` keyword",
    "explanation": "`ReturnType<T>` uses conditional types and `infer` to look at a function's signature and extract exactly what it returns. It's perfect for typing variables that hold the result of an API call."
  },
  {
    "id": 267,
    "level": "intermediate",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Built-in Utility: Parameters<T>",
    "question": "What does the built-in `Parameters<T>` utility type return when passed a function type?",
    "code_snippet": null,
    "options": ["The return type of the function", "A tuple type representing all the parameter types of the function", "The `this` context of the function", "A union of all argument types"],
    "correct_answer": "A tuple type representing all the parameter types of the function",
    "explanation": "`Parameters<T>` extracts the arguments of a function into a tuple. For `(a: string, b: number) => void`, it returns `[a: string, b: number]`. This is incredibly useful for creating type-safe event emitters or wrappers."
  },
  {
    "id": 268,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Built-in Utility: Exclude / Extract",
    "question": "What does the `Extract<T, U>` utility type do?",
    "code_snippet": null,
    "options": ["Removes from `T` those types that are assignable to `U`", "Extracts from `T` those types that are assignable to `U`", "Combines `T` and `U` into an intersection", "Converts `T` to `U`"],
    "correct_answer": "Extracts from `T` those types that are assignable to `U`",
    "explanation": "If `T` is `'a' | 'b' | 'c'` and `U` is `'a' | 'c'`, `Extract<T, U>` returns `'a' | 'c'`. It filters the union `T`, keeping only the members that overlap with `U`. (`Exclude` does the exact opposite)."
  },
  {
    "id": 269,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Type Level Programming Philosophy",
    "question": "TypeScript's type system is often described as a 'Turing-complete functional programming language'. What does this mean in practice?",
    "code_snippet": null,
    "options": ["TypeScript can execute loops and conditionals at runtime faster than JavaScript", "The type system is expressive enough to perform complex computations, recursion, and conditional logic entirely at compile-time to validate data shapes", "TypeScript replaces the need for a backend database", "TypeScript can compile to languages other than JavaScript"],
    "correct_answer": "The type system is expressive enough to perform complex computations, recursion, and conditional logic entirely at compile-time to validate data shapes",
    "explanation": "You can write types that recursively parse strings, compute mathematical results, and validate complex data schemas before your code ever executes. The TS compiler is essentially running a separate, purely functional program to verify your code."
  },
  {
    "id": 270,
    "level": "advanced",
    "module_id": "ts_mod_04_advanced_narrowing",
    "module_name": "Advanced Types & Type Narrowing",
    "type": "conceptual",
    "topic": "Part 3 Wrap-up",
    "question": "You've now mastered Mapped Types, Conditional Types, `infer`, and Template Literals. What is the ultimate superpower of these advanced type-level features?",
    "code_snippet": null,
    "options": ["They make the compiled JavaScript run significantly faster", "They allow you to create highly expressive, reusable types that automatically adapt, transform, and validate complex data structures at compile-time, acting as a 'compiler within a compiler'", "They eliminate the need for runtime testing", "They reduce the file size of the TypeScript compiler"],
    "correct_answer": "They allow you to create highly expressive, reusable types that automatically adapt, transform, and validate complex data structures at compile-time, acting as a 'compiler within a compiler'",
    "explanation": "By mastering these features, you transition from simply 'using' TypeScript to 'programming' TypeScript. You can build custom utility types that enforce your team's architectural rules automatically, making invalid states literally impossible to represent."
  }
]
