[
  {
    "id": 201,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "REST Maturity Model (HATEOAS)",
    "question": "What is 'HATEOAS' (Hypermedia As The Engine Of Application State) in the context of the Richardson Maturity Model for REST APIs?",
    "code_snippet": null,
    "options": ["Using XML instead of JSON", "Including hyperlinks (URLs) in the API response that tell the client what actions they can perform next, making the API self-discoverable", "Encrypting the payload", "Using WebSockets for real-time updates"],
    "correct_answer": "Including hyperlinks (URLs) in the API response that tell the client what actions they can perform next, making the API self-discoverable",
    "explanation": "Instead of the client hardcoding URLs like `/users/123/ban`, the server returns the user object with a `_links: { ban: { href: '/users/123/ban' } }` property. This decouples the client from the server's URL structure, which is the ultimate goal of REST (Level 3 maturity)."
  },
  {
    "id": 202,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Pagination (Cursor vs Offset)",
    "question": "Why is 'Cursor-Based' (Keyset) pagination generally preferred over 'Offset-Based' pagination for large, frequently updated datasets?",
    "code_snippet": null,
    "options": ["It is easier to implement", "Offset pagination suffers from the 'missing/duplicate item' problem when new rows are inserted during pagination; Cursor pagination uses a unique, immutable pointer (like an ID or timestamp) to guarantee consistent results", "Cursor pagination uses less database storage", "Offset pagination is deprecated in SQL"],
    "correct_answer": "Offset pagination suffers from the 'missing/duplicate item' problem when new rows are inserted; Cursor pagination uses a unique pointer to guarantee consistent results",
    "explanation": "If you are on page 2 (`OFFSET 10`) and a new user is inserted at the top of the list, the last user from page 1 will be duplicated on page 2, and the first user of page 2 will be skipped. Cursor pagination (`WHERE id > last_seen_id LIMIT 10`) completely avoids this."
  },
  {
    "id": 203,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL Security (Query Depth Limiting)",
    "question": "What malicious attack does 'Query Depth Limiting' prevent in a GraphQL API?",
    "code_snippet": null,
    "options": ["SQL Injection", "A Denial of Service (DoS) attack where a client sends a deeply nested query (e.g., `author { posts { author { posts { ... } } } }`) that causes the server to recursively resolve thousands of database joins and crash", "Cross-Site Scripting (XSS)", "Man-in-the-Middle attacks"],
    "correct_answer": "A DoS attack where a client sends a deeply nested query that causes the server to recursively resolve thousands of database joins and crash",
    "explanation": "Unlike REST, where the server dictates the shape of the response, GraphQL allows the client to request infinite nesting. Depth limiting (e.g., max depth of 5) is a mandatory security middleware to prevent malicious clients from exhausting your server's CPU and database connections."
  },
  {
    "id": 204,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL (DataLoader)",
    "question": "How does the `DataLoader` library solve the N+1 query problem in GraphQL resolvers?",
    "code_snippet": null,
    "options": ["By caching the entire database in memory", "By batching multiple individual `load(id)` calls that occur within the same event loop tick into a single SQL `WHERE id IN (...)` query", "By forcing the client to use REST instead", "By encrypting the database queries"],
    "correct_answer": "By batching multiple individual `load(id)` calls that occur within the same event loop tick into a single SQL query",
    "explanation": "If a GraphQL query asks for 100 users and their posts, the `post` resolver might be called 100 times. DataLoader intercepts these 100 calls, groups the user IDs, and executes exactly ONE database query, then maps the results back to the correct resolvers."
  },
  {
    "id": 205,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Gateway (BFF Pattern)",
    "question": "What is the 'Backend-For-Frontend' (BFF) pattern in API architecture?",
    "code_snippet": null,
    "options": ["Using a single API for all clients", "Creating a dedicated, specialized API layer for each specific frontend client (e.g., a Mobile BFF, a Web BFF) to aggregate and format data exactly as that client needs it", "Hosting the frontend and backend on the same server", "Using GraphQL instead of REST"],
    "correct_answer": "Creating a dedicated, specialized API layer for each specific frontend client to aggregate and format data exactly as that client needs it",
    "explanation": "A mobile app might need a lightweight, aggregated response to save battery and bandwidth, while a web dashboard needs a massive, detailed response. The BFF pattern prevents the generic, internal microservices from having to cater to the specific UI quirks of every different client."
  },
  {
    "id": 206,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Authorization (RBAC vs ABAC)",
    "question": "What is the fundamental difference between Role-Based Access Control (RBAC) and Attribute-Based Access Control (ABAC)?",
    "code_snippet": null,
    "options": ["RBAC is for APIs; ABAC is for databases", "RBAC grants access based on static roles (e.g., 'Admin'); ABAC grants access dynamically based on attributes of the user, the resource, and the environment (e.g., 'User can edit document IF user.department == document.department AND time < 5PM')", "ABAC is deprecated", "RBAC requires a database; ABAC does not"],
    "correct_answer": "RBAC grants access based on static roles; ABAC grants access dynamically based on attributes of the user, resource, and environment",
    "explanation": "RBAC is simple but rigid (Role Explosion problem). ABAC is incredibly flexible and scalable for complex enterprise policies, often evaluated at runtime by a dedicated Policy Decision Point (PDP) like Open Policy Agent (OPA)."
  },
  {
    "id": 207,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "OAuth 2.0 (Client Credentials Flow)",
    "question": "Which OAuth 2.0 flow is specifically designed for Machine-to-Machine (M2M) communication, where a backend service needs to access an API without a human user present?",
    "code_snippet": null,
    "options": ["Authorization Code Flow", "Client Credentials Flow", "Implicit Flow", "PKCE Flow"],
    "correct_answer": "Client Credentials Flow",
    "explanation": "In the Client Credentials flow, the backend service authenticates itself using its own `client_id` and `client_secret` directly with the Authorization Server to get an Access Token. No user login or browser redirect is involved."
  },
  {
    "id": 208,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "OAuth 2.0 (Refresh Token Rotation)",
    "question": "What is 'Refresh Token Rotation', and what security threat does it mitigate?",
    "code_snippet": null,
    "options": ["Changing the JWT signing algorithm daily", "Issuing a brand new Refresh Token every time the Access Token is refreshed, and invalidating the old one; this allows the server to detect if a Refresh Token is stolen and reused (token theft)", "Rotating the database passwords", "Encrypting the refresh token in the browser"],
    "correct_answer": "Issuing a brand new Refresh Token every time the Access Token is refreshed, and invalidating the old one",
    "explanation": "If an attacker steals a Refresh Token and uses it, the legitimate user's next refresh attempt will fail (because the token was already used). The server detects this 'reuse' and instantly revokes the entire token family, locking out the attacker."
  },
  {
    "id": 209,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "JWT (RS256 vs HS256)",
    "question": "Why is the `RS256` (Asymmetric) algorithm generally preferred over `HS256` (Symmetric) for signing JWTs in a microservices architecture?",
    "code_snippet": null,
    "options": ["RS256 is faster to compute", "With RS256, the Auth Server signs with a Private Key, and all microservices verify with a Public Key; this means microservices don't need to share a secret key, preventing a compromised service from forging tokens", "HS256 is deprecated", "RS256 produces smaller tokens"],
    "correct_answer": "With RS256, the Auth Server signs with a Private Key, and microservices verify with a Public Key; preventing a compromised service from forging tokens",
    "explanation": "If you use HS256, every microservice needs the exact same secret key to verify the token. If one microservice is compromised, the attacker can forge valid JWTs for any user. With RS256, microservices only have the read-only Public Key."
  },
  {
    "id": 210,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "JWT Security (Replay Attacks & JTI)",
    "question": "If a stateless JWT is stolen, it can be reused until it expires. How does the `jti` (JWT ID) claim help mitigate this?",
    "code_snippet": null,
    "options": ["It encrypts the payload", "By assigning a unique ID to every token, the server can maintain a blocklist of revoked `jti`s (e.g., in Redis) to reject stolen or logged-out tokens before their expiration", "It compresses the token", "It verifies the user's IP address"],
    "correct_answer": "By assigning a unique ID to every token, the server can maintain a blocklist of revoked `jti`s to reject stolen tokens",
    "explanation": "While JWTs are meant to be stateless, adding a `jti` claim allows you to introduce a tiny bit of state (a Redis blacklist) specifically for token revocation, balancing security and performance."
  },
  {
    "id": 211,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "OWASP API Top 10 (BOLA / IDOR)",
    "question": "What is 'Broken Object Level Authorization' (BOLA), also known as Insecure Direct Object Reference (IDOR), and why is it the #1 API security risk?",
    "code_snippet": null,
    "options": ["When the API uses HTTP instead of HTTPS", "When an API exposes a resource ID (e.g., `/api/invoices/123`) and fails to verify that the currently authenticated user actually owns that specific resource", "When the API rate limit is too high", "When the database is not encrypted"],
    "correct_answer": "When an API exposes a resource ID and fails to verify that the authenticated user actually owns that specific resource",
    "explanation": "If User A is logged in, but can change the URL to `/api/invoices/456` and see User B's invoice, that is BOLA. It happens because developers verify 'Is the user logged in?' but forget to verify 'Does this invoice belong to the logged-in user?'"
  },
  {
    "id": 212,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "CORS (Pre-flight Requests)",
    "question": "Under what conditions does a browser automatically send an `OPTIONS` (Pre-flight) request before the actual API call?",
    "code_snippet": null,
    "options": ["On every single GET request", "When the request uses methods other than GET/HEAD/POST, or includes custom headers (like `Authorization`), or uses non-simple Content-Types (like `application/json`)", "Only when the API returns a 500 error", "When the user is on a mobile device"],
    "correct_answer": "When the request uses non-simple methods, custom headers, or non-simple Content-Types",
    "explanation": "The browser sends an `OPTIONS` request to ask the server: 'Do you allow requests from my origin with the `Authorization` header?' The server must respond with the correct `Access-Control-Allow-*` headers, or the browser will block the actual request."
  },
  {
    "id": 213,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Webhooks (Replay Attacks)",
    "question": "Even if a webhook payload has a valid HMAC signature, how can an attacker perform a 'Replay Attack', and how do you prevent it?",
    "code_snippet": null,
    "options": ["They cannot; HMAC prevents all attacks", "By intercepting a valid payload and resending it hours later; prevented by including a timestamp in the signature and rejecting requests where the timestamp is older than a strict tolerance window (e.g., 5 minutes)", "By changing the JSON payload", "By using a different HTTP method"],
    "correct_answer": "By intercepting a valid payload and resending it later; prevented by including a timestamp and rejecting old requests",
    "explanation": "If an attacker captures a valid 'PaymentReceived' webhook, they can replay it 100 times to credit their account 100 times. By signing the payload *along with a timestamp*, the server can reject any webhook where the timestamp is more than 5 minutes old."
  },
  {
    "id": 214,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "code-fill-in-blank",
    "topic": "API Rate Limiting Headers",
    "question": "Fill in the blank with the standard HTTP response header used to tell the client how many requests they have left in the current rate limit window.",
    "code_snippet": "res.set('_______-Remaining', '42');",
    "options": ["X-RateLimit", "X-Quota", "X-Limit", "X-Requests"],
    "correct_answer": "X-RateLimit",
    "explanation": "Standard rate limit headers include `X-RateLimit-Limit` (total allowed), `X-RateLimit-Remaining` (left in window), and `X-RateLimit-Reset` (Unix timestamp when the window resets). This allows well-behaved clients to throttle themselves gracefully."
  },
  {
    "id": 215,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Documentation (OpenAPI)",
    "question": "What is the OpenAPI Specification (formerly Swagger), and why is it critical for enterprise APIs?",
    "code_snippet": null,
    "options": ["A testing framework", "A standardized, language-agnostic YAML/JSON format for describing REST APIs, enabling automatic client SDK generation, interactive documentation, and automated contract testing", "A database schema language", "A security protocol"],
    "correct_answer": "A standardized format for describing REST APIs, enabling automatic client SDK generation and interactive documentation",
    "explanation": "OpenAPI acts as the single source of truth for your API. Tools can read the OpenAPI file to generate beautiful docs (Swagger UI), generate type-safe TypeScript/Python clients for consumers, and validate that your server actually returns what the docs promise."
  },
  {
    "id": 216,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Security (Mass Assignment)",
    "question": "What is a 'Mass Assignment' vulnerability in an API?",
    "code_snippet": null,
    "options": ["When the API takes too long to respond", "When an API blindly binds the entire incoming JSON request body to a database model, allowing an attacker to modify sensitive fields they shouldn't have access to (e.g., passing `\"isAdmin\": true` in a profile update)", "When the database runs out of connections", "When the API uses XML"],
    "correct_answer": "When an API blindly binds the incoming JSON to a database model, allowing an attacker to modify sensitive fields like `isAdmin`",
    "explanation": "If your `PUT /users/me` endpoint takes the raw JSON body and passes it directly to `User.update(req.body)`, an attacker can add `\"role\": \"admin\"` to the payload. You must use DTOs (Data Transfer Objects) or explicit whitelisting to only allow specific fields to be updated."
  },
  {
    "id": 217,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL (Subscriptions)",
    "question": "How do GraphQL Subscriptions differ from standard Queries and Mutations?",
    "code_snippet": null,
    "options": ["They are faster", "They establish a persistent, long-lived connection (usually via WebSockets) allowing the server to push real-time data updates to the client whenever a specific event occurs", "They are used for database backups", "They only work with SQL databases"],
    "correct_answer": "They establish a persistent connection allowing the server to push real-time data updates to the client",
    "explanation": "Queries are 'pull' (client asks for data). Subscriptions are 'push' (client listens for data). When a new message is created in a chat app, the server automatically pushes the new message to all subscribed clients without them needing to poll."
  },
  {
    "id": 218,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Idempotency (POST vs PUT)",
    "question": "According to HTTP specifications, why is a `PUT` request considered idempotent, while a `POST` request is not?",
    "code_snippet": null,
    "options": ["PUT is faster", "Sending the exact same `PUT` request multiple times results in the same final state (overwriting the resource with the exact same data); `POST` creates a new resource every time, resulting in duplicates", "POST is deprecated", "PUT uses HTTPS; POST uses HTTP"],
    "correct_answer": "Sending the same `PUT` request multiple times results in the same final state; `POST` creates a new resource every time",
    "explanation": "If you `PUT /users/123` with `{name: 'Alice'}` five times, the user's name is just 'Alice'. If you `POST /users` with `{name: 'Alice'}` five times, you now have five different users named Alice. This is why POST requires Idempotency Keys for safe retries."
  },
  {
    "id": 219,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Testing (Contract Testing)",
    "question": "What is the primary goal of 'API Contract Testing' (e.g., using Pact) between a Frontend and Backend team?",
    "code_snippet": null,
    "options": ["Testing the UI design", "Ensuring that the Backend's API actually returns the exact JSON shape and status codes that the Frontend's code expects, preventing integration failures when either side changes independently", "Testing the database speed", "Testing the CSS styles"],
    "correct_answer": "Ensuring that the Backend's API actually returns the exact JSON shape that the Frontend expects, preventing integration failures",
    "explanation": "Instead of relying on a fragile, end-to-end staging environment, Contract Testing creates a 'contract' (a mock). If the Backend changes a field from `userId` to `user_id`, the contract test fails immediately, warning them that they are about to break the Frontend."
  },
  {
    "id": 220,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've now covered HATEOAS, GraphQL security, OAuth2 flows, and OWASP API vulnerabilities. What is the core philosophy of designing a secure, scalable API?",
    "code_snippet": null,
    "options": ["Making the API as complex as possible to hide data", "Treating the API as a strict, untrusting boundary; validating every input, enforcing least-privilege authorization, protecting against abuse, and designing for the client's ease of use and safety", "Using only GET requests", "Disabling all security headers to improve speed"],
    "correct_answer": "Treating the API as a strict, untrusting boundary; validating every input, enforcing least-privilege authorization, and protecting against abuse",
    "explanation": "An API is the front door to your entire backend infrastructure. A Senior API Designer assumes every request is potentially malicious, rigorously enforces boundaries, and builds systems that are easy for legitimate clients to use correctly, but impossible for attackers to exploit."
  }
]
[
  {
    "id": 221,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "WebSockets Scaling (Redis Adapter)",
    "question": "If you scale a Socket.io application across 5 different Node.js servers behind a Load Balancer, how do you ensure that a message emitted on Server A reaches a client connected to Server B?",
    "code_snippet": null,
    "options": ["The Load Balancer automatically duplicates the message", "By using a Pub/Sub adapter (like the Redis Adapter) that broadcasts the event to all Node instances via a shared Redis channel", "WebSockets cannot be scaled horizontally", "By storing the message in a SQL database and polling it"],
    "correct_answer": "By using a Pub/Sub adapter (like the Redis Adapter) that broadcasts the event to all Node instances via a shared Redis channel",
    "explanation": "By default, Socket.io only emits to clients connected to the *current* Node process. The Redis Adapter intercepts the `emit` call, publishes it to a Redis channel, and all other Node instances subscribed to that channel receive it and push it to their local WebSocket clients."
  },
  {
    "id": 222,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "WebSocket Heartbeats (Ping/Pong)",
    "question": "Why are 'Heartbeat' (Ping/Pong) frames critical in a WebSocket architecture?",
    "code_snippet": null,
    "options": ["To encrypt the data stream", "To detect and cleanly close 'zombie' connections where the client's network dropped silently without sending a proper TCP FIN packet", "To compress the payload", "To authenticate the user"],
    "explanation": "Because WebSockets are long-lived TCP connections, a router or NAT might silently drop a connection if it's idle, or a user might walk out of WiFi range. The server sends a 'Ping'; if it doesn't receive a 'Pong' within a timeout, it forcefully cleans up the socket, preventing memory leaks."
  },
  {
    "id": 223,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "gRPC (Bidirectional Streaming)",
    "question": "What is 'Bidirectional Streaming' in gRPC, and what is a real-world use case for it?",
    "code_snippet": null,
    "options": ["Sending a single request and getting a single response", "Both the client and the server send a continuous stream of messages to each other concurrently over a single HTTP/2 connection; use case: real-time multiplayer gaming or collaborative document editing", "Streaming a file from the server to the client only", "Sending HTTP headers without a body"],
    "correct_answer": "Both the client and the server send a continuous stream of messages to each other concurrently over a single HTTP/2 connection; use case: real-time multiplayer gaming or collaborative document editing",
    "explanation": "Unlike standard REST or even Server-Sent Events, gRPC bidirectional streaming allows full-duplex communication. The client can stream sensor data while simultaneously receiving control commands from the server, all multiplexed over one TCP connection."
  },
  {
    "id": 224,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Analytics (The Golden Signals)",
    "question": "When monitoring an API for performance and reliability, what are the 'Four Golden Signals' defined by Google SRE?",
    "code_snippet": null,
    "options": ["CPU, RAM, Disk, Network", "Latency, Traffic, Errors, and Saturation", "GET, POST, PUT, DELETE", "Users, Sessions, Conversions, Bounce Rate"],
    "correct_answer": "Latency, Traffic, Errors, and Saturation",
    "explanation": "Latency (how long requests take), Traffic (demand placed on the system), Errors (rate of failed requests), and Saturation (how 'full' your resources are, like connection pools or CPU). These four metrics give a complete picture of API health."
  },
  {
    "id": 225,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Monetization (Tiered Rate Limiting)",
    "question": "How do you architect an API Gateway to support tiered monetization (e.g., Free: 100 req/min, Pro: 10,000 req/min)?",
    "code_snippet": null,
    "options": ["By hardcoding limits in the application code", "By extracting the API Key from the request, looking up its associated tier in a fast cache (like Redis), and applying the corresponding rate limit algorithm dynamically", "By using different domain names for each tier", "By limiting based on the user's IP address only"],
    "correct_answer": "By extracting the API Key, looking up its tier in a fast cache, and applying the corresponding rate limit dynamically",
    "explanation": "The API Gateway acts as the enforcement point. It reads the `X-API-Key` header, checks Redis for the key's metadata (e.g., `tier: pro`), and applies the specific sliding-window or token-bucket limit associated with that tier before routing the request."
  },
  {
    "id": 226,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Zero Trust Architecture (Micro-segmentation)",
    "question": "In a Zero Trust internal API architecture, what does 'Micro-segmentation' mean?",
    "code_snippet": null,
    "options": ["Using microservices instead of a monolith", "Encrypting the database", "Treating every internal service-to-service communication as untrusted, requiring strict identity verification and least-privilege access, even if they are on the same private VPC", "Splitting the database into shards"],
    "correct_answer": "Treating every internal service-to-service communication as untrusted, requiring strict identity verification and least-privilege access, even if they are on the same private VPC",
    "explanation": "The old 'castle and moat' security model assumed everything inside the VPC was safe. Zero Trust dictates that if the Billing Service calls the User Service, it must present a valid identity and have explicit permission to do so, preventing lateral movement if one service is compromised."
  },
  {
    "id": 227,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "mTLS (Mutual TLS)",
    "question": "How does Mutual TLS (mTLS) differ from standard TLS (HTTPS)?",
    "code_snippet": null,
    "options": ["mTLS is faster", "In standard TLS, only the server proves its identity via a certificate; in mTLS, BOTH the client and the server must present and verify X.509 certificates before the connection is established", "mTLS does not use encryption", "mTLS is only for WebSockets"],
    "correct_answer": "In standard TLS, only the server proves its identity; in mTLS, BOTH the client and the server must present and verify certificates",
    "explanation": "mTLS guarantees that the client making the API request is exactly who they claim to be at the network layer, completely eliminating the risk of spoofed internal services or unauthorized third-party clients connecting to your API."
  },
  {
    "id": 228,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Service Mesh (Sidecar Proxy)",
    "question": "How does a Service Mesh (like Istio or Linkerd) enforce mTLS and retries without requiring developers to write that logic in their Node.js code?",
    "code_snippet": null,
    "options": ["It modifies the Node.js source code automatically", "By injecting an invisible 'Sidecar Proxy' (like Envoy) into every Pod that intercepts all incoming and outgoing network traffic, handling TLS, routing, and observability transparently", "It uses a centralized database for all traffic", "It replaces the Node.js runtime"],
    "correct_answer": "By injecting an invisible 'Sidecar Proxy' into every Pod that intercepts all network traffic, handling TLS and routing transparently",
    "explanation": "The application code just sends plain HTTP to `localhost`. The Sidecar proxy intercepts it, wraps it in mTLS, adds tracing headers, and sends it to the destination's Sidecar. This decouples security/observability from business logic."
  },
  {
    "id": 229,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Penetration Testing (Fuzzing)",
    "question": "What is 'API Fuzzing' in the context of security testing?",
    "code_snippet": null,
    "options": ["Compressing the API payload", "Automatically sending thousands of malformed, unexpected, or random data payloads to API endpoints to discover crashes, memory leaks, or unhandled exceptions", "Testing the UI design", "Encrypting the database"],
    "correct_answer": "Automatically sending thousands of malformed, unexpected, or random data payloads to API endpoints to discover crashes or unhandled exceptions",
    "explanation": "Fuzzing tools (like Postman Fuzzing or dedicated tools) mutate valid JSON requests into invalid ones (e.g., sending a string where an integer is expected, or a 10MB string where a 10-char limit exists) to find edge cases that developers missed."
  },
  {
    "id": 230,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "HTTP/3 (QUIC Protocol)",
    "question": "What is the underlying transport protocol that HTTP/3 is built upon, replacing TCP?",
    "code_snippet": null,
    "options": ["UDP (via the QUIC protocol)", "WebSockets", "SCTP", "ICMP"],
    "correct_answer": "UDP (via the QUIC protocol)",
    "explanation": "HTTP/3 uses QUIC (Quick UDP Internet Connections), which runs over UDP. This eliminates the TCP handshake overhead, allows connection migration (e.g., switching from WiFi to 5G without dropping the connection), and prevents Head-of-Line blocking."
  },
  {
    "id": 231,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "HTTP/3 (Solving Head-of-Line Blocking)",
    "question": "How does HTTP/3 over QUIC solve the 'Head-of-Line Blocking' problem that plagued HTTP/2 over TCP?",
    "code_snippet": null,
    "options": ["It uses a faster CPU", "Because UDP doesn't guarantee order, QUIC implements independent streams; if a packet is lost on Stream A, Stream B can still be delivered and processed immediately without waiting", "It compresses the packets", "It uses a single massive connection"],
    "correct_answer": "Because UDP doesn't guarantee order, QUIC implements independent streams; if a packet is lost on Stream A, Stream B can still be delivered without waiting",
    "explanation": "In TCP, if packet #2 is lost, packets #3, #4, and #5 cannot be processed until #2 is retransmitted, even if they belong to completely different HTTP requests. QUIC multiplexes streams at the transport layer, isolating packet loss to only the affected stream."
  },
  {
    "id": 232,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "WebTransport",
    "question": "What is 'WebTransport', and how does it improve upon WebSockets for modern web apps?",
    "code_snippet": null,
    "options": ["It is a replacement for HTTP", "A web API built on HTTP/3 that supports reliable streams, unreliable datagrams, and bidirectional communication, offering better firewall traversal and native flow control compared to WebSockets", "It is a database protocol", "It is a CSS framework"],
    "correct_answer": "A web API built on HTTP/3 that supports reliable streams, unreliable datagrams, and bidirectional communication",
    "explanation": "WebSockets are strictly ordered and reliable (TCP). WebTransport allows developers to choose: use reliable streams for chat, or unreliable datagrams (like UDP) for real-time gaming where a dropped frame is better than a delayed one."
  },
  {
    "id": 233,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Security (Graceful Secret Rotation)",
    "question": "When rotating a critical API key or database password, how do you prevent downtime for clients currently using the old key?",
    "code_snippet": null,
    "options": ["Shut down the server during the rotation", "Implement a 'Graceful Overlap' period where the server accepts BOTH the old and new keys simultaneously, communicate the new key to clients, and only revoke the old key after a safe window", "Email the clients to update their code instantly", "Use a random number generator"],
    "correct_answer": "Implement a 'Graceful Overlap' period where the server accepts BOTH the old and new keys simultaneously",
    "explanation": "If you revoke the old key instantly, any client mid-request or using a cached key will fail. By accepting both keys for a set period (e.g., 24 hours), you allow clients to naturally rotate at their own pace without breaking production."
  },
  {
    "id": 234,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Bot Mitigation (JA3 Fingerprinting)",
    "question": "How does 'JA3 Fingerprinting' help differentiate between legitimate API clients and malicious bots, even if they spoof their User-Agent?",
    "code_snippet": null,
    "options": ["By analyzing the database queries", "By hashing the client's TLS ClientHello packet (cipher suites, extensions, elliptic curves); bots using Python/cURL have distinctly different TLS fingerprints than real Chrome/Safari browsers", "By checking the user's password", "By measuring the screen resolution"],
    "correct_answer": "By hashing the client's TLS ClientHello packet; bots using Python/cURL have distinctly different TLS fingerprints than real browsers",
    "explanation": "A malicious bot can easily send `User-Agent: Mozilla/5.0 (Chrome)`. But it cannot easily fake the exact, complex TLS handshake parameters of a real Chrome browser. JA3 captures this network-level fingerprint to block sophisticated scrapers."
  },
  {
    "id": 235,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL (Persisted Queries)",
    "question": "What are 'Persisted Queries' in GraphQL, and what security/performance benefit do they provide?",
    "code_snippet": null,
    "options": ["Caching the database results", "Sending a unique hash (ID) of the query instead of the full query string; the server looks up the pre-registered query, saving bandwidth and preventing arbitrary/malicious query injection", "Encrypting the schema", "Disabling subscriptions"],
    "correct_answer": "Sending a unique hash of the query instead of the full string; saving bandwidth and preventing arbitrary query injection",
    "explanation": "In production, you pre-compile all allowed GraphQL queries and store them on the server. The client only sends the `queryHash`. This drastically reduces payload size and acts as a strict whitelist, completely neutralizing arbitrary query DoS attacks."
  },
  {
    "id": 236,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "code-fill-in-blank",
    "topic": "API Deprecation (Sunset Header)",
    "question": "Fill in the blank with the standard HTTP response header used to inform API consumers that a specific endpoint or version is being deprecated and will be removed on a specific date.",
    "code_snippet": "res.set('_______', 'Wed, 01 Jan 2025 23:59:59 GMT');",
    "options": ["Deprecation", "Sunset", "Expires", "Remove"],
    "correct_answer": "Sunset",
    "explanation": "The `Sunset` header (often paired with the `Deprecation: true` header) is the RFC-standard way to tell clients exactly when an API will die. Monitoring tools can alert developers when they receive responses with this header, prompting them to migrate."
  },
  {
    "id": 237,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Security (Credential Stuffing)",
    "question": "What is 'Credential Stuffing', and what is the most effective API-level defense against it?",
    "code_snippet": null,
    "options": ["Guessing passwords one by one; defense: CAPTCHA", "Automated login attempts using millions of username/password pairs leaked from OTHER breaches; defense: strict rate limiting on login endpoints, device fingerprinting, and enforcing MFA", "Stealing cookies; defense: HTTPS", "SQL Injection; defense: parameterized queries"],
    "correct_answer": "Automated login attempts using leaked credentials from other breaches; defense: strict rate limiting, device fingerprinting, and MFA",
    "explanation": "Attackers don't hack your database; they buy a list of 10 million emails/passwords from a dark web breach of a different site, and use bots to try them on your `/login` API. Rate limiting per IP/Device and requiring MFA completely stops this."
  },
  {
    "id": 238,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Gateway (Request/Response Transformation)",
    "question": "What is 'Request Transformation' at the API Gateway level?",
    "code_snippet": null,
    "options": ["Translating code to machine language", "Modifying headers, converting payload formats (e.g., XML to JSON), or injecting context (like a `tenant_id`) before the request reaches the backend microservice", "Compressing the database", "Routing traffic to the database"],
    "correct_answer": "Modifying headers, converting payload formats, or injecting context before the request reaches the backend",
    "explanation": "Instead of forcing every backend microservice to parse legacy XML or figure out the tenant ID from a JWT, the API Gateway handles the heavy lifting, transforming the request into a clean, standardized JSON format that the backend expects."
  },
  {
    "id": 239,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Supply Chain Security",
    "question": "How do API dependencies (npm packages) introduce security risks, and how is this mitigated?",
    "code_snippet": null,
    "options": ["They don't; npm is 100% secure", "A compromised dependency can intercept API traffic, steal keys, or alter responses; mitigated by using lockfiles, automated auditing (Snyk/Socket), and generating SBOMs (Software Bill of Materials)", "By using older versions of packages", "By avoiding TypeScript"],
    "correct_answer": "A compromised dependency can intercept API traffic or steal keys; mitigated by lockfiles, automated auditing, and SBOMs",
    "explanation": "If a popular npm package you use for JWT validation is hijacked by a malicious actor, they can silently siphon your users' tokens. Supply chain security requires strict lockfiles, continuous vulnerability scanning, and knowing exactly what code is running in your app."
  },
  {
    "id": 240,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (The Future of APIs)",
    "question": "As APIs evolve toward HTTP/3, WebTransport, and Zero Trust, what is the ultimate mindset of an API Security Architect?",
    "code_snippet": null,
    "options": ["To block all external traffic", "To assume the network is inherently hostile and unpredictable; designing APIs that verify every identity, encrypt every payload, gracefully handle protocol shifts, and survive supply-chain compromises without losing user trust", "To use only REST", "To disable all logging to save space"],
    "correct_answer": "To assume the network is inherently hostile; designing APIs that verify every identity, encrypt every payload, gracefully handle protocol shifts, and survive supply-chain compromises",
    "explanation": "The future of APIs isn't just about faster protocols; it's about building resilient, zero-trust boundaries. A true Architect designs systems that remain secure and functional whether the client is on HTTP/1.1 or HTTP/3, and whether the network is perfect or under active attack."
  }
]
[
  {
    "id": 241,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL Federation (Concept)",
    "question": "What is 'GraphQL Federation' (Apollo Federation), and what problem does it solve at enterprise scale?",
    "code_snippet": null,
    "options": ["A caching layer for GraphQL", "A framework for composing a single, unified GraphQL API (Supergraph) from multiple independently deployed, team-owned Subgraphs (microservices), without a monolithic schema", "A database ORM for GraphQL", "A security protocol for GraphQL"],
    "correct_answer": "A framework for composing a single, unified GraphQL API from multiple independently deployed, team-owned Subgraphs",
    "explanation": "Instead of one massive GraphQL server owned by one team, Federation allows the User Team to own the `User` subgraph, the Product Team to own the `Product` subgraph, and the Gateway stitches them into one seamless API for the client."
  },
  {
    "id": 242,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL Federation (Entity Resolution)",
    "question": "In GraphQL Federation, how does the Gateway resolve a `User` entity that spans multiple subgraphs (e.g., User Service has `name`, Order Service has `orders`)?",
    "code_snippet": null,
    "options": ["It queries a shared database", "Using the `@key` directive and `__resolveReference` resolver; the Gateway fetches the base entity from one subgraph, then passes its key to other subgraphs to fetch their extended fields", "It duplicates the data across all subgraphs", "It uses REST internally"],
    "correct_answer": "Using the `@key` directive and `__resolveReference` resolver; the Gateway passes the entity's key to other subgraphs to fetch their extended fields",
    "explanation": "The User subgraph defines `type User @key(fields: \"id\")`. The Order subgraph extends it: `extend type User @key(fields: \"id\") { orders: [Order] }`. The Gateway fetches the user, then calls the Order subgraph with `{ _typename: 'User', id: '123' }` to get the orders."
  },
  {
    "id": 243,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL Federation (Schema Composition)",
    "question": "What is the 'Supergraph Schema' in Apollo Federation?",
    "code_snippet": null,
    "options": ["The database schema", "The composed, unified schema generated by merging all subgraph schemas together, which the Gateway uses to plan and execute distributed queries", "The client-side schema", "The authentication schema"],
    "correct_answer": "The composed, unified schema generated by merging all subgraph schemas, which the Gateway uses to plan distributed queries",
    "explanation": "The Supergraph is the 'map' that tells the Gateway which subgraph owns which fields. When a client queries `{ user { name orders { total } } }`, the Gateway reads the Supergraph, plans the execution across subgraphs, and stitches the results."
  },
  {
    "id": 244,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Observability (Distributed Tracing for APIs)",
    "question": "How does Distributed Tracing (OpenTelemetry) work across an API Gateway and multiple backend microservices?",
    "code_snippet": null,
    "options": ["Each service generates its own independent trace", "The Gateway generates a unique Trace ID and propagates it via HTTP headers (like `traceparent`) to every downstream service, allowing all spans to be stitched into a single waterfall timeline", "The database generates the trace", "Tracing only works within a single service"],
    "correct_answer": "The Gateway generates a unique Trace ID and propagates it via HTTP headers to every downstream service, stitching all spans into a single timeline",
    "explanation": "The `traceparent` header (W3C Trace Context standard) carries the Trace ID and Span ID. Every service creates a child span, logs its duration, and passes the header downstream. Tools like Jaeger or Datadog reconstruct the full request journey."
  },
  {
    "id": 245,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Observability (Error Budgets & SLOs)",
    "question": "What is an 'Error Budget' in the context of API reliability (SRE)?",
    "code_snippet": null,
    "options": ["The amount of money spent on error logging", "The acceptable amount of downtime or error rate (e.g., 0.1% of requests can fail) that a team is allowed to 'spend' before halting feature development to focus on reliability", "The number of bugs in the codebase", "The size of the error log files"],
    "correct_answer": "The acceptable amount of downtime or error rate that a team is allowed before halting feature development to focus on reliability",
    "explanation": "If your SLO is 99.9% availability, your Error Budget is 0.1% (about 43 minutes of downtime per month). Once the budget is exhausted, the team stops shipping features and focuses entirely on fixing reliability issues."
  },
  {
    "id": 246,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Edge API Security (WAF)",
    "question": "What is a Web Application Firewall (WAF), and how does it protect APIs at the Edge?",
    "code_snippet": null,
    "options": ["A firewall that blocks all traffic", "A security layer that inspects incoming HTTP requests against a set of rules (like OWASP Top 10 signatures) to block SQL injection, XSS, and malicious payloads before they reach the application server", "A database encryption tool", "A load balancer"],
    "correct_answer": "A security layer that inspects incoming HTTP requests against rules to block malicious payloads before they reach the application server",
    "explanation": "A WAF (like AWS WAF, Cloudflare WAF, or ModSecurity) sits at the network perimeter. It analyzes request bodies, headers, and URLs for known attack patterns (like `' OR 1=1 --`) and drops them instantly, protecting your backend without any code changes."
  },
  {
    "id": 247,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "GraphQL Subscriptions at Scale",
    "question": "What is the primary scaling challenge of GraphQL Subscriptions (WebSockets) in a multi-server environment?",
    "code_snippet": null,
    "options": ["WebSockets are too slow", "Each WebSocket connection is stateful and pinned to a specific server; publishing an event on Server A won't reach subscribers connected to Server B without a shared Pub/Sub layer (like Redis or NATS)", "GraphQL doesn't support subscriptions", "WebSockets cannot be encrypted"],
    "correct_answer": "Each WebSocket connection is stateful and pinned to a specific server; publishing on Server A won't reach subscribers on Server B without a shared Pub/Sub layer",
    "explanation": "Unlike stateless HTTP requests, WebSocket connections maintain a persistent TCP socket to a specific Node.js process. To broadcast a 'NewMessage' event to all subscribers globally, you need Redis Pub/Sub or a dedicated message broker to fan out the event across all server instances."
  },
  {
    "id": 248,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Data Privacy (GDPR - Right to Erasure)",
    "question": "How does the GDPR 'Right to Erasure' (Article 17) impact API and database architecture?",
    "code_snippet": null,
    "options": ["It only affects the frontend UI", "APIs must support the complete, cascading deletion of ALL personal data associated with a user across every microservice, database, backup, and third-party integration upon request", "It only applies to European servers", "It requires encrypting all data"],
    "correct_answer": "APIs must support complete, cascading deletion of ALL personal data across every microservice, database, backup, and third-party integration",
    "explanation": "When a user requests deletion, your system must purge their data from the primary DB, all read replicas, caches (Redis), search indexes (Elasticsearch), analytics warehouses, and notify third-party processors. This requires a well-designed 'User Deletion' event that cascades through your entire architecture."
  },
  {
    "id": 249,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Data Privacy (Data Minimization)",
    "question": "What does the GDPR principle of 'Data Minimization' require from API designers?",
    "code_snippet": null,
    "options": ["Return as much data as possible for flexibility", "APIs should only collect, process, and return the absolute minimum personal data necessary for the specific, stated purpose", "Encrypt all API responses", "Store data for as long as possible"],
    "correct_answer": "APIs should only collect, process, and return the absolute minimum personal data necessary for the specific purpose",
    "explanation": "If a 'Get User Profile' endpoint only needs to display a name and avatar, it should NOT return the user's email, phone number, and billing address. Over-fetching personal data violates Data Minimization and increases your breach liability."
  },
  {
    "id": 250,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Governance (Schema Registry)",
    "question": "What is a 'Schema Registry' (like Confluent Schema Registry or Apollo Studio) in API governance?",
    "code_snippet": null,
    "options": ["A database for storing user data", "A centralized, version-controlled repository for API schemas (GraphQL SDL, Protobuf, Avro) that enforces backwards compatibility checks before any schema change is deployed", "A CSS style guide", "A testing framework"],
    "correct_answer": "A centralized, version-controlled repository for API schemas that enforces backwards compatibility checks before deployment",
    "explanation": "If a developer tries to remove a field from a GraphQL type or change a Protobuf field number, the Schema Registry's CI check will block the PR, preventing a breaking change from reaching production and crashing downstream consumers."
  },
  {
    "id": 251,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Versioning (Semantic Versioning)",
    "question": "In API design, what constitutes a 'Breaking Change' that requires a major version bump (e.g., v1 → v2)?",
    "code_snippet": null,
    "options": ["Adding a new optional field to a response", "Removing a field, changing a field's type, renaming an endpoint, or changing the semantics of an existing parameter", "Adding a new endpoint", "Fixing a typo in documentation"],
    "correct_answer": "Removing a field, changing a field's type, renaming an endpoint, or changing the semantics of an existing parameter",
    "explanation": "Adding a new optional field is backwards-compatible (old clients ignore it). Removing a field or changing `age: number` to `age: string` will crash every existing consumer. These require a major version bump and a deprecation period."
  },
  {
    "id": 252,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Backwards Compatibility (Additive Changes)",
    "question": "Which of the following changes to a REST API response is considered 'Additive' (non-breaking) and does NOT require a version bump?",
    "code_snippet": null,
    "options": ["Removing the `email` field from the response", "Changing `price` from a number to a string", "Adding a new `middleName` field to the response object", "Renaming `/users` to `/people`"],
    "correct_answer": "Adding a new `middleName` field to the response object",
    "explanation": "Well-written clients ignore unknown fields. Adding a new field doesn't break existing parsing logic. Removing, renaming, or changing types DOES break clients. This is why 'additive-only' evolution is the gold standard for API longevity."
  },
  {
    "id": 253,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Security (JWT in URL vs Header)",
    "question": "Why is passing a JWT as a query parameter (`?token=eyJ...`) considered a severe security anti-pattern?",
    "code_snippet": null,
    "options": ["It makes the request slower", "URLs are logged in server access logs, browser history, proxy logs, and the `Referer` header, exposing the token to anyone with log access", "It increases the payload size", "It doesn't work with HTTPS"],
    "correct_answer": "URLs are logged in server access logs, browser history, proxy logs, and the Referer header, exposing the token",
    "explanation": "Every CDN, proxy, and web server logs the full URL. If your JWT is in the query string, it ends up in plaintext in dozens of log files. Always pass tokens in the `Authorization: Bearer <token>` header, which is never logged by default."
  },
  {
    "id": 254,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Security (Response Filtering)",
    "question": "Why must APIs implement strict 'Response Filtering' (or Field-Level Access Control)?",
    "code_snippet": null,
    "options": ["To make the response smaller", "To ensure that sensitive fields (like `ssn`, `internalNotes`, or `role`) are stripped from the response based on the requesting user's permissions, preventing information leakage", "To compress the JSON", "To encrypt the response"],
    "correct_answer": "To ensure that sensitive fields are stripped from the response based on the requesting user's permissions",
    "explanation": "A regular user calling `GET /users/123` should receive `{ name, email }`. An admin calling the same endpoint should receive `{ name, email, ssn, internalNotes }`. The API must dynamically filter the response shape based on the caller's role."
  },
  {
    "id": 255,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Design (Idempotent DELETE)",
    "question": "Why is the HTTP `DELETE` method considered idempotent, and how should an API handle a DELETE request for a resource that doesn't exist?",
    "code_snippet": null,
    "options": ["Return a 404 Not Found error", "Return a 204 No Content (success), because the desired end-state (resource not existing) is already achieved", "Return a 500 Internal Server Error", "Create the resource and then delete it"],
    "correct_answer": "Return a 204 No Content, because the desired end-state (resource not existing) is already achieved",
    "explanation": "Idempotency means 'the same result regardless of how many times you call it.' If the resource is already gone, calling DELETE again still results in 'resource doesn't exist.' Returning 204 (or 200) is correct. Returning 404 breaks retry logic in clients."
  },
  {
    "id": 256,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Design (Envelope Pattern)",
    "question": "What is the 'Response Envelope' pattern in API design?",
    "code_snippet": null,
    "options": ["Encrypting the response", "Wrapping the actual data payload in a consistent outer structure (e.g., `{ data: {...}, meta: {...}, errors: [...] }`) to provide a uniform contract for all endpoints", "Compressing the response with gzip", "Using XML instead of JSON"],
    "correct_answer": "Wrapping the data in a consistent outer structure to provide a uniform contract for all endpoints",
    "explanation": "Instead of returning raw arrays or objects, an envelope like `{ data: [...], pagination: { nextCursor: '...' }, errors: [] }` gives clients a predictable structure to parse, regardless of the endpoint. It also provides a clean place to attach metadata and errors."
  },
  {
    "id": 257,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Security (Timing Attacks)",
    "question": "What is a 'Timing Attack' on an API, and how do you prevent it when comparing secrets (like API keys or HMAC signatures)?",
    "code_snippet": null,
    "options": ["An attack that measures server response time", "An attack that measures the exact time a string comparison takes to deduce the correct secret character-by-character; prevented by using constant-time comparison functions (like `crypto.timingSafeEqual`)", "An attack that overloads the server", "An attack on the database"],
    "correct_answer": "An attack that measures string comparison time to deduce secrets; prevented by using constant-time comparison functions",
    "explanation": "Standard `===` returns `false` as soon as the first character mismatches. An attacker can measure that a 1ms response means 'first char wrong' and a 2ms response means 'first char right, second char wrong.' `crypto.timingSafeEqual` always takes the same time regardless of where the mismatch is."
  },
  {
    "id": 258,
    "level": "intermediate",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "API Documentation (Living Docs)",
    "question": "What is the 'Docs-as-Code' approach to API documentation?",
    "code_snippet": null,
    "options": ["Writing docs in Microsoft Word", "Storing API documentation (OpenAPI specs, Markdown guides) in the same Git repository as the code, reviewing it via Pull Requests, and auto-publishing it on every merge", "Hiring a technical writer to maintain a wiki", "Using only inline code comments"],
    "correct_answer": "Storing API documentation in the same Git repository as the code, reviewing via PRs, and auto-publishing on merge",
    "explanation": "When docs live in a separate wiki, they rot. When they live in the repo alongside the code, the same PR that changes an endpoint MUST update the OpenAPI spec. CI can enforce this, ensuring documentation never drifts from reality."
  },
  {
    "id": 259,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "The API Economy (Platform Thinking)",
    "question": "What does it mean to treat your API as a 'Product' rather than just a 'technical interface'?",
    "code_snippet": null,
    "options": ["Adding more endpoints", "Designing the API with the developer experience (DX) as the primary user; providing excellent docs, SDKs, sandbox environments, clear error messages, and versioning stability to attract and retain external consumers", "Making the API free", "Removing authentication"],
    "correct_answer": "Designing the API with developer experience as the primary user; providing excellent docs, SDKs, sandboxes, and stability",
    "explanation": "Companies like Stripe, Twilio, and Shopify treat their APIs as their core product. The quality of the documentation, the clarity of error messages, and the stability of the contract directly determine revenue. The API IS the product."
  },
  {
    "id": 260,
    "level": "advanced",
    "module_id": "node_mod_04_api_security",
    "module_name": "Advanced API Design & Security",
    "type": "conceptual",
    "topic": "Backend & Systems Track Wrap-up (The Architect's Oath)",
    "question": "You have now completed the entire Backend & Systems Architecture track (4 modules, 260 questions). What is the ultimate oath of a Backend Systems Architect?",
    "code_snippet": null,
    "options": ["To use the most complex technology stack possible", "To build systems that are correct under all conditions, resilient against all failures, secure against all threats, and simple enough for the next engineer to understand and maintain at 3 AM during an outage", "To never write a bug", "To avoid all third-party dependencies"],
    "correct_answer": "To build systems that are correct under all conditions, resilient against all failures, secure against all threats, and simple enough for the next engineer to understand and maintain at 3 AM during an outage",
    "explanation": "The true measure of a Backend Architect is not the complexity of their system, but its resilience and clarity. When the database fails, when the network partitions, when a malicious actor probes the API at 3 AM—your system must survive, recover, and protect its users. Congratulations on completing this monumental track!"
  }
]
