[
  {
    "id": 121,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Monolith vs Microservices",
    "question": "What is the primary architectural difference between a Monolith and a Microservices architecture?",
    "code_snippet": null,
    "options": ["Monoliths use SQL; Microservices use NoSQL", "A Monolith is a single, unified codebase and deployment unit; Microservices decompose the application into small, independently deployable services communicating over a network", "Microservices are always faster", "Monoliths cannot use TypeScript"],
    "correct_answer": "A Monolith is a single, unified codebase and deployment unit; Microservices decompose the application into small, independently deployable services communicating over a network",
    "explanation": "Monoliths are simpler to develop and deploy initially but become difficult to scale and maintain as the team grows. Microservices allow independent scaling and tech-stack diversity per service, but introduce massive complexity in networking, deployment, and data consistency."
  },
  {
    "id": 122,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "The CAP Theorem",
    "question": "According to the CAP Theorem, in the event of a network Partition (P), a distributed data store must choose between which two properties?",
    "code_snippet": null,
    "options": ["Latency and Throughput", "Consistency (C) and Availability (A)", "Security and Performance", "Durability and Atomicity"],
    "correct_answer": "Consistency (C) and Availability (A)",
    "explanation": "The CAP theorem states that a distributed system can only provide two of three guarantees: Consistency, Availability, and Partition Tolerance. Since network partitions (P) are inevitable in distributed systems, architects must choose: do we return an error to maintain Consistency (CP), or do we return potentially stale data to remain Available (AP)?"
  },
  {
    "id": 123,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "CAP Theorem (Examples)",
    "question": "Which of the following databases is considered an 'AP' (Availability + Partition Tolerance) system?",
    "code_snippet": null,
    "options": ["PostgreSQL", "MongoDB (in default multi-node setup) or Cassandra", "Redis (Single node)", "MySQL with InnoDB"],
    "correct_answer": "MongoDB (in default multi-node setup) or Cassandra",
    "explanation": "Databases like Cassandra or DynamoDB prioritize Availability. If a network split occurs, they will continue to accept writes on both sides of the partition, eventually reconciling the data later (Eventual Consistency). PostgreSQL, conversely, is CP; it will halt writes to preserve strict consistency."
  },
  {
    "id": 124,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "The PACELC Theorem",
    "question": "How does the PACELC theorem extend the CAP theorem?",
    "code_snippet": null,
    "options": ["It adds Security to the equation", "It states that EVEN IF the system is NOT experiencing a Partition (ELC), it must choose between Latency (L) and Consistency (C) during normal operation", "It proves CAP is wrong", "It applies only to relational databases"],
    "correct_answer": "It states that EVEN IF the system is NOT experiencing a Partition (ELC), it must choose between Latency (L) and Consistency (C) during normal operation",
    "explanation": "CAP only describes behavior during a network failure. PACELC points out that even when the network is fine, a distributed system must choose: do we replicate data synchronously for strict Consistency (adding Latency), or asynchronously for low Latency (sacrificing immediate Consistency)?"
  },
  {
    "id": 125,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Horizontal vs Vertical Scaling",
    "question": "What is the difference between Vertical Scaling (Scale-Up) and Horizontal Scaling (Scale-Out)?",
    "code_snippet": null,
    "options": ["Vertical is for databases; Horizontal is for APIs", "Vertical means adding more CPU/RAM to a single existing server; Horizontal means adding more servers (nodes) to the pool", "Horizontal is slower", "Vertical requires a load balancer"],
    "correct_answer": "Vertical means adding more CPU/RAM to a single existing server; Horizontal means adding more servers (nodes) to the pool",
    "explanation": "Vertical scaling has a hard physical limit (the biggest motherboard available) and requires downtime. Horizontal scaling is theoretically infinite and allows for zero-downtime deployments, but requires the application to be stateless and designed for distributed systems."
  },
  {
    "id": 126,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Statelessness",
    "question": "Why must web servers in a horizontally scaled architecture be 'Stateless'?",
    "code_snippet": null,
    "options": ["Because stateless code runs faster", "Because if a server stores user session data in its local memory, a subsequent request routed to a DIFFERENT server will fail to find that session", "Because stateful servers cannot use TypeScript", "Because stateless servers don't need a database"],
    "correct_answer": "Because if a server stores user session data in its local memory, a subsequent request routed to a DIFFERENT server will fail to find that session",
    "explanation": "If Server A holds the user's session, and the Load Balancer sends the next request to Server B, Server B won't know who the user is. Stateless servers force you to store session state in a centralized, shared data store like Redis or a database."
  },
  {
    "id": 127,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Load Balancers (L4 vs L7)",
    "question": "What is the difference between a Layer 4 (Transport) and Layer 7 (Application) Load Balancer?",
    "code_snippet": null,
    "options": ["L4 is for HTTP; L7 is for TCP", "L4 routes traffic based on IP and Port (fast, but blind to content); L7 inspects the actual HTTP headers, URLs, and cookies to make intelligent routing decisions", "L7 is faster than L4", "L4 requires SSL termination"],
    "correct_answer": "L4 routes traffic based on IP and Port (fast, but blind to content); L7 inspects the actual HTTP headers, URLs, and cookies to make intelligent routing decisions",
    "explanation": "An L7 Load Balancer (like NGINX or AWS ALB) can route `/api/*` to the backend servers and `/static/*` to a CDN, or route requests with a specific `Authorization` header to a premium tier of servers. L4 (like AWS NLB) just forwards the raw TCP packets."
  },
  {
    "id": 128,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Load Balancing Algorithms",
    "question": "Which load balancing algorithm is best suited for a cluster of servers with varying CPU/RAM capacities?",
    "code_snippet": null,
    "options": ["Round Robin", "Least Connections (or Weighted Least Connections)", "Random", "First Available"],
    "correct_answer": "Least Connections (or Weighted Least Connections)",
    "explanation": "Round Robin blindly sends 1 request to Server A, 1 to Server B, regardless of whether Server A is currently processing a heavy 10-second query. 'Least Connections' dynamically routes new traffic to the server that is currently the least busy, ensuring even load distribution."
  },
  {
    "id": 129,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Consistent Hashing",
    "question": "What problem does 'Consistent Hashing' solve in a distributed caching system (like Memcached or Redis Cluster)?",
    "code_snippet": null,
    "options": ["It encrypts the cache keys", "It minimizes the number of keys that need to be remapped to different servers when a cache node is added or removed", "It ensures all keys are stored on a single server", "It automatically deletes expired keys"],
    "correct_answer": "It minimizes the number of keys that need to be remapped to different servers when a cache node is added or removed",
    "explanation": "Standard hashing (`hash(key) % N`) causes almost ALL keys to shift to a new server when `N` changes. Consistent Hashing maps both servers and keys to a circular hash ring. When a server dies, only the keys immediately preceding it on the ring are remapped, preventing a catastrophic cache stampede."
  },
  {
    "id": 130,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "API Gateway",
    "question": "What is the primary role of an 'API Gateway' in a microservices architecture?",
    "code_snippet": null,
    "options": ["To store the database", "To act as the single entry point for all clients, handling request routing, composition, authentication, and rate limiting, so individual microservices don't have to", "To compile TypeScript", "To load balance the database"],
    "correct_answer": "To act as the single entry point for all clients, handling request routing, composition, authentication, and rate limiting",
    "explanation": "Instead of the mobile app needing to know the URLs of 20 different microservices, it talks to the API Gateway. The Gateway handles SSL termination, validates the JWT, and routes the request to the correct internal service."
  },
  {
    "id": 131,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Service Discovery",
    "question": "In a dynamic microservices environment (like Kubernetes), how does Service A know the IP address of Service B if Service B's IP changes every time it restarts?",
    "code_snippet": null,
    "options": ["Service A hardcodes the IP", "Service A queries a Service Registry (like Consul, Eureka, or Kubernetes DNS) to get the current, healthy IP addresses of Service B", "Service B emails Service A", "They use a static DNS record"],
    "correct_answer": "Service A queries a Service Registry (like Consul, Eureka, or Kubernetes DNS) to get the current, healthy IP addresses of Service B",
    "explanation": "Service Discovery is the phonebook of microservices. When Service B starts, it registers its IP. When it dies, it's deregistered. Service A asks the registry, 'Where is Service B?' and gets a live, accurate list of IPs to route traffic to."
  },
  {
    "id": 132,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Rate Limiting (Why)",
    "question": "What are the three primary reasons to implement Rate Limiting on an API?",
    "code_snippet": null,
    "options": ["To make the API slower", "1. Security (prevent DDoS/Brute Force), 2. Fair Usage (prevent one user from monopolizing resources), 3. Revenue (enforce paid tiers)", "To compress the JSON", "To encrypt the payload"],
    "correct_answer": "1. Security (prevent DDoS/Brute Force), 2. Fair Usage, 3. Revenue (enforce paid tiers)",
    "explanation": "Rate limiting protects your infrastructure from being overwhelmed by malicious bots or buggy clients, ensures fair access for all users, and allows you to sell 'Pro' tiers with higher API quotas."
  },
  {
    "id": 133,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Rate Limiting Algorithms",
    "question": "What is the key difference between the 'Token Bucket' and 'Leaky Bucket' rate limiting algorithms?",
    "code_snippet": null,
    "options": ["Token Bucket allows bursts of traffic up to the bucket size; Leaky Bucket enforces a strict, constant output rate", "Leaky Bucket allows bursts; Token Bucket is strict", "Token Bucket is for read requests; Leaky Bucket is for write requests", "There is no difference"],
    "correct_answer": "Token Bucket allows bursts of traffic up to the bucket size; Leaky Bucket enforces a strict, constant output rate",
    "explanation": "Token Bucket adds tokens over time; if the bucket is full, a user can consume 100 tokens instantly (a burst). Leaky Bucket drains requests at a fixed rate (e.g., exactly 5 per second), smoothing out bursts into a steady queue."
  },
  {
    "id": 134,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Circuit Breaker Pattern",
    "question": "What is the purpose of the 'Circuit Breaker' pattern in a microservices architecture?",
    "code_snippet": null,
    "options": ["To restart the server when it crashes", "To prevent a cascading failure by stopping requests to a downstream service that is currently failing or timing out, giving it time to recover", "To encrypt the network traffic", "To balance the load between databases"],
    "correct_answer": "To prevent a cascading failure by stopping requests to a downstream service that is currently failing or timing out",
    "explanation": "If the Payment Service is down, calling it 10,000 times a second will just cause your API Gateway to pile up thousands of hanging threads and crash. The Circuit Breaker 'trips' after a threshold of errors, immediately returning a fallback response without even trying to call the dead service."
  },
  {
    "id": 135,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Idempotency (Concept)",
    "question": "What does it mean for an API endpoint to be 'Idempotent'?",
    "code_snippet": null,
    "options": ["It runs faster", "Making the exact same request multiple times produces the exact same server state and result as making it once", "It requires a password", "It only works on GET requests"],
    "correct_answer": "Making the exact same request multiple times produces the exact same server state and result as making it once",
    "explanation": "GET, PUT, and DELETE are naturally idempotent. POST is NOT. If you click 'Pay $50' twice due to a network glitch, an idempotent API ensures you are only charged once."
  },
  {
    "id": 136,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Idempotency Keys",
    "question": "How do 'Idempotency Keys' prevent duplicate charges in a payment API?",
    "code_snippet": null,
    "options": ["By encrypting the credit card number", "The client sends a unique key (e.g., a UUID) in the header; the server stores the key and the result. If the same key is sent again, the server returns the cached result without re-executing the charge", "By requiring the user to enter a CAPTCHA", "By using HTTPS"],
    "correct_answer": "The client sends a unique key; the server stores the key and the result. If the same key is sent again, the server returns the cached result without re-executing the charge",
    "explanation": "Stripe and PayPal use this pattern. The client generates a UUID for the checkout attempt. If the network drops, the client retries with the SAME UUID. The server sees the UUID, realizes it already processed it, and just returns the original success receipt."
  },
  {
    "id": 137,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Health Checks",
    "question": "What is the difference between a 'Liveness' probe and a 'Readiness' probe in container orchestration (like Kubernetes)?",
    "code_snippet": null,
    "options": ["They are the same", "Liveness checks if the app is deadlocked/crashed (restarts it if so); Readiness checks if the app is ready to accept traffic (e.g., DB connected, cache warmed) and removes it from the Load Balancer if not", "Liveness is for databases; Readiness is for APIs", "Liveness checks CPU; Readiness checks RAM"],
    "correct_answer": "Liveness checks if the app is deadlocked (restarts it); Readiness checks if the app is ready to accept traffic and removes it from the Load Balancer if not",
    "explanation": "If your DB is down, your app is 'Live' (the process is running), but it is NOT 'Ready' to handle user requests. The Readiness probe tells the Load Balancer to stop sending traffic to this pod until the DB connection is restored."
  },
  {
    "id": 138,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Graceful Degradation",
    "question": "What is 'Graceful Degradation' in system design?",
    "code_snippet": null,
    "options": ["Shutting down the server slowly", "Designing the system so that if a non-critical component fails (like the Recommendation Engine), the core functionality (like Checkout) continues to work, perhaps with a fallback UI", "Reducing the image quality", "Slowing down the API intentionally"],
    "correct_answer": "Designing the system so that if a non-critical component fails, the core functionality continues to work, perhaps with a fallback UI",
    "explanation": "If YouTube's recommendation algorithm crashes, you should still be able to watch the video you searched for. The system degrades gracefully by hiding the 'Recommended for You' section rather than showing a 500 Error page."
  },
  {
    "id": 139,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Distributed Tracing",
    "question": "When a single user request passes through 10 different microservices, how do you debug a latency spike that occurred in one specific service?",
    "code_snippet": null,
    "options": ["Check the logs of all 10 servers manually", "Use Distributed Tracing (like OpenTelemetry/Jaeger) to assign a single 'Trace ID' to the request, allowing you to visualize the exact timeline and latency of every service hop", "Restart all servers", "Use a load balancer"],
    "correct_answer": "Use Distributed Tracing to assign a single 'Trace ID' to the request, allowing you to visualize the exact timeline and latency of every service hop",
    "explanation": "Distributed tracing injects a Trace ID into the HTTP headers. Every service logs its start/end time with that ID. Tools like Jaeger stitch these logs together into a waterfall chart, showing you exactly which service (or database query) caused the delay."
  },
  {
    "id": 140,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've now covered CAP, Load Balancing, Circuit Breakers, and Idempotency. What is the core mindset shift required to master System Design?",
    "code_snippet": null,
    "options": ["Memorizing every AWS service", "Accepting that in distributed systems, everything fails all the time; your job is not to prevent failure, but to design systems that anticipate, isolate, and recover from failure gracefully", "Writing code without errors", "Using only one server"],
    "correct_answer": "Accepting that in distributed systems, everything fails all the time; your job is not to prevent failure, but to design systems that anticipate, isolate, and recover from failure gracefully",
    "explanation": "Networks will partition. Servers will crash. Disks will fill up. A Senior Engineer doesn't write code assuming the network is perfect; they write code assuming the network is hostile, using patterns like retries, circuit breakers, and idempotency to survive the chaos."
  }
]
[
  {
    "id": 141,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Message Queues (Concept)",
    "question": "What is the primary architectural benefit of introducing a Message Queue (like RabbitMQ or SQS) between microservices?",
    "code_snippet": null,
    "options": ["It makes the database queries faster", "It decouples the services, allowing the producer to send a message and immediately return, while the consumer processes it asynchronously in the background", "It encrypts the data in transit", "It replaces the need for an API Gateway"],
    "correct_answer": "It decouples the services, allowing the producer to send a message and immediately return, while the consumer processes it asynchronously in the background",
    "explanation": "If Service A needs to generate a 5-minute PDF and email it, doing that synchronously will cause the HTTP request to time out. By dropping a 'GeneratePDF' message into a queue, Service A responds to the user in 50ms, and a background worker processes the heavy task later."
  },
  {
    "id": 142,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "RabbitMQ vs. Kafka",
    "question": "What is the fundamental architectural difference between RabbitMQ and Apache Kafka?",
    "code_snippet": null,
    "options": ["RabbitMQ is for SQL; Kafka is for NoSQL", "RabbitMQ is a 'smart broker, dumb consumer' (pushes messages, deletes them after ACK); Kafka is a 'dumb broker, smart consumer' (retains a log of messages, consumers pull at their own pace)", "Kafka is slower than RabbitMQ", "RabbitMQ does not support clustering"],
    "correct_answer": "RabbitMQ is a 'smart broker, dumb consumer' (pushes messages, deletes them after ACK); Kafka is a 'dumb broker, smart consumer' (retains a log of messages, consumers pull at their own pace)",
    "explanation": "RabbitMQ deletes a message once the consumer acknowledges it. Kafka acts like a distributed commit log; it retains messages on disk for days/weeks, allowing multiple different consumers to read the exact same stream of events independently at their own speed."
  },
  {
    "id": 143,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Kafka (Partitions)",
    "question": "How does Apache Kafka achieve massive throughput and parallel processing?",
    "code_snippet": null,
    "options": ["By using a single, massive CPU core", "By dividing a Topic into multiple Partitions, allowing multiple consumers in a group to read from different partitions simultaneously", "By compressing all messages into a single ZIP file", "By storing everything in RAM"],
    "correct_answer": "By dividing a Topic into multiple Partitions, allowing multiple consumers in a group to read from different partitions simultaneously",
    "explanation": "If a Topic has 10 partitions, you can have 10 consumer instances processing 10 different chunks of the data stream in parallel. This is how Kafka handles millions of messages per second."
  },
  {
    "id": 144,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Kafka (Consumer Groups)",
    "question": "If you have a Kafka topic with 5 partitions, and you deploy 10 instances of a consumer service in the same 'Consumer Group', what happens?",
    "code_snippet": null,
    "options": ["All 10 instances process every message, duplicating the work", "5 instances will actively consume from the 5 partitions, and the remaining 5 instances will sit completely idle", "Kafka will automatically create 5 more partitions", "The system will crash"],
    "correct_answer": "5 instances will actively consume from the 5 partitions, and the remaining 5 instances will sit completely idle",
    "explanation": "In Kafka, a partition can only be read by ONE consumer within a consumer group. If you have more consumers than partitions, the extra consumers are useless. To scale, you must increase the number of partitions, not just the consumers."
  },
  {
    "id": 145,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Pub/Sub Pattern",
    "question": "What is the core characteristic of the Publish/Subscribe (Pub/Sub) messaging pattern?",
    "code_snippet": null,
    "options": ["Messages are sent directly to a specific receiver's IP address", "The publisher and subscribers are completely decoupled; the publisher sends a message to a 'Topic', and any number of interested subscribers can listen to that Topic", "It only supports one-to-one communication", "It requires a direct TCP connection between sender and receiver"],
    "correct_answer": "The publisher and subscribers are completely decoupled; the publisher sends a message to a 'Topic', and any number of interested subscribers can listen to that Topic",
    "explanation": "Pub/Sub allows for massive fan-out. When a 'UserRegistered' event is published, the Email Service, the Analytics Service, and the Welcome Bonus Service can all subscribe to that topic and react independently without knowing about each other."
  },
  {
    "id": 146,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "WebSockets vs. Long Polling",
    "question": "What is the primary advantage of WebSockets over Long Polling for real-time applications?",
    "code_snippet": null,
    "options": ["WebSockets use less memory on the server", "WebSockets establish a single, persistent, full-duplex TCP connection, eliminating the massive HTTP overhead and latency of constantly opening/closing connections in Long Polling", "WebSockets are supported by older browsers", "Long Polling is faster"],
    "correct_answer": "WebSockets establish a single, persistent, full-duplex TCP connection, eliminating the massive HTTP overhead and latency of constantly opening/closing connections in Long Polling",
    "explanation": "Long Polling tricks the browser into making an HTTP request that the server holds open until data is available. WebSockets upgrade the HTTP connection to a raw TCP socket where both client and server can push data to each other instantly at any time."
  },
  {
    "id": 147,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Server-Sent Events (SSE)",
    "question": "When should you choose Server-Sent Events (SSE) over WebSockets?",
    "code_snippet": null,
    "options": ["When the client needs to send frequent data to the server", "When you only need a one-way, server-to-client stream of data (like live stock ticks or AI text generation), as SSE is simpler, HTTP-based, and handles auto-reconnection natively", "When you need to transfer binary files", "SSE is deprecated"],
    "correct_answer": "When you only need a one-way, server-to-client stream of data, as SSE is simpler, HTTP-based, and handles auto-reconnection natively",
    "explanation": "WebSockets are complex and require a dedicated protocol. If your app only needs the server to push updates to the client (like a live dashboard), SSE uses standard HTTP, works beautifully through corporate proxies, and automatically reconnects if the network drops."
  },
  {
    "id": 148,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "CQRS (Concept)",
    "question": "What does CQRS stand for, and what problem does it solve?",
    "code_snippet": null,
    "options": ["Central Query Routing System; it routes traffic", "Command Query Responsibility Segregation; it separates the read (Query) and write (Command) models of an application, allowing them to be scaled and optimized independently", "Cached Query Response System; it speeds up SQL", "Concurrent Query Resolution Standard; it prevents deadlocks"],
    "correct_answer": "Command Query Responsibility Segregation; it separates the read and write models of an application, allowing them to be scaled and optimized independently",
    "explanation": "In many apps, read traffic is 100x higher than write traffic. CQRS allows you to use a highly normalized PostgreSQL database for writes, and asynchronously replicate that data to a denormalized, read-optimized database (like Elasticsearch or Cassandra) for reads."
  },
  {
    "id": 149,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "CQRS (Eventual Consistency)",
    "question": "What is the major trade-off when implementing CQRS?",
    "code_snippet": null,
    "options": ["It makes writes faster", "The read database is updated asynchronously, meaning there is a delay (Eventual Consistency) where a user might read stale data immediately after writing it", "It requires a NoSQL database", "It disables transactions"],
    "correct_answer": "The read database is updated asynchronously, meaning there is a delay (Eventual Consistency) where a user might read stale data immediately after writing it",
    "explanation": "If a user updates their profile picture (Write DB), and immediately refreshes their dashboard (Read DB), the dashboard might still show the old picture because the async replication hasn't finished yet. The UI must handle this 'eventual consistency' gracefully."
  },
  {
    "id": 150,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Event Sourcing (Concept)",
    "question": "What is 'Event Sourcing' in database architecture?",
    "code_snippet": null,
    "options": ["Using only NoSQL databases", "Instead of storing the current state of an entity (e.g., `balance = 100`), you store every state-changing event as an immutable log (e.g., `+50`, `+20`, `-10`, `+40`)", "Encrypting all database rows", "Sourcing data from third-party APIs"],
    "correct_answer": "Instead of storing the current state, you store every state-changing event as an immutable log",
    "explanation": "Event Sourcing treats your database like a bank ledger. You never just overwrite 'Balance = 100'. You append 'Deposited $50', 'Deposited $20', 'Withdrew $10'. This gives you a perfect audit trail and the ability to 'time travel' to reconstruct the state at any point in history."
  },
  {
    "id": 151,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Event Sourcing vs. CQRS",
    "question": "How do Event Sourcing and CQRS relate to each other?",
    "code_snippet": null,
    "options": ["They are the exact same thing", "They are distinct patterns but often used together; Event Sourcing is how you STORE the data (as events), while CQRS is how you READ/WRITE the data (segregating models)", "You cannot use one without the other", "CQRS is the newer version of Event Sourcing"],
    "correct_answer": "They are distinct patterns but often used together; Event Sourcing is how you STORE the data, while CQRS is how you READ/WRITE the data",
    "explanation": "You can use CQRS without Event Sourcing (just using standard SQL tables but separating read/write logic). You can use Event Sourcing without CQRS (replaying events to get the current state for both reads and writes). But together, they create incredibly powerful, scalable systems."
  },
  {
    "id": 152,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Data Replication (Sync vs. Async)",
    "question": "What is the trade-off between Synchronous and Asynchronous database replication?",
    "code_snippet": null,
    "options": ["Sync is faster; Async is slower", "Sync guarantees zero data loss but adds latency to every write (waiting for the replica to confirm); Async is blazing fast but risks losing the last few milliseconds of data if the primary crashes", "Sync is for reads; Async is for writes", "There is no trade-off"],
    "correct_answer": "Sync guarantees zero data loss but adds latency; Async is blazing fast but risks losing recent data if the primary crashes",
    "explanation": "In Sync replication, a write isn't considered 'successful' until both the Primary and the Follower acknowledge it. This is safe but slow. In Async replication, the Primary acknowledges immediately and copies to the Follower in the background. If the Primary dies right then, that data is lost forever."
  },
  {
    "id": 153,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Database Sharding (Shard Key)",
    "question": "What is the most critical factor when choosing a 'Shard Key' for a distributed database?",
    "code_snippet": null,
    "options": ["It should be a text string", "It must have high cardinality (many unique values) and distribute writes evenly across all shards to prevent 'hot spots'", "It should be the same as the primary key", "It must be encrypted"],
    "correct_answer": "It must have high cardinality and distribute writes evenly across all shards to prevent 'hot spots'",
    "explanation": "If you shard by 'Country', and 90% of your users are in the US, 90% of your write traffic will hit a single shard (the US shard), completely bottlenecking your system while the other shards sit idle. A good shard key (like `user_id`) ensures even distribution."
  },
  {
    "id": 154,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Consistent Hashing (Virtual Nodes)",
    "question": "What problem do 'Virtual Nodes' (vnodes) solve in Consistent Hashing?",
    "code_snippet": null,
    "options": ["They encrypt the hash ring", "They solve data skew by mapping a single physical server to multiple points on the hash ring, ensuring an even distribution of data even if physical servers have different capacities", "They speed up the hashing algorithm", "They compress the data"],
    "correct_answer": "They solve data skew by mapping a single physical server to multiple points on the hash ring, ensuring an even distribution of data",
    "explanation": "If you only have 3 physical servers on a hash ring, the space between them might be uneven, causing one server to hold 80% of the data. By giving each server 100 'virtual' identities scattered randomly around the ring, the data distribution becomes mathematically uniform."
  },
  {
    "id": 155,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Saga Pattern (Choreography)",
    "question": "In a microservices architecture, how does the 'Choreography' approach to the Saga pattern manage distributed transactions?",
    "code_snippet": null,
    "options": ["A central database locks all tables", "Each service listens for events and performs its local transaction; if it fails, it publishes a new event to trigger a 'compensating' undo action in the previous services", "A central coordinator tells every service exactly what to do step-by-step", "It uses Two-Phase Commit (2PC)"],
    "correct_answer": "Each service listens for events and performs its local transaction; if it fails, it publishes a new event to trigger a 'compensating' undo action",
    "explanation": "Choreography is decentralized. Service A finishes and emits 'OrderCreated'. Service B hears it, charges the card, and emits 'PaymentProcessed'. If Service C fails to ship the item, it emits 'ShippingFailed', which Service B hears to trigger a 'RefundIssued' compensating event."
  },
  {
    "id": 156,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Saga Pattern (Orchestration)",
    "question": "How does the 'Orchestration' approach to the Saga pattern differ from Choreography?",
    "code_snippet": null,
    "options": ["It uses a central 'Orchestrator' service that explicitly commands each participant service what to do and handles the rollback logic centrally", "It is faster than Choreography", "It requires a shared database", "It does not support rollbacks"],
    "correct_answer": "It uses a central 'Orchestrator' service that explicitly commands each participant service what to do and handles the rollback logic centrally",
    "explanation": "Instead of services talking to each other via events, an Orchestrator (like a State Machine) says: 'Order Service, create order. Payment Service, charge card. Inventory Service, reserve item.' If step 3 fails, the Orchestrator explicitly tells step 2 to refund. It's much easier to debug than Choreography."
  },
  {
    "id": 157,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Compensating Transactions",
    "question": "What is a 'Compensating Transaction' in the context of distributed systems?",
    "code_snippet": null,
    "options": ["A transaction that runs twice as fast", "An operation that logically undoes the work of a previous transaction to maintain eventual consistency, since true distributed rollbacks are impossible", "A backup of the database", "A transaction that encrypts the data"],
    "correct_answer": "An operation that logically undoes the work of a previous transaction to maintain eventual consistency",
    "explanation": "You cannot physically 'rollback' a credit card charge or an email sent by another microservice. Instead, you execute a compensating action: you issue a 'Refund' or send a 'Cancellation Email'. It doesn't erase history; it adds a new event that balances the ledger."
  },
  {
    "id": 158,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Two-Phase Commit (2PC)",
    "question": "Why is the Two-Phase Commit (2PC) protocol generally avoided in modern microservices architectures?",
    "code_snippet": null,
    "options": ["It is too fast", "It is a blocking, synchronous protocol that locks resources across multiple databases, creating a massive bottleneck and a single point of failure (the coordinator)", "It doesn't support SQL", "It is only for NoSQL"],
    "correct_answer": "It is a blocking, synchronous protocol that locks resources across multiple databases, creating a massive bottleneck and a single point of failure",
    "explanation": "In 2PC, the coordinator asks all databases if they are ready to commit. If they say yes, it tells them to commit. If the coordinator crashes after saying 'prepare' but before saying 'commit', all databases are left in a locked, limbo state forever. Sagas are preferred because they are non-blocking."
  },
  {
    "id": 159,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Message Delivery Semantics",
    "question": "Why must a message queue consumer be strictly idempotent if the queue guarantees 'At-Least-Once' delivery?",
    "code_snippet": null,
    "options": ["Because the queue might deliver the exact same message multiple times (e.g., if the network drops right after processing but before the ACK is sent)", "Because the queue compresses messages", "Because the consumer runs on multiple threads", "Because the queue encrypts the payload"],
    "correct_answer": "Because the queue might deliver the exact same message multiple times if the network drops right after processing but before the ACK is sent",
    "explanation": "To guarantee a message isn't lost, queues use 'At-Least-Once'. If the consumer processes the message, but crashes before sending the 'ACK' back to the broker, the broker assumes it failed and redelivers it. The consumer must use idempotency keys to recognize the duplicate and ignore it."
  },
  {
    "id": 160,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've now mastered Message Queues, CQRS, Event Sourcing, and Sagas. What is the ultimate philosophy of Event-Driven System Design?",
    "code_snippet": null,
    "options": ["To make every API call synchronous", "To treat 'state' not as a current snapshot, but as a flowing river of immutable events, allowing systems to scale infinitely, react asynchronously, and never lose a single piece of historical context", "To avoid using databases", "To use only one server"],
    "correct_answer": "To treat 'state' as a flowing river of immutable events, allowing systems to scale infinitely, react asynchronously, and never lose historical context",
    "explanation": "When you shift from 'Request/Response' to 'Event-Driven', you stop building rigid, tightly-coupled monoliths. You build living ecosystems where services simply react to what has happened, enabling massive scale, resilience, and perfect auditability."
  }
]
[
  {
    "id": 161,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "REST vs GraphQL vs gRPC",
    "question": "What is the fundamental difference in payload and transport between REST, GraphQL, and gRPC?",
    "code_snippet": null,
    "options": ["REST uses XML; GraphQL uses Binary; gRPC uses JSON", "REST uses JSON over HTTP/1.1; GraphQL uses JSON over HTTP/1.1 but allows client-driven queries; gRPC uses Protocol Buffers (binary) over HTTP/2", "GraphQL is only for databases; gRPC is only for UI", "There is no difference, they are just marketing terms"],
    "correct_answer": "REST uses JSON over HTTP/1.1; GraphQL uses JSON over HTTP/1.1 but allows client-driven queries; gRPC uses Protocol Buffers (binary) over HTTP/2",
    "explanation": "REST is simple and ubiquitous but suffers from over/under-fetching. GraphQL solves the fetching problem but requires complex server-side resolvers. gRPC is blazing fast, strictly typed, and supports streaming, making it the undisputed king of internal microservice-to-microservice communication."
  },
  {
    "id": 162,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "gRPC (Protocol Buffers)",
    "question": "Why is gRPC significantly faster and more bandwidth-efficient than REST/JSON?",
    "code_snippet": null,
    "options": ["It uses a faster programming language", "It serializes data into Protocol Buffers (a compact binary format) rather than verbose text-based JSON, and multiplexes streams over a single HTTP/2 connection", "It bypasses the network layer", "It compresses JSON using ZIP"],
    "correct_answer": "It serializes data into Protocol Buffers (a compact binary format) rather than verbose text-based JSON, and multiplexes streams over a single HTTP/2 connection",
    "explanation": "JSON requires parsing text and inferring types. Protocol Buffers are pre-compiled into strict binary schemas. The payload is a fraction of the size, and HTTP/2 allows multiple concurrent requests (multiplexing) over one TCP connection, eliminating Head-of-Line blocking."
  },
  {
    "id": 163,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "GraphQL (The N+1 Problem)",
    "question": "Why is the 'N+1 Query Problem' particularly dangerous in GraphQL, and what is the standard solution?",
    "code_snippet": null,
    "options": ["GraphQL doesn't have this problem", "Because GraphQL resolvers execute per-field, fetching a list of 100 users and their posts can trigger 101 separate DB queries; the solution is using a batching/caching utility like DataLoader", "The solution is to disable caching", "The solution is to use REST instead"],
    "correct_answer": "Because GraphQL resolvers execute per-field, fetching a list of 100 users and their posts can trigger 101 separate DB queries; the solution is using a batching utility like DataLoader",
    "explanation": "In REST, you write one SQL JOIN. In GraphQL, the `posts` resolver runs for *every single user* in the list. DataLoader intercepts these individual calls, batches them into a single `WHERE user_id IN (...)` query, and maps the results back, saving the database from collapsing."
  },
  {
    "id": 164,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "API Versioning Strategies",
    "question": "What is the most common and easily cacheable method for versioning a public REST API?",
    "code_snippet": null,
    "options": ["Changing the database schema", "URI Versioning (e.g., `/v1/users` vs `/v2/users`)", "Changing the HTTP Method", "Using a query parameter like `?version=2`"],
    "correct_answer": "URI Versioning (e.g., `/v1/users` vs `/v2/users`)",
    "explanation": "While purists argue for Header versioning (`Accept: application/vnd.myapi.v2+json`), URI versioning is the industry standard because it is highly visible, easy to route at the API Gateway, and plays perfectly with CDN and browser caching mechanisms."
  },
  {
    "id": 165,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Webhooks (Security & HMAC)",
    "question": "Since Webhooks are just public HTTP POST endpoints, how does your server verify that a webhook payload actually came from the legitimate provider (like Stripe) and not a malicious attacker?",
    "code_snippet": null,
    "options": ["By checking the sender's IP address", "By verifying an HMAC-SHA256 cryptographic signature included in the webhook header, using a shared secret key", "By requiring a CAPTCHA", "Webhooks cannot be secured"],
    "correct_answer": "By verifying an HMAC-SHA256 cryptographic signature included in the webhook header, using a shared secret key",
    "explanation": "The provider hashes the raw JSON payload using your shared secret and sends it in the `X-Signature` header. Your server hashes the received payload with the same secret. If the hashes match, the payload is authentic and hasn't been tampered with in transit."
  },
  {
    "id": 166,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Webhooks (Retry & Idempotency)",
    "question": "If your server returns a 500 Error while processing a webhook, the provider will retry the delivery. What must your webhook handler do to prevent processing the same event twice?",
    "code_snippet": null,
    "options": ["Delete the webhook from the provider's queue", "Use the unique Event ID from the payload to check a database/Redis table; if it already exists, acknowledge it immediately without re-executing the business logic", "Return a 200 OK immediately before processing", "Ignore all retries"],
    "correct_answer": "Use the unique Event ID from the payload to check a database/Redis table; if it already exists, acknowledge it immediately without re-executing the business logic",
    "explanation": "Webhooks are inherently 'At-Least-Once' delivery. Your handler must be strictly idempotent. By storing the `event_id` in a table with a UNIQUE constraint, you guarantee that even if the provider sends the exact same payload 5 times, your business logic only runs once."
  },
  {
    "id": 167,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "OAuth 2.0 (Authorization Code Flow)",
    "question": "In the OAuth 2.0 Authorization Code flow, why does the client exchange the temporary 'Authorization Code' for an Access Token via a backend channel, instead of just having the Identity Provider send the Access Token directly to the browser's URL?",
    "code_snippet": null,
    "options": ["It makes the UI load faster", "To prevent the Access Token (and Client Secret) from being exposed in the browser's history, URL bar, or to malicious browser extensions", "Because URLs have a character limit", "It is required by HTTP/2"],
    "correct_answer": "To prevent the Access Token from being exposed in the browser's history, URL bar, or to malicious browser extensions",
    "explanation": "The Authorization Code flow is designed for confidential clients (servers). The code is useless without the Client Secret, which is safely stored on the backend. The backend exchanges the code + secret for the token, ensuring the long-lived token never touches the user's browser."
  },
  {
    "id": 168,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "OAuth 2.0 (PKCE)",
    "question": "What is the purpose of PKCE (Proof Key for Code Exchange) in OAuth 2.0?",
    "code_snippet": null,
    "options": ["It encrypts the database", "It secures the Authorization Code flow for public clients (SPAs, Mobile Apps) that cannot safely store a Client Secret, preventing authorization code interception attacks", "It speeds up the login process", "It replaces JWTs"],
    "correct_answer": "It secures the Authorization Code flow for public clients that cannot safely store a Client Secret, preventing authorization code interception attacks",
    "explanation": "PKCE generates a random `code_verifier` on the client, hashes it into a `code_challenge`, and sends it with the initial auth request. When exchanging the code for a token, the client sends the original `code_verifier`. The server hashes it and compares it to the challenge, proving the client is the same one that initiated the flow."
  },
  {
    "id": 169,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "OpenID Connect (OIDC)",
    "question": "What is the fundamental difference between OAuth 2.0 and OpenID Connect (OIDC)?",
    "code_snippet": null,
    "options": ["They are exactly the same", "OAuth 2.0 is for Authorization (delegated access); OIDC is an identity layer ON TOP of OAuth 2.0 that provides Authentication (who the user is) via an ID Token (JWT)", "OIDC is for databases; OAuth is for UI", "OAuth 2.0 is deprecated"],
    "correct_answer": "OAuth 2.0 is for Authorization; OIDC is an identity layer ON TOP of OAuth 2.0 that provides Authentication via an ID Token",
    "explanation": "OAuth 2.0 gives you a token to access an API (e.g., 'Let this app read my Google Calendar'). OIDC adds an ID Token (a JWT containing user profile info) so the app also knows *who* the user is (e.g., 'Log the user into my app using their Google identity')."
  },
  {
    "id": 170,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "JWT (JSON Web Tokens)",
    "question": "What are the three distinct parts of a JWT, separated by dots?",
    "code_snippet": null,
    "options": ["Username, Password, Token", "Header (algorithm/type), Payload (claims/data), Signature (cryptographic verification)", "ID, Secret, Expiry", "Public Key, Private Key, Hash"],
    "correct_answer": "Header (algorithm/type), Payload (claims/data), Signature (cryptographic verification)",
    "explanation": "The Header tells the server how the token is signed (e.g., HS256). The Payload contains the claims (e.g., `sub: user123`, `role: admin`). The Signature proves that the payload hasn't been tampered with since it was issued by the trusted server."
  },
  {
    "id": 171,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "JWT (The Revocation Problem)",
    "question": "What is the major architectural drawback of using stateless JWTs for authentication, and how is it typically solved?",
    "code_snippet": null,
    "options": ["They are too large to send over the network", "Because they are stateless, you cannot invalidate them before their expiration date (e.g., if a user is banned); solved by using very short-lived Access Tokens paired with longer-lived, revocable Refresh Tokens", "They cannot be encrypted", "They require a database on every request"],
    "correct_answer": "Because they are stateless, you cannot invalidate them before their expiration date; solved by using short-lived Access Tokens paired with revocable Refresh Tokens",
    "explanation": "If a JWT is valid for 24 hours, and the user's account is compromised at hour 1, the attacker can use the JWT for 23 more hours. The standard fix is to issue Access Tokens that expire in 15 minutes, and use a server-stored Refresh Token (which can be deleted from a DB) to get new Access Tokens."
  },
  {
    "id": 172,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "CDN (Content Delivery Network)",
    "question": "How does a CDN reduce latency for global users?",
    "code_snippet": null,
    "options": ["By using faster database queries", "By caching static and dynamic content at Edge Points of Presence (PoPs) geographically closer to the user, eliminating the round-trip to the origin server", "By compressing the database", "By load balancing the origin servers"],
    "correct_answer": "By caching content at Edge Points of Presence (PoPs) geographically closer to the user, eliminating the round-trip to the origin server",
    "explanation": "If your origin server is in Virginia, a user in Tokyo experiences 200ms of latency. A CDN caches your images, CSS, and even API responses on a server in Tokyo, serving the user in 5ms."
  },
  {
    "id": 173,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "CDN (Cache-Control Headers)",
    "question": "What does the `stale-while-revalidate` directive in a `Cache-Control` header instruct the CDN to do?",
    "code_snippet": null,
    "options": ["Delete the cache immediately", "Serve the expired (stale) cache to the user instantly for a fast response, while simultaneously fetching the fresh data from the origin in the background to update the cache for the NEXT user", "Never cache the data", "Encrypt the cache"],
    "correct_answer": "Serve the expired (stale) cache to the user instantly, while simultaneously fetching the fresh data from the origin in the background",
    "explanation": "This is the ultimate performance trick. Instead of making User A wait 2 seconds for the origin to generate fresh data after the cache expires, User A gets the 1-day-old stale data in 5ms. The CDN refreshes the cache in the background, so User B (1 second later) gets the fresh data."
  },
  {
    "id": 174,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Edge Computing",
    "question": "What is the core concept of 'Edge Computing' (e.g., Cloudflare Workers, Vercel Edge Functions)?",
    "code_snippet": null,
    "options": ["Running heavy AI models on the user's phone", "Moving backend application logic (like authentication, A/B testing, or API routing) out of the centralized origin server and executing it directly on the CDN's global Edge network", "Using blockchain for databases", "Running Node.js on IoT devices only"],
    "correct_answer": "Moving backend logic out of the centralized origin server and executing it directly on the CDN's global Edge network",
    "explanation": "Instead of a request traveling from Tokyo to Virginia to execute a simple JWT check, the Edge Function intercepts the request in Tokyo, validates the JWT, and routes it, saving hundreds of milliseconds of global transit time."
  },
  {
    "id": 175,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Distributed Consensus (Quorum)",
    "question": "In a distributed database with `N` total nodes, what is the mathematical formula required to guarantee strong consistency (meaning every read returns the most recent write)?",
    "code_snippet": null,
    "options": ["R + W < N", "R + W > N (where R is read quorum, W is write quorum)", "R * W = N", "R = W = N"],
    "correct_answer": "R + W > N (where R is read quorum, W is write quorum)",
    "explanation": "If you have 5 nodes (N=5), and you write to 3 (W=3) and read from 3 (R=3), R+W = 6. Because 6 > 5, the read and write sets MUST overlap by at least one node. This guarantees the reader will always see the latest write, ensuring strong consistency."
  },
  {
    "id": 176,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Distributed Locks (Fencing Tokens)",
    "question": "Why are simple time-based distributed locks (like Redis `SETNX` with a 10s TTL) considered unsafe, and how do 'Fencing Tokens' fix this?",
    "code_snippet": null,
    "options": ["Redis is too slow", "If a client gets a lock, pauses (e.g., Garbage Collection), and the lock expires, a second client can get the lock. Fencing tokens (monotonically increasing IDs) allow the storage server to reject stale writes from the paused client", "Redis cannot handle locks", "Fencing tokens encrypt the lock"],
    "correct_answer": "If a client pauses and the lock expires, a second client can get it. Fencing tokens (monotonically increasing IDs) allow the storage server to reject stale writes from the paused client",
    "explanation": "Client A gets lock #33. Network/GC pauses. Lock expires. Client B gets lock #34 and writes data. Client A wakes up and overwrites the data. If the DB requires the lock token to strictly increase, it rejects Client A's write (33 < 34), preventing data corruption."
  },
  {
    "id": 177,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Bloom Filters",
    "question": "What is a 'Bloom Filter', and why is it used in distributed databases (like Cassandra or HBase)?",
    "code_snippet": null,
    "options": ["A tool to encrypt data", "A highly space-efficient probabilistic data structure that answers 'Does this key exist?'; it can yield false positives, but NEVER false negatives, saving massive amounts of disk I/O", "A type of database index", "A network protocol"],
    "correct_answer": "A space-efficient probabilistic data structure that answers 'Does this key exist?'; it can yield false positives, but NEVER false negatives",
    "explanation": "Before checking the slow disk to see if a user exists, the DB checks the in-memory Bloom Filter. If it says 'No', the DB instantly returns 'Not Found' without touching the disk. If it says 'Yes', it might be a false positive, so the DB checks the disk anyway."
  },
  {
    "id": 178,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Logical Clocks (Lamport)",
    "question": "In a distributed system where servers do not have perfectly synchronized physical clocks (NTP), how do you determine the causal order of events (e.g., did Message A happen before Message B)?",
    "code_snippet": null,
    "options": ["Use the server's local timestamp", "Use Logical Clocks (like Lamport timestamps or Vector Clocks), which increment a counter on every local event and pass it along with messages to establish a partial ordering", "You cannot determine order", "Use a blockchain"],
    "correct_answer": "Use Logical Clocks, which increment a counter on every local event and pass it along with messages to establish a partial ordering",
    "explanation": "Physical clocks drift. Lamport clocks use a simple rule: 'I increment my counter before every event, and when I send a message, I include my counter. When I receive a message, I set my counter to max(my_counter, their_counter) + 1.' This establishes a mathematical 'happened-before' relationship."
  },
  {
    "id": 179,
    "level": "intermediate",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "System Design (Rate Limiting at the Edge)",
    "question": "Why is it architecturally superior to implement Rate Limiting at the API Gateway or Edge layer, rather than inside the application logic?",
    "code_snippet": null,
    "options": ["It makes the database faster", "It drops malicious or excessive traffic before it consumes expensive application server CPU, memory, and database connections", "It is required by OAuth2", "It compresses the payload"],
    "correct_answer": "It drops malicious or excessive traffic before it consumes expensive application server CPU, memory, and database connections",
    "explanation": "If a bot sends 100,000 requests per second, and your rate limiter is inside the Node.js app, your Node.js server still has to parse 100,000 HTTP requests just to reject them. Doing it at the Edge (Cloudflare/AWS WAF) drops them at the network perimeter for free."
  },
  {
    "id": 180,
    "level": "advanced",
    "module_id": "node_mod_03_system_design",
    "module_name": "System Design & Distributed Systems",
    "type": "conceptual",
    "topic": "Part 3 Wrap-up",
    "question": "You've now mastered API protocols, OAuth2, Edge Computing, and Distributed Consensus. What is the ultimate hallmark of a Principal System Architect?",
    "code_snippet": null,
    "options": ["Choosing the newest, most complex technology for every problem", "Understanding that there is no 'perfect' architecture, only trade-offs; and knowing exactly when to sacrifice consistency for availability, or simplicity for scalability, based on the specific business requirements", "Writing all code in Assembly", "Avoiding the use of networks"],
    "correct_answer": "Understanding that there is no 'perfect' architecture, only trade-offs; and knowing exactly when to sacrifice consistency for availability, or simplicity for scalability, based on the specific business requirements",
    "explanation": "A Principal Engineer knows that Microservices aren't always better than Monoliths. Event Sourcing isn't always better than CRUD. True mastery is the ability to look at a business problem, map it to the CAP theorem, and design a system that survives the inevitable chaos of the real world."
  }
]
