[
  {
    "id": 1,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Node.js Architecture",
    "question": "Node.js is often described as a combination of two distinct components. What are they?",
    "code_snippet": null,
    "options": ["React and Webpack", "The V8 JavaScript Engine (for executing code) and Libuv (for the Event Loop and async I/O)", "Express and Prisma", "TypeScript and Babel"],
    "correct_answer": "The V8 JavaScript Engine (for executing code) and Libuv (for the Event Loop and async I/O)",
    "explanation": "V8 (written by Google) compiles and executes JavaScript. Libuv (written for Node.js) provides the event loop, thread pool, and asynchronous I/O capabilities, allowing Node to handle thousands of concurrent connections without blocking."
  },
  {
    "id": 2,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "The Event Loop Phases",
    "question": "What is the correct order of the main phases in the Node.js Event Loop?",
    "code_snippet": null,
    "options": ["Timers -> Poll -> Check -> Close", "Timers -> Pending I/O -> Poll -> Check -> Close Callbacks", "Init -> Execute -> Cleanup", "Microtasks -> Macrotasks -> Render"],
    "correct_answer": "Timers -> Pending I/O -> Poll -> Check -> Close Callbacks",
    "explanation": "The Event Loop is not just one loop; it's a cycle through specific phases. Timers (setTimeout), Pending I/O, Poll (incoming data/connections), Check (setImmediate), and Close Callbacks. Understanding this order is critical for debugging async timing issues."
  },
  {
    "id": 3,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "output-prediction",
    "topic": "Microtasks vs Macrotasks",
    "question": "What will be the exact output order of this code?\n```javascript\nconsole.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nprocess.nextTick(() => console.log('4'));\nconsole.log('5');\n```",
    "code_snippet": "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nprocess.nextTick(() => console.log('4'));\nconsole.log('5');",
    "options": ["1, 5, 2, 3, 4", "1, 5, 4, 3, 2", "1, 5, 3, 4, 2", "1, 2, 3, 4, 5"],
    "correct_answer": "1, 5, 4, 3, 2",
    "explanation": "Synchronous code runs first (1, 5). Then the Microtask queue empties completely. `process.nextTick` has the highest priority (4), followed by Promises (3). Finally, the Event Loop moves to the Timers phase for the macrotask `setTimeout` (2)."
  },
  {
    "id": 4,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "process.nextTick vs setImmediate",
    "question": "Despite their confusing names, what is the actual difference between `process.nextTick()` and `setImmediate()`?",
    "code_snippet": null,
    "options": ["They are aliases for the same function", "`nextTick` fires before the Event Loop continues to the next phase; `setImmediate` fires in the 'Check' phase of the Event Loop", "`setImmediate` is faster", "`nextTick` is for Promises, `setImmediate` is for timers"],
    "correct_answer": "`nextTick` fires before the Event Loop continues to the next phase; `setImmediate` fires in the 'Check' phase of the Event Loop",
    "explanation": "`process.nextTick` is technically not part of the Event Loop; it interrupts it. It fires immediately after the current operation completes, before the loop continues. `setImmediate` is queued for the 'Check' phase, making it actually 'slower' but safer for preventing stack overflows."
  },
  {
    "id": 5,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Single-Threaded Myth",
    "question": "People often say 'Node.js is single-threaded.' What is the technically accurate statement?",
    "code_snippet": null,
    "options": ["Node.js uses exactly one CPU core for everything", "The JavaScript execution (V8) runs on a single main thread, but Libuv maintains a thread pool (usually 4 threads) to handle heavy async I/O operations like File System and DNS lookups", "Node.js cannot handle concurrent requests", "Node.js requires a multi-core server to run"],
    "correct_answer": "The JavaScript execution (V8) runs on a single main thread, but Libuv maintains a thread pool (usually 4 threads) to handle heavy async I/O operations like File System and DNS lookups",
    "explanation": "Your JS code is single-threaded, which prevents race conditions in your logic. But when you call `fs.readFile`, Libuv hands that off to a background C++ thread pool so the main JS thread isn't blocked while waiting for the disk."
  },
  {
    "id": 6,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Buffers",
    "question": "What is a `Buffer` in Node.js, and why was it introduced?",
    "code_snippet": null,
    "options": ["A cache for database queries", "A temporary memory allocation outside the V8 heap used to handle raw binary data (like files or network packets) efficiently", "A way to store large strings", "A tool to compress images"],
    "correct_answer": "A temporary memory allocation outside the V8 heap used to handle raw binary data (like files or network packets) efficiently",
    "explanation": "JavaScript originally didn't have a mechanism for reading/manipulating raw bytes. Buffers were introduced in Node.js to interact with binary streams, allowing developers to handle file I/O and network data without crashing the V8 memory heap."
  },
  {
    "id": 7,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Streams (Types)",
    "question": "What are the four fundamental types of Streams in Node.js?",
    "code_snippet": null,
    "options": ["Input, Output, Error, Standard", "Readable, Writable, Duplex, and Transform", "Sync, Async, Blocking, Non-blocking", "Text, Binary, JSON, XML"],
    "correct_answer": "Readable, Writable, Duplex, and Transform",
    "explanation": "Readable (can consume data, like `fs.createReadStream`), Writable (can write data, like `fs.createWriteStream`), Duplex (both, like a TCP socket), and Transform (a Duplex stream that modifies the data as it passes through, like `zlib` for compression)."
  },
  {
    "id": 8,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Streams (Backpressure)",
    "question": "What is 'Backpressure' in the context of Node.js Streams, and why is it critical?",
    "code_snippet": null,
    "options": ["When the server runs out of CPU", "The mechanism that prevents a fast Readable stream from overwhelming a slow Writable stream, preventing memory leaks and crashes", "When the database locks a table", "When a Promise rejects"],
    "correct_answer": "The mechanism that prevents a fast Readable stream from overwhelming a slow Writable stream, preventing memory leaks and crashes",
    "explanation": "If you read a 10GB file and try to write it to a slow network connection, the data will pile up in RAM and crash the server. Backpressure (handled via the `drain` event and `.pipe()`) tells the reader to pause until the writer catches up."
  },
  {
    "id": 9,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "code-fill-in-blank",
    "topic": "Streams (Piping)",
    "question": "Fill in the blank to correctly pipe a readable file stream into a writable file stream, automatically handling backpressure.",
    "code_snippet": "const fs = require('fs');\nconst readStream = fs.createReadStream('input.txt');\nconst writeStream = fs.createWriteStream('output.txt');\n\nreadStream._______(writeStream);",
    "options": ["pipe", "flow", "stream", "connect"],
    "correct_answer": "pipe",
    "explanation": "The `.pipe()` method is the most elegant way to handle streams. It automatically listens for data, writes it to the destination, and pauses/resumes the readable stream based on backpressure, preventing memory leaks."
  },
  {
    "id": 10,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Worker Threads vs Cluster",
    "question": "What is the fundamental difference between the `worker_threads` module and the `cluster` module?",
    "code_snippet": null,
    "options": ["They are the same thing", "`worker_threads` shares memory within a single Node.js process for CPU-heavy tasks; `cluster` forks the entire Node.js process across multiple CPU cores to handle more HTTP connections", "`cluster` is for databases, `worker_threads` is for UI", "`worker_threads` is deprecated"],
    "correct_answer": "`worker_threads` shares memory within a single Node.js process for CPU-heavy tasks; `cluster` forks the entire Node.js process across multiple CPU cores to handle more HTTP connections",
    "explanation": "Use `cluster` (or PM2) to utilize all CPU cores for your web server. Use `worker_threads` when you have a single, heavy computational task (like image processing or cryptography) that would otherwise block the main event loop."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Memory (Heap vs Stack)",
    "question": "In the V8 engine, where are primitive values and function calls stored, and where are objects and closures stored?",
    "code_snippet": null,
    "options": ["Everything is in the Heap", "Primitives/Calls in the Call Stack (Stack memory); Objects/Closures in the Heap memory", "Everything is in the Stack", "Objects in the Stack; Primitives in the Heap"],
    "correct_answer": "Primitives/Calls in the Call Stack (Stack memory); Objects/Closures in the Heap memory",
    "explanation": "The Stack is fast, strictly ordered, and automatically cleaned up when functions return. The Heap is massive, unstructured, and requires the Garbage Collector to manually find and free unused objects."
  },
  {
    "id": 12,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Garbage Collection",
    "question": "What is the primary algorithm used by the V8 Garbage Collector to clean up the Heap?",
    "code_snippet": null,
    "options": ["Reference Counting", "Mark and Sweep (specifically the Orinoco garbage collector)", "First-In-First-Out", "Manual Memory Management"],
    "correct_answer": "Mark and Sweep (specifically the Orinoco garbage collector)",
    "explanation": "V8 starts from 'GC roots' (like the global object), 'marks' everything it can reach as 'alive', and then 'sweeps' (deletes) everything that wasn't marked. Modern V8 does this concurrently in the background to avoid freezing the main thread."
  },
  {
    "id": 13,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Memory Leaks",
    "question": "Which of the following is the most common cause of a memory leak in a Node.js backend application?",
    "code_snippet": null,
    "options": ["Using `const` instead of `let`", "Accumulating data in a global variable, a growing cache without an eviction policy, or forgetting to close database connections/streams", "Using async/await", "Using TypeScript"],
    "correct_answer": "Accumulating data in a global variable, a growing cache without an eviction policy, or forgetting to close database connections/streams",
    "explanation": "Because the Garbage Collector only cleans up unreachable objects, anything attached to the global scope or held in an open closure/connection will never be freed, eventually causing the Node process to crash with an 'Out of Memory' (OOM) error."
  },
  {
    "id": 14,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "code-fill-in-blank",
    "topic": "EventEmitter Memory Leak Warning",
    "question": "Fill in the blank to correctly increase the limit of listeners on an EventEmitter to prevent the 'MaxListenersExceededWarning' (use with caution).",
    "code_snippet": "const EventEmitter = require('events');\nconst myEmitter = new EventEmitter();\nmyEmitter._______(20);",
    "options": ["setMaxListeners", "increaseLimit", "setLimit", "allowMoreListeners"],
    "correct_answer": "setMaxListeners",
    "explanation": "By default, Node warns you if you attach more than 10 listeners to an EventEmitter, as it usually indicates a memory leak (like attaching a new listener on every HTTP request without removing it). `setMaxListeners(20)` suppresses the warning, but you should usually fix the leak instead."
  },
  {
    "id": 15,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Child Processes (exec vs spawn)",
    "question": "What is the main difference between `child_process.exec()` and `child_process.spawn()`?",
    "code_snippet": null,
    "options": ["They are the same", "`exec` buffers the output in memory (bad for large outputs); `spawn` returns a Stream, allowing you to process large outputs chunk-by-chunk", "`spawn` is for Windows, `exec` is for Linux", "`exec` is asynchronous, `spawn` is synchronous"],
    "correct_answer": "`exec` buffers the output in memory (bad for large outputs); `spawn` returns a Stream, allowing you to process large outputs chunk-by-chunk",
    "explanation": "If you run a command that outputs 500MB of data, `exec` will crash your Node app by exceeding the buffer limit. `spawn` streams the data, keeping memory usage flat and low."
  },
  {
    "id": 16,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Non-Blocking I/O",
    "question": "When Node.js performs a non-blocking I/O operation (like a network request), what happens to the main JavaScript thread?",
    "code_snippet": null,
    "options": ["It waits (blocks) until the response arrives", "It moves on to execute the next line of code, and Libuv pushes the callback to the Event Loop queue when the I/O finishes", "It throws an error", "It spawns a new V8 instance"],
    "correct_answer": "It moves on to execute the next line of code, and Libuv pushes the callback to the Event Loop queue when the I/O finishes",
    "explanation": "This is the magic of Node.js. The main thread never waits. It delegates the I/O to the OS/Thread pool, continues executing JS, and only handles the result later via the callback/Promise when the Event Loop picks it up."
  },
  {
    "id": 17,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "The Event Loop Starvation",
    "question": "What is 'Event Loop Starvation' (or Lag), and how does it affect a Node.js API?",
    "code_snippet": null,
    "options": ["When the server runs out of disk space", "When a synchronous, CPU-heavy task blocks the main thread, preventing the Event Loop from processing incoming HTTP requests or timers, causing massive latency for all users", "When the database locks", "When the SSL certificate expires"],
    "correct_answer": "When a synchronous, CPU-heavy task blocks the main thread, preventing the Event Loop from processing incoming HTTP requests or timers, causing massive latency for all users",
    "explanation": "Because Node is single-threaded, a `for` loop that takes 5 seconds to calculate a hash will freeze the entire server for 5 seconds. No other user can get a response. This is why CPU-heavy tasks must be offloaded to Worker Threads."
  },
  {
    "id": 18,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Uncaught Exceptions",
    "question": "What happens to a Node.js process if an error is thrown and not caught by a `try/catch` or a Promise `.catch()`?",
    "code_snippet": null,
    "options": ["The server ignores it and keeps running", "The process prints the stack trace and immediately exits with a non-zero exit code", "It automatically restarts", "It converts the error to a warning"],
    "correct_answer": "The process prints the stack trace and immediately exits with a non-zero exit code",
    "explanation": "Node.js considers uncaught exceptions fatal. The process will crash. This is why production apps MUST use a process manager like PM2 or a container orchestrator like Kubernetes to automatically restart the app when it crashes."
  },
  {
    "id": 19,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "process.exit() vs process.abort()",
    "question": "What is the difference between `process.exit(1)` and `process.abort()`?",
    "code_snippet": null,
    "options": ["They are the same", "`exit(1)` allows the Event Loop to finish pending tasks and triggers 'exit' events; `abort()` immediately kills the process and generates a core dump file for debugging", "`abort()` is for Windows", "`exit()` is asynchronous"],
    "correct_answer": "`exit(1)` allows the Event Loop to finish pending tasks and triggers 'exit' events; `abort()` immediately kills the process and generates a core dump file for debugging",
    "explanation": "Use `process.exit(1)` for normal error handling. Use `process.abort()` (or sending a SIGABRT signal) only when you need to freeze the exact state of memory for a C++ level core dump to debug a catastrophic V8 or native addon failure."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "Why is mastering the Node.js Event Loop and Memory Management the ultimate 'senior developer' filter in backend interviews?",
    "code_snippet": null,
    "options": ["Because it proves you memorized the documentation", "Because it proves you understand exactly how your code interacts with the OS, allowing you to build highly performant, non-blocking systems that don't crash under heavy load", "Because it is required by TypeScript", "Because it replaces the need for databases"],
    "correct_answer": "Because it proves you understand exactly how your code interacts with the OS, allowing you to build highly performant, non-blocking systems that don't crash under heavy load",
    "explanation": "Anyone can write an Express route. But a Senior Engineer knows that writing a synchronous loop inside that route will take down the entire production server. Mastering the runtime is what separates coders from architects."
  }
]
[
  {
    "id": 21,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "output-prediction",
    "topic": "Microtask Queue (Nested Promises)",
    "question": "What will be the exact output order of this code?",
    "code_snippet": "Promise.resolve().then(() => console.log(1)).then(() => console.log(2));\nPromise.resolve().then(() => console.log(3));",
    "options": ["1, 2, 3", "1, 3, 2", "3, 1, 2", "3, 2, 1"],
    "correct_answer": "1, 3, 2",
    "explanation": "The first promise queues a microtask that logs 1 and returns a new promise. The second promise queues a microtask that logs 3. The microtask queue processes 1, then 3. The `.then` chained on the first promise queues another microtask that logs 2, which runs last."
  },
  {
    "id": 22,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "AsyncLocalStorage (Concept)",
    "question": "What problem does the `AsyncLocalStorage` API solve in Node.js backend applications?",
    "code_snippet": null,
    "options": ["It stores data in the browser's localStorage", "It allows you to store data that is accessible throughout the lifecycle of an async request (like a user ID or transaction ID) without manually passing it through every function argument", "It caches database queries", "It stores environment variables"],
    "correct_answer": "It allows you to store data that is accessible throughout the lifecycle of an async request (like a user ID or transaction ID) without manually passing it through every function argument",
    "explanation": "In complex backend apps, passing a `transactionId` or `userId` through 10 layers of functions is tedious. `AsyncLocalStorage` creates a 'context' that automatically propagates through async/await chains, similar to thread-local storage in Java."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "code-fill-in-blank",
    "topic": "AsyncLocalStorage (API)",
    "question": "Fill in the blank to correctly run a function within a specific AsyncLocalStorage context.",
    "code_snippet": "const asyncLocalStorage = new AsyncLocalStorage();\nconst store = { userId: 123 };\n\nasyncLocalStorage._______(store, () => {\n  // Inside here, asyncLocalStorage.getStore() returns { userId: 123 }\n});",
    "options": ["run", "enter", "context", "bind"],
    "correct_answer": "run",
    "explanation": "The `.run(store, callback)` method executes the callback synchronously, but any async operations spawned inside it will inherit the `store` context, making it accessible via `.getStore()` anywhere down the call stack."
  },
  {
    "id": 24,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Unhandled Promise Rejections",
    "question": "What happens in Node.js (v15 and later) if a Promise is rejected and no `.catch()` or `try/catch` handles it?",
    "code_snippet": null,
    "options": ["It prints a warning but keeps running", "The Node.js process immediately exits with a non-zero exit code", "It automatically retries the Promise", "It converts the rejection to an 'error' event"],
    "correct_answer": "The Node.js process immediately exits with a non-zero exit code",
    "explanation": "Prior to Node 15, unhandled rejections just printed a deprecation warning. Now, they are treated as fatal errors (equivalent to uncaught exceptions) because they almost always indicate a bug that leaves the application in an unpredictable state."
  },
  {
    "id": 25,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Stream Error Handling (pipe vs pipeline)",
    "question": "What is the major flaw of using the legacy `.pipe()` method for streams, and how does `stream.pipeline()` fix it?",
    "code_snippet": null,
    "options": [".pipe() is slower", ".pipe() does not automatically destroy the streams if an error occurs in one of them, leading to memory leaks; `pipeline` handles cleanup and error propagation automatically", ".pipe() only works with files", ".pipe() cannot handle backpressure"],
    "correct_answer": ".pipe() does not automatically destroy the streams if an error occurs in one of them, leading to memory leaks; `pipeline` handles cleanup and error propagation automatically",
    "explanation": "If the destination stream errors, `.pipe()` leaves the source stream open and leaking memory. `stream.pipeline` (or `stream/promises`) ensures that if ANY stream in the chain errors, all other streams are properly destroyed and the error is passed to a final callback."
  },
  {
    "id": 26,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "AbortController (Concept)",
    "question": "What is the purpose of the `AbortController` API in modern Node.js?",
    "code_snippet": null,
    "options": ["To stop the Node.js process", "To provide a standardized way to abort one or more asynchronous operations (like `fetch` requests or streams) before they complete", "To pause the Event Loop", "To cancel a `setTimeout`"],
    "correct_answer": "To provide a standardized way to abort one or more asynchronous operations (like `fetch` requests or streams) before they complete",
    "explanation": "`AbortController` creates a signal that can be passed to `fetch` or stream methods. When you call `controller.abort()`, the operation is immediately canceled, freeing up network and memory resources."
  },
  {
    "id": 27,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "code-fill-in-blank",
    "topic": "AbortController (Fetch Cancellation)",
    "question": "Fill in the blank to correctly pass an abort signal to a `fetch` request.",
    "code_snippet": "const controller = new AbortController();\nconst signal = controller.signal;\n\nfetch('https://api.com/data', { _______: signal });\n\n// Later, if needed:\ncontroller.abort();",
    "options": ["abort", "signal", "cancel", "controller"],
    "correct_answer": "signal",
    "explanation": "The `signal` property in the `fetch` options object links the network request to the controller. If `controller.abort()` is called, the fetch Promise immediately rejects with an `AbortError`."
  },
  {
    "id": 28,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "EventEmitter ('error' Event)",
    "question": "What happens if an `EventEmitter` emits an `'error'` event, but no listener is attached for the `'error'` event?",
    "code_snippet": null,
    "options": ["It logs the error to the console", "It throws the error as an uncaught exception, which will crash the Node.js process", "It ignores the error", "It converts the error to a rejected Promise"],
    "correct_answer": "It throws the error as an uncaught exception, which will crash the Node.js process",
    "explanation": "The `'error'` event is special in Node.js. If it's emitted without a listener, Node assumes it's an unhandled fatal error and crashes the process. You must ALWAYS attach an `.on('error', ...)` listener to any EventEmitter that can emit errors (like streams or servers)."
  },
  {
    "id": 29,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "EventEmitter (once vs on)",
    "question": "What is the difference between `.on()` and `.once()` on an EventEmitter?",
    "code_snippet": null,
    "options": [".on() fires every time; .once() fires only the first time and then automatically removes itself", ".once() is faster", ".on() is for streams; .once() is for HTTP", "There is no difference"],
    "correct_answer": ".on() fires every time; .once() fires only the first time and then automatically removes itself",
    "explanation": "`.once()` is perfect for setup/teardown logic or waiting for a single specific event (like a server 'listening' event) without having to manually call `.removeListener()`."
  },
  {
    "id": 30,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "CommonJS Module Caching",
    "question": "How does Node.js handle `require()` calls for the same module multiple times?",
    "code_snippet": null,
    "options": ["It re-evaluates the module code every time", "It caches the exported value after the first evaluation; subsequent `require()` calls return the exact same cached object reference", "It throws an error", "It creates a new instance of the module in a separate thread"],
    "correct_answer": "It caches the exported value after the first evaluation; subsequent `require()` calls return the exact same cached object reference",
    "explanation": "This is why Node.js modules are singletons. If you `require('./config')` in 10 different files, they all share the exact same object in memory. This is great for singletons, but can cause issues if you accidentally mutate the exported object."
  },
  {
    "id": 31,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "ESM vs CommonJS (Static vs Dynamic)",
    "question": "What is the fundamental difference between ESM `import` and CommonJS `require()`?",
    "code_snippet": null,
    "options": ["ESM is asynchronous and statically analyzed at compile time; CJS is synchronous and dynamically evaluated at runtime", "CJS is for frontend; ESM is for backend", "ESM is slower", "CJS supports top-level await"],
    "correct_answer": "ESM is asynchronous and statically analyzed at compile time; CJS is synchronous and dynamically evaluated at runtime",
    "explanation": "Because `import` is static, bundlers and Node.js can perform 'tree-shaking' (removing unused exports) and know the dependency graph before running code. `require()` can be placed inside `if` statements or functions, making static analysis impossible."
  },
  {
    "id": 32,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Top-Level Await (ESM)",
    "question": "In which Node.js module system is 'Top-Level Await' natively supported without wrapping code in an async IIFE?",
    "code_snippet": null,
    "options": ["CommonJS", "ES Modules (ESM)", "Both", "Neither"],
    "correct_answer": "ES Modules (ESM)",
    "explanation": "Top-level `await` allows you to use `await` directly in the root of a module file. This is incredibly useful for initializing database connections or loading configuration before the rest of the app starts, but it is only supported in ESM."
  },
  {
    "id": 33,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "The 'node:' Protocol Prefix",
    "question": "What is the benefit of using the `node:` prefix for built-in modules (e.g., `import fs from 'node:fs'`)?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It explicitly tells Node.js and bundlers that this is a built-in core module, preventing accidental conflicts with npm packages of the same name", "It enables TypeScript support", "It is required for ESM"],
    "correct_answer": "It explicitly tells Node.js and bundlers that this is a built-in core module, preventing accidental conflicts with npm packages of the same name",
    "explanation": "If you install an npm package named `events` or `util`, importing `events` might accidentally load the npm package instead of the Node core module. `node:events` guarantees you get the built-in module."
  },
  {
    "id": 34,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "V8 Heap Snapshots",
    "question": "What is a 'Heap Snapshot' in the context of debugging Node.js memory leaks?",
    "code_snippet": null,
    "options": ["A screenshot of the terminal", "A serialized representation of all objects in the V8 heap at a specific moment, used to identify which objects are consuming memory and not being garbage collected", "A log of all HTTP requests", "A backup of the database"],
    "correct_answer": "A serialized representation of all objects in the V8 heap at a specific moment, used to identify which objects are consuming memory and not being garbage collected",
    "explanation": "By taking a heap snapshot, waiting, and taking another, you can compare them to see exactly which objects are growing in memory (e.g., a global array that keeps pushing data) and trace them back to the exact line of code that created them."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Node.js CPU Profiling",
    "question": "How can you generate a CPU profile of a Node.js application to find performance bottlenecks?",
    "code_snippet": null,
    "options": ["Using `console.time()`", "By running the app with the `node --prof app.js` flag, which generates a V8 log file that can be processed into a flamegraph", "Using `setTimeout`", "You cannot profile Node.js"],
    "correct_answer": "By running the app with the `node --prof app.js` flag, which generates a V8 log file that can be processed into a flamegraph",
    "explanation": "The `--prof` flag tells the V8 engine to record every function call and its duration. You can then use the `--prof-process` tool to generate a text report or use tools like Speedscope to visualize a flamegraph of exactly where your CPU time is being spent."
  },
  {
    "id": 36,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Diagnostics Channel",
    "question": "What is the `diagnostics_channel` module in Node.js?",
    "code_snippet": null,
    "options": ["A chat room for developers", "A built-in module that allows core Node.js and third-party libraries to emit internal telemetry and tracing events without adding performance overhead unless someone is listening", "A logging framework", "A database connector"],
    "correct_answer": "A built-in module that allows core Node.js and third-party libraries to emit internal telemetry and tracing events without adding performance overhead unless someone is listening",
    "explanation": "It's the foundation for modern APM (Application Performance Monitoring) tools like Datadog or OpenTelemetry. They subscribe to these channels to trace HTTP requests, DNS lookups, and database queries without monkey-patching core modules."
  },
  {
    "id": 37,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Worker Threads (SharedArrayBuffer)",
    "question": "When using `worker_threads`, what is the purpose of a `SharedArrayBuffer`?",
    "code_snippet": null,
    "options": ["To share text files between threads", "To create a block of memory that can be accessed and modified concurrently by the main thread and worker threads without copying data", "To share database connections", "To share HTTP requests"],
    "correct_answer": "To create a block of memory that can be accessed and modified concurrently by the main thread and worker threads without copying data",
    "explanation": "Normally, workers communicate by copying data (which is slow for large payloads). `SharedArrayBuffer` allows multiple threads to read/write the exact same memory space, enabling ultra-high-performance data processing (though it requires careful synchronization like `Atomics` to avoid race conditions)."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Node.js Native Watch Mode",
    "question": "What does the `node --watch` flag do in modern Node.js versions?",
    "code_snippet": null,
    "options": ["Monitors CPU usage", "Automatically restarts the Node.js process when file changes are detected, replacing the need for third-party tools like `nodemon`", "Watches for security vulnerabilities", "Tracks memory leaks"],
    "correct_answer": "Automatically restarts the Node.js process when file changes are detected, replacing the need for third-party tools like `nodemon`",
    "explanation": "Introduced in Node 18.11+, `node --watch` provides native, highly optimized file watching and process restarting, making tools like `nodemon` largely obsolete for standard development workflows."
  },
  {
    "id": 39,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Web Crypto API",
    "question": "What is the `crypto.webcrypto` object in Node.js?",
    "code_snippet": null,
    "options": ["A deprecated crypto module", "An implementation of the browser's Web Crypto API, allowing developers to use the exact same cryptographic code (like `SubtleCrypto`) in Node.js and the browser", "A tool to encrypt CSS", "A random number generator only"],
    "correct_answer": "An implementation of the browser's Web Crypto API, allowing developers to use the exact same cryptographic code (like `SubtleCrypto`) in Node.js and the browser",
    "explanation": "This enables 'isomorphic' cryptography. You can write code to generate JWTs, hash passwords, or encrypt data using the Web Crypto API, and it will work identically in a React frontend and a Node.js backend without needing separate libraries."
  },
  {
    "id": 40,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up",
    "question": "You've now covered AsyncLocalStorage, Stream error handling, ESM, and Node.js profiling. What is the ultimate takeaway from mastering these advanced runtime features?",
    "code_snippet": null,
    "options": ["To memorize the API documentation", "To build resilient, observable, and highly performant backend systems that can handle massive scale without leaking memory or crashing under edge-case errors", "To avoid using async/await", "To write code without error handling"],
    "correct_answer": "To build resilient, observable, and highly performant backend systems that can handle massive scale without leaking memory or crashing under edge-case errors",
    "explanation": "Mastering the Node.js runtime means you stop guessing why your server crashed or slowed down. You gain the ability to trace context across async boundaries, handle errors gracefully at the stream level, and profile your code to the millisecond."
  }
]
[
  {
    "id": 41,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "HTTP Internals (Streams)",
    "question": "In the Node.js `http` module, what are the `IncomingMessage` (req) and `ServerResponse` (res) objects under the hood?",
    "code_snippet": null,
    "options": ["Standard JavaScript objects", "They are both Readable and Writable Streams, allowing you to pipe data directly to/from them for high-performance file uploads and streaming responses", "They are Promises", "They are Web Workers"],
    "correct_answer": "They are both Readable and Writable Streams, allowing you to pipe data directly to/from them for high-performance file uploads and streaming responses",
    "explanation": "Because `req` is a Readable stream and `res` is a Writable stream, you can do `req.pipe(res)` or `fs.createReadStream().pipe(res)`. This streams data chunk-by-chunk, keeping memory usage incredibly low even for 10GB file uploads."
  },
  {
    "id": 42,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "HTTP Agent & Keep-Alive",
    "question": "What is the purpose of the `http.Agent` class, and why is `keepAlive: true` critical for backend performance?",
    "code_snippet": null,
    "options": ["It caches HTML pages", "It manages connection pooling; `keepAlive: true` reuses existing TCP connections for multiple HTTP requests, eliminating the massive overhead of the TCP/TLS handshake on every request", "It compresses JSON", "It routes requests to different servers"],
    "correct_answer": "It manages connection pooling; `keepAlive: true` reuses existing TCP connections for multiple HTTP requests, eliminating the massive overhead of the TCP/TLS handshake on every request",
    "explanation": "By default, Node.js HTTP clients close the connection after every request. If your backend makes 1,000 requests to a microservice per second, creating 1,000 TCP connections will destroy your CPU. An Agent with `keepAlive: true` pools and reuses connections."
  },
  {
    "id": 43,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "code-fill-in-blank",
    "topic": "HTTPS Server Creation",
    "question": "Fill in the blank to correctly create an HTTPS server using a private key and certificate.",
    "code_snippet": "const https = require('node:https');\nconst options = { key: privateKey, cert: certificate };\n\nhttps._______(options, app).listen(443);",
    "options": ["createServer", "start", "init", "bind"],
    "correct_answer": "createServer",
    "explanation": "The `https.createServer` method takes an options object containing the cryptographic keys and a request listener (like your Express app). It handles the complex TLS handshake automatically before passing the decrypted request to your app."
  },
  {
    "id": 44,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "DNS Resolution (lookup vs resolve)",
    "question": "What is the fundamental difference between `dns.lookup()` and `dns.resolve()` in Node.js?",
    "code_snippet": null,
    "options": ["They are aliases", "`dns.lookup()` uses the OS's native resolver (blocking the Libuv thread pool); `dns.resolve()` uses the non-blocking `c-ares` library to query DNS servers directly", "`resolve()` is deprecated", "`lookup()` is for IPv6"],
    "correct_answer": "`dns.lookup()` uses the OS's native resolver (blocking the Libuv thread pool); `dns.resolve()` uses the non-blocking `c-ares` library to query DNS servers directly",
    "explanation": "If you do millions of DNS lookups, `dns.lookup()` can exhaust the Libuv thread pool and starve your file system I/O. `dns.resolve()` bypasses the OS and the thread pool entirely, making it vastly superior for high-throughput backend services."
  },
  {
    "id": 45,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "The Cluster Module",
    "question": "What is the primary purpose of the `cluster` module in Node.js?",
    "code_snippet": null,
    "options": ["To connect to a database cluster", "To fork the single-threaded Node.js process into multiple worker processes that all share the same server port, utilizing all CPU cores", "To cluster CSS files", "To group HTTP requests"],
    "correct_answer": "To fork the single-threaded Node.js process into multiple worker processes that all share the same port, utilizing all CPU cores",
    "explanation": "Because Node.js runs on a single thread, it can only use one CPU core. The `cluster` module creates a 'primary' process that spawns 'worker' processes (one per core), load-balancing incoming HTTP requests across them."
  },
  {
    "id": 46,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Cluster IPC (Inter-Process Communication)",
    "question": "How do the primary process and worker processes in a Cluster communicate with each other?",
    "code_snippet": null,
    "options": ["They share the same memory space", "Through an IPC (Inter-Process Communication) channel using `process.send()` and `process.on('message')`", "Through HTTP requests", "They cannot communicate"],
    "correct_answer": "Through an IPC (Inter-Process Communication) channel using `process.send()` and `process.on('message')`",
    "explanation": "Because each worker is a completely separate V8 instance with its own memory, they cannot share JavaScript variables. They must serialize messages and send them over the IPC channel provided by Node.js."
  },
  {
    "id": 47,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Cluster Shared State",
    "question": "If you need to share a real-time cache or session state across all workers in a Cluster, what is the correct architectural approach?",
    "code_snippet": null,
    "options": ["Use a global JavaScript object", "Use an external, shared data store like Redis or Memcached that all workers can connect to", "Use `AsyncLocalStorage`", "Use the IPC channel for every cache hit"],
    "correct_answer": "Use an external, shared data store like Redis or Memcached that all workers can connect to",
    "explanation": "Because workers have isolated memory, an in-memory cache in Worker 1 won't be visible to Worker 2. You must use a centralized, external system like Redis to ensure all workers see the exact same state."
  },
  {
    "id": 48,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "UV_THREADPOOL_SIZE",
    "question": "What environment variable allows you to increase the size of the Libuv thread pool, and why would you need to?",
    "code_snippet": null,
    "options": ["NODE_THREADS", "UV_THREADPOOL_SIZE", "MAX_WORKERS", "LIBUV_POOL"],
    "correct_answer": "UV_THREADPOOL_SIZE",
    "explanation": "By default, the Libuv thread pool has 4 threads. If your app does heavy file system I/O, cryptography, or DNS lookups, 4 threads might become a bottleneck. Setting `UV_THREADPOOL_SIZE=128` allows Node to handle more concurrent blocking OS tasks."
  },
  {
    "id": 49,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Monitoring Event Loop Lag",
    "question": "How can you programmatically measure the 'Event Loop Lag' (how delayed the event loop is) in a production Node.js app?",
    "code_snippet": null,
    "options": ["Using `console.time()`", "Using the `perf_hooks` module, specifically `monitorEventLoopDelay()`, to track the histogram of loop delays", "Using `process.memoryUsage()`", "Using `os.loadavg()`"],
    "correct_answer": "Using the `perf_hooks` module, specifically `monitorEventLoopDelay()`, to track the histogram of loop delays",
    "explanation": "Event Loop Lag is the ultimate metric for Node.js health. If the lag is high, it means your single thread is blocked, and users are experiencing slow response times. `perf_hooks` provides a highly optimized, low-overhead way to track this."
  },
  {
    "id": 50,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Undici & Native Fetch",
    "question": "What is `undici`, and how does it relate to the native `fetch` API in Node.js 18+?",
    "code_snippet": null,
    "options": ["It is a database driver", "It is the official, high-performance HTTP client built from scratch for Node.js; it powers the native global `fetch` API, replacing the older `http` module for outbound requests", "It is a CSS parser", "It is a testing framework"],
    "correct_answer": "It is the official, high-performance HTTP client built from scratch for Node.js; it powers the native global `fetch` API, replacing the older `http` module for outbound requests",
    "explanation": "Before Node 18, developers used `node-fetch` or `axios`. Now, `undici` provides a blazing-fast, fully spec-compliant `fetch` implementation natively in the runtime, supporting connection pooling, HTTP/2, and WebSockets out of the box."
  },
  {
    "id": 51,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Path Module (join vs resolve)",
    "question": "What is the exact difference between `path.join()` and `path.resolve()`?",
    "code_snippet": null,
    "options": ["They are the same", "`join()` simply concatenates path segments; `resolve()` resolves the sequence of paths into an absolute path, working from right to left like a series of `cd` commands", "`resolve()` is for URLs", "`join()` is deprecated"],
    "correct_answer": "`join()` simply concatenates path segments; `resolve()` resolves the sequence of paths into an absolute path, working from right to left like a series of `cd` commands",
    "explanation": "`path.join('/foo', 'bar')` results in `/foo/bar`. But `path.resolve('/foo', 'bar')` treats `/foo` as the current directory and resolves `bar` against it, guaranteeing an absolute path based on the current working directory if no absolute path is provided."
  },
  {
    "id": 52,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Process Signals (SIGTERM)",
    "question": "When running Node.js in Docker or Kubernetes, what signal does the orchestrator send to request a graceful shutdown?",
    "code_snippet": null,
    "options": ["SIGINT", "SIGTERM", "SIGKILL", "SIGHUP"],
    "correct_answer": "SIGTERM",
    "explanation": "SIGTERM is the polite request to terminate. It gives your Node.js app time to catch the signal, finish processing current requests, close database connections, and exit cleanly. SIGKILL, on the other hand, instantly murders the process without warning."
  },
  {
    "id": 53,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Graceful Shutdown Pattern",
    "question": "What is the correct sequence of operations for implementing a 'Graceful Shutdown' in a Node.js API?",
    "code_snippet": null,
    "options": ["Call `process.exit(0)` immediately", "1. Catch SIGTERM, 2. Stop the HTTP server from accepting new connections, 3. Wait for in-flight requests to finish, 4. Close DB/Redis connections, 5. Call `process.exit(0)`", "Close the database first, then stop the server", "Restart the server automatically"],
    "correct_answer": "1. Catch SIGTERM, 2. Stop the HTTP server from accepting new connections, 3. Wait for in-flight requests to finish, 4. Close DB/Redis connections, 5. Call `process.exit(0)`",
    "explanation": "If you close the DB before finishing requests, those requests will crash. If you exit immediately, you drop active user connections. A graceful shutdown ensures zero data loss and zero interrupted user experiences during deployments."
  },
  {
    "id": 54,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "HTTP/2 Multiplexing",
    "question": "What is the primary advantage of the `http2` module over the `http` module?",
    "code_snippet": null,
    "options": ["It uses JSON instead of text", "It supports multiplexing, allowing multiple concurrent request/response streams over a single TCP connection, eliminating Head-of-Line blocking", "It is written in Rust", "It automatically compresses images"],
    "correct_answer": "It supports multiplexing, allowing multiple concurrent request/response streams over a single TCP connection, eliminating Head-of-Line blocking",
    "explanation": "In HTTP/1.1, a slow request blocks other requests on the same connection. HTTP/2 multiplexes streams, meaning a slow database query for User A doesn't delay the response for User B on the same connection."
  },
  {
    "id": 55,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "fs.promises vs fs",
    "question": "Why is `fs.promises` generally preferred over the callback-based `fs` module in modern Node.js?",
    "code_snippet": null,
    "options": ["It is faster", "It allows the use of `async/await`, resulting in flatter, more readable code and much easier error handling via `try/catch`", "It supports larger files", "It is synchronous"],
    "correct_answer": "It allows the use of `async/await`, resulting in flatter, more readable code and much easier error handling via `try/catch`",
    "explanation": "Callback-based `fs` leads to 'callback hell' and makes error propagation difficult. `fs.promises` integrates perfectly with modern async/await syntax, making file operations clean and robust."
  },
  {
    "id": 56,
    "level": "intermediate",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "The OS Module",
    "question": "What kind of information does the `os` module provide?",
    "code_snippet": null,
    "options": ["Database schemas", "Utilities for interacting with the operating system, such as CPU core counts, total/free memory, network interfaces, and system uptime", "CSS variables", "HTTP headers"],
    "correct_answer": "Utilities for interacting with the operating system, such as CPU core counts, total/free memory, network interfaces, and system uptime",
    "explanation": "The `os` module is essential for building health-check endpoints or auto-scaling logic. For example, you can use `os.freemem()` to trigger an alert if your server is running out of RAM."
  },
  {
    "id": 57,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Zero-Downtime Deployments",
    "question": "How does the Cluster module enable 'Zero-Downtime Deployments'?",
    "code_snippet": null,
    "options": ["It doesn't", "The primary process can gracefully shut down old workers one-by-one while spinning up new workers with the updated code, ensuring the server always has available workers to handle traffic", "It pauses the internet", "It caches the entire app in the browser"],
    "correct_answer": "The primary process can gracefully shut down old workers one-by-one while spinning up new workers with the updated code, ensuring the server always has available workers to handle traffic",
    "explanation": "Tools like PM2 use the Cluster module under the hood to perform 'cluster mode' restarts. They never kill all workers at once, ensuring that users never experience a 502 Bad Gateway during a deployment."
  },
  {
    "id": 58,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Anti-Pattern (Sync I/O)",
    "question": "Why is using `fs.readFileSync` considered a catastrophic anti-pattern in a production Node.js web server?",
    "code_snippet": null,
    "options": ["It uses too much memory", "It completely blocks the main event loop thread, freezing the entire server and preventing it from handling ANY other incoming HTTP requests until the file read finishes", "It is deprecated", "It corrupts the file"],
    "correct_answer": "It completely blocks the main event loop thread, freezing the entire server and preventing it from handling ANY other incoming HTTP requests until the file read finishes",
    "explanation": "If reading a config file takes 2 seconds, your entire API is completely unresponsive for 2 seconds. In a high-traffic environment, this will cause thousands of requests to time out. Always use `fs.promises.readFile` or `fs.readFile`."
  },
  {
    "id": 59,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "WebSockets (ws module)",
    "question": "How does Node.js handle WebSockets, given that the core `http` module only supports HTTP?",
    "code_snippet": null,
    "options": ["It doesn't support them", "Through the HTTP 'Upgrade' mechanism, where an HTTP request is upgraded to a persistent, full-duplex WebSocket connection, typically handled by libraries like `ws` or `Socket.io`", "By using HTTP/2 only", "By polling every second"],
    "correct_answer": "Through the HTTP 'Upgrade' mechanism, where an HTTP request is upgraded to a persistent, full-duplex WebSocket connection, typically handled by libraries like `ws` or `Socket.io`",
    "explanation": "WebSockets start as a standard HTTP request with an `Upgrade: websocket` header. Node.js intercepts this, hands it off to the `ws` library, and the connection transitions from HTTP to a raw TCP socket that both client and server can write to at any time."
  },
  {
    "id": 60,
    "level": "advanced",
    "module_id": "node_mod_01_internals",
    "module_name": "Advanced Node.js & Runtime Internals",
    "type": "conceptual",
    "topic": "Module 1 Wrap-up (The Node.js Zen)",
    "question": "You have now completed the deep dive into Node.js Internals. What is the ultimate hallmark of a Senior Node.js Backend Engineer?",
    "code_snippet": null,
    "options": ["Memorizing every core module", "Understanding that Node.js is a single-threaded, event-driven runtime; and designing systems that offload heavy I/O to the OS, use streams for memory efficiency, and protect the event loop at all costs to ensure massive scalability", "Writing synchronous code for simplicity", "Avoiding the use of npm packages"],
    "correct_answer": "Understanding that Node.js is a single-threaded, event-driven runtime; and designing systems that offload heavy I/O to the OS, use streams for memory efficiency, and protect the event loop at all costs to ensure massive scalability",
    "explanation": "Mastering Node.js isn't about learning Express routes. It's about deeply respecting the Event Loop. When you understand how Libuv, V8, and the thread pool interact, you can build backend systems that handle millions of concurrent connections with minimal hardware."
  }
]
