[
  {
    "id": 61,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Web Storage (localStorage vs sessionStorage)",
    "question": "What is the fundamental difference between `localStorage` and `sessionStorage`?",
    "code_snippet": null,
    "options": ["localStorage is for files; sessionStorage is for text", "localStorage persists even after the browser is closed; sessionStorage is cleared as soon as the browser tab is closed", "sessionStorage has a larger capacity limit", "localStorage is synchronous; sessionStorage is asynchronous"],
    "correct_answer": "localStorage persists even after the browser is closed; sessionStorage is cleared as soon as the browser tab is closed",
    "explanation": "Both store key-value pairs (up to ~5MB) synchronously. Use `localStorage` for long-term user preferences (like dark mode). Use `sessionStorage` for temporary state (like a multi-step form wizard) that should vanish when the user leaves the tab."
  },
  {
    "id": 62,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Cookie Security Attributes",
    "question": "What does the `HttpOnly` attribute do when set on a browser cookie?",
    "code_snippet": null,
    "options": ["It hides the cookie from the browser's developer tools", "It prevents client-side JavaScript (like `document.cookie`) from accessing the cookie, mitigating XSS token theft", "It encrypts the cookie's value", "It forces the cookie to be deleted after 1 hour"],
    "correct_answer": "It prevents client-side JavaScript from accessing the cookie, mitigating XSS token theft",
    "explanation": "If an attacker injects a malicious script into your page, they can easily read `document.cookie` and steal the user's session. `HttpOnly` ensures the cookie is ONLY sent to the server via HTTP headers, keeping it completely invisible to JavaScript."
  },
  {
    "id": 63,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "IndexedDB (Concept)",
    "question": "When should you use IndexedDB instead of `localStorage`?",
    "code_snippet": null,
    "options": ["When you need to store less than 5MB of simple strings", "When you need to store large amounts of structured data (like files, blobs, or complex objects) asynchronously without blocking the main UI thread", "When you need the data to be sent to the server automatically", "When you need to encrypt the data"],
    "correct_answer": "When you need to store large amounts of structured data asynchronously without blocking the main UI thread",
    "explanation": "`localStorage` is synchronous and blocks the UI while reading/writing. IndexedDB is an asynchronous, transactional, NoSQL database built into the browser, capable of storing hundreds of megabytes (or even gigabytes) of data, perfect for offline-first apps."
  },
  {
    "id": 64,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly request the user's current geographic coordinates via the browser API.",
    "code_snippet": "navigator._______.getCurrentPosition(\n  (pos) => console.log(pos.coords.latitude),\n  (err) => console.error(err)\n);",
    "options": ["location", "geolocation", "gps", "coordinates"],
    "correct_answer": "geolocation",
    "explanation": "The Geolocation API requires explicit user permission. If granted, it returns the latitude, longitude, and accuracy, usually derived from GPS, Wi-Fi, or IP address."
  },
  {
    "id": 65,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Web Workers (Concept & Limitations)",
    "question": "What is a 'Web Worker', and what is its most critical limitation?",
    "code_snippet": null,
    "options": ["A background thread that can manipulate the DOM; limitation: it is slow", "A background thread for heavy computation; limitation: it CANNOT access the DOM, `window`, or `document` objects", "A tool for styling HTML; limitation: it only works in Chrome", "A server-side Node.js process; limitation: it requires a backend"],
    "correct_answer": "A background thread for heavy computation; limitation: it CANNOT access the DOM, `window`, or `document` objects",
    "explanation": "JavaScript is single-threaded. If you parse a massive JSON file on the main thread, the UI freezes. Web Workers run in a separate thread, but they must communicate with the main thread via `postMessage()` because they have zero access to the DOM."
  },
  {
    "id": 66,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Service Workers (Concept)",
    "question": "What is the primary role of a 'Service Worker' in a modern web application?",
    "code_snippet": null,
    "options": ["To style the HTML document", "To act as a programmable network proxy, allowing you to intercept fetch requests, cache responses, and enable offline capabilities", "To replace the backend database", "To compile TypeScript"],
    "correct_answer": "To act as a programmable network proxy, allowing you to intercept fetch requests, cache responses, and enable offline capabilities",
    "explanation": "Service Workers are the foundation of Progressive Web Apps (PWAs). They sit between the app and the network, allowing you to serve cached assets instantly or show an 'offline' page when the user has no internet connection."
  },
  {
    "id": 67,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Service Worker Lifecycle",
    "question": "Which of the following is a mandatory requirement for registering a Service Worker in a browser?",
    "code_snippet": null,
    "options": ["The page must be served over HTTPS (or localhost)", "The page must be an HTML5 document", "The browser must be Safari", "The user must be logged in"],
    "correct_answer": "The page must be served over HTTPS (or localhost)",
    "explanation": "Because Service Workers can intercept and modify network requests, they are a massive security risk if intercepted by a Man-in-the-Middle attack. Browsers strictly require HTTPS to register a Service Worker (with `localhost` as the only exception for local development)."
  },
  {
    "id": 68,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Intersection Observer API",
    "question": "What problem does the `IntersectionObserver` API solve compared to listening to the `scroll` event?",
    "code_snippet": null,
    "options": ["It makes the page scroll faster", "It efficiently detects when an element enters or exits the viewport without causing layout thrashing or performance drops associated with continuous scroll listeners", "It automatically lazy-loads images", "It prevents the user from scrolling"],
    "correct_answer": "It efficiently detects when an element enters or exits the viewport without causing layout thrashing",
    "explanation": "Listening to `window.onscroll` fires hundreds of times per second, forcing the browser to recalculate layouts. `IntersectionObserver` runs asynchronously in the browser's native rendering pipeline, making it perfect for lazy-loading images or triggering infinite scroll."
  },
  {
    "id": 69,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly add the native HTML5 lazy-loading attribute to an image.",
    "code_snippet": "<img src=\"hero.jpg\" _______=\"lazy\" alt=\"Hero Image\">",
    "options": ["loading", "defer", "lazy", "async"],
    "correct_answer": "loading",
    "explanation": "The `loading=\"lazy\"` attribute tells the browser to defer downloading the image until the user scrolls near it. This drastically reduces initial page weight and improves the Largest Contentful Paint (LCP) metric."
  },
  {
    "id": 70,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "History API (SPAs)",
    "question": "How do Single Page Applications (SPAs) like React Router change the URL in the browser without triggering a full page reload?",
    "code_snippet": null,
    "options": ["By using `<iframe>` tags", "By using the History API (`window.history.pushState`) to manipulate the browser's session history programmatically", "By using `localStorage`", "By using WebSockets"],
    "correct_answer": "By using the History API (`window.history.pushState`) to manipulate the browser's session history programmatically",
    "explanation": "`pushState` allows JS to add a new entry to the browser's back/forward history and update the URL bar. It does NOT reload the page or make a network request; it simply updates the browser state, allowing the SPA to render the new view."
  },
  {
    "id": 71,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Clipboard API",
    "question": "What is the modern, secure way to copy text to the user's clipboard via JavaScript?",
    "code_snippet": null,
    "options": ["`document.execCommand('copy')`", "`navigator.clipboard.writeText('text')`", "`window.copy('text')`", "`localStorage.setItem('clipboard', 'text')`"],
    "correct_answer": "`navigator.clipboard.writeText('text')`",
    "explanation": "The legacy `execCommand` was synchronous and insecure. The modern Clipboard API is asynchronous (returns a Promise) and requires the page to be in focus and served over HTTPS, ensuring the user isn't surprised by background clipboard hijacking."
  },
  {
    "id": 72,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Page Visibility API",
    "question": "How can a web application detect if the user has switched to a different browser tab or minimized the window?",
    "code_snippet": null,
    "options": ["By listening to the `onblur` event on the window", "By using the Page Visibility API (`document.hidden` and the `visibilitychange` event)", "By using the Geolocation API", "It is impossible to detect"],
    "correct_answer": "By using the Page Visibility API (`document.hidden` and the `visibilitychange` event)",
    "explanation": "This is crucial for performance and UX. You can use it to pause a heavy video or stop polling an API when the tab is hidden, and resume them instantly when the user comes back."
  },
  {
    "id": 73,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "PostMessage API (Cross-Origin)",
    "question": "If your main page and an embedded `<iframe>` are hosted on different domains, how can they securely communicate?",
    "code_snippet": null,
    "options": ["They cannot communicate due to the Same-Origin Policy", "By using the `window.postMessage()` API, which safely bypasses the Same-Origin Policy when used correctly", "By sharing `localStorage`", "By using WebSockets"],
    "correct_answer": "By using the `window.postMessage()` API, which safely bypasses the Same-Origin Policy when used correctly",
    "explanation": "`postMessage` allows cross-origin communication. The sender specifies the target origin, and the receiver MUST verify the `event.origin` to ensure the message is coming from a trusted domain, preventing malicious data injection."
  },
  {
    "id": 74,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Fetch API vs XMLHttpRequest",
    "question": "What is the primary architectural advantage of the `fetch()` API over the legacy `XMLHttpRequest` (XHR)?",
    "code_snippet": null,
    "options": ["It is synchronous by default", "It is built on Promises, making it much cleaner to use with `async/await`, and it supports streaming responses", "It automatically parses XML", "It bypasses CORS"],
    "correct_answer": "It is built on Promises, making it much cleaner to use with `async/await`, and it supports streaming responses",
    "explanation": "XHR relies on messy callbacks. `fetch()` returns a Promise, integrating perfectly with modern JavaScript. It also provides low-level access to the response stream, allowing you to process massive files chunk-by-chunk."
  },
  {
    "id": 75,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Resource Hints (Preload vs Prefetch)",
    "question": "What is the difference between `<link rel=\"preload\">` and `<link rel=\"prefetch\">`?",
    "code_snippet": null,
    "options": ["They are the same", "`preload` fetches critical resources needed for the CURRENT page immediately; `prefetch` fetches resources that might be needed for FUTURE navigations during browser idle time", "`prefetch` is for CSS; `preload` is for JS", "`preload` is deprecated"],
    "correct_answer": "`preload` fetches critical resources for the CURRENT page; `prefetch` fetches resources for FUTURE navigations during idle time",
    "explanation": "Use `preload` for the custom font or hero image that the current page needs *right now* to render. Use `prefetch` for the JavaScript bundle of the next page you expect the user to click on, downloading it quietly in the background."
  },
  {
    "id": 76,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Core Web Vitals (INP)",
    "question": "In March 2024, Google replaced FID (First Input Delay) with INP as a Core Web Vital. What does INP (Interaction to Next Paint) measure?",
    "code_snippet": null,
    "options": ["How fast the first image loads", "The overall responsiveness of a page by measuring the latency of ALL user interactions (clicks, taps, keyboard) throughout the entire session", "How much the layout shifts", "The total download size"],
    "correct_answer": "The overall responsiveness of a page by measuring the latency of ALL user interactions throughout the entire session",
    "explanation": "FID only measured the *first* click. INP measures every click, tap, and keypress, ensuring the page remains snappy and responsive not just at load time, but throughout the user's entire journey."
  },
  {
    "id": 77,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "SEO (Canonical Tag)",
    "question": "What is the purpose of the `<link rel=\"canonical\">` tag in the `<head>` of an HTML document?",
    "code_snippet": null,
    "options": ["To link to the CSS stylesheet", "To tell search engines the 'master' URL of a page, preventing duplicate content penalties when multiple URLs serve the same content", "To redirect the user to a new domain", "To hide the page from search engines"],
    "correct_answer": "To tell search engines the 'master' URL of a page, preventing duplicate content penalties",
    "explanation": "If your product page is accessible via `/product/123` AND `/product/123?color=red`, search engines might see them as duplicate content. The canonical tag points both to the single, authoritative URL, consolidating SEO ranking power."
  },
  {
    "id": 78,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Structured Data (JSON-LD)",
    "question": "How do you provide 'Structured Data' (like Recipe or Product schemas) to search engines in modern HTML?",
    "code_snippet": null,
    "options": ["By adding custom HTML attributes", "By embedding a `<script type=\"application/ld+json\">` block containing Schema.org JSON-LD data in the `<head>`", "By using the `<meta>` tag exclusively", "By writing a sitemap.xml file"],
    "correct_answer": "By embedding a `<script type=\"application/ld+json\">` block containing Schema.org JSON-LD data",
    "explanation": "JSON-LD (JavaScript Object Notation for Linked Data) is the Google-recommended format. It allows you to explicitly tell search engines 'This is a Product, it costs $50, and it has 5 stars,' enabling rich snippets in search results."
  },
  {
    "id": 79,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Web Manifest (PWA)",
    "question": "What does the `<link rel=\"manifest\">` tag link to, and what is its purpose?",
    "code_snippet": null,
    "options": ["A CSS file; for styling the app", "A `manifest.json` file; it defines how the app appears when installed on a device (name, icons, theme color, display mode)", "A JavaScript file; for routing", "A database file; for offline storage"],
    "correct_answer": "A `manifest.json` file; it defines how the app appears when installed on a device",
    "explanation": "The Web App Manifest is what allows a website to be 'Installed to Home Screen' on mobile devices, launching in a standalone window without the browser's URL bar, bridging the gap between web and native apps."
  },
  {
    "id": 80,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up (The Browser as a Platform)",
    "question": "You've covered Storage, Workers, Observers, and Performance APIs. What is the ultimate paradigm shift of modern Web APIs?",
    "code_snippet": null,
    "options": ["The browser is just a document viewer", "The browser is a fully-fledged application runtime (like an OS), providing secure, standardized APIs for hardware, network, and storage that rival native desktop/mobile apps", "HTML has replaced JavaScript", "Web APIs are only for mobile devices"],
    "correct_answer": "The browser is a fully-fledged application runtime, providing secure, standardized APIs for hardware, network, and storage that rival native apps",
    "explanation": "With Web Workers, IndexedDB, Service Workers, and WebRTC, the browser is no longer just rendering text. It is a secure, sandboxed operating system capable of running complex, offline-capable, real-time applications entirely within the HTML document."
  }
]
[
  {
    "id": 81,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "WebRTC (Concept)",
    "question": "What is WebRTC (Web Real-Time Communication), and what primary problem does it solve for web applications?",
    "code_snippet": null,
    "options": ["It allows websites to access the local file system", "It enables direct, peer-to-peer audio, video, and data sharing between browsers without requiring a dedicated media server in the middle", "It encrypts HTTP requests", "It manages browser cookies"],
    "correct_answer": "It enables direct, peer-to-peer audio, video, and data sharing between browsers without requiring a dedicated media server in the middle",
    "explanation": "WebRTC powers applications like Zoom, Google Meet, and Discord in the browser. By establishing a direct peer-to-peer connection, it drastically reduces latency and server bandwidth costs for real-time streaming."
  },
  {
    "id": 82,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "WebRTC (Signaling)",
    "question": "If WebRTC is peer-to-peer, why do you still need a backend server (a Signaling Server) to make a WebRTC call work?",
    "code_snippet": null,
    "options": ["To store the video files", "To exchange the initial connection metadata (SDP and ICE candidates) so the two browsers can find each other through firewalls and NATs", "To compress the video stream", "To handle the billing"],
    "correct_answer": "To exchange the initial connection metadata (SDP and ICE candidates) so the two browsers can find each other",
    "explanation": "Browsers behind corporate firewalls or NATs don't know their own public IP addresses. The Signaling Server (usually using WebSockets) acts as a matchmaker, passing the 'handshake' data between peers so they can establish the direct P2P connection."
  },
  {
    "id": 83,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "OffscreenCanvas",
    "question": "What is the `OffscreenCanvas` API, and how does it improve performance for heavy canvas rendering?",
    "code_snippet": null,
    "options": ["It hides the canvas from the user", "It allows canvas rendering to be performed in a Web Worker, completely off the main UI thread, preventing frame drops and UI freezing", "It automatically compresses the canvas image", "It renders the canvas in 3D"],
    "correct_answer": "It allows canvas rendering to be performed in a Web Worker, completely off the main UI thread",
    "explanation": "Normally, drawing complex graphics on a `<canvas>` blocks the main thread, causing the UI to stutter. `OffscreenCanvas` moves the rendering context to a background Web Worker, keeping the main thread free for user interactions."
  },
  {
    "id": 84,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "topic": "WebGL Context",
    "question": "Fill in the blank to correctly request a WebGL rendering context from a canvas element.",
    "code_snippet": "const canvas = document.getElementById('myCanvas');\nconst gl = canvas._______('webgl2');",
    "options": ["getContext", "render", "init", "draw"],
    "correct_answer": "getContext",
    "explanation": "The `getContext()` method tells the browser what type of rendering engine you want to use. Passing `'webgl'` or `'webgl2'` returns the OpenGL ES context required to draw hardware-accelerated 3D graphics."
  },
  {
    "id": 85,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Web Animations API",
    "question": "What is the primary advantage of the Web Animations API over traditional CSS animations or JavaScript `requestAnimationFrame`?",
    "code_snippet": null,
    "options": ["It uses less memory", "It combines the high performance of CSS animations with the programmatic control of JavaScript, allowing you to pause, reverse, and seek animations via code", "It only works on mobile devices", "It automatically generates SVG paths"],
    "correct_answer": "It combines the high performance of CSS animations with the programmatic control of JavaScript",
    "explanation": "CSS animations are fast but hard to control dynamically. JS `requestAnimationFrame` is highly controllable but can cause performance drops. The Web Animations API gives you the best of both worlds, running on the browser's compositor thread."
  },
  {
    "id": 86,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "topic": "Web Animations API (Syntax)",
    "question": "Fill in the blank to correctly apply a native Web Animation to an element.",
    "code_snippet": "const animation = element._______([\n  { transform: 'translateY(0px)' },\n  { transform: 'translateY(100px)' }\n], {\n  duration: 1000,\n  iterations: Infinity\n});",
    "options": ["animate", "transition", "move", "keyframe"],
    "correct_answer": "animate",
    "explanation": "The `element.animate()` method takes an array of keyframes and a timing options object, returning an `Animation` object that you can use to call `.pause()`, `.play()`, or `.reverse()`."
  },
  {
    "id": 87,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Payment Request API",
    "question": "What does the Payment Request API allow web developers to do?",
    "code_snippet": null,
    "options": ["Process credit card numbers directly in the browser", "Invoke the browser's native, secure checkout UI to collect payment information (like saved credit cards or Apple Pay) with a single click", "Connect directly to the bank's database", "Generate cryptocurrency wallets"],
    "correct_answer": "Invoke the browser's native, secure checkout UI to collect payment information with a single click",
    "explanation": "The API doesn't process the payment itself; it securely collects the user's payment method details (which are stored in the browser/OS) and passes them to your backend server for processing, drastically reducing checkout friction."
  },
  {
    "id": 88,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Web Authentication (WebAuthn / Passkeys)",
    "question": "What is the Web Authentication API (WebAuthn), and how does it enable 'Passkeys'?",
    "code_snippet": null,
    "options": ["It stores passwords in localStorage", "It provides a standard way to authenticate users using biometrics (TouchID/FaceID) or hardware security keys, replacing traditional passwords with cryptographic public/private key pairs", "It encrypts the user's session cookie", "It generates CAPTCHAs"],
    "correct_answer": "It provides a standard way to authenticate users using biometrics or hardware security keys, replacing passwords with cryptographic keys",
    "explanation": "With WebAuthn, the server issues a challenge. The user's device (phone or laptop) signs the challenge using a private key stored securely in the device's enclave, and sends back the signature. The server verifies it with the public key. No passwords are ever transmitted or stored."
  },
  {
    "id": 89,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "topic": "Web Authentication (Credentials API)",
    "question": "Fill in the blank to correctly prompt the user to create a new Passkey/WebAuthn credential.",
    "code_snippet": "const credential = await navigator.credentials._______({\n  publicKey: {\n    challenge: new Uint8Array(32),\n    rp: { name: 'My App' },\n    user: { id: ..., name: 'user@example.com' }\n  }\n});",
    "options": ["create", "register", "new", "generate"],
    "correct_answer": "create",
    "explanation": "The `navigator.credentials.create()` method is used for registration (creating a new public/private key pair). To log in later, you use `navigator.credentials.get()` to request a signature."
  },
  {
    "id": 90,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Accessibility (Focus Trapping)",
    "question": "Why is 'Focus Trapping' a mandatory requirement when building a custom modal dialog in HTML/JS?",
    "code_snippet": null,
    "options": ["To make the modal load faster", "To prevent keyboard users from pressing 'Tab' and accidentally moving focus to the background page content behind the modal", "To hide the modal from screen readers", "To prevent the user from closing the modal"],
    "correct_answer": "To prevent keyboard users from pressing 'Tab' and accidentally moving focus to the background page content",
    "explanation": "When a modal opens, the user's context is entirely inside that modal. If focus escapes to the background, a blind user will be interacting with hidden elements, causing severe confusion. You must use JS to cycle focus only between the focusable elements inside the modal."
  },
  {
    "id": 91,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Accessibility (ARIA Live Regions)",
    "question": "What is the difference between `aria-live=\"polite\"` and `aria-live=\"assertive\"`?",
    "code_snippet": null,
    "options": ["There is no difference", "`polite` waits until the screen reader is finished speaking its current sentence before announcing the update; `assertive` immediately interrupts the screen reader to announce the update", "`assertive` is for visual alerts; `polite` is for audio", "`polite` is deprecated"],
    "correct_answer": "`polite` waits until the screen reader is finished speaking; `assertive` immediately interrupts the screen reader",
    "explanation": "Use `polite` for non-urgent updates (like a 'Search results updated' message). Use `assertive` only for critical, time-sensitive errors (like 'Payment failed' or 'Form submission error') where the user must know immediately."
  },
  {
    "id": 92,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "topic": "Accessibility (aria-current)",
    "question": "Fill in the blank to correctly indicate to a screen reader which link in a navigation menu represents the current page.",
    "code_snippet": "<nav>\n  <a href=\"/home\">Home</a>\n  <a href=\"/about\" aria-_______=\"page\">About</a>\n</nav>",
    "options": ["current", "active", "selected", "here"],
    "correct_answer": "current",
    "explanation": "`aria-current=\"page\"` tells assistive technology exactly where the user is within a set of related elements (like a breadcrumb trail, a pagination list, or a main navigation menu)."
  },
  {
    "id": 93,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Accessibility (Reduced Motion)",
    "question": "How should a web developer respect a user's OS-level preference to disable animations (e.g., to prevent motion sickness)?",
    "code_snippet": null,
    "options": ["By using JavaScript to detect the mouse speed", "By using the CSS media query `@media (prefers-reduced-motion: reduce)` to disable or simplify animations", "By adding a toggle button in the footer", "You cannot detect OS preferences"],
    "correct_answer": "By using the CSS media query `@media (prefers-reduced-motion: reduce)`",
    "explanation": "Users with vestibular disorders can experience severe nausea from parallax scrolling and complex transitions. Wrapping your CSS animations in this media query ensures you only serve heavy motion to users who haven't explicitly requested it to be turned off."
  },
  {
    "id": 94,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Accessibility (Color Contrast)",
    "question": "According to WCAG AA standards, what is the minimum contrast ratio required for normal body text against its background color?",
    "code_snippet": null,
    "options": ["2:1", "3:1", "4.5:1", "7:1"],
    "correct_answer": "4.5:1",
    "explanation": "A 4.5:1 ratio ensures that users with moderately low vision or color blindness can comfortably read the text. (Large text requires a slightly lower 3:1 ratio, while AAA compliance requires 7:1 for normal text)."
  },
  {
    "id": 95,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Modern HTML (Popover API)",
    "question": "What is the native HTML `popover` attribute, and what problem does it solve?",
    "code_snippet": null,
    "options": ["It creates a full-screen modal", "It allows you to create native, accessible tooltips, menus, and non-modal floating elements that automatically handle focus, z-index, and closing on outside clicks without writing JavaScript", "It hides elements from the DOM", "It compresses the HTML"],
    "correct_answer": "It allows you to create native, accessible floating elements that automatically handle focus, z-index, and outside clicks without JS",
    "explanation": "Before the Popover API, building a custom tooltip or dropdown required complex JavaScript to manage the 'top layer', trap focus, and listen for escape keys. The `popover` attribute gives you all of this natively in the browser."
  },
  {
    "id": 96,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "code-fill-in-blank",
    "topic": "Modern HTML (Popover Trigger)",
    "question": "Fill in the blank to correctly link a button to toggle a native HTML popover.",
    "code_snippet": "<button _______=\"my-tooltip\">Hover me</button>\n<div id=\"my-tooltip\" popover>This is the tooltip content</div>",
    "options": ["popovertarget", "target", "data-popover", "trigger"],
    "correct_answer": "popovertarget",
    "explanation": "The `popovertarget` attribute on a button or input tells the browser exactly which element (by its ID) to toggle when clicked. You can also use `popovertargetaction=\"show\"` or `\"hide\"` for specific behaviors."
  },
  {
    "id": 97,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Modern HTML (View Transitions API)",
    "question": "What does the View Transitions API allow web developers to do?",
    "code_snippet": null,
    "options": ["Translate text automatically", "Create smooth, animated transitions between different DOM states or across page navigations by capturing the old and new states as bitmaps and morphing them", "Compress CSS files", "Manage browser history"],
    "correct_answer": "Create smooth, animated transitions between different DOM states or page navigations",
    "explanation": "Historically, animating a layout change (like expanding a card into a full page) required complex FLIP JavaScript calculations. The View Transitions API lets the browser handle the heavy lifting, creating cinematic, app-like transitions natively."
  },
  {
    "id": 98,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Security (Subresource Integrity)",
    "question": "What does the `integrity` attribute do on a `<script>` or `<link>` tag?",
    "code_snippet": null,
    "options": ["It compresses the file", "It provides a cryptographic hash (SRI) that the browser uses to verify the downloaded file hasn't been tampered with or compromised by a CDN attack", "It makes the script load asynchronously", "It encrypts the script"],
    "correct_answer": "It provides a cryptographic hash that the browser uses to verify the downloaded file hasn't been tampered with",
    "explanation": "If you load a library from a public CDN (like cdnjs), a hacker could compromise that CDN and inject malicious code into the library. The `integrity=\"sha384-...\"` attribute ensures the browser will refuse to execute the file if its hash doesn't perfectly match the one you specified."
  },
  {
    "id": 99,
    "level": "intermediate",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Security (Content Security Policy)",
    "question": "How does a Content Security Policy (CSP) protect a website from Cross-Site Scripting (XSS)?",
    "code_snippet": null,
    "options": ["By encrypting the database", "By providing a whitelist of trusted sources for scripts, styles, and images, instructing the browser to block any inline scripts or unauthorized external resources", "By hiding the HTML source code", "By requiring a password to view the page"],
    "correct_answer": "By providing a whitelist of trusted sources, instructing the browser to block unauthorized scripts and resources",
    "explanation": "Even if an attacker manages to inject `<script>alert('hack')</script>` into your HTML, a strict CSP will tell the browser to ignore it because it wasn't loaded from an allowed, trusted domain. It is the ultimate safety net against XSS."
  },
  {
    "id": 100,
    "level": "advanced",
    "module_id": "html_mod_02_web_apis",
    "module_name": "Advanced HTML5 & Web APIs",
    "type": "conceptual",
    "topic": "Module 2 Wrap-up (The Modern Web Platform)",
    "question": "You have now completed the 60-question deep dive into Advanced HTML5 & Web APIs. What is the ultimate hallmark of a modern Web Platform Engineer?",
    "code_snippet": null,
    "options": ["Memorizing every CSS property", "Understanding that the browser is a powerful, secure, and standardized runtime; and knowing how to leverage native APIs for performance, accessibility, and security before reaching for heavy third-party JavaScript libraries", "Writing all logic in inline HTML attributes", "Avoiding the use of HTML entirely"],
    "correct_answer": "Understanding that the browser is a powerful, secure runtime; and knowing how to leverage native APIs before reaching for heavy JS libraries",
    "explanation": "The modern web platform provides native solutions for things we used to need massive libraries for: Popovers, View Transitions, WebAuthn, Intersection Observers, and Form Validation. A true expert uses the browser's built-in power first, resulting in faster, smaller, and more resilient applications. Congratulations on completing the HTML track!"
  }
]
