[
  {
    "id": 101,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Email HTML (Layout)",
    "question": "Why do email developers still use HTML `<table>` layouts instead of modern CSS Flexbox or Grid?",
    "code_snippet": null,
    "options": ["Tables load faster", "Many legacy email clients (especially Microsoft Outlook, which uses the Word rendering engine) do not support Flexbox or Grid, making tables the only reliable way to ensure consistent layouts", "Tables are required by the SMTP protocol", "CSS is completely blocked in all email clients"],
    "correct_answer": "Many legacy email clients (especially Outlook) do not support Flexbox or Grid, making tables the only reliable way to ensure consistent layouts",
    "explanation": "Email HTML is stuck in the past. To guarantee your email looks the same in Gmail, Apple Mail, and Outlook 2016, you must use nested tables for the structural layout, even though it feels like writing HTML in 1999."
  },
  {
    "id": 102,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Email HTML (Inline Styles)",
    "question": "Why is it a strict best practice to use inline CSS styles (e.g., `<td style=\"color: red;\">`) in HTML emails instead of a `<style>` block in the `<head>`?",
    "code_snippet": null,
    "options": ["Inline styles make the file size smaller", "Many email clients strip out `<style>` tags and `<head>` content for security reasons, so inline styles are the only way to guarantee your CSS is applied", "Inline styles load the email faster", "There is no difference"],
    "correct_answer": "Many email clients strip out `<style>` tags and `<head>` content for security reasons, so inline styles are the only way to guarantee your CSS is applied",
    "explanation": "Gmail, in particular, is notorious for stripping `<style>` blocks. While modern tools can automatically 'inline' your CSS before sending, the final HTML that reaches the inbox must have styles directly on the elements."
  },
  {
    "id": 103,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "code-fill-in-blank",
    "topic": "Email HTML (Accessibility Tables)",
    "question": "Fill in the blank to correctly tell screen readers that a table is being used purely for layout, not for tabular data.",
    "code_snippet": "<table role=\"_______\" width=\"100%\">",
    "options": ["presentation", "layout", "none", "structure"],
    "correct_answer": "presentation",
    "explanation": "If a screen reader encounters a standard `<table>`, it will announce 'Table, 3 columns, 5 rows' and try to read the data. `role=\"presentation\"` tells assistive technology to ignore the table structure and just read the text inside it linearly."
  },
  {
    "id": 104,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Email HTML (Preheader Text)",
    "question": "What is 'Preheader Text' in an HTML email, and how is it typically implemented?",
    "code_snippet": null,
    "options": ["The subject line of the email", "A short summary text that follows the subject line in the inbox preview, usually implemented as a hidden `<div>` or `<span>` at the very top of the email body", "The sender's name", "The unsubscribe link"],
    "explanation": "The preheader is the 'second subject line.' It is the snippet of text email clients display next to or below the subject line in the inbox. Developers often hide it visually using CSS (`display: none !important;` or `max-height: 0;`) but keep it in the HTML so clients can scrape it."
  },
  {
    "id": 105,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Email HTML (Dark Mode)",
    "question": "How can an email developer signal to email clients that their email supports Dark Mode natively?",
    "code_snippet": null,
    "options": ["By adding a `<meta name=\"dark-mode\">` tag", "By adding the `color-scheme: light dark;` CSS property to the `<meta>` tag or root styles, allowing the client to invert colors safely", "By using black backgrounds by default", "Dark mode is not supported in emails"],
    "correct_answer": "By adding the `color-scheme: light dark;` CSS property, allowing the client to invert colors safely",
    "explanation": "If you don't declare `color-scheme`, aggressive email clients (like Apple Mail) will forcefully invert your colors, often breaking your brand's design. Declaring it tells the client you have handled the dark mode styling yourself."
  },
  {
    "id": 106,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SVG (The viewBox Attribute)",
    "question": "In an `<svg>` element, what is the primary purpose of the `viewBox` attribute?",
    "code_snippet": null,
    "options": ["It sets the physical pixel size of the SVG on the screen", "It defines the internal coordinate system and aspect ratio, allowing the SVG to scale infinitely without distortion regardless of its CSS width/height", "It links the SVG to an external CSS file", "It enables JavaScript animations"],
    "correct_answer": "It defines the internal coordinate system and aspect ratio, allowing the SVG to scale infinitely without distortion",
    "explanation": "If `width` and `height` dictate how big the SVG is on the screen, `viewBox` dictates the 'canvas' the drawing exists on. A `viewBox=\"0 0 100 100\"` means your drawing coordinates go from 0 to 100, and the browser will map that perfectly to whatever CSS size you apply."
  },
  {
    "id": 107,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "code-fill-in-blank",
    "topic": "SVG (Path Data)",
    "question": "Fill in the blank with the SVG path command that moves the 'pen' to a new starting coordinate without drawing a line.",
    "code_snippet": "<path d=\"_______ 10 10 L 50 50 Z\" />",
    "options": ["M", "L", "C", "Z"],
    "correct_answer": "M",
    "explanation": "In SVG path data (`d` attribute), `M` stands for 'MoveTo' (lifts the pen), `L` is 'LineTo' (draws a line), `C` is 'CurveTo' (Bezier curve), and `Z` closes the path back to the start."
  },
  {
    "id": 108,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SVG (Inline vs Image Tag)",
    "question": "What is the massive advantage of embedding an SVG directly inline in the HTML (e.g., `<svg>...</svg>`) instead of using an `<img src=\"icon.svg\">`?",
    "code_snippet": null,
    "options": ["It reduces the HTTP requests to zero for that image", "It allows you to target and style the internal elements of the SVG (like paths and shapes) directly with external CSS and manipulate them with JavaScript", "It makes the SVG load faster", "It automatically animates the SVG"],
    "correct_answer": "It allows you to target and style the internal elements of the SVG directly with external CSS and JS",
    "explanation": "If you use `<img>`, the SVG is a black box; you cannot change the `fill` color of a specific path on hover using CSS. Inline SVG exposes the DOM tree of the graphic, making it fully styleable and scriptable."
  },
  {
    "id": 109,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SVG (Defs and Use)",
    "question": "What is the purpose of the `<defs>` and `<use>` elements in SVG?",
    "code_snippet": null,
    "options": ["To define CSS variables", "To define reusable graphical objects (like gradients or complex shapes) invisibly inside `<defs>`, and then stamp them onto the canvas multiple times using `<use>`", "To animate the SVG", "To add text to the SVG"],
    "correct_answer": "To define reusable graphical objects invisibly inside `<defs>`, and stamp them using `<use>`",
    "explanation": "If you have a complex icon that appears 50 times on a page, defining it once in `<defs id=\"my-icon\">` and calling it with `<use href=\"#my-icon\" />` 50 times drastically reduces the DOM size and HTML payload."
  },
  {
    "id": 110,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SVG (Accessibility)",
    "question": "How do you make a complex, informative SVG (like a chart or diagram) accessible to screen readers?",
    "code_snippet": null,
    "options": ["By adding an `alt` attribute to the `<svg>` tag", "By adding `<title>` and `<desc>` tags inside the SVG, and setting `role=\"img\"` and `aria-labelledby` on the root `<svg>` element", "By wrapping it in a `<div>`", "SVGs are automatically accessible"],
    "correct_answer": "By adding `<title>` and `<desc>` tags inside the SVG, and setting `role=\"img\"` and `aria-labelledby`",
    "explanation": "Unlike `<img>`, SVGs don't use the `alt` attribute. You must use the native SVG `<title>` (acts as the accessible name) and `<desc>` (acts as the description), and link them to the root element using ARIA."
  },
  {
    "id": 111,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "code-fill-in-blank",
    "topic": "Canvas (Getting Context)",
    "question": "Fill in the blank to correctly retrieve the 2D rendering context from an HTML5 canvas element.",
    "code_snippet": "const canvas = document.getElementById('myCanvas');\nconst ctx = canvas._______('2d');",
    "options": ["getContext", "render", "init", "draw"],
    "correct_answer": "getContext",
    "explanation": "The `<canvas>` element is just a blank container. You must call `getContext('2d')` (or 'webgl') to get the actual drawing API object that provides methods like `fillRect` and `stroke`."
  },
  {
    "id": 112,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Canvas (State Machine)",
    "question": "In the Canvas API, why is it critical to call `ctx.beginPath()` before drawing a new shape?",
    "code_snippet": null,
    "options": ["It clears the entire canvas", "It resets the current path, ensuring that new drawing commands (like `lineTo`) don't accidentally connect to and fill the previously drawn shapes", "It changes the stroke color", "It saves the canvas state"],
    "correct_answer": "It resets the current path, ensuring new commands don't accidentally connect to previously drawn shapes",
    "explanation": "Canvas is a state machine. If you draw a square, and then draw a triangle without calling `beginPath()`, Canvas will connect the last point of the square to the first point of the triangle, creating a messy, merged shape."
  },
  {
    "id": 113,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Canvas (Fill vs Stroke)",
    "question": "What is the difference between `ctx.fill()` and `ctx.stroke()`?",
    "code_snippet": null,
    "options": ["`fill()` draws the outline; `stroke()` colors the inside", "`fill()` paints the interior area of the current path with `fillStyle`; `stroke()` draws the outline/border of the path with `strokeStyle`", "They are the same", "`fill()` is for text; `stroke()` is for shapes"],
    "correct_answer": "`fill()` paints the interior area; `stroke()` draws the outline/border",
    "explanation": "You define the shape using `moveTo` and `lineTo`. Then, you call `fill()` to make it a solid shape, or `stroke()` to make it a wireframe outline. You can even call both to have a filled shape with a distinct border."
  },
  {
    "id": 114,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Canvas (Pixel Manipulation)",
    "question": "Which Canvas API method allows you to read the raw RGBA pixel data of a specific rectangular area of the canvas?",
    "code_snippet": null,
    "options": ["ctx.readPixels()", "ctx.getImageData()", "ctx.getPixelColor()", "ctx.scan()"],
    "correct_answer": "ctx.getImageData()",
    "explanation": "`getImageData(x, y, width, height)` returns an `ImageData` object containing a massive 1D array of pixels (Red, Green, Blue, Alpha). This is how you build custom image filters, color pickers, or computer vision effects in the browser."
  },
  {
    "id": 115,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Canvas (Animation Loop)",
    "question": "What is the standard browser API used to create a smooth, 60FPS animation loop on an HTML5 Canvas?",
    "code_snippet": null,
    "options": ["setInterval()", "setTimeout()", "requestAnimationFrame()", "canvas.animate()"],
    "correct_answer": "requestAnimationFrame()",
    "explanation": "`setInterval` is tied to the screen's refresh rate and can cause stuttering. `requestAnimationFrame` syncs perfectly with the browser's rendering cycle (usually 60 or 120 times a second), pausing automatically when the tab is hidden to save battery."
  },
  {
    "id": 116,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Canvas (Transformations)",
    "question": "If you call `ctx.translate(50, 50)` and then draw a rectangle at `(0, 0)`, where will the rectangle actually appear on the canvas?",
    "code_snippet": null,
    "options": ["At the exact top-left corner (0,0) of the canvas", "At 50px from the left and 50px from the top, because the entire coordinate system has been shifted", "It will not render", "It will be scaled by 50"],
    "correct_answer": "At 50px from the left and 50px from the top, because the entire coordinate system has been shifted",
    "explanation": "Canvas transformations (`translate`, `rotate`, `scale`) don't move the object; they move the 'origin point' (0,0) of the canvas grid itself. All subsequent drawing commands are relative to this new origin."
  },
  {
    "id": 117,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Canvas (State Stack)",
    "question": "How do you safely apply a temporary transformation (like a rotation) to a single shape without affecting the rest of the canvas?",
    "code_snippet": null,
    "options": ["By calling `ctx.reset()`", "By calling `ctx.save()` before the transformation, and `ctx.restore()` after drawing the shape", "By clearing the canvas", "By using a separate `<canvas>` element"],
    "correct_answer": "By calling `ctx.save()` before the transformation, and `ctx.restore()` after drawing the shape",
    "explanation": "`save()` pushes the current canvas state (styles, transformations, clipping) onto a stack. `restore()` pops it off, instantly reverting the canvas back to exactly how it was before the `save()`. It's like Ctrl+Z for the canvas state."
  },
  {
    "id": 118,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "code-fill-in-blank",
    "topic": "Canvas (Drawing Text)",
    "question": "Fill in the blank to correctly render solid text on a canvas at coordinates (10, 50).",
    "code_snippet": "ctx.font = '20px Arial';\nctx._______('Hello World', 10, 50);",
    "options": ["fillText", "strokeText", "drawText", "renderText"],
    "correct_answer": "fillText",
    "explanation": "`fillText` draws solid text using the current `fillStyle`. `strokeText` draws only the outline of the text using the `strokeStyle`. Both take the text string, X, and Y coordinates."
  },
  {
    "id": 119,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SVG vs Canvas (When to use which)",
    "question": "When building a complex, interactive data visualization with 10,000 individual data points, why is `<canvas>` generally preferred over `<svg>`?",
    "code_snippet": null,
    "options": ["Canvas has better SEO", "SVG requires a DOM node for every single shape, which causes massive memory overhead and rendering lag at 10,000 elements; Canvas draws pixels directly to a bitmap, handling millions of shapes effortlessly", "Canvas supports CSS styling better", "SVG does not support colors"],
    "correct_answer": "SVG requires a DOM node for every shape, causing massive overhead; Canvas draws pixels directly, handling millions of shapes effortlessly",
    "explanation": "SVG is Retained Mode (keeps a model of every shape in the DOM). Canvas is Immediate Mode (just paints pixels and forgets them). For massive scale (games, particle effects, huge charts), Canvas is vastly superior for performance."
  },
  {
    "id": 120,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've covered the dark arts of Email HTML, the vector precision of SVG, and the pixel power of Canvas. What is the core takeaway regarding HTML graphics?",
    "code_snippet": null,
    "options": ["Always use Canvas for everything", "Always use SVG for everything", "Choose the right tool for the job: SVG for scalable, accessible, styleable UI graphics; Canvas for high-performance, pixel-heavy, immediate-mode rendering; and Tables for the unforgiving world of Email", "HTML cannot handle graphics"],
    "correct_answer": "Choose the right tool for the job: SVG for scalable UI graphics; Canvas for high-performance rendering; and Tables for Email",
    "explanation": "The modern web provides incredibly powerful, native graphical engines. Understanding the architectural differences between Retained (SVG) and Immediate (Canvas) rendering, and respecting the legacy constraints of Email clients, separates a junior developer from a true web platform expert."
  }
]
[
  {
    "id": 121,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Custom Elements (Naming Rule)",
    "question": "What is the strict naming convention required when defining a Custom Element (Web Component) in HTML?",
    "code_snippet": null,
    "options": ["It must start with an uppercase letter", "It must contain a hyphen (e.g., `<my-button>`, `<app-header>`), cannot be a single word, and must be lowercase", "It must start with 'x-'", "There are no naming rules"],
    "correct_answer": "It must contain a hyphen, cannot be a single word, and must be lowercase",
    "explanation": "The hyphen requirement ensures that custom elements will never collide with current or future standard HTML tags (which are always single words like `<div>`, `<button>`, `<section>`). The browser uses the hyphen as the signal that this is a custom element."
  },
  {
    "id": 122,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "code-fill-in-blank",
    "topic": "Custom Elements (Registration)",
    "question": "Fill in the blank to correctly register a Custom Element with the browser.",
    "code_snippet": "class MyButton extends HTMLElement {\n  constructor() { super(); }\n}\n\ncustomElements._______('my-button', MyButton);",
    "options": ["register", "define", "create", "add"],
    "correct_answer": "define",
    "explanation": "`customElements.define()` takes the tag name (with hyphen) and the class that extends `HTMLElement`. After this call, every `<my-button>` in the DOM will automatically be upgraded to an instance of your class."
  },
  {
    "id": 123,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Custom Elements (Lifecycle Callbacks)",
    "question": "Which lifecycle callback is triggered when a Custom Element is inserted into the DOM?",
    "code_snippet": null,
    "options": ["createdCallback()", "connectedCallback()", "mounted()", "onLoad()"],
    "correct_answer": "connectedCallback()",
    "explanation": "The four lifecycle callbacks are: `connectedCallback()` (added to DOM), `disconnectedCallback()` (removed from DOM), `adoptedCallback()` (moved to a new document), and `attributeChangedCallback()` (an observed attribute changes). These mirror React's mount/unmount lifecycle."
  },
  {
    "id": 124,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Shadow DOM (Encapsulation)",
    "question": "What happens when you attach a Shadow DOM to a Custom Element using `this.attachShadow({ mode: 'open' })`?",
    "code_snippet": null,
    "options": ["The element becomes invisible", "A completely isolated DOM tree is created inside the element; external CSS cannot leak in, and internal styles cannot leak out", "The element is removed from the accessibility tree", "The element becomes a global singleton"],
    "correct_answer": "A completely isolated DOM tree is created; external CSS cannot leak in, and internal styles cannot leak out",
    "explanation": "Shadow DOM is the ultimate CSS encapsulation. You can write `button { color: red; }` inside the Shadow DOM and it will ONLY affect buttons inside your component, not any buttons on the rest of the page. `mode: 'open'` allows JS access via `element.shadowRoot`."
  },
  {
    "id": 125,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Shadow DOM (CSS Parts)",
    "question": "Since Shadow DOM blocks external CSS, how can a component author allow consumers to style specific internal elements?",
    "code_snippet": null,
    "options": ["By using `!important`", "By using the `::part()` CSS pseudo-element, which exposes specific internal elements for external styling", "By removing the Shadow DOM", "By using inline styles only"],
    "correct_answer": "By using the `::part()` CSS pseudo-element, which exposes specific internal elements for external styling",
    "explanation": "Inside the component, you mark an element with `part=\"header\"`. The consumer can then style it from outside using `my-component::part(header) { color: blue; }`. This provides controlled, intentional style extensibility without breaking encapsulation."
  },
  {
    "id": 126,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Shadow DOM (CSS Custom Properties)",
    "question": "What is the one CSS feature that CAN cross the Shadow DOM boundary from the outside in?",
    "code_snippet": null,
    "options": ["Class selectors", "CSS Custom Properties (CSS Variables like `--primary-color`)", "ID selectors", "Media queries"],
    "correct_answer": "CSS Custom Properties (CSS Variables like `--primary-color`)",
    "explanation": "CSS Variables inherit through the Shadow DOM boundary. This is the primary theming mechanism for Web Components. A consumer sets `--button-bg: blue` on the page, and the component reads `background: var(--button-bg)` inside its Shadow DOM."
  },
  {
    "id": 127,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Slots (Named vs Default)",
    "question": "What is the difference between a default `<slot>` and a named `<slot name=\"header\">`?",
    "code_snippet": null,
    "options": ["Named slots are faster", "A default slot captures all light DOM children that don't have a `slot` attribute; a named slot only captures children with a matching `slot=\"header\"` attribute", "Default slots are deprecated", "Named slots only work with text"],
    "correct_answer": "A default slot captures all unassigned children; a named slot captures children with a matching `slot` attribute",
    "explanation": "This enables powerful composition. A `<my-card>` component can have `<slot name=\"header\">`, `<slot name=\"body\">`, and `<slot name=\"footer\">`, allowing the consumer to inject different content into each specific area of the card."
  },
  {
    "id": 128,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Custom Elements (Observed Attributes)",
    "question": "How does a Custom Element react to attribute changes (e.g., `<my-button disabled>`)?",
    "code_snippet": null,
    "options": ["It automatically re-renders", "You must define a static `observedAttributes` getter listing the attributes to watch, and implement `attributeChangedCallback(name, oldVal, newVal)` to handle changes", "Attributes cannot be observed", "It requires a MutationObserver"],
    "correct_answer": "You must define `observedAttributes` and implement `attributeChangedCallback`",
    "explanation": "Unlike React, Custom Elements don't automatically react to prop changes. You explicitly declare which attributes to observe, and the browser calls your callback whenever one of those attributes is added, removed, or changed."
  },
  {
    "id": 129,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Web Audio API (Concept)",
    "question": "What is the Web Audio API, and how does it differ from the `<audio>` HTML element?",
    "code_snippet": null,
    "options": ["They are the same", "The Web Audio API provides a powerful, low-level system for generating, processing, and analyzing audio in real-time using an audio graph of nodes, far beyond simple playback", "The Web Audio API only works with MIDI", "The `<audio>` element is deprecated"],
    "correct_answer": "The Web Audio API provides a low-level system for generating, processing, and analyzing audio in real-time using an audio graph of nodes",
    "explanation": "The `<audio>` tag is like a simple music player. The Web Audio API is a full digital audio workstation in the browser. You can create oscillators, apply filters, add reverb, visualize waveforms, and build synthesizers entirely in code."
  },
  {
    "id": 130,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Web Audio API (AudioContext)",
    "question": "Why must an `AudioContext` be created or resumed inside a user gesture (like a click event)?",
    "code_snippet": null,
    "options": ["Because audio files are large", "Because browsers enforce an autoplay policy to prevent websites from playing unexpected, annoying audio without the user's explicit consent", "Because the AudioContext requires a GPU", "Because audio processing is CPU-intensive"],
    "correct_answer": "Because browsers enforce an autoplay policy to prevent websites from playing unexpected audio without user consent",
    "explanation": "If you try to create and start an `AudioContext` on page load, the browser will suspend it. You must call `audioContext.resume()` inside a click or keypress handler to 'unlock' audio playback, ensuring the user intended to hear sound."
  },
  {
    "id": 131,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Web MIDI API",
    "question": "What does the Web MIDI API allow a web application to do?",
    "code_snippet": null,
    "options": ["Play MP3 files", "Send and receive MIDI messages to/from external hardware instruments (like keyboards, drum pads, and synthesizers) connected via USB", "Edit video files", "Generate 3D graphics"],
    "correct_answer": "Send and receive MIDI messages to/from external hardware instruments connected via USB",
    "explanation": "The Web MIDI API turns the browser into a music production tool. You can connect a physical MIDI keyboard, read the note-on/note-off messages in real-time, and trigger sounds using the Web Audio API—all without installing any drivers or software."
  },
  {
    "id": 132,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "WebUSB API",
    "question": "What does the WebUSB API enable, and what security restriction does it enforce?",
    "code_snippet": null,
    "options": ["It allows websites to access any USB device automatically", "It allows web apps to communicate directly with USB devices (like Arduino boards or 3D printers), but requires explicit user permission via a device picker dialog", "It replaces Bluetooth", "It only works with flash drives"],
    "correct_answer": "It allows web apps to communicate directly with USB devices, but requires explicit user permission via a device picker dialog",
    "explanation": "WebUSB eliminates the need to install native drivers or companion apps. A web-based Arduino IDE can flash code directly to a board. The browser's permission dialog ensures a malicious site can't silently access your USB devices."
  },
  {
    "id": 133,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Web Bluetooth API",
    "question": "What is a real-world use case for the Web Bluetooth API?",
    "code_snippet": null,
    "options": ["Streaming music to speakers", "Connecting a web app to a Bluetooth Low Energy (BLE) device like a heart rate monitor, smart thermometer, or IoT sensor without installing a native app", "Replacing WiFi", "Pairing keyboards"],
    "correct_answer": "Connecting a web app to a BLE device like a heart rate monitor or IoT sensor without installing a native app",
    "explanation": "Web Bluetooth uses the GATT protocol to read/write characteristics from BLE devices. This enables 'app-less' experiences: a user can visit a website and instantly read their glucose monitor or configure a smart light bulb."
  },
  {
    "id": 134,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Advanced Canvas (Compositing)",
    "question": "What does the `globalCompositeOperation` property control in the Canvas API?",
    "code_snippet": null,
    "options": ["The canvas resolution", "How new shapes are blended with existing content on the canvas (e.g., 'source-over', 'multiply', 'screen', 'destination-out')", "The canvas background color", "The animation frame rate"],
    "correct_answer": "How new shapes are blended with existing content on the canvas",
    "explanation": "This is the Canvas equivalent of Photoshop's layer blend modes. Setting `globalCompositeOperation = 'destination-out'` turns your brush into an eraser. Setting it to `'multiply'` creates darkening overlay effects."
  },
  {
    "id": 135,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Advanced Canvas (Clipping)",
    "question": "What does `ctx.clip()` do in the Canvas API?",
    "code_snippet": null,
    "options": ["It cuts the canvas in half", "It restricts all future drawing operations to the area inside the current path, acting as a mask", "It copies the canvas to the clipboard", "It compresses the image"],
    "correct_answer": "It restricts all future drawing operations to the area inside the current path, acting as a mask",
    "explanation": "If you draw a circle and call `clip()`, everything you draw afterward will only be visible inside that circle. This is how you create circular profile pictures, reveal animations, or complex masked effects."
  },
  {
    "id": 136,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Advanced Canvas (HiDPI / Retina)",
    "question": "Why do Canvas drawings often appear blurry on Retina/HiDPI displays, and how do you fix it?",
    "code_snippet": null,
    "options": ["Because Canvas doesn't support high resolution", "Because the canvas's internal pixel buffer (width/height attributes) defaults to CSS pixels, not device pixels; you must scale the canvas buffer by `window.devicePixelRatio`", "Because CSS blurs the canvas", "Because the browser compresses the canvas"],
    "correct_answer": "Because the canvas buffer defaults to CSS pixels; you must scale it by `window.devicePixelRatio`",
    "explanation": "On a 2x Retina display, a 400x400 CSS pixel canvas needs an 800x800 internal buffer to look sharp. You set `canvas.width = 400 * devicePixelRatio`, then `ctx.scale(devicePixelRatio, devicePixelRatio)` to compensate."
  },
  {
    "id": 137,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "HTML (The <noscript> Element)",
    "question": "When is the content inside a `<noscript>` tag displayed to the user?",
    "code_snippet": null,
    "options": ["Always", "Only when JavaScript is disabled or blocked in the user's browser", "Only on mobile devices", "Only when the page is offline"],
    "correct_answer": "Only when JavaScript is disabled or blocked in the user's browser",
    "explanation": "The `<noscript>` tag provides a graceful fallback for the small percentage of users who disable JavaScript or use strict privacy tools like NoScript. It is commonly used to display a message asking the user to enable JS."
  },
  {
    "id": 138,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "HTML (The <wbr> Element)",
    "question": "What does the `<wbr>` (Word Break Opportunity) tag do?",
    "code_snippet": null,
    "options": ["It forces a line break", "It suggests to the browser a safe point where a long word or URL can break onto the next line if needed, without forcing a break", "It wraps text in a box", "It makes text bold"],
    "correct_answer": "It suggests a safe point where a long word can break onto the next line if needed",
    "explanation": "If you have a long URL like `https://example.com/very/long/path`, the browser might break it awkwardly. Inserting `<wbr>` at logical points (like after slashes) tells the browser where it's safe to wrap the text."
  },
  {
    "id": 139,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "HTML (The <time> Element)",
    "question": "What is the semantic purpose of the `<time>` element?",
    "code_snippet": null,
    "options": ["To display a live clock", "To represent a specific date, time, or duration in a machine-readable format (via the `datetime` attribute) while displaying human-readable text", "To create a countdown timer", "To schedule JavaScript events"],
    "correct_answer": "To represent a date/time in a machine-readable format while displaying human-readable text",
    "explanation": "`<time datetime=\"2024-12-25\">Christmas Day</time>` shows 'Christmas Day' to humans, but search engines and calendar apps can parse the exact ISO date from the `datetime` attribute, enabling rich snippets and event detection."
  },
  {
    "id": 140,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (The Extensible Web)",
    "question": "You've covered Web Components, Web Audio, WebUSB, and advanced Canvas. What is the overarching philosophy of the 'Extensible Web' movement?",
    "code_snippet": null,
    "options": ["To make HTML as complex as possible", "To expose low-level browser capabilities (hardware, audio, graphics, networking) as standardized web APIs, empowering developers to build native-quality applications entirely within the browser", "To replace JavaScript with WebAssembly", "To eliminate the need for servers"],
    "correct_answer": "To expose low-level browser capabilities as standardized web APIs, empowering developers to build native-quality applications entirely within the browser",
    "explanation": "The Extensible Web Manifesto argues that the browser should provide the 'primitives' (low-level APIs), and developers should build the 'frameworks' on top. This is why we now have WebGPU, WebAudio, WebUSB, and Web Components—the browser is becoming a full operating system."
  }
]
[
  {
    "id": 141,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SEO (Sitemaps)",
    "question": "What is the purpose of a `sitemap.xml` file, and when is it absolutely critical for a website?",
    "code_snippet": null,
    "options": ["It styles the website for search engines", "It provides a structured map of all important URLs, helping search engine crawlers discover and index pages efficiently; it is critical for large sites or sites with poor internal linking", "It blocks bots from scraping the site", "It translates the HTML into multiple languages"],
    "correct_answer": "It provides a structured map of all important URLs, helping search engine crawlers discover and index pages efficiently",
    "explanation": "While search engines are smart, a sitemap acts as a guaranteed roadmap. If you have a massive e-commerce site or a site where pages aren't heavily linked to each other, the sitemap ensures Google knows every single page exists."
  },
  {
    "id": 142,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SEO (Robots.txt)",
    "question": "What is the function of the `robots.txt` file located at the root of a domain?",
    "code_snippet": null,
    "options": ["It encrypts the website", "It provides instructions to well-behaved web crawlers about which parts of the site they are allowed or disallowed from accessing", "It forces the browser to cache the site", "It redirects users to a login page"],
    "correct_answer": "It provides instructions to web crawlers about which parts of the site they are allowed or disallowed from accessing",
    "explanation": "Using directives like `Disallow: /admin/`, you can politely ask search engine bots not to crawl sensitive or duplicate areas of your site, saving crawl budget and keeping private routes out of search results."
  },
  {
    "id": 143,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "SEO (noindex vs robots.txt)",
    "question": "What is the critical difference between blocking a page in `robots.txt` and using the `<meta name=\"robots\" content=\"noindex\">` tag?",
    "code_snippet": null,
    "options": ["They do the exact same thing", "`robots.txt` prevents the bot from crawling the page (so it might still be indexed if linked elsewhere); `noindex` allows crawling but explicitly forbids the page from appearing in search results", "`noindex` is for images; `robots.txt` is for text", "`robots.txt` is deprecated"],
    "correct_answer": "`robots.txt` prevents crawling; `noindex` allows crawling but forbids indexing",
    "explanation": "If you block a page in `robots.txt`, Google can't read the `noindex` meta tag! The page might still appear in search results as a 'URL without content'. To guarantee a page is removed from search results, you MUST allow crawling and use the `noindex` meta tag."
  },
  {
    "id": 144,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Performance (Cumulative Layout Shift)",
    "question": "How does properly defining the `width` and `height` attributes on `<img>` and `<video>` tags directly improve the Cumulative Layout Shift (CLS) Core Web Vital?",
    "code_snippet": null,
    "options": ["It makes the images load faster", "It allows the browser to calculate the aspect ratio and reserve the exact correct amount of space before the image downloads, preventing the layout from jumping when the image finally renders", "It compresses the image file", "It enables lazy loading"],
    "correct_answer": "It allows the browser to calculate the aspect ratio and reserve space, preventing the layout from jumping",
    "explanation": "CLS measures visual stability. If an image lacks dimensions, the browser renders the text below it immediately. When the image finally loads, it pushes the text down, causing a jarring 'shift' that ruins the UX and tanks your SEO score."
  },
  {
    "id": 145,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Accessibility (The POUR Principles)",
    "question": "What are the four foundational principles of the WCAG (Web Content Accessibility Guidelines), often abbreviated as POUR?",
    "code_snippet": null,
    "options": ["Performance, Operability, Usability, Reliability", "Perceivable, Operable, Understandable, Robust", "Progressive, Open, Universal, Responsive", "Private, Open, Universal, Resilient"],
    "correct_answer": "Perceivable, Operable, Understandable, Robust",
    "explanation": "Content must be Perceivable (alt text, captions), Operable (keyboard accessible), Understandable (clear language, predictable UI), and Robust (compatible with assistive technologies). This is the bible of web accessibility."
  },
  {
    "id": 146,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Security (Clickjacking)",
    "question": "How do you protect your HTML website from 'Clickjacking' attacks, where a malicious site embeds yours in an invisible iframe to trick users into clicking buttons?",
    "code_snippet": null,
    "options": ["By disabling JavaScript", "By setting the `X-Frame-Options: DENY` HTTP header or using the `frame-ancestors` directive in your Content Security Policy (CSP)", "By adding a CAPTCHA to every page", "By using HTTPS only"],
    "correct_answer": "By setting the `X-Frame-Options: DENY` HTTP header or using the `frame-ancestors` CSP directive",
    "explanation": "These headers instruct the browser to refuse to render your page inside any `<iframe>`, `<object>`, or `<embed>` tag on a different domain, completely neutralizing the clickjacking overlay attack."
  },
  {
    "id": 147,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Web Standards (WHATWG vs W3C)",
    "question": "Historically, the W3C maintained HTML. Today, which organization is the sole maintainer of the HTML standard, and what is its publishing model?",
    "code_snippet": null,
    "options": ["The W3C; they publish versioned snapshots (HTML5, HTML6)", "The WHATWG (Web Hypertext Application Technology Working Group); they maintain HTML as a 'Living Standard' that is continuously updated without version numbers", "Google; they publish annual updates", "The UN; they publish decadal updates"],
    "correct_answer": "The WHATWG; they maintain HTML as a 'Living Standard' continuously updated without version numbers",
    "explanation": "In 2019, the W3C officially surrendered HTML to the WHATWG. 'HTML5' is no longer a version; it's just 'HTML'. The standard is a living document that evolves weekly based on browser consensus and real-world developer needs."
  },
  {
    "id": 148,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Future of HTML (Declarative Shadow DOM)",
    "question": "What problem does 'Declarative Shadow DOM' (DSR) solve for Web Components in Server-Side Rendering (SSR)?",
    "code_snippet": null,
    "options": ["It makes Web Components load faster on mobile", "It allows the Shadow DOM structure to be serialized directly in the initial HTML payload, preventing the Flash of Unstyled Content (FOUC) before JavaScript hydrates the component", "It removes the need for CSS", "It allows Shadow DOM to be accessed by external scripts"],
    "correct_answer": "It allows the Shadow DOM structure to be serialized in the initial HTML, preventing FOUC before JS hydrates",
    "explanation": "Previously, SSR Web Components rendered as empty shells until JS downloaded and ran `attachShadow()`. DSR introduces a `<template shadowroot=\"open\">` tag, allowing the server to send the fully styled Shadow DOM in the raw HTML, ensuring instant, flicker-free rendering."
  },
  {
    "id": 149,
    "level": "intermediate",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "Web Philosophy (Progressive Enhancement)",
    "question": "What is the core philosophy of 'Progressive Enhancement' in web development?",
    "code_snippet": null,
    "options": ["Building the site entirely in JavaScript for maximum performance", "Starting with a solid, accessible HTML baseline that works for everyone, then layering on CSS and JavaScript to enhance the experience for modern browsers and capable devices", "Only supporting the latest version of Chrome", "Disabling features for older browsers"],
    "correct_answer": "Starting with a solid, accessible HTML baseline, then layering on CSS and JS to enhance the experience",
    "explanation": "If JavaScript fails, or a user is on a slow network, the core content (the HTML) is still readable and functional. You don't build a fragile house of cards; you build a solid foundation and add decorations on top."
  },
  {
    "id": 150,
    "level": "advanced",
    "module_id": "html_mod_03_specialized_html",
    "module_name": "Specialized HTML, Graphics & Email",
    "type": "conceptual",
    "topic": "The Ultimate Milestone (The Zen of the Web)",
    "question": "You have now completed the HTML track and hit the 3,000 question milestone. What is the ultimate 'Zen' of mastering HTML and the Web Platform?",
    "code_snippet": null,
    "options": ["Memorizing every single HTML tag and attribute", "Understanding that HTML is not just markup, but the semantic, accessible, and resilient foundation of the entire digital world; and respecting the separation of concerns between structure (HTML), presentation (CSS), and behavior (JS)", "Replacing HTML with WebAssembly", "Writing all CSS inline"],
    "correct_answer": "Understanding that HTML is the semantic, accessible foundation of the digital world; and respecting the separation of concerns between structure, presentation, and behavior",
    "explanation": "Frameworks come and go. React, Vue, Angular, Svelte—they are all just tools that ultimately compile down to the exact same thing: HTML, CSS, and JS. Mastering the raw, native web platform makes you a master of the underlying engine that powers the entire internet. Congratulations on this monumental achievement!"
  }
]
