[
  {
    "id": 1,
    "level": "beginner",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP Tags",
    "question": "What is the correct way to start a PHP code block?",
    "code_snippet": null,
    "options": ["<php>", "<?php", "<script language=\"php\">", "<?"],
    "correct_answer": "<?php",
    "explanation": "The standard opening tag is `<?php`. While `<?` (short open tag) exists, it's discouraged as it requires specific server configuration and can conflict with XML declarations. Always use `<?php` for maximum compatibility."
  },
  {
    "id": 2,
    "level": "beginner",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Variables",
    "question": "Fill in the blank to correctly declare a variable in PHP.",
    "code_snippet": "_______ $name = \"John\";",
    "options": ["var", "let", "const", "$"],
    "correct_answer": "$",
    "explanation": "In PHP, all variables must start with a `$` sign followed by the variable name. Unlike JavaScript, you don't use `let`, `const`, or `var` keywords."
  },
  {
    "id": 3,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Variable Variables",
    "question": "What does the syntax `$$variable` (variable variables) do in PHP?",
    "code_snippet": null,
    "options": ["It creates a reference to the variable", "It uses the value of `$variable` as the name of another variable", "It doubles the value of the variable", "It creates a constant"],
    "correct_answer": "It uses the value of `$variable` as the name of another variable",
    "explanation": "If `$var = 'foo'` and `$$var = 'bar'`, then `$foo` equals 'bar'. This is rarely used in modern PHP and is generally considered bad practice as it makes code harder to read and debug."
  },
  {
    "id": 4,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Arrays (Indexed vs Associative)",
    "question": "What is the difference between an indexed array and an associative array in PHP?",
    "code_snippet": null,
    "options": ["Indexed arrays use numeric keys starting from 0; associative arrays use string keys", "Associative arrays are faster", "Indexed arrays can only store strings", "There is no difference"],
    "correct_answer": "Indexed arrays use numeric keys starting from 0; associative arrays use string keys",
    "explanation": "PHP arrays are actually ordered maps. `$arr = [1, 2, 3]` is indexed (keys 0, 1, 2). `$arr = ['name' => 'John', 'age' => 30]` is associative. PHP automatically converts between them, which can sometimes cause unexpected behavior."
  },
  {
    "id": 5,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Array Functions",
    "question": "Fill in the blank with the PHP function that adds an element to the end of an array.",
    "code_snippet": "$arr = [1, 2, 3];\n_______($arr, 4);\n// $arr is now [1, 2, 3, 4]",
    "options": ["array_push", "array_unshift", "array_pop", "array_shift"],
    "correct_answer": "array_push",
    "explanation": "`array_push()` adds elements to the end of an array. `array_unshift()` adds to the beginning. `array_pop()` removes from the end. `array_shift()` removes from the beginning."
  },
  {
    "id": 6,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Strict vs Loose Comparison",
    "question": "What is the difference between `==` and `===` in PHP?",
    "code_snippet": null,
    "options": ["`==` compares values with type juggling; `===` compares both value AND type strictly", "`===` is deprecated", "`==` is faster", "There is no difference"],
    "correct_answer": "`==` compares values with type juggling; `===` compares both value AND type strictly",
    "explanation": "`'5' == 5` is true (PHP converts string to number). `'5' === 5` is false (different types). Always prefer `===` and `!==` to avoid unexpected type coercion bugs."
  },
  {
    "id": 7,
    "level": "beginner",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Superglobals ($_GET)",
    "question": "Fill in the blank to correctly access a URL query parameter named 'id' in PHP.",
    "code_snippet": "$id = _______['id'];",
    "options": ["$_GET", "$_POST", "$_REQUEST", "$_QUERY"],
    "correct_answer": "$_GET",
    "explanation": "`$_GET` is a superglobal array containing URL query parameters (e.g., `page.php?id=5`). `$_POST` contains form data submitted via POST. `$_REQUEST` contains both GET, POST, and COOKIE data combined."
  },
  {
    "id": 8,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Security (SQL Injection)",
    "question": "Why is directly inserting `$_GET` or `$_POST` variables into SQL queries dangerous?",
    "code_snippet": null,
    "options": ["It makes the query slower", "It allows SQL Injection attacks where malicious users can manipulate the database", "PHP doesn't support GET/POST in SQL", "It causes syntax errors"],
    "correct_answer": "It allows SQL Injection attacks where malicious users can manipulate the database",
    "explanation": "Never do `$db->query(\"SELECT * FROM users WHERE id = \" . $_GET['id'])`. A user could pass `id=1 OR 1=1` to dump your entire database. Always use prepared statements with parameterized queries."
  },
  {
    "id": 9,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Sessions",
    "question": "Fill in the blank to correctly start a PHP session.",
    "code_snippet": "_______();\n$_SESSION['user'] = 'John';",
    "options": ["session_start", "start_session", "session_begin", "init_session"],
    "correct_answer": "session_start",
    "explanation": "`session_start()` must be called before any output is sent to the browser. It initializes the session or resumes the current one based on the session identifier passed via a GET or POST request, or passed via a cookie."
  },
  {
    "id": 10,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Cookies",
    "question": "How do you set a cookie in PHP that expires in 1 hour?",
    "code_snippet": null,
    "options": ["`setcookie('name', 'value', time() + 3600)`", "`cookie_set('name', 'value', 3600)`", "`$_COOKIE['name'] = 'value'`", "`set_cookie('name', 'value', '+1 hour')`"],
    "correct_answer": "`setcookie('name', 'value', time() + 3600)`",
    "explanation": "`setcookie()` must be called before any output. The third parameter is the expiration timestamp. `time() + 3600` sets it to expire in 1 hour (3600 seconds). Unlike sessions, cookies are stored on the client's browser."
  },
  {
    "id": 11,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Include vs Require",
    "question": "What is the difference between `include` and `require` in PHP?",
    "code_snippet": null,
    "options": ["`include` produces a warning if the file is missing; `require` produces a fatal error and stops script execution", "`require` is faster", "`include` can only be used once", "There is no difference"],
    "correct_answer": "`include` produces a warning if the file is missing; `require` produces a fatal error",
    "explanation": "Use `require` for essential files (like configuration or database connections) that must exist. Use `include` for optional files (like templates) where the script can continue even if the file is missing."
  },
  {
    "id": 12,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Functions (Return Types)",
    "question": "Fill in the blank to correctly declare a function with a return type hint in PHP.",
    "code_snippet": "function add(int $a, int $b): _______ {\n    return $a + $b;\n}",
    "options": ["int", "integer", "void", "return"],
    "correct_answer": "int",
    "explanation": "PHP 7+ supports return type declarations. `: int` tells PHP this function must return an integer. If it returns something else, a TypeError is thrown. Other types include `string`, `bool`, `array`, `float`, and `void`."
  },
  {
    "id": 13,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Null Coalescing Operator",
    "question": "What does the null coalescing operator `??` do in PHP?",
    "code_snippet": null,
    "options": ["It concatenates two strings", "It returns the first operand if it exists and is not null; otherwise returns the second operand", "It checks if a variable is set", "It merges two arrays"],
    "correct_answer": "It returns the first operand if it exists and is not null; otherwise returns the second operand",
    "explanation": "`$username = $_GET['user'] ?? 'guest'` is equivalent to `isset($_GET['user']) ? $_GET['user'] : 'guest'`. It's a concise way to provide default values for potentially undefined variables."
  },
  {
    "id": 14,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Type Juggling",
    "question": "What is the result of this comparison in PHP: `'0' == false`?",
    "code_snippet": null,
    "options": ["false", "true", "null", "It throws an error"],
    "correct_answer": "true",
    "explanation": "PHP's loose comparison (`==`) performs type juggling. The string `'0'` is converted to integer 0, which equals false. This is why you should always use `===` for comparisons to avoid these unexpected behaviors."
  },
  {
    "id": 15,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Heredoc and Nowdoc",
    "question": "What is the difference between Heredoc and Nowdoc syntax in PHP?",
    "code_snippet": null,
    "options": ["Heredoc parses variables; Nowdoc treats the string literally like single quotes", "Nowdoc is faster", "Heredoc can only be used for SQL", "There is no difference"],
    "correct_answer": "Heredoc parses variables; Nowdoc treats the string literally",
    "explanation": "Heredoc (`<<<EOT ... EOT`) is like double quotes - variables are parsed. Nowdoc (`<<<'EOT' ... EOT`) is like single quotes - everything is literal. Both are useful for multi-line strings, especially SQL queries or HTML templates."
  },
  {
    "id": 16,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Error Handling",
    "question": "Fill in the blank to correctly catch an exception in PHP.",
    "code_snippet": "try {\n    // some code\n} _______ (Exception $e) {\n    echo $e->getMessage();\n}",
    "options": ["catch", "except", "handle", "error"],
    "correct_answer": "catch",
    "explanation": "PHP uses try-catch blocks for exception handling. The `catch` block receives the Exception object, which provides methods like `getMessage()`, `getCode()`, and `getTrace()` for debugging."
  },
  {
    "id": 17,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP 8 Match Expression",
    "question": "How does the `match` expression in PHP 8 differ from `switch`?",
    "code_snippet": null,
    "options": ["`match` returns a value and uses strict comparison; `switch` doesn't return a value and uses loose comparison", "`match` is slower", "`switch` is deprecated", "They are identical"],
    "correct_answer": "`match` returns a value and uses strict comparison; `switch` doesn't return a value and uses loose comparison",
    "explanation": "`match` is an expression that returns a value and uses `===` (strict comparison). It's more concise and safer than `switch`. Example: `$status = match($code) { 200 => 'ok', 404 => 'not found' };`"
  },
  {
    "id": 18,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP 8 Named Arguments",
    "question": "What is the benefit of Named Arguments in PHP 8?",
    "code_snippet": null,
    "options": ["They make functions run faster", "They allow you to pass arguments by parameter name instead of position, improving readability and allowing you to skip optional parameters", "They are required for all functions", "They only work with arrays"],
    "correct_answer": "They allow you to pass arguments by parameter name instead of position",
    "explanation": "Instead of `htmlspecialchars($string, ENT_QUOTES, 'UTF-8')`, you can write `htmlspecialchars($string, encoding: 'UTF-8')`. This makes code more readable and lets you skip optional parameters without passing defaults."
  },
  {
    "id": 19,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP 8 Constructor Property Promotion",
    "question": "What does Constructor Property Promotion in PHP 8 allow you to do?",
    "code_snippet": null,
    "options": ["Promote private properties to public", "Declare and initialize class properties directly in the constructor parameters, reducing boilerplate code", "Automatically generate getters and setters", "Promote methods to static"],
    "correct_answer": "Declare and initialize class properties directly in the constructor parameters",
    "explanation": "Instead of declaring properties and then assigning them in the constructor, you can do: `public function __construct(public string $name, private int $age) {}`. This drastically reduces boilerplate code."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've covered PHP syntax, arrays, superglobals, and modern PHP 8 features. What is the core philosophy of modern PHP development?",
    "code_snippet": null,
    "options": ["Write the shortest code possible", "Write clean, type-safe, secure code using modern PHP 8+ features, prepared statements for database safety, and proper error handling", "Avoid using functions", "Only use procedural code"],
    "correct_answer": "Write clean, type-safe, secure code using modern PHP 8+ features, prepared statements, and proper error handling",
    "explanation": "Modern PHP (8+) is a strongly-typed, object-oriented language. The days of messy, insecure PHP are over. Use type hints, prepared statements, namespaces, and modern syntax to write professional, maintainable, and secure applications."
  }
]
[
  {
    "id": 21,
    "level": "beginner",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Classes and Objects",
    "question": "How do you instantiate (create) a new object from a class named `User` in PHP?",
    "code_snippet": null,
    "options": ["`$user = new User();`", "`$user = User::create();`", "`$user = object(User);`", "`$user = User();`"],
    "correct_answer": "`$user = new User();`",
    "explanation": "The `new` keyword is used to create an instance of a class. It allocates memory for the object and calls the class's `__construct()` method if one is defined."
  },
  {
    "id": 22,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Visibility Modifiers",
    "question": "What is the difference between `public`, `protected`, and `private` visibility in PHP classes?",
    "code_snippet": null,
    "options": ["Public is accessible everywhere; protected is accessible only within the class and its subclasses; private is accessible ONLY within the defining class", "Private is accessible everywhere; protected is only in the class; public is only in subclasses", "They are just comments and do nothing", "Protected is for static methods only"],
    "correct_answer": "Public is accessible everywhere; protected is accessible only within the class and its subclasses; private is accessible ONLY within the defining class",
    "explanation": "Encapsulation is a core OOP principle. Use `private` for internal state that shouldn't be touched, `protected` for state that child classes need to inherit and modify, and `public` for the API your object exposes to the outside world."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Static Methods and Properties",
    "question": "How do you call a static method named `format` on a class named `StringHelper` without creating an instance of the class?",
    "code_snippet": null,
    "options": ["`StringHelper->format()`", "`StringHelper::format()`", "`static::format()`", "`$StringHelper::format()`"],
    "correct_answer": "`StringHelper::format()`",
    "explanation": "The `::` (Scope Resolution Operator) is used to access static members. Static methods belong to the class itself, not to any specific object instance, meaning they cannot access `$this`."
  },
  {
    "id": 24,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Inheritance",
    "question": "Fill in the blank to correctly make the `Admin` class inherit from the `User` class.",
    "code_snippet": "class Admin _______ User {\n    // ...\n}",
    "options": ["implements", "extends", "inherits", "uses"],
    "correct_answer": "extends",
    "explanation": "PHP uses the `extends` keyword for class inheritance. An `Admin` class will inherit all `public` and `protected` properties and methods from the `User` class. PHP only supports single inheritance (a class can only extend one parent)."
  },
  {
    "id": 25,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Abstract Classes",
    "question": "What is the primary purpose of an `abstract` class in PHP?",
    "code_snippet": null,
    "options": ["To make the class run faster", "To define a base class that cannot be instantiated directly and may contain abstract methods that child classes MUST implement", "To prevent a class from being inherited", "To make all methods static"],
    "correct_answer": "To define a base class that cannot be instantiated directly and may contain abstract methods that child classes MUST implement",
    "explanation": "Abstract classes are templates. You cannot do `new Animal()` if `Animal` is abstract. You must create a `Dog` or `Cat` class that extends it. It allows you to enforce a contract while still providing shared, concrete implementation details."
  },
  {
    "id": 26,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Interfaces",
    "question": "How does an `interface` differ from an `abstract class` in PHP?",
    "code_snippet": null,
    "options": ["Interfaces can contain concrete method implementations; abstract classes cannot", "Interfaces define a strict contract of method signatures with NO implementation details, and a class can implement MULTIPLE interfaces", "Abstract classes can be instantiated; interfaces cannot", "There is no difference"],
    "correct_answer": "Interfaces define a strict contract of method signatures with NO implementation details, and a class can implement MULTIPLE interfaces",
    "explanation": "Because PHP only allows single inheritance (`extends`), interfaces (`implements`) are crucial for achieving multiple inheritance of type. A class can be both a `Serializable` and a `Jsonable`."
  },
  {
    "id": 27,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Traits",
    "question": "What problem do `traits` solve in PHP's OOP model?",
    "code_snippet": null,
    "options": ["They allow multiple inheritance of state and behavior, enabling horizontal code reuse across unrelated classes", "They replace the need for interfaces", "They make private properties public", "They automatically generate database migrations"],
    "correct_answer": "They allow multiple inheritance of state and behavior, enabling horizontal code reuse across unrelated classes",
    "explanation": "If a `Bird` and an `Airplane` both need a `fly()` method, they don't share a common ancestor. You can create a `Flyable` trait and `use` it in both classes, injecting the method directly into their composition."
  },
  {
    "id": 28,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Magic Methods (__get, __set)",
    "question": "When are the magic methods `__get($name)` and `__set($name, $value)` triggered in a PHP class?",
    "code_snippet": null,
    "options": ["When any property is accessed", "When attempting to read or write to inaccessible or non-existent properties", "When the object is serialized", "When the object is destroyed"],
    "correct_answer": "When attempting to read or write to inaccessible or non-existent properties",
    "explanation": "These methods enable 'overloading' in PHP. They are commonly used to create dynamic properties, implement virtual attributes, or enforce strict data validation before assigning a value to a private property."
  },
  {
    "id": 29,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "code-fill-in-blank",
    "topic": "Namespaces",
    "question": "Fill in the blank to correctly declare a namespace for a class to prevent naming collisions.",
    "code_snippet": "_______ App\\Models;\n\nclass User {\n    // ...\n}",
    "options": ["namespace", "package", "module", "import"],
    "correct_answer": "namespace",
    "explanation": "Namespaces group related classes and prevent conflicts. If you have a `User` class for your app, and a third-party library also has a `User` class, namespaces (`App\\Models\\User` vs `Library\\Auth\\User`) keep them completely separate."
  },
  {
    "id": 30,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Autoloading (PSR-4)",
    "question": "What is the purpose of an autoloader (like Composer's PSR-4 autoloader) in modern PHP?",
    "code_snippet": null,
    "options": ["To automatically compile PHP to machine code", "To automatically load class files only when they are first referenced, eliminating the need for manual `require` or `include` statements", "To automatically connect to the database", "To automatically format the code"],
    "explanation": "In the past, you had to `require_once` every file at the top of your script. PSR-4 maps namespaces to directory structures. When you call `new App\\Models\\User()`, the autoloader automatically finds and includes `src/Models/User.php`."
  },
  {
    "id": 31,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Composer",
    "question": "What is the role of the `composer.json` file and the `vendor/` directory in a PHP project?",
    "code_snippet": null,
    "options": ["`composer.json` stores database credentials; `vendor/` stores logs", "`composer.json` defines project metadata and dependencies; `vendor/` contains the downloaded third-party libraries and the autoloader", "They are used for frontend CSS compilation", "They are legacy files no longer used in modern PHP"],
    "correct_answer": "`composer.json` defines project metadata and dependencies; `vendor/` contains the downloaded libraries and the autoloader",
    "explanation": "Composer is the undisputed standard for PHP dependency management. It resolves version constraints, downloads packages from Packagist, and generates the `vendor/autoload.php` file that bootstraps your entire application's classes."
  },
  {
    "id": 32,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Late Static Binding",
    "question": "In PHP, what is the difference between using `self::` and `static::` inside a class method?",
    "code_snippet": null,
    "options": ["They are exactly the same", "`self::` refers to the class where the method is defined; `static::` refers to the class that actually called the method at runtime (Late Static Binding)", "`static::` is for static variables only", "`self::` is deprecated"],
    "correct_answer": "`self::` refers to the class where the method is defined; `static::` refers to the class that actually called the method at runtime",
    "explanation": "If a parent class has a method using `self::class`, it will always return the Parent's name, even if called on a Child class. Using `static::class` resolves to the Child class, enabling powerful polymorphic behavior in static contexts."
  },
  {
    "id": 33,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Final Classes and Methods",
    "question": "What happens if you add the `final` keyword to a class or a method in PHP?",
    "code_snippet": null,
    "options": ["It makes the class run in production mode", "It prevents the class from being inherited, or the method from being overridden by child classes", "It makes the method static", "It encrypts the class"],
    "correct_answer": "It prevents the class from being inherited, or the method from being overridden by child classes",
    "explanation": "`final` is used to enforce design constraints and protect critical logic. For example, a `Singleton` base class is often marked `final` to prevent subclasses from breaking the singleton pattern."
  },
  {
    "id": 34,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP 8.1 Readonly Properties",
    "question": "What does the `readonly` modifier do when applied to a class property in PHP 8.1?",
    "code_snippet": null,
    "options": ["It makes the property static", "It allows the property to be written to exactly once (usually in the constructor) and never modified again, ensuring immutable state", "It hides the property from var_dump()", "It automatically generates a setter method"],
    "correct_answer": "It allows the property to be written to exactly once and never modified again, ensuring immutable state",
    "explanation": "Readonly properties are a game-changer for Data Transfer Objects (DTOs) and Value Objects. Once the constructor sets the value, any subsequent attempt to modify it throws an `Error`, guaranteeing data integrity."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP 8.1 Enums",
    "question": "How do 'Backed Enums' in PHP 8.1 differ from standard Enums?",
    "code_snippet": null,
    "options": ["Backed Enums can be serialized to the database; standard Enums cannot", "Backed Enums are associated with a scalar value (int or string), allowing them to be easily persisted or mapped to database columns", "Backed Enums can contain methods; standard Enums cannot", "There is no difference"],
    "correct_answer": "Backed Enums are associated with a scalar value (int or string), allowing them to be easily persisted or mapped to database columns",
    "explanation": "A standard enum (`enum Status { case Active; }`) is just a unique type. A backed enum (`enum Status: string { case Active = 'active'; }`) has an underlying value, making it trivial to save to a database or return in a JSON API."
  },
  {
    "id": 36,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP 8.1 Fibers",
    "question": "What is a `Fiber` in PHP 8.1, and what problem does it solve?",
    "code_snippet": null,
    "options": ["A tool for encrypting data", "A lightweight, cooperative multitasking primitive that allows execution to be paused and resumed, forming the basis for async PHP frameworks", "A type of database connection", "A CSS framework for PHP"],
    "correct_answer": "A lightweight, cooperative multitasking primitive that allows execution to be paused and resumed",
    "explanation": "Fibers don't make PHP multi-threaded, but they allow frameworks (like Swoole or ReactPHP) to pause a function waiting for a database query, do other work, and resume the function later, enabling high-concurrency async I/O."
  },
  {
    "id": 37,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "PHP-FPM (FastCGI Process Manager)",
    "question": "In a modern production environment (e.g., Nginx + PHP), what is the role of PHP-FPM?",
    "code_snippet": null,
    "options": ["It compiles PHP to C++", "It acts as a FastCGI process manager, maintaining a pool of worker processes that handle PHP execution, completely separating the web server from the PHP runtime", "It manages the MySQL database", "It is a frontend framework"],
    "explanation": "Nginx is incredibly fast at serving static files and handling network connections, but it cannot execute PHP. Nginx passes `.php` requests via FastCGI to PHP-FPM, which manages the heavy lifting of booting the PHP interpreter and executing the code."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Dependency Injection",
    "question": "What is 'Constructor Injection' in PHP OOP?",
    "code_snippet": null,
    "options": ["Passing HTML into a PHP file", "Passing required object dependencies into a class via its constructor parameters, rather than creating them internally with `new`", "Injecting JavaScript into the page", "Using `$_POST` to inject data"],
    "correct_answer": "Passing required object dependencies into a class via its constructor parameters",
    "explanation": "Instead of `class Mailer { public function __construct() { $this->smtp = new SmtpClient(); } }`, you do `public function __construct(private SmtpClient $smtp)`. This decouples the classes and makes unit testing with mock objects incredibly easy."
  },
  {
    "id": 39,
    "level": "intermediate",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Anonymous Classes",
    "question": "When would you use an Anonymous Class in PHP?",
    "code_snippet": null,
    "options": ["When you need to create a permanent, reusable framework component", "When you need a simple, one-off object (often for testing or passing a specific implementation to a method) without formally defining a named class file", "Anonymous classes are deprecated", "They are used exclusively for database connections"],
    "correct_answer": "When you need a simple, one-off object without formally defining a named class file",
    "explanation": "Syntax: `$logger = new class implements LoggerInterface { ... };`. They are perfect for creating mock objects in PHPUnit tests or providing a quick, localized implementation of an interface without polluting your namespace."
  },
  {
    "id": 40,
    "level": "advanced",
    "module_id": "php_mod_01_fundamentals",
    "module_name": "PHP Fundamentals & Modern Syntax",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (The OOP Philosophy)",
    "question": "You've covered Classes, Traits, Enums, Fibers, and Composer. What is the ultimate philosophy of modern PHP Object-Oriented Design?",
    "code_snippet": null,
    "options": ["Put as much logic as possible into a single massive class", "Design small, focused, loosely coupled classes that communicate via interfaces, rely on dependency injection, and leverage PHP 8+ features for strict type safety and immutability", "Avoid using namespaces", "Only use procedural functions for speed"],
    "correct_answer": "Design small, focused, loosely coupled classes that communicate via interfaces, rely on DI, and leverage PHP 8+ features for strict type safety",
    "explanation": "Modern PHP is heavily inspired by Java and C# architecture. By embracing SOLID principles, strict typing, readonly states, and dependency injection, you build enterprise-grade applications that are testable, maintainable, and robust."
  }
]
