[
  {
    "id": 1,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "The Front Controller Pattern",
    "question": "What is the 'Front Controller' pattern, and how do modern PHP frameworks (like Laravel/Symfony) implement it?",
    "code_snippet": null,
    "options": ["Every URL maps to a separate physical PHP file", "All incoming HTTP requests are routed through a single entry point (e.g., `public/index.php`), which bootstraps the framework and dispatches the request to the appropriate controller", "It is a database design pattern", "It prevents users from accessing the API"],
    "correct_answer": "All incoming HTTP requests are routed through a single entry point (e.g., `public/index.php`)",
    "explanation": "Instead of having `about.php`, `contact.php`, and `user.php`, the web server (Nginx/Apache) is configured to send ALL requests to `index.php`. The framework's router then reads the URL and executes the correct PHP logic. This provides centralized security, bootstrapping, and routing."
  },
  {
    "id": 2,
    "level": "beginner",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "code-fill-in-blank",
    "topic": "Basic Routing",
    "question": "Fill in the blank to correctly define a GET route in Laravel that returns a simple string.",
    "code_snippet": "_______::get('/hello', function () {\n    return 'Hello World';\n});",
    "options": ["Route", "Router", "URL", "Path"],
    "correct_answer": "Route",
    "explanation": "The `Route` facade is the standard way to define HTTP endpoints in Laravel. You specify the HTTP verb (get, post, put, delete), the URI pattern, and the closure or controller action that handles it."
  },
  {
    "id": 3,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Route Parameters & Constraints",
    "question": "How do you enforce that a route parameter `{id}` must be a numeric integer in Laravel?",
    "code_snippet": null,
    "options": ["By casting it in the controller", "By chaining the `whereNumber('id')` or `where('id', '[0-9]+')` method to the route definition", "By using a POST request instead", "You cannot constrain parameters"],
    "correct_answer": "By chaining the `whereNumber('id')` or `where('id', '[0-9]+')` method to the route definition",
    "explanation": "Route constraints ensure that `/users/abc` returns a 404 Not Found, while `/users/123` successfully hits the controller. This prevents invalid data from ever reaching your business logic or database queries."
  },
  {
    "id": 4,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Middleware (Concept)",
    "question": "What is 'Middleware' in the context of a PHP framework's HTTP lifecycle?",
    "code_snippet": null,
    "options": ["A database ORM", "A filtering mechanism that intercepts HTTP requests entering the application and responses leaving it, allowing you to inspect, modify, or reject them", "A frontend CSS compiler", "A caching driver"],
    "explanation": "Middleware acts as a series of checkpoints. Before a request reaches your controller, it passes through middleware (e.g., 'Is the user authenticated?', 'Is the IP banned?', 'Add CORS headers?'). If a middleware rejects the request, it never reaches the controller."
  },
  {
    "id": 5,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "code-fill-in-blank",
    "topic": "Middleware Execution",
    "question": "Fill in the blank to correctly pass the request to the next middleware in the pipeline.",
    "code_snippet": "public function handle($request, Closure $next) {\n    if ($request->age < 18) {\n        return redirect('/home');\n    }\n    return _______($request);\n}",
    "options": ["$next", "next()", "continue()", "$request"],
    "correct_answer": "$next",
    "explanation": "The `$next` closure represents the rest of the application. Calling `$next($request)` passes the baton forward. If you return a response *before* calling `$next`, you short-circuit the pipeline (e.g., redirecting an unauthorized user)."
  },
  {
    "id": 6,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Controllers (Resource Controllers)",
    "question": "What is a 'Resource Controller' in Laravel, and what HTTP methods does it automatically map?",
    "code_snippet": null,
    "options": ["A controller that only handles database connections", "A controller that groups standard CRUD actions (index, create, store, show, edit, update, destroy) into a single class, mapping them to RESTful HTTP verbs", "A controller for frontend assets", "A deprecated feature"],
    "correct_answer": "A controller that groups standard CRUD actions into a single class, mapping them to RESTful HTTP verbs",
    "explanation": "Instead of writing 7 separate route definitions for a 'Post' resource, you use `Route::resource('posts', PostController::class)`. The framework automatically maps GET `/posts` to `index()`, POST `/posts` to `store()`, GET `/posts/{id}` to `show()`, etc."
  },
  {
    "id": 7,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Request Validation",
    "question": "What is the primary benefit of using a dedicated 'Form Request' class for validation instead of calling `$request->validate()` directly in the controller?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It separates validation logic from controller logic, keeping controllers thin, and allows the validation rules to be easily reused and unit-tested", "It bypasses CSRF protection", "It automatically saves the data to the database"],
    "correct_answer": "It separates validation logic from controller logic, keeping controllers thin and reusable",
    "explanation": "Controllers should only handle the HTTP request/response cycle. By moving validation rules, authorization checks, and custom error messages into a `StoreUserRequest` class, your controller's `store()` method becomes incredibly clean and focused purely on business logic."
  },
  {
    "id": 8,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "code-fill-in-blank",
    "topic": "JSON Responses",
    "question": "Fill in the blank to correctly return a JSON response with a 201 Created status code.",
    "code_snippet": "return _______()->json(['message' => 'Created'], 201);",
    "options": ["response", "return", "json", "http"],
    "correct_answer": "response",
    "explanation": "The `response()` helper function creates a Response factory instance. Chaining `->json()` automatically sets the `Content-Type: application/json` header and encodes the array into a JSON string."
  },
  {
    "id": 9,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "The Service Container (IoC)",
    "question": "What is the 'Service Container' (or Inversion of Control Container) in a PHP framework?",
    "code_snippet": null,
    "options": ["A Docker container", "A powerful tool for managing class dependencies and performing dependency injection, acting as the central registry for the application", "A database connection pool", "A frontend bundler"],
    "correct_answer": "A powerful tool for managing class dependencies and performing dependency injection",
    "explanation": "Instead of hardcoding `new Mailer()` inside your controllers, you type-hint `Mailer $mailer` in your constructor. The Service Container reads the type-hint, realizes it needs a Mailer, builds it (along with its own dependencies), and injects it automatically."
  },
  {
    "id": 10,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Service Providers",
    "question": "What is the role of a 'Service Provider' in Laravel/Symfony?",
    "code_snippet": null,
    "options": ["To provide third-party APIs", "To act as the central bootstrapping mechanism, binding classes into the Service Container and registering event listeners or routes", "To provide frontend CSS", "To manage user sessions"],
    "correct_answer": "To act as the central bootstrapping mechanism, binding classes into the Service Container",
    "explanation": "Service Providers are the bridge between your application and the framework. In their `register()` method, they tell the Container how to build specific classes. In their `boot()` method, they execute logic once all other providers have been loaded (like loading routes or view composers)."
  },
  {
    "id": 11,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Facades",
    "question": "What is a 'Facade' in Laravel, and what does it provide access to?",
    "code_snippet": null,
    "options": ["A frontend UI component", "A static-like interface to an underlying class resolved from the Service Container, providing syntactic sugar and testability", "A database migration tool", "A security firewall"],
    "correct_answer": "A static-like interface to an underlying class resolved from the Service Container",
    "explanation": "When you call `Cache::get('key')`, you aren't calling a static method. The `Cache` Facade intercepts the call, resolves the actual Cache Manager instance from the Service Container, and calls the method on it. This gives you the brevity of static calls with the testability of dependency injection."
  },
  {
    "id": 12,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Configuration & .env",
    "question": "Why should sensitive credentials (like database passwords or API keys) NEVER be hardcoded in your PHP framework's config files?",
    "code_snippet": null,
    "options": ["It makes the code slower", "They should be stored in the `.env` file and accessed via `env()` or `config()`, ensuring secrets are kept out of version control (Git) and can vary per environment", "PHP doesn't support hardcoded strings", "It violates PSR-4"],
    "correct_answer": "They should be stored in the `.env` file, ensuring secrets are kept out of version control",
    "explanation": "The `.env` file is excluded from Git via `.gitignore`. Your `config/database.php` file reads `env('DB_PASSWORD')`. This allows you to have one codebase but safely deploy it to dev, staging, and production with entirely different credentials."
  },
  {
    "id": 13,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Route Model Binding",
    "question": "What does 'Implicit Route Model Binding' do in Laravel?",
    "code_snippet": null,
    "options": ["It automatically validates the user's password", "It automatically injects the Eloquent Model instance directly into the controller route, based on the route parameter (e.g., `{user}` resolves to `User::find($id)`)", "It automatically generates the HTML form", "It encrypts the database connection"],
    "correct_answer": "It automatically injects the Eloquent Model instance directly into the controller route",
    "explanation": "Instead of `public function show($id) { $user = User::findOrFail($id); }`, you write `public function show(User $user)`. The framework sees the type-hint, grabs the `{user}` ID from the URL, queries the database, and injects the model. If it doesn't exist, it automatically returns a 404."
  },
  {
    "id": 14,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Route Groups",
    "question": "What is the primary purpose of wrapping routes in a 'Route Group'?",
    "code_snippet": null,
    "options": ["To encrypt the routes", "To apply shared attributes (like middleware, URL prefixes, or namespaces) to a large block of routes without repeating them on every single route", "To group them into a database table", "To hide them from the router"],
    "correct_answer": "To apply shared attributes to a large block of routes without repeating them",
    "explanation": "Instead of adding `->middleware('auth')` to 20 different routes, you wrap them in `Route::middleware('auth')->group(function () { ... })`. This keeps your routing file DRY (Don't Repeat Yourself) and highly organized."
  },
  {
    "id": 15,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Middleware Terminate",
    "question": "What is the purpose of the `terminate($request, $response)` method in a middleware class?",
    "code_snippet": null,
    "options": ["It forcefully crashes the server", "It allows you to execute tasks AFTER the response has already been sent to the user's browser, such as logging or saving session data", "It cancels the HTTP request", "It deletes the middleware"],
    "correct_answer": "It allows you to execute tasks AFTER the response has been sent to the user",
    "explanation": "Normally, middleware runs before the controller. But if you define a `terminate` method, the framework will call it at the very end of the lifecycle. This is perfect for heavy tasks like writing analytics logs, where you don't want the user to wait for the disk I/O to finish before seeing their page."
  },
  {
    "id": 16,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Artisan CLI",
    "question": "What is the primary function of the `artisan` command-line tool in a PHP framework?",
    "code_snippet": null,
    "options": ["To compile frontend CSS", "To provide a robust CLI for running database migrations, generating boilerplate code, clearing caches, and scheduling custom background tasks", "To manage Docker containers", "To format PHP code"],
    "correct_answer": "To provide a robust CLI for running migrations, generating code, and managing the app",
    "explanation": "Commands like `php artisan make:model Post`, `php artisan migrate`, and `php artisan route:list` are the backbone of developer productivity in Laravel. They eliminate manual file creation and provide safe, repeatable database schema management."
  },
  {
    "id": 17,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Exception Handling",
    "question": "In a modern PHP framework, where should you handle the rendering of custom error pages (like a 404 or 500 view)?",
    "code_snippet": null,
    "options": ["Inside every single controller", "In the global Exception Handler class (e.g., `app/Exceptions/Handler.php`), which catches unhandled exceptions and maps them to the correct HTTP response or view", "In the `.env` file", "In the database"],
    "correct_answer": "In the global Exception Handler class",
    "explanation": "The Exception Handler is the ultimate safety net. It intercepts any uncaught `Throwable`, checks if it's a validation error (422), a not found error (404), or a server crash (500), and renders the appropriate JSON or HTML response, ensuring the user never sees a raw PHP stack trace in production."
  },
  {
    "id": 18,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "CSRF Protection in Frameworks",
    "question": "How do modern PHP frameworks automatically protect POST/PUT/DELETE routes from CSRF attacks?",
    "code_snippet": null,
    "options": ["By requiring HTTPS", "By including a global middleware that verifies a `_token` hidden field in the form matches the token stored in the user's session", "By encrypting the database", "By disabling cookies"],
    "correct_answer": "By including a global middleware that verifies a `_token` hidden field matches the session token",
    "explanation": "The `VerifyCsrfToken` middleware runs on every state-changing request. If the request lacks a valid CSRF token (usually injected via `@csrf` in Blade templates or an `X-CSRF-TOKEN` header in AJAX), the middleware rejects it with a 419 Page Expired error."
  },
  {
    "id": 19,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Binding Interfaces to Implementations",
    "question": "Why is it a best practice to bind an Interface to a concrete Implementation in the Service Container (e.g., `$this->app->bind(PaymentGateway::class, StripeGateway::class)`)?",
    "code_snippet": null,
    "options": ["It makes the code run faster", "It allows you to type-hint the Interface in your controllers, making it trivial to swap the underlying implementation (e.g., from Stripe to PayPal) without changing any controller code", "It prevents memory leaks", "It encrypts the payment data"],
    "correct_answer": "It allows you to type-hint the Interface, making it trivial to swap implementations without changing controller code",
    "explanation": "This is the core of the Dependency Inversion Principle (the 'D' in SOLID). Your controller depends on the abstract `PaymentGateway` contract, not the concrete `StripeGateway`. If you switch providers, you only change ONE line of code in your Service Provider."
  },
  {
    "id": 20,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Part 1 Wrap-up",
    "question": "You've covered Routing, Middleware, the Service Container, and Providers. What is the core architectural benefit of using a modern PHP framework over raw PHP?",
    "code_snippet": null,
    "options": ["It makes the PHP engine run faster", "It enforces a structured, decoupled architecture (MVC) where routing, business logic, data access, and security are strictly separated, making the application testable and maintainable at scale", "It eliminates the need for a database", "It automatically writes unit tests"],
    "correct_answer": "It enforces a structured, decoupled architecture (MVC) where concerns are strictly separated",
    "explanation": "Raw PHP often leads to 'spaghetti code' where HTML, SQL, and business logic are mixed in one file. Frameworks force you to separate these concerns. The Router handles URLs, the Controller handles logic, the Model handles data, and Middleware handles security. This separation is what allows teams of 50 developers to work on the same codebase without breaking it."
  }
]
[
  {
    "id": 21,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "ORM (Active Record Pattern)",
    "question": "What design pattern does Laravel's Eloquent ORM primarily use, and what does it mean for the developer?",
    "code_snippet": null,
    "options": ["Data Mapper; it requires separate repository classes for every query", "Active Record; each model class corresponds to a database table, and each instance represents a row, with built-in methods for saving and deleting", "Singleton; it only allows one database connection", "Factory; it generates random database rows"],
    "correct_answer": "Active Record; each model class corresponds to a database table, and each instance represents a row",
    "explanation": "In the Active Record pattern, your `User` model has methods like `save()`, `delete()`, and `update()`. You interact with the database using object-oriented syntax (`$user->name = 'John'; $user->save();`) rather than writing raw SQL strings."
  },
  {
    "id": 22,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Mass Assignment Vulnerability",
    "question": "What is the 'Mass Assignment Vulnerability', and how do frameworks like Laravel prevent it using the `$fillable` property?",
    "code_snippet": null,
    "options": ["It allows hackers to upload viruses; `$fillable` scans files for malware", "It occurs when a user passes unexpected HTTP parameters (like `is_admin=1`) that overwrite sensitive database columns; `$fillable` explicitly whitelists which columns can be mass-assigned", "It slows down the database; `$fillable` caches the columns", "It encrypts the database; `$fillable` holds the encryption keys"],
    "correct_answer": "It occurs when a user passes unexpected HTTP parameters that overwrite sensitive columns; `$fillable` explicitly whitelists allowed columns",
    "explanation": "If you do `User::create($request->all())`, a malicious user could add `is_admin=true` to the form data. By defining `protected $fillable = ['name', 'email'];` on the model, the ORM silently ignores any other fields, protecting your database."
  },
  {
    "id": 23,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Database Migrations",
    "question": "What is the primary purpose of 'Database Migrations' in a PHP framework?",
    "code_snippet": null,
    "options": ["To move the database to a different server", "To act as version control for your database schema, allowing teams to define, share, and apply table structures using PHP code instead of raw SQL", "To backup the database to S3", "To translate SQL into NoSQL"],
    "correct_answer": "To act as version control for your database schema, allowing teams to define and share table structures using PHP code",
    "explanation": "Instead of manually running `CREATE TABLE` in phpMyAdmin, you write a migration file (`php artisan make:migration create_users_table`). This file is committed to Git, ensuring every developer and the production server can build the exact same database schema by running `php artisan migrate`."
  },
  {
    "id": 24,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "The N+1 Query Problem",
    "question": "What is the 'N+1 Query Problem' in ORMs, and how does Eager Loading (e.g., `User::with('posts')->get()`) solve it?",
    "code_snippet": null,
    "options": ["It makes queries run 1 second slower; Eager Loading compresses the SQL", "It occurs when looping through models triggers a separate database query for each relationship; Eager Loading fetches all related models in just two highly optimized queries", "It prevents SQL injection; Eager Loading encrypts the data", "It is a frontend rendering issue; Eager Loading caches the HTML"],
    "correct_answer": "It occurs when looping through models triggers a separate query for each relationship; Eager Loading fetches all related models in just two queries",
    "explanation": "If you fetch 100 users and loop through them to get their posts, a lazy ORM executes 1 query for users + 100 queries for posts (101 total). Eager Loading (`with('posts')`) tells the ORM to execute `SELECT * FROM users` and then `SELECT * FROM posts WHERE user_id IN (...)`, reducing it to exactly 2 queries."
  },
  {
    "id": 25,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Many-to-Many Relationships (Pivot Tables)",
    "question": "In a Many-to-Many relationship (e.g., Users and Roles), what is a 'Pivot Table'?",
    "code_snippet": null,
    "options": ["A frontend CSS layout", "An intermediate junction table that holds the foreign keys of both related models, allowing a user to have multiple roles and a role to have multiple users", "A database backup file", "A caching mechanism"],
    "correct_answer": "An intermediate junction table that holds the foreign keys of both related models",
    "explanation": "Because relational databases cannot directly link one row to multiple rows in another table, you create a `role_user` pivot table containing `user_id` and `role_id`. The ORM uses this table behind the scenes to resolve `belongsToMany()` relationships."
  },
  {
    "id": 26,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Soft Deletes",
    "question": "What does the 'Soft Deletes' feature do in an ORM?",
    "code_snippet": null,
    "options": ["It deletes the database schema", "Instead of permanently removing the row, it sets a `deleted_at` timestamp; the ORM automatically hides these records from queries, but they can be restored", "It compresses the database", "It moves the data to a different server"],
    "correct_answer": "Instead of permanently removing the row, it sets a `deleted_at` timestamp; the ORM hides these records but allows restoration",
    "explanation": "Soft deletes are crucial for data integrity and audit trails. If a user accidentally deletes an invoice, you can easily query `Invoice::withTrashed()->restore()`. The data remains in the database, but standard queries ignore it."
  },
  {
    "id": 27,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "API Resources (Transformers)",
    "question": "Why should you use 'API Resources' (or Transformers) instead of returning Eloquent models directly as JSON?",
    "code_snippet": null,
    "options": ["It makes the database faster", "It allows you to format the data, hide sensitive fields (like passwords), and control the exact JSON structure returned to the client, decoupling the database schema from the API response", "It encrypts the JSON", "It automatically validates the user's input"],
    "correct_answer": "It allows you to format data, hide sensitive fields, and control the exact JSON structure, decoupling the DB schema from the API",
    "explanation": "Returning a raw model might accidentally expose `password_hash` or internal database IDs. An API Resource acts as a transformation layer, ensuring your API contract remains stable even if your internal database schema changes."
  },
  {
    "id": 28,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Authentication Guards",
    "question": "What is an 'Authentication Guard' in a PHP framework?",
    "code_snippet": null,
    "options": ["A firewall rule", "A mechanism that defines how users are authenticated for each request (e.g., using Session cookies for web UIs, or Token-based auth for APIs)", "A database encryption tool", "A frontend CSS class"],
    "correct_answer": "A mechanism that defines how users are authenticated for each request",
    "explanation": "Frameworks allow multiple guards. You might use the `web` guard (session-based) for your admin dashboard, and the `api` guard (Sanctum/JWT token-based) for your mobile app, all within the same application."
  },
  {
    "id": 29,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Laravel Sanctum (API Auth)",
    "question": "How does Laravel Sanctum handle authentication for a Single Page Application (SPA) versus a mobile app?",
    "code_snippet": null,
    "options": ["It uses the same method for both", "It uses secure, HTTP-only session cookies for SPAs (since they share the same domain), and issues long-lived API tokens for mobile apps or third-party clients", "It only supports mobile apps", "It requires a third-party OAuth server"],
    "correct_answer": "It uses secure session cookies for SPAs, and issues API tokens for mobile apps or third-party clients",
    "explanation": "Sanctum simplifies API auth by providing a lightweight, secure cookie-based system for SPAs (avoiding the complexity of JWTs for first-party apps) while still offering robust Bearer token generation for external API consumers."
  },
  {
    "id": 30,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Queues (Concept)",
    "question": "What is the primary purpose of 'Queues' in a web application?",
    "code_snippet": null,
    "options": ["To sort database results", "To defer the processing of time-consuming tasks (like sending emails or generating PDFs) to a background worker, keeping the HTTP response fast", "To queue frontend CSS files", "To manage user sessions"],
    "correct_answer": "To defer time-consuming tasks to a background worker, keeping the HTTP response fast",
    "explanation": "If sending an email takes 3 seconds, doing it synchronously forces the user to stare at a loading spinner for 3 seconds. By dispatching an `SendEmailJob` to a queue, the controller returns a 200 OK in 50ms, and a background worker handles the email later."
  },
  {
    "id": 31,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Queue Drivers",
    "question": "What is the role of a 'Queue Driver' (like Redis, Database, or SQS)?",
    "code_snippet": null,
    "options": ["It compiles the PHP code", "It acts as the storage and messaging system that holds the serialized jobs until a worker process is ready to execute them", "It connects to the frontend", "It encrypts the database"],
    "correct_answer": "It acts as the storage and messaging system that holds the serialized jobs until a worker executes them",
    "explanation": "When you dispatch a job, it gets serialized and pushed to the driver. Redis is the most popular choice because it is blazing fast and supports advanced features like delayed jobs and rate limiting. The Database driver is great for simple setups as it just stores jobs in a SQL table."
  },
  {
    "id": 32,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Failed Jobs",
    "question": "What happens if a background job throws an exception and fails permanently?",
    "code_snippet": null,
    "options": ["The entire server crashes", "The framework moves the job payload to a `failed_jobs` table, allowing developers to inspect the error and manually retry it later", "It automatically deletes the user's account", "It sends an email to the CEO"],
    "correct_answer": "The framework moves the job payload to a `failed_jobs` table, allowing inspection and manual retry",
    "explanation": "Queues are designed to be resilient. If an external API is temporarily down, the job fails. Once the API is back up, an admin can run `php artisan queue:retry all` to reprocess the failed jobs without losing any data."
  },
  {
    "id": 33,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "code-fill-in-blank",
    "question": "Fill in the blank to correctly use the framework's caching method that retrieves a value from the cache, or executes a closure to generate and store it if it doesn't exist.",
    "code_snippet": "$users = Cache::_______('top_users', 3600, function () {\n    return User::top()->get();\n});",
    "options": ["get", "remember", "fetch", "store"],
    "correct_answer": "remember",
    "explanation": "`Cache::remember($key, $seconds, $closure)` is the ultimate caching pattern. It checks if `top_users` exists. If yes, it returns it instantly. If no, it runs the database query, saves the result for 3600 seconds, and returns it."
  },
  {
    "id": 34,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Task Scheduling",
    "question": "How do modern PHP frameworks handle recurring background tasks (like sending a weekly newsletter) without requiring the developer to manually edit the server's `crontab`?",
    "code_snippet": null,
    "options": ["They don't; you must use a third-party service", "They provide a fluent Task Scheduling API (e.g., `$schedule->job()->weekly()`) in a central Kernel file, requiring only ONE cron entry on the server to run the scheduler every minute", "They use frontend JavaScript timers", "They rely on database triggers"],
    "correct_answer": "They provide a fluent Task Scheduling API in a central Kernel file, requiring only ONE cron entry on the server",
    "explanation": "Instead of managing 20 different crontab entries, you add one entry that runs `php artisan schedule:run` every minute. The framework's scheduler checks its internal schedule and executes the correct PHP commands at the right times."
  },
  {
    "id": 35,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Events & Listeners",
    "question": "What is the 'Event and Listener' pattern, and how does it promote decoupled architecture?",
    "code_snippet": null,
    "options": ["It is a frontend CSS framework", "It allows you to raise an 'Event' (e.g., `UserRegistered`) and have multiple independent 'Listeners' react to it (e.g., `SendWelcomeEmail`, `UpdateAnalytics`), without the controller knowing they exist", "It encrypts database events", "It manages HTTP routing"],
    "correct_answer": "It allows you to raise an Event and have multiple independent Listeners react to it, without the controller knowing they exist",
    "explanation": "Instead of a massive controller that sends emails, updates analytics, and notifies admins all at once, the controller just fires `event(new UserRegistered($user))`. The framework handles the rest. This makes the codebase incredibly modular and easy to test."
  },
  {
    "id": 36,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Database Factories & Seeders",
    "question": "What is the purpose of 'Factories' and 'Seeders' in a PHP framework's testing ecosystem?",
    "code_snippet": null,
    "options": ["To compile production code", "Factories generate realistic fake data (using Faker) for models, and Seeders populate the database with this test data, enabling robust automated testing and local development", "To backup the database", "To format JSON responses"],
    "correct_answer": "Factories generate realistic fake data, and Seeders populate the database with it for testing and local development",
    "explanation": "Instead of manually inserting 'John Doe' into the database to test your UI, you write a Factory that generates 50 unique users with realistic names, emails, and avatars. Running `php artisan db:seed` instantly populates your local environment."
  },
  {
    "id": 37,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Global Scopes",
    "question": "What does a 'Global Scope' do in an Eloquent model?",
    "code_snippet": null,
    "options": ["It makes the model available globally via a Facade", "It automatically applies a specific query constraint (like `WHERE tenant_id = X` or `WHERE is_active = 1`) to EVERY query made on that model", "It encrypts the model", "It deletes the model globally"],
    "correct_answer": "It automatically applies a specific query constraint to EVERY query made on that model",
    "explanation": "Global Scopes are perfect for multi-tenant applications or soft deletes. You write the scope once, and you never have to worry about accidentally forgetting to add `WHERE tenant_id = 1` to a query and leaking another tenant's data."
  },
  {
    "id": 38,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Accessors & Mutators",
    "question": "What are 'Accessors' and 'Mutators' in an ORM model?",
    "code_snippet": null,
    "options": ["Database migration tools", "Methods that automatically format data when retrieving it from the database (Accessor) or automatically format it before saving it to the database (Mutator)", "Authentication guards", "API routing tools"],
    "correct_answer": "Methods that automatically format data when retrieving it (Accessor) or before saving it (Mutator)",
    "explanation": "An accessor can automatically convert a `first_name` and `last_name` column into a `full_name` attribute. A mutator can automatically hash a password or convert a string to lowercase before it is ever saved to the database, keeping your controllers clean."
  },
  {
    "id": 39,
    "level": "intermediate",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Rate Limiting (Throttling)",
    "question": "How do modern PHP frameworks protect APIs from abuse and DDoS attacks?",
    "code_snippet": null,
    "options": ["By disabling the database", "By applying Rate Limiting middleware (e.g., `throttle:60,1`), which tracks the user's IP or API token and returns a 429 Too Many Requests status if they exceed the limit", "By requiring a CAPTCHA on every route", "By encrypting the API responses"],
    "correct_answer": "By applying Rate Limiting middleware, which tracks the user and returns a 429 status if they exceed the limit",
    "explanation": "Frameworks use the cache driver to track requests per minute. If a user exceeds the limit, the middleware intercepts the request and returns a 429 response with a `Retry-After` header, protecting your server's CPU and database from being overwhelmed."
  },
  {
    "id": 40,
    "level": "advanced",
    "module_id": "php_mod_02_frameworks",
    "module_name": "Modern PHP Frameworks & APIs",
    "type": "conceptual",
    "topic": "Part 2 Wrap-up (The Ecosystem)",
    "question": "You've covered Eloquent, Queues, Caching, Events, and API Auth. What is the ultimate power of a modern PHP framework ecosystem?",
    "code_snippet": null,
    "options": ["It replaces the need for developers", "It provides a cohesive, standardized set of tools for every aspect of backend development, allowing developers to focus entirely on business logic rather than reinventing infrastructure plumbing", "It makes the PHP engine run in C++", "It automatically generates the frontend UI"],
    "correct_answer": "It provides a cohesive, standardized set of tools for every aspect of backend development, allowing developers to focus entirely on business logic",
    "explanation": "When you need a queue, you don't write a custom Redis worker. When you need caching, you don't write a custom file-locking mechanism. The framework provides battle-tested, secure, and optimized solutions for everything. This is what allows a single PHP developer to build in a week what used to take a team a month."
  }
]
